#!/bin/sh

BASEDIR=$(dirname "$0")

git diff --cached --name-only | grep -E '.*\.(c|cpp|h|hpp)$' | while read FILE; do
    if [[ -f $FILE ]]; then
        echo "formatting '$FILE'"
        clang-format -i $FILE
    fi
done
