language: python

sudo: required
dist: trusty

cache: 
  - ccache

install:
  - mkdir -p ~/cmake
  - mkdir -p ~/work
  
  - remote_branch=${remote_ref#refs/heads/}
  
  - cd ~/work
  - git clone --branch="$remote_branch" https://github.com/AnyDSL/anydsl.git
  
  - cd anydsl
  - bash scripts/install_cmake.sh ~/cmake/
  - export PATH=~/cmake/bin:~/work/anydsl/llvm_install/bin:~/work/anydsl/impala/build/bin:$PATH
  
  - cp config.sh.template config.sh
  - sed -i 's/BRANCH:=master/BRANCH:=$remote_branch/g' config.sh
  - sed -i 's/HTTPS:=false/HTTPS:=true/g' config.sh
  - cat config.sh
  
  - bash setup_travis.sh

script:
  - cd impala/test/
  - python run_tests.py .
