language: python

sudo: required
dist: trusty

cache: 
  - ccache

install:
  - mkdir -p ~/cmake
  - mkdir -p ~/work
  
  - cd ~/work
  - git clone --branch=master_llvm36 https://github.com/AnyDSL/anydsl.git
  
  - cd anydsl
  - bash scripts/install_cmake.sh ~/cmake/
  - export PATH=~/cmake/bin:~/work/anydsl/llvm_install/bin:~/work/anydsl/impala/build/bin:$PATH
  - echo $PATH
  
  - cp config.sh.template config.sh
  - sed -i 's/BRANCH:=master/BRANCH:=master_llvm36/g' config.sh
  - sed -i 's/HTTPS:=false/HTTPS:=true/g' config.sh
  - cat config.sh
  
  - bash setup_travis.sh

script:
  - clang --version
  - cmake --version
