language: python

before_install: git clone --branch=master_llvm36 https://github.com/AnyDSL/anydsl.git

cache: 
  - ccache

install:
  - mkdir -p ~/bin/
  
  - cd anydsl
  - bash scripts/install_cmake.sh ~/bin/
  - PATH=~/bin/:/home/travis/AnyDSL/thorin/anydsl/llvm_install/:$PATH
  
  - cp config.sh.template config.sh
  - sed -i 's/BRANCH:=master/BRANCH:=master_llvm36/g' config.sh
  - sed -i 's/HTTPS:=false/HTTPS:=true/g' config.sh
  - cat config.sh
  
  - bash setup_travis.sh

script:
  - clang --version
  - cmake --version
