language: python

before_install: git clone https://github.com/AnyDSL/travis-ci.git

cache: ccache

install:
  - travis-ci/install.sh impala
  - travis-ci/build.sh
  - export PATH=$PATH:$PWD/../llvm_install/bin:$PWD/../impala/build/bin

script:
  - travis-ci/run.sh
