language: python

before_install: git clone --branch=master_llvm36 https://github.com/AnyDSL/anydsl.git

cache: ccache

install:
  - mkdir -p ~/bin/
  
  - cd anydsl
  - bash scripts/install_cmake.sh ~/bin/
  - export PATH=~/bin/:$PATH
  
  - bash setup_travis.sh

script:
  - clang --version
  - cmake --version
