var annotated_dup =
[
    [ "automaton", "namespaceautomaton.html", [
      [ "AutomatonBase", "classautomaton_1_1AutomatonBase.html", "classautomaton_1_1AutomatonBase" ],
      [ "DFANode", "classautomaton_1_1DFANode.html", "classautomaton_1_1DFANode" ],
      [ "DFA", "classautomaton_1_1DFA.html", "classautomaton_1_1DFA" ],
      [ "NFANode", "classautomaton_1_1NFANode.html", "classautomaton_1_1NFANode" ],
      [ "NFA", "classautomaton_1_1NFA.html", "classautomaton_1_1NFA" ],
      [ "RangeCompare", "structautomaton_1_1RangeCompare.html", "structautomaton_1_1RangeCompare" ]
    ] ],
    [ "mim", "namespacemim.html", [
      [ "ast", "namespacemim_1_1ast.html", [
        [ "AnnexInfo", "structmim_1_1ast_1_1AnnexInfo.html", "structmim_1_1ast_1_1AnnexInfo" ],
        [ "AST", "classmim_1_1ast_1_1AST.html", "classmim_1_1ast_1_1AST" ],
        [ "Node", "classmim_1_1ast_1_1Node.html", "classmim_1_1ast_1_1Node" ],
        [ "Expr", "classmim_1_1ast_1_1Expr.html", "classmim_1_1ast_1_1Expr" ],
        [ "Decl", "classmim_1_1ast_1_1Decl.html", "classmim_1_1ast_1_1Decl" ],
        [ "ValDecl", "classmim_1_1ast_1_1ValDecl.html", "classmim_1_1ast_1_1ValDecl" ],
        [ "Ptrn", "classmim_1_1ast_1_1Ptrn.html", "classmim_1_1ast_1_1Ptrn" ],
        [ "ErrorPtrn", "classmim_1_1ast_1_1ErrorPtrn.html", "classmim_1_1ast_1_1ErrorPtrn" ],
        [ "IdPtrn", "classmim_1_1ast_1_1IdPtrn.html", "classmim_1_1ast_1_1IdPtrn" ],
        [ "GrpPtrn", "classmim_1_1ast_1_1GrpPtrn.html", "classmim_1_1ast_1_1GrpPtrn" ],
        [ "AliasPtrn", "classmim_1_1ast_1_1AliasPtrn.html", "classmim_1_1ast_1_1AliasPtrn" ],
        [ "TuplePtrn", "classmim_1_1ast_1_1TuplePtrn.html", "classmim_1_1ast_1_1TuplePtrn" ],
        [ "ErrorExpr", "classmim_1_1ast_1_1ErrorExpr.html", "classmim_1_1ast_1_1ErrorExpr" ],
        [ "HoleExpr", "classmim_1_1ast_1_1HoleExpr.html", "classmim_1_1ast_1_1HoleExpr" ],
        [ "IdExpr", "classmim_1_1ast_1_1IdExpr.html", "classmim_1_1ast_1_1IdExpr" ],
        [ "PrimaryExpr", "classmim_1_1ast_1_1PrimaryExpr.html", "classmim_1_1ast_1_1PrimaryExpr" ],
        [ "LitExpr", "classmim_1_1ast_1_1LitExpr.html", "classmim_1_1ast_1_1LitExpr" ],
        [ "DeclExpr", "classmim_1_1ast_1_1DeclExpr.html", "classmim_1_1ast_1_1DeclExpr" ],
        [ "TypeExpr", "classmim_1_1ast_1_1TypeExpr.html", "classmim_1_1ast_1_1TypeExpr" ],
        [ "RuleExpr", "classmim_1_1ast_1_1RuleExpr.html", "classmim_1_1ast_1_1RuleExpr" ],
        [ "UnionExpr", "classmim_1_1ast_1_1UnionExpr.html", "classmim_1_1ast_1_1UnionExpr" ],
        [ "InjExpr", "classmim_1_1ast_1_1InjExpr.html", "classmim_1_1ast_1_1InjExpr" ],
        [ "MatchExpr", "classmim_1_1ast_1_1MatchExpr.html", "classmim_1_1ast_1_1MatchExpr" ],
        [ "ArrowExpr", "classmim_1_1ast_1_1ArrowExpr.html", "classmim_1_1ast_1_1ArrowExpr" ],
        [ "PiExpr", "classmim_1_1ast_1_1PiExpr.html", "classmim_1_1ast_1_1PiExpr" ],
        [ "LamExpr", "classmim_1_1ast_1_1LamExpr.html", "classmim_1_1ast_1_1LamExpr" ],
        [ "AppExpr", "classmim_1_1ast_1_1AppExpr.html", "classmim_1_1ast_1_1AppExpr" ],
        [ "RetExpr", "classmim_1_1ast_1_1RetExpr.html", "classmim_1_1ast_1_1RetExpr" ],
        [ "SigmaExpr", "classmim_1_1ast_1_1SigmaExpr.html", "classmim_1_1ast_1_1SigmaExpr" ],
        [ "TupleExpr", "classmim_1_1ast_1_1TupleExpr.html", "classmim_1_1ast_1_1TupleExpr" ],
        [ "SeqExpr", "classmim_1_1ast_1_1SeqExpr.html", "classmim_1_1ast_1_1SeqExpr" ],
        [ "ExtractExpr", "classmim_1_1ast_1_1ExtractExpr.html", "classmim_1_1ast_1_1ExtractExpr" ],
        [ "InsertExpr", "classmim_1_1ast_1_1InsertExpr.html", "classmim_1_1ast_1_1InsertExpr" ],
        [ "UniqExpr", "classmim_1_1ast_1_1UniqExpr.html", "classmim_1_1ast_1_1UniqExpr" ],
        [ "LetDecl", "classmim_1_1ast_1_1LetDecl.html", "classmim_1_1ast_1_1LetDecl" ],
        [ "AxmDecl", "classmim_1_1ast_1_1AxmDecl.html", "classmim_1_1ast_1_1AxmDecl" ],
        [ "RecDecl", "classmim_1_1ast_1_1RecDecl.html", "classmim_1_1ast_1_1RecDecl" ],
        [ "LamDecl", "classmim_1_1ast_1_1LamDecl.html", "classmim_1_1ast_1_1LamDecl" ],
        [ "CDecl", "classmim_1_1ast_1_1CDecl.html", "classmim_1_1ast_1_1CDecl" ],
        [ "RuleDecl", "classmim_1_1ast_1_1RuleDecl.html", "classmim_1_1ast_1_1RuleDecl" ],
        [ "Import", "classmim_1_1ast_1_1Import.html", "classmim_1_1ast_1_1Import" ],
        [ "Module", "classmim_1_1ast_1_1Module.html", "classmim_1_1ast_1_1Module" ],
        [ "Lexer", "classmim_1_1ast_1_1Lexer.html", "classmim_1_1ast_1_1Lexer" ],
        [ "Parser", "classmim_1_1ast_1_1Parser.html", "classmim_1_1ast_1_1Parser" ],
        [ "Tok", "classmim_1_1ast_1_1Tok.html", "classmim_1_1ast_1_1Tok" ],
        [ "DummyDecl", "classmim_1_1ast_1_1DummyDecl.html", "classmim_1_1ast_1_1DummyDecl" ],
        [ "Scopes", "classmim_1_1ast_1_1Scopes.html", "classmim_1_1ast_1_1Scopes" ],
        [ "Emitter", "classmim_1_1ast_1_1Emitter.html", "classmim_1_1ast_1_1Emitter" ],
        [ "S", "structmim_1_1ast_1_1S.html", "structmim_1_1ast_1_1S" ],
        [ "R", "structmim_1_1ast_1_1R.html", "structmim_1_1ast_1_1R" ],
        [ "AnnexInfo.sym", "namespacemim_1_1ast.html#structmim_1_1ast_1_1AnnexInfo_8sym", "namespacemim_1_1ast_structmim_1_1ast_1_1AnnexInfo_8sym_dup" ],
        [ "AnnexInfo.id", "namespacemim_1_1ast.html#structmim_1_1ast_1_1AnnexInfo_8id", "namespacemim_1_1ast_structmim_1_1ast_1_1AnnexInfo_8id_dup" ]
      ] ],
      [ "plug", "namespacemim_1_1plug.html", [
        [ "affine", "namespacemim_1_1plug_1_1affine.html", [
          [ "phase", "namespacemim_1_1plug_1_1affine_1_1phase.html", [
            [ "LowerFor", "classmim_1_1plug_1_1affine_1_1phase_1_1LowerFor.html", "classmim_1_1plug_1_1affine_1_1phase_1_1LowerFor" ]
          ] ]
        ] ],
        [ "autodiff", "namespacemim_1_1plug_1_1autodiff.html", [
          [ "Eval", "classmim_1_1plug_1_1autodiff_1_1Eval.html", "classmim_1_1plug_1_1autodiff_1_1Eval" ]
        ] ],
        [ "clos", "namespacemim_1_1plug_1_1clos.html", [
          [ "ClosLit", "classmim_1_1plug_1_1clos_1_1ClosLit.html", "classmim_1_1plug_1_1clos_1_1ClosLit" ],
          [ "BranchClosElim", "classmim_1_1plug_1_1clos_1_1BranchClosElim.html", "classmim_1_1plug_1_1clos_1_1BranchClosElim" ],
          [ "Clos2SJLJ", "classmim_1_1plug_1_1clos_1_1Clos2SJLJ.html", "classmim_1_1plug_1_1clos_1_1Clos2SJLJ" ],
          [ "ClosConvPrep", "classmim_1_1plug_1_1clos_1_1ClosConvPrep.html", "classmim_1_1plug_1_1clos_1_1ClosConvPrep" ],
          [ "LowerTypedClosPrep", "classmim_1_1plug_1_1clos_1_1LowerTypedClosPrep.html", "classmim_1_1plug_1_1clos_1_1LowerTypedClosPrep" ],
          [ "FreeDefAna", "classmim_1_1plug_1_1clos_1_1FreeDefAna.html", "classmim_1_1plug_1_1clos_1_1FreeDefAna" ],
          [ "ClosConv", "classmim_1_1plug_1_1clos_1_1ClosConv.html", "classmim_1_1plug_1_1clos_1_1ClosConv" ],
          [ "LowerTypedClos", "classmim_1_1plug_1_1clos_1_1LowerTypedClos.html", "classmim_1_1plug_1_1clos_1_1LowerTypedClos" ]
        ] ],
        [ "direct", "namespacemim_1_1plug_1_1direct.html", [
          [ "CPS2DSPhase", "classmim_1_1plug_1_1direct_1_1CPS2DSPhase.html", "classmim_1_1plug_1_1direct_1_1CPS2DSPhase" ],
          [ "DS2CPS", "classmim_1_1plug_1_1direct_1_1DS2CPS.html", "classmim_1_1plug_1_1direct_1_1DS2CPS" ]
        ] ],
        [ "matrix", "namespacemim_1_1plug_1_1matrix.html", [
          [ "LowerMatrixHighLevelMapRed", "classmim_1_1plug_1_1matrix_1_1LowerMatrixHighLevelMapRed.html", "classmim_1_1plug_1_1matrix_1_1LowerMatrixHighLevelMapRed" ],
          [ "LowerMatrixLowLevel", "classmim_1_1plug_1_1matrix_1_1LowerMatrixLowLevel.html", "classmim_1_1plug_1_1matrix_1_1LowerMatrixLowLevel" ],
          [ "LowerMatrixMediumLevel", "classmim_1_1plug_1_1matrix_1_1LowerMatrixMediumLevel.html", "classmim_1_1plug_1_1matrix_1_1LowerMatrixMediumLevel" ]
        ] ],
        [ "mem", "namespacemim_1_1plug_1_1mem.html", [
          [ "pass", "namespacemim_1_1plug_1_1mem_1_1pass.html", [
            [ "CopyProp", "classmim_1_1plug_1_1mem_1_1pass_1_1CopyProp.html", "classmim_1_1plug_1_1mem_1_1pass_1_1CopyProp" ],
            [ "Reshape", "classmim_1_1plug_1_1mem_1_1pass_1_1Reshape.html", "classmim_1_1plug_1_1mem_1_1pass_1_1Reshape" ],
            [ "SSA", "classmim_1_1plug_1_1mem_1_1pass_1_1SSA.html", "classmim_1_1plug_1_1mem_1_1pass_1_1SSA" ]
          ] ],
          [ "phase", "namespacemim_1_1plug_1_1mem_1_1phase.html", [
            [ "AddMem", "classmim_1_1plug_1_1mem_1_1phase_1_1AddMem.html", "classmim_1_1plug_1_1mem_1_1phase_1_1AddMem" ]
          ] ]
        ] ],
        [ "regex", "namespacemim_1_1plug_1_1regex.html", [
          [ "LowerRegex", "classmim_1_1plug_1_1regex_1_1LowerRegex.html", "classmim_1_1plug_1_1regex_1_1LowerRegex" ],
          [ "app_range", "structmim_1_1plug_1_1regex_1_1app__range.html", "structmim_1_1plug_1_1regex_1_1app__range" ]
        ] ]
      ] ],
      [ "ll", "namespacemim_1_1ll.html", [
        [ "BB", "structmim_1_1ll_1_1BB.html", "structmim_1_1ll_1_1BB" ],
        [ "Emitter", "classmim_1_1ll_1_1Emitter.html", "classmim_1_1ll_1_1Emitter" ]
      ] ],
      [ "sexpr", "namespacemim_1_1sexpr.html", [
        [ "BB", "structmim_1_1sexpr_1_1BB.html", "structmim_1_1sexpr_1_1BB" ],
        [ "Emitter", "classmim_1_1sexpr_1_1Emitter.html", "classmim_1_1sexpr_1_1Emitter" ]
      ] ],
      [ "lct", "namespacemim_1_1lct.html", [
        [ "Node", "classmim_1_1lct_1_1Node.html", "classmim_1_1lct_1_1Node" ]
      ] ],
      [ "Axm", "classmim_1_1Axm.html", "classmim_1_1Axm" ],
      [ "Emitter", "classmim_1_1Emitter.html", "classmim_1_1Emitter" ],
      [ "Hole", "classmim_1_1Hole.html", "classmim_1_1Hole" ],
      [ "Checker", "classmim_1_1Checker.html", "classmim_1_1Checker" ],
      [ "Setters", "classmim_1_1Setters.html", "classmim_1_1Setters" ],
      [ "Def", "classmim_1_1Def.html", "classmim_1_1Def" ],
      [ "Var", "classmim_1_1Var.html", "classmim_1_1Var" ],
      [ "Univ", "classmim_1_1Univ.html", "classmim_1_1Univ" ],
      [ "UMax", "classmim_1_1UMax.html", "classmim_1_1UMax" ],
      [ "UInc", "classmim_1_1UInc.html", "classmim_1_1UInc" ],
      [ "Type", "classmim_1_1Type.html", "classmim_1_1Type" ],
      [ "Lit", "classmim_1_1Lit.html", "classmim_1_1Lit" ],
      [ "Nat", "classmim_1_1Nat.html", "classmim_1_1Nat" ],
      [ "Idx", "classmim_1_1Idx.html", "classmim_1_1Idx" ],
      [ "Proxy", "classmim_1_1Proxy.html", "classmim_1_1Proxy" ],
      [ "Global", "classmim_1_1Global.html", "classmim_1_1Global" ],
      [ "Driver", "classmim_1_1Driver.html", "classmim_1_1Driver" ],
      [ "Flags", "namespacemim.html#structmim_1_1Flags", "namespacemim_structmim_1_1Flags_dup" ],
      [ "Pi", "classmim_1_1Pi.html", "classmim_1_1Pi" ],
      [ "Lam", "classmim_1_1Lam.html", "classmim_1_1Lam" ],
      [ "App", "classmim_1_1App.html", "classmim_1_1App" ],
      [ "Bound", "classmim_1_1Bound.html", "classmim_1_1Bound" ],
      [ "TBound", "classmim_1_1TBound.html", "classmim_1_1TBound" ],
      [ "Merge", "classmim_1_1Merge.html", "classmim_1_1Merge" ],
      [ "Inj", "classmim_1_1Inj.html", "classmim_1_1Inj" ],
      [ "Split", "classmim_1_1Split.html", "classmim_1_1Split" ],
      [ "Match", "classmim_1_1Match.html", "classmim_1_1Match" ],
      [ "Ext", "classmim_1_1Ext.html", "classmim_1_1Ext" ],
      [ "TExt", "classmim_1_1TExt.html", "classmim_1_1TExt" ],
      [ "Uniq", "classmim_1_1Uniq.html", "classmim_1_1Uniq" ],
      [ "Nest", "classmim_1_1Nest.html", "classmim_1_1Nest" ],
      [ "Res", "classmim_1_1Res.html", "classmim_1_1Res" ],
      [ "Stage", "classmim_1_1Stage.html", "classmim_1_1Stage" ],
      [ "Pass", "classmim_1_1Pass.html", "classmim_1_1Pass" ],
      [ "PassMan", "classmim_1_1PassMan.html", "classmim_1_1PassMan" ],
      [ "RWPass", "classmim_1_1RWPass.html", "classmim_1_1RWPass" ],
      [ "FPPass", "classmim_1_1FPPass.html", "classmim_1_1FPPass" ],
      [ "BetaRed", "classmim_1_1BetaRed.html", "classmim_1_1BetaRed" ],
      [ "EtaExp", "classmim_1_1EtaExp.html", "classmim_1_1EtaExp" ],
      [ "EtaRed", "classmim_1_1EtaRed.html", "classmim_1_1EtaRed" ],
      [ "LamSpec", "classmim_1_1LamSpec.html", "classmim_1_1LamSpec" ],
      [ "Scalarize", "classmim_1_1Scalarize.html", "classmim_1_1Scalarize" ],
      [ "TailRecElim", "classmim_1_1TailRecElim.html", "classmim_1_1TailRecElim" ],
      [ "Phase", "classmim_1_1Phase.html", "classmim_1_1Phase" ],
      [ "Analysis", "classmim_1_1Analysis.html", "classmim_1_1Analysis" ],
      [ "RWPhase", "classmim_1_1RWPhase.html", "classmim_1_1RWPhase" ],
      [ "Repl", "classmim_1_1Repl.html", "classmim_1_1Repl" ],
      [ "ReplMan", "classmim_1_1ReplMan.html", "classmim_1_1ReplMan" ],
      [ "ReplManPhase", "classmim_1_1ReplManPhase.html", "classmim_1_1ReplManPhase" ],
      [ "Cleanup", "classmim_1_1Cleanup.html", "classmim_1_1Cleanup" ],
      [ "PassManPhase", "classmim_1_1PassManPhase.html", "classmim_1_1PassManPhase" ],
      [ "PhaseMan", "classmim_1_1PhaseMan.html", "classmim_1_1PhaseMan" ],
      [ "ClosedMutPhase", "classmim_1_1ClosedMutPhase.html", "classmim_1_1ClosedMutPhase" ],
      [ "NestPhase", "classmim_1_1NestPhase.html", "classmim_1_1NestPhase" ],
      [ "BetaRedPhase", "classmim_1_1BetaRedPhase.html", "classmim_1_1BetaRedPhase" ],
      [ "BranchNormalizePhase", "classmim_1_1BranchNormalizePhase.html", "classmim_1_1BranchNormalizePhase" ],
      [ "EtaExpPhase", "classmim_1_1EtaExpPhase.html", "classmim_1_1EtaExpPhase" ],
      [ "EtaRedPhase", "classmim_1_1EtaRedPhase.html", "classmim_1_1EtaRedPhase" ],
      [ "PrefixCleanup", "classmim_1_1PrefixCleanup.html", "classmim_1_1PrefixCleanup" ],
      [ "RetWrap", "classmim_1_1RetWrap.html", "classmim_1_1RetWrap" ],
      [ "SymExprOpt", "classmim_1_1SymExprOpt.html", "classmim_1_1SymExprOpt" ],
      [ "Plugin", "structmim_1_1Plugin.html", "structmim_1_1Plugin" ],
      [ "Annex", "structmim_1_1Annex.html", "structmim_1_1Annex" ],
      [ "Rewriter", "classmim_1_1Rewriter.html", "classmim_1_1Rewriter" ],
      [ "VarRewriter", "classmim_1_1VarRewriter.html", "classmim_1_1VarRewriter" ],
      [ "Zonker", "classmim_1_1Zonker.html", "classmim_1_1Zonker" ],
      [ "Reform", "classmim_1_1Reform.html", "classmim_1_1Reform" ],
      [ "Rule", "classmim_1_1Rule.html", "classmim_1_1Rule" ],
      [ "Use", "classmim_1_1Use.html", "classmim_1_1Use" ],
      [ "UseHash", "structmim_1_1UseHash.html", "structmim_1_1UseHash" ],
      [ "UseEq", "structmim_1_1UseEq.html", "structmim_1_1UseEq" ],
      [ "Scheduler", "classmim_1_1Scheduler.html", "classmim_1_1Scheduler" ],
      [ "Prod", "classmim_1_1Prod.html", "classmim_1_1Prod" ],
      [ "Sigma", "classmim_1_1Sigma.html", "classmim_1_1Sigma" ],
      [ "Tuple", "classmim_1_1Tuple.html", "classmim_1_1Tuple" ],
      [ "Seq", "classmim_1_1Seq.html", "classmim_1_1Seq" ],
      [ "Arr", "classmim_1_1Arr.html", "classmim_1_1Arr" ],
      [ "Pack", "classmim_1_1Pack.html", "classmim_1_1Pack" ],
      [ "Extract", "classmim_1_1Extract.html", "classmim_1_1Extract" ],
      [ "Insert", "classmim_1_1Insert.html", "classmim_1_1Insert" ],
      [ "Select", "classmim_1_1Select.html", "classmim_1_1Select" ],
      [ "Branch", "classmim_1_1Branch.html", "classmim_1_1Branch" ],
      [ "Dispatch", "classmim_1_1Dispatch.html", "classmim_1_1Dispatch" ],
      [ "Error", "classmim_1_1Error.html", "classmim_1_1Error" ],
      [ "Dbg", "structmim_1_1Dbg.html", "structmim_1_1Dbg" ],
      [ "FNV1", "namespacemim.html#structmim_1_1FNV1", null ],
      [ "FNV1&lt; 4 &gt;", "structmim_1_1FNV1_3_014_01_4.html", "structmim_1_1FNV1_3_014_01_4" ],
      [ "FNV1&lt; 8 &gt;", "structmim_1_1FNV1_3_018_01_4.html", "structmim_1_1FNV1_3_018_01_4" ],
      [ "Log", "classmim_1_1Log.html", "classmim_1_1Log" ],
      [ "Elem", "structmim_1_1Elem.html", "structmim_1_1Elem" ],
      [ "Tab", "classmim_1_1Tab.html", "classmim_1_1Tab" ],
      [ "Sets", "classmim_1_1Sets.html", "classmim_1_1Sets" ],
      [ "Span", "classmim_1_1Span.html", "classmim_1_1Span" ],
      [ "unique_stack", "classmim_1_1unique__stack.html", "classmim_1_1unique__stack" ],
      [ "unique_queue", "classmim_1_1unique__queue.html", "classmim_1_1unique__queue" ],
      [ "GIDHash", "structmim_1_1GIDHash.html", "structmim_1_1GIDHash" ],
      [ "GIDLt", "structmim_1_1GIDLt.html", "structmim_1_1GIDLt" ],
      [ "Vector", "classmim_1_1Vector.html", "classmim_1_1Vector" ],
      [ "World", "classmim_1_1World.html", "classmim_1_1World" ]
    ] ],
    [ "std", "namespacestd.html", [
      [ "tuple_size&lt; mim::Span&lt; T, N &gt; &gt;", "structstd_1_1tuple__size_3_01mim_1_1Span_3_01T_00_01N_01_4_01_4.html", null ],
      [ "tuple_element&lt; I, mim::Span&lt; T, N &gt; &gt;", "namespacestd.html#structstd_1_1tuple__element_3_01I_00_01mim_1_1Span_3_01T_00_01N_01_4_01_4", "namespacestd_structstd_1_1tuple__element_3_01I_00_01mim_1_1Span_3_01T_00_01N_01_4_01_4_dup" ]
    ] ]
];