var annotated_dup =
[
    [ "automaton", "namespaceautomaton.html", [
      [ "AutomatonBase", "classautomaton_1_1AutomatonBase.html", "classautomaton_1_1AutomatonBase" ],
      [ "DFA", "classautomaton_1_1DFA.html", "classautomaton_1_1DFA" ],
      [ "DFANode", "classautomaton_1_1DFANode.html", "classautomaton_1_1DFANode" ],
      [ "NFA", "classautomaton_1_1NFA.html", "classautomaton_1_1NFA" ],
      [ "NFANode", "classautomaton_1_1NFANode.html", "classautomaton_1_1NFANode" ],
      [ "RangeCompare", "structautomaton_1_1RangeCompare.html", "structautomaton_1_1RangeCompare" ]
    ] ],
    [ "mim", "namespacemim.html", [
      [ "ast", "namespacemim_1_1ast.html", [
        [ "AliasPtrn", "classmim_1_1ast_1_1AliasPtrn.html", "classmim_1_1ast_1_1AliasPtrn" ],
        [ "AnnexInfo", "structmim_1_1ast_1_1AnnexInfo.html", "structmim_1_1ast_1_1AnnexInfo" ],
        [ "AnnexInfo.id", "namespacemim_1_1ast.html#structmim_1_1ast_1_1AnnexInfo_8id", "namespacemim_1_1ast_structmim_1_1ast_1_1AnnexInfo_8id_dup" ],
        [ "AnnexInfo.sym", "namespacemim_1_1ast.html#structmim_1_1ast_1_1AnnexInfo_8sym", "namespacemim_1_1ast_structmim_1_1ast_1_1AnnexInfo_8sym_dup" ],
        [ "AppExpr", "classmim_1_1ast_1_1AppExpr.html", "classmim_1_1ast_1_1AppExpr" ],
        [ "ArrOrPackExpr", "classmim_1_1ast_1_1ArrOrPackExpr.html", "classmim_1_1ast_1_1ArrOrPackExpr" ],
        [ "ArrowExpr", "classmim_1_1ast_1_1ArrowExpr.html", "classmim_1_1ast_1_1ArrowExpr" ],
        [ "AST", "classmim_1_1ast_1_1AST.html", "classmim_1_1ast_1_1AST" ],
        [ "AxiomDecl", "classmim_1_1ast_1_1AxiomDecl.html", "classmim_1_1ast_1_1AxiomDecl" ],
        [ "CDecl", "classmim_1_1ast_1_1CDecl.html", "classmim_1_1ast_1_1CDecl" ],
        [ "Decl", "classmim_1_1ast_1_1Decl.html", "classmim_1_1ast_1_1Decl" ],
        [ "DeclExpr", "classmim_1_1ast_1_1DeclExpr.html", "classmim_1_1ast_1_1DeclExpr" ],
        [ "DummyDecl", "classmim_1_1ast_1_1DummyDecl.html", "classmim_1_1ast_1_1DummyDecl" ],
        [ "Emitter", "classmim_1_1ast_1_1Emitter.html", "classmim_1_1ast_1_1Emitter" ],
        [ "ErrorExpr", "classmim_1_1ast_1_1ErrorExpr.html", "classmim_1_1ast_1_1ErrorExpr" ],
        [ "ErrorPtrn", "classmim_1_1ast_1_1ErrorPtrn.html", "classmim_1_1ast_1_1ErrorPtrn" ],
        [ "Expr", "classmim_1_1ast_1_1Expr.html", "classmim_1_1ast_1_1Expr" ],
        [ "ExtractExpr", "classmim_1_1ast_1_1ExtractExpr.html", "classmim_1_1ast_1_1ExtractExpr" ],
        [ "GrpPtrn", "classmim_1_1ast_1_1GrpPtrn.html", "classmim_1_1ast_1_1GrpPtrn" ],
        [ "HoleExpr", "classmim_1_1ast_1_1HoleExpr.html", "classmim_1_1ast_1_1HoleExpr" ],
        [ "IdExpr", "classmim_1_1ast_1_1IdExpr.html", "classmim_1_1ast_1_1IdExpr" ],
        [ "IdPtrn", "classmim_1_1ast_1_1IdPtrn.html", "classmim_1_1ast_1_1IdPtrn" ],
        [ "Import", "classmim_1_1ast_1_1Import.html", "classmim_1_1ast_1_1Import" ],
        [ "InsertExpr", "classmim_1_1ast_1_1InsertExpr.html", "classmim_1_1ast_1_1InsertExpr" ],
        [ "LamDecl", "classmim_1_1ast_1_1LamDecl.html", "classmim_1_1ast_1_1LamDecl" ],
        [ "LamExpr", "classmim_1_1ast_1_1LamExpr.html", "classmim_1_1ast_1_1LamExpr" ],
        [ "LetDecl", "classmim_1_1ast_1_1LetDecl.html", "classmim_1_1ast_1_1LetDecl" ],
        [ "Lexer", "classmim_1_1ast_1_1Lexer.html", "classmim_1_1ast_1_1Lexer" ],
        [ "LitExpr", "classmim_1_1ast_1_1LitExpr.html", "classmim_1_1ast_1_1LitExpr" ],
        [ "Module", "classmim_1_1ast_1_1Module.html", "classmim_1_1ast_1_1Module" ],
        [ "Node", "classmim_1_1ast_1_1Node.html", "classmim_1_1ast_1_1Node" ],
        [ "Parser", "classmim_1_1ast_1_1Parser.html", "classmim_1_1ast_1_1Parser" ],
        [ "PiExpr", "classmim_1_1ast_1_1PiExpr.html", "classmim_1_1ast_1_1PiExpr" ],
        [ "PrimaryExpr", "classmim_1_1ast_1_1PrimaryExpr.html", "classmim_1_1ast_1_1PrimaryExpr" ],
        [ "Ptrn", "classmim_1_1ast_1_1Ptrn.html", "classmim_1_1ast_1_1Ptrn" ],
        [ "R", "structmim_1_1ast_1_1R.html", "structmim_1_1ast_1_1R" ],
        [ "RecDecl", "classmim_1_1ast_1_1RecDecl.html", "classmim_1_1ast_1_1RecDecl" ],
        [ "RetExpr", "classmim_1_1ast_1_1RetExpr.html", "classmim_1_1ast_1_1RetExpr" ],
        [ "S", "structmim_1_1ast_1_1S.html", "structmim_1_1ast_1_1S" ],
        [ "Scopes", "classmim_1_1ast_1_1Scopes.html", "classmim_1_1ast_1_1Scopes" ],
        [ "SigmaExpr", "classmim_1_1ast_1_1SigmaExpr.html", "classmim_1_1ast_1_1SigmaExpr" ],
        [ "Tok", "classmim_1_1ast_1_1Tok.html", "classmim_1_1ast_1_1Tok" ],
        [ "TupleExpr", "classmim_1_1ast_1_1TupleExpr.html", "classmim_1_1ast_1_1TupleExpr" ],
        [ "TuplePtrn", "classmim_1_1ast_1_1TuplePtrn.html", "classmim_1_1ast_1_1TuplePtrn" ],
        [ "TypeExpr", "classmim_1_1ast_1_1TypeExpr.html", "classmim_1_1ast_1_1TypeExpr" ],
        [ "UniqExpr", "classmim_1_1ast_1_1UniqExpr.html", "classmim_1_1ast_1_1UniqExpr" ],
        [ "ValDecl", "classmim_1_1ast_1_1ValDecl.html", "classmim_1_1ast_1_1ValDecl" ]
      ] ],
      [ "lct", "namespacemim_1_1lct.html", [
        [ "Node", "classmim_1_1lct_1_1Node.html", "classmim_1_1lct_1_1Node" ]
      ] ],
      [ "ll", "namespacemim_1_1ll.html", [
        [ "BB", "structmim_1_1ll_1_1BB.html", "structmim_1_1ll_1_1BB" ],
        [ "Emitter", "classmim_1_1ll_1_1Emitter.html", "classmim_1_1ll_1_1Emitter" ]
      ] ],
      [ "plug", "namespacemim_1_1plug.html", [
        [ "affine", "namespacemim_1_1plug_1_1affine.html", [
          [ "LowerFor", "classmim_1_1plug_1_1affine_1_1LowerFor.html", "classmim_1_1plug_1_1affine_1_1LowerFor" ]
        ] ],
        [ "autodiff", "namespacemim_1_1plug_1_1autodiff.html", [
          [ "AutoDiffEval", "classmim_1_1plug_1_1autodiff_1_1AutoDiffEval.html", "classmim_1_1plug_1_1autodiff_1_1AutoDiffEval" ],
          [ "AutoDiffZero", "classmim_1_1plug_1_1autodiff_1_1AutoDiffZero.html", "classmim_1_1plug_1_1autodiff_1_1AutoDiffZero" ],
          [ "AutoDiffZeroCleanup", "classmim_1_1plug_1_1autodiff_1_1AutoDiffZeroCleanup.html", "classmim_1_1plug_1_1autodiff_1_1AutoDiffZeroCleanup" ]
        ] ],
        [ "clos", "namespacemim_1_1plug_1_1clos.html", [
          [ "BranchClosElim", "classmim_1_1plug_1_1clos_1_1BranchClosElim.html", "classmim_1_1plug_1_1clos_1_1BranchClosElim" ],
          [ "Clos2SJLJ", "classmim_1_1plug_1_1clos_1_1Clos2SJLJ.html", "classmim_1_1plug_1_1clos_1_1Clos2SJLJ" ],
          [ "ClosConv", "classmim_1_1plug_1_1clos_1_1ClosConv.html", "classmim_1_1plug_1_1clos_1_1ClosConv" ],
          [ "ClosConvPrep", "classmim_1_1plug_1_1clos_1_1ClosConvPrep.html", "classmim_1_1plug_1_1clos_1_1ClosConvPrep" ],
          [ "ClosLit", "classmim_1_1plug_1_1clos_1_1ClosLit.html", "classmim_1_1plug_1_1clos_1_1ClosLit" ],
          [ "FreeDefAna", "classmim_1_1plug_1_1clos_1_1FreeDefAna.html", "classmim_1_1plug_1_1clos_1_1FreeDefAna" ],
          [ "LowerTypedClos", "classmim_1_1plug_1_1clos_1_1LowerTypedClos.html", "classmim_1_1plug_1_1clos_1_1LowerTypedClos" ],
          [ "LowerTypedClosPrep", "classmim_1_1plug_1_1clos_1_1LowerTypedClosPrep.html", "classmim_1_1plug_1_1clos_1_1LowerTypedClosPrep" ]
        ] ],
        [ "compile", "namespacemim_1_1plug_1_1compile.html", [
          [ "DebugPrint", "classmim_1_1plug_1_1compile_1_1DebugPrint.html", "classmim_1_1plug_1_1compile_1_1DebugPrint" ],
          [ "InternalCleanup", "classmim_1_1plug_1_1compile_1_1InternalCleanup.html", "classmim_1_1plug_1_1compile_1_1InternalCleanup" ]
        ] ],
        [ "direct", "namespacemim_1_1plug_1_1direct.html", [
          [ "CPS2DS", "classmim_1_1plug_1_1direct_1_1CPS2DS.html", "classmim_1_1plug_1_1direct_1_1CPS2DS" ],
          [ "DS2CPS", "classmim_1_1plug_1_1direct_1_1DS2CPS.html", "classmim_1_1plug_1_1direct_1_1DS2CPS" ]
        ] ],
        [ "matrix", "namespacemim_1_1plug_1_1matrix.html", [
          [ "LowerMatrixHighLevelMapRed", "classmim_1_1plug_1_1matrix_1_1LowerMatrixHighLevelMapRed.html", "classmim_1_1plug_1_1matrix_1_1LowerMatrixHighLevelMapRed" ],
          [ "LowerMatrixLowLevel", "classmim_1_1plug_1_1matrix_1_1LowerMatrixLowLevel.html", "classmim_1_1plug_1_1matrix_1_1LowerMatrixLowLevel" ],
          [ "LowerMatrixMediumLevel", "classmim_1_1plug_1_1matrix_1_1LowerMatrixMediumLevel.html", "classmim_1_1plug_1_1matrix_1_1LowerMatrixMediumLevel" ]
        ] ],
        [ "mem", "namespacemim_1_1plug_1_1mem.html", [
          [ "AddMem", "classmim_1_1plug_1_1mem_1_1AddMem.html", "classmim_1_1plug_1_1mem_1_1AddMem" ],
          [ "Alloc2Malloc", "classmim_1_1plug_1_1mem_1_1Alloc2Malloc.html", "classmim_1_1plug_1_1mem_1_1Alloc2Malloc" ],
          [ "CopyProp", "classmim_1_1plug_1_1mem_1_1CopyProp.html", "classmim_1_1plug_1_1mem_1_1CopyProp" ],
          [ "RememElim", "classmim_1_1plug_1_1mem_1_1RememElim.html", "classmim_1_1plug_1_1mem_1_1RememElim" ],
          [ "Reshape", "classmim_1_1plug_1_1mem_1_1Reshape.html", "classmim_1_1plug_1_1mem_1_1Reshape" ],
          [ "SSAConstr", "classmim_1_1plug_1_1mem_1_1SSAConstr.html", "classmim_1_1plug_1_1mem_1_1SSAConstr" ]
        ] ],
        [ "refly", "namespacemim_1_1plug_1_1refly.html", [
          [ "RemoveDbgPerm", "classmim_1_1plug_1_1refly_1_1RemoveDbgPerm.html", "classmim_1_1plug_1_1refly_1_1RemoveDbgPerm" ]
        ] ],
        [ "regex", "namespacemim_1_1plug_1_1regex.html", [
          [ "app_range", "structmim_1_1plug_1_1regex_1_1app__range.html", "structmim_1_1plug_1_1regex_1_1app__range" ],
          [ "LowerRegex", "classmim_1_1plug_1_1regex_1_1LowerRegex.html", "classmim_1_1plug_1_1regex_1_1LowerRegex" ]
        ] ]
      ] ],
      [ "Ac", "classmim_1_1Ac.html", "classmim_1_1Ac" ],
      [ "Annex", "structmim_1_1Annex.html", "structmim_1_1Annex" ],
      [ "App", "classmim_1_1App.html", "classmim_1_1App" ],
      [ "Arr", "classmim_1_1Arr.html", "classmim_1_1Arr" ],
      [ "Axiom", "classmim_1_1Axiom.html", "classmim_1_1Axiom" ],
      [ "BetaRed", "classmim_1_1BetaRed.html", "classmim_1_1BetaRed" ],
      [ "BitSet", "classmim_1_1BitSet.html", "classmim_1_1BitSet" ],
      [ "Bound", "classmim_1_1Bound.html", "classmim_1_1Bound" ],
      [ "Checker", "classmim_1_1Checker.html", "classmim_1_1Checker" ],
      [ "Cleanup", "classmim_1_1Cleanup.html", "classmim_1_1Cleanup" ],
      [ "ClosedCollector", "classmim_1_1ClosedCollector.html", "classmim_1_1ClosedCollector" ],
      [ "ClosedMutPhase", "classmim_1_1ClosedMutPhase.html", "classmim_1_1ClosedMutPhase" ],
      [ "Dbg", "structmim_1_1Dbg.html", "structmim_1_1Dbg" ],
      [ "Def", "classmim_1_1Def.html", "classmim_1_1Def" ],
      [ "DefDefEq", "structmim_1_1DefDefEq.html", "structmim_1_1DefDefEq" ],
      [ "DefDefHash", "structmim_1_1DefDefHash.html", "structmim_1_1DefDefHash" ],
      [ "Driver", "classmim_1_1Driver.html", "classmim_1_1Driver" ],
      [ "Elem", "structmim_1_1Elem.html", "structmim_1_1Elem" ],
      [ "Emitter", "classmim_1_1Emitter.html", "classmim_1_1Emitter" ],
      [ "Error", "classmim_1_1Error.html", "classmim_1_1Error" ],
      [ "EtaExp", "classmim_1_1EtaExp.html", "classmim_1_1EtaExp" ],
      [ "EtaRed", "classmim_1_1EtaRed.html", "classmim_1_1EtaRed" ],
      [ "Ext", "classmim_1_1Ext.html", "classmim_1_1Ext" ],
      [ "Extract", "classmim_1_1Extract.html", "classmim_1_1Extract" ],
      [ "Flags", "namespacemim.html#structmim_1_1Flags", "namespacemim_structmim_1_1Flags_dup" ],
      [ "FNV1", "namespacemim.html#structmim_1_1FNV1", null ],
      [ "FNV1< 4 >", "structmim_1_1FNV1_3_014_01_4.html", "structmim_1_1FNV1_3_014_01_4" ],
      [ "FNV1< 8 >", "structmim_1_1FNV1_3_018_01_4.html", "structmim_1_1FNV1_3_018_01_4" ],
      [ "FPPass", "classmim_1_1FPPass.html", "classmim_1_1FPPass" ],
      [ "FPPhase", "classmim_1_1FPPhase.html", "classmim_1_1FPPhase" ],
      [ "GIDEq", "structmim_1_1GIDEq.html", "structmim_1_1GIDEq" ],
      [ "GIDHash", "structmim_1_1GIDHash.html", "structmim_1_1GIDHash" ],
      [ "GIDLt", "structmim_1_1GIDLt.html", "structmim_1_1GIDLt" ],
      [ "Global", "classmim_1_1Global.html", "classmim_1_1Global" ],
      [ "Hole", "classmim_1_1Hole.html", "classmim_1_1Hole" ],
      [ "Idx", "classmim_1_1Idx.html", "classmim_1_1Idx" ],
      [ "IndexMap", "classmim_1_1IndexMap.html", "classmim_1_1IndexMap" ],
      [ "IndexSet", "classmim_1_1IndexSet.html", "classmim_1_1IndexSet" ],
      [ "Insert", "classmim_1_1Insert.html", "classmim_1_1Insert" ],
      [ "Lam", "classmim_1_1Lam.html", "classmim_1_1Lam" ],
      [ "LamSpec", "classmim_1_1LamSpec.html", "classmim_1_1LamSpec" ],
      [ "Lit", "classmim_1_1Lit.html", "classmim_1_1Lit" ],
      [ "Log", "classmim_1_1Log.html", "classmim_1_1Log" ],
      [ "Match", "classmim_1_1Match.html", "classmim_1_1Match" ],
      [ "Nat", "classmim_1_1Nat.html", "classmim_1_1Nat" ],
      [ "Nest", "classmim_1_1Nest.html", "classmim_1_1Nest" ],
      [ "NestPhase", "classmim_1_1NestPhase.html", "classmim_1_1NestPhase" ],
      [ "Pack", "classmim_1_1Pack.html", "classmim_1_1Pack" ],
      [ "Pass", "classmim_1_1Pass.html", "classmim_1_1Pass" ],
      [ "PassMan", "classmim_1_1PassMan.html", "classmim_1_1PassMan" ],
      [ "PassManPhase", "classmim_1_1PassManPhase.html", "classmim_1_1PassManPhase" ],
      [ "PassPhase", "classmim_1_1PassPhase.html", "classmim_1_1PassPhase" ],
      [ "Phase", "classmim_1_1Phase.html", "classmim_1_1Phase" ],
      [ "Pi", "classmim_1_1Pi.html", "classmim_1_1Pi" ],
      [ "Pick", "classmim_1_1Pick.html", "classmim_1_1Pick" ],
      [ "Pipeline", "classmim_1_1Pipeline.html", "classmim_1_1Pipeline" ],
      [ "PipelineBuilder", "classmim_1_1PipelineBuilder.html", "classmim_1_1PipelineBuilder" ],
      [ "Plugin", "structmim_1_1Plugin.html", "structmim_1_1Plugin" ],
      [ "Proxy", "classmim_1_1Proxy.html", "classmim_1_1Proxy" ],
      [ "Res", "classmim_1_1Res.html", "classmim_1_1Res" ],
      [ "RetWrap", "classmim_1_1RetWrap.html", "classmim_1_1RetWrap" ],
      [ "Rewriter", "classmim_1_1Rewriter.html", "classmim_1_1Rewriter" ],
      [ "RWPass", "classmim_1_1RWPass.html", "classmim_1_1RWPass" ],
      [ "RWPhase", "classmim_1_1RWPhase.html", "classmim_1_1RWPhase" ],
      [ "Scalarize", "classmim_1_1Scalarize.html", "classmim_1_1Scalarize" ],
      [ "Scheduler", "classmim_1_1Scheduler.html", "classmim_1_1Scheduler" ],
      [ "Sets", "classmim_1_1Sets.html", "classmim_1_1Sets" ],
      [ "Setters", "classmim_1_1Setters.html", "classmim_1_1Setters" ],
      [ "Sigma", "classmim_1_1Sigma.html", "classmim_1_1Sigma" ],
      [ "Span", "classmim_1_1Span.html", "classmim_1_1Span" ],
      [ "Tab", "classmim_1_1Tab.html", "classmim_1_1Tab" ],
      [ "TailRecElim", "classmim_1_1TailRecElim.html", "classmim_1_1TailRecElim" ],
      [ "TBound", "classmim_1_1TBound.html", "classmim_1_1TBound" ],
      [ "Test", "classmim_1_1Test.html", "classmim_1_1Test" ],
      [ "TExt", "classmim_1_1TExt.html", "classmim_1_1TExt" ],
      [ "Tuple", "classmim_1_1Tuple.html", "classmim_1_1Tuple" ],
      [ "Type", "classmim_1_1Type.html", "classmim_1_1Type" ],
      [ "UInc", "classmim_1_1UInc.html", "classmim_1_1UInc" ],
      [ "UMax", "classmim_1_1UMax.html", "classmim_1_1UMax" ],
      [ "Uniq", "classmim_1_1Uniq.html", "classmim_1_1Uniq" ],
      [ "unique_queue", "classmim_1_1unique__queue.html", "classmim_1_1unique__queue" ],
      [ "unique_stack", "classmim_1_1unique__stack.html", "classmim_1_1unique__stack" ],
      [ "Univ", "classmim_1_1Univ.html", "classmim_1_1Univ" ],
      [ "Use", "classmim_1_1Use.html", "classmim_1_1Use" ],
      [ "UseEq", "structmim_1_1UseEq.html", "structmim_1_1UseEq" ],
      [ "UseHash", "structmim_1_1UseHash.html", "structmim_1_1UseHash" ],
      [ "Var", "classmim_1_1Var.html", "classmim_1_1Var" ],
      [ "VarRewriter", "classmim_1_1VarRewriter.html", "classmim_1_1VarRewriter" ],
      [ "Vector", "classmim_1_1Vector.html", "classmim_1_1Vector" ],
      [ "Vel", "classmim_1_1Vel.html", "classmim_1_1Vel" ],
      [ "World", "classmim_1_1World.html", "classmim_1_1World" ]
    ] ],
    [ "std", "namespacestd.html", [
      [ "tuple_element< I, mim::Span< T, N > >", "namespacestd.html#structstd_1_1tuple__element_3_01I_00_01mim_1_1Span_3_01T_00_01N_01_4_01_4", "namespacestd_structstd_1_1tuple__element_3_01I_00_01mim_1_1Span_3_01T_00_01N_01_4_01_4_dup" ],
      [ "tuple_size< mim::Span< T, N > >", "structstd_1_1tuple__size_3_01mim_1_1Span_3_01T_00_01N_01_4_01_4.html", null ]
    ] ],
    [ "DebugDump", "classDebugDump.html", "classDebugDump" ]
];