Thorin: thorin::Mangler Class Reference
thorin::Mangler Class Reference
#include <thorin/transform/mangle.h>
Public Member Functions
Mangler (const Scope &scope, Defs args, Defs lift)
const Scope & scope () const
World & world () const
std::optional< const Def * > old2new (const Def *def)
Lam * mangle ()
Lam * old_entry () const
Lam * new_entry () const
Detailed Description
Definition at line 9 of file mangle.h.
Constructor & Destructor Documentation
Mangler()
thorin::Mangler::Mangler (const Scope & scope, Defs args, Defs lift)
Definition at line 9 of file mangle.cpp.
References thorin::detail::HashTable< Key, T, H, StackCapacity >::insert(), thorin::lift(), old_entry(), thorin::pop(), and thorin::ArrayRef< T >::size().
Member Function Documentation
mangle()
Lam * thorin::Mangler::mangle ()
Definition at line 37 of file mangle.cpp.
References thorin::World::cn(), thorin::e, mangle(), new_entry(), thorin::World::nom_lam(), old_entry(), thorin::Lam::set(), thorin::World::tuple(), thorin::Def::var(), and world().
Referenced by mangle(), and thorin::mangle().
new_entry()
Lam * thorin::Mangler::new_entry () const inline
Definition at line 18 of file mangle.h.
Referenced by mangle().
old2new()
std::optional< const Def * > thorin::Mangler::old2new (const Def * def) inline
Definition at line 15 of file mangle.h.
References thorin::HashMap< Key, T, H, StackCapacity >::lookup().
old_entry()
Lam * thorin::Mangler::old_entry () const inline
Definition at line 17 of file mangle.h.
Referenced by mangle(), and Mangler().
scope()
const Scope & thorin::Mangler::scope () const inline
Definition at line 13 of file mangle.h.
world()
World & thorin::Mangler::world () const inline
Definition at line 14 of file mangle.h.
References thorin::Scope::world().
Referenced by mangle().
The documentation for this class was generated from the following files:
thorin/transform/mangle.h
thorin/transform/mangle.cpp