Thorin: thorin::IPass Class Reference
thorin::IPass Class Reference
This is a minimalistic base interface to work with when dynamically loading a Pass.
#include </home/runner/work/thorin2/thorin2/thorin/pass/pass.h>
Public Member Functions
IPass (PassMan &man, const char *name)
virtual ~IPass ()=default
getters
PassMan & man ()
const PassMan & man () const
const char * name () const
size_t index () const
Detailed Description
This is a minimalistic base interface to work with when dynamically loading a Pass.
Definition at line 15 of file pass.h.
Constructor & Destructor Documentation
IPass()
thorin::IPass::IPass (PassMan & man, const char * name)
Definition at line 9 of file pass.cpp.
References thorin::size.
~IPass()
virtual thorin::IPass::~IPass () virtual default
Member Function Documentation
index()
size_t thorin::IPass::index () const inline
Definition at line 25 of file pass.h.
Referenced by thorin::Pass::as_proxy(), thorin::FPPass< P, N >::data(), and thorin::Pass::isa_proxy().
man() [1/2]
PassMan & thorin::IPass::man () inline
Definition at line 22 of file pass.h.
Referenced by thorin::RWPass< N >::curr_nom(), thorin::FPPass< P, N >::curr_undo(), thorin::RWPass< N >::inspect(), thorin::FPPass< P, N >::states(), thorin::FPPass< P, N >::undo_visit(), and thorin::Pass::world().
man() [2/2]
const PassMan & thorin::IPass::man () const inline
Definition at line 23 of file pass.h.
name()
const char * thorin::IPass::name () const inline
Definition at line 24 of file pass.h.
The documentation for this class was generated from the following files:
/home/runner/work/thorin2/thorin2/thorin/pass/pass.h
/home/runner/work/thorin2/thorin2/thorin/pass/pass.cpp