Thorin: thorin::Dumper Class Reference
thorin::Dumper Class Reference
Public Member Functions
Dumper (std::ostream &os, size_t max)
void run (const DepNode *node=nullptr)
void recurse (const Def *)
void recurse (Defs defs)
void dump (const DepNode *n)
void dump_ptrn (const Def *, const Def *)
void dump (const DepNode *, Lam *)
Static Public Member Functions
static std::string id (const Def *def)
static std::string_view external (const Def *def)
Public Attributes
std::ostream & os
Tab tab
size_t max
unique_queue< NomSet > noms
DefSet defs
Detailed Description
Definition at line 164 of file dump.cpp.
Constructor & Destructor Documentation
Dumper()
thorin::Dumper::Dumper (std::ostream & os, size_t max) inline
Definition at line 166 of file dump.cpp.
Member Function Documentation
dump() [1/2]
void thorin::Dumper::dump (const DepNode * node, Lam * lam)
Definition at line 293 of file dump.cpp.
References thorin::Lam::body(), thorin::DepNode::children(), thorin::Pi::codom(), thorin::Pi::dom(), dump_ptrn(), external(), thorin::Pi::is_cn(), thorin::Def::is_set(), thorin::Tab::lnprint(), noms, thorin::Def::ops(), os, thorin::Tab::print(), thorin::unique_queue< Set >::push(), recurse(), run(), tab, thorin::Lam::type(), and thorin::Def::var().
dump() [2/2]
void thorin::Dumper::dump (const DepNode * n)
Definition at line 249 of file dump.cpp.
References thorin::isa_decl(), thorin::DepNode::nom(), noms, thorin::unique_queue< Set >::push(), and run().
Referenced by run().
dump_ptrn()
void thorin::Dumper::dump_ptrn (const Def * def, const Def * type)
Definition at line 278 of file dump.cpp.
References dump_ptrn(), os, thorin::print(), thorin::Def::proj(), thorin::Def::projs(), and thorin::Def::unique_name().
Referenced by dump(), and dump_ptrn().
external()
static std::string_view thorin::Dumper::external (const Def * def) inline static
Definition at line 184 of file dump.cpp.
References thorin::Def::is_external().
Referenced by dump(), and run().
id()
static std::string thorin::Dumper::id (const Def * def) inline static
Definition at line 179 of file dump.cpp.
References thorin::Def::is_external(), thorin::Def::is_set(), thorin::RuntimeCast< Base >::isa(), thorin::Def::name(), and thorin::Def::unique_name().
recurse() [1/2]
void thorin::Dumper::recurse (const Def * def)
Definition at line 256 of file dump.cpp.
References defs, thorin::isa_decl(), thorin::let(), thorin::Tab::lnprint(), max, noms, thorin::clos::op(), os, thorin::Def::partial_ops(), thorin::unique_queue< Set >::push(), recurse(), thorin::ArrayRef< T >::skip_front(), and tab.
Referenced by dump(), recurse(), run(), and thorin::Def::stream().
recurse() [2/2]
void thorin::Dumper::recurse (Defs defs) inline
Definition at line 172 of file dump.cpp.
References defs, and recurse().
run()
void thorin::Dumper::run (const DepNode * node = nullptr)
Definition at line 196 of file dump.cpp.
References dump(), thorin::e, thorin::unique_queue< Set >::empty(), external(), thorin::Tab::lnprint(), noms, os, thorin::unique_queue< Set >::pop(), thorin::print(), thorin::Tab::print(), recurse(), tab, and thorin::unreachable().
Referenced by dump(), and thorin::Def::stream().
Member Data Documentation
defs
DefSet thorin::Dumper::defs
Definition at line 193 of file dump.cpp.
Referenced by recurse().
max
size_t thorin::Dumper::max
Definition at line 191 of file dump.cpp.
Referenced by recurse().
noms
unique_queue<NomSet> thorin::Dumper::noms
Definition at line 192 of file dump.cpp.
Referenced by dump(), recurse(), run(), and thorin::Def::stream().
os
std::ostream& thorin::Dumper::os
Definition at line 189 of file dump.cpp.
Referenced by dump(), dump_ptrn(), recurse(), and run().
tab
Tab thorin::Dumper::tab
Definition at line 190 of file dump.cpp.
Referenced by dump(), recurse(), and run().
The documentation for this class was generated from the following file:
/home/runner/work/thorin2/thorin2/thorin/dump.cpp