Thorin: thorin::clos::ClosLit Class Reference
thorin::clos::ClosLit Class Reference
Wrapper around a Def that can be used to match closures (see isa_clos_lit).
#include <dialects/clos/clos.h>
Public Types
using Clos = thorin::clos::clos
Public Member Functions
operator bool () const
operator const Tuple * ()
const Tuple * operator-> ()
Getters
const Sigma * type ()
const Def * env ()
const Def * env_type ()
const Def * fnc ()
const Pi * fnc_type ()
Lam * fnc_as_lam ()
const Def * env_var ()
const Def * ret_var ()
Properties
bool is_returning ()
bool is_basicblock ()
Clos get ()
Clos annotation. These should appear in front of the code-part.
Friends
ClosLit isa_clos_lit (const Def *, bool)
Tries to match a closure literal.
Detailed Description
Wrapper around a Def that can be used to match closures (see isa_clos_lit).
Definition at line 30 of file clos.h.
Member Typedef Documentation
Clos
using thorin::clos::ClosLit::Clos = thorin::clos::clos
Definition at line 32 of file clos.h.
Member Function Documentation
env()
const Def * thorin::clos::ClosLit::env ()
Definition at line 99 of file clos_conv.cpp.
References thorin::clos::clos_unpack().
Referenced by env_type().
env_type()
const Def * thorin::clos::ClosLit::env_type () inline
Definition at line 42 of file clos.h.
References env(), and thorin::Def::type().
env_var()
const Def * thorin::clos::ClosLit::env_var ()
Definition at line 115 of file clos_conv.cpp.
References thorin::clos::Clos_Env_Param, and thorin::Def::var().
fnc()
const Def * thorin::clos::ClosLit::fnc ()
Definition at line 104 of file clos_conv.cpp.
References thorin::clos::clos_unpack().
Referenced by fnc_type().
fnc_as_lam()
Lam * thorin::clos::ClosLit::fnc_as_lam ()
Definition at line 109 of file clos_conv.cpp.
References thorin::f.
Referenced by ret_var().
fnc_type()
const Pi * thorin::clos::ClosLit::fnc_type () inline
Definition at line 45 of file clos.h.
References fnc(), thorin::RuntimeCast< Base >::isa(), and thorin::Def::type().
Referenced by is_basicblock(), and is_returning().
get()
Clos thorin::clos::ClosLit::get () inline
Clos annotation. These should appear in front of the code-part.
Definition at line 65 of file clos.h.
is_basicblock()
bool thorin::clos::ClosLit::is_basicblock () inline
Definition at line 64 of file clos.h.
References fnc_type(), and thorin::Pi::is_basicblock().
is_returning()
bool thorin::clos::ClosLit::is_returning () inline
Definition at line 63 of file clos.h.
References fnc_type(), and thorin::Pi::is_returning().
operator bool()
thorin::clos::ClosLit::operator bool () const inline
Definition at line 52 of file clos.h.
operator const Tuple *()
thorin::clos::ClosLit::operator const Tuple * () inline
Definition at line 54 of file clos.h.
operator->()
const Tuple * thorin::clos::ClosLit::operator-> () inline
Definition at line 56 of file clos.h.
ret_var()
const Def * thorin::clos::ClosLit::ret_var () inline
Definition at line 49 of file clos.h.
References fnc_as_lam(), and thorin::Lam::ret_var().
type()
const Sigma * thorin::clos::ClosLit::type () inline
Definition at line 36 of file clos.h.
References thorin::RuntimeCast< Base >::isa(), and thorin::Def::type().
Friends And Related Function Documentation
isa_clos_lit
ClosLit isa_clos_lit (const Def * def, bool fn_isa_lam = true) friend
Tries to match a closure literal.
Definition at line 85 of file clos_conv.cpp.
The documentation for this class was generated from the following files:
dialects/clos/clos.h
dialects/clos/phase/clos_conv.cpp