MimIR: mim::Match< Id, D > Class Template Reference
mim::Match< Id, D > Class Template Reference
#include <mim/axiom.h>
Public Member Functions
Match ()=default
Match (const Axiom *axiom, const D *def)
Getters
const Axiom * axiom () const
const D * operator-> () const
operator const D * () const
operator bool ()
Axiom Name
See also
annex_name "Annex Name"
auto plugin () const
auto tag () const
auto sub () const
auto base () const
auto id () const
Axiom::flags cast to Id.
Detailed Description
template<class Id, class D>
class mim::Match< Id, D >
Definition at line 76 of file axiom.h.
Constructor & Destructor Documentation
Match() [1/2]
template<class Id , class D > mim::Match< Id, D >::Match () default
Match() [2/2]
template<class Id , class D > mim::Match< Id, D >::Match (const Axiom * axiom, const D * def) inline
Definition at line 82 of file axiom.h.
Member Function Documentation
axiom()
template<class Id , class D > const Axiom * mim::Match< Id, D >::axiom () const inline
Definition at line 88 of file axiom.h.
Referenced by mim::Match< Id, D >::base(), mim::Match< Id, D >::id(), mim::Match< Id, D >::plugin(), mim::Match< Id, D >::sub(), and mim::Match< Id, D >::tag().
base()
template<class Id , class D > auto mim::Match< Id, D >::base () const inline
See also
exiom::base.
Definition at line 100 of file axiom.h.
References mim::Match< Id, D >::axiom(), and mim::Axiom::sub().
id()
template<class Id , class D > auto mim::Match< Id, D >::id () const inline
Axiom::flags cast to Id.
Definition at line 101 of file axiom.h.
References mim::Match< Id, D >::axiom().
operator bool()
template<class Id , class D > mim::Match< Id, D >::operator bool () inline explicit
Definition at line 91 of file axiom.h.
operator const D *()
template<class Id , class D > mim::Match< Id, D >::operator const D * () const inline
Definition at line 90 of file axiom.h.
operator->()
template<class Id , class D > const D * mim::Match< Id, D >::operator-> () const inline
Definition at line 89 of file axiom.h.
plugin()
template<class Id , class D > auto mim::Match< Id, D >::plugin () const inline
See also
Axiom::plugin.
Definition at line 97 of file axiom.h.
References mim::Match< Id, D >::axiom(), and mim::Axiom::plugin().
sub()
template<class Id , class D > auto mim::Match< Id, D >::sub () const inline
See also
Axiom::sub.
Definition at line 99 of file axiom.h.
References mim::Match< Id, D >::axiom(), and mim::Axiom::sub().
tag()
template<class Id , class D > auto mim::Match< Id, D >::tag () const inline
See also
Axiom::tag.
Definition at line 98 of file axiom.h.
References mim::Match< Id, D >::axiom(), and mim::Axiom::tag().
The documentation for this class was generated from the following file:
include/mim/axiom.h