Thorin: thorin::plug::mem::SSAConstr Class Reference
thorin::plug::mem::SSAConstr Class Reference
SSA construction algorithm that promotes slots, loads, and stores to SSA values.
#include <thorin/plug/mem/pass/ssa_constr.h>
Classes
struct Info
Public Types
enum : u32 {
Phixy ,
Sloxy ,
Traxy
}
using Data = GIDNodeMap< Lam *, Info >
Public Types inherited from thorin::FPPass< SSAConstr, Lam >
using Super = RWPass< SSAConstr, Lam >
using Data = std::tuple<>
Default.
Public Member Functions
SSAConstr (PassMan &man, EtaExp *eta_exp)
Public Member Functions inherited from thorin::FPPass< SSAConstr, Lam >
FPPass (PassMan &man, std::string_view name)
bool fixed_point () const override
Public Member Functions inherited from thorin::RWPass< P, M >
RWPass (PassMan &man, std::string_view name)
bool inspect () const override
Should the PassMan even consider this pass?
M * curr_mut () const
Public Member Functions inherited from thorin::Pass
Pass (PassMan &, std::string_view name)
virtual ~Pass ()=default
World & world ()
PassMan & man ()
const PassMan & man () const
std::string_view name () const
size_t index () const
virtual Ref rewrite (const Var *var)
virtual undo_t analyze (const Var *)
virtual void prepare ()
Invoked once before entering the main rewrite loop.
const Proxy * proxy (Ref type, Defs ops, u32 tag=0)
const Proxy * isa_proxy (Ref def, u32 tag=0)
Check whether given def is a Proxy whose Proxy::pass matches this Pass's IPass::index.
const Proxy * as_proxy (Ref def, u32 tag=0)
Private Member Functions
PassMan hooks
void enter () override
Invoked just before Pass::rewriteing PassMan::curr_mut's body.
Ref rewrite (const Proxy *) override
Ref rewrite (Ref) override
undo_t analyze (const Proxy *) override
undo_t analyze (Ref) override
SSA construction helpers - see paper
Additional Inherited Members
Protected Member Functions inherited from thorin::FPPass< SSAConstr, Lam >
const auto & states () const
auto & states ()
auto & data ()
auto & data ()
auto & data (const K &key)
Use this for your convenience if P::Data is a map.
auto & data (const K &key)
Use this for your convenience if P::Data<I> is a map.
undo_t curr_undo () const
Current undo point.
undo_t undo_visit (Def *mut) const
Retrieves the point to backtrack to just before mut was seen the very first time.
undo_t undo_enter (Def *mut) const
Retrieves the point to backtrack to just before rewriting mut's body.
Detailed Description
SSA construction algorithm that promotes slots, loads, and stores to SSA values.
This is loosely based upon: "Simple and Efficient Construction of Static Single Assignment Form" by Braun, Buchwald, Hack, Leißa, Mallon, Zwinkau.
Definition at line 15 of file ssa_constr.h.
Class Documentation
thorin::plug::mem::SSAConstr::Info
struct thorin::plug::mem::SSAConstr::Info
Definition at line 23 of file ssa_constr.h.
Class Members
Lam * pred = nullptr
GIDSet< const Proxy * > writable
Member Typedef Documentation
Data
using thorin::plug::mem::SSAConstr::Data = GIDNodeMap<Lam*, Info>
Definition at line 28 of file ssa_constr.h.
Member Enumeration Documentation
anonymous enum
anonymous enum : u32
Enumerator
Phixy
Sloxy
Traxy
Definition at line 21 of file ssa_constr.h.
Constructor & Destructor Documentation
SSAConstr()
thorin::plug::mem::SSAConstr::SSAConstr (PassMan & man, EtaExp * eta_exp) inline
Definition at line 17 of file ssa_constr.h.
Member Function Documentation
analyze() [1/2]
undo_t thorin::plug::mem::SSAConstr::analyze (const Proxy * proxy) override private virtual
Reimplemented from thorin::Pass.
Definition at line 139 of file ssa_constr.cpp.
References thorin::Def::as_mut(), thorin::No_Undo, thorin::Def::op(), Phixy, thorin::Pass::proxy(), Sloxy, thorin::Proxy::tag(), thorin::FPPass< SSAConstr, Lam >::undo_enter(), thorin::FPPass< SSAConstr, Lam >::undo_visit(), and thorin::Pass::world().
analyze() [2/2]
undo_t thorin::plug::mem::SSAConstr::analyze (Ref def) override private virtual
Reimplemented from thorin::Pass.
Definition at line 159 of file ssa_constr.cpp.
References thorin::RWPass< P, M >::curr_mut(), thorin::FPPass< SSAConstr, Lam >::data(), thorin::Lam::isa_basicblock(), thorin::isa_callee(), thorin::Def::isa_mut(), thorin::isa_workable(), thorin::No_Undo, thorin::Def::num_ops(), thorin::Def::op(), and thorin::Pass::world().
enter()
void thorin::plug::mem::SSAConstr::enter () override private virtual
Invoked just before Pass::rewriteing PassMan::curr_mut's body.
Note
This is invoked when seeing the inside of a mutable the first time. This is often too late, as you usually want to do something when you see a mutable the first time from the outside. This means that this PassMan::curr_mut has already been encountered elsewhere. Otherwise, we wouldn't have seen PassMan::curr_mut to begin with (unless it is Def::is_external).
Reimplemented from thorin::Pass.
Definition at line 17 of file ssa_constr.cpp.
References thorin::RWPass< P, M >::curr_mut().
rewrite() [1/2]
Ref thorin::plug::mem::SSAConstr::rewrite (const Proxy * proxy) override private virtual
Reimplemented from thorin::Pass.
Definition at line 19 of file ssa_constr.cpp.
References thorin::Pass::as_proxy(), thorin::RWPass< P, M >::curr_mut(), thorin::Def::num_ops(), thorin::Def::op(), thorin::Pass::proxy(), Sloxy, thorin::Proxy::tag(), Traxy, and thorin::Pass::world().
rewrite() [2/2]
Ref thorin::plug::mem::SSAConstr::rewrite (Ref def) override private virtual
Reimplemented from thorin::Pass.
Definition at line 30 of file ssa_constr.cpp.
References thorin::RWPass< P, M >::curr_mut(), thorin::FPPass< SSAConstr, Lam >::data(), thorin::isa_apped_mut_lam(), thorin::Def::isa_mut(), thorin::Pass::isa_proxy(), thorin::isa_workable(), thorin::Def::num_ops(), thorin::Def::op(), thorin::plug::mem::op_remem(), thorin::Def::projs(), thorin::EtaExp::proxy(), thorin::Pass::proxy(), thorin::Def::refine(), thorin::Def::set(), Sloxy, thorin::World::tuple(), and thorin::Pass::world().
The documentation for this class was generated from the following files:
include/thorin/plug/mem/pass/ssa_constr.h
src/thorin/plug/mem/pass/ssa_constr.cpp