Thorin: thorin::TuplePtrn Class Reference
thorin::TuplePtrn Class Reference
#include <thorin/fe/ast.h>
Public Member Functions
TuplePtrn (Dbg dbg, bool rebind, Ptrns &&ptrns, const Def *type, std::vector< Infer * > &&infers, Def *decl)
const Ptrns & ptrns () const
const Ptrn * ptrn (size_t i) const
size_t num_ptrns () const
void bind (Scopes &, const Def *, bool rebind=false) const override
const Def * type (World &, Def2Fields &) const override
Public Member Functions inherited from thorin::Ptrn
Ptrn (Dbg dbg, bool rebind, const Def *type)
virtual ~Ptrn ()
Dbg dbg () const
Loc loc () const
Sym sym () const
bool rebind () const
bool is_anonymous () const
Additional Inherited Members
Protected Attributes inherited from thorin::Ptrn
Dbg dbg_
bool rebind_
const Def * type_
Detailed Description
Definition at line 56 of file ast.h.
Constructor & Destructor Documentation
TuplePtrn()
thorin::TuplePtrn::TuplePtrn (Dbg dbg, bool rebind, Ptrns && ptrns, const Def * type, std::vector< Infer * > && infers, Def * decl) inline
Definition at line 58 of file ast.h.
Member Function Documentation
bind()
void thorin::TuplePtrn::bind (Scopes & scopes, const Def * def, bool rebind = false) const override virtual
Implements thorin::Ptrn.
Definition at line 20 of file ast.cpp.
References thorin::Scopes::bind(), thorin::Ptrn::bind(), thorin::Ptrn::dbg(), thorin::Ptrn::loc(), num_ptrns(), thorin::Def::proj(), ptrn(), thorin::Ptrn::rebind(), thorin::Def::set(), and thorin::Ptrn::sym().
num_ptrns()
size_t thorin::TuplePtrn::num_ptrns () const inline
Definition at line 66 of file ast.h.
References ptrns().
Referenced by bind(), and type().
ptrn()
const Ptrn * thorin::TuplePtrn::ptrn (size_t i) const inline
Definition at line 65 of file ast.h.
Referenced by bind(), and type().
ptrns()
const Ptrns & thorin::TuplePtrn::ptrns () const inline
Definition at line 64 of file ast.h.
Referenced by num_ptrns().
type()
const Def * thorin::TuplePtrn::type (World & world, Def2Fields & def2fields) const override virtual
Implements thorin::Ptrn.
Definition at line 37 of file ast.cpp.
References thorin::assert_emplace(), thorin::error(), thorin::Def::isa_mut(), thorin::Ptrn::loc(), thorin::World::mut_sigma(), num_ptrns(), ptrn(), thorin::ScopeRewriter::rewrite(), thorin::Def::set(), thorin::Sigma::set(), thorin::World::sigma(), thorin::Ptrn::sym(), thorin::Type, thorin::Ptrn::type(), type(), thorin::Ptrn::type_, and thorin::World::umax().
Referenced by type().
The documentation for this class was generated from the following files:
include/thorin/fe/ast.h
src/thorin/fe/ast.cpp