MimIR: mim::ast::AliasPtrn Class Reference
mim::ast::AliasPtrn Class Reference
ptrn as id
#include <mim/ast/ast.h>
Public Member Functions
AliasPtrn (Loc loc, Ptr< Ptrn > &&ptrn, Dbg dbg)
const Ptrn * ptrn () const
Dbg dbg () const
bool is_implicit () const override
void bind (Scopes &, bool rebind, bool quiet) const override
const Def * emit_value (Emitter &, const Def *) const override
const Def * emit_type (Emitter &) const override
std::ostream & stream (Tab &, std::ostream &) const override
Public Member Functions inherited from mim::ast::Ptrn
Ptrn (Loc loc)
Public Member Functions inherited from mim::ast::Decl
const Def * def () const
Public Member Functions inherited from mim::ast::Node
Loc loc () const
void dump () const
Additional Inherited Members
Static Public Member Functions inherited from mim::ast::Ptrn
static Ptr< Expr > to_expr (AST &, Ptr< Ptrn > &&)
static Ptr< Ptrn > to_ptrn (Ptr< Expr > &&)
Protected Member Functions inherited from mim::ast::Decl
Decl (Loc loc)
Protected Member Functions inherited from mim::ast::Node
Node (Loc loc)
virtual ~Node ()
Protected Attributes inherited from mim::ast::Decl
const Def * def_ = nullptr
Detailed Description
ptrn as id
Definition at line 268 of file ast.h.
Constructor & Destructor Documentation
AliasPtrn()
mim::ast::AliasPtrn::AliasPtrn (Loc loc, Ptr< Ptrn > && ptrn, Dbg dbg) inline
Definition at line 270 of file ast.h.
References dbg(), mim::ast::Node::loc(), mim::ast::Ptrn::Ptrn(), and ptrn().
Member Function Documentation
bind()
void mim::ast::AliasPtrn::bind (Scopes & s, bool rebind, bool quiet) const override virtual
Implements mim::ast::Ptrn.
Definition at line 105 of file bind.cpp.
References mim::ast::Ptrn::bind(), dbg(), and ptrn().
dbg()
Dbg mim::ast::AliasPtrn::dbg () const inline
Definition at line 276 of file ast.h.
Referenced by AliasPtrn(), bind(), emit_value(), and stream().
emit_type()
const Def * mim::ast::AliasPtrn::emit_type (Emitter & e) const override virtual
Implements mim::ast::Ptrn.
Definition at line 90 of file emit.cpp.
References mim::ast::Ptrn::emit_type(), and ptrn().
emit_value()
const Def * mim::ast::AliasPtrn::emit_value (Emitter & e, const Def * def) const override virtual
Implements mim::ast::Ptrn.
Definition at line 67 of file emit.cpp.
References dbg(), mim::ast::Decl::def(), mim::ast::Decl::def_, mim::ast::Ptrn::emit_value(), ptrn(), and mim::Def::set().
is_implicit()
bool mim::ast::AliasPtrn::is_implicit () const inline override virtual
Reimplemented from mim::ast::Ptrn.
Definition at line 277 of file ast.h.
References mim::ast::Ptrn::is_implicit(), and ptrn().
ptrn()
const Ptrn * mim::ast::AliasPtrn::ptrn () const inline
Definition at line 275 of file ast.h.
References mim::ast::Ptrn::Ptrn().
Referenced by AliasPtrn(), bind(), emit_type(), emit_value(), is_implicit(), and stream().
stream()
std::ostream & mim::ast::AliasPtrn::stream (Tab & tab, std::ostream & os) const override virtual
Implements mim::ast::Node.
Definition at line 57 of file stream.cpp.
References dbg(), mim::print(), and ptrn().
The documentation for this class was generated from the following files:
include/mim/ast/ast.h
src/mim/ast/bind.cpp
src/mim/ast/emit.cpp
src/mim/ast/stream.cpp