MimIR: mim::ast::Emitter Class Reference
mim::ast::Emitter Class Reference
Public Member Functions
Emitter (AST &ast)
AST & ast () const
World & world ()
Driver & driver ()
void register_annex (AnnexInfo *annex, sub_t sub, const Def *def)
Public Attributes
absl::node_hash_map< Sigma *, fe::SymMap< size_t >, GIDHash< const Def * > > sigma2sym2idx
Detailed Description
Definition at line 12 of file emit.cpp.
Constructor & Destructor Documentation
Emitter()
mim::ast::Emitter::Emitter (AST & ast) inline
Definition at line 14 of file emit.cpp.
References ast().
Member Function Documentation
ast()
AST & mim::ast::Emitter::ast () const inline
Definition at line 17 of file emit.cpp.
Referenced by Emitter(), and world().
driver()
Driver & mim::ast::Emitter::driver () inline
Definition at line 19 of file emit.cpp.
References mim::World::driver(), and world().
register_annex()
void mim::ast::Emitter::register_annex (AnnexInfo * annex, sub_t sub, const Def * def) inline
Definition at line 21 of file emit.cpp.
References mim::ast::AnnexInfo::id, mim::World::register_annex(), and world().
world()
World & mim::ast::Emitter::world () inline
Definition at line 18 of file emit.cpp.
References ast(), and mim::ast::AST::world().
Referenced by driver(), and register_annex().
Member Data Documentation
sigma2sym2idx
absl::node_hash_map<Sigma*, fe::SymMap<size_t>, GIDHash<const Def*> > mim::ast::Emitter::sigma2sym2idx
Definition at line 28 of file emit.cpp.
The documentation for this class was generated from the following file:
src/mim/ast/emit.cpp