Thorin: thorin::RWPass< P, N > Class Template Reference
thorin::RWPass< P, N > Class Template Reference
Inherit from this class if your Pass does not need state and a fixed-point iteration.
#include <thorin/pass/pass.h>
Public Member Functions
RWPass (PassMan &man, std::string_view name)
bool inspect () const override
Should the PassMan even consider this pass?
N * curr_nom () const
Public Member Functions inherited from thorin::Pass
Pass (PassMan &, std::string_view name)
virtual ~Pass ()=default
World & world ()
PassMan & man ()
const PassMan & man () const
std::string_view name () const
size_t index () const
virtual const Def * rewrite (const Def *def)
virtual const Def * rewrite (const Var *var)
virtual const Def * rewrite (const Proxy *proxy)
virtual undo_t analyze (const Def *)
virtual undo_t analyze (const Var *)
virtual undo_t analyze (const Proxy *)
virtual bool fixed_point () const
virtual void enter ()
Invoked just before Pass::rewriteing PassMan::curr_nom's body.
const Proxy * proxy (const Def *type, Defs ops, u32 tag=0, const Def *dbg={})
const Proxy * isa_proxy (const Def *def, u32 tag=0)
Check whether given def is a Proxy whose Proxy::pass matches this Pass's IPass::index.
const Proxy * as_proxy (const Def *def, u32 tag=0)
Detailed Description
template<class P, class N>
class thorin::RWPass< P, N >
Inherit from this class if your Pass does not need state and a fixed-point iteration.
Definition at line 214 of file pass.h.
Constructor & Destructor Documentation
RWPass()
template<class P , class N > thorin::RWPass< P, N >::RWPass (PassMan & man, std::string_view name) inline
Definition at line 216 of file pass.h.
Member Function Documentation
curr_nom()
template<class P , class N > N * thorin::RWPass< P, N >::curr_nom () const inline
Definition at line 226 of file pass.h.
References thorin::PassMan::curr_nom(), and thorin::Pass::man().
Referenced by thorin::FPPass< P, N >::undo_enter().
inspect()
template<class P , class N > bool thorin::RWPass< P, N >::inspect () const inline override virtual
Should the PassMan even consider this pass?
Implements thorin::Pass.
Definition at line 219 of file pass.h.
References thorin::PassMan::curr_nom(), and thorin::Pass::man().
The documentation for this class was generated from the following file:
/home/runner/work/thorin2/thorin2/thorin/pass/pass.h