MimIR: mim::plug::autodiff::AutoDiffZeroCleanup Class Reference
mim::plug::autodiff::AutoDiffZeroCleanup Class Reference
Replaces remaining zeros (not resolvable) with ⊥.
#include <mim/plug/autodiff/pass/autodiff_zero_cleanup.h>
Public Member Functions
AutoDiffZeroCleanup (PassMan &man)
Ref rewrite (Ref) override
Public Member Functions inherited from mim::RWPass< AutoDiffZeroCleanup, Lam >
RWPass (PassMan &man, std::string_view name)
bool inspect () const override
Should the PassMan even consider this pass?
Lam * curr_mut () const
Public Member Functions inherited from mim::Pass
Pass (PassMan &, std::string_view name)
virtual ~Pass ()=default
World & world ()
PassMan & man ()
const PassMan & man () const
std::string_view name () const
size_t index () const
virtual Ref rewrite (const Var *var)
virtual Ref rewrite (const Proxy *proxy)
virtual undo_t analyze (Ref)
virtual undo_t analyze (const Var *)
virtual undo_t analyze (const Proxy *)
virtual bool fixed_point () const
virtual void enter ()
Invoked just before Pass::rewriteing PassMan::curr_mut's body.
virtual void prepare ()
Invoked once before entering the main rewrite loop.
const Proxy * proxy (Ref type, Defs ops, u32 tag=0)
const Proxy * isa_proxy (Ref def, u32 tag=0)
Check whether given def is a Proxy whose Proxy::pass matches this Pass's IPass::index.
const Proxy * as_proxy (Ref def, u32 tag=0)
Detailed Description
Replaces remaining zeros (not resolvable) with ⊥.
Definition at line 9 of file autodiff_zero_cleanup.h.
Constructor & Destructor Documentation
AutoDiffZeroCleanup()
mim::plug::autodiff::AutoDiffZeroCleanup::AutoDiffZeroCleanup (PassMan & man) inline
Definition at line 11 of file autodiff_zero_cleanup.h.
Member Function Documentation
rewrite()
Ref mim::plug::autodiff::AutoDiffZeroCleanup::rewrite (Ref def) override virtual
Reimplemented from mim::Pass.
Definition at line 14 of file autodiff_zero_cleanup.cpp.
References mim::World::bot(), mim::match(), and mim::Pass::world().
The documentation for this class was generated from the following files:
include/mim/plug/autodiff/pass/autodiff_zero_cleanup.h
src/mim/plug/autodiff/pass/autodiff_zero_cleanup.cpp