MimIR: mim::Driver::Imports Class Reference
mim::Driver::Imports Class Reference
#include <mim/driver.h>
Public Member Functions
Imports (Driver &driver)
const fs::path * add (fs::path, Sym)
Yields a fs::path*, if not already added that you can use in Location; returns nullptr otherwise.
Get imports
const auto & path2sym ()
auto paths ()
auto syms ()
Iterators
auto begin () const
auto end () const
Detailed Description
Definition at line 48 of file driver.h.
Constructor & Destructor Documentation
Imports()
mim::Driver::Imports::Imports (Driver & driver) inline
Definition at line 50 of file driver.h.
References mim::Driver::Driver().
Member Function Documentation
add()
const fs::path * mim::Driver::Imports::add (fs::path path, Sym sym)
Yields a fs::path*, if not already added that you can use in Location; returns nullptr otherwise.
Definition at line 10 of file driver.cpp.
References paths().
begin()
auto mim::Driver::Imports::begin () const inline
Definition at line 62 of file driver.h.
end()
auto mim::Driver::Imports::end () const inline
Definition at line 63 of file driver.h.
path2sym()
const auto & mim::Driver::Imports::path2sym () inline
Definition at line 55 of file driver.h.
paths()
auto mim::Driver::Imports::paths () inline
Definition at line 56 of file driver.h.
Referenced by add().
syms()
auto mim::Driver::Imports::syms () inline
Definition at line 57 of file driver.h.
The documentation for this class was generated from the following files:
include/mim/driver.h
src/mim/driver.cpp