Thorin: thorin::PipelineBuilder Class Reference
thorin::PipelineBuilder Class Reference
#include <thorin/pass/pipelinebuilder.h>
Public Member Functions
PipelineBuilder ()
int last_phase ()
template<class P , class... Args>
void add_pass (const Def *def, Args &&... args)
void remember_pass_instance (Pass *p, const Def *)
Pass * get_pass_instance (const Def *)
void append_phase_end (PhaseBuilder, int priority=Pass_Default_Priority)
void append_pass_in_end (PassBuilder, int priority=Pass_Default_Priority)
void append_pass_after_end (PassBuilder, int priority=Pass_Default_Priority)
void append_phase (int i, PhaseBuilder, int priority=Pass_Default_Priority)
void extend_opt_phase (int i, PassBuilder, int priority=Pass_Default_Priority)
void extend_opt_phase (PassBuilder &&)
void add_opt (int i)
void extend_codegen_prep_phase (PassBuilder &&)
std::unique_ptr< PassMan > opt_phase (int i, World &world)
void buildPipeline (Pipeline &pipeline)
void buildPipelinePart (int i, Pipeline &pipeline)
void add_opt (PassMan man)
std::vector< int > passes ()
std::vector< int > phases ()
Detailed Description
Definition at line 32 of file pipelinebuilder.h.
Constructor & Destructor Documentation
PipelineBuilder()
thorin::PipelineBuilder::PipelineBuilder () inline explicit
Definition at line 34 of file pipelinebuilder.h.
Member Function Documentation
add_opt() [1/2]
void thorin::PipelineBuilder::add_opt (int i)
Definition at line 63 of file pipelinebuilder.cpp.
References thorin::PassMan::add(), extend_opt_phase(), and thorin::Pass_Internal_Priority.
Referenced by thorin::optimize().
add_opt() [2/2]
void thorin::PipelineBuilder::add_opt (PassMan man)
add_pass()
template<class P , class... Args> void thorin::PipelineBuilder::add_pass (const Def * def, Args &&... args) inline
Definition at line 40 of file pipelinebuilder.h.
References thorin::PassMan::add(), append_pass_in_end(), and remember_pass_instance().
append_pass_after_end()
void thorin::PipelineBuilder::append_pass_after_end (PassBuilder pass, int priority = Pass_Default_Priority)
Definition at line 41 of file pipelinebuilder.cpp.
References extend_opt_phase(), and last_phase().
append_pass_in_end()
void thorin::PipelineBuilder::append_pass_in_end (PassBuilder pass, int priority = Pass_Default_Priority)
Definition at line 38 of file pipelinebuilder.cpp.
References extend_opt_phase(), and last_phase().
Referenced by add_pass().
append_phase()
void thorin::PipelineBuilder::append_phase (int i, PhaseBuilder extension, int priority = Pass_Default_Priority)
Definition at line 51 of file pipelinebuilder.cpp.
Referenced by append_phase_end().
append_phase_end()
void thorin::PipelineBuilder::append_phase_end (PhaseBuilder phase, int priority = Pass_Default_Priority)
Definition at line 35 of file pipelinebuilder.cpp.
References append_phase(), and last_phase().
Referenced by add_passes().
buildPipeline()
void thorin::PipelineBuilder::buildPipeline (Pipeline & pipeline)
Definition at line 106 of file pipelinebuilder.cpp.
References buildPipelinePart(), and phases().
Referenced by thorin::optimize().
buildPipelinePart()
void thorin::PipelineBuilder::buildPipelinePart (int i, Pipeline & pipeline)
Definition at line 109 of file pipelinebuilder.cpp.
References thorin::Pipeline::add(), opt_phase(), and thorin::Phase::world().
Referenced by buildPipeline().
extend_codegen_prep_phase()
void thorin::PipelineBuilder::extend_codegen_prep_phase (PassBuilder && extension)
Definition at line 47 of file pipelinebuilder.cpp.
References thorin::Codegen_Prep_Phase, and extend_opt_phase().
extend_opt_phase() [1/2]
void thorin::PipelineBuilder::extend_opt_phase (int i, PassBuilder extension, int priority = Pass_Default_Priority)
Definition at line 56 of file pipelinebuilder.cpp.
Referenced by add_opt(), append_pass_after_end(), append_pass_in_end(), extend_codegen_prep_phase(), extend_opt_phase(), and thorin::optimize().
extend_opt_phase() [2/2]
void thorin::PipelineBuilder::extend_opt_phase (PassBuilder && extension)
Definition at line 45 of file pipelinebuilder.cpp.
References extend_opt_phase(), and thorin::Opt_Phase.
get_pass_instance()
Pass * thorin::PipelineBuilder::get_pass_instance (const Def * def)
Definition at line 26 of file pipelinebuilder.cpp.
last_phase()
int thorin::PipelineBuilder::last_phase ()
Definition at line 28 of file pipelinebuilder.cpp.
References phases().
Referenced by append_pass_after_end(), append_pass_in_end(), and append_phase_end().
opt_phase()
std::unique_ptr< PassMan > thorin::PipelineBuilder::opt_phase (int i, World & world)
Definition at line 96 of file pipelinebuilder.cpp.
Referenced by buildPipelinePart().
passes()
std::vector< int > thorin::PipelineBuilder::passes ()
Definition at line 77 of file pipelinebuilder.cpp.
phases()
std::vector< int > thorin::PipelineBuilder::phases ()
Definition at line 84 of file pipelinebuilder.cpp.
Referenced by buildPipeline(), and last_phase().
remember_pass_instance()
void thorin::PipelineBuilder::remember_pass_instance (Pass * p, const Def * def)
Definition at line 25 of file pipelinebuilder.cpp.
Referenced by add_pass().
The documentation for this class was generated from the following files:
thorin/pass/pipelinebuilder.h
thorin/pass/pipelinebuilder.cpp