Thorin: thorin::ast::AST Class Reference
thorin::ast::AST Class Reference
#include <thorin/ast/ast.h>
Public Member Functions
AST ()=default
AST (World &world)
AST (AST &&other)
~AST ()
template<class T , class... Args>
auto ptr (Args &&... args)
void bootstrap (Sym plugin, std::ostream &h)
Getters
World & world ()
Driver & driver ()
Error & error ()
const Error & error () const
Sym
Sym sym (const char *s)
Sym sym (std::string_view s)
Sym sym (const std::string &s)
Sym sym_anon ()
"_".
Sym sym_return ()
"return".
Sym sym_error ()
"_error_".
Formatted Output
template<class... Args>
Error & error (Loc loc, const char *fmt, Args &&... args) const
template<class... Args>
Error & warn (Loc loc, const char *fmt, Args &&... args) const
template<class... Args>
Error & note (Loc loc, const char *fmt, Args &&... args) const
Manage Annex
AnnexInfo * name2annex (Dbg dbg, sub_t *)
const auto & plugin2annexes (Sym plugin)
Friends
void swap (AST &a1, AST &a2) noexcept
Detailed Description
Definition at line 48 of file ast.h.
Constructor & Destructor Documentation
AST() [1/3]
thorin::ast::AST::AST () default
AST() [2/3]
thorin::ast::AST::AST (World & world) inline
Definition at line 51 of file ast.h.
AST() [3/3]
thorin::ast::AST::AST (AST && other) inline
Definition at line 53 of file ast.h.
References swap.
~AST()
thorin::ast::AST::~AST ()
Definition at line 9 of file ast.cpp.
References error().
Member Function Documentation
bootstrap()
void thorin::ast::AST::bootstrap (Sym plugin, std::ostream & h)
Definition at line 52 of file ast.cpp.
References thorin::Annex::mangle(), plugin2annexes(), thorin::print(), thorin::Tab::print(), and sym().
driver()
Driver & thorin::ast::AST::driver () inline
Definition at line 62 of file ast.h.
References thorin::World::driver(), and world().
Referenced by thorin::ast::Parser::driver(), thorin::ast::Scopes::driver(), name2annex(), sym(), sym(), and sym().
error() [1/3]
Error & thorin::ast::AST::error () inline
Definition at line 63 of file ast.h.
Referenced by thorin::ast::Scopes::bind(), thorin::ast::Module::compile(), thorin::ast::Scopes::find(), thorin::ast::Parser::import(), thorin::ast::Lexer::lex(), name2annex(), and ~AST().
error() [2/3]
const Error & thorin::ast::AST::error () const inline
Definition at line 64 of file ast.h.
error() [3/3]
template<class... Args> Error & thorin::ast::AST::error (Loc loc, const char * fmt, Args &&... args) const inline
Definition at line 84 of file ast.h.
References thorin::Error::error(), and thorin::fmt().
name2annex()
AnnexInfo * thorin::ast::AST::name2annex (Dbg dbg, sub_t * sub_id)
Definition at line 14 of file ast.cpp.
References driver(), error(), thorin::Annex::mangle(), thorin::Annex::split(), and sym_error().
note()
template<class... Args> Error & thorin::ast::AST::note (Loc loc, const char * fmt, Args &&... args) const inline
Definition at line 86 of file ast.h.
References thorin::fmt(), and thorin::Error::note().
Referenced by thorin::ast::Scopes::bind().
plugin2annexes()
const auto & thorin::ast::AST::plugin2annexes (Sym plugin) inline
Definition at line 93 of file ast.h.
Referenced by bootstrap().
ptr()
template<class T , class... Args> auto thorin::ast::AST::ptr (Args &&... args) inline
Definition at line 77 of file ast.h.
Referenced by thorin::ast::PiExpr::Dom::add_ret(), thorin::ast::IdPtrn::mk_id(), thorin::ast::IdPtrn::mk_type(), and thorin::ast::Ptrn::to_expr().
sym() [1/3]
Sym thorin::ast::AST::sym (const char * s) inline
Definition at line 69 of file ast.h.
References driver().
Referenced by bootstrap(), sym_anon(), sym_error(), and sym_return().
sym() [2/3]
Sym thorin::ast::AST::sym (const std::string & s) inline
Definition at line 71 of file ast.h.
References driver().
sym() [3/3]
Sym thorin::ast::AST::sym (std::string_view s) inline
Definition at line 70 of file ast.h.
References driver().
sym_anon()
Sym thorin::ast::AST::sym_anon () inline
"_".
Definition at line 72 of file ast.h.
References sym().
Referenced by thorin::ast::IdPtrn::mk_type().
sym_error()
Sym thorin::ast::AST::sym_error () inline
"_error_".
Definition at line 74 of file ast.h.
References sym().
Referenced by name2annex().
sym_return()
Sym thorin::ast::AST::sym_return () inline
"return".
Definition at line 73 of file ast.h.
References sym().
Referenced by thorin::ast::PiExpr::Dom::add_ret().
warn()
template<class... Args> Error & thorin::ast::AST::warn (Loc loc, const char * fmt, Args &&... args) const inline
Definition at line 85 of file ast.h.
References thorin::fmt(), and thorin::Error::warn().
world()
World & thorin::ast::AST::world () inline
Definition at line 61 of file ast.h.
Referenced by driver(), and thorin::ast::Emitter::world().
Friends And Related Symbol Documentation
swap
void swap (AST & a1, AST & a2) friend
Definition at line 98 of file ast.h.
Referenced by AST().
The documentation for this class was generated from the following files:
include/thorin/ast/ast.h
src/thorin/ast/ast.cpp