MimIR: mim::ast::Parser Class Reference
mim::ast::Parser Class Reference
Parses Mim code as AST.
#include <mim/ast/parser.h>
Public Member Functions
Parser (AST &ast)
AST & ast ()
Driver & driver ()
Ptr< Module > import (std::string_view sv)
Ptr< Module > import (Dbg, std::ostream *md=nullptr)
Ptr< Module > import (std::istream &, Loc={}, const fs::path *=nullptr, std::ostream *md=nullptr)
Ptr< Module > plugin (Dbg)
Ptr< Module > plugin (const std::string &s)
Ptr< Module > plugin (const char *name)
Detailed Description
Parses Mim code as AST.
The logic behind the various parse methods is as follows:
The parse_* method does not have a std::string_view ctxt parameter:
It's the caller's responsibility to first make appropriate FIRST/FOLLOW checks. Otherwise, an assertion will be triggered in the case of a syntax error.
The parse_* method does have a std::string_view ctxt parameter:
The called method checks this and spits out an appropriate error message using ctxt in the case of a syntax error.
The parse_* method does have a std::string_view ctxt = {} parameter with default argument:
If default argument is elided we have the same behavior as in 1.
If default argument is provided we have the same behavior as in 2.
Definition at line 30 of file parser.h.
Constructor & Destructor Documentation
Parser()
mim::ast::Parser::Parser (AST & ast) inline
Definition at line 34 of file parser.h.
References ast().
Member Function Documentation
ast()
AST & mim::ast::Parser::ast () inline
Definition at line 37 of file parser.h.
Referenced by driver(), import(), and Parser().
driver()
Driver & mim::ast::Parser::driver () inline
Definition at line 38 of file parser.h.
References ast(), and mim::ast::AST::driver().
Referenced by import(), import(), import(), plugin(), plugin(), and plugin().
import() [1/3]
Ptr< Module > mim::ast::Parser::import (Dbg dbg, std::ostream * md = nullptr)
Definition at line 122 of file parser.cpp.
References driver().
import() [2/3]
Ptr< Module > mim::ast::Parser::import (std::istream & is, Loc loc = {}, const fs::path * path = nullptr, std::ostream * md = nullptr)
Definition at line 145 of file parser.cpp.
References ast(), driver(), and mim::ast::AST::error().
import() [3/3]
Ptr< Module > mim::ast::Parser::import (std::string_view sv) inline
Definition at line 39 of file parser.h.
References driver().
plugin() [1/3]
Ptr< Module > mim::ast::Parser::plugin (const char * name) inline
Definition at line 44 of file parser.h.
References driver(), and plugin().
Referenced by plugin().
plugin() [2/3]
Ptr< Module > mim::ast::Parser::plugin (const std::string & s) inline
Definition at line 43 of file parser.h.
References driver(), and plugin().
Referenced by plugin().
plugin() [3/3]
Ptr< Module > mim::ast::Parser::plugin (Dbg dbg)
Definition at line 161 of file parser.cpp.
References driver(), and mim::Driver::load().
The documentation for this class was generated from the following files:
include/mim/ast/parser.h
src/mim/ast/parser.cpp