Thorin: thorin::StringStream Class Reference
thorin::StringStream Class Reference
#include <thorin/util/stream.h>
Public Member Functions
StringStream ()
std::string str () const
Public Member Functions inherited from thorin::Stream
Stream (std::ostream &ostream=std::cout, std::string_view tab={" "}, size_t level=0)
void friend swap (Stream &a, Stream &b)
std::ostream & ostream ()
std::string_view tab () const
size_t level () const
Stream & indent (size_t i=1)
Stream & dedent (size_t i=1)
Stream & endl ()
Stream & flush ()
Stream & fmt (const char *s)
Base case.
template<class T , class... Args>
Stream & fmt (const char *s, T &&t, Args &&... args)
fprintf-like function.
template<class R , class F , bool rangei = false>
Stream & range (const R &r, const char *sep, F f)
template<class R , class F , bool rangei = false>
Stream & range (const R &r, F f)
template<class R , class F >
Stream & rangei (const R &r, const char *sep, F f)
template<class R , class F >
Stream & rangei (const R &r, F f)
template<class R >
Stream & range (const R &r, const char *sep=", ")
Friends
void swap (StringStream &a, StringStream &b)
Additional Inherited Members
Protected Member Functions inherited from thorin::Stream
bool match2nd (const char *next, const char *&s, const char c)
Protected Attributes inherited from thorin::Stream
std::ostream * ostream_
std::string tab_
size_t level_
Detailed Description
Definition at line 103 of file stream.h.
Constructor & Destructor Documentation
StringStream()
thorin::StringStream::StringStream () inline
Definition at line 105 of file stream.h.
Member Function Documentation
str()
std::string thorin::StringStream::str () const inline
Definition at line 108 of file stream.h.
Referenced by thorin::err(), thorin::ll::CodeGen::finalize(), thorin::ll::CodeGen::run(), and thorin::dot::DotEmitter::~DotEmitter().
Friends And Related Function Documentation
swap
void swap (StringStream & a, StringStream & b) friend
Definition at line 110 of file stream.h.
The documentation for this class was generated from the following file:
thorin/util/stream.h