Thorin: thorin::ast::CDecl Class Reference
thorin::ast::CDecl Class Reference
.cfun dbg dom -> codom
#include <thorin/ast/ast.h>
Public Member Functions
CDecl (Loc loc, Tok::Tag tag, Dbg dbg, Ptr< Ptrn > &&dom, Ptr< Expr > &&codom)
Dbg dbg () const
Tok::Tag tag () const
const Ptrn * dom () const
const Expr * codom () const
void bind (Scopes &) const override
void emit (Emitter &) const override
std::ostream & stream (Tab &, std::ostream &) const override
Public Member Functions inherited from thorin::ast::Decl
Ref def () const
Public Member Functions inherited from thorin::ast::Node
Loc loc () const
void dump () const
Additional Inherited Members
Protected Member Functions inherited from thorin::ast::ValDecl
ValDecl (Loc loc)
Protected Member Functions inherited from thorin::ast::Decl
Decl (Loc loc)
Protected Member Functions inherited from thorin::ast::Node
Node (Loc loc)
virtual ~Node ()
Protected Attributes inherited from thorin::ast::Decl
Ref def_ = nullptr
Detailed Description
.cfun dbg dom -> codom
Definition at line 876 of file ast.h.
Constructor & Destructor Documentation
CDecl()
thorin::ast::CDecl::CDecl (Loc loc, Tok::Tag tag, Dbg dbg, Ptr< Ptrn > && dom, Ptr< Expr > && codom) inline
Definition at line 878 of file ast.h.
Member Function Documentation
bind()
void thorin::ast::CDecl::bind (Scopes & s) const override virtual
Implements thorin::ast::ValDecl.
Definition at line 327 of file bind.cpp.
References thorin::ast::Expr::bind(), and thorin::ast::PiExpr::Dom::bind().
codom()
const Expr * thorin::ast::CDecl::codom () const inline
Definition at line 888 of file ast.h.
dbg()
Dbg thorin::ast::CDecl::dbg () const inline
Definition at line 885 of file ast.h.
dom()
const Ptrn * thorin::ast::CDecl::dom () const inline
Definition at line 887 of file ast.h.
emit()
void thorin::ast::CDecl::emit (Emitter & e) const override virtual
Implements thorin::ast::ValDecl.
Definition at line 451 of file emit.cpp.
References thorin::ast::Expr::emit(), and thorin::ast::PiExpr::Dom::emit_type().
stream()
std::ostream & thorin::ast::CDecl::stream (Tab & tab, std::ostream & os) const override virtual
Implements thorin::ast::Node.
Definition at line 212 of file stream.cpp.
References thorin::print().
tag()
Tok::Tag thorin::ast::CDecl::tag () const inline
Definition at line 886 of file ast.h.
The documentation for this class was generated from the following files:
include/thorin/ast/ast.h
src/thorin/ast/bind.cpp
src/thorin/ast/emit.cpp
src/thorin/ast/stream.cpp