Thorin: thorin::RuntimeCast< B > Class Template Reference
thorin::RuntimeCast< B > Class Template Reference
Inherit from this class using CRTP, for some nice dynamic_cast-style wrappers.
#include <thorin/util/cast.h>
Public Member Functions
template<class T >
T * as ()
static_cast with debug check.
template<class T >
T * isa ()
dynamic_cast.
template<class T , class U >
B * isa ()
Yields B* if it is either T or U and `nullptr* otherwise.
template<class T >
const T * as () const
const version.
template<class T >
const T * isa () const
const version.
template<class T , class U >
const B * isa () const
const version.
Detailed Description
template<class B>
class thorin::RuntimeCast< B >
Inherit from this class using CRTP, for some nice dynamic_cast-style wrappers.
Definition at line 35 of file cast.h.
Member Function Documentation
as() [1/2]
template<class B > template<class T > T * thorin::RuntimeCast< B >::as () inline
static_cast with debug check.
Definition at line 39 of file cast.h.
Referenced by thorin::Global::alloced_type(), thorin::as_lit(), thorin::Pass::as_proxy(), thorin::autodiff::AutoDiffEval::augment_app(), thorin::App::callee_type(), thorin::clos::clos_pack(), thorin::clos::clos_type_to_pi(), thorin::continuation_codom(), thorin::continuation_dom(), thorin::App::decurry(), thorin::refly::do_reflect(), thorin::ll::Emitter::emit_epilogue(), thorin::clos::Clos2SJLJ::enter(), thorin::clos::ClosConvPrep::eta_wrap(), thorin::World::extract(), thorin::World::iapp(), thorin::match(), thorin::autodiff::normalize_add(), thorin::math::normalize_arith(), thorin::core::normalize_bit1(), thorin::core::normalize_bit2(), thorin::math::normalize_cmp(), thorin::core::normalize_conv(), thorin::math::normalize_conv(), thorin::core::normalize_div(), thorin::math::normalize_extrema(), thorin::core::normalize_icmp(), thorin::mem::normalize_load(), thorin::compile::normalize_pass_phase(), thorin::core::normalize_shr(), thorin::autodiff::normalize_sum(), thorin::core::normalize_wrap(), thorin::core::normalize_zip(), thorin::direct::op_cps2ds_dep(), thorin::optimize(), thorin::register_pass_with_arg(), thorin::mem::rewrite_apped_mut_lam_in_tuple(), thorin::clos::ClosConvPrep::rewrite_arg(), thorin::clos::ClosConvPrep::rewrite_callee(), thorin::mem::rewrite_mut_lam_in_tuple(), thorin::Pack::set(), thorin::Infer::set(), thorin::Lam::set(), thorin::Sigma::set(), thorin::Lam::set_body(), thorin::Arr::set_body(), thorin::Pi::set_codom(), thorin::Pi::set_dom(), thorin::Lam::set_filter(), thorin::Arr::set_shape(), thorin::mem::split_phixy(), thorin_get_plugin(), thorin::Lam::type(), and thorin::Pack::type().
as() [2/2]
template<class B > template<class T > const T * thorin::RuntimeCast< B >::as () const inline
const version.
Definition at line 55 of file cast.h.
isa() [1/4]
template<class B > template<class T > T * thorin::RuntimeCast< B >::isa () inline
dynamic_cast.
If T isa thorin::detail::Nodeable, it will use node(), otherwise a dynamic_cast.
Definition at line 44 of file cast.h.
Referenced by thorin::World::ac(), thorin::World::app(), thorin::Checker::assignable(), thorin::autodiff::AutoDiffEval::augment_(), thorin::autodiff::AutoDiffEval::augment_app(), thorin::autodiff::autodiff_type_fun(), thorin::World::bound(), thorin::clos::ca_isa_var(), thorin::clos::clos_insert_env(), thorin::clos::clos_remove_env(), thorin::collect_args(), thorin::decurry(), thorin::Dumper::dump(), thorin::Scheduler::early(), thorin::ll::Emitter::emit_bb(), thorin::dot::Emitter::emit_bb(), thorin::dot::emit_node_attributes(), thorin::clos::ClosConvPrep::enter(), thorin::eta_rule(), thorin::World::ext(), thorin::World::extract(), thorin::Infer::find(), thorin::clos::ClosLit::fnc_type(), thorin::Axiom::get(), thorin::compile::handle_optimization_part(), thorin::World::iapp(), thorin::id(), thorin::Axiom::infer_curry_and_trip(), thorin::World::insert(), thorin::clos::interesting_type(), thorin::Pi::is_cn(), thorin::ll::is_const(), thorin::is_continuation_type(), thorin::clos::is_memop_res(), thorin::is_shape(), thorin::clos::is_toplevel(), thorin::is_var(), thorin::isa_apped_mut_lam(), thorin::mem::isa_apped_mut_lam_in_tuple(), thorin::clos::isa_br(), thorin::clos::isa_branch(), thorin::isa_callee(), thorin::clos::isa_clos_type(), thorin::isa_lit(), thorin::Pass::isa_proxy(), thorin::Scheduler::late(), thorin::merge_sigma(), thorin::merge_tuple(), thorin::core::normalize_bitcast(), thorin::core::normalize_conv(), thorin::math::normalize_conv(), thorin::mem::normalize_store(), thorin::core::normalize_trait(), thorin::core::normalize_zip(), thorin::Inline::operator bool(), thorin::Rewriter::rewrite(), thorin::clos::BranchClosElim::rewrite(), thorin::clos::ClosConvPrep::rewrite(), thorin::direct::DS2CPS::rewrite(), thorin::Scalerize::rewrite(), thorin::matrix::LowerMatrixHighLevelMapRed::rewrite_(), thorin::matrix::LowerMatrixMediumLevel::rewrite_(), thorin::clos::ClosConvPrep::rewrite_callee(), thorin::matrix::LowerMatrixLowLevel::rewrite_imm(), thorin::mem::should_flatten(), thorin::Idx::size(), thorin::Idx::size2bitwidth(), thorin::clos::split(), thorin::mem::strip_mem(), thorin::mem::strip_mem_ty(), thorin::World::test(), thorin::clos::ClosLit::type(), thorin::World::type(), thorin::World::uinc(), thorin::World::umax(), thorin::World::vel(), and thorin::autodiff::zero_def().
isa() [2/4]
template<class B > template<class T , class U > B * thorin::RuntimeCast< B >::isa () inline
Yields B* if it is either T or U and `nullptr* otherwise.
Definition at line 53 of file cast.h.
isa() [3/4]
template<class B > template<class T > const T * thorin::RuntimeCast< B >::isa () const inline
const version.
Definition at line 56 of file cast.h.
isa() [4/4]
template<class B > template<class T , class U > const B * thorin::RuntimeCast< B >::isa () const inline
const version.
Definition at line 57 of file cast.h.
The documentation for this class was generated from the following file:
thorin/util/cast.h