MimIR: mim::plug::affine::LowerFor Class Reference
mim::plug::affine::LowerFor Class Reference
Lowers the for axiom to actual control flow in CPS.
#include <mim/plug/affine/pass/lower_for.h>
Public Member Functions
LowerFor (PassMan &man)
const Def * rewrite (const Def *) override
Public Member Functions inherited from mim::RWPass< LowerFor, Lam >
RWPass (PassMan &man, std::string_view name)
bool inspect () const override
Should the PassMan even consider this pass?
Lam * curr_mut () const
Public Member Functions inherited from mim::Pass
Pass (PassMan &, std::string_view name)
virtual ~Pass ()=default
World & world ()
PassMan & man ()
const PassMan & man () const
std::string_view name () const
size_t index () const
virtual const Def * rewrite (const Var *var)
virtual const Def * rewrite (const Proxy *proxy)
virtual undo_t analyze (const Def *)
virtual undo_t analyze (const Var *)
virtual undo_t analyze (const Proxy *)
virtual bool fixed_point () const
virtual void enter ()
Invoked just before Pass::rewriteing PassMan::curr_mut's body.
virtual void prepare ()
Invoked once before entering the main rewrite loop.
const Proxy * proxy (const Def *type, Defs ops, u32 tag=0)
const Proxy * isa_proxy (const Def *def, u32 tag=0)
Check whether given def is a Proxy whose Proxy::pass matches this Pass's IPass::index.
const Proxy * as_proxy (const Def *def, u32 tag=0)
Detailed Description
Lowers the for axiom to actual control flow in CPS.
It basically mimics this implementation:
con %affine.For_impl
    (m: Nat , n: Nat , Ts: «n; *»)
    (begin: Idx m, end: Idx m, step: Idx m, init: «i: n; Ts#i»,
            body: Cn [iter: Idx m, acc: «i: n; Ts#i», yield: Cn «i: n; Ts#i»],
            exit: Cn «i: n; Ts#i»
    ) =
    con head(iter: Idx m, acc: «i: n; Ts#i») =
        con new_body() = body (iter, acc, cn acc: «i: n; Ts#i» =
            let iter2 = %core.wrap.add %core.mode.nsuw (iter, step);
            head (iter2, acc));
        con new_exit() = exit (acc);
        (new_exit, new_body)#(%core.icmp.ul (iter, end)) ();
    head(begin, init);
However, we merge init/acc into the signature, as it may contain a mem. In this case we have to equip new_body/new_exit with a mem as well.
Todo
We probably want to have phases which fix such things so we don't have to do this in C++.
Definition at line 29 of file lower_for.h.
Constructor & Destructor Documentation
LowerFor()
mim::plug::affine::LowerFor::LowerFor (PassMan & man) inline
Definition at line 31 of file lower_for.h.
Member Function Documentation
rewrite()
const Def * mim::plug::affine::LowerFor::rewrite (const Def * def) override virtual
Reimplemented from mim::Pass.
Definition at line 32 of file lower_for.cpp.
References mim::plug::core::add, mim::World::app(), mim::World::call(), mim::RWPass< LowerFor, Lam >::curr_mut(), mim::Def::isa_mut(), mim::match(), mim::plug::mem::mem_def(), mim::plug::mem::mem_var(), mim::World::mut_con(), mim::plug::core::nusw, mim::Def::set(), mim::Lam::set(), mim::World::sigma(), mim::World::tuple(), mim::World::type(), mim::plug::core::ul, mim::World::var(), mim::Def::vars(), and mim::Pass::world().
The documentation for this class was generated from the following files:
include/mim/plug/affine/pass/lower_for.h
src/mim/plug/affine/pass/lower_for.cpp