MimIR: mim::ast::DeclExpr Class Reference
mim::ast::DeclExpr Class Reference
decls e or e where decls if where is true.
#include <mim/ast/ast.h>
Public Member Functions
DeclExpr (Loc loc, Ptrs< ValDecl > &&decls, Ptr< Expr > &&expr, bool is_where)
const auto & decls () const
bool is_where () const
const Expr * expr () const
void bind (Scopes &) const override
std::ostream & stream (Tab &, std::ostream &) const override
Public Member Functions inherited from mim::ast::Expr
const Def * emit (Emitter &) const
virtual const Def * emit_decl (Emitter &, const Def *) const
virtual void emit_body (Emitter &, const Def *) const
Public Member Functions inherited from mim::ast::Node
Loc loc () const
void dump () const
Private Member Functions
const Def * emit_ (Emitter &) const override
Additional Inherited Members
enum class Prec {
Err ,
Bot ,
Where ,
Arrow ,
Pi ,
Inj ,
App ,
Union ,
Extract ,
Lit
}
static constexpr bool is_rassoc (Prec p)
Protected Member Functions inherited from mim::ast::Expr
Expr (Loc loc)
Protected Member Functions inherited from mim::ast::Node
Node (Loc loc)
virtual ~Node ()
Detailed Description
decls e or e where decls if where is true.
Definition at line 409 of file ast.h.
Constructor & Destructor Documentation
DeclExpr()
mim::ast::DeclExpr::DeclExpr (Loc loc, Ptrs< ValDecl > && decls, Ptr< Expr > && expr, bool is_where) inline
Definition at line 411 of file ast.h.
References decls(), mim::ast::Expr::Expr(), expr(), is_where(), and mim::ast::Node::loc().
Member Function Documentation
bind()
void mim::ast::DeclExpr::bind (Scopes & s) const override virtual
Implements mim::ast::Expr.
Definition at line 133 of file bind.cpp.
References mim::ast::Expr::bind(), decls(), expr(), and is_where().
decls()
const auto & mim::ast::DeclExpr::decls () const inline
Definition at line 417 of file ast.h.
Referenced by bind(), DeclExpr(), emit_(), and stream().
emit_()
const Def * mim::ast::DeclExpr::emit_ (Emitter & e) const override private virtual
Implements mim::ast::Expr.
Definition at line 186 of file emit.cpp.
References decls(), mim::ast::Expr::emit(), expr(), and is_where().
expr()
const Expr * mim::ast::DeclExpr::expr () const inline
Definition at line 419 of file ast.h.
References mim::ast::Expr::Expr().
Referenced by bind(), DeclExpr(), emit_(), and stream().
is_where()
bool mim::ast::DeclExpr::is_where () const inline
Definition at line 418 of file ast.h.
Referenced by bind(), DeclExpr(), emit_(), and stream().
stream()
std::ostream & mim::ast::DeclExpr::stream (Tab & tab, std::ostream & os) const override virtual
Implements mim::ast::Node.
Definition at line 93 of file stream.cpp.
References decls(), expr(), is_where(), mim::print(), and mim::Tab::println().
The documentation for this class was generated from the following files:
include/mim/ast/ast.h
src/mim/ast/bind.cpp
src/mim/ast/emit.cpp
src/mim/ast/stream.cpp