MimIR: mim::Idx Class Reference
mim::Idx Class Reference
A built-in constant of type Nat -> *.
#include <mim/def.h>
Static Public Member Functions
isa
static Ref isa (Ref def)
Checks if def is a Idx s and returns s or nullptr otherwise.
static Ref as (Ref def)
static std::optional< nat_t > isa_lit (Ref def)
static nat_t as_lit (Ref def)
Convert between Idx::isa and bitwidth and vice versa
static constexpr nat_t bitwidth2size (nat_t n)
static constexpr nat_t size2bitwidth (nat_t n)
static std::optional< nat_t > size2bitwidth (Ref size)
Static Public Attributes
static constexpr auto Node = Node::Idx
Private Member Functions
Ref rebuild_ (World &, Ref, Defs) const override
Friends
class World
Additional Inherited Members
Public Member Functions inherited from mim::Def
World & world () const noexcept
constexpr flags_t flags () const noexcept
constexpr u32 gid () const noexcept
Global id - unique number for this Def.
constexpr u32 tid () const noexcept
Trie id - only used in Trie.
constexpr size_t hash () const noexcept
constexpr node_t node () const noexcept
std::string_view node_name () const
Ref type () const noexcept
Yields the raw type of this Def, i.e. maybe nullptr.
Ref unfold_type () const
Yields the type of this Def and builds a new Type (UInc n) if necessary.
bool is_term () const
Yields true if this:T and T:(Type 0).
Ref arity () const
std::optional< nat_t > isa_lit_arity () const
nat_t as_lit_arity () const
template<size_t N = std::dynamic_extent>
constexpr auto ops () const noexcept
Ref op (size_t i) const noexcept
constexpr size_t num_ops () const noexcept
Def * set (size_t i, Ref)
Successively set from left to right.
Def * reset (size_t i, Ref def)
Successively reset from left to right.
Def * set (Defs ops)
Def::set ops all at once.
Def * reset (Defs ops)
Def::reset ops all at once.
Def * unset ()
Unsets all Def::ops; works even, if not set at all or partially.
bool is_set () const
Yields true if empty or the last op is set.
Defs deps () const
Ref dep (size_t i) const
size_t num_deps () const
bool has_dep () const
bool has_dep (Dep d) const
bool has_dep (unsigned u) const
bool has_const_dep () const
Neither a Dep::Mut nor a Dep::Var; can often be used as shortcut as an optimization.
nat_t num_projs () const
Yields Def::as_lit_arity(), if it is in fact a Lit, or 1 otherwise.
nat_t num_tprojs () const
As above but yields 1, if Flags::scalarize_threshold is exceeded.
Ref proj (nat_t a, nat_t i) const
Similar to World::extract while assuming an arity of a, but also works on Sigmas and Arrays.
Ref proj (nat_t i) const
As above but takes Def::num_projs as arity.
Ref tproj (nat_t i) const
As above but takes Def::num_tprojs.
template<nat_t A = std::dynamic_extent, class F >
auto projs (F f) const
Splits this Def via Def::projections into an Array (if A == std::dynamic_extent) or std::array (otherwise).
template<class F >
auto tprojs (F f) const
template<class F >
auto projs (nat_t a, F f) const
template<nat_t A = std::dynamic_extent>
auto projs () const
auto tprojs () const
auto projs (nat_t a) const
nat_t num_vars () noexcept
nat_t num_tvars () noexcept
Ref var (nat_t a, nat_t i) noexcept
Ref var (nat_t i) noexcept
Ref tvar (nat_t i) noexcept
template<nat_t A = std::dynamic_extent, class F >
auto vars (F f) noexcept
template<class F >
auto tvars (F f) noexcept
template<nat_t A = std::dynamic_extent>
auto vars () noexcept
auto tvars () noexcept
template<class F >
auto vars (nat_t a, F f) noexcept
auto vars (nat_t a) noexcept
Ref var ()
Not necessarily a Var: E.g., if the return type is [], this will yield ().
const Var * has_var ()
Only returns not nullptr, if Var of this mutable has ever been created.
const Var * has_var () const
As above if this is a mutable.
Muts local_muts () const
Mutables reachable by following immutable deps(); mut->local_muts() is by definition the set { mut }.
Vars local_vars () const
Vars reachable by following immutable deps().
Muts mut_local_muts ()
All local_muts() of this mutable's deps().
Vars free_vars () const
Compute a global solution, i.e., by transitively following mutables as well.
Vars free_vars ()
Muts users ()
Set of mutables where this mutable is locally referenced.
bool is_open () const
Has free_vars()?
bool is_closed () const
Has no free_vars()?
bool is_external () const
void make_external ()
void make_internal ()
void transfer_external (Def *to)
template<class T = Def>
const T * isa_imm () const
template<class T = Def>
const T * as_imm () const
template<class T = Def, class R >
const T * isa_imm (R(T::*f)() const) const
template<class T = Def, bool invert = false>
T * isa_mut () const
If this is *mut*able, it will cast constness away and perform a dynamic_cast to T.
template<class T = Def, bool invert = false>
T * as_mut () const
Asserts that this is a mutable, casts constness away and performs a static_cast to T.
Dbg dbg () const
Loc loc () const
Sym sym () const
std::string unique_name () const
name + "_" + Def::gid
template<bool Ow = false>
const Def * set (Loc l) const
template<bool Ow = false>
Def * set (Loc l)
template<bool Ow = false>
const Def * set (Sym s) const
template<bool Ow = false>
Def * set (Sym s)
template<bool Ow = false>
const Def * set (std::string s) const
template<bool Ow = false>
Def * set (std::string s)
template<bool Ow = false>
const Def * set (Loc l, Sym s) const
template<bool Ow = false>
Def * set (Loc l, Sym s)
template<bool Ow = false>
const Def * set (Loc l, std::string s) const
template<bool Ow = false>
Def * set (Loc l, std::string s)
template<bool Ow = false>
const Def * set (Dbg d) const
template<bool Ow = false>
Def * set (Dbg d)
const Def * debug_prefix (std::string) const
const Def * debug_suffix (std::string) const
Def * stub (World &w, Ref type)
Def * stub (Ref type)
Ref rebuild (World &w, Ref type, Defs ops) const
Def::rebuilds this Def while using new_op as substitute for its i'th Def::op.
Ref rebuild (Ref type, Defs ops) const
virtual const Def * immutabilize ()
Tries to make an immutable from a mutable.
bool is_immutabilizable ()
Ref refine (size_t i, Ref new_op) const
DefVec reduce (Ref arg) const
Rewrites Def::ops by substituting this mutable's Var with arg.
DefVec reduce (Ref arg)
Ref reduce (size_t i, Ref arg) const
As above but only rewrites this->op(i).
virtual Ref check (size_t, Ref def)
virtual Ref check ()
const Def * zonk () const
void dump () const
void dump (int max) const
void write (int max) const
void write (int max, const char *file) const
std::ostream & stream (std::ostream &, int max) const
void dot (std::ostream &os, uint32_t max=0xFFFFFF, bool types=false) const
void dot (const char *file=nullptr, uint32_t max=0xFFFFFF, bool types=false) const
Same as above but write to file or std::cout if file is nullptr.
void dot (const std::string &file, uint32_t max=0xFFFFFF, bool types=false) const
Public Member Functions inherited from mim::Setters< Idx >
const Idx * set (Loc l) const
Idx * set (Loc l)
const Idx * set (Sym s) const
Idx * set (Sym s)
const Idx * set (std::string s) const
Idx * set (std::string s)
const Idx * set (Loc l, Sym s) const
Idx * set (Loc l, Sym s)
const Idx * set (Loc l, std::string s) const
Idx * set (Loc l, std::string s)
const Idx * set (Dbg d) const
Idx * set (Dbg d)
Protected Member Functions inherited from mim::Def
Def (World *, node_t, const Def *type, Defs ops, flags_t flags)
Constructor for an immutable Def.
Def (node_t n, const Def *type, Defs ops, flags_t flags)
As above but World retrieved from type.
Def (node_t, const Def *type, size_t num_ops, flags_t flags)
Constructor for a mutable Def.
virtual ~Def ()=default
Sym sym (const char *) const
Sym sym (std::string_view) const
Sym sym (std::string) const
Protected Attributes inherited from mim::Def
Dbg dbg_
union {
NormalizeFn normalizer_
Axiom only: Axioms use this member to store their normalizer.
const Axiom * axiom_
App only: Curried Apps of Axioms use this member to propagate the Axiom.
const Var * var_
Mutable only: Var of a mutable.
World * world_
};
flags_t flags_
u8 curry_ = 0
u8 trip_ = 0
Detailed Description
A built-in constant of type Nat -> *.
Definition at line 767 of file def.h.
Member Function Documentation
as()
static Ref mim::Idx::as (Ref def) inline static
Definition at line 782 of file def.h.
References isa().
as_lit()
static nat_t mim::Idx::as_lit (Ref def) inline static
Definition at line 788 of file def.h.
References isa_lit().
Referenced by mim::plug::autodiff::normalize_add().
bitwidth2size()
static constexpr nat_t mim::Idx::bitwidth2size (nat_t n) inline static constexpr
Definition at line 798 of file def.h.
Referenced by mim::World::lit_i1(), mim::World::lit_i16(), mim::World::lit_i32(), mim::World::lit_i64(), mim::World::lit_i8(), mim::World::lit_idx(), mim::World::lit_int(), and mim::World::type_int().
isa()
Ref mim::Idx::isa (Ref def) static
Checks if def is a Idx s and returns s or nullptr otherwise.
Definition at line 519 of file def.cpp.
Referenced by as(), mim::plug::autodiff::autodiff_type_fun(), mim::ll::Emitter::emit_bb(), mim::World::extract(), mim::World::insert(), isa_lit(), mim::World::lit(), mim::plug::autodiff::normalize_add(), mim::plug::core::normalize_bitcast(), mim::plug::core::normalize_idx(), mim::plug::core::normalize_shr(), mim::plug::core::normalize_trait(), mim::plug::core::normalize_wrap(), mim::World::var(), and mim::plug::autodiff::zero_def().
isa_lit()
std::optional< nat_t > mim::Idx::isa_lit (Ref def) static
Definition at line 527 of file def.cpp.
References isa(), and mim::Lit::isa().
Referenced by as_lit().
rebuild_()
Ref mim::Idx::rebuild_ (World & w, Ref , Defs) const override private virtual
Implements mim::Def.
Definition at line 93 of file def.cpp.
size2bitwidth() [1/2]
static constexpr nat_t mim::Idx::size2bitwidth (nat_t n) inline static constexpr
Definition at line 799 of file def.h.
Referenced by mim::ll::Emitter::emit_bb(), mim::plug::core::normalize_conv(), mim::plug::math::normalize_conv(), mim::plug::core::normalize_trait(), and size2bitwidth().
size2bitwidth() [2/2]
std::optional< nat_t > mim::Idx::size2bitwidth (Ref size) static
Definition at line 533 of file def.cpp.
References mim::Lit::isa(), and size2bitwidth().
Friends And Related Symbol Documentation
World
friend class World friend
Definition at line 809 of file def.h.
Member Data Documentation
Node
auto mim::Idx::Node = Node::Idx static constexpr
Definition at line 804 of file def.h.
The documentation for this class was generated from the following files:
include/mim/def.h
src/mim/def.cpp