Thorin: thorin::direct::DS2CPS Class Reference
thorin::direct::DS2CPS Class Reference
Converts direct style function to cps functions.
#include <dialects/direct/passes/ds2cps.h>
Public Member Functions
DS2CPS (PassMan &man)
const Def * rewrite (const Def *) override
Public Member Functions inherited from thorin::RWPass< DS2CPS, Lam >
RWPass (PassMan &man, std::string_view name)
bool inspect () const override
Should the PassMan even consider this pass?
Lam * curr_nom () const
Public Member Functions inherited from thorin::Pass
Pass (PassMan &, std::string_view name)
virtual ~Pass ()=default
World & world ()
PassMan & man ()
const PassMan & man () const
std::string_view name () const
size_t index () const
virtual const Def * rewrite (const Var *var)
virtual const Def * rewrite (const Proxy *proxy)
virtual undo_t analyze (const Def *)
virtual undo_t analyze (const Var *)
virtual undo_t analyze (const Proxy *)
virtual bool fixed_point () const
virtual void enter ()
Invoked just before Pass::rewriteing PassMan::curr_nom's body.
virtual void prepare ()
const Proxy * proxy (const Def *type, Defs ops, u32 tag=0, const Def *dbg={})
const Proxy * isa_proxy (const Def *def, u32 tag=0)
Check whether given def is a Proxy whose Proxy::pass matches this Pass's IPass::index.
const Proxy * as_proxy (const Def *def, u32 tag=0)
Detailed Description
Converts direct style function to cps functions.
To do so, for each (non-type-level) ds function a corresponding cps function is created: f: Π a : A -> B f_cps : cn[a:A, cn B] Only the type signature of the function is changed and the body is wrapped in the newly added return continuation. (Technical detail: the arguments are substituted to fit the new function)
In a second distinct but connected step, the call sites are converted: For a direct style call f args, the call to the cps function cps2ds_dep ... f_cps args is introduced. The underlying substitution is f -> cps2ds_dep ... f_cps.
Definition at line 18 of file ds2cps.h.
Constructor & Destructor Documentation
DS2CPS()
thorin::direct::DS2CPS::DS2CPS (PassMan & man) inline
Definition at line 20 of file ds2cps.h.
Member Function Documentation
rewrite()
const Def * thorin::direct::DS2CPS::rewrite (const Def * def) override virtual
Reimplemented from thorin::Pass.
Definition at line 11 of file ds2cps.cpp.
References thorin::World::app(), thorin::RuntimeCast< Base >::isa(), thorin::Pass::world(), and thorin::Def::world().
The documentation for this class was generated from the following files:
dialects/direct/passes/ds2cps.h
dialects/direct/passes/ds2cps.cpp