Thorin: thorin::Span< T > Class Template Reference
thorin::Span< T > Class Template Reference
A container-like wrapper for an array.
#include <thorin/util/array.h>
Public Types
using value_type = T
using const_iterator = const T *
using const_reverse_iterator = std::reverse_iterator< const_iterator >
Public Member Functions
constructor, destructor & assignment
Span ()
Span (size_t size, const T *ptr)
template<size_t N>
Span (const T(&ptr)[N])
Span (const Span< T > &ref)
Span (const Array< T > &array)
template<size_t N>
Span (const std::array< T, N > &array)
Span (std::initializer_list< T > list)
Span (const std::vector< T > &vector)
Span (Span &&array)
Span & operator= (Span other)
template<size_t N>
std::array< T, N > to_array () const
size
size_t size () const
bool empty () const
begin/end iterators
const_iterator begin () const
const_iterator end () const
const_reverse_iterator rbegin () const
const_reverse_iterator rend () const
access
const T & operator[] (size_t i) const
T const & front () const
T const & back () const
slice
Span< T > skip_front (size_t num=1) const
Span< T > skip_back (size_t num=1) const
Span< T > first (size_t num=1) const
Span< T > last (size_t num=1) const
relational operators
template<class Other >
bool operator== (const Other &other) const
template<class Other >
bool operator!= (const Other &other) const
Friends
void swap (Span< T > &a1, Span< T > &a2)
Detailed Description
template<class T>
class thorin::Span< T >
A container-like wrapper for an array.
The array may either stem from a C array, a std::vector, a std::initializer_list, an Array or another Span. Span does not own the data and, thus, does not destroy any data. Likewise, you must be carefull to not destroy data a Span is pointing to. Note that you can often construct a Span inline with an initializer_list: foo(arg1, {elem1, elem2, elem3}, arg3).
Definition at line 28 of file array.h.
Member Typedef Documentation
const_iterator
template<class T > using thorin::Span< T >::const_iterator = const T*
Definition at line 31 of file array.h.
const_reverse_iterator
template<class T > using thorin::Span< T >::const_reverse_iterator = std::reverse_iterator<const_iterator>
Definition at line 32 of file array.h.
value_type
template<class T > using thorin::Span< T >::value_type = T
Definition at line 30 of file array.h.
Constructor & Destructor Documentation
Span() [1/9]
template<class T > thorin::Span< T >::Span () inline
Definition at line 36 of file array.h.
Span() [2/9]
template<class T > thorin::Span< T >::Span (size_t size, const T * ptr) inline
Definition at line 39 of file array.h.
Span() [3/9]
template<class T > template<size_t N> thorin::Span< T >::Span (const T(&) ptr[N]) inline
Definition at line 43 of file array.h.
Span() [4/9]
template<class T > thorin::Span< T >::Span (const Span< T > & ref) inline
Definition at line 46 of file array.h.
Span() [5/9]
template<class T > thorin::Span< T >::Span (const Array< T > & array) inline
Definition at line 49 of file array.h.
Span() [6/9]
template<class T > template<size_t N> thorin::Span< T >::Span (const std::array< T, N > & array) inline
Definition at line 53 of file array.h.
Span() [7/9]
template<class T > thorin::Span< T >::Span (std::initializer_list< T > list) inline
Definition at line 56 of file array.h.
Span() [8/9]
template<class T > thorin::Span< T >::Span (const std::vector< T > & vector) inline
Definition at line 59 of file array.h.
Span() [9/9]
template<class T > thorin::Span< T >::Span (Span< T > && array) inline
Definition at line 62 of file array.h.
References thorin::Span< T >::swap.
Member Function Documentation
back()
template<class T > T const & thorin::Span< T >::back () const inline
Definition at line 104 of file array.h.
References thorin::Span< T >::empty().
Referenced by thorin::World::arr(), and thorin::World::pack().
begin()
template<class T > const_iterator thorin::Span< T >::begin () const inline
Definition at line 88 of file array.h.
Referenced by thorin::Span< T >::operator!=(), thorin::Span< T >::operator==(), and thorin::Span< T >::rend().
empty()
template<class T > bool thorin::Span< T >::empty () const inline
Definition at line 83 of file array.h.
Referenced by thorin::World::arr(), thorin::Span< T >::back(), thorin::Span< T >::front(), thorin::Checker::is_uniform(), thorin::World::pack(), and thorin::unflatten().
end()
template<class T > const_iterator thorin::Span< T >::end () const inline
Definition at line 89 of file array.h.
Referenced by thorin::Span< T >::operator!=(), thorin::Span< T >::operator==(), and thorin::Span< T >::rbegin().
first()
template<class T > Span< T > thorin::Span< T >::first (size_t num = 1) const inline
Definition at line 114 of file array.h.
References thorin::Span< T >::size().
front()
template<class T > T const & thorin::Span< T >::front () const inline
Definition at line 100 of file array.h.
References thorin::Span< T >::empty().
Referenced by thorin::Checker::is_uniform(), thorin::World::sigma(), and thorin::World::tuple().
last()
template<class T > Span< T > thorin::Span< T >::last (size_t num = 1) const inline
Definition at line 118 of file array.h.
References thorin::Span< T >::size().
operator!=()
template<class T > template<class Other > bool thorin::Span< T >::operator!= (const Other & other) const inline
Definition at line 131 of file array.h.
References thorin::Span< T >::begin(), thorin::Span< T >::end(), and thorin::Span< T >::size().
operator=()
template<class T > Span & thorin::Span< T >::operator= (Span< T > other) inline
Definition at line 67 of file array.h.
References thorin::Span< T >::swap.
operator==()
template<class T > template<class Other > bool thorin::Span< T >::operator== (const Other & other) const inline
Definition at line 127 of file array.h.
References thorin::Span< T >::begin(), thorin::Span< T >::end(), and thorin::Span< T >::size().
operator[]()
template<class T > const T & thorin::Span< T >::operator[] (size_t i) const inline
Definition at line 96 of file array.h.
References thorin::Span< T >::size().
rbegin()
template<class T > const_reverse_iterator thorin::Span< T >::rbegin () const inline
Definition at line 90 of file array.h.
References thorin::Span< T >::end().
rend()
template<class T > const_reverse_iterator thorin::Span< T >::rend () const inline
Definition at line 91 of file array.h.
References thorin::Span< T >::begin().
size()
template<class T > size_t thorin::Span< T >::size () const inline
Definition at line 82 of file array.h.
Referenced by thorin::World::ac(), thorin::World::arr(), thorin::clos::ctype(), thorin::Span< T >::first(), thorin::infer_sigma(), thorin::Span< T >::last(), thorin::merge(), thorin::Def::num_extended_ops(), thorin::Def::num_partial_ops(), thorin::affine::op_for(), thorin::Span< T >::operator!=(), thorin::Span< T >::operator==(), thorin::Span< T >::operator[](), thorin::World::pack(), thorin::World::proxy(), thorin::clos::rebuild(), thorin::World::sigma(), thorin::Span< T >::skip_back(), thorin::Span< T >::skip_front(), thorin::Span< T >::to_array(), thorin::World::tuple(), and thorin::unflatten().
skip_back()
template<class T > Span< T > thorin::Span< T >::skip_back (size_t num = 1) const inline
Definition at line 113 of file array.h.
References thorin::Span< T >::size().
Referenced by thorin::World::arr(), and thorin::World::pack().
skip_front()
template<class T > Span< T > thorin::Span< T >::skip_front (size_t num = 1) const inline
Definition at line 112 of file array.h.
References thorin::Span< T >::size().
Referenced by thorin::Checker::is_uniform(), thorin::Dumper::recurse(), thorin::World::sigma(), and thorin::World::tuple().
to_array()
template<class T > template<size_t N> std::array< T, N > thorin::Span< T >::to_array () const inline
Definition at line 72 of file array.h.
References thorin::Span< T >::size().
Friends And Related Function Documentation
swap
template<class T > void swap (Span< T > & a1, Span< T > & a2) friend
Definition at line 136 of file array.h.
Referenced by thorin::Span< T >::operator=(), and thorin::Span< T >::Span().
The documentation for this class was generated from the following file:
thorin/util/array.h