Thorin: thorin::detail::HashTable< Key, T, H, StackCapacity > Class Template Reference
thorin::detail::HashTable< Key, T, H, StackCapacity > Class Template Reference
Used internally for HashSet and HashMap.
#include <thorin/util/hash.h>
Classes
class iterator_base
Public Types
enum { MinHeapCapacity = StackCapacity * 4 }
typedef Key key_type
typedef std::conditional< std::is_void< T >::value, Key, T >::type mapped_type
typedef std::conditional< std::is_void< T >::value, Key, std::pair< Key, T > >::type value_type
typedef hash_t size_type
typedef iterator_base< false > iterator
typedef iterator_base< true > const_iterator
Public Member Functions
void dump () const
constructor, destructor & assignment
HashTable ()
HashTable (hash_t capacity)
HashTable (HashTable &&other)
HashTable (const HashTable &other)
template<class InputIt >
HashTable (InputIt first, InputIt last)
HashTable (std::initializer_list< value_type > ilist)
~HashTable ()
HashTable & operator= (HashTable other)
getters
hash_t capacity () const
hash_t size () const
bool empty () const
int id () const
begin/end iterators
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
const_iterator cbegin () const
const_iterator cend () const
emplace/insert
template<class... Args>
std::pair< iterator, bool > emplace (Args &&... args)
std::pair< iterator, bool > insert (const value_type &value)
std::pair< iterator, bool > insert (value_type &&value)
void insert (std::initializer_list< value_type > ilist)
template<class R >
bool insert_range (const R &range)
template<class I >
bool insert (I begin, I end)
void rehash (hash_t new_capacity)
erase
void erase (const_iterator pos)
void erase (const_iterator first, const_iterator last)
hash_t erase (const key_type &key)
void clear ()
find
iterator find (const key_type &k)
const_iterator find (const key_type &key) const
hash_t count (const key_type &key) const
bool contains (const key_type &key) const
Friends
void swap (HashTable &t1, HashTable &t2)
Detailed Description
template<class Key, class T, class H, hash_t StackCapacity>
class thorin::detail::HashTable< Key, T, H, StackCapacity >
Used internally for HashSet and HashMap.
Definition at line 147 of file hash.h.
Member Typedef Documentation
const_iterator
template<class Key , class T , class H , hash_t StackCapacity> typedef iterator_base<true> thorin::detail::HashTable< Key, T, H, StackCapacity >::const_iterator
Definition at line 272 of file hash.h.
iterator
template<class Key , class T , class H , hash_t StackCapacity> typedef iterator_base<false> thorin::detail::HashTable< Key, T, H, StackCapacity >::iterator
Definition at line 271 of file hash.h.
key_type
template<class Key , class T , class H , hash_t StackCapacity> typedef Key thorin::detail::HashTable< Key, T, H, StackCapacity >::key_type
Definition at line 150 of file hash.h.
mapped_type
template<class Key , class T , class H , hash_t StackCapacity> typedef std::conditional<std::is_void<T>::value,Key,T>::type thorin::detail::HashTable< Key, T, H, StackCapacity >::mapped_type
Definition at line 151 of file hash.h.
size_type
template<class Key , class T , class H , hash_t StackCapacity> typedef hash_t thorin::detail::HashTable< Key, T, H, StackCapacity >::size_type
Definition at line 270 of file hash.h.
value_type
template<class Key , class T , class H , hash_t StackCapacity> typedef std::conditional<std::is_void<T>::value,Key,std::pair<Key,T>>::type thorin::detail::HashTable< Key, T, H, StackCapacity >::value_type
Definition at line 152 of file hash.h.
Member Enumeration Documentation
anonymous enum
template<class Key , class T , class H , hash_t StackCapacity> anonymous enum
Enumerator
MinHeapCapacity
Definition at line 149 of file hash.h.
Constructor & Destructor Documentation
HashTable() [1/6]
template<class Key , class T , class H , hash_t StackCapacity> thorin::detail::HashTable< Key, T, H, StackCapacity >::HashTable () inline
Definition at line 276 of file hash.h.
HashTable() [2/6]
template<class Key , class T , class H , hash_t StackCapacity> thorin::detail::HashTable< Key, T, H, StackCapacity >::HashTable (hash_t capacity) inline
Definition at line 286 of file hash.h.
References thorin::detail::HashTable< Key, T, H, StackCapacity >::capacity().
HashTable() [3/6]
template<class Key , class T , class H , hash_t StackCapacity> thorin::detail::HashTable< Key, T, H, StackCapacity >::HashTable (HashTable< Key, T, H, StackCapacity > && other) inline
Definition at line 297 of file hash.h.
References thorin::detail::HashTable< Key, T, H, StackCapacity >::swap.
HashTable() [4/6]
template<class Key , class T , class H , hash_t StackCapacity> thorin::detail::HashTable< Key, T, H, StackCapacity >::HashTable (const HashTable< Key, T, H, StackCapacity > & other) inline
Definition at line 301 of file hash.h.
HashTable() [5/6]
template<class Key , class T , class H , hash_t StackCapacity> template<class InputIt > thorin::detail::HashTable< Key, T, H, StackCapacity >::HashTable (InputIt first, InputIt last) inline
Definition at line 317 of file hash.h.
References thorin::utf8::first(), and thorin::detail::HashTable< Key, T, H, StackCapacity >::insert().
HashTable() [6/6]
template<class Key , class T , class H , hash_t StackCapacity> thorin::detail::HashTable< Key, T, H, StackCapacity >::HashTable (std::initializer_list< value_type > ilist) inline
Definition at line 321 of file hash.h.
References thorin::detail::HashTable< Key, T, H, StackCapacity >::insert().
~HashTable()
template<class Key , class T , class H , hash_t StackCapacity> thorin::detail::HashTable< Key, T, H, StackCapacity >::~HashTable () inline
Definition at line 326 of file hash.h.
Member Function Documentation
begin() [1/2]
template<class Key , class T , class H , hash_t StackCapacity> iterator thorin::detail::HashTable< Key, T, H, StackCapacity >::begin () inline
Definition at line 348 of file hash.h.
Referenced by thorin::detail::HashTable< Key, T, H, StackCapacity >::cbegin(), and thorin::detail::HashTable< Key, T, H, StackCapacity >::insert().
begin() [2/2]
template<class Key , class T , class H , hash_t StackCapacity> const_iterator thorin::detail::HashTable< Key, T, H, StackCapacity >::begin () const inline
Definition at line 350 of file hash.h.
References thorin::detail::HashTable< Key, T, H, StackCapacity >::begin().
Referenced by thorin::detail::HashTable< Key, T, H, StackCapacity >::begin().
capacity()
template<class Key , class T , class H , hash_t StackCapacity> hash_t thorin::detail::HashTable< Key, T, H, StackCapacity >::capacity () const inline
Definition at line 338 of file hash.h.
Referenced by thorin::cleanup(), and thorin::detail::HashTable< Key, T, H, StackCapacity >::HashTable().
cbegin()
template<class Key , class T , class H , hash_t StackCapacity> const_iterator thorin::detail::HashTable< Key, T, H, StackCapacity >::cbegin () const inline
Definition at line 352 of file hash.h.
References thorin::detail::HashTable< Key, T, H, StackCapacity >::begin().
cend()
template<class Key , class T , class H , hash_t StackCapacity> const_iterator thorin::detail::HashTable< Key, T, H, StackCapacity >::cend () const inline
Definition at line 353 of file hash.h.
References thorin::detail::HashTable< Key, T, H, StackCapacity >::end().
Referenced by thorin::HashMap< Key, T, H, StackCapacity >::lookup().
clear()
template<class Key , class T , class H , hash_t StackCapacity> void thorin::detail::HashTable< Key, T, H, StackCapacity >::clear () inline
Definition at line 472 of file hash.h.
Referenced by thorin::Def::replace().
contains()
template<class Key , class T , class H , hash_t StackCapacity> bool thorin::detail::HashTable< Key, T, H, StackCapacity >::contains (const key_type & key) const inline
Definition at line 505 of file hash.h.
References thorin::detail::HashTable< Key, T, H, StackCapacity >::count().
count()
template<class Key , class T , class H , hash_t StackCapacity> hash_t thorin::detail::HashTable< Key, T, H, StackCapacity >::count (const key_type & key) const inline
Definition at line 504 of file hash.h.
References thorin::detail::HashTable< Key, T, H, StackCapacity >::end(), and thorin::detail::HashTable< Key, T, H, StackCapacity >::find().
Referenced by thorin::detail::HashTable< Key, T, H, StackCapacity >::contains().
dump()
template<class Key , class T , class H , hash_t StackCapacity> template void thorin::detail::HashTable< Key, T, H, StackCapacity >::dump () const inline
Definition at line 508 of file hash.h.
References thorin::Stream::fmt().
emplace()
template<class Key , class T , class H , hash_t StackCapacity> template<class... Args> std::pair< iterator, bool > thorin::detail::HashTable< Key, T, H, StackCapacity >::emplace (Args &&... args) inline
Definition at line 359 of file hash.h.
References thorin::detail::HashTable< Key, T, H, StackCapacity >::rehash().
Referenced by thorin::CFA::CFA(), thorin::Def::Def(), thorin::PartialEvaluator::enqueue(), thorin::Def::finalize(), thorin::detail::HashTable< Key, T, H, StackCapacity >::insert(), thorin::BetaRed::keep(), thorin::EtaRed::mark_irreducible(), thorin::RecStreamer::run(), thorin::Scheduler::Scheduler(), and thorin::Def::set().
empty()
template<class Key , class T , class H , hash_t StackCapacity> bool thorin::detail::HashTable< Key, T, H, StackCapacity >::empty () const inline
Definition at line 340 of file hash.h.
References thorin::detail::HashTable< Key, T, H, StackCapacity >::size().
Referenced by thorin::detail::HashTable< Key, T, H, StackCapacity >::erase(), thorin::detail::HashTable< Key, T, H, StackCapacity >::find(), and thorin::CondEval::is_top_level().
end() [1/2]
template<class Key , class T , class H , hash_t StackCapacity> iterator thorin::detail::HashTable< Key, T, H, StackCapacity >::end () inline
Definition at line 349 of file hash.h.
Referenced by thorin::detail::HashTable< Key, T, H, StackCapacity >::cend(), thorin::detail::HashTable< Key, T, H, StackCapacity >::count(), thorin::detail::HashTable< Key, T, H, StackCapacity >::erase(), thorin::detail::HashTable< Key, T, H, StackCapacity >::find(), thorin::detail::HashTable< Key, T, H, StackCapacity >::insert(), and thorin::succs().
end() [2/2]
template<class Key , class T , class H , hash_t StackCapacity> const_iterator thorin::detail::HashTable< Key, T, H, StackCapacity >::end () const inline
Definition at line 351 of file hash.h.
References thorin::detail::HashTable< Key, T, H, StackCapacity >::end().
Referenced by thorin::detail::HashTable< Key, T, H, StackCapacity >::end().
erase() [1/3]
template<class Key , class T , class H , hash_t StackCapacity> hash_t thorin::detail::HashTable< Key, T, H, StackCapacity >::erase (const key_type & key) inline
Definition at line 465 of file hash.h.
References thorin::detail::HashTable< Key, T, H, StackCapacity >::end(), thorin::detail::HashTable< Key, T, H, StackCapacity >::erase(), and thorin::detail::HashTable< Key, T, H, StackCapacity >::find().
erase() [2/3]
template<class Key , class T , class H , hash_t StackCapacity> void thorin::detail::HashTable< Key, T, H, StackCapacity >::erase (const_iterator first, const_iterator last) inline
Definition at line 461 of file hash.h.
References thorin::detail::HashTable< Key, T, H, StackCapacity >::erase(), and thorin::utf8::first().
erase() [3/3]
template<class Key , class T , class H , hash_t StackCapacity> void thorin::detail::HashTable< Key, T, H, StackCapacity >::erase (const_iterator pos) inline
Definition at line 432 of file hash.h.
References thorin::detail::HashTable< Key, T, H, StackCapacity >::empty(), thorin::detail::HashTable< Key, T, H, StackCapacity >::end(), thorin::detail::HashTable< Key, T, H, StackCapacity >::MinHeapCapacity, thorin::detail::HashTable< Key, T, H, StackCapacity >::rehash(), thorin::detail::HashTable< Key, T, H, StackCapacity >::swap, and thorin::detail::HashTable< Key, T, H, StackCapacity >::iterator_base< is_const >::verify().
Referenced by thorin::detail::HashTable< Key, T, H, StackCapacity >::erase().
find() [1/2]
template<class Key , class T , class H , hash_t StackCapacity> iterator thorin::detail::HashTable< Key, T, H, StackCapacity >::find (const key_type & k) inline
Definition at line 487 of file hash.h.
References thorin::detail::HashTable< Key, T, H, StackCapacity >::empty(), and thorin::detail::HashTable< Key, T, H, StackCapacity >::end().
Referenced by thorin::detail::HashTable< Key, T, H, StackCapacity >::count(), thorin::detail::HashTable< Key, T, H, StackCapacity >::erase(), thorin::detail::HashTable< Key, T, H, StackCapacity >::find(), thorin::HashMap< Key, T, H, StackCapacity >::lookup(), and thorin::succs().
find() [2/2]
template<class Key , class T , class H , hash_t StackCapacity> const_iterator thorin::detail::HashTable< Key, T, H, StackCapacity >::find (const key_type & key) const inline
Definition at line 500 of file hash.h.
References thorin::detail::HashTable< Key, T, H, StackCapacity >::find().
id()
template<class Key , class T , class H , hash_t StackCapacity> int thorin::detail::HashTable< Key, T, H, StackCapacity >::id () const inline
Definition at line 342 of file hash.h.
insert() [1/4]
template<class Key , class T , class H , hash_t StackCapacity> std::pair< iterator, bool > thorin::detail::HashTable< Key, T, H, StackCapacity >::insert (const value_type & value) inline
Definition at line 367 of file hash.h.
References thorin::detail::HashTable< Key, T, H, StackCapacity >::emplace().
Referenced by thorin::detail::HashTable< Key, T, H, StackCapacity >::HashTable(), thorin::detail::HashTable< Key, T, H, StackCapacity >::insert_range(), thorin::Mangler::Mangler(), thorin::merge(), thorin::HashMap< Key, T, H, StackCapacity >::operator[](), and thorin::succs().
insert() [2/4]
template<class Key , class T , class H , hash_t StackCapacity> template<class I > bool thorin::detail::HashTable< Key, T, H, StackCapacity >::insert (I begin, I end) inline
Definition at line 377 of file hash.h.
References thorin::detail::HashTable< Key, T, H, StackCapacity >::begin(), thorin::detail::HashTable< Key, T, H, StackCapacity >::end(), thorin::detail::HashTable< Key, T, H, StackCapacity >::rehash(), and thorin::detail::HashTable< Key, T, H, StackCapacity >::size().
insert() [3/4]
template<class Key , class T , class H , hash_t StackCapacity> void thorin::detail::HashTable< Key, T, H, StackCapacity >::insert (std::initializer_list< value_type > ilist) inline
Definition at line 369 of file hash.h.
References thorin::detail::HashTable< Key, T, H, StackCapacity >::insert().
Referenced by thorin::detail::HashTable< Key, T, H, StackCapacity >::insert().
insert() [4/4]
template<class Key , class T , class H , hash_t StackCapacity> std::pair< iterator, bool > thorin::detail::HashTable< Key, T, H, StackCapacity >::insert (value_type && value) inline
Definition at line 368 of file hash.h.
References thorin::detail::HashTable< Key, T, H, StackCapacity >::emplace().
insert_range()
template<class Key , class T , class H , hash_t StackCapacity> template<class R > bool thorin::detail::HashTable< Key, T, H, StackCapacity >::insert_range (const R & range) inline
Definition at line 372 of file hash.h.
References thorin::detail::HashTable< Key, T, H, StackCapacity >::insert().
operator=()
template<class Key , class T , class H , hash_t StackCapacity> HashTable & thorin::detail::HashTable< Key, T, H, StackCapacity >::operator= (HashTable< Key, T, H, StackCapacity > other) inline
Definition at line 330 of file hash.h.
References thorin::detail::HashTable< Key, T, H, StackCapacity >::swap.
rehash()
template<class Key , class T , class H , hash_t StackCapacity> void thorin::detail::HashTable< Key, T, H, StackCapacity >::rehash (hash_t new_capacity) inline
Definition at line 397 of file hash.h.
References thorin::detail::HashTable< Key, T, H, StackCapacity >::MinHeapCapacity, and thorin::detail::HashTable< Key, T, H, StackCapacity >::swap.
Referenced by thorin::cleanup(), thorin::detail::HashTable< Key, T, H, StackCapacity >::emplace(), thorin::detail::HashTable< Key, T, H, StackCapacity >::erase(), and thorin::detail::HashTable< Key, T, H, StackCapacity >::insert().
size()
template<class Key , class T , class H , hash_t StackCapacity> hash_t thorin::detail::HashTable< Key, T, H, StackCapacity >::size () const inline
Definition at line 339 of file hash.h.
Referenced by thorin::detail::HashTable< Key, T, H, StackCapacity >::empty(), thorin::detail::HashTable< Key, T, H, StackCapacity >::insert(), thorin::CFG< forward >::num_preds(), and thorin::CFG< forward >::num_succs().
Friends And Related Function Documentation
swap
template<class Key , class T , class H , hash_t StackCapacity> void swap (HashTable< Key, T, H, StackCapacity > & t1, HashTable< Key, T, H, StackCapacity > & t2) friend
Definition at line 513 of file hash.h.
Referenced by thorin::detail::HashTable< Key, T, H, StackCapacity >::erase(), thorin::detail::HashTable< Key, T, H, StackCapacity >::HashTable(), thorin::detail::HashTable< Key, T, H, StackCapacity >::operator=(), and thorin::detail::HashTable< Key, T, H, StackCapacity >::rehash().
The documentation for this class was generated from the following files:
thorin/util/hash.h
thorin/stream.cpp