Thorin: thorin::ast::Scopes Class Reference
thorin::ast::Scopes Class Reference
Public Types
using Scope = fe::SymMap< std::pair< Loc, const Decl * > >
Public Member Functions
Scopes (AST &ast)
AST & ast () const
Driver & driver () const
Scope & top ()
const Decl * dummy () const
void push ()
void pop ()
const Decl * find (Dbg dbg, bool quiet=false)
void bind (Dbg dbg, const Decl *decl, bool rebind=false, bool quiet=false)
Detailed Description
Definition at line 17 of file bind.cpp.
Member Typedef Documentation
Scope
using thorin::ast::Scopes::Scope = fe::SymMap<std::pair<Loc, const Decl*> >
Definition at line 19 of file bind.cpp.
Constructor & Destructor Documentation
Scopes()
thorin::ast::Scopes::Scopes (AST & ast) inline
Definition at line 21 of file bind.cpp.
References push().
Member Function Documentation
ast()
AST & thorin::ast::Scopes::ast () const inline
Definition at line 27 of file bind.cpp.
Referenced by bind(), driver(), and find().
bind()
void thorin::ast::Scopes::bind (Dbg dbg, const Decl * decl, bool rebind = false, bool quiet = false) inline
Definition at line 52 of file bind.cpp.
References ast(), thorin::ast::AST::error(), thorin::ast::AST::note(), and top().
Referenced by find().
driver()
Driver & thorin::ast::Scopes::driver () const inline
Definition at line 28 of file bind.cpp.
References ast(), and thorin::ast::AST::driver().
dummy()
const Decl * thorin::ast::Scopes::dummy () const inline
Definition at line 30 of file bind.cpp.
Referenced by find().
find()
const Decl * thorin::ast::Scopes::find (Dbg dbg, bool quiet = false) inline
Definition at line 39 of file bind.cpp.
References ast(), bind(), dummy(), and thorin::ast::AST::error().
pop()
void thorin::ast::Scopes::pop () inline
Definition at line 34 of file bind.cpp.
push()
void thorin::ast::Scopes::push () inline
Definition at line 32 of file bind.cpp.
Referenced by Scopes().
top()
Scope & thorin::ast::Scopes::top () inline
Definition at line 29 of file bind.cpp.
Referenced by bind().
The documentation for this class was generated from the following file:
src/thorin/ast/bind.cpp