Thorin: thorin::ast::Node Class Reference
thorin::ast::Node Class Reference abstract
#include <thorin/ast/ast.h>
Public Member Functions
Loc loc () const
virtual std::ostream & stream (Tab &, std::ostream &) const =0
void dump () const
Protected Member Functions
Node (Loc loc)
virtual ~Node ()
Detailed Description
Definition at line 114 of file ast.h.
Constructor & Destructor Documentation
Node()
thorin::ast::Node::Node (Loc loc) inline protected
Definition at line 116 of file ast.h.
~Node()
virtual thorin::ast::Node::~Node () inline protected virtual
Definition at line 118 of file ast.h.
Member Function Documentation
dump()
void thorin::ast::Node::dump () const
Definition at line 32 of file stream.cpp.
References stream().
loc()
Loc thorin::ast::Node::loc () const inline
Definition at line 121 of file ast.h.
Referenced by thorin::ast::PiExpr::Dom::add_ret(), thorin::ast::LitExpr::bind(), thorin::ast::PiExpr::bind(), thorin::ast::AxiomDecl::bind(), thorin::ast::AxiomDecl::Alias::bind(), thorin::ast::RecDecl::bind_decl(), thorin::ast::LamDecl::bind_decl(), thorin::ast::Expr::emit(), thorin::ast::Module::emit(), thorin::ast::TuplePtrn::emit_body(), thorin::ast::LamDecl::emit_decl(), thorin::ast::TuplePtrn::emit_decl(), thorin::ast::PiExpr::emit_decl(), thorin::ast::PiExpr::Dom::emit_type(), thorin::ast::IdPtrn::emit_type(), thorin::ast::Ptrn::emit_value(), thorin::ast::IdPtrn::mk_id(), and thorin::ast::IdPtrn::mk_type().
stream()
virtual std::ostream & thorin::ast::Node::stream (Tab & , std::ostream &) const pure virtual
Implemented in thorin::ast::Import, thorin::ast::ErrorPtrn, thorin::ast::IdPtrn, thorin::ast::GrpPtrn, thorin::ast::TuplePtrn, thorin::ast::ErrorExpr, thorin::ast::InferExpr, thorin::ast::IdExpr, thorin::ast::PrimaryExpr, thorin::ast::LitExpr, thorin::ast::DeclExpr, thorin::ast::TypeExpr, thorin::ast::ArrowExpr, thorin::ast::PiExpr::Dom, thorin::ast::PiExpr, thorin::ast::LamExpr, thorin::ast::AppExpr, thorin::ast::RetExpr, thorin::ast::SigmaExpr, thorin::ast::TupleExpr, thorin::ast::ArrOrPackExpr< arr >, thorin::ast::ExtractExpr, thorin::ast::InsertExpr, thorin::ast::LetDecl, thorin::ast::AxiomDecl::Alias, thorin::ast::AxiomDecl, thorin::ast::RecDecl, thorin::ast::LamDecl::Dom, thorin::ast::LamDecl, thorin::ast::CDecl, thorin::ast::Module, and thorin::ast::DummyDecl.
Referenced by dump().
The documentation for this class was generated from the following files:
include/thorin/ast/ast.h
src/thorin/ast/stream.cpp