Thorin: thorin::ScopeRewriter Class Reference
thorin::ScopeRewriter Class Reference
#include <thorin/rewrite.h>
Public Member Functions
ScopeRewriter (World &world, const Scope &scope)
const Def * rewrite (const Def *old_def) override
Recursively rewrites old_def.
Public Member Functions inherited from thorin::Rewriter
Rewriter (World &old_world, World &new_world)
Rewriter (World &world)
virtual std::pair< const Def *, bool > pre_rewrite (const Def *)
Rewrite a given Def in pre-order.
virtual std::pair< const Def *, bool > post_rewrite (const Def *)
As above but in post-order.
Public Attributes
const Scope & scope
Public Attributes inherited from thorin::Rewriter
World & old_world
World & new_world
Def2Def old2new
Detailed Description
Definition at line 42 of file rewrite.h.
Constructor & Destructor Documentation
ScopeRewriter()
thorin::ScopeRewriter::ScopeRewriter (World & world, const Scope & scope) inline
Definition at line 44 of file rewrite.h.
Member Function Documentation
rewrite()
const Def * thorin::ScopeRewriter::rewrite (const Def * old_def) inline override virtual
Recursively rewrites old_def.
Invokes Rewriter::pre_rewrite at the beginning and Rewriter::post_rewrite at the end.
Reimplemented from thorin::Rewriter.
Definition at line 48 of file rewrite.h.
References thorin::Scope::bound(), thorin::Rewriter::rewrite(), and scope.
Referenced by thorin::rewrite(), and thorin::fe::TuplePtrn::type().
Member Data Documentation
scope
const Scope& thorin::ScopeRewriter::scope
Definition at line 53 of file rewrite.h.
Referenced by rewrite().
The documentation for this class was generated from the following file:
thorin/rewrite.h