Thorin: thorin::FPPass< P, M > Class Template Reference
thorin::FPPass< P, M > Class Template Reference
Inherit from this class using CRTP, if you do need a Pass with a state and a fixed-point.
#include <thorin/pass/pass.h>
Public Types
using Super = RWPass< P, M >
using Data = std::tuple<>
Default.
Public Member Functions
FPPass (PassMan &man, std::string_view name)
bool fixed_point () const override
Public Member Functions inherited from thorin::RWPass< P, M >
RWPass (PassMan &man, std::string_view name)
bool inspect () const override
Should the PassMan even consider this pass?
M * curr_mut () const
Public Member Functions inherited from thorin::Pass
Pass (PassMan &, std::string_view name)
virtual ~Pass ()=default
World & world ()
PassMan & man ()
const PassMan & man () const
std::string_view name () const
size_t index () const
virtual Ref rewrite (Ref def)
virtual Ref rewrite (const Var *var)
virtual Ref rewrite (const Proxy *proxy)
virtual undo_t analyze (Ref)
virtual undo_t analyze (const Var *)
virtual undo_t analyze (const Proxy *)
virtual void enter ()
Invoked just before Pass::rewriteing PassMan::curr_mut's body.
virtual void prepare ()
Invoked once before entering the main rewrite loop.
const Proxy * proxy (Ref type, Defs ops, u32 tag=0)
const Proxy * isa_proxy (Ref def, u32 tag=0)
Check whether given def is a Proxy whose Proxy::pass matches this Pass's IPass::index.
const Proxy * as_proxy (Ref def, u32 tag=0)
Protected Member Functions
State-related Getters
const auto & states () const
auto & states ()
auto & data ()
template<size_t I>
auto & data ()
template<class K >
auto & data (const K &key)
Use this for your convenience if P::Data is a map.
template<size_t I, class K >
auto & data (const K &key)
Use this for your convenience if P::Data<I> is a map.
undo
undo_t curr_undo () const
Current undo point.
undo_t undo_visit (Def *mut) const
Retrieves the point to backtrack to just before mut was seen the very first time.
undo_t undo_enter (Def *mut) const
Retrieves the point to backtrack to just before rewriting mut's body.
Private Member Functions
Memory Management for State
void * alloc () override
Default constructor.
void * copy (const void *p) override
Copy constructor.
void dealloc (void *state) override
Destructor.
Detailed Description
template<class P, class M = Def>
class thorin::FPPass< P, M >
Inherit from this class using CRTP, if you do need a Pass with a state and a fixed-point.
Definition at line 242 of file pass.h.
Member Typedef Documentation
Data
template<class P , class M = Def> using thorin::FPPass< P, M >::Data = std::tuple<>
Default.
Definition at line 245 of file pass.h.
Super
template<class P , class M = Def> using thorin::FPPass< P, M >::Super = RWPass<P, M>
Definition at line 244 of file pass.h.
Constructor & Destructor Documentation
FPPass()
template<class P , class M = Def> thorin::FPPass< P, M >::FPPass (PassMan & man, std::string_view name) inline
Definition at line 247 of file pass.h.
Member Function Documentation
alloc()
template<class P , class M = Def> void * thorin::FPPass< P, M >::alloc () inline override private virtual
Default constructor.
Reimplemented from thorin::Pass.
Definition at line 290 of file pass.h.
copy()
template<class P , class M = Def> void * thorin::FPPass< P, M >::copy (const void *) inline override private virtual
Copy constructor.
Reimplemented from thorin::Pass.
Definition at line 291 of file pass.h.
curr_undo()
template<class P , class M = Def> undo_t thorin::FPPass< P, M >::curr_undo () const inline protected
Current undo point.
Definition at line 270 of file pass.h.
References thorin::Pass::man().
data() [1/4]
template<class P , class M = Def> auto & thorin::FPPass< P, M >::data () inline protected
Definition at line 257 of file pass.h.
References thorin::Pass::index(), and thorin::FPPass< P, M >::states().
data() [2/4]
template<class P , class M = Def> template<size_t I> auto & thorin::FPPass< P, M >::data () inline protected
Definition at line 261 of file pass.h.
References thorin::FPPass< P, M >::data().
Referenced by thorin::FPPass< P, M >::data().
data() [3/4]
template<class P , class M = Def> template<class K > auto & thorin::FPPass< P, M >::data (const K & key) inline protected
Use this for your convenience if P::Data is a map.
Definition at line 263 of file pass.h.
References thorin::FPPass< P, M >::data().
Referenced by thorin::FPPass< P, M >::data().
data() [4/4]
template<class P , class M = Def> template<size_t I, class K > auto & thorin::FPPass< P, M >::data (const K & key) inline protected
Use this for your convenience if P::Data<I> is a map.
Definition at line 265 of file pass.h.
dealloc()
template<class P , class M = Def> void thorin::FPPass< P, M >::dealloc (void *) inline override private virtual
Destructor.
Reimplemented from thorin::Pass.
Definition at line 292 of file pass.h.
fixed_point()
template<class P , class M = Def> bool thorin::FPPass< P, M >::fixed_point () const inline override virtual
Reimplemented from thorin::Pass.
Definition at line 250 of file pass.h.
states() [1/2]
template<class P , class M = Def> auto & thorin::FPPass< P, M >::states () inline protected
Definition at line 256 of file pass.h.
References thorin::Pass::man().
states() [2/2]
template<class P , class M = Def> const auto & thorin::FPPass< P, M >::states () const inline protected
Definition at line 255 of file pass.h.
References thorin::Pass::man().
Referenced by thorin::FPPass< P, M >::data(), and thorin::FPPass< P, M >::undo_enter().
undo_enter()
template<class P , class M = Def> undo_t thorin::FPPass< P, M >::undo_enter (Def * mut) const inline protected
Retrieves the point to backtrack to just before rewriting mut's body.
Definition at line 280 of file pass.h.
References thorin::RWPass< P, M >::curr_mut(), thorin::No_Undo, and thorin::FPPass< P, M >::states().
undo_visit()
template<class P , class M = Def> undo_t thorin::FPPass< P, M >::undo_visit (Def * mut) const inline protected
Retrieves the point to backtrack to just before mut was seen the very first time.
Definition at line 273 of file pass.h.
References thorin::Pass::man(), and thorin::No_Undo.
The documentation for this class was generated from the following file:
include/thorin/pass/pass.h