MimIR: mim::Span< T, N > Class Template Reference
mim::Span< T, N > Class Template Reference
This is a thin wrapper for std::span<T, N> with the following additional features:
#include <mim/util/span.h>
Public Types
using Base = std::span<T, N>
Public Member Functions
Constructors
explicit (N !=D) const expr Span(std
constexpr Span (std::span< T, N > span) noexcept
template<Vectorlike Vec>
requires (std::is_same_v<typename Vec::value_type, T>)
explicit (N !=D) const expr Span(Vec &vec) noexcept(noexcept(vec.data()) &&noexcept(vec.size()))
template<Vectorlike Vec>
requires (std::is_same_v<std::add_const_t<typename Vec::value_type>, std::add_const_t<T>>)
explicit (N !=D) const expr Span(const Vec &vec) noexcept(noexcept(vec.data()) &&noexcept(vec.size()))
constexpr Span (typename Base::pointer p) noexcept
subspan
Wrappers for std::span::subspan that return a mim::Span.
Example: If span points to 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, then
span.subspan<2, 5>() and span.subspan(2, 5) will point to 2, 3, 4, 5, 6.
span.subspan<2>() and span.subspan(2) will point to 2, 3, 4, 5, 6, 7, 8, 9.
constexpr Span< T, D > subspan (size_t i, size_t n=D) const noexcept
template<size_t i, size_t n = D>
constexpr Span< T, n !=D ? n :(N !=D ? N - i :D)> subspan () const noexcept
template<size_t n>
constexpr Span< T, n > span () const noexcept
Get first n elements while keeping track of size statically - useful for structured binding!
rsubspan
Similar to Span::subspan but in reverse:
constexpr Span< T, D > rsubspan (size_t i, size_t n=D) const noexcept
template<size_t i, size_t n = D>
constexpr Span< T, n !=D ? n :(N !=D ? N - i :D)> rsubspan () const noexcept
span.rsubspan(3, 5) removes the last 3 elements and picks 5 elements starting before those.
Static Public Attributes
static constexpr auto D = std::dynamic_extent
Detailed Description
template<class T, size_t N = std::dynamic_extent>
class mim::Span< T, N >
This is a thin wrapper for std::span<T, N> with the following additional features:
Constructor with std::initializer_list (C++26 will get this ...)
Constructor for any compatible Vectorlike argument
rsubspan (reverse subspan)
structured binding, if N != std::dynamic_extent:
void f(Span<int, 3> span) {
    auto& [a, b, c] = span;
    b = 23;
    // ...
}
Definition at line 28 of file span.h.
Member Typedef Documentation
Base
template<class T, size_t N = std::dynamic_extent> using mim::Span< T, N >::Base = std::span<T, N>
Definition at line 30 of file span.h.
Constructor & Destructor Documentation
Span() [1/2]
template<class T, size_t N = std::dynamic_extent> mim::Span< T, N >::Span (std::span< T, N > span) inline constexpr noexcept
Definition at line 38 of file span.h.
Referenced by mim::Span< const T, N >::rsubspan().
Span() [2/2]
template<class T, size_t N = std::dynamic_extent> mim::Span< T, N >::Span (typename Base::pointer p) inline explicit constexpr noexcept
Definition at line 46 of file span.h.
Member Function Documentation
explicit() [1/3]
template<class T, size_t N = std::dynamic_extent> template<Vectorlike Vec> requires (std::is_same_v<std::add_const_t<typename Vec::value_type>, std::add_const_t<T>>) mim::Span< T, N >::explicit (N ! = D) const & inline noexcept
Definition at line 44 of file span.h.
explicit() [2/3]
template<class T, size_t N = std::dynamic_extent> mim::Span< T, N >::explicit (N ! = D) const inline
Definition at line 36 of file span.h.
explicit() [3/3]
template<class T, size_t N = std::dynamic_extent> template<Vectorlike Vec> requires (std::is_same_v<typename Vec::value_type, T>) mim::Span< T, N >::explicit (N ! = D) const & inline noexcept
Definition at line 41 of file span.h.
rsubspan() [1/2]
template<class T, size_t N = std::dynamic_extent> template<size_t i, size_t n = D> Span< T, n !=D ? n :(N !=D ? N - i :D)> mim::Span< T, N >::rsubspan () const inline nodiscard constexpr noexcept
span.rsubspan(3, 5) removes the last 3 elements and picks 5 elements starting before those.
Definition at line 80 of file span.h.
rsubspan() [2/2]
template<class T, size_t N = std::dynamic_extent> Span< T, D > mim::Span< T, N >::rsubspan (size_t i, size_t n = D) const inline nodiscard constexpr noexcept
Definition at line 74 of file span.h.
span()
template<class T, size_t N = std::dynamic_extent> template<size_t n> Span< T, n > mim::Span< T, N >::span () const inline nodiscard constexpr noexcept
Get first n elements while keeping track of size statically - useful for structured binding!
Definition at line 66 of file span.h.
subspan() [1/2]
template<class T, size_t N = std::dynamic_extent> template<size_t i, size_t n = D> Span< T, n !=D ? n :(N !=D ? N - i :D)> mim::Span< T, N >::subspan () const inline nodiscard constexpr noexcept
Definition at line 61 of file span.h.
Referenced by mim::Span< const T, N >::rsubspan(), mim::Span< const T, N >::span(), and mim::Span< const T, N >::subspan().
subspan() [2/2]
template<class T, size_t N = std::dynamic_extent> Span< T, D > mim::Span< T, N >::subspan (size_t i, size_t n = D) const inline nodiscard constexpr noexcept
Definition at line 58 of file span.h.
Member Data Documentation
D
template<class T, size_t N = std::dynamic_extent> auto mim::Span< T, N >::D = std::dynamic_extent static constexpr
Definition at line 31 of file span.h.
The documentation for this class was generated from the following file:
include/mim/util/span.h