Thorin: thorin::Global Class Reference
thorin::Global Class Reference
#include <thorin/def.h>
Public Member Functions
ops
This thing's sole purpose is to differentiate on global from another.
const Def * init () const
void set (const Def *init)
type
const App * type () const
const Def * alloced_type () const
misc getters
bool is_mutable () const
virtual methods
Global * stub (World &, const Def *, const Def *) override
Public Member Functions inherited from thorin::Def
World & world () const
flags_t flags () const
u32 gid () const
hash_t hash () const
node_t node () const
std::string_view node_name () const
const Def * type () const
const Def * unfold_type () const
Sort sort () const
const Def * arity () const
template<size_t N = -1_s>
auto ops () const
const Def * op (size_t i) const
size_t num_ops () const
Def * set (size_t i, const Def *def)
Def * set (Defs ops)
void unset (size_t i)
void unset ()
Def * set_type (const Def *)
void unset_type ()
bool is_set () const
Are all Def::ops set?
bool is_unset () const
Not Def::is_set.
Defs extended_ops () const
const Def * extended_op (size_t i) const
size_t num_extended_ops () const
Defs partial_ops () const
const Def * partial_op (size_t i) const
size_t num_partial_ops () const
const Uses & uses () const
Array< Use > copy_uses () const
size_t num_uses () const
unsigned dep () const
bool dep_none () const
bool dep_const () const
bool dep_proxy () const
nat_t num_projs () const
const Def * proj (nat_t a, nat_t i, const Def *dbg={}) const
Similar to World::extract while assuming an arity of a but also works on Sigmas, and Arrays.
const Def * proj (nat_t i, const Def *dbg={}) const
Same as above but takes Def::num_projs as arity.
template<nat_t A = -1_s, class F >
auto projs (F f, Defs dbgs={}) const
Splits this Def via Def::projections into an Array (if A == -1_s) or std::array (otherwise).
template<class F >
auto projs (nat_t a, F f, Defs dbgs={}) const
template<nat_t A = -1_s>
auto projs (Defs dbgs={}) const
auto projs (nat_t a, Defs dbgs={}) const
bool is_external () const
bool is_internal () const
Not Def::is_external.
void make_external ()
void make_internal ()
const Def * dbg () const
Returns debug information as Def.
Debug debug () const
Returns the debug information as Debug.
std::string name () const
Loc loc () const
const Def * meta () const
void set_dbg (const Def *dbg) const
void set_debug_name (std::string_view) const
Set Def::name in Debug build only; does nothing in Release build.
std::string unique_name () const
name + "_" + Def::gid
template<class T = Def>
const T * isa_structural () const
template<class T = Def>
const T * as_structural () const
template<class T = Def, bool invert = false>
T * isa_nom () const
If this is *nom*inal, it will cast constness away and perform a dynamic cast to T.
template<class T = Def, bool invert = false>
T * as_nom () const
Asserts that this is a *nom*inal, casts constness away and performs a static cast to T (checked in Debug build).
const Var * var (const Def *dbg={})
nat_t num_vars ()
const Def * var (nat_t a, nat_t i, const Def *dbg={})
const Def * var (nat_t i, const Def *dbg={})
template<nat_t A = -1_s, class F >
auto vars (F f, Defs dbgs={})
template<nat_t A = -1_s>
auto vars (Defs dbgs={})
template<class F >
auto vars (nat_t a, F f, Defs dbgs={})
auto vars (nat_t a, Defs dbgs={})
DefArray reduce (const Def *arg) const
DefArray reduce (const Def *arg)
const Def * reduce_rec () const
Transitively Def::reduce Lams, if this is an App.
virtual bool check ()
virtual size_t first_dependend_op ()
virtual const Def * rebuild (World &, const Def *, Defs, const Def *) const
const Def * refine (size_t i, const Def *new_op) const
Def::rebuilds this Def while using new_op as substitute for its i'th Def::op.
virtual const Def * restructure ()
void dump () const
void dump (int max) const
void write (int max) const
void write (int max, const char *file) const
std::ostream & stream (std::ostream &, int max) const
Public Member Functions inherited from thorin::RuntimeCast< Def >
T * isa ()
Dynamic cast.
const T * isa () const
Dynamic cast. const version.
T * as ()
Static cast with debug check.
const T * as () const
Static cast with debug check. const version.
Static Public Attributes
static constexpr auto Node = Node::Global
Friends
class World
Additional Inherited Members
Public Types inherited from thorin::Def
using NormalizeFn = const Def *(*)(const Def *, const Def *, const Def *, const Def *)
Protected Member Functions inherited from thorin::Def
Def (World *, node_t, const Def *type, Defs ops, flags_t flags, const Def *dbg)
Constructor for a structural Def.
Def (node_t n, const Def *type, Defs ops, flags_t flags, const Def *dbg)
Def (node_t, const Def *type, size_t num_ops, flags_t flags, const Def *dbg)
Constructor for a *nom*inal Def.
virtual ~Def ()=default
const Def ** ops_ptr () const
void finalize ()
bool equal (const Def *other) const
Protected Attributes inherited from thorin::Def
union {
NormalizeFn normalizer_
Axioms use this member to store their normalizer.
const Axiom * axiom_
World * world_
Curried Apps of Axioms use this member to propagate the Axiom.
};
flags_t flags_
uint8_t node_
unsigned nom_: 1
unsigned dep_: 4
unsigned pading_: 3
u16 curry_
hash_t hash_
u32 gid_
u32 num_ops_
Uses uses_
const Def * dbg_
const Def * type_
Detailed Description
Deprecated:
A global variable in the data segment. A Global may be mutable or immutable.
Attention
WILL BE REMOVED.
Definition at line 599 of file def.h.
Member Function Documentation
alloced_type()
const Def * thorin::Global::alloced_type () const
Definition at line 416 of file def.cpp.
References thorin::App::arg(), and type().
init()
const Def * thorin::Global::init () const inline
Definition at line 608 of file def.h.
References thorin::Def::op().
Referenced by set().
is_mutable()
bool thorin::Global::is_mutable () const inline
Definition at line 620 of file def.h.
References thorin::Def::flags().
Referenced by stub().
set()
void thorin::Global::set (const Def * init) inline
Definition at line 609 of file def.h.
References init(), and thorin::Def::set().
stub()
Global * thorin::Global::stub (World & w, const Def * t, const Def * dbg) override virtual
Reimplemented from thorin::Def.
Definition at line 113 of file def.cpp.
References thorin::Def::dbg(), thorin::World::global(), is_mutable(), and thorin::t.
type()
const App * thorin::Global::type () const
Definition at line 415 of file def.cpp.
References thorin::RuntimeCast< Base >::as(), and thorin::Def::type().
Referenced by alloced_type().
Friends And Related Function Documentation
World
friend class World friend
Definition at line 629 of file def.h.
Member Data Documentation
Node
constexpr auto thorin::Global::Node = Node::Global static constexpr
Definition at line 628 of file def.h.
The documentation for this class was generated from the following files:
thorin/def.h
thorin/def.cpp