MimIR: mim::Sets< D, N >::Set::iterator Class Reference
mim::Sets< D, N >::Set::iterator Class Reference
#include <mim/util/sets.h>
Public Types
Iterator Properties
using iterator_category = std::forward_iterator_tag
using difference_type = std::ptrdiff_t
using value_type = D*
using pointer = D* const*
using reference = D* const&
Public Member Functions
iterator & clear ()
Construction
constexpr iterator () noexcept=default
Increment
Note
These operations only change the view of this Set; the Set itself is not modified.
constexpr iterator & operator++ () noexcept
constexpr iterator operator++ (int) noexcept
Comparisons
constexpr bool operator== (iterator other) const noexcept
constexpr bool operator!= (iterator other) const noexcept
Dereference
constexpr reference operator* () const noexcept
constexpr pointer operator-> () const noexcept
Friends
class Set
Detailed Description
template<class D, size_t N = 16>
class mim::Sets< D, N >::Set::iterator
Definition at line 284 of file sets.h.
Member Typedef Documentation
difference_type
template<class D , size_t N = 16> using mim::Sets< D, N >::Set::iterator::difference_type = std::ptrdiff_t
Definition at line 300 of file sets.h.
iterator_category
template<class D , size_t N = 16> using mim::Sets< D, N >::Set::iterator::iterator_category = std::forward_iterator_tag
Definition at line 299 of file sets.h.
pointer
template<class D , size_t N = 16> using mim::Sets< D, N >::Set::iterator::pointer = D* const*
Definition at line 302 of file sets.h.
reference
template<class D , size_t N = 16> using mim::Sets< D, N >::Set::iterator::reference = D* const&
Definition at line 303 of file sets.h.
value_type
template<class D , size_t N = 16> using mim::Sets< D, N >::Set::iterator::value_type = D*
Definition at line 301 of file sets.h.
Constructor & Destructor Documentation
iterator()
template<class D , size_t N = 16> mim::Sets< D, N >::Set::iterator::iterator () constexpr default noexcept
Member Function Documentation
clear()
template<class D , size_t N = 16> iterator & mim::Sets< D, N >::Set::iterator::clear () inline
Definition at line 362 of file sets.h.
Referenced by mim::Sets< D, N >::Set::iterator::operator++().
operator!=()
template<class D , size_t N = 16> bool mim::Sets< D, N >::Set::iterator::operator!= (iterator other) const inline constexpr noexcept
Definition at line 344 of file sets.h.
operator*()
template<class D , size_t N = 16> reference mim::Sets< D, N >::Set::iterator::operator* () const inline constexpr noexcept
Definition at line 350 of file sets.h.
Referenced by mim::Sets< D, N >::Set::iterator::operator->().
operator++() [1/2]
template<class D , size_t N = 16> iterator & mim::Sets< D, N >::Set::iterator::operator++ () inline constexpr noexcept
Definition at line 314 of file sets.h.
References mim::Sets< D, N >::Set::iterator::clear().
Referenced by mim::Sets< D, N >::Set::iterator::operator++().
operator++() [2/2]
template<class D , size_t N = 16> iterator mim::Sets< D, N >::Set::iterator::operator++ (int) inline constexpr noexcept
Definition at line 333 of file sets.h.
References mim::Sets< D, N >::Set::iterator::operator++().
operator->()
template<class D , size_t N = 16> pointer mim::Sets< D, N >::Set::iterator::operator-> () const inline constexpr noexcept
Definition at line 359 of file sets.h.
References mim::Sets< D, N >::Set::iterator::operator*().
operator==()
template<class D , size_t N = 16> bool mim::Sets< D, N >::Set::iterator::operator== (iterator other) const inline constexpr noexcept
Definition at line 343 of file sets.h.
Friends And Related Symbol Documentation
Set
template<class D , size_t N = 16> friend class Set friend
Definition at line 368 of file sets.h.
The documentation for this class was generated from the following file:
include/mim/util/sets.h