MimIR: mim::ast::Scopes Class Reference
mim::ast::Scopes Class Reference
Public Types
using Scope = fe::SymMap<std::pair<Loc, const Decl*>>
Public Member Functions
Scopes (AST &ast)
AST & ast () const
Driver & driver () const
Scope & top ()
const Decl * dummy () const
void push ()
void pop ()
const Decl * find (Dbg dbg, bool quiet=false)
void bind (Dbg dbg, const Decl *decl, bool rebind=false, bool quiet=false)
Detailed Description
Definition at line 17 of file bind.cpp.
Member Typedef Documentation
Scope
using mim::ast::Scopes::Scope = fe::SymMap<std::pair<Loc, const Decl*>>
Definition at line 19 of file bind.cpp.
Constructor & Destructor Documentation
Scopes()
mim::ast::Scopes::Scopes (AST & ast) inline
Definition at line 21 of file bind.cpp.
References ast(), and push().
Member Function Documentation
ast()
AST & mim::ast::Scopes::ast () const inline
Definition at line 27 of file bind.cpp.
Referenced by bind(), driver(), find(), and Scopes().
bind()
void mim::ast::Scopes::bind (Dbg dbg, const Decl * decl, bool rebind = false, bool quiet = false) inline
Definition at line 52 of file bind.cpp.
References ast(), mim::ast::AST::error(), mim::ast::AST::note(), and top().
Referenced by find().
driver()
Driver & mim::ast::Scopes::driver () const inline
Definition at line 28 of file bind.cpp.
References ast(), and mim::ast::AST::driver().
dummy()
const Decl * mim::ast::Scopes::dummy () const inline
Definition at line 30 of file bind.cpp.
Referenced by find().
find()
const Decl * mim::ast::Scopes::find (Dbg dbg, bool quiet = false) inline
Definition at line 39 of file bind.cpp.
References ast(), bind(), dummy(), and mim::ast::AST::error().
pop()
void mim::ast::Scopes::pop () inline
Definition at line 34 of file bind.cpp.
push()
void mim::ast::Scopes::push () inline
Definition at line 32 of file bind.cpp.
Referenced by Scopes().
top()
Scope & mim::ast::Scopes::top () inline
Definition at line 29 of file bind.cpp.
Referenced by bind().
The documentation for this class was generated from the following file:
src/mim/ast/bind.cpp