Thorin: thorin::CFA Class Reference
thorin::CFA Class Reference
Control Flow Analysis.
#include <thorin/analyses/cfg.h>
Public Member Functions
CFA (const CFA &)=delete
CFA & operator= (CFA)=delete
CFA (const Scope &scope)
~CFA ()
const Scope & scope () const
World & world () const
size_t size () const
const NomMap< const CFNode * > & nodes () const
const F_CFG & f_cfg () const
const B_CFG & b_cfg () const
const CFNode * operator[] (Def *nom) const
Friends
template<bool >
class CFG
Detailed Description
Control Flow Analysis.
Definition at line 57 of file cfg.h.
Constructor & Destructor Documentation
CFA() [1/2]
thorin::CFA::CFA (const CFA &) delete
CFA() [2/2]
thorin::CFA::CFA (const Scope & scope) explicit
Definition at line 29 of file cfg.cpp.
References thorin::Scope::bound(), thorin::Scope::entry(), thorin::clos::op(), thorin::Def::ops(), thorin::pop(), and scope().
~CFA()
thorin::CFA::~CFA ()
Definition at line 77 of file cfg.cpp.
Member Function Documentation
b_cfg()
const B_CFG & thorin::CFA::b_cfg () const
Definition at line 82 of file cfg.cpp.
References thorin::lazy_init().
Referenced by thorin::Scope::b_cfg().
f_cfg()
const F_CFG & thorin::CFA::f_cfg () const
Definition at line 81 of file cfg.cpp.
References thorin::lazy_init().
Referenced by thorin::Scope::f_cfg().
nodes()
const NomMap< const CFNode * > & thorin::CFA::nodes () const inline
Definition at line 68 of file cfg.h.
Referenced by size().
operator=()
CFA & thorin::CFA::operator= (CFA) delete
operator[]()
const CFNode * thorin::CFA::operator[] (Def * nom) const inline
Definition at line 71 of file cfg.h.
scope()
const Scope & thorin::CFA::scope () const inline
Definition at line 65 of file cfg.h.
Referenced by CFA(), and world().
size()
size_t thorin::CFA::size () const inline
Definition at line 67 of file cfg.h.
References nodes().
Referenced by thorin::CFG< forward >::size().
world()
World & thorin::CFA::world () const inline
Definition at line 66 of file cfg.h.
References scope(), and thorin::Scope::world().
Friends And Related Function Documentation
CFG
template<bool > friend class CFG friend
Definition at line 101 of file cfg.h.
The documentation for this class was generated from the following files:
thorin/analyses/cfg.h
thorin/analyses/cfg.cpp