MimIR: mim::plug::matrix::LowerMatrixLowLevel Class Reference
mim::plug::matrix::LowerMatrixLowLevel Class Reference
In this phase, we lower all matrix operations and types to the low-level representation using pointers.
#include <mim/plug/matrix/pass/lower_matrix_lowlevel.h>
Public Member Functions
LowerMatrixLowLevel (World &world)
Ref rewrite_imm (Ref) override
Public Member Functions inherited from mim::RWPhase
RWPhase (World &world, std::string_view name)
World & world ()
void start () override
Actual entry.
Public Member Functions inherited from mim::Phase
Phase (World &world, std::string_view name, bool dirty)
virtual ~Phase ()=default
World & world ()
std::string_view name () const
bool is_dirty () const
virtual void run ()
Entry point and generates some debug output; invokes Phase::start.
Public Member Functions inherited from mim::Rewriter
Rewriter (World &world)
World & world ()
Ref map (Ref old_def, Ref new_def)
Map old_def to new_def and returns new_def;.
virtual Ref rewrite (Ref)
virtual Ref rewrite_mut (Def *)
Additional Inherited Members
Static Public Member Functions inherited from mim::Phase
template<class P , class... Args>
static void run (Args &&... args)
Runs a single Phase.
Protected Member Functions inherited from mim::Phase
void set_name (std::string name)
Detailed Description
In this phase, we lower all matrix operations and types to the low-level representation using pointers.
The matrix type is replaced by a pointer to n nested arrays.
init is replaced with alloc
read becomes lea+load
insert becomes lea+store
constMat becomes alloc+pack+store
Definition at line 16 of file lower_matrix_lowlevel.h.
Constructor & Destructor Documentation
LowerMatrixLowLevel()
mim::plug::matrix::LowerMatrixLowLevel::LowerMatrixLowLevel (World & world) inline
Definition at line 18 of file lower_matrix_lowlevel.h.
Member Function Documentation
rewrite_imm()
Ref mim::plug::matrix::LowerMatrixLowLevel::rewrite_imm (Ref def) override virtual
Reimplemented from mim::Rewriter.
Definition at line 59 of file lower_matrix_lowlevel.cpp.
References mim::World::call(), mim::World::lit_nat_0(), mim::match(), mim::plug::mem::op_alloc(), mim::Def::projs(), mim::Rewriter::rewrite(), mim::Rewriter::rewrite_imm(), mim::World::tuple(), mim::Def::type(), and mim::RWPhase::world().
The documentation for this class was generated from the following files:
include/mim/plug/matrix/pass/lower_matrix_lowlevel.h
src/mim/plug/matrix/pass/lower_matrix_lowlevel.cpp