Thorin: thorin::Scope Class Reference
thorin::Scope Class Reference
A Scope represents a region of Defs that are live from the view of an entry's Var.
#include <thorin/analyses/scope.h>
Public Member Functions
Scope (const Scope &)=delete
Scope & operator= (Scope)=delete
Scope (Def *entry)
~Scope ()
getters
World & world () const
Def * entry () const
Def * exit () const
Sym sym () const
Defs bound/free in this Scope
bool bound (const Def *def) const
const DefSet & bound () const
All Defs within this Scope.
const DefSet & free_defs () const
All non-const Defs directly referenced but not bound within this Scope. May also include Vars or noms.
const VarSet & free_vars () const
All Vars that occurr free in this Scope. Does not transitively contain any free Vars from noms.
const NomSet & free_noms () const
All noms that occurr free in this Scope.
simple CFA to construct a CFG
const CFA & cfa () const
const F_CFG & f_cfg () const
const B_CFG & b_cfg () const
Detailed Description
A Scope represents a region of Defs that are live from the view of an entry's Var.
Transitively, all user's of the entry's Var are pooled into this Scope (see defs()). Both entry() and exit() are NOT part of the Scope itself. The exit() is just a virtual dummy to have a unique exit dual to entry().
Definition at line 24 of file scope.h.
Constructor & Destructor Documentation
Scope() [1/2]
thorin::Scope::Scope (const Scope &) delete
Scope() [2/2]
thorin::Scope::Scope (Def * entry) explicit
Definition at line 16 of file scope.cpp.
~Scope()
thorin::Scope::~Scope ()
Definition at line 23 of file scope.cpp.
Member Function Documentation
b_cfg()
const B_CFG & thorin::Scope::b_cfg () const
Definition at line 92 of file scope.cpp.
References thorin::CFA::b_cfg(), and cfa().
bound() [1/2]
const DefSet & thorin::Scope::bound () const inline
All Defs within this Scope.
Definition at line 44 of file scope.h.
bound() [2/2]
bool thorin::Scope::bound (const Def * def) const inline
Definition at line 42 of file scope.h.
References bound().
Referenced by bound(), thorin::CFA::CFA(), thorin::is_free(), and thorin::Scheduler::Scheduler().
cfa()
const CFA & thorin::Scope::cfa () const
Definition at line 90 of file scope.cpp.
References thorin::lazy_init().
Referenced by b_cfg(), and f_cfg().
entry()
Def * thorin::Scope::entry () const inline
Definition at line 35 of file scope.h.
Referenced by thorin::CFA::CFA(), thorin::Scheduler::early(), thorin::Scheduler::late(), thorin::ll::Emitter::prepare(), thorin::dot::Emitter::prepare(), thorin::mem::AddMem::visit(), and thorin::Emitter< Value, Type, BB, Child >::visit().
exit()
Def * thorin::Scope::exit () const inline
Definition at line 36 of file scope.h.
Referenced by thorin::ll::Emitter::finalize(), and thorin::Emitter< Value, Type, BB, Child >::visit().
f_cfg()
const F_CFG & thorin::Scope::f_cfg () const
Definition at line 91 of file scope.cpp.
References cfa(), and thorin::CFA::f_cfg().
Referenced by thorin::schedule().
free_defs()
const DefSet & thorin::Scope::free_defs () const inline
All non-const Defs directly referenced but not bound within this Scope. May also include Vars or noms.
Definition at line 45 of file scope.h.
free_noms()
const NomSet & thorin::Scope::free_noms () const inline
All noms that occurr free in this Scope.
Definition at line 47 of file scope.h.
Referenced by thorin::is_top_level(), thorin::ScopePhase::start(), and thorin::mem::AddMem::visit().
free_vars()
const VarSet & thorin::Scope::free_vars () const inline
All Vars that occurr free in this Scope. Does not transitively contain any free Vars from noms.
Definition at line 46 of file scope.h.
Referenced by thorin::is_top_level().
operator=()
Scope & thorin::Scope::operator= (Scope) delete
sym()
Sym thorin::Scope::sym () const inline
Definition at line 37 of file scope.h.
References thorin::Def::sym().
world()
World & thorin::Scope::world () const inline
Definition at line 34 of file scope.h.
Referenced by thorin::Scheduler::smart(), and thorin::CFA::world().
The documentation for this class was generated from the following files:
thorin/analyses/scope.h
thorin/analyses/scope.cpp