Thorin: thorin::ll::CodeGen Class Reference
thorin::ll::CodeGen Class Reference
Public Member Functions
CodeGen (World &world, std::ostream &ostream)
bool is_valid (std::string_view s)
void run ()
void emit_imported (Lam *)
void emit_epilogue (Lam *)
std::string emit_bb (BB &, const Def *)
std::string prepare (const Scope &)
void prepare (Lam *, std::string_view)
void finalize (const Scope &)
Additional Inherited Members
Public Attributes inherited from thorin::Emitter< std::string, std::string, BB, CodeGen >
Tab tab
Protected Member Functions inherited from thorin::Emitter< std::string, std::string, BB, CodeGen >
Emitter (World &world, std::ostream &ostream)
World & world () const
const Scope & scope () const
std::ostream & ostream () const
std::string emit (const Def *def)
Recursively emits code.
std::string emit_unsafe (const Def *def)
As above but returning !child().is_valid(value) is permitted.
void emit_module ()
void emit_scope (const Scope &scope)
Protected Attributes inherited from thorin::Emitter< std::string, std::string, BB, CodeGen >
World & world_
const Scope * scope_
std::ostream & ostream_
Scheduler scheduler_
DefMap< std::string > locals_
DefMap< std::string > globals_
DefMap< std::string > types_
LamMap< BB > lam2bb_
Lam * entry_
Detailed Description
Definition at line 76 of file ll.cpp.
Constructor & Destructor Documentation
CodeGen()
thorin::ll::CodeGen::CodeGen (World & world, std::ostream & ostream) inline
Definition at line 78 of file ll.cpp.
Member Function Documentation
emit_bb()
std::string thorin::ll::CodeGen::emit_bb (BB & bb, const Def * def)
Definition at line 414 of file ll.cpp.
References thorin::core::_and, thorin::_and, thorin::core::_or, thorin::_or, thorin::core::_xor, thorin::_xor, thorin::a, thorin::core::add, thorin::add, thorin::RMode::afn, thorin::RMode::arcp, thorin::as_lit(), thorin::core::ashr, thorin::ashr, thorin::ll::BB::assign(), thorin::b, thorin::ll::BB::body(), thorin::RMode::contract, thorin::div, thorin::core::e, thorin::e, thorin::Emitter< std::string, std::string, BB, CodeGen >::emit(), thorin::Emitter< std::string, std::string, BB, CodeGen >::emit_unsafe(), thorin::Emitter< std::string, std::string, BB, CodeGen >::entry_, thorin::RMode::fast, thorin::g, thorin::ge, thorin::Emitter< std::string, std::string, BB, CodeGen >::globals_, thorin::core::iff, thorin::iff, thorin::ll::is_const(), thorin::RuntimeCast< Base >::isa(), thorin::isa_lit(), thorin::isa_sized_type(), thorin::l, thorin::Emitter< std::string, std::string, BB, CodeGen >::lam2bb_, thorin::le, thorin::core::lshr, thorin::lshr, thorin::mod2width(), thorin::core::mul, thorin::mul, thorin::core::nand, thorin::nand, thorin::core::ne, thorin::ne, thorin::core::neg, thorin::core::niff, thorin::niff, thorin::RMode::ninf, thorin::RMode::nnan, thorin::core::nor, thorin::nor, thorin::WMode::nsw, thorin::RMode::nsz, thorin::WMode::nuw, thorin::core::nxor, thorin::nxor, thorin::o, thorin::clos::op(), thorin::print(), thorin::Def::proj(), thorin::core::r2r, thorin::r2r, thorin::core::r2s, thorin::r2s, thorin::core::r2u, thorin::r2u, thorin::RMode::reassoc, thorin::rem, thorin::core::s2r, thorin::s2r, thorin::core::s2s, thorin::s2s, thorin::core::sdiv, thorin::core::sg, thorin::sg, thorin::core::sge, thorin::sge, thorin::core::shl, thorin::shl, thorin::size, thorin::core::sl, thorin::sl, thorin::core::sle, thorin::sle, thorin::core::srem, thorin::core::sub, thorin::sub, thorin::t, thorin::Def::type(), thorin::u, thorin::core::u2r, thorin::u2r, thorin::core::u2u, thorin::u2u, thorin::core::udiv, thorin::ue, thorin::core::ug, thorin::ug, thorin::core::uge, thorin::uge, thorin::core::ul, thorin::ul, thorin::core::ule, thorin::ule, thorin::une, thorin::unreachable(), and thorin::core::urem.
emit_epilogue()
void thorin::ll::CodeGen::emit_epilogue (Lam * lam)
Definition at line 297 of file ll.cpp.
References thorin::RuntimeCast< Base >::as(), thorin::Def::as_nom(), thorin::Lam::body(), thorin::e, thorin::Emitter< std::string, std::string, BB, CodeGen >::emit(), thorin::Emitter< std::string, std::string, BB, CodeGen >::emit_unsafe(), thorin::Emitter< std::string, std::string, BB, CodeGen >::entry_, thorin::f, thorin::Lam::is_basicblock(), thorin::Emitter< std::string, std::string, BB, CodeGen >::lam2bb_, thorin::Emitter< std::string, std::string, BB, CodeGen >::locals_, thorin::Def::num_vars(), thorin::print(), thorin::Lam::ret_var(), thorin::t, thorin::Def::unique_name(), thorin::Def::var(), and thorin::Emitter< std::string, std::string, BB, CodeGen >::world().
emit_imported()
void thorin::ll::CodeGen::emit_imported (Lam * lam)
Definition at line 233 of file ll.cpp.
References thorin::print(), thorin::Pi::ret_pi(), and thorin::Lam::type().
finalize()
void thorin::ll::CodeGen::finalize (const Scope & scope)
Definition at line 266 of file ll.cpp.
References thorin::Scope::exit(), thorin::Emitter< std::string, std::string, BB, CodeGen >::lam2bb_, thorin::print(), thorin::Tab::print(), thorin::schedule(), thorin::Emitter< std::string, std::string, BB, CodeGen >::scope(), and thorin::Emitter< std::string, std::string, BB, CodeGen >::tab.
is_valid()
bool thorin::ll::CodeGen::is_valid (std::string_view s) inline
Definition at line 81 of file ll.cpp.
prepare() [1/2]
std::string thorin::ll::CodeGen::prepare (const Scope & scope)
Definition at line 247 of file ll.cpp.
References thorin::Def::as_nom(), thorin::Scope::entry(), thorin::Emitter< std::string, std::string, BB, CodeGen >::locals_, thorin::print(), and thorin::Emitter< std::string, std::string, BB, CodeGen >::scope().
prepare() [2/2]
void thorin::ll::CodeGen::prepare (Lam * , std::string_view)
run()
void thorin::ll::CodeGen::run ()
Definition at line 219 of file ll.cpp.
References thorin::Emitter< std::string, std::string, BB, CodeGen >::emit_module(), and thorin::Emitter< std::string, std::string, BB, CodeGen >::ostream().
Referenced by thorin::ll::emit().
The documentation for this class was generated from the following file:
/home/runner/work/thorin2/thorin2/dialects/core/be/ll/ll.cpp