Thorin: thorin::Driver Class Reference
thorin::Driver Class Reference
Some "global" variables needed all over the place.
#include <thorin/driver.h>
Public Member Functions
Driver ()
Getters
Flags & flags ()
Log & log ()
World & world ()
Manage Search Paths
Search paths for plugins are in the following order:
The empty path. Used as prefix to look into current working directory without resorting to an absolute path.
All further user-specified paths via Driver::add_search_path; paths added first will also be searched first.
All paths specified in the environment variable THORIN_PLUGIN_PATH.
path/to/thorin.exe/../../lib/thorin
CMAKE_INSTALL_PREFIX/lib/thorin
const auto & search_paths () const
void add_search_path (fs::path path)
Manage Imports
This is a list of pairs where each pair contains:
The fs::path used during import,
The name as Symbol used in the .import directive or in Parser::import.
const auto & imports ()
const fs::path * add_import (fs::path, Sym)
Yields a fs::path* if not already added that you can use in Location; returns nullptr otherwise.
Load Plugin
Finds and loads a shared object file that implements the Thorin Plugin name.
If name is an absolute path to a .so/.dll file, this is used. Otherwise, "name", "libthorin_name.so" (Linux, Mac), "thorin_name.dll" (Win) are searched for in Driver::search_paths().
void load (Sym name)
void load (std::string name)
bool is_loaded (Sym sym) const
Manage Plugins
All these lookups yield nullptr if the key has not been found.
auto pass (flags_t flags)
auto normalizer (flags_t flags) const
auto normalizer (plugin_t d, tag_t t, sub_t s) const
auto backend (std::string_view name)
Manage Axiom::Info
const auto & plugin2axiom_infos (Sym plugin)
std::pair< Axiom::Info &, bool > axiom2info (Sym sym, Sym plugin, Sym tag, Loc loc)
Public Member Functions inherited from thorin::SymPool
SymPool ()=default
SymPool (const SymPool &)=delete
SymPool (SymPool &&other)
Sym sym (std::string_view s)
Sym sym (const char *s)
Sym sym (std::string s)
Detailed Description
Some "global" variables needed all over the place.
Well, there are not really global - that's the point of this class.
Definition at line 17 of file driver.h.
Constructor & Destructor Documentation
Driver()
thorin::Driver::Driver ()
Definition at line 19 of file driver.cpp.
References add_search_path(), thorin::sys::path_to_curr_exe(), search_paths(), and THORIN_INSTALL_PREFIX.
Member Function Documentation
add_import()
const fs::path * thorin::Driver::add_import (fs::path path, Sym sym)
Yields a fs::path* if not already added that you can use in Location; returns nullptr otherwise.
Definition at line 44 of file driver.cpp.
References thorin::SymPool::sym().
add_search_path()
void thorin::Driver::add_search_path (fs::path path) inline
Definition at line 37 of file driver.h.
Referenced by Driver().
axiom2info()
std::pair< Axiom::Info &, bool > thorin::Driver::axiom2info (Sym sym, Sym plugin, Sym tag, Loc loc)
Definition at line 89 of file driver.cpp.
References thorin::error(), and thorin::SymPool::sym().
backend()
auto thorin::Driver::backend (std::string_view name) inline
Definition at line 69 of file driver.h.
References thorin::lookup().
flags()
Flags & thorin::Driver::flags () inline
Definition at line 23 of file driver.h.
Referenced by thorin::World::flags(), main(), normalizer(), and pass().
imports()
const auto & thorin::Driver::imports () inline
Definition at line 47 of file driver.h.
is_loaded()
bool thorin::Driver::is_loaded (Sym sym) const inline
Definition at line 60 of file driver.h.
References thorin::lookup(), and thorin::SymPool::sym().
Referenced by load().
load() [1/2]
void thorin::Driver::load (std::string name) inline
Definition at line 59 of file driver.h.
References load(), and thorin::SymPool::sym().
Referenced by load().
load() [2/2]
void thorin::Driver::load (Sym name)
Definition at line 52 of file driver.cpp.
References thorin::assert_emplace(), thorin::dl::close(), thorin::error(), thorin::dl::get(), ILOG, is_loaded(), thorin::dl::open(), search_paths(), thorin::thorin_get_plugin(), and WLOG.
Referenced by thorin::fe::Parser::plugin().
log()
Log & thorin::Driver::log () inline
Definition at line 24 of file driver.h.
Referenced by thorin::World::log().
normalizer() [1/2]
auto thorin::Driver::normalizer (flags_t flags) const inline
Definition at line 67 of file driver.h.
References flags(), and thorin::lookup().
normalizer() [2/2]
auto thorin::Driver::normalizer (plugin_t d, tag_t t, sub_t s) const inline
Definition at line 68 of file driver.h.
References normalizer().
Referenced by normalizer().
pass()
auto thorin::Driver::pass (flags_t flags) inline
Definition at line 66 of file driver.h.
References flags(), and thorin::lookup().
Referenced by thorin::optimize().
plugin2axiom_infos()
const auto & thorin::Driver::plugin2axiom_infos (Sym plugin) inline
Definition at line 74 of file driver.h.
Referenced by thorin::bootstrap().
search_paths()
const auto & thorin::Driver::search_paths () const inline
Definition at line 36 of file driver.h.
Referenced by Driver(), and load().
world()
World & thorin::Driver::world () inline
Definition at line 25 of file driver.h.
The documentation for this class was generated from the following files:
thorin/driver.h
thorin/driver.cpp