Thorin: thorin::utf8::Lexer< Max_Ahead > Class Template Reference
thorin::utf8::Lexer< Max_Ahead > Class Template Reference
#include <thorin/util/utf8.h>
Classes
struct Ahead
Public Member Functions
Lexer (std::string_view filename, std::istream &istream)
virtual ~Lexer ()
Protected Member Functions
Ahead ahead (size_t i=0) const
virtual Ahead next ()
template<class Pred >
bool accept_if (Pred pred, bool append=true)
Yields true if pred holds.
bool accept (char32_t val, bool append=true)
Protected Attributes
std::istream & istream_
Loc loc_
std::string str_
std::array< Ahead, Max_Ahead > ahead_
Detailed Description
template<size_t Max_Ahead>
class thorin::utf8::Lexer< Max_Ahead >
Definition at line 42 of file utf8.h.
Constructor & Destructor Documentation
Lexer()
template<size_t Max_Ahead> thorin::utf8::Lexer< Max_Ahead >::Lexer (std::string_view filename, std::istream & istream) inline
Definition at line 44 of file utf8.h.
~Lexer()
template<size_t Max_Ahead> virtual thorin::utf8::Lexer< Max_Ahead >::~Lexer () inline virtual
Definition at line 51 of file utf8.h.
Member Function Documentation
accept()
template<size_t Max_Ahead> bool thorin::utf8::Lexer< Max_Ahead >::accept (char32_t val, bool append = true) inline protected
Definition at line 104 of file utf8.h.
References thorin::utf8::Lexer< Max_Ahead >::accept_if(), and thorin::utf8::append().
accept_if()
template<size_t Max_Ahead> template<class Pred > bool thorin::utf8::Lexer< Max_Ahead >::accept_if (Pred pred, bool append = true) inline protected
Yields true if pred holds.
In this case invoke next() and append to str_;
Definition at line 95 of file utf8.h.
References thorin::utf8::Lexer< Max_Ahead >::ahead(), thorin::utf8::append(), thorin::utf8::Lexer< Max_Ahead >::next(), and thorin::utf8::Lexer< Max_Ahead >::str_.
Referenced by thorin::utf8::Lexer< Max_Ahead >::accept().
ahead()
template<size_t Max_Ahead> Ahead thorin::utf8::Lexer< Max_Ahead >::ahead (size_t i = 0) const inline protected
Definition at line 65 of file utf8.h.
References thorin::utf8::Lexer< Max_Ahead >::ahead_.
Referenced by thorin::utf8::Lexer< Max_Ahead >::accept_if(), and thorin::utf8::Lexer< Max_Ahead >::next().
next()
template<size_t Max_Ahead> virtual Ahead thorin::utf8::Lexer< Max_Ahead >::next () inline protected virtual
Definition at line 70 of file utf8.h.
References thorin::utf8::Lexer< Max_Ahead >::ahead(), thorin::utf8::Lexer< Max_Ahead >::ahead_, thorin::utf8::encode(), thorin::utf8::EoF, thorin::Loc::finis, thorin::utf8::Lexer< Max_Ahead >::istream_, and thorin::utf8::Lexer< Max_Ahead >::loc_.
Referenced by thorin::utf8::Lexer< Max_Ahead >::accept_if().
Member Data Documentation
ahead_
template<size_t Max_Ahead> std::array<Ahead, Max_Ahead> thorin::utf8::Lexer< Max_Ahead >::ahead_ protected
Definition at line 111 of file utf8.h.
Referenced by thorin::utf8::Lexer< Max_Ahead >::ahead(), and thorin::utf8::Lexer< Max_Ahead >::next().
istream_
template<size_t Max_Ahead> std::istream& thorin::utf8::Lexer< Max_Ahead >::istream_ protected
Definition at line 108 of file utf8.h.
Referenced by thorin::utf8::Lexer< Max_Ahead >::next().
loc_
template<size_t Max_Ahead> Loc thorin::utf8::Lexer< Max_Ahead >::loc_ protected
Definition at line 109 of file utf8.h.
Referenced by thorin::utf8::Lexer< Max_Ahead >::next().
str_
template<size_t Max_Ahead> std::string thorin::utf8::Lexer< Max_Ahead >::str_ protected
Definition at line 110 of file utf8.h.
Referenced by thorin::utf8::Lexer< Max_Ahead >::accept_if().
The documentation for this class was generated from the following file:
thorin/util/utf8.h