MimIR: mim::Error Class Reference
mim::Error Class Reference
#include <mim/util/dbg.h>
Classes
struct Msg
Public Types
enum class Tag {
Error ,
Warn ,
Note
}
Public Member Functions
Constructors
Error ()=default
Error (const Error &)=default
Error (Error &&other)
Error (Loc loc, const std::string &str)
Creates a single Tag::Error message.
Getters
const auto & msgs () const
size_t num_msgs () const
size_t num_errors () const
size_t num_warnings () const
size_t num_notes () const
Add formatted message
template<class... Args>
Error & msg (Loc loc, Tag tag, const char *s, Args &&... args)
template<class... Args>
Error & error (Loc loc, const char *s, Args &&... args)
template<class... Args>
Error & warn (Loc loc, const char *s, Args &&... args)
template<class... Args>
Error & note (Loc loc, const char *s, Args &&... args)
Handle Errors/Warnings
void clear ()
void ack (std::ostream &os=std::cerr)
If errors occured, claim them and throw; if warnings occured, claim them and report to os.
Friends
std::ostream & operator<< (std::ostream &o, Tag tag)
std::ostream & operator<< (std::ostream &os, const Error &e)
void swap (Error &e1, Error &e2) noexcept
Detailed Description
Definition at line 17 of file dbg.h.
Member Enumeration Documentation
Tag
enum class mim::Error::Tag strong
Enumerator
Error
Warn
Note
Definition at line 19 of file dbg.h.
Constructor & Destructor Documentation
Error() [1/4]
mim::Error::Error () default
Referenced by Error(), Error(), Error, error(), msg(), note(), operator<<, swap, and warn().
Error() [2/4]
mim::Error::Error (const Error &) default
References Error().
Error() [3/4]
mim::Error::Error (Error && other) inline
Definition at line 40 of file dbg.h.
References Error(), and swap.
Error() [4/4]
mim::Error::Error (Loc loc, const std::string & str) inline
Creates a single Tag::Error message.
Definition at line 45 of file dbg.h.
References Error.
Member Function Documentation
ack()
void mim::Error::ack (std::ostream & os = std::cerr)
If errors occured, claim them and throw; if warnings occured, claim them and report to os.
Definition at line 15 of file dbg.cpp.
References mim::print().
clear()
void mim::Error::clear ()
Definition at line 7 of file dbg.cpp.
error()
template<class... Args> Error & mim::Error::error (Loc loc, const char * s, Args &&... args) inline
Definition at line 72 of file dbg.h.
References Error(), Error, and msg().
Referenced by mim::World::app(), mim::Lam::check(), mim::ast::AST::error(), mim::World::insert(), and mim::plug::regex::normalize_not().
msg()
template<class... Args> Error & mim::Error::msg (Loc loc, Tag tag, const char * s, Args &&... args) inline
Definition at line 66 of file dbg.h.
References Error(), and mim::fmt().
Referenced by error(), note(), mim::Error::Msg::operator<<, operator<<, and warn().
msgs()
const auto & mim::Error::msgs () const inline
Definition at line 53 of file dbg.h.
note()
template<class... Args> Error & mim::Error::note (Loc loc, const char * s, Args &&... args) inline
Definition at line 74 of file dbg.h.
References Error(), msg(), Note, num_errors(), and num_warnings().
Referenced by mim::World::app(), mim::Lam::check(), mim::World::insert(), and mim::ast::AST::note().
num_errors()
size_t mim::Error::num_errors () const inline
Definition at line 58 of file dbg.h.
Referenced by note(), and num_msgs().
num_msgs()
size_t mim::Error::num_msgs () const inline
Definition at line 54 of file dbg.h.
References num_errors(), num_notes(), and num_warnings().
num_notes()
size_t mim::Error::num_notes () const inline
Definition at line 60 of file dbg.h.
Referenced by num_msgs().
num_warnings()
size_t mim::Error::num_warnings () const inline
Definition at line 59 of file dbg.h.
Referenced by note(), and num_msgs().
warn()
template<class... Args> Error & mim::Error::warn (Loc loc, const char * s, Args &&... args) inline
Definition at line 73 of file dbg.h.
References Error(), msg(), and Warn.
Referenced by mim::ast::AST::warn().
Friends And Related Symbol Documentation
operator<< [1/2]
std::ostream & operator<< (std::ostream & o, Tag tag) friend
Definition at line 87 of file dbg.h.
References Error, Note, and Warn.
operator<< [2/2]
std::ostream & operator<< (std::ostream & os, const Error & e) friend
Definition at line 98 of file dbg.h.
References Error(), and msg().
swap
void swap (Error & e1, Error & e2) friend
Definition at line 104 of file dbg.h.
References Error(), and swap.
Referenced by Error(), and swap.
The documentation for this class was generated from the following files:
include/mim/util/dbg.h
src/mim/util/dbg.cpp