MimIR: mim::SymExprOpt Class Reference
mim::SymExprOpt Class Reference
Symbolic Expression Optimization.
#include <mim/phase/sym_expr_opt.h>
Public Member Functions
SymExprOpt (World &world, flags_t annex)
Public Member Functions inherited from mim::RWPhase
bool is_bootstrapping () const
Returns whether we are currently bootstrapping (rewriting annexes).
virtual bool analyze ()
You can do an optional fixed-point loop on the RWPhase::old_world before rewriting.
RWPhase (World &world, std::string name, Analysis *analysis=nullptr)
RWPhase (World &world, flags_t annex, Analysis *analysis=nullptr)
virtual void rewrite_annex (flags_t, const Def *)
virtual void rewrite_external (Def *)
World & world ()=delete
Hides both and forbids direct access.
World & old_world ()
Get old Defs from here.
World & new_world ()
Create new Defs into this.
Public Member Functions inherited from mim::Phase
Phase (World &world, std::string name)
Phase (World &world, flags_t annex)
bool todo () const
virtual void run ()
Entry point and generates some debug output; invokes Phase::start.
Public Member Functions inherited from mim::Stage
World & world ()
Driver & driver ()
Log & log () const
std::string_view name () const
flags_t annex () const
Stage (World &world, std::string name)
Stage (World &world, flags_t annex)
virtual ~Stage ()=default
virtual std::unique_ptr< Stage > recreate ()
Creates a new instance; needed by a fixed-point PhaseMan.
virtual void apply (const App *)
Invoked if your Stage has additional args.
virtual void apply (Stage &)
Dito, but invoked by Stage::recreate.
Public Member Functions inherited from mim::Rewriter
Rewriter (std::unique_ptr< World > &&ptr)
Rewriter (World &world)
virtual ~Rewriter ()=default
void reset (std::unique_ptr< World > &&ptr)
void reset ()
World & world ()
virtual void push ()
virtual void pop ()
virtual const Def * map (const Def *old_def, const Def *new_def)
const Def * map (const Def *old_def, Defs new_defs)
const Def * map (Defs old_defs, const Def *new_def)
const Def * map (Defs old_defs, Defs new_defs)
virtual const Def * lookup (const Def *old_def)
Lookup old_def by searching in reverse through the stack of maps.
virtual const Def * rewrite (const Def *)
virtual const Def * rewrite_imm (const Def *)
virtual const Def * rewrite_mut (Def *)
virtual const Def * rewrite_stub (Def *, Def *)
virtual DefVec rewrite (Defs)
virtual const Def * rewrite_imm_Seq (const Seq *seq)
virtual const Def * rewrite_mut_Seq (Seq *seq)
Private Member Functions
const Def * rewrite_imm_App (const App *) final
Additional Inherited Members
template<class P, class... Args>
static void run (Args &&... args)
Runs a single Phase.
static auto create (const Flags2Stages &stages, const Def *def)
template<class A, class P>
static void hook (Flags2Stages &stages)
Protected Member Functions inherited from mim::RWPhase
void start () override
Actual entry.
Protected Attributes inherited from mim::Phase
bool todo_ = false
Set to true to indicate that you want to rerun all Phasees in your current fixed-point PhaseMan.
Protected Attributes inherited from mim::Stage
std::string name_
Protected Attributes inherited from mim::Rewriter
std::deque< Def2Def > old2news_
Detailed Description
Symbolic Expression Optimization.
Combines:
Constant propagation with conditional branches but propagates arbitrary expressions
Detecting equality of variables in programs
Much in the spirit of Combining analyses, combining optimizations.
Due to MimIR's sea of node structure a number of other optimizations kick in such as arithmetic simplifications and code motion.
Lattice per Lam::var:
 ⊤      ← Keep as is
 |
Bundle  ← Vars that (horizontally) behave the same build a single congruence class
 |
Expr    ← Whole expression is propagated (vertically) through var
 |
 ⊥
Definition at line 27 of file sym_expr_opt.h.
Constructor & Destructor Documentation
SymExprOpt()
mim::SymExprOpt::SymExprOpt (World & world, flags_t annex) inline
Definition at line 45 of file sym_expr_opt.h.
References mim::Stage::annex(), mim::RWPhase::RWPhase(), and mim::RWPhase::world().
Member Function Documentation
rewrite_imm_App()
const Def * mim::SymExprOpt::rewrite_imm_App (const App * old_app) final private
Definition at line 151 of file sym_expr_opt.cpp.
References mim::App::callee(), mim::first_in_bundle(), mim::Def::isa_mut(), mim::Rewriter::map(), mim::World::mut_lam(), mim::RWPhase::new_world(), mim::Def::num_vars(), mim::Rewriter::rewrite(), mim::Lam::set(), mim::Phase::todo_, and mim::Def::var().
The documentation for this class was generated from the following files:
include/mim/phase/sym_expr_opt.h
src/mim/phase/sym_expr_opt.cpp