Thorin: thorin::unique_queue< Set > Class Template Reference
thorin::unique_queue< Set > Class Template Reference
#include <thorin/util/container.h>
Public Types
using T = typename std::remove_reference_t< Set >::value_type
Public Member Functions
unique_queue ()=default
unique_queue (Set set)
bool push (T val)
bool empty () const
T pop ()
T & front ()
T & back ()
void clear ()
Detailed Description
template<class Set>
class thorin::unique_queue< Set >
Definition at line 62 of file container.h.
Member Typedef Documentation
T
template<class Set > using thorin::unique_queue< Set >::T = typename std::remove_reference_t<Set>::value_type
Definition at line 64 of file container.h.
Constructor & Destructor Documentation
unique_queue() [1/2]
template<class Set > thorin::unique_queue< Set >::unique_queue () default
unique_queue() [2/2]
template<class Set > thorin::unique_queue< Set >::unique_queue (Set set) inline
Definition at line 67 of file container.h.
Member Function Documentation
back()
template<class Set > T & thorin::unique_queue< Set >::back () inline
Definition at line 81 of file container.h.
clear()
template<class Set > void thorin::unique_queue< Set >::clear () inline
Definition at line 82 of file container.h.
empty()
template<class Set > bool thorin::unique_queue< Set >::empty () const inline
Definition at line 78 of file container.h.
Referenced by thorin::ScopePhase::start().
front()
template<class Set > T & thorin::unique_queue< Set >::front () inline
Definition at line 80 of file container.h.
pop()
template<class Set > T thorin::unique_queue< Set >::pop () inline
Definition at line 79 of file container.h.
References thorin::pop().
Referenced by thorin::ScopePhase::start().
push()
template<class Set > bool thorin::unique_queue< Set >::push (T val) inline
Definition at line 70 of file container.h.
Referenced by thorin::Dumper::recurse(), and thorin::ScopePhase::start().
The documentation for this class was generated from the following file:
thorin/util/container.h