MimIR: mim::BetaRed Class Reference
mim::BetaRed Class Reference
Optimistically performs β-reduction (aka inlining).
#include <mim/pass/beta_red.h>
Public Types
using Data = LamSet
Public Types inherited from mim::FPPass< BetaRed, Def >
using Super
using Data
Default.
Public Member Functions
BetaRed (PassMan &man)
void keep (Lam *lam)
Public Member Functions inherited from mim::FPPass< BetaRed, Def >
FPPass (PassMan &man, std::string_view name)
bool fixed_point () const override
Public Member Functions inherited from mim::RWPass< BetaRed, Def >
RWPass (PassMan &man, std::string_view name)
bool inspect () const override
Should the PassMan even consider this pass?
Def * curr_mut () const
Public Member Functions inherited from mim::Pass
Pass (PassMan &, std::string_view name)
virtual ~Pass ()=default
World & world ()
PassMan & man ()
const PassMan & man () const
std::string_view name () const
size_t index () const
virtual const Def * rewrite (const Var *var)
virtual const Def * rewrite (const Proxy *proxy)
virtual undo_t analyze (const Var *)
virtual void enter ()
Invoked just before Pass::rewriteing PassMan::curr_mut's body.
virtual void prepare ()
Invoked once before entering the main rewrite loop.
const Proxy * proxy (const Def *type, Defs ops, u32 tag=0)
const Proxy * isa_proxy (const Def *def, u32 tag=0)
Check whether given def is a Proxy whose Proxy::pass matches this Pass's IPass::index.
const Proxy * as_proxy (const Def *def, u32 tag=0)
Private Member Functions
const Def * rewrite (const Def *) override
undo_t analyze (const Proxy *) override
undo_t analyze (const Def *) override
Additional Inherited Members
Protected Member Functions inherited from mim::FPPass< BetaRed, Def >
const auto & states () const
auto & states ()
auto & data ()
auto & data ()
auto & data (const K &key)
Use this for your convenience if P::Data is a map.
auto & data (const K &key)
Use this for your convenience if P::Data<I> is a map.
undo_t curr_undo () const
Current undo point.
undo_t undo_visit (Def *mut) const
Retrieves the point to backtrack to just before mut was seen the very first time.
undo_t undo_enter (Def *mut) const
Retrieves the point to backtrack to just before rewriting mut's body.
Detailed Description
Optimistically performs β-reduction (aka inlining).
β-reduction of f e happens if f only occurs exactly once in the program in callee position.
Definition at line 9 of file beta_red.h.
Member Typedef Documentation
Data
using mim::BetaRed::Data = LamSet
Definition at line 14 of file beta_red.h.
Constructor & Destructor Documentation
BetaRed()
mim::BetaRed::BetaRed (PassMan & man) inline
Definition at line 11 of file beta_red.h.
References mim::FPPass< BetaRed, Def >::FPPass(), and mim::Pass::man().
Member Function Documentation
analyze() [1/2]
undo_t mim::BetaRed::analyze (const Def * def) override private virtual
Reimplemented from mim::Pass.
Definition at line 28 of file beta_red.cpp.
References mim::RWPass< BetaRed, Def >::curr_mut(), mim::FPPass< BetaRed, Def >::data(), mim::Def::isa_mut(), mim::isa_workable(), mim::No_Undo, mim::Def::ops(), mim::FPPass< BetaRed, Def >::undo_visit(), and mim::Pass::world().
analyze() [2/2]
undo_t mim::BetaRed::analyze (const Proxy * proxy) override private virtual
Reimplemented from mim::Pass.
Definition at line 18 of file beta_red.cpp.
References mim::RWPass< BetaRed, Def >::curr_mut(), mim::No_Undo, mim::Pass::proxy(), mim::FPPass< BetaRed, Def >::undo_visit(), and mim::Pass::world().
keep()
void mim::BetaRed::keep (Lam * lam) inline
Definition at line 16 of file beta_red.h.
rewrite()
const Def * mim::BetaRed::rewrite (const Def * def) override private virtual
Reimplemented from mim::Pass.
Definition at line 5 of file beta_red.cpp.
References mim::FPPass< BetaRed, Def >::data(), mim::isa_apped_mut_lam(), mim::isa_workable(), mim::Pass::proxy(), and mim::Pass::world().
The documentation for this class was generated from the following files:
include/mim/pass/beta_red.h
src/mim/pass/beta_red.cpp