Thorin: thorin::LoopTree< forward >::Base Class Reference
thorin::LoopTree< forward >::Base Class Reference
Represents a node of a loop nesting forest.
#include <thorin/analyses/looptree.h>
Public Types
enum class Node { Head , Leaf }
Public Member Functions
Base (Node node, Head *parent, int depth, const std::vector< const CFNode * > &)
virtual ~Base ()=default
Node node () const
int depth () const
const Head * parent () const
ArrayRef< const CFNode * > cf_nodes () const
size_t num_cf_nodes () const
Public Member Functions inherited from thorin::RuntimeCast< Base >
template<class T >
T * isa ()
Dynamic cast.
template<class T >
const T * isa () const
Dynamic cast. const version.
template<class T >
T * as ()
Static cast with debug check.
template<class T >
const T * as () const
Static cast with debug check. const version.
Protected Attributes
Node node_
Head * parent_
std::vector< const CFNode * > cf_nodes_
int depth_
Detailed Description
template<bool forward>
class thorin::LoopTree< forward >::Base
Represents a node of a loop nesting forest.
A LoopTree::Base consists of a set of header CFNodes. The header CFNodes are the set of CFNodes not dominated by any other CFNode within the loop. The root node is a LoopTree::Head without any CFNodes but further children and depth_ -1. Thus, the forest is pooled into a tree.
Definition at line 27 of file looptree.h.
Member Enumeration Documentation
Node
template<bool forward> enum class thorin::LoopTree::Base::Node strong
Enumerator
Head
Leaf
Definition at line 29 of file looptree.h.
Constructor & Destructor Documentation
Base()
template<bool forward> thorin::LoopTree< forward >::Base::Base (Node node, Head * parent, int depth, const std::vector< const CFNode * > & cf_nodes)
Definition at line 195 of file looptree.cpp.
References thorin::LoopTree< forward >::Base::parent_.
~Base()
template<bool forward> virtual thorin::LoopTree< forward >::Base::~Base () virtual default
Member Function Documentation
cf_nodes()
template<bool forward> ArrayRef< const CFNode * > thorin::LoopTree< forward >::Base::cf_nodes () const inline
Definition at line 37 of file looptree.h.
References thorin::LoopTree< forward >::Base::cf_nodes_.
Referenced by thorin::LoopTree< forward >::Leaf::cf_node(), and thorin::LoopTree< forward >::Base::num_cf_nodes().
depth()
template<bool forward> int thorin::LoopTree< forward >::Base::depth () const inline
Definition at line 35 of file looptree.h.
References thorin::LoopTree< forward >::Base::depth_.
node()
template<bool forward> Node thorin::LoopTree< forward >::Base::node () const inline
Definition at line 34 of file looptree.h.
References thorin::LoopTree< forward >::Base::node_.
num_cf_nodes()
template<bool forward> size_t thorin::LoopTree< forward >::Base::num_cf_nodes () const inline
Definition at line 38 of file looptree.h.
References thorin::LoopTree< forward >::Base::cf_nodes().
parent()
template<bool forward> const Head * thorin::LoopTree< forward >::Base::parent () const inline
Definition at line 36 of file looptree.h.
References thorin::LoopTree< forward >::Base::parent_.
Member Data Documentation
cf_nodes_
template<bool forward> std::vector<const CFNode*> thorin::LoopTree< forward >::Base::cf_nodes_ protected
Definition at line 43 of file looptree.h.
Referenced by thorin::LoopTree< forward >::Base::cf_nodes().
depth_
template<bool forward> int thorin::LoopTree< forward >::Base::depth_ protected
Definition at line 44 of file looptree.h.
Referenced by thorin::LoopTree< forward >::Base::depth().
node_
template<bool forward> Node thorin::LoopTree< forward >::Base::node_ protected
Definition at line 41 of file looptree.h.
Referenced by thorin::LoopTree< forward >::Base::node().
parent_
template<bool forward> Head* thorin::LoopTree< forward >::Base::parent_ protected
Definition at line 42 of file looptree.h.
Referenced by thorin::LoopTree< forward >::Base::Base(), thorin::LoopTree< forward >::Head::is_root(), and thorin::LoopTree< forward >::Base::parent().
The documentation for this class was generated from the following files:
/home/runner/work/thorin2/thorin2/thorin/analyses/looptree.h
/home/runner/work/thorin2/thorin2/thorin/analyses/looptree.cpp