MimIR: mim::PooledSet< T > Class Template Reference
mim::PooledSet< T > Class Template Reference
Ordered set maintained in a consecutive buffer and unified in Pool.
#include <mim/util/pool.h>
Classes
struct Data
Public Member Functions
Getters
constexpr operator bool () const noexcept
Is not empty?
constexpr bool empty () const noexcept
constexpr size_t size () const noexcept
constexpr const T & operator[] (size_t i) const
constexpr const T & front () const
constexpr const T * elems () const
constexpr bool contains (const T &elem) const
bool has_intersection (PooledSet< T > other)
Is ?
Comparisons
constexpr bool operator== (PooledSet< T > other) const noexcept
constexpr bool operator!= (PooledSet< T > other) const noexcept
Iterators
constexpr auto begin () const noexcept
constexpr auto end () const noexcept
constexpr auto cbegin () const noexcept
constexpr auto cend () const noexcept
constexpr auto rbegin () const noexcept
constexpr auto rend () const noexcept
constexpr auto crbegin () const noexcept
constexpr auto crend () const noexcept
Friends
class Pool< T >
template<class H >
H AbslHashValue (H h, PooledSet< T > set)
Construction & Destruction
constexpr PooledSet () noexcept=default
constexpr PooledSet (const PooledSet &) noexcept=default
constexpr PooledSet & operator= (const PooledSet &) noexcept=default
constexpr void clear () noexcept
Detailed Description
template<class T>
class mim::PooledSet< T >
Ordered set maintained in a consecutive buffer and unified in Pool.
Definition at line 22 of file pool.h.
Constructor & Destructor Documentation
PooledSet() [1/2]
template<class T > mim::PooledSet< T >::PooledSet () constexpr default noexcept
PooledSet() [2/2]
template<class T > mim::PooledSet< T >::PooledSet (const PooledSet< T > &) constexpr default noexcept
Member Function Documentation
begin()
template<class T > auto mim::PooledSet< T >::begin () const inline constexpr noexcept
Definition at line 97 of file pool.h.
References mim::PooledSet< T >::elems().
Referenced by mim::PooledSet< T >::contains(), mim::PooledSet< T >::has_intersection(), mim::Pool< T >::intersect(), mim::Pool< T >::merge(), and mim::PooledSet< T >::rend().
cbegin()
template<class T > auto mim::PooledSet< T >::cbegin () const inline constexpr noexcept
Definition at line 99 of file pool.h.
References mim::PooledSet< T >::elems().
cend()
template<class T > auto mim::PooledSet< T >::cend () const inline constexpr noexcept
Definition at line 100 of file pool.h.
References mim::PooledSet< T >::end().
clear()
template<class T > void mim::PooledSet< T >::clear () inline constexpr noexcept
Definition at line 58 of file pool.h.
contains()
template<class T > bool mim::PooledSet< T >::contains (const T & elem) const inline constexpr
Definition at line 69 of file pool.h.
References mim::PooledSet< T >::begin(), mim::binary_find(), and mim::PooledSet< T >::end().
Referenced by mim::Def::is_immutabilizable().
crbegin()
template<class T > auto mim::PooledSet< T >::crbegin () const inline constexpr noexcept
Definition at line 103 of file pool.h.
References mim::PooledSet< T >::rbegin().
crend()
template<class T > auto mim::PooledSet< T >::crend () const inline constexpr noexcept
Definition at line 104 of file pool.h.
References mim::PooledSet< T >::rend().
elems()
template<class T > const T * mim::PooledSet< T >::elems () const inline constexpr
Definition at line 68 of file pool.h.
References mim::PooledSet< T >::Data::elems.
Referenced by mim::PooledSet< T >::begin(), mim::PooledSet< T >::cbegin(), and mim::PooledSet< T >::end().
empty()
template<class T > bool mim::PooledSet< T >::empty () const inline constexpr noexcept
Definition at line 64 of file pool.h.
Referenced by mim::Def::is_closed(), mim::Def::is_open(), mim::VarRewriter::rewrite_imm(), and mim::PooledSet< T >::size().
end()
template<class T > auto mim::PooledSet< T >::end () const inline constexpr noexcept
Definition at line 98 of file pool.h.
References mim::PooledSet< T >::elems(), and mim::PooledSet< T >::size().
Referenced by mim::PooledSet< T >::cend(), mim::PooledSet< T >::contains(), mim::PooledSet< T >::has_intersection(), mim::Pool< T >::intersect(), mim::Pool< T >::merge(), and mim::PooledSet< T >::rbegin().
front()
template<class T > const T & mim::PooledSet< T >::front () const inline constexpr
Definition at line 67 of file pool.h.
has_intersection()
template<class T > bool mim::PooledSet< T >::has_intersection (PooledSet< T > other) inline nodiscard
Is ?
Definition at line 72 of file pool.h.
References mim::PooledSet< T >::begin(), and mim::PooledSet< T >::end().
Referenced by mim::Nest::contains(), mim::plug::clos::ClosConvPrep::from_outer_scope(), mim::VarRewriter::rewrite_imm(), and mim::VarRewriter::rewrite_mut().
operator bool()
template<class T > mim::PooledSet< T >::operator bool () const inline explicit constexpr noexcept
Is not empty?
Definition at line 63 of file pool.h.
operator!=()
template<class T > bool mim::PooledSet< T >::operator!= (PooledSet< T > other) const inline constexpr noexcept
Definition at line 92 of file pool.h.
operator=()
template<class T > PooledSet & mim::PooledSet< T >::operator= (const PooledSet< T > &) constexpr default noexcept
operator==()
template<class T > bool mim::PooledSet< T >::operator== (PooledSet< T > other) const inline constexpr noexcept
Definition at line 91 of file pool.h.
operator[]()
template<class T > const T & mim::PooledSet< T >::operator[] (size_t i) const inline constexpr
Definition at line 66 of file pool.h.
References mim::PooledSet< T >::Data::elems.
rbegin()
template<class T > auto mim::PooledSet< T >::rbegin () const inline constexpr noexcept
Definition at line 101 of file pool.h.
References mim::PooledSet< T >::end().
Referenced by mim::PooledSet< T >::crbegin().
rend()
template<class T > auto mim::PooledSet< T >::rend () const inline constexpr noexcept
Definition at line 102 of file pool.h.
References mim::PooledSet< T >::begin().
Referenced by mim::PooledSet< T >::crend().
size()
template<class T > size_t mim::PooledSet< T >::size () const inline constexpr noexcept
Definition at line 65 of file pool.h.
References mim::PooledSet< T >::empty(), and mim::PooledSet< T >::Data::size.
Referenced by mim::PooledSet< T >::end(), mim::Pool< T >::intersect(), and mim::Pool< T >::merge().
Friends And Related Symbol Documentation
AbslHashValue
template<class T > template<class H > H AbslHashValue (H h, PooledSet< T > set) friend
Definition at line 110 of file pool.h.
Pool< T >
template<class T > friend class Pool< T > friend
Definition at line 110 of file pool.h.
The documentation for this class was generated from the following file:
include/mim/util/pool.h