Thorin: thorin::Lexer Class Reference
thorin::Lexer Class Reference
#include </home/runner/work/thorin2/thorin2/thorin/fe/lexer.h>
Public Member Functions
Lexer (World &world, std::string_view file, std::istream &istream, std::ostream *md=nullptr)
Creates a lexer to read Thorin files (see Lexical Structure).
World & world ()
std::string_view file () const
Loc loc () const
Tok lex ()
Public Member Functions inherited from thorin::utf8::Lexer< 3 >
Lexer (std::string_view filename, std::istream &istream)
virtual ~Lexer ()
Additional Inherited Members
Protected Member Functions inherited from thorin::utf8::Lexer< 3 >
Ahead ahead (size_t i=0) const
virtual Ahead next ()
bool accept_if (Pred pred, bool append=true)
bool accept (char32_t val, bool append=true)
Protected Attributes inherited from thorin::utf8::Lexer< 3 >
std::istream & istream_
Loc loc_
std::string str_
std::array< Ahead, Max_Ahead > ahead_
Detailed Description
Definition at line 16 of file lexer.h.
Constructor & Destructor Documentation
Lexer()
thorin::Lexer::Lexer (World & world, std::string_view file, std::istream & istream, std::ostream * md = nullptr)
Creates a lexer to read Thorin files (see Lexical Structure).
If ostream is not nullptr, a Markdown output will be generated.
Definition at line 12 of file lexer.cpp.
References CODE, THORIN_KEY, and THORIN_SUBST.
Member Function Documentation
file()
std::string_view thorin::Lexer::file () const inline
Definition at line 25 of file lexer.h.
References thorin::Loc::file, and thorin::utf8::Lexer< 3 >::loc_.
lex()
Tok thorin::Lexer::lex ()
Definition at line 31 of file lexer.cpp.
References thorin::utf8::Lexer< 3 >::accept(), thorin::utf8::Lexer< 3 >::accept_if(), thorin::utf8::Lexer< 3 >::ahead(), thorin::Loc::begin, thorin::Tok::D_angle_l, thorin::Tok::D_angle_r, thorin::Tok::D_brace_l, thorin::Tok::D_brace_r, thorin::Tok::D_bracket_l, thorin::Tok::D_bracket_r, thorin::Tok::D_paren_l, thorin::Tok::D_paren_r, thorin::Tok::D_quote_l, thorin::Tok::D_quote_r, thorin::World::dbg(), thorin::utf8::EoF, thorin::utf8::Err, thorin::Loc::file, thorin::issign(), loc(), thorin::utf8::Lexer< 3 >::loc_, thorin::Tok::M_ax, thorin::Tok::M_eof, thorin::Tok::M_id, thorin::utf8::Lexer< 3 >::str_, thorin::World::sym(), thorin::Tok::T_arrow, thorin::Tok::T_assign, thorin::Tok::T_at, thorin::Tok::T_bot, thorin::Tok::T_box, thorin::Tok::T_colon, thorin::Tok::T_colon_colon, thorin::Tok::T_comma, thorin::Tok::T_dot, thorin::Tok::T_extract, thorin::Tok::T_lam, thorin::Tok::T_Pi, thorin::Tok::T_semicolon, thorin::Tok::T_star, and thorin::Tok::T_top.
loc()
Loc thorin::Lexer::loc () const inline
Definition at line 26 of file lexer.h.
References thorin::utf8::Lexer< 3 >::loc_.
Referenced by lex().
world()
World & thorin::Lexer::world () inline
Definition at line 24 of file lexer.h.
Referenced by thorin::Parser::world().
The documentation for this class was generated from the following files:
/home/runner/work/thorin2/thorin2/thorin/fe/lexer.h
/home/runner/work/thorin2/thorin2/thorin/fe/lexer.cpp