Thorin: thorin::Sym Class Reference
thorin::Sym Class Reference
#include <thorin/debug.h>
Public Member Functions
Sym ()
Sym (const Def *str, const Def *loc)
const Def * str () const
const Def * loc () const
std::string to_string () const
Loc to_loc () const
bool is_anonymous () const
operator std::string () const
operator Loc () const
operator bool () const
Detailed Description
Definition at line 53 of file debug.h.
Constructor & Destructor Documentation
Sym() [1/2]
thorin::Sym::Sym () inline
Definition at line 55 of file debug.h.
Sym() [2/2]
thorin::Sym::Sym (const Def * str, const Def * loc) inline
Definition at line 56 of file debug.h.
Member Function Documentation
is_anonymous()
bool thorin::Sym::is_anonymous () const
Definition at line 52 of file debug.cpp.
References thorin::isa_lit(), and str().
Referenced by thorin::fe::Scopes::bind(), thorin::fe::Scopes::find(), and thorin::fe::Ptrn::is_anonymous().
loc()
const Def * thorin::Sym::loc () const inline
Definition at line 61 of file debug.h.
Referenced by thorin::fe::Scopes::bind(), and thorin::fe::Scopes::find().
operator bool()
thorin::Sym::operator bool () const inline
Definition at line 69 of file debug.h.
operator Loc()
thorin::Sym::operator Loc () const inline
Definition at line 68 of file debug.h.
operator std::string()
thorin::Sym::operator std::string () const inline
Definition at line 67 of file debug.h.
References to_string().
str()
const Def * thorin::Sym::str () const inline
Definition at line 60 of file debug.h.
Referenced by is_anonymous(), thorin::SymHash::operator()(), thorin::operator==(), to_string(), and thorin::fe::TuplePtrn::type().
to_loc()
Loc thorin::Sym::to_loc () const inline
Definition at line 64 of file debug.h.
to_string()
std::string thorin::Sym::to_string () const
Definition at line 50 of file debug.cpp.
References str(), and thorin::tuple2str().
Referenced by operator std::string(), and thorin::operator<<().
The documentation for this class was generated from the following files:
thorin/debug.h
thorin/debug.cpp