Thorin: thorin::Axiom Class Reference
thorin::Axiom Class Reference
#include <thorin/axiom.h>
Classes
struct Match
Type of Match::def_.
struct Match< affine::lower_for_pass >
struct Match< autodiff::ad_eval_pass >
struct Match< autodiff::ad_ext_cleanup_pass >
struct Match< autodiff::ad_zero_cleanup_pass >
struct Match< autodiff::ad_zero_pass >
struct Match< clos::branch_clos_pass >
struct Match< clos::clos2sjlj_pass >
struct Match< clos::clos_conv_pass >
struct Match< clos::clos_conv_prep_pass >
struct Match< clos::lower_typed_clos_pass >
struct Match< clos::lower_typed_clos_prep_pass >
struct Match< compile::affine_dialect >
struct Match< compile::autodiff_dialect >
struct Match< compile::beta_red_pass >
struct Match< compile::clos_dialect >
struct Match< compile::core_dialect >
struct Match< compile::demo_dialect >
struct Match< compile::Dialect >
struct Match< compile::direct_dialect >
struct Match< compile::eta_red_pass >
struct Match< compile::internal_cleanup_pass >
struct Match< compile::lam_spec_pass >
struct Match< compile::mem_dialect >
struct Match< compile::nullptr_pass >
struct Match< compile::partial_eval_pass >
struct Match< compile::Pass >
struct Match< compile::Phase >
struct Match< compile::refly_dialect >
struct Match< compile::ret_wrap_pass >
struct Match< direct::cps2ds_pass >
struct Match< direct::ds2cps_pass >
struct Match< mem::add_mem_pass >
struct Match< mem::alloc2malloc_pass >
struct Match< mem::M >
struct Match< mem::remem_elim_pass >
struct Match< mem::reshape_arg >
struct Match< mem::reshape_flat >
struct Match< mem::reshape_mode >
struct Match< refly::Code >
struct Match< refly::remove_dbg_perm_pass >
Public Member Functions
template<bool Ow = false>
const Axiom * set (Loc l) const
template<bool Ow = false>
Axiom * set (Loc l)
template<bool Ow = false>
const Axiom * set (Sym s) const
template<bool Ow = false>
Axiom * set (Sym s)
template<bool Ow = false>
const Axiom * set (std::string s) const
template<bool Ow = false>
Axiom * set (std::string s)
template<bool Ow = false>
const Axiom * set (Loc l, Sym s) const
template<bool Ow = false>
Axiom * set (Loc l, Sym s)
template<bool Ow = false>
const Axiom * set (Loc l, std::string s) const
template<bool Ow = false>
Axiom * set (Loc l, std::string s)
template<bool Ow = false>
const Axiom * set (Dbg d) const
template<bool Ow = false>
Axiom * set (Dbg d)
Axiom * stub (World &w, const Def *type)
Axiom name
Anatomy of an Axiom name:
%dialect.tag.sub
|  48   | 8 | 8 | <-- Number of bits per field.
Def::name() retrieves the full name as Sym.
Def::flags() retrieves the full name as Axiom::mangled 64-bit integer.
dialect_t dialect () const
Yields the dialect part of the name as integer.
tag_t tag () const
Yields the tag part of the name as integer.
sub_t sub () const
Yields the sub part of the name as integer.
flags_t base () const
Includes Axiom::dialect() and Axiom::tag() but not Axiom::sub.
Public Member Functions inherited from thorin::Def
World & world () const
flags_t flags () const
u32 gid () const
hash_t hash () const
node_t node () const
std::string_view node_name () const
const Def * type () const
Yields the raw type of this Def; maybe nullptr.
const Def * unfold_type () const
Yields the type of this Def and unfolds it if necessary. See Def::type, Def::reduce_rec.
const Def * arity () const
std::optional< nat_t > isa_lit_arity () const
nat_t as_lit_arity () const
bool is_term () const
template<size_t N = -1_s>
auto ops () const
const Def * op (size_t i) const
size_t num_ops () const
Def * set (size_t i, const Def *def)
Def * set (Defs ops)
void unset (size_t i)
void unset ()
Def * set_type (const Def *)
void unset_type ()
void update ()
Resolves Infers of this Def's type.
bool is_set () const
Yields true if empty or the last op is set.
Defs extended_ops () const
const Def * extended_op (size_t i) const
size_t num_extended_ops () const
Defs partial_ops () const
const Def * partial_op (size_t i) const
size_t num_partial_ops () const
const Uses & uses () const
Array< Use > copy_uses () const
size_t num_uses () const
unsigned dep () const
bool has_dep (Dep d) const
bool has_dep (unsigned u) const
bool dep_const () const
nat_t num_projs () const
Yields Def::arity as_lit, if it is in fact a Lit, or 1 otherwise.
const Def * proj (nat_t a, nat_t i) const
Similar to World::extract while assuming an arity of a but also works on Sigmas, and Arrays.
const Def * proj (nat_t i) const
Same as above but takes Def::num_projs as arity.
template<nat_t A = -1_s, class F >
auto projs (F f) const
Splits this Def via Def::projections into an Array (if A == -1_s) or std::array (otherwise).
template<class F >
auto projs (nat_t a, F f) const
template<nat_t A = -1_s>
auto projs () const
auto projs (nat_t a) const
bool is_external () const
bool is_internal () const
Not Def::is_external.
void make_external ()
void make_internal ()
std::string unique_name () const
name + "_" + Def::gid
template<bool Ow = false>
const Def * set (Loc l) const
template<bool Ow = false>
Def * set (Loc l)
template<bool Ow = false>
const Def * set (Sym s) const
template<bool Ow = false>
Def * set (Sym s)
template<bool Ow = false>
const Def * set (std::string s) const
template<bool Ow = false>
Def * set (std::string s)
template<bool Ow = false>
const Def * set (Loc l, Sym s) const
template<bool Ow = false>
Def * set (Loc l, Sym s)
template<bool Ow = false>
const Def * set (Loc l, std::string s) const
template<bool Ow = false>
Def * set (Loc l, std::string s)
template<bool Ow = false>
const Def * set (Dbg d) const
template<bool Ow = false>
Def * set (Dbg d)
Dbg dbg () const
Loc loc () const
Sym sym () const
const Def * debug_prefix (std::string) const
const Def * debug_suffix (std::string) const
template<class T = Def>
const T * isa_structural () const
template<class T = Def>
const T * as_structural () const
template<class T = Def, bool invert = false>
T * isa_nom () const
If this is *nom*inal, it will cast constness away and perform a dynamic cast to T.
template<class T = Def, bool invert = false>
T * as_nom () const
Asserts that this is a *nom*inal, casts constness away and performs a static cast to T (checked in Debug build).
const Var * var ()
nat_t num_vars ()
Ref var (nat_t a, nat_t i)
Ref var (nat_t i)
template<nat_t A = -1_s, class F >
auto vars (F f)
template<nat_t A = -1_s>
auto vars ()
template<class F >
auto vars (nat_t a, F f)
auto vars (nat_t a)
DefArray reduce (const Def *arg) const
DefArray reduce (const Def *arg)
const Def * reduce_rec () const
Transitively Def::reduce Lams, if this is an App.
Def * stub (World &w, Ref type)
Ref rebuild (World &w, Ref type, Defs ops) const
Def::rebuilds this Def while using new_op as substitute for its i'th Def::op.
virtual void check ()
virtual size_t first_dependend_op ()
const Def * refine (size_t i, const Def *new_op) const
virtual const Def * restructure ()
void dump () const
void dump (int max) const
void write (int max) const
void write (int max, const char *file) const
std::ostream & stream (std::ostream &, int max) const
Public Member Functions inherited from thorin::RuntimeCast< Def >
T * as ()
static_cast with debug check.
const T * as () const
const version.
T * isa ()
dynamic_cast.
Def * isa ()
Yields B* if it is either T or U and `nullptr* otherwise.
const T * isa () const
const version.
const Def * isa () const
const version.
Static Public Member Functions
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
template<>
constexpr flags_t Base
template<>
constexpr size_t Num
Static Public Attributes
static constexpr auto Node = Node:: Axiom
Helpers for Matching
These are set via template specialization.
template<class Id >
static constexpr size_t Num = size_t(-1)
Number of Axiom::subtags.
template<class Id >
static constexpr flags_t Base = flags_t(-1)
Friends
class World
normalization
For a curried App of an Axiom, you only want to trigger normalization at specific spots.
For this reason, Thorin maintains a Def::curry_ counter that each App decrements. The Axiom::normalizer() will be triggered when Axiom::curry() becomes 0. These are also the spots that you can thorin::match/thorinforce/Match. After that, the counter will be set to Axiom::trip(). E.g., let's say an Axiom has this type:
A -> B -> C -> D -> E
          ^         |
          |         |
          +---------+
Using an initial value as 5 for Axiom::curry and 3 as Axiom::trip has the effect that here
x a b c1 d1 e1 c2 d2 e2 c3 d3 e3
the Axiom::normalizer will be triggered after App'ing e1, e2, and e3.
static constexpr u8 Trip_End = u8(-1)
NormalizeFn normalizer () const
u8 curry () const
u8 trip () const
static std::tuple< const Axiom *, u8, u8 > get (const Def *def)
Yields currying counter of def.
static std::pair< u8, u8 > infer_curry_and_trip (const Def *type)
Mangling Dialect Name
static constexpr size_t Max_Dialect_Size = 8
static constexpr dialect_t Global_Dialect = 0xffff'ffff'ffff'0000_u64
static std::optional< dialect_t > mangle (Sym s)
Mangles s into a dense 48-bit representation.
static Sym demangle (World &, dialect_t u)
Reverts an Axiom::mangled string to a Sym.
static std::array< Sym, 3 > split (World &, Sym)
Additional Inherited Members
Public Types inherited from thorin::Def
using NormalizeFn = Ref(*)(Ref, Ref, Ref)
Protected Member Functions inherited from thorin::Def
Def (World *, node_t, const Def *type, Defs ops, flags_t flags)
Constructor for a structural Def.
Def (node_t n, const Def *type, Defs ops, flags_t flags)
Def (node_t, const Def *type, size_t num_ops, flags_t flags)
Constructor for a *nom*inal Def.
virtual ~Def ()=default
virtual Ref rebuild_ (World &, Ref, Defs) const =0
virtual Def * stub_ (World &, Ref)
const Def ** ops_ptr () const
void finalize ()
bool equal (const Def *other) const
Sym get_sym (const char *) const
Sym get_sym (std::string_view) const
Sym get_sym (std::string) const
Protected Attributes inherited from thorin::Def
union {
NormalizeFn normalizer_
Axioms use this member to store their normalizer.
const Axiom * axiom_
World * world_
Curried Apps of Axioms use this member to propagate the Axiom.
};
flags_t flags_
uint8_t node_
unsigned nom_: 1
unsigned external_: 1
unsigned dep_: 5
unsigned pading_: 1
u8 curry_
u8 trip_
hash_t hash_
u32 gid_
u32 num_ops_
Uses uses_
Dbg dbg_
const Def * type_
Detailed Description
Definition at line 9 of file axiom.h.
Class Documentation
thorin::Axiom::Match
struct thorin::Axiom::Match
template<class T>
struct thorin::Axiom::Match< T >
Type of Match::def_.
Definition at line 115 of file axiom.h.
Class Members
typedef App type
thorin::Axiom::Match< affine::lower_for_pass >
struct thorin::Axiom::Match< affine::lower_for_pass >
Definition at line 32 of file autogen.h.
Class Members
typedef Axiom type
thorin::Axiom::Match< autodiff::ad_eval_pass >
struct thorin::Axiom::Match< autodiff::ad_eval_pass >
Definition at line 130 of file autogen.h.
Class Members
typedef Axiom type
thorin::Axiom::Match< autodiff::ad_ext_cleanup_pass >
struct thorin::Axiom::Match< autodiff::ad_ext_cleanup_pass >
Definition at line 127 of file autogen.h.
Class Members
typedef Axiom type
thorin::Axiom::Match< autodiff::ad_zero_cleanup_pass >
struct thorin::Axiom::Match< autodiff::ad_zero_cleanup_pass >
Definition at line 129 of file autogen.h.
Class Members
typedef Axiom type
thorin::Axiom::Match< autodiff::ad_zero_pass >
struct thorin::Axiom::Match< autodiff::ad_zero_pass >
Definition at line 128 of file autogen.h.
Class Members
typedef Axiom type
thorin::Axiom::Match< clos::branch_clos_pass >
struct thorin::Axiom::Match< clos::branch_clos_pass >
Definition at line 142 of file autogen.h.
Class Members
typedef Axiom type
thorin::Axiom::Match< clos::clos2sjlj_pass >
struct thorin::Axiom::Match< clos::clos2sjlj_pass >
Definition at line 140 of file autogen.h.
Class Members
typedef Axiom type
thorin::Axiom::Match< clos::clos_conv_pass >
struct thorin::Axiom::Match< clos::clos_conv_pass >
Definition at line 138 of file autogen.h.
Class Members
typedef Axiom type
thorin::Axiom::Match< clos::clos_conv_prep_pass >
struct thorin::Axiom::Match< clos::clos_conv_prep_pass >
Definition at line 137 of file autogen.h.
Class Members
typedef Axiom type
thorin::Axiom::Match< clos::lower_typed_clos_pass >
struct thorin::Axiom::Match< clos::lower_typed_clos_pass >
Definition at line 141 of file autogen.h.
Class Members
typedef Axiom type
thorin::Axiom::Match< clos::lower_typed_clos_prep_pass >
struct thorin::Axiom::Match< clos::lower_typed_clos_prep_pass >
Definition at line 139 of file autogen.h.
Class Members
typedef Axiom type
thorin::Axiom::Match< compile::affine_dialect >
struct thorin::Axiom::Match< compile::affine_dialect >
Definition at line 322 of file autogen.h.
Class Members
typedef Axiom type
thorin::Axiom::Match< compile::autodiff_dialect >
struct thorin::Axiom::Match< compile::autodiff_dialect >
Definition at line 319 of file autogen.h.
Class Members
typedef Axiom type
thorin::Axiom::Match< compile::beta_red_pass >
struct thorin::Axiom::Match< compile::beta_red_pass >
Definition at line 331 of file autogen.h.
Class Members
typedef Axiom type
thorin::Axiom::Match< compile::clos_dialect >
struct thorin::Axiom::Match< compile::clos_dialect >
Definition at line 335 of file autogen.h.
Class Members
typedef Axiom type
thorin::Axiom::Match< compile::core_dialect >
struct thorin::Axiom::Match< compile::core_dialect >
Definition at line 323 of file autogen.h.
Class Members
typedef Axiom type
thorin::Axiom::Match< compile::demo_dialect >
struct thorin::Axiom::Match< compile::demo_dialect >
Definition at line 324 of file autogen.h.
Class Members
typedef Axiom type
thorin::Axiom::Match< compile::Dialect >
struct thorin::Axiom::Match< compile::Dialect >
Definition at line 321 of file autogen.h.
Class Members
typedef Axiom type
thorin::Axiom::Match< compile::direct_dialect >
struct thorin::Axiom::Match< compile::direct_dialect >
Definition at line 326 of file autogen.h.
Class Members
typedef Axiom type
thorin::Axiom::Match< compile::eta_red_pass >
struct thorin::Axiom::Match< compile::eta_red_pass >
Definition at line 332 of file autogen.h.
Class Members
typedef Axiom type
thorin::Axiom::Match< compile::internal_cleanup_pass >
struct thorin::Axiom::Match< compile::internal_cleanup_pass >
Definition at line 328 of file autogen.h.
Class Members
typedef Axiom type
thorin::Axiom::Match< compile::lam_spec_pass >
struct thorin::Axiom::Match< compile::lam_spec_pass >
Definition at line 330 of file autogen.h.
Class Members
typedef Axiom type
thorin::Axiom::Match< compile::mem_dialect >
struct thorin::Axiom::Match< compile::mem_dialect >
Definition at line 327 of file autogen.h.
Class Members
typedef Axiom type
thorin::Axiom::Match< compile::nullptr_pass >
struct thorin::Axiom::Match< compile::nullptr_pass >
Definition at line 320 of file autogen.h.
Class Members
typedef Axiom type
thorin::Axiom::Match< compile::partial_eval_pass >
struct thorin::Axiom::Match< compile::partial_eval_pass >
Definition at line 325 of file autogen.h.
Class Members
typedef Axiom type
thorin::Axiom::Match< compile::Pass >
struct thorin::Axiom::Match< compile::Pass >
Definition at line 333 of file autogen.h.
Class Members
typedef Axiom type
thorin::Axiom::Match< compile::Phase >
struct thorin::Axiom::Match< compile::Phase >
Definition at line 329 of file autogen.h.
Class Members
typedef Axiom type
thorin::Axiom::Match< compile::refly_dialect >
struct thorin::Axiom::Match< compile::refly_dialect >
Definition at line 334 of file autogen.h.
Class Members
typedef Axiom type
thorin::Axiom::Match< compile::ret_wrap_pass >
struct thorin::Axiom::Match< compile::ret_wrap_pass >
Definition at line 336 of file autogen.h.
Class Members
typedef Axiom type
thorin::Axiom::Match< direct::cps2ds_pass >
struct thorin::Axiom::Match< direct::cps2ds_pass >
Definition at line 58 of file autogen.h.
Class Members
typedef Axiom type
thorin::Axiom::Match< direct::ds2cps_pass >
struct thorin::Axiom::Match< direct::ds2cps_pass >
Definition at line 59 of file autogen.h.
Class Members
typedef Axiom type
thorin::Axiom::Match< mem::add_mem_pass >
struct thorin::Axiom::Match< mem::add_mem_pass >
Definition at line 217 of file autogen.h.
Class Members
typedef Axiom type
thorin::Axiom::Match< mem::alloc2malloc_pass >
struct thorin::Axiom::Match< mem::alloc2malloc_pass >
Definition at line 216 of file autogen.h.
Class Members
typedef Axiom type
thorin::Axiom::Match< mem::M >
struct thorin::Axiom::Match< mem::M >
Definition at line 214 of file autogen.h.
Class Members
typedef Axiom type
thorin::Axiom::Match< mem::remem_elim_pass >
struct thorin::Axiom::Match< mem::remem_elim_pass >
Definition at line 212 of file autogen.h.
Class Members
typedef Axiom type
thorin::Axiom::Match< mem::reshape_arg >
struct thorin::Axiom::Match< mem::reshape_arg >
Definition at line 213 of file autogen.h.
Class Members
typedef Axiom type
thorin::Axiom::Match< mem::reshape_flat >
struct thorin::Axiom::Match< mem::reshape_flat >
Definition at line 211 of file autogen.h.
Class Members
typedef Axiom type
thorin::Axiom::Match< mem::reshape_mode >
struct thorin::Axiom::Match< mem::reshape_mode >
Definition at line 215 of file autogen.h.
Class Members
typedef Axiom type
thorin::Axiom::Match< refly::Code >
struct thorin::Axiom::Match< refly::Code >
Definition at line 108 of file autogen.h.
Class Members
typedef Axiom type
thorin::Axiom::Match< refly::remove_dbg_perm_pass >
struct thorin::Axiom::Match< refly::remove_dbg_perm_pass >
Definition at line 107 of file autogen.h.
Class Members
typedef Axiom type
Member Function Documentation
Base() [1/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 27 of file autogen.h.
Base() [2/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 29 of file autogen.h.
Base() [3/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 106 of file autogen.h.
Base() [4/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 108 of file autogen.h.
Base() [5/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 110 of file autogen.h.
Base() [6/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 112 of file autogen.h.
Base() [7/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 114 of file autogen.h.
Base() [8/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 116 of file autogen.h.
Base() [9/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 118 of file autogen.h.
Base() [10/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 120 of file autogen.h.
Base() [11/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 122 of file autogen.h.
Base() [12/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 124 of file autogen.h.
Base() [13/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 114 of file autogen.h.
Base() [14/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 116 of file autogen.h.
Base() [15/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 118 of file autogen.h.
Base() [16/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 120 of file autogen.h.
Base() [17/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 122 of file autogen.h.
Base() [18/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 124 of file autogen.h.
Base() [19/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 126 of file autogen.h.
Base() [20/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 128 of file autogen.h.
Base() [21/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 130 of file autogen.h.
Base() [22/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 132 of file autogen.h.
Base() [23/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 134 of file autogen.h.
Base() [24/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 254 of file autogen.h.
Base() [25/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 256 of file autogen.h.
Base() [26/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 258 of file autogen.h.
Base() [27/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 260 of file autogen.h.
Base() [28/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 262 of file autogen.h.
Base() [29/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 264 of file autogen.h.
Base() [30/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 266 of file autogen.h.
Base() [31/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 268 of file autogen.h.
Base() [32/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 270 of file autogen.h.
Base() [33/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 272 of file autogen.h.
Base() [34/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 274 of file autogen.h.
Base() [35/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 276 of file autogen.h.
Base() [36/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 278 of file autogen.h.
Base() [37/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 280 of file autogen.h.
Base() [38/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 282 of file autogen.h.
Base() [39/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 284 of file autogen.h.
Base() [40/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 286 of file autogen.h.
Base() [41/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 288 of file autogen.h.
Base() [42/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 290 of file autogen.h.
Base() [43/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 292 of file autogen.h.
Base() [44/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 294 of file autogen.h.
Base() [45/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 296 of file autogen.h.
Base() [46/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 298 of file autogen.h.
Base() [47/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 300 of file autogen.h.
Base() [48/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 302 of file autogen.h.
Base() [49/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 304 of file autogen.h.
Base() [50/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 306 of file autogen.h.
Base() [51/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 308 of file autogen.h.
Base() [52/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 310 of file autogen.h.
Base() [53/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 312 of file autogen.h.
Base() [54/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 314 of file autogen.h.
Base() [55/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 316 of file autogen.h.
Base() [56/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 392 of file autogen.h.
Base() [57/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 394 of file autogen.h.
Base() [58/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 396 of file autogen.h.
Base() [59/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 398 of file autogen.h.
Base() [60/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 400 of file autogen.h.
Base() [61/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 402 of file autogen.h.
Base() [62/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 404 of file autogen.h.
Base() [63/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 406 of file autogen.h.
Base() [64/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 408 of file autogen.h.
Base() [65/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 410 of file autogen.h.
Base() [66/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 412 of file autogen.h.
Base() [67/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 414 of file autogen.h.
Base() [68/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 416 of file autogen.h.
Base() [69/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 28 of file autogen.h.
Base() [70/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 49 of file autogen.h.
Base() [71/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 51 of file autogen.h.
Base() [72/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 53 of file autogen.h.
Base() [73/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 55 of file autogen.h.
Base() [74/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 330 of file autogen.h.
Base() [75/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 332 of file autogen.h.
Base() [76/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 334 of file autogen.h.
Base() [77/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 336 of file autogen.h.
Base() [78/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 338 of file autogen.h.
Base() [79/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 340 of file autogen.h.
Base() [80/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 342 of file autogen.h.
Base() [81/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 344 of file autogen.h.
Base() [82/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 346 of file autogen.h.
Base() [83/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 348 of file autogen.h.
Base() [84/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 350 of file autogen.h.
Base() [85/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 170 of file autogen.h.
Base() [86/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 172 of file autogen.h.
Base() [87/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 174 of file autogen.h.
Base() [88/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 176 of file autogen.h.
Base() [89/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 178 of file autogen.h.
Base() [90/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 180 of file autogen.h.
Base() [91/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 182 of file autogen.h.
Base() [92/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 184 of file autogen.h.
Base() [93/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 186 of file autogen.h.
Base() [94/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 188 of file autogen.h.
Base() [95/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 190 of file autogen.h.
Base() [96/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 192 of file autogen.h.
Base() [97/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 194 of file autogen.h.
Base() [98/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 196 of file autogen.h.
Base() [99/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 198 of file autogen.h.
Base() [100/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 200 of file autogen.h.
Base() [101/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 202 of file autogen.h.
Base() [102/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 204 of file autogen.h.
Base() [103/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 206 of file autogen.h.
Base() [104/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 208 of file autogen.h.
Base() [105/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 92 of file autogen.h.
Base() [106/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 94 of file autogen.h.
Base() [107/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 96 of file autogen.h.
Base() [108/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 98 of file autogen.h.
Base() [109/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 100 of file autogen.h.
Base() [110/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 102 of file autogen.h.
Base() [111/111]
template<> constexpr flags_t thorin::Axiom::Base static constexpr
Definition at line 104 of file autogen.h.
base()
flags_t thorin::Axiom::base () const inline
Includes Axiom::dialect() and Axiom::tag() but not Axiom::sub.
Definition at line 66 of file axiom.h.
References thorin::Def::flags().
curry()
u8 thorin::Axiom::curry () const inline
Definition at line 34 of file axiom.h.
References thorin::Def::curry_.
demangle()
Sym thorin::Axiom::demangle (World & world, dialect_t u) static
Reverts an Axiom::mangled string to a Sym.
Ignores lower 16-bit of u.
Definition at line 75 of file axiom.cpp.
References thorin::World::sym().
Referenced by thorin::World::ax().
dialect()
dialect_t thorin::Axiom::dialect () const inline
Yields the dialect part of the name as integer.
It consists of 48 relevant bits that are returned in the highest 6 bytes of a 64-bit integer.
Definition at line 57 of file axiom.h.
References thorin::Def::flags(), and Global_Dialect.
Referenced by thorin::Match< Id, D >::dialect().
get()
std::tuple< const Axiom *, u8, u8 > thorin::Axiom::get (const Def * def) static
Yields currying counter of def.
Returns
{nullptr, 0, 0} if no Axiom is present.
Definition at line 40 of file axiom.cpp.
References thorin::RuntimeCast< B >::isa().
Referenced by thorin::match(), and thorin::World::raw_app().
infer_curry_and_trip()
std::pair< u8, u8 > thorin::Axiom::infer_curry_and_trip (const Def * type) static
Definition at line 16 of file axiom.cpp.
References thorin::RuntimeCast< B >::isa().
mangle()
std::optional< dialect_t > thorin::Axiom::mangle (Sym s) static
Mangles s into a dense 48-bit representation.
The layout is as follows:
|---7--||---6--||---5--||---4--||---3--||---2--||---1--||---0--|
7654321076543210765432107654321076543210765432107654321076543210
Char67Char66Char65Char64Char63Char62Char61Char60|---reserved---|
The reserved part is used for the Axiom::tag and the Axiom::sub. Each Char6x is 6-bit wide and hence a dialect name has at most Axiom::Max_Dialect_Size = 8 chars. It uses this encoding:
Char6 ASCII
1: _
2-27: a-z
28-53: A-Z
54-63: 0-9
The 0 is special and marks the end of the name if the name has less than 8 chars.
Returns
std::nullopt if encoding is not possible.
Definition at line 46 of file axiom.cpp.
Referenced by thorin::h::Bootstrapper::emit().
normalizer()
NormalizeFn thorin::Axiom::normalizer () const inline
Definition at line 33 of file axiom.h.
Referenced by thorin::World::raw_app().
Num() [1/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 28 of file autogen.h.
Num() [2/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 30 of file autogen.h.
Num() [3/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 107 of file autogen.h.
Num() [4/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 109 of file autogen.h.
Num() [5/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 111 of file autogen.h.
Num() [6/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 113 of file autogen.h.
Num() [7/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 115 of file autogen.h.
Num() [8/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 117 of file autogen.h.
Num() [9/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 119 of file autogen.h.
Num() [10/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 121 of file autogen.h.
Num() [11/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 123 of file autogen.h.
Num() [12/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 125 of file autogen.h.
Num() [13/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 115 of file autogen.h.
Num() [14/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 117 of file autogen.h.
Num() [15/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 119 of file autogen.h.
Num() [16/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 121 of file autogen.h.
Num() [17/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 123 of file autogen.h.
Num() [18/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 125 of file autogen.h.
Num() [19/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 127 of file autogen.h.
Num() [20/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 129 of file autogen.h.
Num() [21/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 131 of file autogen.h.
Num() [22/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 133 of file autogen.h.
Num() [23/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 135 of file autogen.h.
Num() [24/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 255 of file autogen.h.
Num() [25/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 257 of file autogen.h.
Num() [26/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 259 of file autogen.h.
Num() [27/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 261 of file autogen.h.
Num() [28/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 263 of file autogen.h.
Num() [29/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 265 of file autogen.h.
Num() [30/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 267 of file autogen.h.
Num() [31/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 269 of file autogen.h.
Num() [32/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 271 of file autogen.h.
Num() [33/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 273 of file autogen.h.
Num() [34/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 275 of file autogen.h.
Num() [35/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 277 of file autogen.h.
Num() [36/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 279 of file autogen.h.
Num() [37/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 281 of file autogen.h.
Num() [38/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 283 of file autogen.h.
Num() [39/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 285 of file autogen.h.
Num() [40/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 287 of file autogen.h.
Num() [41/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 289 of file autogen.h.
Num() [42/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 291 of file autogen.h.
Num() [43/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 293 of file autogen.h.
Num() [44/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 295 of file autogen.h.
Num() [45/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 297 of file autogen.h.
Num() [46/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 299 of file autogen.h.
Num() [47/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 301 of file autogen.h.
Num() [48/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 303 of file autogen.h.
Num() [49/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 305 of file autogen.h.
Num() [50/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 307 of file autogen.h.
Num() [51/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 309 of file autogen.h.
Num() [52/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 311 of file autogen.h.
Num() [53/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 313 of file autogen.h.
Num() [54/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 315 of file autogen.h.
Num() [55/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 317 of file autogen.h.
Num() [56/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 393 of file autogen.h.
Num() [57/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 395 of file autogen.h.
Num() [58/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 397 of file autogen.h.
Num() [59/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 399 of file autogen.h.
Num() [60/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 401 of file autogen.h.
Num() [61/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 403 of file autogen.h.
Num() [62/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 405 of file autogen.h.
Num() [63/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 407 of file autogen.h.
Num() [64/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 409 of file autogen.h.
Num() [65/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 411 of file autogen.h.
Num() [66/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 413 of file autogen.h.
Num() [67/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 415 of file autogen.h.
Num() [68/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 417 of file autogen.h.
Num() [69/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 29 of file autogen.h.
Num() [70/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 50 of file autogen.h.
Num() [71/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 52 of file autogen.h.
Num() [72/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 54 of file autogen.h.
Num() [73/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 56 of file autogen.h.
Num() [74/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 331 of file autogen.h.
Num() [75/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 333 of file autogen.h.
Num() [76/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 335 of file autogen.h.
Num() [77/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 337 of file autogen.h.
Num() [78/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 339 of file autogen.h.
Num() [79/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 341 of file autogen.h.
Num() [80/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 343 of file autogen.h.
Num() [81/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 345 of file autogen.h.
Num() [82/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 347 of file autogen.h.
Num() [83/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 349 of file autogen.h.
Num() [84/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 351 of file autogen.h.
Num() [85/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 171 of file autogen.h.
Num() [86/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 173 of file autogen.h.
Num() [87/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 175 of file autogen.h.
Num() [88/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 177 of file autogen.h.
Num() [89/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 179 of file autogen.h.
Num() [90/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 181 of file autogen.h.
Num() [91/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 183 of file autogen.h.
Num() [92/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 185 of file autogen.h.
Num() [93/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 187 of file autogen.h.
Num() [94/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 189 of file autogen.h.
Num() [95/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 191 of file autogen.h.
Num() [96/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 193 of file autogen.h.
Num() [97/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 195 of file autogen.h.
Num() [98/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 197 of file autogen.h.
Num() [99/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 199 of file autogen.h.
Num() [100/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 201 of file autogen.h.
Num() [101/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 203 of file autogen.h.
Num() [102/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 205 of file autogen.h.
Num() [103/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 207 of file autogen.h.
Num() [104/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 209 of file autogen.h.
Num() [105/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 93 of file autogen.h.
Num() [106/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 95 of file autogen.h.
Num() [107/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 97 of file autogen.h.
Num() [108/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 99 of file autogen.h.
Num() [109/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 101 of file autogen.h.
Num() [110/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 103 of file autogen.h.
Num() [111/111]
template<> constexpr size_t thorin::Axiom::Num static constexpr
Definition at line 105 of file autogen.h.
set() [1/12]
template<bool Ow = false> Axiom * thorin::Axiom::set (Dbg d) inline
Definition at line 120 of file axiom.h.
set() [2/12]
template<bool Ow = false> const Axiom * thorin::Axiom::set (Dbg d) const inline
Definition at line 120 of file axiom.h.
set() [3/12]
template<bool Ow = false> Axiom * thorin::Axiom::set (Loc l) inline
Definition at line 120 of file axiom.h.
set() [4/12]
template<bool Ow = false> const Axiom * thorin::Axiom::set (Loc l) const inline
Definition at line 120 of file axiom.h.
set() [5/12]
template<bool Ow = false> Axiom * thorin::Axiom::set (Loc l, std::string s) inline
Definition at line 120 of file axiom.h.
set() [6/12]
template<bool Ow = false> const Axiom * thorin::Axiom::set (Loc l, std::string s) const inline
Definition at line 120 of file axiom.h.
set() [7/12]
template<bool Ow = false> Axiom * thorin::Axiom::set (Loc l, Sym s) inline
Definition at line 120 of file axiom.h.
set() [8/12]
template<bool Ow = false> const Axiom * thorin::Axiom::set (Loc l, Sym s) const inline
Definition at line 120 of file axiom.h.
set() [9/12]
template<bool Ow = false> Axiom * thorin::Axiom::set (std::string s) inline
Definition at line 120 of file axiom.h.
set() [10/12]
template<bool Ow = false> const Axiom * thorin::Axiom::set (std::string s) const inline
Definition at line 120 of file axiom.h.
set() [11/12]
template<bool Ow = false> Axiom * thorin::Axiom::set (Sym s) inline
Definition at line 120 of file axiom.h.
set() [12/12]
template<bool Ow = false> const Axiom * thorin::Axiom::set (Sym s) const inline
Definition at line 120 of file axiom.h.
split()
std::array< Sym, 3 > thorin::Axiom::split (World & world, Sym s) static
Definition at line 97 of file axiom.cpp.
References thorin::subview(), and thorin::World::sym().
Referenced by thorin_get_dialect_info().
stub()
Axiom * thorin::Axiom::stub (World & w, const Def * type) inline
Definition at line 120 of file axiom.h.
sub()
sub_t thorin::Axiom::sub () const inline
Yields the sub part of the name as integer.
Definition at line 63 of file axiom.h.
References thorin::Def::flags().
Referenced by thorin::Match< Id, D >::base(), and thorin::Match< Id, D >::sub().
tag()
tag_t thorin::Axiom::tag () const inline
Yields the tag part of the name as integer.
Definition at line 60 of file axiom.h.
References thorin::Def::flags().
Referenced by thorin::Match< Id, D >::tag().
trip()
u8 thorin::Axiom::trip () const inline
Definition at line 35 of file axiom.h.
References thorin::Def::trip_.
Friends And Related Function Documentation
World
friend class World friend
Definition at line 120 of file axiom.h.
Member Data Documentation
Base
template<class Id > constexpr flags_t thorin::Axiom::Base = flags_t(-1) static constexpr
See also
Axiom::base.
Definition at line 111 of file axiom.h.
Global_Dialect
constexpr dialect_t thorin::Axiom::Global_Dialect = 0xffff'ffff'ffff'0000_u64 static constexpr
Definition at line 72 of file axiom.h.
Referenced by thorin::World::axiom(), and dialect().
Max_Dialect_Size
constexpr size_t thorin::Axiom::Max_Dialect_Size = 8 static constexpr
Definition at line 71 of file axiom.h.
Node
constexpr auto thorin::Axiom::Node = Node:: Axiom static constexpr
Definition at line 120 of file axiom.h.
Num
template<class Id > constexpr size_t thorin::Axiom::Num = size_t(-1) static constexpr
Number of Axiom::subtags.
Definition at line 107 of file axiom.h.
Trip_End
constexpr u8 thorin::Axiom::Trip_End = u8(-1) static constexpr
Definition at line 42 of file axiom.h.
Referenced by thorin::World::raw_app().
The documentation for this class was generated from the following files:
thorin/axiom.h
thorin/axiom.cpp
thorin/def.cpp
build/include/dialects/affine/autogen.h
build/include/dialects/autodiff/autogen.h
build/include/dialects/clos/autogen.h
build/include/dialects/compile/autogen.h
build/include/dialects/core/autogen.h
build/include/dialects/demo/autogen.h
build/include/dialects/direct/autogen.h
build/include/dialects/math/autogen.h
build/include/dialects/mem/autogen.h
build/include/dialects/refly/autogen.h