Thorin: thorin::ll::Emitter Class Reference
thorin::ll::Emitter Class Reference
Public Types
using Super = thorin::Emitter< std::string, std::string, BB, Emitter >
Public Member Functions
Emitter (World &world, std::ostream &ostream)
bool is_valid (std::string_view s)
void start () override
Actual entry.
void emit_imported (Lam *)
void emit_epilogue (Lam *)
std::string emit_bb (BB &, const Def *)
std::string prepare (const Scope &)
void prepare (Lam *, std::string_view)
void finalize (const Scope &)
template<class... Args>
void declare (const char *s, Args &&... args)
Public Member Functions inherited from thorin::ScopePhase
ScopePhase (World &world, std::string_view name, bool elide_empty)
void start () override
Actual entry.
virtual void visit (const Scope &)=0
Public Member Functions inherited from thorin::Phase
Phase (World &world, std::string_view name, bool dirty)
virtual ~Phase ()=default
World & world ()
std::string_view name () const
bool is_dirty () const
virtual void run ()
Entry point and generates some debug output; invokes Phase::start.
Additional Inherited Members
Static Public Member Functions inherited from thorin::Phase
template<class P , class... Args>
static void run (Args &&... args)
Runs a single Phase.
Public Attributes inherited from thorin::Emitter< std::string, std::string, BB, Emitter >
Tab tab
Protected Member Functions inherited from thorin::Emitter< std::string, std::string, BB, Emitter >
Emitter (World &world, std::string_view name, std::ostream &ostream)
std::ostream & ostream () const
std::string emit (const Def *def)
Recursively emits code.
std::string emit_unsafe (const Def *def)
As above but returning !child().is_valid(value) is permitted.
void visit (const Scope &scope) override
Protected Member Functions inherited from thorin::ScopePhase
const Scope & scope () const
virtual void start ()=0
Actual entry.
Protected Attributes inherited from thorin::Emitter< std::string, std::string, BB, Emitter >
std::ostream & ostream_
Scheduler scheduler_
DefMap< std::string > locals_
DefMap< std::string > globals_
DefMap< std::string > types_
LamMap< BB > lam2bb_
Lam * entry_
Protected Attributes inherited from thorin::Phase
World & world_
std::string name_
bool dirty_
Detailed Description
Definition at line 77 of file ll.cpp.
Member Typedef Documentation
Super
using thorin::ll::Emitter::Super = thorin::Emitter<std::string, std::string, BB, Emitter>
Definition at line 79 of file ll.cpp.
Constructor & Destructor Documentation
Emitter()
thorin::ll::Emitter::Emitter (World & world, std::ostream & ostream) inline
Definition at line 81 of file ll.cpp.
Member Function Documentation
declare()
template<class... Args> void thorin::ll::Emitter::declare (const char * s, Args &&... args) inline
Definition at line 94 of file ll.cpp.
References thorin::print().
Referenced by emit_bb(), and emit_epilogue().
emit_bb()
std::string thorin::ll::Emitter::emit_bb (BB & bb, const Def * def)
Definition at line 433 of file ll.cpp.
References thorin::core::a, thorin::math::a, thorin::core::add, thorin::math::add, thorin::math::afn, thorin::math::ahFF, thorin::core::and_, thorin::math::arcp, thorin::as_lit(), thorin::ll::BB::assign(), thorin::bitcast(), thorin::ll::BB::body(), thorin::math::contract, thorin::math::cos, declare(), thorin::math::div, thorin::Def::dump(), thorin::core::e, thorin::math::e, thorin::Emitter< std::string, std::string, BB, Emitter >::emit(), thorin::Emitter< std::string, std::string, BB, Emitter >::emit_unsafe(), thorin::Emitter< std::string, std::string, BB, Emitter >::entry_, thorin::err(), thorin::math::exp, thorin::math::exp2, thorin::math::f, thorin::math::f2f, thorin::math::f2s, thorin::math::f2u, thorin::math::fast, thorin::math::fmax, thorin::math::fmin, thorin::core::g, thorin::math::g, thorin::core::ge, thorin::math::ge, thorin::Emitter< std::string, std::string, BB, Emitter >::globals_, thorin::math::h, thorin::math::ieee754max, thorin::math::ieee754min, thorin::core::iff, thorin::ll::is_const(), thorin::RuntimeCast< B >::isa(), thorin::math::isa_f(), thorin::isa_lit(), thorin::core::l, thorin::Emitter< std::string, std::string, BB, Emitter >::lam2bb_, thorin::core::le, thorin::math::le, thorin::ll::llvm_suffix(), thorin::math::log, thorin::math::log2, thorin::ll::math_suffix(), thorin::core::mul, thorin::math::mul, thorin::Phase::name(), thorin::core::nand, thorin::core::ne, thorin::math::ne, thorin::core::neg, thorin::core::niff, thorin::math::ninf, thorin::math::nnan, thorin::core::nor, thorin::core::nsw, thorin::math::nsz, thorin::core::nuw, thorin::core::nxor, thorin::math::o, thorin::core::or_, thorin::print(), thorin::Def::proj(), thorin::math::reassoc, thorin::math::rem, thorin::core::s, thorin::math::s2f, thorin::core::sdiv, thorin::core::sg, thorin::core::sge, thorin::core::shl, thorin::math::sin, thorin::Idx::size(), thorin::Idx::size2bitwidth(), thorin::core::sl, thorin::core::sle, thorin::math::sq, thorin::core::srem, thorin::core::sub, thorin::math::sub, thorin::math::t, thorin::ll::BB::tail(), thorin::math::tan, thorin::Def::type(), thorin::core::u, thorin::math::u, thorin::math::u2f, thorin::core::udiv, thorin::math::ue, thorin::core::ug, thorin::math::ug, thorin::core::uge, thorin::math::uge, thorin::core::ul, thorin::math::ul, thorin::core::ule, thorin::math::ule, thorin::math::une, thorin::unreachable(), thorin::core::urem, thorin::Phase::world(), thorin::Def::world(), and thorin::core::xor_.
emit_epilogue()
void thorin::ll::Emitter::emit_epilogue (Lam * lam)
Definition at line 274 of file ll.cpp.
References thorin::App::args(), thorin::RuntimeCast< B >::as(), thorin::Def::as_nom(), thorin::Lam::body(), declare(), thorin::Emitter< std::string, std::string, BB, Emitter >::emit(), thorin::Emitter< std::string, std::string, BB, Emitter >::emit_unsafe(), thorin::Emitter< std::string, std::string, BB, Emitter >::entry_, thorin::Lam::is_basicblock(), thorin::Emitter< std::string, std::string, BB, Emitter >::lam2bb_, thorin::Emitter< std::string, std::string, BB, Emitter >::locals_, thorin::Phase::name(), thorin::Def::num_vars(), thorin::print(), thorin::Lam::ret_var(), thorin::Def::var(), and thorin::Phase::world().
emit_imported()
void thorin::ll::Emitter::emit_imported (Lam * lam)
Definition at line 213 of file ll.cpp.
References thorin::Lam::doms(), thorin::print(), thorin::Pi::ret_pi(), and thorin::Lam::type().
finalize()
void thorin::ll::Emitter::finalize (const Scope & scope)
Definition at line 245 of file ll.cpp.
References thorin::Scope::exit(), thorin::Emitter< std::string, std::string, BB, Emitter >::lam2bb_, thorin::print(), thorin::Tab::print(), thorin::schedule(), thorin::ScopePhase::scope(), and thorin::Emitter< std::string, std::string, BB, Emitter >::tab.
is_valid()
bool thorin::ll::Emitter::is_valid (std::string_view s) inline
Definition at line 84 of file ll.cpp.
prepare() [1/2]
std::string thorin::ll::Emitter::prepare (const Scope & scope)
Definition at line 227 of file ll.cpp.
References thorin::Def::as_nom(), thorin::Scope::entry(), thorin::Emitter< std::string, std::string, BB, Emitter >::locals_, thorin::Phase::name(), thorin::print(), and thorin::ScopePhase::scope().
prepare() [2/2]
void thorin::ll::Emitter::prepare (Lam * , std::string_view)
start()
void thorin::ll::Emitter::start () override virtual
Actual entry.
Implements thorin::Phase.
Definition at line 203 of file ll.cpp.
References thorin::Emitter< std::string, std::string, BB, Emitter >::ostream(), and thorin::Phase::start().
The documentation for this class was generated from the following file:
dialects/core/be/ll/ll.cpp