MimIR: mim::PrefixCleanup Class Reference
mim::PrefixCleanup Class Reference
#include <mim/phase/prefix_cleanup.h>
Public Member Functions
PrefixCleanup (World &world, flags_t annex)
void apply (std::string)
void apply (const App *app) final
Invoked if your Stage has additional args.
void apply (Stage &s) final
Dito, but invoked by Stage::recreate.
Public Member Functions inherited from mim::RWPhase
virtual bool analyze ()
You can do an optional fixed-point loop on the RWPhase::old_world before rewriting.
bool is_bootstrapping () const
RWPhase (World &world, std::string name)
RWPhase (World &world, flags_t annex)
virtual void rewrite_annex (flags_t, const Def *)
World & world ()=delete
Hides both and forbids direct access.
World & old_world ()
Get old Defs from here.
World & new_world ()
Create new Defs into this.
Public Member Functions inherited from mim::Phase
Phase (World &world, std::string name)
Phase (World &world, flags_t annex)
bool todo () const
virtual void run ()
Entry point and generates some debug output; invokes Phase::start.
Public Member Functions inherited from mim::Stage
World & world ()
Driver & driver ()
Log & log () const
std::string_view name () const
flags_t annex () const
Stage (World &world, std::string name)
Stage (World &world, flags_t annex)
virtual ~Stage ()=default
virtual std::unique_ptr< Stage > recreate ()
Creates a new instance; needed by a fixed-point PhaseMan.
Public Member Functions inherited from mim::Rewriter
Rewriter (std::unique_ptr< World > &&ptr)
Rewriter (World &world)
void reset (std::unique_ptr< World > &&ptr)
void reset ()
World & world ()
virtual void push ()
virtual void pop ()
const Def * map (const Def *old_def, const Def *new_def)
Map old_def to new_def and returns new_def.
const Def * lookup (const Def *old_def)
Lookup old_def by searching in reverse through the stack of maps.
virtual const Def * rewrite (const Def *)
virtual const Def * rewrite_imm (const Def *)
virtual const Def * rewrite_mut (Def *)
virtual const Def * rewrite_stub (Def *, Def *)
virtual DefVec rewrite (Defs)
virtual const Def * rewrite_imm_Seq (const Seq *seq)
virtual const Def * rewrite_mut_Seq (Seq *seq)
Private Member Functions
void rewrite_external (Def *) final
Additional Inherited Members
template<class P, class... Args>
static void run (Args &&... args)
Runs a single Phase.
static auto create (const Flags2Stages &stages, const Def *def)
template<class A, class P>
static void hook (Flags2Stages &stages)
Protected Member Functions inherited from mim::RWPhase
void start () override
Actual entry.
Protected Attributes inherited from mim::RWPhase
bool bootstrapping_ = true
Protected Attributes inherited from mim::Phase
bool todo_ = false
Set to true to indicate that you want to rerun all Phasees in current your fixed-point PhaseMan.
Protected Attributes inherited from mim::Stage
std::string name_
Detailed Description
Definition at line 7 of file prefix_cleanup.h.
Constructor & Destructor Documentation
PrefixCleanup()
mim::PrefixCleanup::PrefixCleanup (World & world, flags_t annex) inline
Definition at line 9 of file prefix_cleanup.h.
References mim::Stage::annex(), mim::RWPhase::RWPhase(), and mim::RWPhase::world().
Referenced by apply().
Member Function Documentation
apply() [1/3]
void mim::PrefixCleanup::apply (const App *) inline final virtual
Invoked if your Stage has additional args.
Reimplemented from mim::Stage.
Definition at line 13 of file prefix_cleanup.h.
References apply(), and mim::tuple2str().
Referenced by apply().
apply() [2/3]
void mim::PrefixCleanup::apply (Stage &) inline final virtual
Dito, but invoked by Stage::recreate.
Reimplemented from mim::Stage.
Definition at line 14 of file prefix_cleanup.h.
References apply(), and PrefixCleanup().
Referenced by apply().
apply() [3/3]
void mim::PrefixCleanup::apply (std::string prefix)
Definition at line 7 of file prefix_cleanup.cpp.
References mim::Stage::name_.
rewrite_external()
void mim::PrefixCleanup::rewrite_external (Def * old_mut) final private virtual
Reimplemented from mim::RWPhase.
Definition at line 12 of file prefix_cleanup.cpp.
References mim::Def::as_mut(), DLOG, mim::Def::is_external(), mim::Rewriter::rewrite(), and mim::Def::sym().
The documentation for this class was generated from the following files:
include/mim/phase/prefix_cleanup.h
src/mim/phase/prefix_cleanup.cpp