Thorin: thorin::ast::Expr Class Reference
thorin::ast::Expr Class Reference abstract
#include <thorin/ast/ast.h>
Public Member Functions
Ref emit (Emitter &) const
virtual void bind (Scopes &) const =0
virtual Ref emit_decl (Emitter &, Ref) const
virtual void emit_body (Emitter &, Ref) const
Public Member Functions inherited from thorin::ast::Node
Loc loc () const
virtual std::ostream & stream (Tab &, std::ostream &) const =0
void dump () const
Protected Member Functions
Expr (Loc loc)
Protected Member Functions inherited from thorin::ast::Node
Node (Loc loc)
virtual ~Node ()
Private Member Functions
virtual Ref emit_ (Emitter &) const =0
Detailed Description
Definition at line 130 of file ast.h.
Constructor & Destructor Documentation
Expr()
thorin::ast::Expr::Expr (Loc loc) inline protected
Definition at line 132 of file ast.h.
Member Function Documentation
bind()
virtual void thorin::ast::Expr::bind (Scopes &) const pure virtual
Implemented in thorin::ast::ErrorExpr, thorin::ast::InferExpr, thorin::ast::IdExpr, thorin::ast::PrimaryExpr, thorin::ast::LitExpr, thorin::ast::DeclExpr, thorin::ast::TypeExpr, thorin::ast::ArrowExpr, thorin::ast::PiExpr, thorin::ast::LamExpr, thorin::ast::AppExpr, thorin::ast::RetExpr, thorin::ast::SigmaExpr, thorin::ast::TupleExpr, thorin::ast::ArrOrPackExpr< arr >, thorin::ast::ExtractExpr, and thorin::ast::InsertExpr.
Referenced by thorin::ast::LitExpr::bind(), thorin::ast::DeclExpr::bind(), thorin::ast::ArrowExpr::bind(), thorin::ast::PiExpr::bind(), thorin::ast::CDecl::bind(), thorin::ast::IdPtrn::bind(), and thorin::ast::LamDecl::bind_decl().
emit()
Ref thorin::ast::Expr::emit (Emitter & e) const
Definition at line 112 of file emit.cpp.
References emit_(), and thorin::ast::Node::loc().
Referenced by thorin::ast::CDecl::emit(), thorin::ast::LitExpr::emit_(), thorin::ast::DeclExpr::emit_(), thorin::ast::TypeExpr::emit_(), thorin::ast::ArrowExpr::emit_(), thorin::ast::PiExpr::emit_(), thorin::ast::RetExpr::emit_(), thorin::ast::ArrOrPackExpr< arr >::emit_(), thorin::ast::LamDecl::emit_body(), thorin::ast::PiExpr::emit_body(), thorin::ast::LamDecl::emit_decl(), and thorin::ast::IdPtrn::emit_type().
emit_()
virtual Ref thorin::ast::Expr::emit_ (Emitter &) const private pure virtual
Implemented in thorin::ast::ErrorExpr, thorin::ast::InferExpr, thorin::ast::IdExpr, thorin::ast::PrimaryExpr, thorin::ast::LitExpr, thorin::ast::DeclExpr, thorin::ast::TypeExpr, thorin::ast::ArrowExpr, thorin::ast::PiExpr, thorin::ast::LamExpr, thorin::ast::AppExpr, thorin::ast::RetExpr, thorin::ast::SigmaExpr, thorin::ast::TupleExpr, thorin::ast::ArrOrPackExpr< arr >, thorin::ast::ExtractExpr, and thorin::ast::InsertExpr.
Referenced by emit().
emit_body()
virtual void thorin::ast::Expr::emit_body (Emitter & , Ref) const inline virtual
Reimplemented in thorin::ast::PiExpr, thorin::ast::LamExpr, and thorin::ast::SigmaExpr.
Definition at line 139 of file ast.h.
emit_decl()
virtual Ref thorin::ast::Expr::emit_decl (Emitter & , Ref) const inline virtual
Reimplemented in thorin::ast::PiExpr, thorin::ast::LamExpr, and thorin::ast::SigmaExpr.
Definition at line 138 of file ast.h.
The documentation for this class was generated from the following files:
include/thorin/ast/ast.h
src/thorin/ast/emit.cpp