MimIR: mim::IndexSet< Indexer, Key > Class Template Reference
mim::IndexSet< Indexer, Key > Class Template Reference
#include <mim/util/indexset.h>
Classes
class reference
Public Member Functions
IndexSet (const Indexer &indexer)
IndexSet (const IndexSet &other)
IndexSet (IndexSet &&other) noexcept
IndexSet & operator= (IndexSet other) noexcept
const Indexer & indexer () const
size_t capacity () const
size_t next (size_t pos=0)
reference operator[] (Key key)
bool operator[] (Key key) const
template<bool flag>
bool set (Key key)
Depending on flag this method either inserts (true) or removes (false) key and returns true if successful.
bool insert (Key key)
Inserts key and returns true if successful.
bool erase (Key key)
Erase key and returns true if successful.
bool contains (Key key) const
void clear ()
template<class Op>
IndexSet & transform (const IndexSet &other, Op op)
IndexSet & operator&= (const IndexSet &other)
IndexSet & operator|= (const IndexSet &other)
IndexSet & operator^= (const IndexSet &other)
Friends
void swap (IndexSet &set1, IndexSet &set2) noexcept
Detailed Description
template<class Indexer, class Key>
class mim::IndexSet< Indexer, Key >
Definition at line 8 of file indexset.h.
Constructor & Destructor Documentation
IndexSet() [1/3]
template<class Indexer, class Key> mim::IndexSet< Indexer, Key >::IndexSet (const Indexer & indexer) inline
Definition at line 38 of file indexset.h.
References capacity(), and indexer().
Referenced by IndexSet(), IndexSet(), operator&=(), operator=(), operator[](), operator^=(), operator|=(), swap, and transform().
IndexSet() [2/3]
template<class Indexer, class Key> mim::IndexSet< Indexer, Key >::IndexSet (const IndexSet< Indexer, Key > & other) inline
Definition at line 41 of file indexset.h.
References indexer(), and IndexSet().
IndexSet() [3/3]
template<class Indexer, class Key> mim::IndexSet< Indexer, Key >::IndexSet (IndexSet< Indexer, Key > && other) inline noexcept
Definition at line 44 of file indexset.h.
References IndexSet().
Member Function Documentation
capacity()
template<class Indexer, class Key> size_t mim::IndexSet< Indexer, Key >::capacity () const inline
Definition at line 50 of file indexset.h.
References indexer().
Referenced by IndexSet(), next(), and transform().
clear()
template<class Indexer, class Key> void mim::IndexSet< Indexer, Key >::clear () inline
Definition at line 74 of file indexset.h.
contains()
template<class Indexer, class Key> bool mim::IndexSet< Indexer, Key >::contains (Key key) const inline
Definition at line 73 of file indexset.h.
erase()
template<class Indexer, class Key> bool mim::IndexSet< Indexer, Key >::erase (Key key) inline
Erase key and returns true if successful.
Definition at line 72 of file indexset.h.
References set().
indexer()
template<class Indexer, class Key> const Indexer & mim::IndexSet< Indexer, Key >::indexer () const inline
Definition at line 49 of file indexset.h.
Referenced by capacity(), IndexSet(), IndexSet(), and operator[]().
insert()
template<class Indexer, class Key> bool mim::IndexSet< Indexer, Key >::insert (Key key) inline
Inserts key and returns true if successful.
Definition at line 71 of file indexset.h.
References set().
next()
template<class Indexer, class Key> size_t mim::IndexSet< Indexer, Key >::next (size_t pos = 0) inline
Definition at line 51 of file indexset.h.
References capacity().
operator&=()
template<class Indexer, class Key> IndexSet & mim::IndexSet< Indexer, Key >::operator&= (const IndexSet< Indexer, Key > & other) inline
Definition at line 83 of file indexset.h.
References IndexSet(), and transform().
operator=()
template<class Indexer, class Key> IndexSet & mim::IndexSet< Indexer, Key >::operator= (IndexSet< Indexer, Key > other) inline noexcept
Definition at line 47 of file indexset.h.
References IndexSet(), and swap.
operator[]() [1/2]
template<class Indexer, class Key> reference mim::IndexSet< Indexer, Key >::operator[] (Key key) inline
Definition at line 56 of file indexset.h.
References indexer().
operator[]() [2/2]
template<class Indexer, class Key> bool mim::IndexSet< Indexer, Key >::operator[] (Key key) const inline
Definition at line 61 of file indexset.h.
References IndexSet().
operator^=()
template<class Indexer, class Key> IndexSet & mim::IndexSet< Indexer, Key >::operator^= (const IndexSet< Indexer, Key > & other) inline
Definition at line 85 of file indexset.h.
References IndexSet(), and transform().
operator|=()
template<class Indexer, class Key> IndexSet & mim::IndexSet< Indexer, Key >::operator|= (const IndexSet< Indexer, Key > & other) inline
Definition at line 84 of file indexset.h.
References IndexSet(), and transform().
set()
template<class Indexer, class Key> template<bool flag> bool mim::IndexSet< Indexer, Key >::set (Key key) inline
Depending on flag this method either inserts (true) or removes (false) key and returns true if successful.
Definition at line 65 of file indexset.h.
Referenced by erase(), and insert().
transform()
template<class Indexer, class Key> template<class Op> IndexSet & mim::IndexSet< Indexer, Key >::transform (const IndexSet< Indexer, Key > & other, Op op) inline
Definition at line 77 of file indexset.h.
References capacity(), and IndexSet().
Referenced by operator&=(), operator^=(), and operator|=().
Friends And Related Symbol Documentation
swap
template<class Indexer, class Key> void swap (IndexSet< Indexer, Key > & set1, IndexSet< Indexer, Key > & set2) friend
Definition at line 86 of file indexset.h.
References IndexSet(), and swap.
Referenced by operator=(), and swap.
The documentation for this class was generated from the following file:
include/mim/util/indexset.h