MimIR: mim::LamSpec Class Reference
mim::LamSpec Class Reference
#include <mim/pass/lam_spec.h>
Public Member Functions
LamSpec (World &world, flags_t annex)
Public Member Functions inherited from mim::RWPass< LamSpec, Lam >
RWPass (World &world, std::string name)
RWPass (World &world, flags_t annex)
bool inspect () const override
Should the PassMan even consider this pass?
Lam * curr_mut () const
Public Member Functions inherited from mim::Pass
Pass (World &world, std::string name)
Pass (World &world, flags_t annex)
virtual void init (PassMan *)
PassMan & man ()
const PassMan & man () const
size_t index () const
virtual const Def * rewrite (const Var *var)
virtual const Def * rewrite (const Proxy *proxy)
virtual undo_t analyze (const Def *)
virtual undo_t analyze (const Var *)
virtual undo_t analyze (const Proxy *)
virtual bool fixed_point () const
virtual void enter ()
Invoked just before Pass::rewriteing PassMan::curr_mut's body.
virtual void prepare ()
Invoked once before entering the main rewrite loop.
const Proxy * proxy (const Def *type, Defs ops, u32 tag=0)
const Proxy * isa_proxy (const Def *def, u32 tag=0)
Check whether given def is a Proxy whose Proxy::pass matches this Pass's IPass::index.
const Proxy * as_proxy (const Def *def, u32 tag=0)
Public Member Functions inherited from mim::Stage
World & world ()
Driver & driver ()
Log & log () const
std::string_view name () const
flags_t annex () const
Stage (World &world, std::string name)
Stage (World &world, flags_t annex)
virtual ~Stage ()=default
virtual std::unique_ptr< Stage > recreate ()
Creates a new instance; needed by a fixed-point PhaseMan.
virtual void apply (const App *)
Invoked if your Stage has additional args.
virtual void apply (Stage &)
Dito, but invoked by Stage::recreate.
Private Member Functions
PassMan hooks
const Def * rewrite (const Def *) override
Additional Inherited Members
static auto create (const Flags2Stages &stages, const Def *def)
template<class A, class P>
static void hook (Flags2Stages &stages)
Protected Attributes inherited from mim::Stage
std::string name_
Detailed Description
Definition at line 7 of file lam_spec.h.
Constructor & Destructor Documentation
LamSpec()
mim::LamSpec::LamSpec (World & world, flags_t annex) inline
Definition at line 9 of file lam_spec.h.
References mim::Stage::annex(), mim::RWPass< LamSpec, Lam >::RWPass(), and mim::Stage::world().
Member Function Documentation
rewrite()
const Def * mim::LamSpec::rewrite (const Def * def) override private virtual
Reimplemented from mim::Pass.
Definition at line 9 of file lam_spec.cpp.
References mim::World::app(), DLOG, mim::Nest::is_recursive(), mim::isa_apped_mut_lam(), mim::isa_workable(), mim::Def::set(), mim::Def::stub(), and mim::Stage::world().
The documentation for this class was generated from the following files:
include/mim/pass/lam_spec.h
src/mim/pass/lam_spec.cpp