Thorin: thorin::App Class Reference
thorin::App Class Reference
#include <thorin/lam.h>
Public Member Functions
template<bool Ow = false>
const App * set (Loc l) const
template<bool Ow = false>
App * set (Loc l)
template<bool Ow = false>
const App * set (Sym s) const
template<bool Ow = false>
App * set (Sym s)
template<bool Ow = false>
const App * set (std::string s) const
template<bool Ow = false>
App * set (std::string s)
template<bool Ow = false>
const App * set (Loc l, Sym s) const
template<bool Ow = false>
App * set (Loc l, Sym s)
template<bool Ow = false>
const App * set (Loc l, std::string s) const
template<bool Ow = false>
App * set (Loc l, std::string s)
template<bool Ow = false>
const App * set (Dbg d) const
template<bool Ow = false>
App * set (Dbg d)
App * stub (World &w, const Def *type)
ops
const Def * callee () const
const App * decurry () const
Returns App::callee again as App.
const Pi * callee_type () const
const Def * arg () const
nat_t num_args () const
Ref arg (nat_t a, nat_t i) const
Ref arg (nat_t i) const
template<nat_t A = -1_s, class F >
auto args (F f) const
template<nat_t A = -1_s>
auto args () const
template<class F >
auto args (nat_t a, F f) const
auto args (nat_t a) const
get axiom, current curry counter and trip count
const Axiom * axiom () const
u8 curry () const
u8 trip () const
Public Member Functions inherited from thorin::Def
World & world () const
flags_t flags () const
u32 gid () const
hash_t hash () const
node_t node () const
std::string_view node_name () const
const Def * type () const
Yields the raw type of this Def; maybe nullptr.
const Def * unfold_type () const
Yields the type of this Def and unfolds it if necessary. See Def::type, Def::reduce_rec.
Sort sort () const
const Def * arity () const
std::optional< nat_t > isa_lit_arity () const
nat_t as_lit_arity () const
template<size_t N = -1_s>
auto ops () const
const Def * op (size_t i) const
size_t num_ops () const
Def * set (size_t i, const Def *def)
Def * set (Defs ops)
void unset (size_t i)
void unset ()
Def * set_type (const Def *)
void unset_type ()
void update ()
Resolves Infers of this Def's type.
bool is_set () const
Yields true if empty or the last op is set.
Defs extended_ops () const
const Def * extended_op (size_t i) const
size_t num_extended_ops () const
Defs partial_ops () const
const Def * partial_op (size_t i) const
size_t num_partial_ops () const
const Uses & uses () const
Array< Use > copy_uses () const
size_t num_uses () const
unsigned dep () const
bool has_dep (Dep d) const
bool has_dep (unsigned u) const
bool dep_const () const
nat_t num_projs () const
Yields Def::arity as_lit, if it is in fact a Lit, or 1 otherwise.
const Def * proj (nat_t a, nat_t i) const
Similar to World::extract while assuming an arity of a but also works on Sigmas, and Arrays.
const Def * proj (nat_t i) const
Same as above but takes Def::num_projs as arity.
template<nat_t A = -1_s, class F >
auto projs (F f) const
Splits this Def via Def::projections into an Array (if A == -1_s) or std::array (otherwise).
template<class F >
auto projs (nat_t a, F f) const
template<nat_t A = -1_s>
auto projs () const
auto projs (nat_t a) const
bool is_external () const
bool is_internal () const
Not Def::is_external.
void make_external ()
void make_internal ()
std::string unique_name () const
name + "_" + Def::gid
template<bool Ow = false>
const Def * set (Loc l) const
template<bool Ow = false>
Def * set (Loc l)
template<bool Ow = false>
const Def * set (Sym s) const
template<bool Ow = false>
Def * set (Sym s)
template<bool Ow = false>
const Def * set (std::string s) const
template<bool Ow = false>
Def * set (std::string s)
template<bool Ow = false>
const Def * set (Loc l, Sym s) const
template<bool Ow = false>
Def * set (Loc l, Sym s)
template<bool Ow = false>
const Def * set (Loc l, std::string s) const
template<bool Ow = false>
Def * set (Loc l, std::string s)
template<bool Ow = false>
const Def * set (Dbg d) const
template<bool Ow = false>
Def * set (Dbg d)
Dbg dbg () const
Loc loc () const
Sym sym () const
const Def * debug_prefix (std::string) const
const Def * debug_suffix (std::string) const
template<class T = Def>
const T * isa_structural () const
template<class T = Def>
const T * as_structural () const
template<class T = Def, bool invert = false>
T * isa_nom () const
If this is *nom*inal, it will cast constness away and perform a dynamic cast to T.
template<class T = Def, bool invert = false>
T * as_nom () const
Asserts that this is a *nom*inal, casts constness away and performs a static cast to T (checked in Debug build).
const Var * var ()
nat_t num_vars ()
Ref var (nat_t a, nat_t i)
Ref var (nat_t i)
template<nat_t A = -1_s, class F >
auto vars (F f)
template<nat_t A = -1_s>
auto vars ()
template<class F >
auto vars (nat_t a, F f)
auto vars (nat_t a)
DefArray reduce (const Def *arg) const
DefArray reduce (const Def *arg)
const Def * reduce_rec () const
Transitively Def::reduce Lams, if this is an App.
Def * stub (World &w, Ref type)
Ref rebuild (World &w, Ref type, Defs ops) const
Def::rebuilds this Def while using new_op as substitute for its i'th Def::op.
virtual void check ()
virtual size_t first_dependend_op ()
const Def * refine (size_t i, const Def *new_op) const
virtual const Def * restructure ()
void dump () const
void dump (int max) const
void write (int max) const
void write (int max, const char *file) const
std::ostream & stream (std::ostream &, int max) const
Public Member Functions inherited from thorin::RuntimeCast< Def >
T * as ()
static_cast with debug check.
const T * as () const
const version.
T * isa ()
dynamic_cast.
Def * isa ()
Yields B* if it is either T or U and `nullptr* otherwise.
const T * isa () const
const version.
const Def * isa () const
const version.
Static Public Attributes
static constexpr auto Node = Node:: App
Friends
class World
Additional Inherited Members
Public Types inherited from thorin::Def
using NormalizeFn = Ref(*)(Ref, Ref, Ref)
Protected Member Functions inherited from thorin::Def
Def (World *, node_t, const Def *type, Defs ops, flags_t flags)
Constructor for a structural Def.
Def (node_t n, const Def *type, Defs ops, flags_t flags)
Def (node_t, const Def *type, size_t num_ops, flags_t flags)
Constructor for a *nom*inal Def.
virtual ~Def ()=default
virtual Ref rebuild_ (World &, Ref, Defs) const =0
virtual Def * stub_ (World &, Ref)
const Def ** ops_ptr () const
void finalize ()
bool equal (const Def *other) const
Sym get_sym (const char *) const
Sym get_sym (std::string_view) const
Sym get_sym (std::string) const
Protected Attributes inherited from thorin::Def
union {
NormalizeFn normalizer_
Axioms use this member to store their normalizer.
const Axiom * axiom_
World * world_
Curried Apps of Axioms use this member to propagate the Axiom.
};
flags_t flags_
uint8_t node_
unsigned nom_: 1
unsigned external_: 1
unsigned dep_: 5
unsigned pading_: 1
u8 curry_
u8 trip_
hash_t hash_
u32 gid_
u32 num_ops_
Uses uses_
Dbg dbg_
const Def * type_
Detailed Description
Definition at line 122 of file lam.h.
Member Function Documentation
arg() [1/3]
const Def * thorin::App::arg () const inline
Definition at line 137 of file lam.h.
References thorin::Def::op().
Referenced by thorin::autodiff::AutoDiffEval::augment_app(), thorin::clos::isa_cont(), thorin::core::normalize_conv(), thorin::math::normalize_conv(), thorin::core::normalize_zip(), thorin::register_pass_with_arg(), thorin::clos::ClosConvPrep::rewrite_arg(), and thorin_get_dialect_info().
arg() [2/3]
Ref thorin::App::arg (nat_t a, nat_t i) const inline
Definition at line 138 of file lam.h.
arg() [3/3]
Ref thorin::App::arg (nat_t i) const inline
Definition at line 138 of file lam.h.
args() [1/4]
template<nat_t A = -1_s> auto thorin::App::args () const inline
Definition at line 138 of file lam.h.
args() [2/4]
template<nat_t A = -1_s, class F > auto thorin::App::args (F f) const inline
Definition at line 138 of file lam.h.
Referenced by thorin::ll::Emitter::emit_epilogue().
args() [3/4]
auto thorin::App::args (nat_t a) const inline
Definition at line 138 of file lam.h.
args() [4/4]
template<class F > auto thorin::App::args (nat_t a, F f) const inline
Definition at line 138 of file lam.h.
axiom()
const Axiom * thorin::App::axiom () const inline
Definition at line 143 of file lam.h.
callee()
const Def * thorin::App::callee () const inline
Definition at line 134 of file lam.h.
References thorin::Def::op().
Referenced by thorin::autodiff::AutoDiffEval::augment_app(), callee_type(), decurry(), thorin::clos::isa_br(), and thorin::clos::ClosConvPrep::rewrite_callee().
callee_type()
const Pi * thorin::App::callee_type () const inline
Definition at line 136 of file lam.h.
References thorin::RuntimeCast< B >::as(), callee(), and thorin::Def::type().
Referenced by thorin::clos::isa_br(), thorin::clos::isa_callee_br(), thorin::clos::isa_cont(), and thorin::clos::ClosConvPrep::rewrite_callee().
curry()
u8 thorin::App::curry () const inline
Definition at line 144 of file lam.h.
References thorin::Def::curry_.
decurry()
const App * thorin::App::decurry () const inline
Returns App::callee again as App.
Definition at line 135 of file lam.h.
References thorin::RuntimeCast< B >::as(), and callee().
num_args()
nat_t thorin::App::num_args () const inline
Definition at line 138 of file lam.h.
set() [1/12]
template<bool Ow = false> App * thorin::App::set (Dbg d) inline
Definition at line 148 of file lam.h.
set() [2/12]
template<bool Ow = false> const App * thorin::App::set (Dbg d) const inline
Definition at line 148 of file lam.h.
set() [3/12]
template<bool Ow = false> App * thorin::App::set (Loc l) inline
Definition at line 148 of file lam.h.
set() [4/12]
template<bool Ow = false> const App * thorin::App::set (Loc l) const inline
Definition at line 148 of file lam.h.
set() [5/12]
template<bool Ow = false> App * thorin::App::set (Loc l, std::string s) inline
Definition at line 148 of file lam.h.
set() [6/12]
template<bool Ow = false> const App * thorin::App::set (Loc l, std::string s) const inline
Definition at line 148 of file lam.h.
set() [7/12]
template<bool Ow = false> App * thorin::App::set (Loc l, Sym s) inline
Definition at line 148 of file lam.h.
set() [8/12]
template<bool Ow = false> const App * thorin::App::set (Loc l, Sym s) const inline
Definition at line 148 of file lam.h.
set() [9/12]
template<bool Ow = false> App * thorin::App::set (std::string s) inline
Definition at line 148 of file lam.h.
set() [10/12]
template<bool Ow = false> const App * thorin::App::set (std::string s) const inline
Definition at line 148 of file lam.h.
set() [11/12]
template<bool Ow = false> App * thorin::App::set (Sym s) inline
Definition at line 148 of file lam.h.
set() [12/12]
template<bool Ow = false> const App * thorin::App::set (Sym s) const inline
Definition at line 148 of file lam.h.
stub()
App * thorin::App::stub (World & w, const Def * type) inline
Definition at line 148 of file lam.h.
trip()
u8 thorin::App::trip () const inline
Definition at line 145 of file lam.h.
References thorin::Def::trip_.
Friends And Related Function Documentation
World
friend class World friend
Definition at line 148 of file lam.h.
Member Data Documentation
Node
constexpr auto thorin::App::Node = Node:: App static constexpr
Definition at line 148 of file lam.h.
The documentation for this class was generated from the following files:
thorin/lam.h
thorin/def.cpp