MimIR: mim::ast::AxiomDecl Class Reference
mim::ast::AxiomDecl Class Reference
axm ptrn: type = value;
#include <mim/ast/ast.h>
Classes
class Alias
Public Member Functions
AxiomDecl (Loc loc, Dbg dbg, std::deque< Ptrs< Alias > > &&subs, Ptr< Expr > &&type, Dbg normalizer, Tok curry, Tok trip)
Dbg dbg () const
const auto & subs () const
size_t num_subs () const
const auto & sub (size_t i) const
const Expr * type () const
Dbg normalizer () const
Tok curry () const
Tok trip () const
void bind (Scopes &) const override
void emit (Emitter &) const override
std::ostream & stream (Tab &, std::ostream &) const override
Public Member Functions inherited from mim::ast::ValDecl
Public Member Functions inherited from mim::ast::Decl
Ref def () const
Public Member Functions inherited from mim::ast::Node
Loc loc () const
void dump () const
Additional Inherited Members
Protected Member Functions inherited from mim::ast::ValDecl
ValDecl (Loc loc)
Protected Member Functions inherited from mim::ast::Decl
Decl (Loc loc)
Protected Member Functions inherited from mim::ast::Node
Node (Loc loc)
virtual ~Node ()
Protected Attributes inherited from mim::ast::Decl
Ref def_ = nullptr
Detailed Description
axm ptrn: type = value;
Definition at line 771 of file ast.h.
Constructor & Destructor Documentation
AxiomDecl()
mim::ast::AxiomDecl::AxiomDecl (Loc loc, Dbg dbg, std::deque< Ptrs< Alias > > && subs, Ptr< Expr > && type, Dbg normalizer, Tok curry, Tok trip) inline
Definition at line 791 of file ast.h.
Member Function Documentation
bind()
void mim::ast::AxiomDecl::bind (Scopes & s) const override virtual
Implements mim::ast::ValDecl.
Definition at line 226 of file bind.cpp.
References mim::ast::Node::loc().
curry()
Tok mim::ast::AxiomDecl::curry () const inline
Definition at line 806 of file ast.h.
dbg()
Dbg mim::ast::AxiomDecl::dbg () const inline
Definition at line 800 of file ast.h.
Referenced by mim::ast::AxiomDecl::Alias::bind().
emit()
void mim::ast::AxiomDecl::emit (Emitter & e) const override virtual
Implements mim::ast::ValDecl.
Definition at line 350 of file emit.cpp.
References mim::error(), mim::Axiom::infer_curry_and_trip(), and mim::ast::Node::loc().
normalizer()
Dbg mim::ast::AxiomDecl::normalizer () const inline
Definition at line 805 of file ast.h.
num_subs()
size_t mim::ast::AxiomDecl::num_subs () const inline
Definition at line 802 of file ast.h.
stream()
std::ostream & mim::ast::AxiomDecl::stream (Tab & tab, std::ostream & os) const override virtual
Implements mim::ast::Node.
Definition at line 162 of file stream.cpp.
References mim::print().
sub()
const auto & mim::ast::AxiomDecl::sub (size_t i) const inline
Definition at line 803 of file ast.h.
subs()
const auto & mim::ast::AxiomDecl::subs () const inline
Definition at line 801 of file ast.h.
trip()
Tok mim::ast::AxiomDecl::trip () const inline
Definition at line 807 of file ast.h.
type()
const Expr * mim::ast::AxiomDecl::type () const inline
Definition at line 804 of file ast.h.
The documentation for this class was generated from the following files:
include/mim/ast/ast.h
src/mim/ast/bind.cpp
src/mim/ast/emit.cpp
src/mim/ast/stream.cpp