MimIR: mim::ast::LitExpr Class Reference
mim::ast::LitExpr Class Reference
tok:type
#include <mim/ast/ast.h>
Public Member Functions
LitExpr (Loc loc, Tok tok, Ptr< Expr > &&type)
Tok tok () const
Tok::Tag tag () const
const Expr * type () const
void bind (Scopes &) const override
std::ostream & stream (Tab &, std::ostream &) const override
Public Member Functions inherited from mim::ast::Expr
const Def * emit (Emitter &) const
virtual const Def * emit_decl (Emitter &, const Def *) const
virtual void emit_body (Emitter &, const Def *) const
Public Member Functions inherited from mim::ast::Node
Loc loc () const
void dump () const
Private Member Functions
const Def * emit_ (Emitter &) const override
Additional Inherited Members
enum class Prec {
Err ,
Bot ,
Where ,
Arrow ,
Pi ,
Inj ,
App ,
Union ,
Extract ,
Lit
}
static constexpr bool is_rassoc (Prec p)
Protected Member Functions inherited from mim::ast::Expr
Expr (Loc loc)
Protected Member Functions inherited from mim::ast::Node
Node (Loc loc)
virtual ~Node ()
Detailed Description
tok:type
Definition at line 388 of file ast.h.
Constructor & Destructor Documentation
LitExpr()
mim::ast::LitExpr::LitExpr (Loc loc, Tok tok, Ptr< Expr > && type) inline
Definition at line 390 of file ast.h.
References mim::ast::Expr::Expr(), mim::ast::Node::loc(), tok(), and type().
Member Function Documentation
bind()
void mim::ast::LitExpr::bind (Scopes & s) const override virtual
Implements mim::ast::Expr.
Definition at line 127 of file bind.cpp.
References mim::ast::Expr::bind(), mim::ast::Node::loc(), tag(), and type().
emit_()
const Def * mim::ast::LitExpr::emit_ (Emitter & e) const override private virtual
Implements mim::ast::Expr.
Definition at line 174 of file emit.cpp.
References mim::ast::Expr::emit(), mim::ast::Tok::lit_i(), tag(), tok(), and type().
stream()
std::ostream & mim::ast::LitExpr::stream (Tab & tab, std::ostream & os) const override virtual
Implements mim::ast::Node.
Definition at line 82 of file stream.cpp.
References mim::ast::Tok::lit_u(), mim::print(), tag(), tok(), and type().
tag()
Tok::Tag mim::ast::LitExpr::tag () const inline
Definition at line 396 of file ast.h.
Referenced by bind(), emit_(), and stream().
tok()
Tok mim::ast::LitExpr::tok () const inline
Definition at line 395 of file ast.h.
Referenced by emit_(), LitExpr(), and stream().
type()
const Expr * mim::ast::LitExpr::type () const inline
Definition at line 397 of file ast.h.
References mim::ast::Expr::Expr().
Referenced by bind(), emit_(), LitExpr(), and stream().
The documentation for this class was generated from the following files:
include/mim/ast/ast.h
src/mim/ast/bind.cpp
src/mim/ast/emit.cpp
src/mim/ast/stream.cpp