MimIR: mim::Setters< P, D > Class Template Reference
mim::Setters< P, D > Class Template Reference
CRTP-based Mixin to declare setters for Def::loc & Def::name using a covariant return type.
#include <mim/def.h>
Public Member Functions
template<bool Ow = false>
const P * set (Loc l) const
template<bool Ow = false>
P * set (Loc l)
template<bool Ow = false>
const P * set (Sym s) const
template<bool Ow = false>
P * set (Sym s)
template<bool Ow = false>
const P * set (std::string s) const
template<bool Ow = false>
P * set (std::string s)
template<bool Ow = false>
const P * set (Loc l, Sym s) const
template<bool Ow = false>
P * set (Loc l, Sym s)
template<bool Ow = false>
const P * set (Loc l, std::string s) const
template<bool Ow = false>
P * set (Loc l, std::string s)
template<bool Ow = false>
const P * set (Dbg d) const
template<bool Ow = false>
P * set (Dbg d)
Detailed Description
template<class P, class D = Def>
class mim::Setters< P, D >
CRTP-based Mixin to declare setters for Def::loc & Def::name using a covariant return type.
Definition at line 189 of file def.h.
Member Function Documentation
set() [1/12]
template<class P , class D = Def> template<bool Ow = false> P * mim::Setters< P, D >::set (Dbg d) inline
Definition at line 207 of file def.h.
References mim::Setters< P, D >::set().
set() [2/12]
template<class P , class D = Def> template<bool Ow = false> const P * mim::Setters< P, D >::set (Dbg d) const inline
Definition at line 206 of file def.h.
References mim::Setters< P, D >::set().
set() [3/12]
template<class P , class D = Def> template<bool Ow = false> P * mim::Setters< P, D >::set (Loc l) inline
Definition at line 197 of file def.h.
References mim::Setters< P, D >::set().
set() [4/12]
template<class P , class D = Def> template<bool Ow = false> const P * mim::Setters< P, D >::set (Loc l) const inline
Definition at line 196 of file def.h.
References mim::Setters< P, D >::set().
Referenced by mim::Setters< P, D >::set(), mim::Setters< P, D >::set(), mim::Setters< P, D >::set(), mim::Setters< P, D >::set(), mim::Setters< P, D >::set(), mim::Setters< P, D >::set(), mim::Setters< P, D >::set(), mim::Setters< P, D >::set(), mim::Setters< P, D >::set(), mim::Setters< P, D >::set(), mim::Setters< P, D >::set(), mim::Setters< P, D >::set(), mim::TBound< Up >::stub(), and mim::TExt< Up >::stub().
set() [5/12]
template<class P , class D = Def> template<bool Ow = false> P * mim::Setters< P, D >::set (Loc l, std::string s) inline
Definition at line 205 of file def.h.
References mim::Setters< P, D >::set().
set() [6/12]
template<class P , class D = Def> template<bool Ow = false> const P * mim::Setters< P, D >::set (Loc l, std::string s) const inline
Definition at line 204 of file def.h.
References mim::Setters< P, D >::set().
set() [7/12]
template<class P , class D = Def> template<bool Ow = false> P * mim::Setters< P, D >::set (Loc l, Sym s) inline
Definition at line 203 of file def.h.
References mim::Setters< P, D >::set().
set() [8/12]
template<class P , class D = Def> template<bool Ow = false> const P * mim::Setters< P, D >::set (Loc l, Sym s) const inline
Definition at line 202 of file def.h.
References mim::Setters< P, D >::set().
set() [9/12]
template<class P , class D = Def> template<bool Ow = false> P * mim::Setters< P, D >::set (std::string s) inline
Definition at line 201 of file def.h.
References mim::Setters< P, D >::set().
set() [10/12]
template<class P , class D = Def> template<bool Ow = false> const P * mim::Setters< P, D >::set (std::string s) const inline
Definition at line 200 of file def.h.
References mim::Setters< P, D >::set().
set() [11/12]
template<class P , class D = Def> template<bool Ow = false> P * mim::Setters< P, D >::set (Sym s) inline
Definition at line 199 of file def.h.
References mim::Setters< P, D >::set().
set() [12/12]
template<class P , class D = Def> template<bool Ow = false> const P * mim::Setters< P, D >::set (Sym s) const inline
Definition at line 198 of file def.h.
References mim::Setters< P, D >::set().
The documentation for this class was generated from the following file:
include/mim/def.h