Thorin: thorin::ast::PrimaryExpr Class Reference
thorin::ast::PrimaryExpr Class Reference
tag
#include <thorin/ast/ast.h>
Public Member Functions
PrimaryExpr (Loc loc, Tok::Tag tag)
PrimaryExpr (Tok tok)
Tok::Tag tag () const
void bind (Scopes &) const override
std::ostream & stream (Tab &, std::ostream &) const override
Public Member Functions inherited from thorin::ast::Expr
Ref emit (Emitter &) const
virtual Ref emit_decl (Emitter &, Ref) const
virtual void emit_body (Emitter &, Ref) const
Public Member Functions inherited from thorin::ast::Node
Loc loc () const
void dump () const
Private Member Functions
Ref emit_ (Emitter &) const override
Additional Inherited Members
Protected Member Functions inherited from thorin::ast::Expr
Expr (Loc loc)
Protected Member Functions inherited from thorin::ast::Node
Node (Loc loc)
virtual ~Node ()
Detailed Description
tag
Definition at line 327 of file ast.h.
Constructor & Destructor Documentation
PrimaryExpr() [1/2]
thorin::ast::PrimaryExpr::PrimaryExpr (Loc loc, Tok::Tag tag) inline
Definition at line 329 of file ast.h.
PrimaryExpr() [2/2]
thorin::ast::PrimaryExpr::PrimaryExpr (Tok tok) inline
Definition at line 332 of file ast.h.
Member Function Documentation
bind()
void thorin::ast::PrimaryExpr::bind (Scopes &) const override virtual
Implements thorin::ast::Expr.
Definition at line 117 of file bind.cpp.
emit_()
Ref thorin::ast::PrimaryExpr::emit_ (Emitter & e) const override private virtual
Implements thorin::ast::Expr.
Definition at line 130 of file emit.cpp.
stream()
std::ostream & thorin::ast::PrimaryExpr::stream (Tab & , std::ostream & os) const override virtual
Implements thorin::ast::Node.
Definition at line 79 of file stream.cpp.
References thorin::print(), and tag().
tag()
Tok::Tag thorin::ast::PrimaryExpr::tag () const inline
Definition at line 335 of file ast.h.
Referenced by stream().
The documentation for this class was generated from the following files:
include/thorin/ast/ast.h
src/thorin/ast/bind.cpp
src/thorin/ast/emit.cpp
src/thorin/ast/stream.cpp