Thorin: thorin::Dialect Class Reference
thorin::Dialect Class Reference
A thorin dialect.
#include <thorin/dialects.h>
Public Member Functions
std::string name () const
Name of the dialect.
void * handle ()
Shared object handle. Can be used with the functions from dl.
void register_passes (Passes &passes) const
Registers callbacks in the builder that extend the exposed PassMan's.
void register_backends (Backends &backends) const
Registers the mapping from backend names to emission functions in the given backends map.
void register_normalizers (Normalizers &normalizers) const
Registers the mapping from axiom ids to normalizer functions in the given normalizers map.
Static Public Member Functions
static Dialect load (const std::string &name, Span< std::string > search_paths)
Finds and loads a shared object file that implements the name thorin dialect.
Detailed Description
A thorin dialect.
This is used to load and manage a thorin dialect.
A plugin implementor should implement thorin_get_dialect_info and DialectInfo.
Definition at line 45 of file dialects.h.
Member Function Documentation
handle()
void * thorin::Dialect::handle () inline
Shared object handle. Can be used with the functions from dl.
Definition at line 58 of file dialects.h.
Referenced by load().
load()
Dialect thorin::Dialect::load (const std::string & name, Span< std::string > search_paths) static
Finds and loads a shared object file that implements the name thorin dialect.
If name is an absolute path to a .so/.dll file, this is used. Otherwise, "name", "libthorin_name.so" (Linux, Mac), "thorin_name.dll" (Win) are searched for in the search paths:
search_paths, 2. env var THORIN_DIALECT_PATH, 3. "/path/to/executable"
Definition at line 74 of file dialects.cpp.
References thorin::dl::close(), get_plugin_name_variants(), thorin::get_plugin_search_paths(), handle(), name(), and thorin::dl::open().
name()
std::string thorin::Dialect::name () const inline
Name of the dialect.
Definition at line 55 of file dialects.h.
References thorin::DialectInfo::plugin_name.
Referenced by load().
register_backends()
void thorin::Dialect::register_backends (Backends & backends) const inline
Registers the mapping from backend names to emission functions in the given backends map.
Definition at line 66 of file dialects.h.
References thorin::DialectInfo::register_backends.
register_normalizers()
void thorin::Dialect::register_normalizers (Normalizers & normalizers) const inline
Registers the mapping from axiom ids to normalizer functions in the given normalizers map.
Definition at line 71 of file dialects.h.
References thorin::DialectInfo::register_normalizers.
register_passes()
void thorin::Dialect::register_passes (Passes & passes) const inline
Registers callbacks in the builder that extend the exposed PassMan's.
Definition at line 61 of file dialects.h.
References thorin::DialectInfo::register_passes.
The documentation for this class was generated from the following files:
thorin/dialects.h
thorin/dialects.cpp