Thorin: thorin::autodiff::AutoDiffEval Class Reference
thorin::autodiff::AutoDiffEval Class Reference
This pass is the heart of AD.
#include <dialects/autodiff/passes/autodiff_eval.h>
Public Member Functions
AutoDiffEval (PassMan &man)
const Def * rewrite (const Def *) override
Detect autodiff calls.
const Def * derive (const Def *)
Acts on toplevel autodiff on closed terms:
const Def * derive_ (const Def *)
Additionally to the derivation, the pullback is registered and the maps are initialized.
const Def * augment (const Def *, Lam *, Lam *)
Applies to (open) expressions in a functional context.
const Def * augment_ (const Def *, Lam *, Lam *)
Rewrites the given definition in a lambda environment.
const Def * augment_var (const Var *, Lam *, Lam *)
helper functions for augment
const Def * augment_lam (Lam *, Lam *, Lam *)
const Def * augment_extract (const Extract *, Lam *, Lam *)
const Def * augment_app (const App *, Lam *, Lam *)
const Def * augment_lit (const Lit *, Lam *, Lam *)
const Def * augment_tuple (const Tuple *, Lam *, Lam *)
const Def * augment_pack (const Pack *pack, Lam *f, Lam *f_diff)
Public Member Functions inherited from thorin::RWPass< AutoDiffEval, Lam >
RWPass (PassMan &man, std::string_view name)
bool inspect () const override
Should the PassMan even consider this pass?
Lam * curr_nom () const
Public Member Functions inherited from thorin::Pass
Pass (PassMan &, std::string_view name)
virtual ~Pass ()=default
World & world ()
PassMan & man ()
const PassMan & man () const
std::string_view name () const
size_t index () const
virtual const Def * rewrite (const Var *var)
virtual const Def * rewrite (const Proxy *proxy)
virtual undo_t analyze (const Def *)
virtual undo_t analyze (const Var *)
virtual undo_t analyze (const Proxy *)
virtual bool fixed_point () const
virtual void enter ()
Invoked just before Pass::rewriteing PassMan::curr_nom's body.
const Proxy * proxy (const Def *type, Defs ops, u32 tag=0, const Def *dbg={})
const Proxy * isa_proxy (const Def *def, u32 tag=0)
Check whether given def is a Proxy whose Proxy::pass matches this Pass's IPass::index.
const Proxy * as_proxy (const Def *def, u32 tag=0)
Detailed Description
This pass is the heart of AD.
We replace an autodiff fun call with the differentiated function.
Definition at line 10 of file autodiff_eval.h.
Constructor & Destructor Documentation
AutoDiffEval()
thorin::autodiff::AutoDiffEval::AutoDiffEval (PassMan & man) inline
Definition at line 12 of file autodiff_eval.h.
Member Function Documentation
augment()
const Def * thorin::autodiff::AutoDiffEval::augment (const Def * def, Lam * f, Lam * f_diff)
Applies to (open) expressions in a functional context.
Returns the rewritten expressions and augments the partial and modular pullbacks. The rewrite is identity on the term up to renaming of variables. Otherwise, only pullbacks are added. To do so, some calls (e.g. axioms) are replaced by their derivatives. This transformation can be seen as an augmentation with a dual computation that generates the derivatives.
Definition at line 16 of file autodiff_eval.cpp.
References augment_().
Referenced by augment_app(), augment_extract(), augment_lam(), augment_pack(), and derive_().
augment_()
const Def * thorin::autodiff::AutoDiffEval::augment_ (const Def * def, Lam * f, Lam * f_diff)
Rewrites the given definition in a lambda environment.
Definition at line 323 of file autodiff_rewrite_inner.cpp.
References augment_app(), augment_extract(), augment_lam(), augment_lit(), augment_pack(), augment_tuple(), augment_var(), thorin::autodiff::autodiff_type_fun(), findAndReplaceAll(), thorin::Pass::index(), thorin::RuntimeCast< Base >::isa(), thorin::Def::isa_nom(), thorin::World::lookup(), thorin::World::name(), thorin::Def::node_name(), thorin::Def::type(), thorin::Pass::world(), and thorin::Def::world().
Referenced by augment(), and augment_pack().
augment_app()
const Def * thorin::autodiff::AutoDiffEval::augment_app (const App * app, Lam * f, Lam * f_diff)
Definition at line 215 of file autodiff_rewrite_inner.cpp.
References thorin::World::app(), thorin::App::arg(), thorin::RuntimeCast< Base >::as(), augment(), thorin::App::callee(), thorin::compose_continuation(), thorin::World::dbg(), thorin::World::debug_dump(), thorin::is_continuation(), thorin::is_open_continuation(), thorin::RuntimeCast< Base >::isa(), thorin::World::nom_lam(), thorin::direct::op_cps2ds_dep(), thorin::Def::type(), thorin::World::type(), thorin::Def::var(), thorin::Pass::world(), and thorin::Def::world().
Referenced by augment_().
augment_extract()
const Def * thorin::autodiff::AutoDiffEval::augment_extract (const Extract * ext, Lam * f, Lam * f_diff)
Definition at line 93 of file autodiff_rewrite_inner.cpp.
References augment(), thorin::World::dbg(), thorin::World::extract(), f_arg_ty, thorin::Pass::index(), thorin::Extract::index(), thorin::World::insert(), thorin::World::nom_lam(), thorin::autodiff::op_zero(), thorin::autodiff::pullback_type(), thorin::Extract::tuple(), thorin::Def::type(), thorin::World::var(), thorin::Pass::world(), and thorin::Def::world().
Referenced by augment_().
augment_lam()
const Def * thorin::autodiff::AutoDiffEval::augment_lam (Lam * lam, Lam * f, Lam * f_diff)
Definition at line 32 of file autodiff_rewrite_inner.cpp.
References augment(), thorin::autodiff::autodiff_type_fun(), thorin::Lam::body(), thorin::World::cn(), thorin::World::dbg(), thorin::Pi::dom(), f_arg_ty, thorin::Lam::filter(), thorin::is_open_continuation(), thorin::Def::name(), thorin::World::nom_lam(), thorin::autodiff::op_autodiff(), thorin::autodiff::pullback_type(), thorin::Lam::type(), thorin::Def::var(), thorin::Pass::world(), thorin::Def::world(), and thorin::autodiff::zero_pullback().
Referenced by augment_().
augment_lit()
const Def * thorin::autodiff::AutoDiffEval::augment_lit (const Lit * lit, Lam * f, Lam *)
Definition at line 19 of file autodiff_rewrite_inner.cpp.
References f_arg_ty, thorin::Def::type(), and thorin::autodiff::zero_pullback().
Referenced by augment_().
augment_pack()
const Def * thorin::autodiff::AutoDiffEval::augment_pack (const Pack * pack, Lam * f, Lam * f_diff)
Definition at line 172 of file autodiff_rewrite_inner.cpp.
References thorin::World::app(), thorin::Def::arity(), thorin::World::arr(), augment(), augment_(), thorin::World::ax(), thorin::Pack::body(), thorin::World::dbg(), thorin::World::extract(), f_arg_ty, thorin::World::nom_lam(), thorin::World::nom_pack(), thorin::direct::op_cps2ds_dep(), thorin::World::pack(), thorin::autodiff::pullback_type(), thorin::World::raw_app(), thorin::Pack::set(), thorin::autodiff::tangent_type_fun(), thorin::Pack::type(), thorin::Pass::world(), and thorin::Def::world().
Referenced by augment_().
augment_tuple()
const Def * thorin::autodiff::AutoDiffEval::augment_tuple (const Tuple * tup, Lam * f, Lam * f_diff)
Definition at line 136 of file autodiff_rewrite_inner.cpp.
References thorin::World::dbg(), f_arg_ty, thorin::World::nom_lam(), thorin::clos::op(), thorin::autodiff::op_sum(), thorin::Def::projs(), thorin::autodiff::pullback_type(), thorin::autodiff::tangent_type_fun(), thorin::World::tuple(), thorin::Def::type(), thorin::World::var(), thorin::Pass::world(), and thorin::Def::world().
Referenced by augment_().
augment_var()
const Def * thorin::autodiff::AutoDiffEval::augment_var (const Var * var, Lam * , Lam *)
helper functions for augment
Definition at line 25 of file autodiff_rewrite_inner.cpp.
Referenced by augment_().
derive()
const Def * thorin::autodiff::AutoDiffEval::derive (const Def * def)
Acts on toplevel autodiff on closed terms:
Replaces lambdas, operators with the appropriate derivatives.
Creates new lambda, calls associate variables, init maps, calls augment.
Definition at line 22 of file autodiff_eval.cpp.
References derive_().
Referenced by rewrite().
derive_()
const Def * thorin::autodiff::AutoDiffEval::derive_ (const Def * def)
Additionally to the derivation, the pullback is registered and the maps are initialized.
Definition at line 8 of file autodiff_rewrite_toplevel.cpp.
References thorin::Def::as_nom(), augment(), thorin::autodiff::autodiff_type_fun_pi(), thorin::World::dbg(), thorin::autodiff::id_pullback(), thorin::World::nom_lam(), thorin::World::tuple(), thorin::Def::type(), thorin::Def::var(), thorin::Pass::world(), thorin::Def::world(), and thorin::autodiff::zero_pullback().
Referenced by derive().
rewrite()
const Def * thorin::autodiff::AutoDiffEval::rewrite (const Def * def) override virtual
Detect autodiff calls.
Reimplemented from thorin::Pass.
Definition at line 28 of file autodiff_eval.cpp.
References derive(), and thorin::Pass::world().
The documentation for this class was generated from the following files:
dialects/autodiff/passes/autodiff_eval.h
dialects/autodiff/auxiliary/autodiff_rewrite_inner.cpp
dialects/autodiff/auxiliary/autodiff_rewrite_toplevel.cpp
dialects/autodiff/passes/autodiff_eval.cpp