Thorin: thorin::fe::Ptrn Class Reference
thorin::fe::Ptrn Class Reference abstract
#include <thorin/fe/ast.h>
Public Member Functions
Ptrn (Loc loc, Sym sym, const Def *type)
Sym sym () const
bool is_anonymous () const
virtual void bind (Scopes &, const Def *) const =0
virtual const Def * type (World &) const =0
Public Member Functions inherited from thorin::fe::AST
AST (Loc loc)
virtual ~AST ()
Loc loc () const
Protected Attributes
Sym sym_
const Def * type_
Detailed Description
Definition at line 33 of file ast.h.
Constructor & Destructor Documentation
Ptrn()
thorin::fe::Ptrn::Ptrn (Loc loc, Sym sym, const Def * type) inline
Definition at line 35 of file ast.h.
Member Function Documentation
bind()
virtual void thorin::fe::Ptrn::bind (Scopes & , const Def *) const pure virtual
Implemented in thorin::fe::IdPtrn, and thorin::fe::TuplePtrn.
Referenced by thorin::fe::TuplePtrn::bind().
is_anonymous()
bool thorin::fe::Ptrn::is_anonymous () const inline
Definition at line 41 of file ast.h.
References thorin::Sym::is_anonymous(), and sym_.
sym()
Sym thorin::fe::Ptrn::sym () const inline
Definition at line 40 of file ast.h.
References sym_.
Referenced by thorin::fe::TuplePtrn::bind(), and thorin::fe::TuplePtrn::type().
type()
virtual const Def * thorin::fe::Ptrn::type (World &) const pure virtual
Implemented in thorin::fe::IdPtrn, and thorin::fe::TuplePtrn.
Referenced by thorin::fe::TuplePtrn::type().
Member Data Documentation
sym_
Sym thorin::fe::Ptrn::sym_ protected
Definition at line 46 of file ast.h.
Referenced by thorin::fe::IdPtrn::bind(), thorin::fe::TuplePtrn::bind(), is_anonymous(), and sym().
type_
const Def* thorin::fe::Ptrn::type_ mutable protected
Definition at line 47 of file ast.h.
Referenced by thorin::fe::IdPtrn::type(), and thorin::fe::TuplePtrn::type().
The documentation for this class was generated from the following file:
/home/runner/work/thorin2/thorin2/thorin/fe/ast.h