Thorin: thorin::fe::Tok Class Reference
thorin::fe::Tok Class Reference
#include <thorin/fe/tok.h>
Public Member Functions
Tok ()
Tok (Loc loc, Tag tag)
Tok (Loc loc, char8_t c8)
Tok (Loc loc, Tag tag, Sym sym)
Tok (Loc loc, u64 u)
Tok (Loc loc, s64 s)
Tok (Loc loc, f64 r)
Tok (Loc loc, const Def *index)
bool isa (Tag tag) const
Tag tag () const
Dbg dbg () const
Loc loc () const
char8_t c8 () const
u64 u () const
Sym sym () const
const Def * index () const
Precedence
enum class Prec { CODE }
static constexpr std::array< Prec, 2 > prec (Prec p)
static Prec prec (const Def *)
Tag
enum class Tag {
CODE ,
K_module ,
K_import ,
K_plugin ,
K_ax ,
K_def ,
K_let ,
K_ret ,
K_Bool ,
K_Nat ,
K_Idx ,
K_extern ,
K_Arr ,
K_Sigma ,
K_Type ,
K_Univ ,
K_pack ,
K_Cn ,
K_Fn ,
K_Pi ,
K_con ,
K_fun ,
K_lam ,
K_cn ,
K_fn ,
K_ff ,
K_tt ,
K_ins ,
L_s ,
L_u ,
L_r ,
M_eof ,
M_char ,
M_str ,
M_id ,
M_ax ,
M_idx ,
D_angle_l ,
D_angle_r ,
D_brace_l ,
D_brace_r ,
D_brckt_l ,
D_brckt_r ,
D_paren_l ,
D_paren_r ,
D_quote_l ,
D_quote_r ,
T_Pi ,
T_arrow ,
T_assign ,
T_at ,
T_backtick ,
T_bang ,
T_bot ,
T_top ,
T_box ,
T_colon ,
T_colon_colon ,
T_comma ,
T_dollar ,
T_dot ,
T_extract ,
T_lm ,
T_semicolon ,
T_star ,
Nil
}
static std::string_view tag2str (Tok::Tag)
static constexpr Tok::Tag delim_l2r (Tag tag)
Detailed Description
Definition at line 109 of file tok.h.
Member Enumeration Documentation
Prec
enum class thorin::fe::Tok::Prec strong
Enumerator
CODE
Definition at line 113 of file tok.h.
Tag
enum class thorin::fe::Tok::Tag strong
Enumerator
CODE
K_module
K_import
K_plugin
K_ax
K_def
K_let
K_ret
K_Bool
K_Nat
K_Idx
K_extern
K_Arr
K_Sigma
K_Type
K_Univ
K_pack
K_Cn
K_Fn
K_Pi
K_con
K_fun
K_lam
K_cn
K_fn
K_ff
K_tt
K_ins
L_s
L_u
L_r
M_eof
M_char
M_str
M_id
M_ax
M_idx
D_angle_l
D_angle_r
D_brace_l
D_brace_r
D_brckt_l
D_brckt_r
D_paren_l
D_paren_r
D_quote_l
D_quote_r
T_Pi
T_arrow
T_assign
T_at
T_backtick
T_bang
T_bot
T_top
T_box
T_colon
T_colon_colon
T_comma
T_dollar
T_dot
T_extract
T_lm
T_semicolon
T_star
Nil
Definition at line 133 of file tok.h.
Constructor & Destructor Documentation
Tok() [1/8]
thorin::fe::Tok::Tok () inline
Definition at line 145 of file tok.h.
Tok() [2/8]
thorin::fe::Tok::Tok (Loc loc, Tag tag) inline
Definition at line 146 of file tok.h.
Tok() [3/8]
thorin::fe::Tok::Tok (Loc loc, char8_t c8) inline
Definition at line 149 of file tok.h.
Tok() [4/8]
thorin::fe::Tok::Tok (Loc loc, Tag tag, Sym sym) inline
Definition at line 153 of file tok.h.
Tok() [5/8]
thorin::fe::Tok::Tok (Loc loc, u64 u) inline
Definition at line 159 of file tok.h.
Tok() [6/8]
thorin::fe::Tok::Tok (Loc loc, s64 s) inline
Definition at line 163 of file tok.h.
Tok() [7/8]
thorin::fe::Tok::Tok (Loc loc, f64 r) inline
Definition at line 167 of file tok.h.
Tok() [8/8]
thorin::fe::Tok::Tok (Loc loc, const Def * index) inline
Definition at line 171 of file tok.h.
Member Function Documentation
c8()
char8_t thorin::fe::Tok::c8 () const inline
Definition at line 181 of file tok.h.
dbg()
Dbg thorin::fe::Tok::dbg () const inline
Definition at line 178 of file tok.h.
delim_l2r()
static constexpr Tok::Tag thorin::fe::Tok::delim_l2r (Tag tag) inline static constexpr
Definition at line 140 of file tok.h.
index()
const Def * thorin::fe::Tok::index () const inline
Definition at line 184 of file tok.h.
References isa().
isa()
bool thorin::fe::Tok::isa (Tag tag) const inline
Definition at line 176 of file tok.h.
Referenced by index(), sym(), and u().
loc()
Loc thorin::fe::Tok::loc () const inline
Definition at line 179 of file tok.h.
References loc(), and sym().
Referenced by loc().
prec() [1/2]
fe::Tok::Prec thorin::fe::Tok::prec (const Def * def) static
Definition at line 30 of file tok.cpp.
References thorin::RuntimeCast< B >::isa().
prec() [2/2]
static constexpr std::array< Prec, 2 > thorin::fe::Tok::prec (Prec p) inline static constexpr
Definition at line 119 of file tok.h.
References CODE, THORIN_PREC, and thorin::unreachable().
sym()
Sym thorin::fe::Tok::sym () const inline
Definition at line 183 of file tok.h.
References isa().
Referenced by loc().
tag()
Tag thorin::fe::Tok::tag () const inline
Definition at line 177 of file tok.h.
References tag().
Referenced by tag(), and tag2str().
tag2str()
std::string_view thorin::fe::Tok::tag2str (Tok::Tag tag) static
Definition at line 10 of file tok.cpp.
References CODE, tag(), THORIN_KEY, THORIN_LIT, THORIN_TOK, and thorin::unreachable().
u()
u64 thorin::fe::Tok::u () const inline
Definition at line 182 of file tok.h.
References isa().
The documentation for this class was generated from the following files:
thorin/fe/tok.h
thorin/fe/tok.cpp