Thorin: thorin::ast::Decl Class Reference
thorin::ast::Decl Class Reference
#include <thorin/ast/ast.h>
Public Member Functions
Ref def () const
Public Member Functions inherited from thorin::ast::Node
Loc loc () const
virtual std::ostream & stream (Tab &, std::ostream &) const =0
void dump () const
Protected Member Functions
Decl (Loc loc)
Protected Member Functions inherited from thorin::ast::Node
Node (Loc loc)
virtual ~Node ()
Protected Attributes
Ref def_ = nullptr
Detailed Description
Definition at line 145 of file ast.h.
Constructor & Destructor Documentation
Decl()
thorin::ast::Decl::Decl (Loc loc) inline protected
Definition at line 147 of file ast.h.
Member Function Documentation
def()
Ref thorin::ast::Decl::def () const inline
Definition at line 151 of file ast.h.
References def_.
Referenced by thorin::ast::IdExpr::emit_(), thorin::ast::Ptrn::emit_value(), and thorin::ast::TuplePtrn::emit_value_().
Member Data Documentation
def_
Ref thorin::ast::Decl::def_ = nullptr mutable protected
Definition at line 154 of file ast.h.
Referenced by def(), and thorin::ast::Ptrn::emit_value().
The documentation for this class was generated from the following file:
include/thorin/ast/ast.h