MimIR: mim::ast::Tok Class Reference
mim::ast::Tok Class Reference
#include <mim/ast/tok.h>
Public Member Functions
Tok ()
Tok (Loc loc, Tag tag)
Tok (Loc loc, char8_t c)
Tok (Loc loc, uint64_t u)
Tok (Loc loc, int64_t s)
Tok (Loc loc, double d)
Tok (Loc loc, const Lit *i)
Tok (Loc loc, Tag tag, Sym sym)
bool isa (Tag tag) const
Tag tag () const
Dbg dbg () const
Loc loc () const
operator bool () const
const Lit * lit_i () const
char8_t lit_c () const
uint64_t lit_u () const
Sym sym () const
std::string str () const
Friends
std::ostream & operator<< (std::ostream &os, Tok tok)
std::ostream & operator<< (std::ostream &os, Tok::Tag tag)
Tag
enum class Tag {
Nil ,
CODE ,
K_Bool ,
K_Cn ,
K_Fn ,
K_I1 ,
K_I16 ,
K_I32 ,
K_I64 ,
K_I8 ,
K_Idx ,
K_Nat ,
K_Type ,
K_Univ ,
K_and ,
K_as ,
K_axm ,
K_ccon ,
K_cfun ,
K_cn ,
K_con ,
K_end ,
K_extern ,
K_ff ,
K_fn ,
K_fun ,
K_i1 ,
K_i16 ,
K_i32 ,
K_i64 ,
K_i8 ,
K_import ,
K_inj ,
K_ins ,
K_lam ,
K_let ,
K_match ,
K_module ,
K_norm ,
K_plugin ,
K_rec ,
K_ret ,
K_rule ,
K_tt ,
K_when ,
K_where ,
K_with ,
EoF ,
L_s ,
L_u ,
L_i ,
L_f ,
L_c ,
L_str ,
M_id ,
M_anx ,
D_angle_l ,
D_angle_r ,
D_brace_l ,
D_brace_r ,
D_brckt_l ,
D_brckt_r ,
D_curly_l ,
D_curly_r ,
D_paren_l ,
D_paren_r ,
D_quote_l ,
D_quote_r ,
T_arrow ,
T_fat_arrow ,
T_assign ,
T_at ,
T_bot ,
T_top ,
T_box ,
T_colon ,
T_comma ,
T_dollar ,
T_dot ,
T_extract ,
T_lm ,
T_semicolon ,
T_star ,
T_union ,
T_pipe
}
static const char * tag2str (Tok::Tag)
static constexpr Tok::Tag delim_l2r (Tag tag)
Detailed Description
Definition at line 114 of file tok.h.
Member Enumeration Documentation
Tag
enum class mim::ast::Tok::Tag strong
Enumerator
Nil
CODE
K_Bool
K_Cn
K_Fn
K_I1
K_I16
K_I32
K_I64
K_I8
K_Idx
K_Nat
K_Type
K_Univ
K_and
K_as
K_axm
K_ccon
K_cfun
K_cn
K_con
K_end
K_extern
K_ff
K_fn
K_fun
K_i1
K_i16
K_i32
K_i64
K_i8
K_import
K_inj
K_ins
K_lam
K_let
K_match
K_module
K_norm
K_plugin
K_rec
K_ret
K_rule
K_tt
K_when
K_where
K_with
EoF
L_s
L_u
L_i
L_f
L_c
L_str
M_id
M_anx
D_angle_l
D_angle_r
D_brace_l
D_brace_r
D_brckt_l
D_brckt_r
D_curly_l
D_curly_r
D_paren_l
D_paren_r
D_quote_l
D_quote_r
T_arrow
T_fat_arrow
T_assign
T_at
T_bot
T_top
T_box
T_colon
T_comma
T_dollar
T_dot
T_extract
T_lm
T_semicolon
T_star
T_union
T_pipe
Definition at line 118 of file tok.h.
Constructor & Destructor Documentation
Tok() [1/8]
mim::ast::Tok::Tok () inline
Definition at line 131 of file tok.h.
Referenced by operator<<.
Tok() [2/8]
mim::ast::Tok::Tok (Loc loc, Tag tag) inline
Definition at line 132 of file tok.h.
References loc(), and tag().
Tok() [3/8]
mim::ast::Tok::Tok (Loc loc, char8_t c) inline
Definition at line 135 of file tok.h.
References L_c, and loc().
Tok() [4/8]
mim::ast::Tok::Tok (Loc loc, uint64_t u) inline
Definition at line 139 of file tok.h.
References L_u, and loc().
Tok() [5/8]
mim::ast::Tok::Tok (Loc loc, int64_t s) inline
Definition at line 143 of file tok.h.
References L_s, and loc().
Tok() [6/8]
mim::ast::Tok::Tok (Loc loc, double d) inline
Definition at line 147 of file tok.h.
References L_f, and loc().
Tok() [7/8]
mim::ast::Tok::Tok (Loc loc, const Lit * i) inline
Definition at line 151 of file tok.h.
References L_i, and loc().
Tok() [8/8]
mim::ast::Tok::Tok (Loc loc, Tag tag, Sym sym) inline
Definition at line 155 of file tok.h.
References loc(), sym(), and tag().
Member Function Documentation
dbg()
Dbg mim::ast::Tok::dbg () const inline
Definition at line 164 of file tok.h.
References loc(), and sym().
delim_l2r()
static constexpr Tok::Tag mim::ast::Tok::delim_l2r (Tag tag) inline static constexpr
Definition at line 126 of file tok.h.
References tag().
Referenced by mim::ast::TuplePtrn::delim_r().
isa()
bool mim::ast::Tok::isa (Tag tag) const inline
Definition at line 162 of file tok.h.
References tag().
Referenced by lit_c(), lit_i(), lit_u(), operator<<, and sym().
lit_c()
char8_t mim::ast::Tok::lit_c () const inline
Definition at line 169 of file tok.h.
References isa().
lit_i()
const Lit * mim::ast::Tok::lit_i () const inline
Definition at line 168 of file tok.h.
References isa().
Referenced by mim::ast::LitExpr::emit_().
lit_u()
uint64_t mim::ast::Tok::lit_u () const inline
Definition at line 170 of file tok.h.
References isa().
Referenced by mim::ast::LitExpr::stream().
loc()
Loc mim::ast::Tok::loc () const inline
Definition at line 165 of file tok.h.
Referenced by dbg(), Tok(), Tok(), Tok(), Tok(), Tok(), Tok(), and Tok().
operator bool()
mim::ast::Tok::operator bool () const inline explicit
Definition at line 166 of file tok.h.
str()
std::string mim::ast::Tok::str () const
Definition at line 22 of file tok.cpp.
sym()
Sym mim::ast::Tok::sym () const inline
Definition at line 171 of file tok.h.
References isa().
Referenced by dbg(), operator<<, and Tok().
tag()
Tag mim::ast::Tok::tag () const inline
Definition at line 163 of file tok.h.
Referenced by delim_l2r(), isa(), operator<<, operator<<, tag2str(), Tok(), and Tok().
tag2str()
const char * mim::ast::Tok::tag2str (Tok::Tag tag) static
Definition at line 10 of file tok.cpp.
References CODE, MIM_KEY, MIM_TOK, and tag().
Referenced by operator<<, and operator<<.
Friends And Related Symbol Documentation
operator<< [1/2]
std::ostream & operator<< (std::ostream & os, Tok tok) friend
Definition at line 30 of file tok.cpp.
References isa(), sym(), tag(), tag2str(), and Tok().
operator<< [2/2]
std::ostream & operator<< (std::ostream & os, Tok::Tag tag) friend
Definition at line 176 of file tok.h.
References tag(), and tag2str().
The documentation for this class was generated from the following files:
include/mim/ast/tok.h
src/mim/ast/tok.cpp