Thorin: thorin::Emitter< Value, Type, BB, Child > Class Template Reference
thorin::Emitter< Value, Type, BB, Child > Class Template Reference
#include <thorin/be/emitter.h>
Protected Member Functions
Emitter (World &world, Stream &stream)
World & world () const
const Scope & scope () const
Stream & stream () const
Value emit (const Def *def)
Recursively emits code. mem -typed Defs return sth that is !child().is_valid(value) - this variant asserts in this case.
Value emit_unsafe (const Def *def)
As above but returning !child().is_valid(value) is permitted.
void emit_module ()
void emit_scope (const Scope &scope)
Protected Attributes
World & world_
const Scope * scope_ = nullptr
Stream & stream_
Scheduler scheduler_
DefMap< Value > locals_
DefMap< Value > globals_
DefMap< Type > types_
LamMap< BB > lam2bb_
Lam * entry_ = nullptr
Detailed Description
template<class Value, class Type, class BB, class Child>
class thorin::Emitter< Value, Type, BB, Child >
Definition at line 10 of file emitter.h.
Constructor & Destructor Documentation
Emitter()
template<class Value , class Type , class BB , class Child > thorin::Emitter< Value, Type, BB, Child >::Emitter (World & world, Stream & stream) inline protected
Definition at line 23 of file emitter.h.
Member Function Documentation
emit()
template<class Value , class Type , class BB , class Child > Value thorin::Emitter< Value, Type, BB, Child >::emit (const Def * def) inline protected
Recursively emits code. mem -typed Defs return sth that is !child().is_valid(value) - this variant asserts in this case.
Definition at line 33 of file emitter.h.
References thorin::Emitter< Value, Type, BB, Child >::emit_unsafe(), and thorin::utf8::is_valid().
emit_module()
template<class Value , class Type , class BB , class Child > void thorin::Emitter< Value, Type, BB, Child >::emit_module () inline protected
Definition at line 48 of file emitter.h.
References thorin::Emitter< Value, Type, BB, Child >::emit_scope(), thorin::Emitter< Value, Type, BB, Child >::scope(), and thorin::Emitter< Value, Type, BB, Child >::world().
emit_scope()
template<class Value , class Type , class BB , class Child > void thorin::Emitter< Value, Type, BB, Child >::emit_scope (const Scope & scope) inline protected
Definition at line 52 of file emitter.h.
References thorin::Def::as_nom(), thorin::Scope::entry(), thorin::Emitter< Value, Type, BB, Child >::entry_, thorin::Scope::exit(), thorin::Lam::is_basicblock(), thorin::Def::is_set(), thorin::Def::isa_nom(), thorin::Emitter< Value, Type, BB, Child >::lam2bb_, thorin::Emitter< Value, Type, BB, Child >::locals_, thorin::Lam::ret_var(), thorin::schedule(), thorin::Emitter< Value, Type, BB, Child >::scheduler_, thorin::Emitter< Value, Type, BB, Child >::scope(), and thorin::Emitter< Value, Type, BB, Child >::scope_.
Referenced by thorin::Emitter< Value, Type, BB, Child >::emit_module().
emit_unsafe()
template<class Value , class Type , class BB , class Child > Value thorin::Emitter< Value, Type, BB, Child >::emit_unsafe (const Def * def) inline protected
As above but returning !child().is_valid(value) is permitted.
Definition at line 40 of file emitter.h.
References thorin::Emitter< Value, Type, BB, Child >::globals_, and thorin::Emitter< Value, Type, BB, Child >::locals_.
Referenced by thorin::Emitter< Value, Type, BB, Child >::emit().
scope()
template<class Value , class Type , class BB , class Child > const Scope & thorin::Emitter< Value, Type, BB, Child >::scope () const inline protected
Definition at line 29 of file emitter.h.
References thorin::Emitter< Value, Type, BB, Child >::scope_.
Referenced by thorin::Emitter< Value, Type, BB, Child >::emit_module(), and thorin::Emitter< Value, Type, BB, Child >::emit_scope().
stream()
template<class Value , class Type , class BB , class Child > Stream & thorin::Emitter< Value, Type, BB, Child >::stream () const inline protected
Definition at line 30 of file emitter.h.
References thorin::Emitter< Value, Type, BB, Child >::stream_.
world()
template<class Value , class Type , class BB , class Child > World & thorin::Emitter< Value, Type, BB, Child >::world () const inline protected
Definition at line 28 of file emitter.h.
References thorin::Emitter< Value, Type, BB, Child >::world_.
Referenced by thorin::Emitter< Value, Type, BB, Child >::emit_module().
Member Data Documentation
entry_
template<class Value , class Type , class BB , class Child > Lam* thorin::Emitter< Value, Type, BB, Child >::entry_ = nullptr protected
Definition at line 97 of file emitter.h.
Referenced by thorin::Emitter< Value, Type, BB, Child >::emit_scope().
globals_
template<class Value , class Type , class BB , class Child > DefMap<Value> thorin::Emitter< Value, Type, BB, Child >::globals_ protected
Definition at line 94 of file emitter.h.
Referenced by thorin::Emitter< Value, Type, BB, Child >::emit_unsafe().
lam2bb_
template<class Value , class Type , class BB , class Child > LamMap<BB> thorin::Emitter< Value, Type, BB, Child >::lam2bb_ protected
Definition at line 96 of file emitter.h.
Referenced by thorin::Emitter< Value, Type, BB, Child >::emit_scope().
locals_
template<class Value , class Type , class BB , class Child > DefMap<Value> thorin::Emitter< Value, Type, BB, Child >::locals_ protected
Definition at line 93 of file emitter.h.
Referenced by thorin::Emitter< Value, Type, BB, Child >::emit_scope(), and thorin::Emitter< Value, Type, BB, Child >::emit_unsafe().
scheduler_
template<class Value , class Type , class BB , class Child > Scheduler thorin::Emitter< Value, Type, BB, Child >::scheduler_ protected
Definition at line 92 of file emitter.h.
Referenced by thorin::Emitter< Value, Type, BB, Child >::emit_scope().
scope_
template<class Value , class Type , class BB , class Child > const Scope* thorin::Emitter< Value, Type, BB, Child >::scope_ = nullptr protected
Definition at line 90 of file emitter.h.
Referenced by thorin::Emitter< Value, Type, BB, Child >::emit_scope(), and thorin::Emitter< Value, Type, BB, Child >::scope().
stream_
template<class Value , class Type , class BB , class Child > Stream& thorin::Emitter< Value, Type, BB, Child >::stream_ protected
Definition at line 91 of file emitter.h.
Referenced by thorin::Emitter< Value, Type, BB, Child >::stream().
types_
template<class Value , class Type , class BB , class Child > DefMap<Type> thorin::Emitter< Value, Type, BB, Child >::types_ protected
Definition at line 95 of file emitter.h.
world_
template<class Value , class Type , class BB , class Child > World& thorin::Emitter< Value, Type, BB, Child >::world_ protected
Definition at line 89 of file emitter.h.
Referenced by thorin::Emitter< Value, Type, BB, Child >::world().
The documentation for this class was generated from the following file:
thorin/be/emitter.h