Thorin: thorin::Match< Id, D > Class Template Reference
thorin::Match< Id, D > Class Template Reference
#include <thorin/axiom.h>
Public Member Functions
Match ()=default
Match (const Axiom *axiom, const D *def)
getters
const Axiom * axiom () const
const D * operator-> () const
operator const D * () const
operator bool ()
Axiom name
auto dialect () const
auto tag () const
auto sub () const
auto base () const
auto id () const
Axiom::flags cast to Id.
Detailed Description
template<class Id, class D>
class thorin::Match< Id, D >
Definition at line 114 of file axiom.h.
Constructor & Destructor Documentation
Match() [1/2]
template<class Id , class D > thorin::Match< Id, D >::Match () default
Match() [2/2]
template<class Id , class D > thorin::Match< Id, D >::Match (const Axiom * axiom, const D * def) inline
Definition at line 120 of file axiom.h.
Member Function Documentation
axiom()
template<class Id , class D > const Axiom * thorin::Match< Id, D >::axiom () const inline
Definition at line 126 of file axiom.h.
Referenced by thorin::Match< Id, D >::base(), thorin::Match< Id, D >::dialect(), thorin::Match< Id, D >::id(), thorin::Match< Id, D >::sub(), and thorin::Match< Id, D >::tag().
base()
template<class Id , class D > auto thorin::Match< Id, D >::base () const inline
See also
Axiom::base.
Definition at line 137 of file axiom.h.
References thorin::Match< Id, D >::axiom(), and thorin::Axiom::sub().
dialect()
template<class Id , class D > auto thorin::Match< Id, D >::dialect () const inline
See also
Axiom::dialect.
Definition at line 134 of file axiom.h.
References thorin::Match< Id, D >::axiom(), and thorin::Axiom::dialect().
id()
template<class Id , class D > auto thorin::Match< Id, D >::id () const inline
Axiom::flags cast to Id.
Definition at line 138 of file axiom.h.
References thorin::Match< Id, D >::axiom().
operator bool()
template<class Id , class D > thorin::Match< Id, D >::operator bool () inline explicit
Definition at line 129 of file axiom.h.
operator const D *()
template<class Id , class D > thorin::Match< Id, D >::operator const D * () const inline
Definition at line 128 of file axiom.h.
operator->()
template<class Id , class D > const D * thorin::Match< Id, D >::operator-> () const inline
Definition at line 127 of file axiom.h.
sub()
template<class Id , class D > auto thorin::Match< Id, D >::sub () const inline
See also
Axiom::sub.
Definition at line 136 of file axiom.h.
References thorin::Match< Id, D >::axiom(), and thorin::Axiom::sub().
tag()
template<class Id , class D > auto thorin::Match< Id, D >::tag () const inline
See also
Axiom::tag.
Definition at line 135 of file axiom.h.
References thorin::Match< Id, D >::axiom(), and thorin::Axiom::tag().
The documentation for this class was generated from the following file:
thorin/axiom.h