MimIR: mim::Scheduler Class Reference
mim::Scheduler Class Reference
#include <mim/analyses/schedule.h>
Public Member Functions
Construction
Scheduler ()=default
Scheduler (const Nest &)
Scheduler (const Scheduler &)=delete
Scheduler (Scheduler &&other) noexcept
Scheduler & operator= (Scheduler other) noexcept
Getters
World & world ()
const Nest & nest () const
Def * root () const
const CFG & cfg () const
const CFNode * cfg (Def *mut) const
const DomTree & domtree () const
const Uses & uses (const Def *def) const
Compute Schedules
Def * early (const Def *)
Def * late (Def *curr, const Def *)
Def * smart (Def *curr, const Def *)
Friends
void swap (Scheduler &s1, Scheduler &s2) noexcept
Schedule Mutabales
Order of Mutables within a Scope.
using Schedule = std::vector<Def*>
static Schedule schedule (const CFG &)
Detailed Description
Definition at line 48 of file schedule.h.
Member Typedef Documentation
Schedule
using mim::Scheduler::Schedule = std::vector<Def*>
Definition at line 86 of file schedule.h.
Constructor & Destructor Documentation
Scheduler() [1/4]
mim::Scheduler::Scheduler () default
Scheduler() [2/4]
mim::Scheduler::Scheduler (const Nest & n) explicit
Definition at line 14 of file schedule.cpp.
References mim::assert_emplace(), cfg(), mim::Def::isa_mut(), nest(), and mim::Def::type().
Scheduler() [3/4]
mim::Scheduler::Scheduler (const Scheduler &) delete
Scheduler() [4/4]
mim::Scheduler::Scheduler (Scheduler && other) inline noexcept
Definition at line 55 of file schedule.h.
References swap.
Member Function Documentation
cfg() [1/2]
const CFG & mim::Scheduler::cfg () const inline
Definition at line 67 of file schedule.h.
Referenced by Scheduler().
cfg() [2/2]
const CFNode * mim::Scheduler::cfg (Def * mut) const inline
Definition at line 68 of file schedule.h.
References cfg().
Referenced by cfg().
domtree()
const DomTree & mim::Scheduler::domtree () const inline
Definition at line 69 of file schedule.h.
early()
Def * mim::Scheduler::early (const Def * def)
Definition at line 49 of file schedule.cpp.
References mim::Def::deps(), mim::Def::has_const_dep(), and mim::Def::isa_mut().
late()
Def * mim::Scheduler::late (Def * curr, const Def * def)
Definition at line 65 of file schedule.cpp.
References mim::Def::has_const_dep(), and mim::Def::isa_mut().
nest()
const Nest & mim::Scheduler::nest () const inline
Definition at line 65 of file schedule.h.
Referenced by Scheduler(), and world().
operator=()
Scheduler & mim::Scheduler::operator= (Scheduler other) inline noexcept
Definition at line 59 of file schedule.h.
References swap.
root()
Def * mim::Scheduler::root () const inline
Definition at line 66 of file schedule.h.
References mim::Nest::Node::mut(), and mim::Nest::root().
schedule()
Scheduler::Schedule mim::Scheduler::schedule (const CFG & cfg) static
Definition at line 114 of file schedule.cpp.
References mim::CFG::reverse_post_order().
Referenced by mim::ll::Emitter::finalize(), and mim::Emitter< Value, Type, BB, Child >::visit().
smart()
Def * mim::Scheduler::smart (Def * curr, const Def * def)
Definition at line 86 of file schedule.cpp.
uses()
const Uses & mim::Scheduler::uses (const Def * def) const inline
Definition at line 70 of file schedule.h.
world()
World & mim::Scheduler::world () inline
Definition at line 64 of file schedule.h.
References nest(), and mim::Nest::world().
Friends And Related Symbol Documentation
swap
void swap (Scheduler & s1, Scheduler & s2) friend
Definition at line 90 of file schedule.h.
Referenced by operator=(), and Scheduler().
The documentation for this class was generated from the following files:
include/mim/analyses/schedule.h
src/mim/analyses/schedule.cpp