MimIR: mim::ast::Module Class Reference
mim::ast::Module Class Reference
#include <mim/ast/ast.h>
Public Member Functions
Module (Loc loc, Ptrs< Import > &&imports, Ptrs< ValDecl > &&decls)
const auto & implicit_imports () const
const auto & imports () const
const auto & decls () const
void add_implicit_imports (Ptrs< Import > &&imports) const
void compile (AST &) const
void bind (AST &) const
void bind (Scopes &) const
void emit (AST &) const
void emit (Emitter &) const
std::ostream & stream (Tab &, std::ostream &) const override
Public Member Functions inherited from mim::ast::Node
Loc loc () const
void dump () const
Additional Inherited Members
Protected Member Functions inherited from mim::ast::Node
Node (Loc loc)
virtual ~Node ()
Detailed Description
Definition at line 1074 of file ast.h.
Constructor & Destructor Documentation
Module()
mim::ast::Module::Module (Loc loc, Ptrs< Import > && imports, Ptrs< ValDecl > && decls) inline
Definition at line 1076 of file ast.h.
References decls(), imports(), mim::ast::Node::loc(), and mim::ast::Node::Node().
Member Function Documentation
add_implicit_imports()
void mim::ast::Module::add_implicit_imports (Ptrs< Import > && imports) const inline
Definition at line 1085 of file ast.h.
References imports().
bind() [1/2]
void mim::ast::Module::bind (AST & ast) const
Definition at line 77 of file bind.cpp.
References bind().
Referenced by mim::ast::Import::bind(), bind(), and compile().
bind() [2/2]
void mim::ast::Module::bind (Scopes & s) const
Definition at line 82 of file bind.cpp.
References decls(), implicit_imports(), and imports().
compile()
void mim::ast::Module::compile (AST & ast) const
Definition at line 183 of file ast.cpp.
References bind(), and emit().
decls()
const auto & mim::ast::Module::decls () const inline
Definition at line 1083 of file ast.h.
Referenced by bind(), emit(), Module(), and stream().
emit() [1/2]
void mim::ast::Module::emit (AST & ast) const
Definition at line 38 of file emit.cpp.
References emit().
Referenced by compile(), mim::ast::Import::emit(), and emit().
emit() [2/2]
void mim::ast::Module::emit (Emitter & e) const
Definition at line 43 of file emit.cpp.
References decls(), implicit_imports(), imports(), and mim::ast::Node::loc().
implicit_imports()
const auto & mim::ast::Module::implicit_imports () const inline
Definition at line 1081 of file ast.h.
Referenced by bind(), and emit().
imports()
const auto & mim::ast::Module::imports () const inline
Definition at line 1082 of file ast.h.
Referenced by add_implicit_imports(), bind(), emit(), Module(), and stream().
stream()
std::ostream & mim::ast::Module::stream (Tab & tab, std::ostream & os) const override virtual
Implements mim::ast::Node.
Definition at line 43 of file stream.cpp.
References decls(), imports(), and mim::Tab::println().
The documentation for this class was generated from the following files:
include/mim/ast/ast.h
src/mim/ast/ast.cpp
src/mim/ast/bind.cpp
src/mim/ast/emit.cpp
src/mim/ast/stream.cpp