MimIR: mim::Rewriter Class Reference
mim::Rewriter Class Reference
Recurseivly rebuilds part of a program into the provided World w.r.t. Rewriter::map.
#include <mim/rewrite.h>
Public Member Functions
Construction & Destruction
Rewriter (std::unique_ptr< World > &&ptr)
Rewriter (World &world)
virtual ~Rewriter ()=default
void reset (std::unique_ptr< World > &&ptr)
void reset ()
Getters
World & world ()
Push / Pop
virtual void push ()
virtual void pop ()
Map / Lookup
Map old_def to new_def and returns new_def.
virtual const Def * map (const Def *old_def, const Def *new_def)
const Def * map (const Def *old_def, Defs new_defs)
const Def * map (Defs old_defs, const Def *new_def)
const Def * map (Defs old_defs, Defs new_defs)
virtual const Def * lookup (const Def *old_def)
Lookup old_def by searching in reverse through the stack of maps.
rewrite
Recursively rewrite old Defs.
virtual const Def * rewrite (const Def *)
virtual const Def * rewrite_imm (const Def *)
virtual const Def * rewrite_mut (Def *)
virtual const Def * rewrite_stub (Def *, Def *)
virtual DefVec rewrite (Defs)
virtual const Def * rewrite_imm_Seq (const Seq *seq)
virtual const Def * rewrite_mut_Seq (Seq *seq)
Protected Attributes
std::deque< Def2Def > old2news_
Friends
void swap (Rewriter &rw1, Rewriter &rw2) noexcept
Detailed Description
Recurseivly rebuilds part of a program into the provided World w.r.t. Rewriter::map.
This World may be different than the World we started with.
Definition at line 18 of file rewrite.h.
Constructor & Destructor Documentation
Rewriter() [1/2]
mim::Rewriter::Rewriter (std::unique_ptr< World > && ptr) inline
Definition at line 22 of file rewrite.h.
References mim::get(), and push().
Referenced by mim::RWPhase::RWPhase(), mim::RWPhase::RWPhase(), swap, mim::VarRewriter::swap, mim::Zonker::swap, mim::VarRewriter::VarRewriter(), mim::VarRewriter::VarRewriter(), and mim::Zonker::Zonker().
Rewriter() [2/2]
mim::Rewriter::Rewriter (World & world) inline
Definition at line 27 of file rewrite.h.
References push(), and world().
~Rewriter()
virtual mim::Rewriter::~Rewriter () virtual default
Member Function Documentation
lookup()
virtual const Def * mim::Rewriter::lookup (const Def * old_def) inline virtual
Lookup old_def by searching in reverse through the stack of maps.
Returns
nullptr if nothing was found.
Reimplemented in mim::Zonker.
Definition at line 69 of file rewrite.h.
References old2news_.
Referenced by rewrite(), and mim::VarRewriter::rewrite().
map() [1/4]
virtual const Def * mim::Rewriter::map (const Def * old_def, const Def * new_def) inline virtual
Reimplemented in mim::Zonker.
Definition at line 59 of file rewrite.h.
References old2news_.
Referenced by mim::VarRewriter::add(), rewrite_imm(), mim::BetaRedPhase::rewrite_imm_App(), mim::plug::affine::phase::LowerFor::rewrite_imm_App(), mim::SCCP::rewrite_imm_App(), mim::RetWrap::rewrite_mut_Lam(), rewrite_mut_Seq(), and rewrite_stub().
map() [2/4]
const Def * mim::Rewriter::map (const Def * old_def, Defs new_defs)
Definition at line 17 of file rewrite.cpp.
References old2news_, mim::World::tuple(), and world().
map() [3/4]
const Def * mim::Rewriter::map (Defs old_defs, const Def * new_def)
Definition at line 20 of file rewrite.cpp.
References old2news_, mim::World::tuple(), and world().
map() [4/4]
const Def * mim::Rewriter::map (Defs old_defs, Defs new_defs)
Definition at line 23 of file rewrite.cpp.
References old2news_, mim::World::tuple(), and world().
pop()
virtual void mim::Rewriter::pop () inline virtual
Reimplemented in mim::VarRewriter.
Definition at line 53 of file rewrite.h.
References old2news_.
Referenced by mim::VarRewriter::pop(), reset(), mim::plug::affine::phase::LowerFor::rewrite_imm_App(), and rewrite_mut_Seq().
push()
virtual void mim::Rewriter::push () inline virtual
Reimplemented in mim::VarRewriter.
Definition at line 52 of file rewrite.h.
References old2news_.
Referenced by mim::VarRewriter::push(), reset(), mim::plug::affine::phase::LowerFor::rewrite_imm_App(), rewrite_mut_Seq(), Rewriter(), and Rewriter().
reset() [1/2]
void mim::Rewriter::reset () inline
Definition at line 38 of file rewrite.h.
References old2news_, pop(), and push().
Referenced by reset().
reset() [2/2]
void mim::Rewriter::reset (std::unique_ptr< World > && ptr) inline
Definition at line 33 of file rewrite.h.
References reset().
rewrite() [1/2]
const Def * mim::Rewriter::rewrite (const Def * old_def) virtual
Reimplemented in mim::EtaExpPhase, mim::ReplManPhase, mim::RetWrap, mim::VarRewriter, and mim::Zonker.
Definition at line 27 of file rewrite.cpp.
References mim::Def::dbg(), mim::Def::isa_mut(), lookup(), rewrite_imm(), and rewrite_mut().
Referenced by mim::EtaExpPhase::rewrite(), mim::ReplManPhase::rewrite(), mim::RetWrap::rewrite(), rewrite(), mim::Zonker::rewrite(), mim::RWPhase::rewrite_annex(), mim::PrefixCleanup::rewrite_external(), mim::RWPhase::rewrite_external(), mim::BetaRedPhase::rewrite_imm_App(), mim::plug::affine::phase::LowerFor::rewrite_imm_App(), mim::plug::matrix::LowerMatrixLowLevel::rewrite_imm_App(), mim::SCCP::rewrite_imm_App(), rewrite_imm_Seq(), rewrite_mut_Seq(), and rewrite_stub().
rewrite() [2/2]
DefVec mim::Rewriter::rewrite (Defs ops) virtual
Definition at line 60 of file rewrite.cpp.
References rewrite().
rewrite_imm()
const Def * mim::Rewriter::rewrite_imm (const Def * old_def) virtual
Definition at line 39 of file rewrite.cpp.
References CODE_IMM, map(), MIM_IMM_NODE, and mim::Def::node().
Referenced by rewrite(), and mim::VarRewriter::rewrite().
rewrite_imm_Seq()
const Def * mim::Rewriter::rewrite_imm_Seq (const Seq * seq) virtual
Definition at line 134 of file rewrite.cpp.
References mim::Def::arity(), mim::Seq::body(), mim::Def::is_intro(), mim::Lit::isa(), mim::World::prod(), rewrite(), mim::World::seq(), and world().
rewrite_mut()
const Def * mim::Rewriter::rewrite_mut (Def * old_mut) virtual
Reimplemented in mim::VarRewriter, and mim::Zonker.
Definition at line 48 of file rewrite.cpp.
References CODE_MUT, MIM_MUT_NODE, and mim::Def::node().
Referenced by rewrite(), and mim::VarRewriter::rewrite_mut().
rewrite_mut_Seq()
const Def * mim::Rewriter::rewrite_mut_Seq (Seq * seq) virtual
Definition at line 140 of file rewrite.cpp.
References mim::Def::arity(), mim::Def::as_mut(), mim::Seq::body(), mim::Def::has_var(), mim::Def::is_intro(), mim::Def::is_set(), mim::Lit::isa(), map(), pop(), mim::World::prod(), push(), rewrite(), rewrite_stub(), mim::Def::type(), and world().
rewrite_stub()
const Def * mim::Rewriter::rewrite_stub (Def * old_mut, Def * new_mut) virtual
Definition at line 165 of file rewrite.cpp.
References mim::Def::immutabilize(), mim::Def::is_set(), map(), mim::Def::num_ops(), mim::Def::op(), rewrite(), and mim::Def::set().
Referenced by mim::RetWrap::rewrite_mut_Lam(), and rewrite_mut_Seq().
world()
World & mim::Rewriter::world () inline
Definition at line 47 of file rewrite.h.
Referenced by map(), map(), map(), mim::RWPhase::new_world(), rewrite_imm_Seq(), mim::VarRewriter::rewrite_mut(), rewrite_mut_Seq(), Rewriter(), mim::VarRewriter::VarRewriter(), mim::VarRewriter::VarRewriter(), and mim::Zonker::Zonker().
Friends And Related Symbol Documentation
swap
void swap (Rewriter & rw1, Rewriter & rw2) friend
Definition at line 96 of file rewrite.h.
References Rewriter(), and swap.
Referenced by mim::ReplManPhase::apply(), mim::RWPhase::start(), and swap.
Member Data Documentation
old2news_
std::deque<Def2Def> mim::Rewriter::old2news_ protected
Definition at line 107 of file rewrite.h.
Referenced by lookup(), mim::Zonker::lookup(), map(), map(), map(), map(), mim::Zonker::map(), pop(), push(), and reset().
The documentation for this class was generated from the following files:
include/mim/rewrite.h
src/mim/rewrite.cpp