MimIR: mim::Axm::IsA< Id, D > Class Template Reference
mim::Axm::IsA< Id, D > Class Template Reference
#include <mim/axm.h>
Public Member Functions
IsA ()=default
IsA (const Axm *axm, const D *def)
Getters
const Axm * axm () const
const D * operator-> () const
operator const D * () const
operator bool ()
Axm Name
See also
annex_name "Annex Name"
auto plugin () const
auto tag () const
auto sub () const
auto base () const
auto id () const
Axm::flags cast to Id.
Detailed Description
template<class Id, class D>
class mim::Axm::IsA< Id, D >
Definition at line 67 of file axm.h.
Constructor & Destructor Documentation
IsA() [1/2]
template<class Id, class D> mim::Axm::IsA< Id, D >::IsA () default
IsA() [2/2]
template<class Id, class D> mim::Axm::IsA< Id, D >::IsA (const Axm * axm, const D * def) inline
Definition at line 73 of file axm.h.
References axm().
Member Function Documentation
axm()
template<class Id, class D> const Axm * mim::Axm::IsA< Id, D >::axm () const inline
Definition at line 79 of file axm.h.
Referenced by base(), id(), IsA(), plugin(), sub(), and tag().
base()
template<class Id, class D> auto mim::Axm::IsA< Id, D >::base () const inline
See also
exiom::base.
Definition at line 91 of file axm.h.
References axm(), and mim::Axm::sub().
id()
template<class Id, class D> auto mim::Axm::IsA< Id, D >::id () const inline
Axm::flags cast to Id.
Definition at line 92 of file axm.h.
References axm(), and mim::Def::flags().
operator bool()
template<class Id, class D> mim::Axm::IsA< Id, D >::operator bool () inline explicit
Definition at line 82 of file axm.h.
operator const D *()
template<class Id, class D> mim::Axm::IsA< Id, D >::operator const D * () const inline
Definition at line 81 of file axm.h.
operator->()
template<class Id, class D> const D * mim::Axm::IsA< Id, D >::operator-> () const inline
Definition at line 80 of file axm.h.
plugin()
template<class Id, class D> auto mim::Axm::IsA< Id, D >::plugin () const inline
See also
Axm::plugin.
Definition at line 88 of file axm.h.
References axm(), and mim::Axm::plugin().
sub()
template<class Id, class D> auto mim::Axm::IsA< Id, D >::sub () const inline
See also
Axm::sub.
Definition at line 90 of file axm.h.
References axm(), and mim::Axm::sub().
tag()
template<class Id, class D> auto mim::Axm::IsA< Id, D >::tag () const inline
See also
Axm::tag.
Definition at line 89 of file axm.h.
References axm(), and mim::Axm::tag().
The documentation for this class was generated from the following file:
include/mim/axm.h