MimIR: mim::ast::TupleExpr Class Reference
mim::ast::TupleExpr Class Reference
(elem_0, ..., elem_n-1)
#include <mim/ast/ast.h>
Public Member Functions
TupleExpr (Loc loc, Ptrs< Expr > &&elems)
const auto & elems () const
const Expr * elem (size_t i) const
size_t num_elems () const
void bind (Scopes &) const override
std::ostream & stream (Tab &, std::ostream &) const override
Public Member Functions inherited from mim::ast::Expr
const Def * emit (Emitter &) const
virtual const Def * emit_decl (Emitter &, const Def *) const
virtual void emit_body (Emitter &, const Def *) const
Public Member Functions inherited from mim::ast::Node
Loc loc () const
void dump () const
Private Member Functions
const Def * emit_ (Emitter &) const override
Additional Inherited Members
enum class Prec {
Err ,
Bot ,
Where ,
Arrow ,
Pi ,
Inj ,
App ,
Union ,
Extract ,
Lit
}
static constexpr bool is_rassoc (Prec p)
Protected Member Functions inherited from mim::ast::Expr
Expr (Loc loc)
Protected Member Functions inherited from mim::ast::Node
Node (Loc loc)
virtual ~Node ()
Detailed Description
(elem_0, ..., elem_n-1)
Definition at line 718 of file ast.h.
Constructor & Destructor Documentation
TupleExpr()
mim::ast::TupleExpr::TupleExpr (Loc loc, Ptrs< Expr > && elems) inline
Definition at line 720 of file ast.h.
References elems(), mim::ast::Expr::Expr(), and mim::ast::Node::loc().
Member Function Documentation
bind()
void mim::ast::TupleExpr::bind (Scopes & s) const override virtual
Implements mim::ast::Expr.
Definition at line 213 of file bind.cpp.
References elem(), and elems().
elem()
const Expr * mim::ast::TupleExpr::elem (size_t i) const inline
Definition at line 725 of file ast.h.
References mim::ast::Expr::Expr().
Referenced by bind(), and emit_().
elems()
const auto & mim::ast::TupleExpr::elems () const inline
Definition at line 724 of file ast.h.
Referenced by bind(), emit_(), num_elems(), stream(), and TupleExpr().
emit_()
const Def * mim::ast::TupleExpr::emit_ (Emitter & e) const override private virtual
Implements mim::ast::Expr.
Definition at line 315 of file emit.cpp.
References elem(), elems(), and num_elems().
num_elems()
size_t mim::ast::TupleExpr::num_elems () const inline
Definition at line 726 of file ast.h.
References elems().
Referenced by emit_().
stream()
std::ostream & mim::ast::TupleExpr::stream (Tab & tab, std::ostream & os) const override virtual
Implements mim::ast::Node.
Definition at line 161 of file stream.cpp.
References elems(), and mim::print().
The documentation for this class was generated from the following files:
include/mim/ast/ast.h
src/mim/ast/bind.cpp
src/mim/ast/emit.cpp
src/mim/ast/stream.cpp