MimIR: automaton::DFANode Class Reference
automaton::DFANode Class Reference
#include <automaton/dfa.h>
Classes
struct Lt
Public Member Functions
DFANode (int id)
constexpr int id () const noexcept
void add_transition (const DFANode *to, std::uint16_t c)
const DFANode * get_transition (std::uint16_t c) const
template<class F>
void for_transitions (F &&f, std::uint16_t c) const
template<class F>
void for_transitions (F &&f) const
bool is_accepting () const noexcept
void set_accepting (bool accepting) noexcept
bool is_erroring () const noexcept
void set_erroring (bool erroring) noexcept
Friends
std::ostream & operator<< (std::ostream &os, const DFANode &node)
Detailed Description
Definition at line 11 of file dfa.h.
Constructor & Destructor Documentation
DFANode()
automaton::DFANode::DFANode (int id) inline
Definition at line 17 of file dfa.h.
References id().
Referenced by add_transition(), get_transition(), automaton::DFANode::Lt::operator()(), and operator<<.
Member Function Documentation
add_transition()
void automaton::DFANode::add_transition (const DFANode * to, std::uint16_t c)
Definition at line 9 of file dfa.cpp.
References DFANode().
for_transitions() [1/2]
template<class F> void automaton::DFANode::for_transitions (F && f) const inline
Definition at line 31 of file dfa.h.
for_transitions() [2/2]
template<class F> void automaton::DFANode::for_transitions (F && f, std::uint16_t c) const inline
Definition at line 25 of file dfa.h.
get_transition()
const DFANode * automaton::DFANode::get_transition (std::uint16_t c) const
Definition at line 11 of file dfa.cpp.
References DFANode().
id()
int automaton::DFANode::id () const inline constexpr noexcept
Definition at line 20 of file dfa.h.
Referenced by DFANode().
is_accepting()
bool automaton::DFANode::is_accepting () const inline noexcept
Definition at line 36 of file dfa.h.
is_erroring()
bool automaton::DFANode::is_erroring () const inline noexcept
Definition at line 42 of file dfa.h.
set_accepting()
void automaton::DFANode::set_accepting (bool accepting) inline noexcept
Definition at line 37 of file dfa.h.
set_erroring()
void automaton::DFANode::set_erroring (bool erroring) inline noexcept
Definition at line 43 of file dfa.h.
Friends And Related Symbol Documentation
operator<<
std::ostream & operator<< (std::ostream & os, const DFANode & node) friend
Definition at line 19 of file dfa.cpp.
References DFANode(), and automaton::print_node().
The documentation for this class was generated from the following files:
include/automaton/dfa.h
src/automaton/dfa.cpp