MimIR: mim::ast::ExtractExpr Class Reference
mim::ast::ExtractExpr Class Reference
tuple#index
#include <mim/ast/ast.h>
Public Member Functions
ExtractExpr (Loc loc, Ptr< Expr > &&tuple, Ptr< Expr > &&index)
ExtractExpr (Loc loc, Ptr< Expr > &&tuple, Dbg index)
const Expr * tuple () const
const auto & index () const
const Decl * decl () const
void bind (Scopes &) const override
std::ostream & stream (Tab &, std::ostream &) const override
Public Member Functions inherited from mim::ast::Expr
const Def * emit (Emitter &) const
virtual const Def * emit_decl (Emitter &, const Def *) const
virtual void emit_body (Emitter &, const Def *) const
Public Member Functions inherited from mim::ast::Node
Loc loc () const
void dump () const
Private Member Functions
const Def * emit_ (Emitter &) const override
Additional Inherited Members
enum class Prec {
Err ,
Bot ,
Where ,
Arrow ,
Pi ,
Inj ,
App ,
Union ,
Extract ,
Lit
}
static constexpr bool is_rassoc (Prec p)
Protected Member Functions inherited from mim::ast::Expr
Expr (Loc loc)
Protected Member Functions inherited from mim::ast::Node
Node (Loc loc)
virtual ~Node ()
Detailed Description
tuple#index
Definition at line 767 of file ast.h.
Constructor & Destructor Documentation
ExtractExpr() [1/2]
mim::ast::ExtractExpr::ExtractExpr (Loc loc, Ptr< Expr > && tuple, Ptr< Expr > && index) inline
Definition at line 769 of file ast.h.
References mim::ast::Expr::Expr(), index(), mim::ast::Node::loc(), and tuple().
ExtractExpr() [2/2]
mim::ast::ExtractExpr::ExtractExpr (Loc loc, Ptr< Expr > && tuple, Dbg index) inline
Definition at line 773 of file ast.h.
References mim::ast::Expr::Expr(), index(), mim::ast::Node::loc(), and tuple().
Member Function Documentation
bind()
void mim::ast::ExtractExpr::bind (Scopes & s) const override virtual
Implements mim::ast::Expr.
Definition at line 219 of file bind.cpp.
References index(), and tuple().
decl()
const Decl * mim::ast::ExtractExpr::decl () const inline
Definition at line 780 of file ast.h.
Referenced by emit_().
emit_()
const Def * mim::ast::ExtractExpr::emit_ (Emitter & e) const override private virtual
Implements mim::ast::Expr.
Definition at line 344 of file emit.cpp.
References decl(), mim::error(), mim::get(), index(), and tuple().
index()
const auto & mim::ast::ExtractExpr::index () const inline
Definition at line 779 of file ast.h.
Referenced by bind(), emit_(), ExtractExpr(), ExtractExpr(), and stream().
stream()
std::ostream & mim::ast::ExtractExpr::stream (Tab & tab, std::ostream & os) const override virtual
Implements mim::ast::Node.
Definition at line 163 of file stream.cpp.
References index(), mim::print(), and tuple().
tuple()
const Expr * mim::ast::ExtractExpr::tuple () const inline
Definition at line 778 of file ast.h.
References mim::ast::Expr::Expr().
Referenced by bind(), emit_(), ExtractExpr(), ExtractExpr(), and stream().
The documentation for this class was generated from the following files:
include/mim/ast/ast.h
src/mim/ast/bind.cpp
src/mim/ast/emit.cpp
src/mim/ast/stream.cpp