MimIR: mim::ast::IdPtrn Class Reference
mim::ast::IdPtrn Class Reference
dbg: type
#include <mim/ast/ast.h>
Public Member Functions
IdPtrn (Loc loc, Dbg dbg, Ptr< Expr > &&type)
Dbg dbg () const
const Expr * type () const
void bind (Scopes &, bool rebind, bool quiet) const override
Ref emit_value (Emitter &, Ref) const override
Ref emit_type (Emitter &) const override
std::ostream & stream (Tab &, std::ostream &) const override
Public Member Functions inherited from mim::ast::Ptrn
Ptrn (Loc loc)
virtual bool is_implicit () const
Public Member Functions inherited from mim::ast::Decl
Ref def () const
Public Member Functions inherited from mim::ast::Node
Loc loc () const
void dump () const
Static Public Member Functions
static Ptr< IdPtrn > make_type (AST &ast, Ptr< Expr > &&type)
static Ptr< IdPtrn > make_id (AST &ast, Dbg dbg, Ptr< Expr > &&type)
Static Public Member Functions inherited from mim::ast::Ptrn
static Ptr< Expr > to_expr (AST &, Ptr< Ptrn > &&)
static Ptr< Ptrn > to_ptrn (Ptr< Expr > &&)
Additional Inherited Members
Protected Member Functions inherited from mim::ast::Decl
Decl (Loc loc)
Protected Member Functions inherited from mim::ast::Node
Node (Loc loc)
virtual ~Node ()
Protected Attributes inherited from mim::ast::Decl
Ref def_ = nullptr
Detailed Description
dbg: type
Definition at line 214 of file ast.h.
Constructor & Destructor Documentation
IdPtrn()
mim::ast::IdPtrn::IdPtrn (Loc loc, Dbg dbg, Ptr< Expr > && type) inline
Definition at line 216 of file ast.h.
Member Function Documentation
bind()
void mim::ast::IdPtrn::bind (Scopes & s, bool rebind, bool quiet) const override virtual
Implements mim::ast::Ptrn.
Definition at line 97 of file bind.cpp.
References mim::ast::Expr::bind(), dbg(), and type().
Referenced by mim::ast::PiExpr::Dom::bind().
dbg()
Dbg mim::ast::IdPtrn::dbg () const inline
Definition at line 221 of file ast.h.
Referenced by bind(), emit_value(), make_id(), stream(), and mim::ast::Ptrn::to_expr().
emit_type()
Ref mim::ast::IdPtrn::emit_type (Emitter & e) const override virtual
Implements mim::ast::Ptrn.
Definition at line 77 of file emit.cpp.
References mim::ast::Expr::emit(), mim::ast::Node::loc(), and type().
Referenced by mim::ast::GrpPtrn::emit_type(), and emit_value().
emit_value()
Ref mim::ast::IdPtrn::emit_value (Emitter & e, Ref def) const override virtual
Implements mim::ast::Ptrn.
Definition at line 55 of file emit.cpp.
References dbg(), mim::ast::Decl::def(), mim::ast::Decl::def_, emit_type(), and mim::Def::set().
make_id()
static Ptr< IdPtrn > mim::ast::IdPtrn::make_id (AST & ast, Dbg dbg, Ptr< Expr > && type) inline static
Definition at line 228 of file ast.h.
References dbg(), mim::ast::Node::loc(), mim::Dbg::loc(), mim::ast::AST::ptr(), and type().
make_type()
static Ptr< IdPtrn > mim::ast::IdPtrn::make_type (AST & ast, Ptr< Expr > && type) inline static
Definition at line 224 of file ast.h.
References mim::ast::Node::loc(), mim::ast::AST::ptr(), mim::ast::AST::sym_anon(), and type().
stream()
std::ostream & mim::ast::IdPtrn::stream (Tab & tab, std::ostream & os) const override virtual
Implements mim::ast::Node.
Definition at line 57 of file stream.cpp.
References dbg(), mim::print(), and type().
type()
const Expr * mim::ast::IdPtrn::type () const inline
Definition at line 222 of file ast.h.
Referenced by bind(), emit_type(), make_id(), make_type(), and stream().
The documentation for this class was generated from the following files:
include/mim/ast/ast.h
src/mim/ast/bind.cpp
src/mim/ast/emit.cpp
src/mim/ast/stream.cpp