Thorin: thorin::IndexSet< Indexer, Key > Class Template Reference
thorin::IndexSet< Indexer, Key > Class Template Reference
#include <thorin/util/indexset.h>
Classes
class reference
Public Member Functions
IndexSet (const Indexer &indexer)
IndexSet (IndexSet &&other)
IndexSet (const IndexSet &other)
const Indexer & indexer () const
size_t capacity () const
size_t next (size_t pos=0)
reference operator[] (Key key)
bool operator[] (Key key) const
template<bool flag>
bool set (Key key)
Depending on flag this method either inserts (true) or removes (false) key and returns true if successful.
bool insert (Key key)
Inserts key and returns true if successful.
bool erase (Key key)
Erase key and returns true if successful.
bool contains (Key key) const
void clear ()
template<class Op >
IndexSet & transform (const IndexSet &other, Op op)
IndexSet & operator&= (const IndexSet &other)
IndexSet & operator|= (const IndexSet &other)
IndexSet & operator^= (const IndexSet &other)
IndexSet & operator= (IndexSet other)
Friends
void swap (IndexSet &set1, IndexSet &set2)
Detailed Description
template<class Indexer, class Key>
class thorin::IndexSet< Indexer, Key >
Definition at line 8 of file indexset.h.
Constructor & Destructor Documentation
IndexSet() [1/3]
template<class Indexer , class Key > thorin::IndexSet< Indexer, Key >::IndexSet (const Indexer & indexer) inline
Definition at line 38 of file indexset.h.
IndexSet() [2/3]
template<class Indexer , class Key > thorin::IndexSet< Indexer, Key >::IndexSet (IndexSet< Indexer, Key > && other) inline
Definition at line 41 of file indexset.h.
References thorin::IndexSet< Indexer, Key >::swap.
IndexSet() [3/3]
template<class Indexer , class Key > thorin::IndexSet< Indexer, Key >::IndexSet (const IndexSet< Indexer, Key > & other) inline
Definition at line 45 of file indexset.h.
Member Function Documentation
capacity()
template<class Indexer , class Key > size_t thorin::IndexSet< Indexer, Key >::capacity () const inline
Definition at line 50 of file indexset.h.
References thorin::IndexSet< Indexer, Key >::indexer().
Referenced by thorin::IndexSet< Indexer, Key >::next(), and thorin::IndexSet< Indexer, Key >::transform().
clear()
template<class Indexer , class Key > void thorin::IndexSet< Indexer, Key >::clear () inline
Definition at line 75 of file indexset.h.
References thorin::u.
contains()
template<class Indexer , class Key > bool thorin::IndexSet< Indexer, Key >::contains (Key key) const inline
Definition at line 74 of file indexset.h.
Referenced by thorin::visit_first().
erase()
template<class Indexer , class Key > bool thorin::IndexSet< Indexer, Key >::erase (Key key) inline
Erase key and returns true if successful.
Definition at line 73 of file indexset.h.
indexer()
template<class Indexer , class Key > const Indexer & thorin::IndexSet< Indexer, Key >::indexer () const inline
Definition at line 49 of file indexset.h.
Referenced by thorin::IndexSet< Indexer, Key >::capacity(), and thorin::IndexSet< Indexer, Key >::operator[]().
insert()
template<class Indexer , class Key > bool thorin::IndexSet< Indexer, Key >::insert (Key key) inline
Inserts key and returns true if successful.
Definition at line 72 of file indexset.h.
Referenced by thorin::visit().
next()
template<class Indexer , class Key > size_t thorin::IndexSet< Indexer, Key >::next (size_t pos = 0) inline
Definition at line 51 of file indexset.h.
References thorin::IndexSet< Indexer, Key >::capacity(), and thorin::e.
operator&=()
template<class Indexer , class Key > IndexSet & thorin::IndexSet< Indexer, Key >::operator&= (const IndexSet< Indexer, Key > & other) inline
Definition at line 83 of file indexset.h.
References thorin::IndexSet< Indexer, Key >::transform().
operator=()
template<class Indexer , class Key > IndexSet & thorin::IndexSet< Indexer, Key >::operator= (IndexSet< Indexer, Key > other) inline
Definition at line 86 of file indexset.h.
References thorin::IndexSet< Indexer, Key >::swap.
operator[]() [1/2]
template<class Indexer , class Key > reference thorin::IndexSet< Indexer, Key >::operator[] (Key key) inline
Definition at line 57 of file indexset.h.
References thorin::IndexSet< Indexer, Key >::indexer().
operator[]() [2/2]
template<class Indexer , class Key > bool thorin::IndexSet< Indexer, Key >::operator[] (Key key) const inline
Definition at line 62 of file indexset.h.
operator^=()
template<class Indexer , class Key > IndexSet & thorin::IndexSet< Indexer, Key >::operator^= (const IndexSet< Indexer, Key > & other) inline
Definition at line 85 of file indexset.h.
References thorin::IndexSet< Indexer, Key >::transform().
operator|=()
template<class Indexer , class Key > IndexSet & thorin::IndexSet< Indexer, Key >::operator|= (const IndexSet< Indexer, Key > & other) inline
Definition at line 84 of file indexset.h.
References thorin::IndexSet< Indexer, Key >::transform().
set()
template<class Indexer , class Key > template<bool flag> bool thorin::IndexSet< Indexer, Key >::set (Key key) inline
Depending on flag this method either inserts (true) or removes (false) key and returns true if successful.
Definition at line 66 of file indexset.h.
transform()
template<class Indexer , class Key > template<class Op > IndexSet & thorin::IndexSet< Indexer, Key >::transform (const IndexSet< Indexer, Key > & other, Op op) inline
Definition at line 78 of file indexset.h.
References thorin::IndexSet< Indexer, Key >::capacity(), thorin::e, thorin::clos::op(), and thorin::size.
Referenced by thorin::IndexSet< Indexer, Key >::operator&=(), thorin::IndexSet< Indexer, Key >::operator^=(), and thorin::IndexSet< Indexer, Key >::operator|=().
Friends And Related Function Documentation
swap
template<class Indexer , class Key > void swap (IndexSet< Indexer, Key > & set1, IndexSet< Indexer, Key > & set2) friend
Definition at line 90 of file indexset.h.
Referenced by thorin::IndexSet< Indexer, Key >::IndexSet(), and thorin::IndexSet< Indexer, Key >::operator=().
The documentation for this class was generated from the following file:
/home/runner/work/thorin2/thorin2/thorin/util/indexset.h