MimIR: mim::ast::TuplePtrn Class Reference
mim::ast::TuplePtrn Class Reference
(ptrn_0, ..., ptrn_n-1), [ptrn_0, ..., ptrn_n-1], or {ptrn_0, ..., ptrn_n-1}
#include <mim/ast/ast.h>
Public Member Functions
TuplePtrn (Loc loc, Tok::Tag delim_l, Ptrs< Ptrn > &&ptrns)
Tok::Tag delim_l () const
Tok::Tag delim_r () const
bool is_paren () const
bool is_brckt () const
bool is_implicit () const override
const auto & ptrns () const
const Ptrn * ptrn (size_t i) const
size_t num_ptrns () const
void bind (Scopes &, bool rebind, bool quiet) const override
Ref emit_value (Emitter &, Ref) const override
Ref emit_type (Emitter &) const override
Ref emit_decl (Emitter &, Ref type) const
Ref emit_body (Emitter &, Ref decl) const
std::ostream & stream (Tab &, std::ostream &) const override
Public Member Functions inherited from mim::ast::Ptrn
Ptrn (Loc loc)
Public Member Functions inherited from mim::ast::Decl
Ref def () const
Public Member Functions inherited from mim::ast::Node
Loc loc () const
void dump () const
Additional Inherited Members
Static Public Member Functions inherited from mim::ast::Ptrn
static Ptr< Expr > to_expr (AST &, Ptr< Ptrn > &&)
static Ptr< Ptrn > to_ptrn (Ptr< Expr > &&)
Protected Member Functions inherited from mim::ast::Decl
Decl (Loc loc)
Protected Member Functions inherited from mim::ast::Node
Node (Loc loc)
virtual ~Node ()
Protected Attributes inherited from mim::ast::Decl
Ref def_ = nullptr
Detailed Description
(ptrn_0, ..., ptrn_n-1), [ptrn_0, ..., ptrn_n-1], or {ptrn_0, ..., ptrn_n-1}
Definition at line 287 of file ast.h.
Constructor & Destructor Documentation
TuplePtrn()
mim::ast::TuplePtrn::TuplePtrn (Loc loc, Tok::Tag delim_l, Ptrs< Ptrn > && ptrns) inline
Definition at line 289 of file ast.h.
Member Function Documentation
bind()
void mim::ast::TuplePtrn::bind (Scopes & s, bool rebind, bool quiet) const override virtual
Implements mim::ast::Ptrn.
Definition at line 107 of file bind.cpp.
References mim::ast::Ptrn::bind(), ptrn(), and ptrns().
delim_l()
Tok::Tag mim::ast::TuplePtrn::delim_l () const inline
Definition at line 294 of file ast.h.
Referenced by delim_r(), is_brckt(), is_paren(), and stream().
delim_r()
Tok::Tag mim::ast::TuplePtrn::delim_r () const inline
Definition at line 295 of file ast.h.
References delim_l(), and mim::ast::Tok::delim_l2r().
Referenced by stream().
emit_body()
Ref mim::ast::TuplePtrn::emit_body (Emitter & e, Ref decl) const
Definition at line 88 of file emit.cpp.
References mim::Def::as_mut(), emit_type(), mim::ast::Ptrn::emit_value(), mim::Sigma::immutabilize(), mim::ast::Node::loc(), num_ptrns(), ptrn(), mim::Sigma::set(), and mim::Def::var().
Referenced by emit_type().
emit_decl()
Ref mim::ast::TuplePtrn::emit_decl (Emitter & e, Ref type) const
Definition at line 111 of file emit.cpp.
References mim::ast::Node::loc(), and num_ptrns().
emit_type()
Ref mim::ast::TuplePtrn::emit_type (Emitter & e) const override virtual
Implements mim::ast::Ptrn.
Definition at line 86 of file emit.cpp.
References emit_body().
Referenced by emit_body(), and emit_value().
emit_value()
Ref mim::ast::TuplePtrn::emit_value (Emitter & e, Ref def) const override virtual
Implements mim::ast::Ptrn.
Definition at line 64 of file emit.cpp.
References mim::ast::Decl::def(), mim::ast::Decl::def_, emit_type(), mim::ast::Ptrn::emit_value(), mim::ast::Node::loc(), num_ptrns(), mim::Def::proj(), and ptrn().
is_brckt()
bool mim::ast::TuplePtrn::is_brckt () const inline
Definition at line 297 of file ast.h.
References delim_l().
Referenced by mim::ast::Ptrn::to_expr().
is_implicit()
bool mim::ast::TuplePtrn::is_implicit () const inline override virtual
Reimplemented from mim::ast::Ptrn.
Definition at line 298 of file ast.h.
is_paren()
bool mim::ast::TuplePtrn::is_paren () const inline
Definition at line 296 of file ast.h.
References delim_l().
num_ptrns()
size_t mim::ast::TuplePtrn::num_ptrns () const inline
Definition at line 302 of file ast.h.
References ptrns().
Referenced by emit_body(), emit_decl(), and emit_value().
ptrn()
const Ptrn * mim::ast::TuplePtrn::ptrn (size_t i) const inline
Definition at line 301 of file ast.h.
Referenced by bind(), emit_body(), and emit_value().
ptrns()
const auto & mim::ast::TuplePtrn::ptrns () const inline
Definition at line 300 of file ast.h.
Referenced by bind(), num_ptrns(), and stream().
stream()
std::ostream & mim::ast::TuplePtrn::stream (Tab & tab, std::ostream & os) const override virtual
Implements mim::ast::Node.
Definition at line 66 of file stream.cpp.
References delim_l(), delim_r(), mim::print(), and ptrns().
The documentation for this class was generated from the following files:
include/mim/ast/ast.h
src/mim/ast/bind.cpp
src/mim/ast/emit.cpp
src/mim/ast/stream.cpp