Thorin: thorin::SymPool Class Reference
thorin::SymPool Class Reference
Hash set where all strings - wrapped in Symbol - live in.
#include <thorin/util/sym.h>
Public Member Functions
SymPool ()=default
SymPool (const SymPool &)=delete
SymPool (SymPool &&other)
Sym sym (std::string_view s)
Sym sym (const char *s)
Sym sym (std::string s)
Friends
void swap (SymPool &p1, SymPool &p2)
Detailed Description
Hash set where all strings - wrapped in Symbol - live in.
You can access the SymPool from Driver.
Definition at line 82 of file sym.h.
Constructor & Destructor Documentation
SymPool() [1/3]
thorin::SymPool::SymPool () default
SymPool() [2/3]
thorin::SymPool::SymPool (const SymPool &) delete
SymPool() [3/3]
thorin::SymPool::SymPool (SymPool && other) inline
Definition at line 86 of file sym.h.
Member Function Documentation
sym() [1/3]
Sym thorin::SymPool::sym (const char * s) inline
Definition at line 90 of file sym.h.
sym() [2/3]
Sym thorin::SymPool::sym (std::string s) inline
Definition at line 91 of file sym.h.
sym() [3/3]
Sym thorin::SymPool::sym (std::string_view s) inline
Definition at line 89 of file sym.h.
Referenced by thorin::Driver::add_import(), thorin::Driver::axiom2info(), thorin::Driver::is_loaded(), thorin::Driver::load(), and thorin::World::sym().
Friends And Related Function Documentation
swap
void swap (SymPool & p1, SymPool & p2) friend
Definition at line 93 of file sym.h.
The documentation for this class was generated from the following file:
thorin/util/sym.h