Thorin: thorin::Lam Class Reference
thorin::Lam Class Reference
A function.
#include <thorin/lam.h>
Public Member Functions
ops & type
Ref filter () const
Ref body () const
const Pi * type () const
dom
See also
proj
Ref dom () const
nat_t num_doms () const
Ref dom (nat_t a, nat_t i) const
Ref dom (nat_t i) const
template<nat_t A = -1_s, class F >
auto doms (F f) const
template<nat_t A = -1_s>
auto doms () const
template<class F >
auto doms (nat_t a, F f) const
auto doms (nat_t a) const
codom
See also
proj
Ref codom () const
nat_t num_codoms () const
Ref codom (nat_t a, nat_t i) const
Ref codom (nat_t i) const
template<nat_t A = -1_s, class F >
auto codoms (F f) const
template<nat_t A = -1_s>
auto codoms () const
template<class F >
auto codoms (nat_t a, F f) const
auto codoms (nat_t a) const
Return Continuation
See also
Pi: Return Continuation
const Pi * ret_pi () const
Ref ret_dom () const
Ref ret_var ()
Yields the Lam::var of the Lam::ret_pi.
Rebuild
Lam * stub (World &, Ref) override
Ref rebuild (World &, Ref, Defs) const override
Def::rebuilds this Def while using new_op as substitute for its i'th Def::op.
Type Checking
void check () override
Public Member Functions inherited from thorin::Def
World & world () const
flags_t flags () const
u32 gid () const
hash_t hash () const
node_t node () const
std::string_view node_name () const
const Def * type () const
Yields the raw type of this Def, i.e. maybe nullptr.
const Def * unfold_type () const
Yields the type of this Def and unfolds it if necessary.
bool is_term () const
Yields true if this:T and T:(.Type 0).
Ref arity () const
std::optional< nat_t > isa_lit_arity () const
nat_t as_lit_arity () const
template<size_t N = -1_s>
auto ops () const
const Def * op (size_t i) const
size_t num_ops () const
Def * set (size_t i, const Def *def)
Successively set from left to right.
Def * reset (size_t i, const Def *def)
Successively reset from left to right.
Def * set (Defs ops)
Def::set ops all at once.
Def * reset (Defs ops)
Def::reset ops all at once.
Def * unset ()
Unsets all Def::ops; works even, if not set at all or partially.
Def * set_type (const Def *)
void unset_type ()
void update ()
Resolves Infers of this Def's type.
bool is_set () const
Yields true if empty or the last op is set.
Defs extended_ops () const
const Def * extended_op (size_t i) const
size_t num_extended_ops () const
Defs partial_ops () const
const Def * partial_op (size_t i) const
size_t num_partial_ops () const
const Uses & uses () const
size_t num_uses () const
unsigned dep () const
bool has_dep (Dep d) const
bool has_dep (unsigned u) const
bool dep_const () const
nat_t num_projs () const
Yields Def::as_lit_arity(), if it is in fact a Lit, or 1 otherwise.
const Def * proj (nat_t a, nat_t i) const
Similar to World::extract while assuming an arity of a, but also works on Sigmas and Arrays.
const Def * proj (nat_t i) const
Same as above but takes Def::num_projs as arity.
template<nat_t A = -1_s, class F >
auto projs (F f) const
Splits this Def via Def::projections into an Array (if A == -1_s) or std::array (otherwise).
template<class F >
auto projs (nat_t a, F f) const
template<nat_t A = -1_s>
auto projs () const
auto projs (nat_t a) const
Ref var ()
nat_t num_vars ()
Ref var (nat_t a, nat_t i)
Ref var (nat_t i)
template<nat_t A = -1_s, class F >
auto vars (F f)
template<nat_t A = -1_s>
auto vars ()
template<class F >
auto vars (nat_t a, F f)
auto vars (nat_t a)
bool is_external () const
void make_external ()
void make_internal ()
void transfer_external (Def *to)
template<class T = Def>
const T * isa_imm () const
template<class T = Def>
const T * as_imm () const
template<class T = Def, class R >
const T * isa_imm (R(T::*f)() const) const
template<class T = Def, bool invert = false>
T * isa_mut () const
If this is *mut*able, it will cast constness away and perform a dynamic_cast to T.
template<class T = Def, bool invert = false>
T * as_mut () const
Asserts that this is a mutable, casts constness away and performs a static_cast to T.
Dbg dbg () const
Loc loc () const
Sym sym () const
std::string unique_name () const
name + "_" + Def::gid
template<bool Ow = false>
const Def * set (Loc l) const
template<bool Ow = false>
Def * set (Loc l)
template<bool Ow = false>
const Def * set (Sym s) const
template<bool Ow = false>
Def * set (Sym s)
template<bool Ow = false>
const Def * set (std::string s) const
template<bool Ow = false>
Def * set (std::string s)
template<bool Ow = false>
const Def * set (Loc l, Sym s) const
template<bool Ow = false>
Def * set (Loc l, Sym s)
template<bool Ow = false>
const Def * set (Loc l, std::string s) const
template<bool Ow = false>
Def * set (Loc l, std::string s)
template<bool Ow = false>
const Def * set (Dbg d) const
template<bool Ow = false>
Def * set (Dbg d)
const Def * debug_prefix (std::string) const
const Def * debug_suffix (std::string) const
virtual const Def * immutabilize ()
Tries to make an immutable from a mutable.
const Def * refine (size_t i, const Def *new_op) const
DefArray reduce (const Def *arg) const
Rewrites Def::ops by substituting this mutable's Var with arg.
DefArray reduce (const Def *arg)
const Def * reduce_rec () const
Transitively Def::reduce Lams, if this is an App.
void dump () const
void dump (int max) const
void write (int max) const
void write (int max, const char *file) const
std::ostream & stream (std::ostream &, int max) const
Public Member Functions inherited from thorin::RuntimeCast< Def >
T * as ()
static_cast with debug check.
const T * as () const
const version.
T * isa ()
dynamic_cast.
Def * isa ()
Yields B* if it is either T or U and `nullptr* otherwise.
const T * isa () const
const version.
const Def * isa () const
const version.
Static Public Member Functions
Continuations
See also
Pi: Continuations
static const Lam * isa_cn (Ref d)
static const Lam * isa_basicblock (Ref d)
static const Lam * isa_returning (Ref d)
static Lam * isa_mut_cn (Ref d)
Only for mutables.
static Lam * isa_mut_basicblock (Ref d)
Only for mutables.
static Lam * isa_mut_returning (Ref d)
Only for mutables.
Static Public Attributes
static constexpr auto Node = Node:: Lam
Setters
Lam::Filter is a std::variant<bool, const Def*> that lets you set the Lam::filter() like this:
lam1->app(true, f, arg);
lam2->app(my_filter_def, f, arg);
See also
Setting Ops
using Filter = std::variant< bool, const Def * >
Lam * set (Filter filter, const Def *body)
Lam * set_filter (Filter)
Set filter first.
Lam * set_body (const Def *body)
Set body second.
Lam * app (Filter filter, const Def *callee, const Def *arg)
Set body to an App of callee and arg.
Lam * app (Filter filter, const Def *callee, Defs args)
Set body to an App of callee and args.
Lam * branch (Filter filter, const Def *cond, const Def *t, const Def *f, const Def *mem)
Set body to an App of (f, t)#cond mem.
Lam * test (Filter filter, const Def *val, const Def *idx, const Def *match, const Def *clash, const Def *mem)
Lam * set (Defs ops)
Lam * unset ()
Additional Inherited Members
Protected Member Functions inherited from thorin::Def
Def (World *, node_t, const Def *type, Defs ops, flags_t flags)
Constructor for an immutable Def.
Def (node_t n, const Def *type, Defs ops, flags_t flags)
Def (node_t, const Def *type, size_t num_ops, flags_t flags)
Constructor for a mutable Def.
virtual ~Def ()=default
Sym sym (const char *) const
Sym sym (std::string_view) const
Sym sym (std::string) const
Protected Attributes inherited from thorin::Def
Dbg dbg_
union {
NormalizeFn normalizer_
Axioms use this member to store their normalizer.
const Axiom * axiom_
World * world_
Curried Apps of Axioms use this member to propagate the Axiom.
};
flags_t flags_
u8 curry_
u8 trip_
Detailed Description
A function.
See also
Pi
Definition at line 94 of file lam.h.
Member Typedef Documentation
Filter
using thorin::Lam::Filter = std::variant<bool, const Def*>
Definition at line 155 of file lam.h.
Member Function Documentation
app() [1/2]
Lam * thorin::Lam::app (Filter filter, const Def * callee, const Def * arg)
Set body to an App of callee and arg.
Definition at line 29 of file lam.cpp.
References app(), set_body(), set_filter(), and thorin::Def::world().
Referenced by app(), branch(), thorin::RetWrap::enter(), and test().
app() [2/2]
Lam * thorin::Lam::app (Filter filter, const Def * callee, Defs args)
Set body to an App of callee and args.
Definition at line 30 of file lam.cpp.
References app(), filter(), and thorin::Def::world().
body()
Ref thorin::Lam::body () const inline
Definition at line 105 of file lam.h.
References thorin::Def::op().
Referenced by thorin::World::app(), thorin::autodiff::AutoDiffEval::augment_lam(), check(), thorin::ll::Emitter::emit_epilogue(), thorin::dot::Emitter::emit_epilogue(), thorin::clos::ClosConvPrep::enter(), set(), and set_body().
branch()
Lam * thorin::Lam::branch (Filter filter, const Def * cond, const Def * t, const Def * f, const Def * mem)
Set body to an App of (f, t)#cond mem.
Definition at line 32 of file lam.cpp.
References app(), filter(), and thorin::Def::world().
check()
void thorin::Lam::check () override virtual
Reimplemented from thorin::Def.
Definition at line 191 of file check.cpp.
References thorin::Check::alpha(), thorin::Check::assignable(), body(), codom(), thorin::error(), filter(), type(), and thorin::Def::world().
codom() [1/3]
Ref thorin::Lam::codom () const inline
Definition at line 121 of file lam.h.
References thorin::Pi::codom(), and type().
Referenced by check().
codom() [2/3]
Ref thorin::Lam::codom (nat_t a, nat_t i) const inline
Definition at line 122 of file lam.h.
codom() [3/3]
Ref thorin::Lam::codom (nat_t i) const inline
Definition at line 122 of file lam.h.
codoms() [1/4]
template<nat_t A = -1_s> auto thorin::Lam::codoms () const inline
Definition at line 122 of file lam.h.
codoms() [2/4]
template<nat_t A = -1_s, class F > auto thorin::Lam::codoms (F f) const inline
Definition at line 122 of file lam.h.
codoms() [3/4]
auto thorin::Lam::codoms (nat_t a) const inline
Definition at line 122 of file lam.h.
codoms() [4/4]
template<class F > auto thorin::Lam::codoms (nat_t a, F f) const inline
Definition at line 122 of file lam.h.
dom() [1/3]
Ref thorin::Lam::dom () const inline
Definition at line 113 of file lam.h.
References thorin::Pi::dom(), and type().
dom() [2/3]
Ref thorin::Lam::dom (nat_t a, nat_t i) const inline
Definition at line 114 of file lam.h.
dom() [3/3]
Ref thorin::Lam::dom (nat_t i) const inline
Definition at line 114 of file lam.h.
doms() [1/4]
template<nat_t A = -1_s> auto thorin::Lam::doms () const inline
Definition at line 114 of file lam.h.
doms() [2/4]
template<nat_t A = -1_s, class F > auto thorin::Lam::doms (F f) const inline
Definition at line 114 of file lam.h.
Referenced by thorin::ll::Emitter::emit_imported().
doms() [3/4]
auto thorin::Lam::doms (nat_t a) const inline
Definition at line 114 of file lam.h.
doms() [4/4]
template<class F > auto thorin::Lam::doms (nat_t a, F f) const inline
Definition at line 114 of file lam.h.
filter()
Ref thorin::Lam::filter () const inline
Definition at line 104 of file lam.h.
References thorin::Def::op().
Referenced by app(), thorin::World::app(), thorin::autodiff::AutoDiffEval::augment_lam(), branch(), check(), set(), set_filter(), and test().
isa_basicblock()
static const Lam * thorin::Lam::isa_basicblock (Ref d) inline static
Definition at line 130 of file lam.h.
References thorin::Pi::isa_basicblock().
Referenced by thorin::autodiff::AutoDiffEval::augment_lam(), isa_mut_basicblock(), and thorin::Emitter< Value, Type, BB, Child >::visit().
isa_cn()
static const Lam * thorin::Lam::isa_cn (Ref d) inline static
Definition at line 129 of file lam.h.
References thorin::Pi::isa_cn().
Referenced by isa_mut_cn().
isa_mut_basicblock()
static Lam * thorin::Lam::isa_mut_basicblock (Ref d) inline static
Only for mutables.
Definition at line 133 of file lam.h.
References isa_basicblock().
Referenced by thorin::ll::Emitter::emit_epilogue(), thorin::clos::ClosConvPrep::enter(), and thorin::clos::ClosConvPrep::rewrite_arg().
isa_mut_cn()
static Lam * thorin::Lam::isa_mut_cn (Ref d) inline static
Only for mutables.
Definition at line 132 of file lam.h.
References isa_cn().
isa_mut_returning()
static Lam * thorin::Lam::isa_mut_returning (Ref d) inline static
Only for mutables.
Definition at line 134 of file lam.h.
References isa_returning().
isa_returning()
static const Lam * thorin::Lam::isa_returning (Ref d) inline static
Definition at line 131 of file lam.h.
References thorin::Pi::isa_returning().
Referenced by isa_mut_returning().
num_codoms()
nat_t thorin::Lam::num_codoms () const inline
Definition at line 122 of file lam.h.
num_doms()
nat_t thorin::Lam::num_doms () const inline
Definition at line 114 of file lam.h.
Referenced by thorin::optimize().
rebuild()
Ref thorin::Lam::rebuild (World & w, Ref type, Defs ops) const override virtual
Def::rebuilds this Def while using new_op as substitute for its i'th Def::op.
Implements thorin::Def.
Definition at line 94 of file def.cpp.
ret_dom()
Ref thorin::Lam::ret_dom () const inline
Definition at line 142 of file lam.h.
References thorin::Pi::dom(), and ret_pi().
ret_pi()
const Pi * thorin::Lam::ret_pi () const inline
Definition at line 141 of file lam.h.
References thorin::Pi::ret_pi(), and type().
Referenced by ret_dom().
ret_var()
Ref thorin::Lam::ret_var () inline
Yields the Lam::var of the Lam::ret_pi.
Definition at line 144 of file lam.h.
References thorin::Def::num_vars(), thorin::Pi::ret_pi(), type(), and thorin::Def::var().
Referenced by thorin::ll::Emitter::emit_epilogue(), thorin::RetWrap::enter(), thorin::clos::ClosLit::ret_var(), and thorin::Emitter< Value, Type, BB, Child >::visit().
set() [1/2]
Lam * thorin::Lam::set (Defs ops) inline
Definition at line 166 of file lam.h.
References thorin::RuntimeCast< B >::as(), thorin::Def::ops(), and thorin::Def::set().
set() [2/2]
Lam * thorin::Lam::set (Filter filter, const Def * body) inline
Definition at line 156 of file lam.h.
References body(), filter(), set_body(), and set_filter().
Referenced by thorin::autodiff::AutoDiffEval::augment_app(), thorin::autodiff::AutoDiffEval::augment_extract(), thorin::autodiff::AutoDiffEval::augment_lam(), thorin::autodiff::AutoDiffEval::augment_pack(), thorin::autodiff::AutoDiffEval::augment_tuple(), thorin::autodiff::AutoDiffEval::derive_(), thorin::RetWrap::enter(), thorin::affine::LowerFor::rewrite(), thorin::matrix::LowerMatrixMediumLevel::rewrite_(), and thorin::World::World().
set_body()
Lam * thorin::Lam::set_body (const Def * body) inline
Set body second.
Definition at line 158 of file lam.h.
References thorin::RuntimeCast< B >::as(), body(), and thorin::Def::set().
Referenced by app(), and set().
set_filter()
Lam * thorin::Lam::set_filter (Filter filter)
Set filter first.
Definition at line 28 of file lam.cpp.
References thorin::RuntimeCast< B >::as(), filter(), thorin::Def::set(), and thorin::Def::world().
Referenced by app(), and set().
stub()
Lam * thorin::Lam::stub (World & w, Ref t) override virtual
Reimplemented from thorin::Def.
Definition at line 126 of file def.cpp.
Referenced by thorin::affine::LowerFor::rewrite().
test()
Lam * thorin::Lam::test (Filter filter, const Def * val, const Def * idx, const Def * match, const Def * clash, const Def * mem)
Definition at line 36 of file lam.cpp.
References app(), filter(), thorin::match(), test(), and thorin::Def::world().
Referenced by test().
type()
const Pi * thorin::Lam::type () const inline
Definition at line 106 of file lam.h.
References thorin::RuntimeCast< B >::as(), and thorin::Def::type().
Referenced by thorin::autodiff::AutoDiffEval::augment_lam(), check(), codom(), dom(), thorin::ll::Emitter::emit_imported(), thorin::EtaExp::proxy(), ret_pi(), and ret_var().
unset()
Lam * thorin::Lam::unset () inline
Definition at line 167 of file lam.h.
References thorin::RuntimeCast< B >::as(), and thorin::Def::unset().
Member Data Documentation
Node
constexpr auto thorin::Lam::Node = Node:: Lam static constexpr
Definition at line 177 of file lam.h.
The documentation for this class was generated from the following files:
thorin/lam.h
thorin/check.cpp
thorin/def.cpp
thorin/lam.cpp