Thorin: thorin::ast::PiExpr::Dom Class Reference
thorin::ast::PiExpr::Dom Class Reference
#include <thorin/ast/ast.h>
Public Member Functions
Dom (Loc loc, bool is_implicit, Ptr< Ptrn > &&ptrn)
bool is_implicit () const
const Ptrn * ptrn () const
const IdPtrn * ret () const
void add_ret (AST &ast, Ptr< Expr > &&type) const
virtual void bind (Scopes &scopes, bool quiet=false) const
virtual void emit_type (Emitter &) const
std::ostream & stream (Tab &, std::ostream &) const override
Public Member Functions inherited from thorin::ast::Node
Loc loc () const
void dump () const
Protected Attributes
Pi * pi_ = nullptr
Pi * decl_ = nullptr
Friends
class PiExpr
Additional Inherited Members
Protected Member Functions inherited from thorin::ast::Node
Node (Loc loc)
virtual ~Node ()
Detailed Description
Definition at line 449 of file ast.h.
Constructor & Destructor Documentation
Dom()
thorin::ast::PiExpr::Dom::Dom (Loc loc, bool is_implicit, Ptr< Ptrn > && ptrn) inline
Definition at line 451 of file ast.h.
Member Function Documentation
add_ret()
void thorin::ast::PiExpr::Dom::add_ret (AST & ast, Ptr< Expr > && type) const inline
Definition at line 460 of file ast.h.
References thorin::ast::Node::loc(), thorin::ast::AST::ptr(), and thorin::ast::AST::sym_return().
bind()
void thorin::ast::PiExpr::Dom::bind (Scopes & scopes, bool quiet = false) const virtual
Reimplemented in thorin::ast::LamDecl::Dom.
Definition at line 147 of file bind.cpp.
References thorin::ast::Ptrn::bind(), thorin::ast::IdPtrn::bind(), ptrn(), and ret().
Referenced by thorin::ast::PiExpr::bind(), thorin::ast::CDecl::bind(), thorin::ast::LamDecl::Dom::bind(), thorin::ast::LamDecl::bind_body(), and thorin::ast::LamDecl::bind_decl().
emit_type()
void thorin::ast::PiExpr::Dom::emit_type (Emitter & e) const virtual
Definition at line 187 of file emit.cpp.
References decl_, emit_type(), thorin::ast::Ptrn::emit_type(), thorin::ast::Ptrn::emit_value(), is_implicit(), thorin::ast::Node::loc(), pi_, ptrn(), ret(), thorin::Pi::set_dom(), and thorin::Def::var().
Referenced by thorin::ast::CDecl::emit(), thorin::ast::PiExpr::emit_(), thorin::ast::LamDecl::emit_decl(), and emit_type().
is_implicit()
bool thorin::ast::PiExpr::Dom::is_implicit () const inline
Definition at line 456 of file ast.h.
Referenced by emit_type(), and stream().
ptrn()
const Ptrn * thorin::ast::PiExpr::Dom::ptrn () const inline
Definition at line 457 of file ast.h.
Referenced by bind(), emit_type(), and stream().
ret()
const IdPtrn * thorin::ast::PiExpr::Dom::ret () const inline
Definition at line 458 of file ast.h.
Referenced by bind(), emit_type(), and stream().
stream()
std::ostream & thorin::ast::PiExpr::Dom::stream (Tab & tab, std::ostream & os) const override virtual
Implements thorin::ast::Node.
Definition at line 113 of file stream.cpp.
References is_implicit(), thorin::print(), ptrn(), and ret().
Friends And Related Symbol Documentation
PiExpr
friend class PiExpr friend
Definition at line 478 of file ast.h.
Member Data Documentation
decl_
Pi* thorin::ast::PiExpr::Dom::decl_ = nullptr mutable protected
Definition at line 471 of file ast.h.
Referenced by emit_type().
pi_
Pi* thorin::ast::PiExpr::Dom::pi_ = nullptr mutable protected
Definition at line 470 of file ast.h.
Referenced by thorin::ast::PiExpr::emit_(), thorin::ast::LamDecl::emit_decl(), and emit_type().
The documentation for this class was generated from the following files:
include/thorin/ast/ast.h
src/thorin/ast/bind.cpp
src/thorin/ast/emit.cpp
src/thorin/ast/stream.cpp