MimIR: mim::ast::Node Class Reference
mim::ast::Node Class Reference abstract
#include <mim/ast/ast.h>
Public Member Functions
Loc loc () const
virtual std::ostream & stream (Tab &, std::ostream &) const =0
void dump () const
Protected Member Functions
Node (Loc loc)
virtual ~Node ()
Detailed Description
Definition at line 115 of file ast.h.
Constructor & Destructor Documentation
Node()
mim::ast::Node::Node (Loc loc) inline protected
Definition at line 117 of file ast.h.
References loc().
Referenced by mim::ast::MatchExpr::Arm::Arm(), mim::ast::Decl::Decl(), mim::ast::PiExpr::Dom::Dom(), mim::ast::Expr::Expr(), mim::ast::Import::Import(), and mim::ast::Module::Module().
~Node()
virtual mim::ast::Node::~Node () inline protected virtual
Definition at line 119 of file ast.h.
Member Function Documentation
dump()
void mim::ast::Node::dump () const
Definition at line 33 of file stream.cpp.
References stream().
loc()
Loc mim::ast::Node::loc () const inline
Definition at line 122 of file ast.h.
Referenced by mim::ast::PiExpr::Dom::add_ret(), mim::ast::AxmDecl::Alias::Alias(), mim::ast::AliasPtrn::AliasPtrn(), mim::ast::AppExpr::AppExpr(), mim::ast::MatchExpr::Arm::Arm(), mim::ast::ArrowExpr::ArrowExpr(), mim::ast::AxmDecl::AxmDecl(), mim::ast::AxmDecl::Alias::bind(), mim::ast::AxmDecl::bind(), mim::ast::LitExpr::bind(), mim::ast::PiExpr::bind(), mim::ast::LamDecl::bind_decl(), mim::ast::RecDecl::bind_decl(), mim::ast::CDecl::CDecl(), mim::ast::Decl::Decl(), mim::ast::DeclExpr::DeclExpr(), mim::ast::LamDecl::Dom::Dom(), mim::ast::PiExpr::Dom::Dom(), mim::ast::Expr::emit(), mim::ast::MatchExpr::Arm::emit(), mim::ast::Module::emit(), mim::ast::RetExpr::emit_(), mim::ast::TuplePtrn::emit_body(), mim::ast::ArrowExpr::emit_decl(), mim::ast::LamDecl::emit_decl(), mim::ast::PiExpr::emit_decl(), mim::ast::TuplePtrn::emit_decl(), mim::ast::IdPtrn::emit_type(), mim::ast::PiExpr::Dom::emit_type(), mim::ast::TuplePtrn::emit_value(), mim::ast::ErrorExpr::ErrorExpr(), mim::ast::ErrorPtrn::ErrorPtrn(), mim::ast::Expr::Expr(), mim::ast::ExtractExpr::ExtractExpr(), mim::ast::ExtractExpr::ExtractExpr(), mim::ast::GrpPtrn::GrpPtrn(), mim::ast::HoleExpr::HoleExpr(), mim::ast::IdExpr::IdExpr(), mim::ast::IdPtrn::IdPtrn(), mim::ast::Import::Import(), mim::ast::InjExpr::InjExpr(), mim::ast::InsertExpr::InsertExpr(), mim::ast::LamDecl::LamDecl(), mim::ast::LamExpr::LamExpr(), mim::ast::LetDecl::LetDecl(), mim::ast::LitExpr::LitExpr(), mim::ast::IdPtrn::make_id(), mim::ast::IdPtrn::make_type(), mim::ast::MatchExpr::MatchExpr(), mim::ast::Module::Module(), Node(), mim::ast::PiExpr::PiExpr(), mim::ast::PrimaryExpr::PrimaryExpr(), mim::ast::PrimaryExpr::PrimaryExpr(), mim::ast::Ptrn::Ptrn(), mim::ast::RecDecl::RecDecl(), mim::ast::RetExpr::RetExpr(), mim::ast::SeqExpr::SeqExpr(), mim::ast::SigmaExpr::SigmaExpr(), mim::ast::TupleExpr::TupleExpr(), mim::ast::TuplePtrn::TuplePtrn(), mim::ast::TypeExpr::TypeExpr(), mim::ast::UnionExpr::UnionExpr(), mim::ast::UniqExpr::UniqExpr(), and mim::ast::ValDecl::ValDecl().
stream()
virtual std::ostream & mim::ast::Node::stream (Tab & , std::ostream &) const pure virtual
Implemented in mim::ast::AliasPtrn, mim::ast::AppExpr, mim::ast::ArrowExpr, mim::ast::AxmDecl::Alias, mim::ast::AxmDecl, mim::ast::CDecl, mim::ast::DeclExpr, mim::ast::DummyDecl, mim::ast::ErrorExpr, mim::ast::ErrorPtrn, mim::ast::ExtractExpr, mim::ast::GrpPtrn, mim::ast::HoleExpr, mim::ast::IdExpr, mim::ast::IdPtrn, mim::ast::Import, mim::ast::InjExpr, mim::ast::InsertExpr, mim::ast::LamDecl::Dom, mim::ast::LamDecl, mim::ast::LamExpr, mim::ast::LetDecl, mim::ast::LitExpr, mim::ast::MatchExpr::Arm, mim::ast::MatchExpr, mim::ast::Module, mim::ast::PiExpr::Dom, mim::ast::PiExpr, mim::ast::PrimaryExpr, mim::ast::RecDecl, mim::ast::RetExpr, mim::ast::SeqExpr, mim::ast::SigmaExpr, mim::ast::TupleExpr, mim::ast::TuplePtrn, mim::ast::TypeExpr, mim::ast::UnionExpr, and mim::ast::UniqExpr.
Referenced by dump().
The documentation for this class was generated from the following files:
include/mim/ast/ast.h
src/mim/ast/stream.cpp