MimIR: mim::Pool< T > Class Template Reference
mim::Pool< T > Class Template Reference
Maintains PooledSets within a fe::Arena and unifies them in a absl::flat_hash_set.
#include <mim/util/pool.h>
Public Member Functions
Construction & Destruction
Pool & operator= (const Pool &)=delete
Pool ()=default
Pool (const Pool &)=delete
Pool (Pool &&other)
Set Operations
PooledSet< T > singleton (T elem)
Create a PooledSet wih a single element: .
PooledSet< T > merge (PooledSet< T > a, PooledSet< T > b)
Yields .
PooledSet< T > insert (PooledSet< T > a, const T &elem)
Yields .
PooledSet< T > erase (PooledSet< T > set, const T &elem)
Yields .
bool has_intersection (PooledSet< T > a, PooledSet< T > b)
Is ?
Friends
void swap (Pool &p1, Pool &p2) noexcept
Detailed Description
template<class T>
class mim::Pool< T >
Maintains PooledSets within a fe::Arena and unifies them in a absl::flat_hash_set.
Definition at line 105 of file pool.h.
Constructor & Destructor Documentation
Pool() [1/3]
template<class T > mim::Pool< T >::Pool () default
Pool() [2/3]
template<class T > mim::Pool< T >::Pool (const Pool< T > &) delete
Pool() [3/3]
template<class T > mim::Pool< T >::Pool (Pool< T > && other) inline
Definition at line 115 of file pool.h.
References mim::Pool< T >::swap.
Member Function Documentation
erase()
template<class T > PooledSet< T > mim::Pool< T >::erase (PooledSet< T > set, const T & elem) inline nodiscard
Yields .
Definition at line 164 of file pool.h.
References mim::PooledSet< T >::begin(), mim::binary_find(), mim::PooledSet< T >::end(), and mim::PooledSet< T >::size().
has_intersection()
template<class T > bool mim::Pool< T >::has_intersection (PooledSet< T > a, PooledSet< T > b) inline nodiscard
Is ?
Definition at line 178 of file pool.h.
References mim::PooledSet< T >::begin(), and mim::PooledSet< T >::end().
insert()
template<class T > PooledSet< T > mim::Pool< T >::insert (PooledSet< T > a, const T & elem) inline nodiscard
Yields .
Definition at line 161 of file pool.h.
References mim::Pool< T >::merge(), and mim::Pool< T >::singleton().
merge()
template<class T > PooledSet< T > mim::Pool< T >::merge (PooledSet< T > a, PooledSet< T > b) inline nodiscard
Yields .
Definition at line 133 of file pool.h.
References mim::PooledSet< T >::begin(), mim::PooledSet< T >::end(), and mim::PooledSet< T >::size().
Referenced by mim::Pool< T >::insert().
operator=()
template<class T > Pool & mim::Pool< T >::operator= (const Pool< T > &) delete
singleton()
template<class T > PooledSet< T > mim::Pool< T >::singleton (T elem) inline nodiscard
Create a PooledSet wih a single element: .
Note
All operations do not modify the input set(s); they create a new PooledSet.
Definition at line 126 of file pool.h.
Referenced by mim::Pool< T >::insert().
Friends And Related Symbol Documentation
swap
template<class T > void swap (Pool< T > & p1, Pool< T > & p2) friend
Definition at line 195 of file pool.h.
Referenced by mim::Pool< T >::Pool().
The documentation for this class was generated from the following file:
include/mim/util/pool.h