MimIR: mim::ast::GrpPtrn Class Reference
mim::ast::GrpPtrn Class Reference
If you have x1 x2 x3 x4: T it consists of 3 GrpPtrns and 1 IdPtrn while each GrpPtrn references the last IdPtrn.
#include <mim/ast/ast.h>
Public Member Functions
GrpPtrn (Dbg dbg, const IdPtrn *id)
Dbg dbg () const
const IdPtrn * id () const
void bind (Scopes &, bool rebind, bool quiet) const override
const Def * emit_value (Emitter &, const Def *) const override
const Def * emit_type (Emitter &) const override
std::ostream & stream (Tab &, std::ostream &) const override
Public Member Functions inherited from mim::ast::Ptrn
Ptrn (Loc loc)
virtual bool is_implicit () const
Public Member Functions inherited from mim::ast::Decl
const Def * def () const
Public Member Functions inherited from mim::ast::Node
Loc loc () const
void dump () const
Additional Inherited Members
Static Public Member Functions inherited from mim::ast::Ptrn
static Ptr< Expr > to_expr (AST &, Ptr< Ptrn > &&)
static Ptr< Ptrn > to_ptrn (Ptr< Expr > &&)
Protected Member Functions inherited from mim::ast::Decl
Decl (Loc loc)
Protected Member Functions inherited from mim::ast::Node
Node (Loc loc)
virtual ~Node ()
Protected Attributes inherited from mim::ast::Decl
const Def * def_ = nullptr
Detailed Description
If you have x1 x2 x3 x4: T it consists of 3 GrpPtrns and 1 IdPtrn while each GrpPtrn references the last IdPtrn.
Definition at line 246 of file ast.h.
Constructor & Destructor Documentation
GrpPtrn()
mim::ast::GrpPtrn::GrpPtrn (Dbg dbg, const IdPtrn * id) inline
Definition at line 248 of file ast.h.
References dbg(), id(), mim::ast::Node::loc(), and mim::ast::Ptrn::Ptrn().
Member Function Documentation
bind()
void mim::ast::GrpPtrn::bind (Scopes & s, bool rebind, bool quiet) const override virtual
Implements mim::ast::Ptrn.
Definition at line 95 of file bind.cpp.
References dbg().
dbg()
Dbg mim::ast::GrpPtrn::dbg () const inline
Definition at line 253 of file ast.h.
Referenced by bind(), emit_value(), GrpPtrn(), and stream().
emit_type()
const Def * mim::ast::GrpPtrn::emit_type (Emitter & e) const override virtual
Implements mim::ast::Ptrn.
Definition at line 88 of file emit.cpp.
References mim::ast::IdPtrn::emit_type(), and id().
emit_value()
const Def * mim::ast::GrpPtrn::emit_value (Emitter & , const Def * def) const override virtual
Implements mim::ast::Ptrn.
Definition at line 62 of file emit.cpp.
References dbg(), mim::ast::Decl::def(), and mim::ast::Decl::def_.
id()
const IdPtrn * mim::ast::GrpPtrn::id () const inline
Definition at line 254 of file ast.h.
Referenced by emit_type(), and GrpPtrn().
stream()
std::ostream & mim::ast::GrpPtrn::stream (Tab & , std::ostream & os) const override virtual
Implements mim::ast::Node.
Definition at line 55 of file stream.cpp.
References dbg().
The documentation for this class was generated from the following files:
include/mim/ast/ast.h
src/mim/ast/bind.cpp
src/mim/ast/emit.cpp
src/mim/ast/stream.cpp