MimIR: mim::ast::RecDecl Class Reference
mim::ast::RecDecl Class Reference
.rec dbg: type = body
#include <mim/ast/ast.h>
Public Member Functions
RecDecl (Loc loc, Dbg dbg, Ptr< Expr > &&type, Ptr< Expr > &&body, Ptr< RecDecl > &&next)
Dbg dbg () const
const Expr * type () const
const Expr * body () const
const RecDecl * next () const
void bind (Scopes &) const override
virtual void bind_decl (Scopes &) const
virtual void bind_body (Scopes &) const
void emit (Emitter &) const override
virtual void emit_decl (Emitter &) const
virtual void emit_body (Emitter &) const
std::ostream & stream (Tab &, std::ostream &) const override
Public Member Functions inherited from mim::ast::Decl
const Def * def () const
Public Member Functions inherited from mim::ast::Node
Loc loc () const
void dump () const
Additional Inherited Members
Protected Member Functions inherited from mim::ast::ValDecl
ValDecl (Loc loc)
Protected Member Functions inherited from mim::ast::Decl
Decl (Loc loc)
Protected Member Functions inherited from mim::ast::Node
Node (Loc loc)
virtual ~Node ()
Protected Attributes inherited from mim::ast::Decl
const Def * def_ = nullptr
Detailed Description
.rec dbg: type = body
Definition at line 909 of file ast.h.
Constructor & Destructor Documentation
RecDecl()
mim::ast::RecDecl::RecDecl (Loc loc, Dbg dbg, Ptr< Expr > && type, Ptr< Expr > && body, Ptr< RecDecl > && next) inline
Definition at line 911 of file ast.h.
References body(), dbg(), mim::ast::Node::loc(), next(), type(), and mim::ast::ValDecl::ValDecl().
Referenced by mim::ast::LamDecl::LamDecl(), and next().
Member Function Documentation
bind()
void mim::ast::RecDecl::bind (Scopes & s) const override virtual
Implements mim::ast::ValDecl.
Definition at line 284 of file bind.cpp.
References dbg().
bind_body()
void mim::ast::RecDecl::bind_body (Scopes & s) const virtual
Reimplemented in mim::ast::LamDecl.
Definition at line 301 of file bind.cpp.
References body().
bind_decl()
void mim::ast::RecDecl::bind_decl (Scopes & s) const virtual
Reimplemented in mim::ast::LamDecl.
Definition at line 290 of file bind.cpp.
References body(), dbg(), mim::ast::Node::loc(), and type().
body()
const Expr * mim::ast::RecDecl::body () const inline
Definition at line 920 of file ast.h.
Referenced by mim::ast::LamDecl::bind_body(), bind_body(), bind_decl(), mim::ast::LamDecl::emit_body(), emit_body(), emit_decl(), mim::ast::LamDecl::LamDecl(), RecDecl(), mim::ast::LamDecl::stream(), and stream().
dbg()
Dbg mim::ast::RecDecl::dbg () const inline
Definition at line 918 of file ast.h.
Referenced by bind(), mim::ast::LamDecl::bind_decl(), bind_decl(), mim::ast::LamDecl::emit_decl(), emit_decl(), mim::ast::LamDecl::LamDecl(), RecDecl(), mim::ast::LamDecl::stream(), and stream().
emit()
void mim::ast::RecDecl::emit (Emitter & e) const override virtual
Implements mim::ast::ValDecl.
Definition at line 428 of file emit.cpp.
emit_body()
void mim::ast::RecDecl::emit_body (Emitter & e) const virtual
Reimplemented in mim::ast::LamDecl.
Definition at line 439 of file emit.cpp.
References body(), and mim::ast::Decl::def_.
emit_decl()
void mim::ast::RecDecl::emit_decl (Emitter & e) const virtual
Reimplemented in mim::ast::LamDecl.
Definition at line 433 of file emit.cpp.
References body(), dbg(), mim::ast::Decl::def_, and type().
next()
const RecDecl * mim::ast::RecDecl::next () const inline
Definition at line 921 of file ast.h.
References RecDecl().
Referenced by mim::ast::LamDecl::LamDecl(), and RecDecl().
stream()
std::ostream & mim::ast::RecDecl::stream (Tab & tab, std::ostream & os) const override virtual
Implements mim::ast::Node.
Definition at line 198 of file stream.cpp.
References body(), dbg(), mim::print(), and type().
type()
const Expr * mim::ast::RecDecl::type () const inline
Definition at line 919 of file ast.h.
Referenced by bind_decl(), emit_decl(), RecDecl(), mim::ast::LamDecl::Dom::stream(), and stream().
The documentation for this class was generated from the following files:
include/mim/ast/ast.h
src/mim/ast/bind.cpp
src/mim/ast/emit.cpp
src/mim/ast/stream.cpp