Thorin: thorin::Ref Class Reference
thorin::Ref Class Reference
Helper class to retrieve Infer::arg if present.
#include <thorin/def.h>
Public Member Functions
Ref ()=default
Ref (const Def *def)
const Def * operator* () const
const Def * operator-> () const
operator const Def * () const
operator bool () const
Static Public Member Functions
static const Def * refer (const Def *def)
Retrieves Infer::arg from def.
Detailed Description
Helper class to retrieve Infer::arg if present.
Definition at line 76 of file def.h.
Constructor & Destructor Documentation
Ref() [1/2]
thorin::Ref::Ref () default
Ref() [2/2]
thorin::Ref::Ref (const Def * def) inline
Definition at line 79 of file def.h.
Member Function Documentation
operator bool()
thorin::Ref::operator bool () const inline explicit
Definition at line 85 of file def.h.
operator const Def *()
thorin::Ref::operator const Def * () const inline
Definition at line 84 of file def.h.
References refer().
operator*()
const Def * thorin::Ref::operator* () const inline
Definition at line 82 of file def.h.
References refer().
operator->()
const Def * thorin::Ref::operator-> () const inline
Definition at line 83 of file def.h.
References refer().
refer()
const Def * thorin::Ref::refer (const Def * def) static
Retrieves Infer::arg from def.
Definition at line 27 of file check.cpp.
References thorin::Infer::find().
Referenced by thorin::Infer::find(), thorin::World::iapp(), operator const Def *(), operator*(), operator->(), and thorin::Def::update().
The documentation for this class was generated from the following files:
thorin/def.h
thorin/check.cpp