MimIR: mim::Emitter< Value, Type, BB, Child > Class Template Reference
mim::Emitter< Value, Type, BB, Child > Class Template Reference
#include <mim/be/emitter.h>
Public Attributes
Tab tab
Protected Member Functions
Emitter (World &world, std::string_view name, std::ostream &ostream)
std::ostream & ostream () const
Value emit (const Def *def)
Recursively emits code.
Value emit_unsafe (const Def *def)
As above but returning !child().is_valid(value) is permitted.
void visit (const Nest &nest) override
Protected Member Functions inherited from mim::ClosedMutPhase< Lam >
Lam * root () const
Protected Member Functions inherited from mim::Phase
void set_name (std::string name)
Protected Attributes
Lam * curr_lam_ = nullptr
std::ostream & ostream_
Scheduler scheduler_
DefMap< Value > locals_
DefMap< Value > globals_
DefMap< Type > types_
LamMap< BB > lam2bb_
Additional Inherited Members
Public Member Functions inherited from mim::NestPhase< Lam >
NestPhase (World &world, std::string_view name, bool dirty, bool elide_empty)
const Nest & nest () const
Public Member Functions inherited from mim::ClosedMutPhase< Lam >
ClosedMutPhase (World &world, std::string_view name, bool dirty, bool elide_empty)
void start () override
Actual entry.
Public Member Functions inherited from mim::Phase
Phase (World &world, std::string_view name, bool dirty)
virtual ~Phase ()=default
World & world ()
std::string_view name () const
bool is_dirty () const
virtual void run ()
Entry point and generates some debug output; invokes Phase::start.
Static Public Member Functions inherited from mim::Phase
template<class P , class... Args>
static void run (Args &&... args)
Runs a single Phase.
Detailed Description
template<class Value, class Type, class BB, class Child>
class mim::Emitter< Value, Type, BB, Child >
Definition at line 10 of file emitter.h.
Constructor & Destructor Documentation
Emitter()
template<class Value , class Type , class BB , class Child > mim::Emitter< Value, Type, BB, Child >::Emitter (World & world, std::string_view name, std::ostream & ostream) inline protected
Definition at line 26 of file emitter.h.
Member Function Documentation
emit()
template<class Value , class Type , class BB , class Child > Value mim::Emitter< Value, Type, BB, Child >::emit (const Def * def) inline protected
Recursively emits code.
mem-typed defs return sth that is !child().is_valid(value). This variant asserts in this case.
Definition at line 35 of file emitter.h.
References mim::Emitter< Value, Type, BB, Child >::emit_unsafe().
emit_unsafe()
template<class Value , class Type , class BB , class Child > Value mim::Emitter< Value, Type, BB, Child >::emit_unsafe (const Def * def) inline protected
As above but returning !child().is_valid(value) is permitted.
Definition at line 42 of file emitter.h.
References mim::Emitter< Value, Type, BB, Child >::globals_, and mim::Emitter< Value, Type, BB, Child >::locals_.
Referenced by mim::Emitter< Value, Type, BB, Child >::emit().
ostream()
template<class Value , class Type , class BB , class Child > std::ostream & mim::Emitter< Value, Type, BB, Child >::ostream () const inline protected
Definition at line 30 of file emitter.h.
References mim::Emitter< Value, Type, BB, Child >::ostream_.
visit()
template<class Value , class Type , class BB , class Child > void mim::Emitter< Value, Type, BB, Child >::visit (const Nest & nest) inline override protected virtual
Implements mim::NestPhase< Lam >.
Definition at line 50 of file emitter.h.
References mim::Emitter< Value, Type, BB, Child >::curr_lam_, mim::Lam::isa_basicblock(), mim::Emitter< Value, Type, BB, Child >::lam2bb_, mim::Emitter< Value, Type, BB, Child >::locals_, mim::NestPhase< Lam >::nest(), mim::ClosedMutPhase< Lam >::root(), mim::Scheduler::schedule(), and mim::Emitter< Value, Type, BB, Child >::scheduler_.
Member Data Documentation
curr_lam_
template<class Value , class Type , class BB , class Child > Lam* mim::Emitter< Value, Type, BB, Child >::curr_lam_ = nullptr protected
Definition at line 83 of file emitter.h.
Referenced by mim::Emitter< Value, Type, BB, Child >::visit().
globals_
template<class Value , class Type , class BB , class Child > DefMap<Value> mim::Emitter< Value, Type, BB, Child >::globals_ protected
Definition at line 87 of file emitter.h.
Referenced by mim::Emitter< Value, Type, BB, Child >::emit_unsafe().
lam2bb_
template<class Value , class Type , class BB , class Child > LamMap<BB> mim::Emitter< Value, Type, BB, Child >::lam2bb_ protected
Definition at line 89 of file emitter.h.
Referenced by mim::Emitter< Value, Type, BB, Child >::visit().
locals_
template<class Value , class Type , class BB , class Child > DefMap<Value> mim::Emitter< Value, Type, BB, Child >::locals_ protected
Definition at line 86 of file emitter.h.
Referenced by mim::Emitter< Value, Type, BB, Child >::emit_unsafe(), and mim::Emitter< Value, Type, BB, Child >::visit().
ostream_
template<class Value , class Type , class BB , class Child > std::ostream& mim::Emitter< Value, Type, BB, Child >::ostream_ protected
Definition at line 84 of file emitter.h.
Referenced by mim::Emitter< Value, Type, BB, Child >::ostream().
scheduler_
template<class Value , class Type , class BB , class Child > Scheduler mim::Emitter< Value, Type, BB, Child >::scheduler_ protected
Definition at line 85 of file emitter.h.
Referenced by mim::Emitter< Value, Type, BB, Child >::visit().
tab
template<class Value , class Type , class BB , class Child > Tab mim::Emitter< Value, Type, BB, Child >::tab
Definition at line 23 of file emitter.h.
types_
template<class Value , class Type , class BB , class Child > DefMap<Type> mim::Emitter< Value, Type, BB, Child >::types_ protected
Definition at line 88 of file emitter.h.
The documentation for this class was generated from the following file:
include/mim/be/emitter.h