MimIR: mim::Nest Class Reference
mim::Nest Class Reference
Builds a nesting tree of all immutables‍/binders.
#include <mim/nest.h>
Classes
class Node
Public Member Functions
Constructors
Nest (Def *root)
Nest (View< Def * > muts)
Constructs a virtual root with muts as children.
Nest (World &)
Virtual root with all World::externals as children.
Getters
World & world () const
Node * root ()
const Node * root () const
Vars vars () const
All Vars occurring in this Nest.
bool contains (const Def *def) const
bool is_recursive () const
Nodes
const auto & nodes () const
size_t num_nodes () const
const Node * mut2node (Def *mut) const
const Node * operator[] (Def *mut) const
Same as above.
dot
void dot (std::ostream &os) const
void dot (const char *file=nullptr) const
Static Public Member Functions
static const Node * lca (const Node *n, const Node *m)
Least common ancestor of n and m.
Detailed Description
Builds a nesting tree of all immutables‍/binders.
Definition at line 10 of file nest.h.
Constructor & Destructor Documentation
Nest() [1/3]
mim::Nest::Nest (Def * root)
Definition at line 11 of file nest.cpp.
Nest() [2/3]
mim::Nest::Nest (View< Def * > muts)
Constructs a virtual root with muts as children.
Definition at line 17 of file nest.cpp.
Nest() [3/3]
mim::Nest::Nest (World & world)
Virtual root with all World::externals as children.
Definition at line 24 of file nest.cpp.
References mim::closed_muts(), and world().
Member Function Documentation
contains()
bool mim::Nest::contains (const Def * def) const inline
Definition at line 121 of file nest.h.
References mim::Def::free_vars(), mim::PooledSet< T >::intersects(), and vars().
Referenced by mim::plug::clos::free_defs(), and mim::Scheduler::Scheduler().
dot() [1/2]
void mim::Nest::dot (const char * file = nullptr) const
Definition at line 159 of file dot.cpp.
References dot().
dot() [2/2]
void mim::Nest::dot (std::ostream & os) const
Definition at line 168 of file dot.cpp.
References mim::println(), mim::Tab::println(), and root().
Referenced by dot(), and main().
is_recursive()
bool mim::Nest::is_recursive () const inline
Definition at line 122 of file nest.h.
References mim::Nest::Node::is_recursive(), and root().
Referenced by mim::LamSpec::rewrite().
lca()
const Nest::Node * mim::Nest::lca (const Node * n, const Node * m) static
Least common ancestor of n and m.
Definition at line 106 of file nest.cpp.
References mim::Nest::Node::level(), and mim::Nest::Node::parent().
mut2node()
const Node * mim::Nest::mut2node (Def * mut) const inline
Definition at line 129 of file nest.h.
Referenced by operator[](), and mim::post_order().
nodes()
const auto & mim::Nest::nodes () const inline
Definition at line 127 of file nest.h.
Referenced by mim::Scheduler::Scheduler().
num_nodes()
size_t mim::Nest::num_nodes () const inline
Definition at line 128 of file nest.h.
operator[]()
const Node * mim::Nest::operator[] (Def * mut) const inline
Same as above.
Definition at line 133 of file nest.h.
References mut2node().
root() [1/2]
Node * mim::Nest::root () inline
Definition at line 118 of file nest.h.
Referenced by dot(), mim::plug::clos::free_defs(), is_recursive(), mim::Scheduler::root(), and mim::Scheduler::schedule().
root() [2/2]
const Node * mim::Nest::root () const inline
Definition at line 119 of file nest.h.
vars()
Vars mim::Nest::vars () const inline
All Vars occurring in this Nest.
Definition at line 120 of file nest.h.
Referenced by contains().
world()
World & mim::Nest::world () const inline
Definition at line 117 of file nest.h.
Referenced by Nest(), and mim::Scheduler::world().
The documentation for this class was generated from the following files:
include/mim/nest.h
src/mim/dot.cpp
src/mim/nest.cpp