Thorin: thorin::Tab Class Reference
thorin::Tab Class Reference
Keeps track of indentation level.
#include <thorin/util/print.h>
Public Member Functions
Tab (std::string_view tab={" "}, size_t indent=0)
template<class... Args>
std::ostream & print (std::ostream &os, const char *s, Args &&... args)
Wraps thorin::print to prefix it with indentation.
template<class... Args>
std::ostream & lnprint (std::ostream &os, const char *s, Args &&... args)
Same as Tab::print but prepends a std::endl to os.
template<class... Args>
std::ostream & println (std::ostream &os, const char *s, Args &&... args)
Same as Tab::print but appends a std::endl to os.
getters
size_t indent () const
std::string_view tab () const
creates a new Tab
Tab operator++ (int) const
Tab operator-- (int) const
Tab operator+ (size_t indent) const
Tab operator- (size_t indent) const
modifies this Tab
Tab & operator++ ()
Tab & operator-- ()
Tab & operator+= (size_t indent)
Tab & operator-= (size_t indent)
Tab & operator= (size_t indent)
Tab & operator= (std::string_view tab)
Detailed Description
Keeps track of indentation level.
Definition at line 159 of file print.h.
Constructor & Destructor Documentation
Tab()
thorin::Tab::Tab (std::string_view tab = {" "}, size_t indent = 0) inline
Definition at line 161 of file print.h.
Member Function Documentation
indent()
size_t thorin::Tab::indent () const inline
Definition at line 184 of file print.h.
Referenced by operator+(), operator+=(), operator-(), operator-=(), and operator=().
lnprint()
template<class... Args> std::ostream & thorin::Tab::lnprint (std::ostream & os, const char * s, Args &&... args) inline
Same as Tab::print but prepends a std::endl to os.
Definition at line 173 of file print.h.
References print().
operator+()
Tab thorin::Tab::operator+ (size_t indent) const inline
Definition at line 193 of file print.h.
References indent().
operator++() [1/2]
Tab & thorin::Tab::operator++ () inline
Definition at line 199 of file print.h.
operator++() [2/2]
Tab thorin::Tab::operator++ (int) const inline
Definition at line 191 of file print.h.
operator+=()
Tab & thorin::Tab::operator+= (size_t indent) inline
Definition at line 201 of file print.h.
References indent().
operator-()
Tab thorin::Tab::operator- (size_t indent) const inline
Definition at line 194 of file print.h.
References indent().
operator--() [1/2]
Tab & thorin::Tab::operator-- () inline
Definition at line 200 of file print.h.
operator--() [2/2]
Tab thorin::Tab::operator-- (int) const inline
Definition at line 192 of file print.h.
operator-=()
Tab & thorin::Tab::operator-= (size_t indent) inline
Definition at line 202 of file print.h.
References indent().
operator=() [1/2]
Tab & thorin::Tab::operator= (size_t indent) inline
Definition at line 203 of file print.h.
References indent().
operator=() [2/2]
Tab & thorin::Tab::operator= (std::string_view tab) inline
Definition at line 204 of file print.h.
References tab().
print()
template<class... Args> std::ostream & thorin::Tab::print (std::ostream & os, const char * s, Args &&... args) inline
Wraps thorin::print to prefix it with indentation.
Definition at line 167 of file print.h.
References thorin::print().
Referenced by thorin::bootstrap(), thorin::Dumper::dump(), thorin::Dumper::dump_let(), thorin::ll::Emitter::finalize(), lnprint(), and println().
println()
template<class... Args> std::ostream & thorin::Tab::println (std::ostream & os, const char * s, Args &&... args) inline
Same as Tab::print but appends a std::endl to os.
Definition at line 178 of file print.h.
References print().
Referenced by thorin::Dumper::dump().
tab()
std::string_view thorin::Tab::tab () const inline
Definition at line 185 of file print.h.
Referenced by operator=().
The documentation for this class was generated from the following file:
thorin/util/print.h