Thorin: thorin::World Class Reference
thorin::World Class Reference
The World represents the whole program and manages creation of Thorin nodes (Defs).
#include <thorin/world.h>
Classes
struct BreakHash
struct SeaHash
Public Member Functions
World (World &&)=delete
World & operator= (const World &)=delete
World (std::string_view name={})
World (const World &other)
Inherits the World::state_ of the other World but does not perform a copy.
~World ()
getters
std::string_view name () const
std::vector< Lam * > copy_lams () const
manage global identifier - a unique number for each Def
u32 curr_gid () const
u32 next_gid ()
Space, Kind, Var, Proxy
const Space * space () const
const Kind * kind () const
const Var * var (const Def *type, Def *nom, const Def *dbg={})
const Proxy * proxy (const Def *type, Defs ops, tag_t index, flags_t flags, const Def *dbg={})
Axiom
const Axiom * axiom (Def::NormalizeFn normalize, const Def *type, tag_t tag, flags_t flags, const Def *dbg={})
const Axiom * axiom (const Def *type, tag_t tag, flags_t flags, const Def *dbg={})
const Axiom * axiom (const Def *type, const Def *dbg={})
Builds a fresh Axiom with descending tag.
Pi
const Pi * pi (const Def *dom, const Def *codom, const Def *dbg={})
const Pi * pi (Defs dom, const Def *codom, const Def *dbg={})
Pi * nom_pi (const Def *type, const Def *dbg={})
Pi: continuation type (cn), i.e., Pi type with codom Bottom
const Pi * cn ()
const Pi * cn (const Def *dom, const Def *dbg={})
const Pi * cn (Defs doms, const Def *dbg={})
const Pi * cn_mem (const Def *dom, const Def *dbg={})
Same as World::cn / World::pi but adds a World::type_mem-typed Var to each Pi.
const Pi * cn_mem_ret (const Def *dom, const Def *ret_dom, const Def *dbg={})
const Pi * pi_mem (const Def *domain, const Def *codomain, const Def *dbg={})
const Pi * fn_mem (const Def *domain, const Def *codomain, const Def *dbg={})
Lambda
Lam * nom_lam (const Pi *cn, Lam::CC cc=Lam::CC::C, const Def *dbg={})
Lam * nom_lam (const Pi *cn, const Def *dbg={})
const Lam * lam (const Pi *pi, const Def *filter, const Def *body, const Def *dbg)
const Lam * lam (const Pi *pi, const Def *body, const Def *dbg)
App
const Def * app (const Def *callee, const Def *arg, const Def *dbg={})
const Def * app (const Def *callee, Defs args, const Def *dbg={})
const Def * raw_app (const Def *callee, const Def *arg, const Def *dbg={})
Same as World::app but does not apply NormalizeFn.
const Def * raw_app (const Def *callee, Defs args, const Def *dbg={})
Same as World::app but does not apply NormalizeFn.
Sigma
Sigma * nom_sigma (const Def *type, size_t size, const Def *dbg={})
Sigma * nom_sigma (size_t size, const Def *dbg={})
A *nom*inal Sigma of type Kind.
const Def * sigma (Defs ops, const Def *dbg={})
const Sigma * sigma ()
The unit type within Kind.
Arr
Arr * nom_arr (const Def *type, const Def *shape, const Def *dbg={})
Arr * nom_arr (const Def *shape, const Def *dbg={})
const Def * arr (const Def *shape, const Def *body, const Def *dbg={})
const Def * arr (Defs shape, const Def *body, const Def *dbg={})
const Def * arr (u64 n, const Def *body, const Def *dbg={})
const Def * arr (ArrayRef< u64 > shape, const Def *body, const Def *dbg={})
const Def * arr_unsafe (const Def *body, const Def *dbg={})
Tuple
const Def * tuple (Defs ops, const Def *dbg={})
const Def * tuple (const Def *type, Defs ops, const Def *dbg={})
Ascribes type to this tuple - needed for dependently typed and nominal Sigmas.
const Def * tuple_str (std::string_view s, const Def *dbg={})
Sym sym (std::string_view s, const Def *dbg={})
const Tuple * tuple ()
the unit value of type []
Pack
const Def * pack (const Def *arity, const Def *body, const Def *dbg={})
const Def * pack (Defs shape, const Def *body, const Def *dbg={})
const Def * pack (u64 n, const Def *body, const Def *dbg={})
const Def * pack (ArrayRef< u64 > shape, const Def *body, const Def *dbg={})
Extract
const Def * extract (const Def *tup, const Def *i, const Def *dbg={})
const Def * extract (const Def *tup, u64 a, u64 i, const Def *dbg={})
const Def * extract (const Def *tup, u64 i, const Def *dbg={})
const Def * extract_unsafe (const Def *tup, u64 i, const Def *dbg={})
const Def * extract_unsafe (const Def *tup, const Def *i, const Def *dbg={})
const Def * extract_ (const Def *ex_type, const Def *tup, const Def *i, const Def *dbg={})
During a rebuild we cannot infer the type if it is not set yet; in this case we rely on ex_type.
const Def * select (const Def *t, const Def *f, const Def *cond, const Def *dbg={})
Builds (f, t)cond.
Insert
const Def * insert (const Def *tup, const Def *i, const Def *val, const Def *dbg={})
const Def * insert (const Def *tup, u64 a, u64 i, const Def *val, const Def *dbg={})
const Def * insert (const Def *tup, u64 i, const Def *val, const Def *dbg={})
const Def * insert_unsafe (const Def *tup, u64 i, const Def *val, const Def *dbg={})
const Def * insert_unsafe (const Def *tup, const Def *i, const Def *val, const Def *dbg={})
Lit
const Lit * lit (const Def *type, u64 val, const Def *dbg={})
const Lit * lit_nat (nat_t a, const Def *dbg={})
const Lit * lit_nat_0 ()
const Lit * lit_nat_1 ()
const Lit * lit_nat_max ()
const Lit * lit_int (const Def *type, u64 val, const Def *dbg={})
const Lit * lit_int_width (nat_t width, u64 val, const Def *dbg={})
Constructs Tag::Int Lit val via width, i.e. converts from width to internal mod value.
const Lit * lit_int_mod (nat_t mod, u64 val, const Def *dbg={})
Constructs Tag::Int Lit val with external mod.
const Lit * lit_int (nat_t mod, u64 val, const Def *dbg={})
Constructs Tag::Int Lit val with internal mod, i.e.
template<class I >
const Lit * lit_int (I val, const Def *dbg={})
const Lit * lit_bool (bool val)
const Lit * lit_false ()
const Lit * lit_true ()
const Lit * lit_real (nat_t width, r64 val, const Def *dbg={})
template<class R >
const Lit * lit_real (R val, const Def *dbg={})
set operations
template<bool up>
const Def * ext (const Def *type, const Def *dbg={})
const Def * bot (const Def *type, const Def *dbg={})
const Def * top (const Def *type, const Def *dbg={})
const Def * bot_kind ()
const Def * top_nat ()
template<bool up>
TBound< up > * nom_bound (const Def *type, size_t size, const Def *dbg={})
template<bool up>
TBound< up > * nom_bound (size_t size, const Def *dbg={})
A nom Bound of type Kind.
template<bool up>
const Def * bound (Defs ops, const Def *dbg={})
Join * nom_join (const Def *type, size_t size, const Def *dbg={})
Meet * nom_meet (const Def *type, size_t size, const Def *dbg={})
Join * nom_join (size_t size, const Def *dbg={})
Meet * nom_meet (size_t size, const Def *dbg={})
const Def * join (Defs ops, const Def *dbg={})
const Def * meet (Defs ops, const Def *dbg={})
const Def * et (const Def *type, Defs ops, const Def *dbg={})
const Def * et (Defs ops, const Def *dbg={})
Infers the type using a structural Meet.
const Def * vel (const Def *type, const Def *value, const Def *dbg={})
const Def * pick (const Def *type, const Def *value, const Def *dbg={})
const Def * test (const Def *value, const Def *probe, const Def *match, const Def *clash, const Def *dbg={})
globals – depdrecated; will be removed
Global * global (const Def *type, bool is_mutable=true, const Def *dbg={})
Global * global_immutable_string (std::string_view str, const Def *dbg={})
types
const Nat * type_nat ()
const Axiom * type_mem ()
const Axiom * type_int ()
const Axiom * type_real ()
const Axiom * type_ptr ()
const App * type_bool ()
const App * type_int_width (nat_t width)
const App * type_int (nat_t mod)
const App * type_real (nat_t width)
const App * type_int (const Def *mod)
const App * type_real (const Def *width)
const App * type_ptr (const Def *pointee, nat_t addr_space=AddrSpace::Generic, const Def *dbg={})
const App * type_ptr (const Def *pointee, const Def *addr_space, const Def *dbg={})
bulitin axioms
const Axiom * ax (Acc o) const
const Axiom * ax (Bit o) const
const Axiom * ax (Conv o) const
const Axiom * ax (Div o) const
const Axiom * ax (ICmp o) const
const Axiom * ax (PE o) const
const Axiom * ax (RCmp o) const
const Axiom * ax (ROp o) const
const Axiom * ax (Shr o) const
const Axiom * ax (Trait o) const
const Axiom * ax (Wrap o) const
const Axiom * ax_alloc () const
const Axiom * ax_atomic () const
const Axiom * ax_bitcast () const
const Axiom * ax_lea () const
const Axiom * ax_malloc () const
const Axiom * ax_mslot () const
const Axiom * ax_zip () const
const Axiom * ax_for () const
const Axiom * ax_load () const
const Axiom * ax_remem () const
const Axiom * ax_slot () const
const Axiom * ax_store () const
fn - these guys yield the final function to be invoked for the various operations
const Def * fn (Bit o, const Def *mod, const Def *dbg={})
const Def * fn (Conv o, const Def *dst_w, const Def *src_w, const Def *dbg={})
const Def * fn (Div o, const Def *mod, const Def *dbg={})
const Def * fn (ICmp o, const Def *mod, const Def *dbg={})
const Def * fn (RCmp o, const Def *rmode, const Def *width, const Def *dbg={})
const Def * fn (ROp o, const Def *rmode, const Def *width, const Def *dbg={})
const Def * fn (Shr o, const Def *mod, const Def *dbg={})
const Def * fn (Wrap o, const Def *wmode, const Def *mod, const Def *dbg={})
template<class O >
const Def * fn (O o, nat_t size, const Def *dbg={})
template<class O >
const Def * fn (O o, nat_t other, nat_t size, const Def *dbg={})
const Def * fn_atomic (const Def *fn, const Def *dbg={})
const Def * fn_bitcast (const Def *dst_t, const Def *src_t, const Def *dbg={})
const Def * fn_for (Defs params)
op - these guys build the final function application for the various operations
const Def * op (Bit o, const Def *a, const Def *b, const Def *dbg={})
const Def * op (Div o, const Def *mem, const Def *a, const Def *b, const Def *dbg={})
const Def * op (ICmp o, const Def *a, const Def *b, const Def *dbg={})
const Def * op (RCmp o, const Def *rmode, const Def *a, const Def *b, const Def *dbg={})
const Def * op (ROp o, const Def *rmode, const Def *a, const Def *b, const Def *dbg={})
const Def * op (Shr o, const Def *a, const Def *b, const Def *dbg={})
const Def * op (Wrap o, const Def *wmode, const Def *a, const Def *b, const Def *dbg={})
template<class O >
const Def * op (O o, nat_t mode, const Def *a, const Def *b, const Def *dbg={})
const Def * op (Conv o, const Def *dst_type, const Def *src, const Def *dbg={})
const Def * op (Trait o, const Def *type, const Def *dbg={})
const Def * op (PE o, const Def *def, const Def *dbg={})
const Def * op (Acc o, const Def *a, const Def *b, const Def *body, const Def *dbg={})
const Def * op_atomic (const Def *fn, Defs args, const Def *dbg={})
const Def * op_bitcast (const Def *dst_type, const Def *src, const Def *dbg={})
const Def * op_lea (const Def *ptr, const Def *index, const Def *dbg={})
const Def * op_lea_unsafe (const Def *ptr, u64 i, const Def *dbg={})
const Def * op_lea_unsafe (const Def *ptr, const Def *i, const Def *dbg={})
const Def * op_remem (const Def *mem, const Def *dbg={})
const Def * op_load (const Def *mem, const Def *ptr, const Def *dbg={})
const Def * op_store (const Def *mem, const Def *ptr, const Def *val, const Def *dbg={})
const Def * op_alloc (const Def *type, const Def *mem, const Def *dbg={})
const Def * op_slot (const Def *type, const Def *mem, const Def *dbg={})
const Def * op_malloc (const Def *type, const Def *mem, const Def *dbg={})
const Def * op_mslot (const Def *type, const Def *mem, const Def *id, const Def *dbg={})
const Def * op_for (const Def *mem, const Def *start, const Def *stop, const Def *step, Defs inits, const Def *body, const Def *brk)
wrappers for unary operations
const Def * op_negate (const Def *a, const Def *dbg={})
const Def * op_rminus (const Def *rmode, const Def *a, const Def *dbg={})
const Def * op_wminus (const Def *wmode, const Def *a, const Def *dbg={})
const Def * op_rminus (nat_t rmode, const Def *a, const Def *dbg={})
const Def * op_wminus (nat_t wmode, const Def *a, const Def *dbg={})
helpers
const Def * dbg (Debug)
const Def * infer (const Def *def)
const Def * infer_kind (Defs) const
partial evaluation done?
void mark_pe_done (bool flag=true)
bool is_pe_done () const
stream
Stream & stream (Stream &) const
Stream & stream (RecStreamer &, const DepNode *) const
void debug_stream ()
Stream thorin if World::State::min_level is LogLevel::Debug.
error handling
void set (std::unique_ptr< ErrorHandler > &&err)
ErrorHandler * err ()
Public Member Functions inherited from thorin::Streamable< World >
void write (std::string_view filename) const
Writes to a file with name filename.
void dump () const
Writes to stdout.
std::string to_string () const
Streams to string.
Friends
void swap (World &w1, World &w2)
DefArray Def::reduce (const Def *)
Sea of Nodes
using Sea = HashSet< const Def *, SeaHash >
This HashSet contains Thorin's "sea of nodes".
const Sea & defs () const
Manage Externals
using Externals = HashMap< std::string, Def *, StrViewHash >
using VisitFn = std::function< void(const Scope &)>
const Externals & externals () const
bool empty ()
void make_external (Def *def)
void make_internal (Def *def)
bool is_external (const Def *def)
Def * lookup (std::string_view name)
template<bool elide_empty = true>
void visit (VisitFn) const
Transitively visits all reachable Scopes in this World that do not have free variables.
Debugging Features
using Breakpoints = HashSet< u32, BreakHash >
void breakpoint (size_t number)
void use_breakpoint (size_t number)
void enable_history (bool flag=true)
bool track_history () const
const Def * gid2def (u32 gid)
Logging
Stream & stream ()
LogLevel min_level () const
void set (LogLevel min_level)
void set (std::shared_ptr< Stream > stream)
template<class... Args>
void log (LogLevel level, Loc loc, const char *fmt, Args &&... args)
void log () const
for DLOG in Release build.
template<class... Args>
void error (Loc loc, const char *fmt, Args &&... args)
template<class... Args>
void idef (const Def *def, const char *fmt, Args &&... args)
template<class... Args>
void wdef (const Def *def, const char *fmt, Args &&... args)
template<class... Args>
void edef (const Def *def, const char *fmt, Args &&... args)
static std::string_view level2string (LogLevel level)
static int level2color (LogLevel level)
static std::string colorize (std::string_view str, int color)
Detailed Description
The World represents the whole program and manages creation of Thorin nodes (Defs).
Structural Defs are hashed into an internal HashSet. The getters just calculate a hash and lookup the Def, if it is already present, or create a new one otherwise. This corresponds to value numbering.
You can create several worlds. All worlds are completely independent from each other.
Note that types are also just Defs and will be hashed as well.
Definition at line 37 of file world.h.
Member Typedef Documentation
Breakpoints
using thorin::World::Breakpoints = HashSet<u32, BreakHash>
Definition at line 538 of file world.h.
Externals
using thorin::World::Externals = HashMap<std::string, Def*, StrViewHash>
Definition at line 512 of file world.h.
Sea
using thorin::World::Sea = HashSet<const Def*, SeaHash>
This HashSet contains Thorin's "sea of nodes".
Definition at line 59 of file world.h.
VisitFn
using thorin::World::VisitFn = std::function<void(const Scope&)>
Definition at line 521 of file world.h.
Constructor & Destructor Documentation
World() [1/3]
thorin::World::World (World &&) delete
World() [2/3]
thorin::World::World (std::string_view name = {}) explicit
Definition at line 33 of file world.cpp.
References thorin::Tag::Alloc, arr(), thorin::as(), thorin::Tag::Atomic, axiom(), thorin::Tag::Bitcast, cn(), cn_mem_ret(), CODE, dbg(), extract(), thorin::Tag::For, thorin::hlt, thorin::Tag::Int, kind(), thorin::known, thorin::Tag::LEA, lit_int(), lit_nat(), thorin::Tag::Load, thorin::Tag::Malloc, thorin::Tag::Mem, thorin::Tag::Mslot, name(), nom_arr(), nom_pi(), nom_sigma(), thorin::normalize_bitcast(), thorin::normalize_lea(), thorin::normalize_load(), thorin::normalize_remem(), thorin::normalize_store(), thorin::normalize_zip(), thorin::o, thorin::op2str(), thorin::Tag::PE, pi(), thorin::Tag::Ptr, thorin::r2r, thorin::r2s, thorin::r2u, thorin::Tag::Real, thorin::Tag::Remem, thorin::run, thorin::s2r, thorin::Pi::set_codom(), thorin::Pi::set_dom(), sigma(), thorin::Tag::Slot, space(), thorin::Tag::Store, THORIN_ACC, THORIN_BIT, THORIN_CONV, THORIN_DIV, THORIN_I_CMP, THORIN_R_CMP, THORIN_R_OP, THORIN_SHR, THORIN_TRAIT, THORIN_WRAP, type_bool(), type_int(), type_nat(), type_ptr(), type_real(), thorin::u2r, thorin::Def::var(), thorin::Def::vars(), and thorin::Tag::Zip.
World() [3/3]
thorin::World::World (const World & other) inline explicit
Inherits the World::state_ of the other World but does not perform a copy.
Definition at line 44 of file world.h.
~World()
thorin::World::~World ()
Definition at line 282 of file world.cpp.
Member Function Documentation
app() [1/2]
const Def * thorin::World::app (const Def * callee, const Def * arg, const Def * dbg = {})
Definition at line 290 of file world.cpp.
References thorin::RuntimeCast< Base >::as(), axiom(), thorin::Array< T >::back(), dbg(), thorin::Pi::dom(), err(), thorin::Axiom::get(), thorin::ErrorHandler::ill_typed_app(), thorin::Axiom::normalizer(), pi(), thorin::Def::reduce(), and thorin::Def::type().
Referenced by fn_for(), op_for(), op_lea(), op_malloc(), op_mslot(), thorin::App::rebuild(), thorin::Def::reduce_rec(), type_int(), and type_real().
app() [2/2]
const Def * thorin::World::app (const Def * callee, Defs args, const Def * dbg = {}) inline
Definition at line 146 of file world.h.
arr() [1/4]
const Def * thorin::World::arr (ArrayRef< u64 > shape, const Def * body, const Def * dbg = {}) inline
Definition at line 169 of file world.h.
arr() [2/4]
const Def * thorin::World::arr (const Def * shape, const Def * body, const Def * dbg = {})
Definition at line 460 of file world.cpp.
References thorin::a, arr(), dbg(), err(), thorin::ErrorHandler::expected_shape(), thorin::is_shape(), thorin::RuntimeCast< Base >::isa(), thorin::isa_lit(), kind(), thorin::Def::ops(), pack(), sigma(), tuple(), and thorin::Def::type().
Referenced by arr(), ext(), pack(), thorin::Arr::rebuild(), sigma(), and World().
arr() [3/4]
const Def * thorin::World::arr (Defs shape, const Def * body, const Def * dbg = {})
Definition at line 503 of file world.cpp.
References arr(), thorin::ArrayRef< T >::back(), dbg(), thorin::ArrayRef< T >::empty(), and thorin::ArrayRef< T >::skip_back().
arr() [4/4]
const Def * thorin::World::arr (u64 n, const Def * body, const Def * dbg = {}) inline
Definition at line 168 of file world.h.
arr_unsafe()
const Def * thorin::World::arr_unsafe (const Def * body, const Def * dbg = {}) inline
Definition at line 172 of file world.h.
ax() [1/11]
const Axiom * thorin::World::ax (Acc o) const inline
Definition at line 357 of file world.h.
References thorin::o.
ax() [2/11]
const Axiom * thorin::World::ax (Bit o) const inline
Definition at line 358 of file world.h.
References thorin::o.
ax() [3/11]
const Axiom * thorin::World::ax (Conv o) const inline
Definition at line 359 of file world.h.
References thorin::o.
ax() [4/11]
const Axiom * thorin::World::ax (Div o) const inline
Definition at line 360 of file world.h.
References thorin::o.
ax() [5/11]
const Axiom * thorin::World::ax (ICmp o) const inline
Definition at line 361 of file world.h.
References thorin::o.
ax() [6/11]
const Axiom * thorin::World::ax (PE o) const inline
Definition at line 362 of file world.h.
References thorin::o.
ax() [7/11]
const Axiom * thorin::World::ax (RCmp o) const inline
Definition at line 363 of file world.h.
References thorin::o.
ax() [8/11]
const Axiom * thorin::World::ax (ROp o) const inline
Definition at line 364 of file world.h.
References thorin::o.
ax() [9/11]
const Axiom * thorin::World::ax (Shr o) const inline
Definition at line 365 of file world.h.
References thorin::o.
ax() [10/11]
const Axiom * thorin::World::ax (Trait o) const inline
Definition at line 366 of file world.h.
References thorin::o.
ax() [11/11]
const Axiom * thorin::World::ax (Wrap o) const inline
Definition at line 367 of file world.h.
References thorin::o.
ax_alloc()
const Axiom * thorin::World::ax_alloc () const inline
Definition at line 368 of file world.h.
ax_atomic()
const Axiom * thorin::World::ax_atomic () const inline
Definition at line 369 of file world.h.
ax_bitcast()
const Axiom * thorin::World::ax_bitcast () const inline
Definition at line 370 of file world.h.
ax_for()
const Axiom * thorin::World::ax_for () const inline
Definition at line 375 of file world.h.
Referenced by fn_for().
ax_lea()
const Axiom * thorin::World::ax_lea () const inline
Definition at line 371 of file world.h.
Referenced by op_lea().
ax_load()
const Axiom * thorin::World::ax_load () const inline
Definition at line 376 of file world.h.
ax_malloc()
const Axiom * thorin::World::ax_malloc () const inline
Definition at line 372 of file world.h.
Referenced by op_malloc().
ax_mslot()
const Axiom * thorin::World::ax_mslot () const inline
Definition at line 373 of file world.h.
Referenced by op_mslot().
ax_remem()
const Axiom * thorin::World::ax_remem () const inline
Definition at line 377 of file world.h.
ax_slot()
const Axiom * thorin::World::ax_slot () const inline
Definition at line 378 of file world.h.
ax_store()
const Axiom * thorin::World::ax_store () const inline
Definition at line 379 of file world.h.
ax_zip()
const Axiom * thorin::World::ax_zip () const inline
Definition at line 374 of file world.h.
axiom() [1/3]
const Axiom * thorin::World::axiom (const Def * type, const Def * dbg = {}) inline
Builds a fresh Axiom with descending tag.
This is useful during testing to come up with some entitiy of a specific type. It starts with tag_t(-1) (aka max) for Axiom::tag and counts down from there. The Axiom::flags are set to 0 and the Axiom::normalizer to nullptr.
Definition at line 99 of file world.h.
axiom() [2/3]
const Axiom * thorin::World::axiom (const Def * type, tag_t tag, flags_t flags, const Def * dbg = {}) inline
Definition at line 91 of file world.h.
axiom() [3/3]
const Axiom * thorin::World::axiom (Def::NormalizeFn normalize, const Def * type, tag_t tag, flags_t flags, const Def * dbg = {}) inline
Definition at line 88 of file world.h.
Referenced by app(), raw_app(), thorin::Axiom::rebuild(), and World().
bot()
const Def * thorin::World::bot (const Def * type, const Def * dbg = {}) inline
Definition at line 296 of file world.h.
Referenced by dbg(), thorin::fold(), thorin::fold_Conv(), and thorin::normalize_bitcast().
bot_kind()
const Def * thorin::World::bot_kind () inline
Definition at line 298 of file world.h.
Referenced by dbg().
bound()
template<bool up> template const Def * thorin::World::bound< false > (Defs ops, const Def * dbg = {})
Definition at line 552 of file world.cpp.
References thorin::Array< T >::begin(), dbg(), infer_kind(), thorin::RuntimeCast< Base >::isa(), kind(), op(), thorin::Array< T >::shrink(), and thorin::Array< T >::size().
Referenced by thorin::TBound< up >::rebuild().
breakpoint()
void thorin::World::breakpoint (size_t number)
Definition at line 667 of file world.cpp.
cn() [1/3]
const Pi * thorin::World::cn () inline
Definition at line 113 of file world.h.
References cn(), and sigma().
Referenced by cn(), and World().
cn() [2/3]
const Pi * thorin::World::cn (const Def * dom, const Def * dbg = {}) inline
Definition at line 114 of file world.h.
cn() [3/3]
const Pi * thorin::World::cn (Defs doms, const Def * dbg = {}) inline
Definition at line 115 of file world.h.
cn_mem()
const Pi * thorin::World::cn_mem (const Def * dom, const Def * dbg = {}) inline
Same as World::cn / World::pi but adds a World::type_mem-typed Var to each Pi.
Definition at line 117 of file world.h.
cn_mem_ret()
const Pi * thorin::World::cn_mem_ret (const Def * dom, const Def * ret_dom, const Def * dbg = {}) inline
Definition at line 118 of file world.h.
Referenced by World().
colorize()
std::string thorin::World::colorize (std::string_view str, int color) static
Definition at line 767 of file world.cpp.
Referenced by log().
copy_lams()
std::vector< Lam * > thorin::World::copy_lams () const
Definition at line 655 of file world.cpp.
References thorin::Def::isa_nom(), and lam().
curr_gid()
u32 thorin::World::curr_gid () const inline
Definition at line 72 of file world.h.
dbg()
const Def * thorin::World::dbg (Debug d)
Definition at line 684 of file world.cpp.
References thorin::Loc::begin, bot(), bot_kind(), thorin::Loc::file, thorin::Loc::finis, lit_nat(), thorin::Debug::loc, thorin::Debug::meta, thorin::Debug::name, name(), tuple(), and tuple_str().
Referenced by app(), arr(), bound(), et(), ext(), extract_(), global_immutable_string(), insert(), lam(), lit_int(), op_lea(), op_malloc(), op_mslot(), pack(), pick(), raw_app(), sigma(), test(), tuple(), tuple_str(), vel(), and World().
debug_stream()
void thorin::World::debug_stream ()
Stream thorin if World::State::min_level is LogLevel::Debug.
Definition at line 288 of file stream.cpp.
References thorin::Debug, min_level(), and stream().
Referenced by thorin::PassMan::run().
defs()
const Sea & thorin::World::defs () const inline
Definition at line 61 of file world.h.
Referenced by thorin::cleanup(), infer_kind(), and visit().
edef()
template<class... Args> void thorin::World::edef (const Def * def, const char * fmt, Args &&... args) inline
Definition at line 574 of file world.h.
References thorin::Def::debug(), error(), and thorin::Debug::loc.
empty()
bool thorin::World::empty () inline
Definition at line 514 of file world.h.
enable_history()
void thorin::World::enable_history (bool flag = true)
Definition at line 669 of file world.cpp.
err()
ErrorHandler * thorin::World::err () inline
Definition at line 592 of file world.h.
Referenced by app(), arr(), extract_(), insert(), lit_int(), pack(), set(), test(), and tuple().
error()
template<class... Args> void thorin::World::error (Loc loc, const char * fmt, Args &&... args) inline
Definition at line 566 of file world.h.
References thorin::Error, and log().
Referenced by edef().
et() [1/2]
const Def * thorin::World::et (const Def * type, Defs ops, const Def * dbg = {})
Definition at line 576 of file world.cpp.
References dbg(), thorin::RuntimeCast< Base >::isa(), meet(), and thorin::ArrayRef< T >::size().
Referenced by thorin::Et::rebuild().
et() [2/2]
const Def * thorin::World::et (Defs ops, const Def * dbg = {}) inline
Infers the type using a structural Meet.
Definition at line 319 of file world.h.
ext()
template<bool up> template const Def * thorin::World::ext< false > (const Def * type, const Def * dbg = {})
Definition at line 544 of file world.cpp.
References arr(), dbg(), thorin::RuntimeCast< Base >::isa(), thorin::Def::num_ops(), pack(), sigma(), and tuple().
externals()
const Externals & thorin::World::externals () const inline
Definition at line 513 of file world.h.
Referenced by thorin::cleanup(), stream(), and visit().
extract() [1/3]
const Def * thorin::World::extract (const Def * tup, const Def * i, const Def * dbg = {}) inline
Definition at line 197 of file world.h.
Referenced by extract_(), thorin::Def::proj(), tuple(), and World().
extract() [2/3]
const Def * thorin::World::extract (const Def * tup, u64 a, u64 i, const Def * dbg = {}) inline
Definition at line 198 of file world.h.
extract() [3/3]
const Def * thorin::World::extract (const Def * tup, u64 i, const Def * dbg = {}) inline
Definition at line 201 of file world.h.
extract_()
const Def * thorin::World::extract_ (const Def * ex_type, const Def * tup, const Def * i, const Def * dbg = {})
During a rebuild we cannot infer the type if it is not set yet; in this case we rely on ex_type.
Definition at line 380 of file world.cpp.
References thorin::Def::arity(), thorin::as_lit(), dbg(), err(), extract(), thorin::ErrorHandler::index_out_of_range(), insert(), thorin::RuntimeCast< Base >::isa(), thorin::isa_lit(), thorin::Def::isa_nom(), thorin::isa_sized_type(), thorin::Def::isa_structural(), thorin::Def::num_ops(), thorin::Def::op(), pack(), thorin::Def::proj(), thorin::Def::reduce_rec(), sigma(), tuple(), and thorin::Def::type().
Referenced by thorin::Extract::rebuild().
extract_unsafe() [1/2]
const Def * thorin::World::extract_unsafe (const Def * tup, const Def * i, const Def * dbg = {}) inline
Definition at line 207 of file world.h.
extract_unsafe() [2/2]
const Def * thorin::World::extract_unsafe (const Def * tup, u64 i, const Def * dbg = {}) inline
Definition at line 204 of file world.h.
fn() [1/10]
const Def * thorin::World::fn (Bit o, const Def * mod, const Def * dbg = {}) inline
Definition at line 385 of file world.h.
fn() [2/10]
const Def * thorin::World::fn (Conv o, const Def * dst_w, const Def * src_w, const Def * dbg = {}) inline
Definition at line 386 of file world.h.
fn() [3/10]
const Def * thorin::World::fn (Div o, const Def * mod, const Def * dbg = {}) inline
Definition at line 389 of file world.h.
fn() [4/10]
const Def * thorin::World::fn (ICmp o, const Def * mod, const Def * dbg = {}) inline
Definition at line 390 of file world.h.
fn() [5/10]
template<class O > const Def * thorin::World::fn (O o, nat_t other, nat_t size, const Def * dbg = {}) inline
Definition at line 406 of file world.h.
fn() [6/10]
template<class O > const Def * thorin::World::fn (O o, nat_t size, const Def * dbg = {}) inline
Definition at line 402 of file world.h.
fn() [7/10]
const Def * thorin::World::fn (RCmp o, const Def * rmode, const Def * width, const Def * dbg = {}) inline
Definition at line 391 of file world.h.
fn() [8/10]
const Def * thorin::World::fn (ROp o, const Def * rmode, const Def * width, const Def * dbg = {}) inline
Definition at line 394 of file world.h.
fn() [9/10]
const Def * thorin::World::fn (Shr o, const Def * mod, const Def * dbg = {}) inline
Definition at line 397 of file world.h.
fn() [10/10]
const Def * thorin::World::fn (Wrap o, const Def * wmode, const Def * mod, const Def * dbg = {}) inline
Definition at line 398 of file world.h.
fn_atomic()
const Def * thorin::World::fn_atomic (const Def * fn, const Def * dbg = {}) inline
Definition at line 409 of file world.h.
fn_bitcast()
const Def * thorin::World::fn_bitcast (const Def * dst_t, const Def * src_t, const Def * dbg = {}) inline
Definition at line 410 of file world.h.
fn_for()
const Def * thorin::World::fn_for (Defs params)
Definition at line 609 of file world.cpp.
References app(), ax_for(), lit_nat(), thorin::ArrayRef< T >::size(), tuple(), and thorin::width2mod().
Referenced by op_for().
fn_mem()
const Pi * thorin::World::fn_mem (const Def * domain, const Def * codomain, const Def * dbg = {}) inline
Definition at line 125 of file world.h.
gid2def()
const Def * thorin::World::gid2def (u32 gid)
Definition at line 672 of file world.cpp.
global()
Global * thorin::World::global (const Def * type, bool is_mutable = true, const Def * dbg = {}) inline
Definition at line 327 of file world.h.
Referenced by global_immutable_string(), and thorin::Global::stub().
global_immutable_string()
Global * thorin::World::global_immutable_string (std::string_view str, const Def * dbg = {})
Definition at line 526 of file world.cpp.
References thorin::Array< T >::back(), dbg(), global(), lit_nat(), thorin::size, tuple(), and type_ptr().
idef()
template<class... Args> void thorin::World::idef (const Def * def, const char * fmt, Args &&... args) inline
Definition at line 572 of file world.h.
References thorin::Def::debug(), thorin::Info, thorin::Debug::loc, and log().
infer()
const Def * thorin::World::infer (const Def * def) inline
Definition at line 500 of file world.h.
References thorin::isa_sized_type(), and thorin::Def::type().
infer_kind()
const Def * thorin::World::infer_kind (Defs defs) const
Definition at line 696 of file world.cpp.
References defs(), and kind().
Referenced by bound(), and sigma().
insert() [1/3]
const Def * thorin::World::insert (const Def * tup, const Def * i, const Def * val, const Def * dbg = {})
Definition at line 422 of file world.cpp.
References thorin::a, thorin::Def::arity(), thorin::as_lit(), dbg(), err(), thorin::ErrorHandler::index_out_of_range(), insert(), thorin::RuntimeCast< Base >::isa(), thorin::isa_lit(), thorin::isa_sized_type(), pack(), thorin::Def::reduce_rec(), thorin::t, tuple(), and thorin::Def::type().
Referenced by extract_(), insert(), and thorin::Insert::rebuild().
insert() [2/3]
const Def * thorin::World::insert (const Def * tup, u64 a, u64 i, const Def * val, const Def * dbg = {}) inline
Definition at line 222 of file world.h.
insert() [3/3]
const Def * thorin::World::insert (const Def * tup, u64 i, const Def * val, const Def * dbg = {}) inline
Definition at line 225 of file world.h.
insert_unsafe() [1/2]
const Def * thorin::World::insert_unsafe (const Def * tup, const Def * i, const Def * val, const Def * dbg = {}) inline
Definition at line 231 of file world.h.
insert_unsafe() [2/2]
const Def * thorin::World::insert_unsafe (const Def * tup, u64 i, const Def * val, const Def * dbg = {}) inline
Definition at line 228 of file world.h.
is_external()
bool thorin::World::is_external (const Def * def) inline
Definition at line 517 of file world.h.
References thorin::Def::debug(), and thorin::Debug::name.
Referenced by thorin::Def::is_external().
is_pe_done()
bool thorin::World::is_pe_done () const inline
Definition at line 507 of file world.h.
join()
const Def * thorin::World::join (Defs ops, const Def * dbg = {}) inline
Definition at line 315 of file world.h.
Referenced by test().
kind()
const Kind * thorin::World::kind () const inline
Definition at line 79 of file world.h.
Referenced by arr(), bound(), infer_kind(), thorin::Kind::rebuild(), and World().
lam() [1/2]
const Lam * thorin::World::lam (const Pi * pi, const Def * body, const Def * dbg) inline
Definition at line 140 of file world.h.
References dbg(), lam(), lit_true(), and pi().
Referenced by lam().
lam() [2/2]
const Lam * thorin::World::lam (const Pi * pi, const Def * filter, const Def * body, const Def * dbg) inline
Definition at line 137 of file world.h.
References dbg(), and pi().
Referenced by copy_lams(), and thorin::Lam::rebuild().
level2color()
int thorin::World::level2color (LogLevel level) static
Definition at line 745 of file world.cpp.
References thorin::Debug, thorin::Error, thorin::Info, thorin::unreachable(), thorin::Verbose, and thorin::Warn.
Referenced by log().
level2string()
std::string_view thorin::World::level2string (LogLevel level) static
Definition at line 732 of file world.cpp.
References thorin::Debug, thorin::Error, thorin::Info, thorin::unreachable(), thorin::Verbose, and thorin::Warn.
Referenced by log().
lit()
const Lit * thorin::World::lit (const Def * type, u64 val, const Def * dbg = {}) inline
Definition at line 238 of file world.h.
Referenced by thorin::fold(), lit_int(), and thorin::Lit::rebuild().
lit_bool()
const Lit * thorin::World::lit_bool (bool val) inline
Definition at line 268 of file world.h.
Referenced by thorin::Lam::set_filter().
lit_false()
const Lit * thorin::World::lit_false () inline
Definition at line 269 of file world.h.
Referenced by thorin::normalize_PE().
lit_int() [1/3]
const Lit * thorin::World::lit_int (const Def * type, u64 val, const Def * dbg = {})
Definition at line 513 of file world.cpp.
References thorin::a, dbg(), err(), thorin::ErrorHandler::index_out_of_range(), thorin::isa_lit(), thorin::isa_sized_type(), thorin::l, lit(), and thorin::size.
Referenced by thorin::Bound::index(), and World().
lit_int() [2/3]
template<class I > const Lit * thorin::World::lit_int (I val, const Def * dbg = {}) inline
Definition at line 263 of file world.h.
lit_int() [3/3]
const Lit * thorin::World::lit_int (nat_t mod, u64 val, const Def * dbg = {}) inline
Constructs Tag::Int Lit val with internal mod, i.e.
without any conversions - mod = 0 means 2^64. Use this version if you directly receive an internal mod which is already converted.
Definition at line 261 of file world.h.
lit_int_mod()
const Lit * thorin::World::lit_int_mod (nat_t mod, u64 val, const Def * dbg = {}) inline
Constructs Tag::Int Lit val with external mod.
I.e. if mod == 0, it will be adjusted to uint_t(-1) (special case for 2^64).
Definition at line 255 of file world.h.
lit_int_width()
const Lit * thorin::World::lit_int_width (nat_t width, u64 val, const Def * dbg = {}) inline
Constructs Tag::Int Lit val via width, i.e. converts from width to internal mod value.
Definition at line 249 of file world.h.
lit_nat()
const Lit * thorin::World::lit_nat (nat_t a, const Def * dbg = {}) inline
Definition at line 242 of file world.h.
Referenced by thorin::Def::arity(), dbg(), fn_for(), global_immutable_string(), thorin::normalize_Trait(), tuple_str(), type_int(), type_int_width(), type_real(), and World().
lit_nat_0()
const Lit * thorin::World::lit_nat_0 () inline
Definition at line 243 of file world.h.
Referenced by op_malloc(), and op_mslot().
lit_nat_1()
const Lit * thorin::World::lit_nat_1 () inline
Definition at line 244 of file world.h.
lit_nat_max()
const Lit * thorin::World::lit_nat_max () inline
Definition at line 245 of file world.h.
lit_real() [1/2]
const Lit * thorin::World::lit_real (nat_t width, r64 val, const Def * dbg = {}) inline
Definition at line 272 of file world.h.
lit_real() [2/2]
template<class R > const Lit * thorin::World::lit_real (R val, const Def * dbg = {}) inline
Definition at line 281 of file world.h.
lit_true()
const Lit * thorin::World::lit_true () inline
Definition at line 270 of file world.h.
Referenced by lam().
log() [1/2]
void thorin::World::log () const inline
for DLOG in Release build.
Definition at line 563 of file world.h.
Referenced by error(), idef(), and wdef().
log() [2/2]
template<class... Args> void thorin::World::log (LogLevel level, Loc loc, const char * fmt, Args &&... args) inline
Definition at line 557 of file world.h.
References colorize(), thorin::Stream::endl(), thorin::Stream::flush(), thorin::Stream::fmt(), level2color(), level2string(), min_level(), stream(), and thorin::Streamable< C >::to_string().
lookup()
Def * thorin::World::lookup (std::string_view name) inline
Definition at line 519 of file world.h.
References name().
make_external()
void thorin::World::make_external (Def * def) inline
Definition at line 515 of file world.h.
References thorin::Def::name().
Referenced by thorin::Def::make_external().
make_internal()
void thorin::World::make_internal (Def * def) inline
Definition at line 516 of file world.h.
References thorin::Def::name().
Referenced by thorin::Def::make_internal().
mark_pe_done()
void thorin::World::mark_pe_done (bool flag = true) inline
Definition at line 506 of file world.h.
meet()
const Def * thorin::World::meet (Defs ops, const Def * dbg = {}) inline
Definition at line 316 of file world.h.
Referenced by et().
min_level()
LogLevel thorin::World::min_level () const inline
Definition at line 551 of file world.h.
Referenced by debug_stream(), log(), and set().
name()
std::string_view thorin::World::name () const inline
Definition at line 66 of file world.h.
Referenced by dbg(), lookup(), stream(), visit(), and World().
next_gid()
u32 thorin::World::next_gid () inline
Definition at line 73 of file world.h.
Referenced by thorin::Def::Def().
nom_arr() [1/2]
Arr * thorin::World::nom_arr (const Def * shape, const Def * dbg = {}) inline
Definition at line 165 of file world.h.
nom_arr() [2/2]
Arr * thorin::World::nom_arr (const Def * type, const Def * shape, const Def * dbg = {}) inline
Definition at line 164 of file world.h.
Referenced by thorin::Arr::stub(), and World().
nom_bound() [1/2]
template<bool up> TBound< up > * thorin::World::nom_bound (const Def * type, size_t size, const Def * dbg = {}) inline
Definition at line 301 of file world.h.
Referenced by thorin::TBound< up >::stub().
nom_bound() [2/2]
template<bool up> TBound< up > * thorin::World::nom_bound (size_t size, const Def * dbg = {}) inline
A nom Bound of type Kind.
Definition at line 306 of file world.h.
nom_join() [1/2]
Join * thorin::World::nom_join (const Def * type, size_t size, const Def * dbg = {}) inline
Definition at line 311 of file world.h.
nom_join() [2/2]
Join * thorin::World::nom_join (size_t size, const Def * dbg = {}) inline
Definition at line 313 of file world.h.
nom_lam() [1/2]
Lam * thorin::World::nom_lam (const Pi * cn, const Def * dbg = {}) inline
Definition at line 136 of file world.h.
nom_lam() [2/2]
Lam * thorin::World::nom_lam (const Pi * cn, Lam::CC cc = Lam::CC::C, const Def * dbg = {}) inline
Definition at line 132 of file world.h.
Referenced by thorin::RetWrap::enter(), and thorin::Lam::stub().
nom_meet() [1/2]
Meet * thorin::World::nom_meet (const Def * type, size_t size, const Def * dbg = {}) inline
Definition at line 312 of file world.h.
nom_meet() [2/2]
Meet * thorin::World::nom_meet (size_t size, const Def * dbg = {}) inline
Definition at line 314 of file world.h.
nom_pi()
Pi * thorin::World::nom_pi (const Def * type, const Def * dbg = {}) inline
Definition at line 108 of file world.h.
Referenced by thorin::Pi::stub(), and World().
nom_sigma() [1/2]
Sigma * thorin::World::nom_sigma (const Def * type, size_t size, const Def * dbg = {}) inline
Definition at line 155 of file world.h.
Referenced by thorin::Sigma::stub(), and World().
nom_sigma() [2/2]
Sigma * thorin::World::nom_sigma (size_t size, const Def * dbg = {}) inline
A *nom*inal Sigma of type Kind.
Definition at line 157 of file world.h.
op() [1/12]
const Def * thorin::World::op (Acc o, const Def * a, const Def * b, const Def * body, const Def * dbg = {}) inline
Definition at line 444 of file world.h.
op() [2/12]
const Def * thorin::World::op (Bit o, const Def * a, const Def * b, const Def * dbg = {}) inline
Definition at line 418 of file world.h.
Referenced by bound(), op_malloc(), op_mslot(), thorin::reassociate(), sigma(), and tuple().
op() [3/12]
const Def * thorin::World::op (Conv o, const Def * dst_type, const Def * src, const Def * dbg = {}) inline
Definition at line 437 of file world.h.
op() [4/12]
const Def * thorin::World::op (Div o, const Def * mem, const Def * a, const Def * b, const Def * dbg = {}) inline
Definition at line 419 of file world.h.
op() [5/12]
const Def * thorin::World::op (ICmp o, const Def * a, const Def * b, const Def * dbg = {}) inline
Definition at line 422 of file world.h.
op() [6/12]
template<class O > const Def * thorin::World::op (O o, nat_t mode, const Def * a, const Def * b, const Def * dbg = {}) inline
Definition at line 434 of file world.h.
op() [7/12]
const Def * thorin::World::op (PE o, const Def * def, const Def * dbg = {}) inline
Definition at line 443 of file world.h.
op() [8/12]
const Def * thorin::World::op (RCmp o, const Def * rmode, const Def * a, const Def * b, const Def * dbg = {}) inline
Definition at line 423 of file world.h.
op() [9/12]
const Def * thorin::World::op (ROp o, const Def * rmode, const Def * a, const Def * b, const Def * dbg = {}) inline
Definition at line 426 of file world.h.
op() [10/12]
const Def * thorin::World::op (Shr o, const Def * a, const Def * b, const Def * dbg = {}) inline
Definition at line 429 of file world.h.
op() [11/12]
const Def * thorin::World::op (Trait o, const Def * type, const Def * dbg = {}) inline
Definition at line 442 of file world.h.
op() [12/12]
const Def * thorin::World::op (Wrap o, const Def * wmode, const Def * a, const Def * b, const Def * dbg = {}) inline
Definition at line 430 of file world.h.
op_alloc()
const Def * thorin::World::op_alloc (const Def * type, const Def * mem, const Def * dbg = {}) inline
Definition at line 466 of file world.h.
op_atomic()
const Def * thorin::World::op_atomic (const Def * fn, Defs args, const Def * dbg = {}) inline
Definition at line 447 of file world.h.
op_bitcast()
const Def * thorin::World::op_bitcast (const Def * dst_type, const Def * src, const Def * dbg = {}) inline
Definition at line 448 of file world.h.
op_for()
const Def * thorin::World::op_for (const Def * mem, const Def * start, const Def * stop, const Def * step, Defs inits, const Def * body, const Def * brk)
Definition at line 640 of file world.cpp.
References app(), fn_for(), thorin::ArrayRef< T >::size(), and tuple().
op_lea()
const Def * thorin::World::op_lea (const Def * ptr, const Def * index, const Def * dbg = {})
Definition at line 624 of file world.cpp.
References app(), thorin::Def::arity(), ax_lea(), dbg(), thorin::tuple_of_types(), and thorin::Def::type().
op_lea_unsafe() [1/2]
const Def * thorin::World::op_lea_unsafe (const Def * ptr, const Def * i, const Def * dbg = {}) inline
Definition at line 453 of file world.h.
op_lea_unsafe() [2/2]
const Def * thorin::World::op_lea_unsafe (const Def * ptr, u64 i, const Def * dbg = {}) inline
Definition at line 452 of file world.h.
op_load()
const Def * thorin::World::op_load (const Def * mem, const Def * ptr, const Def * dbg = {}) inline
Definition at line 458 of file world.h.
op_malloc()
const Def * thorin::World::op_malloc (const Def * type, const Def * mem, const Def * dbg = {})
Definition at line 630 of file world.cpp.
References app(), ax_malloc(), dbg(), lit_nat_0(), op(), and thorin::size.
Referenced by thorin::Alloc2Malloc::rewrite().
op_mslot()
const Def * thorin::World::op_mslot (const Def * type, const Def * mem, const Def * id, const Def * dbg = {})
Definition at line 635 of file world.cpp.
References app(), ax_mslot(), dbg(), lit_nat_0(), op(), and thorin::size.
Referenced by thorin::Alloc2Malloc::rewrite().
op_negate()
const Def * thorin::World::op_negate (const Def * a, const Def * dbg = {}) inline
Definition at line 481 of file world.h.
op_remem()
const Def * thorin::World::op_remem (const Def * mem, const Def * dbg = {}) inline
Definition at line 457 of file world.h.
op_rminus() [1/2]
const Def * thorin::World::op_rminus (const Def * rmode, const Def * a, const Def * dbg = {}) inline
Definition at line 485 of file world.h.
op_rminus() [2/2]
const Def * thorin::World::op_rminus (nat_t rmode, const Def * a, const Def * dbg = {}) inline
Definition at line 493 of file world.h.
op_slot()
const Def * thorin::World::op_slot (const Def * type, const Def * mem, const Def * dbg = {}) inline
Definition at line 469 of file world.h.
op_store()
const Def * thorin::World::op_store (const Def * mem, const Def * ptr, const Def * val, const Def * dbg = {}) inline
Definition at line 462 of file world.h.
op_wminus() [1/2]
const Def * thorin::World::op_wminus (const Def * wmode, const Def * a, const Def * dbg = {}) inline
Definition at line 489 of file world.h.
op_wminus() [2/2]
const Def * thorin::World::op_wminus (nat_t wmode, const Def * a, const Def * dbg = {}) inline
Definition at line 494 of file world.h.
operator=()
World & thorin::World::operator= (const World &) delete
pack() [1/4]
const Def * thorin::World::pack (ArrayRef< u64 > shape, const Def * body, const Def * dbg = {}) inline
Definition at line 190 of file world.h.
pack() [2/4]
const Def * thorin::World::pack (const Def * arity, const Def * body, const Def * dbg = {})
Definition at line 481 of file world.cpp.
References thorin::a, arr(), dbg(), err(), thorin::ErrorHandler::expected_shape(), thorin::is_shape(), thorin::RuntimeCast< Base >::isa(), thorin::isa_lit(), thorin::Def::ops(), pack(), tuple(), and thorin::Def::type().
Referenced by arr(), ext(), extract_(), insert(), pack(), thorin::Pack::rebuild(), and tuple().
pack() [3/4]
const Def * thorin::World::pack (Defs shape, const Def * body, const Def * dbg = {})
Definition at line 508 of file world.cpp.
References thorin::ArrayRef< T >::back(), dbg(), thorin::ArrayRef< T >::empty(), pack(), and thorin::ArrayRef< T >::skip_back().
pack() [4/4]
const Def * thorin::World::pack (u64 n, const Def * body, const Def * dbg = {}) inline
Definition at line 189 of file world.h.
pi() [1/2]
const Pi * thorin::World::pi (const Def * dom, const Def * codom, const Def * dbg = {}) inline
Definition at line 104 of file world.h.
Referenced by app(), lam(), raw_app(), thorin::Pi::rebuild(), thorin::Pi::restructure(), test(), and World().
pi() [2/2]
const Pi * thorin::World::pi (Defs dom, const Def * codom, const Def * dbg = {}) inline
Definition at line 107 of file world.h.
pi_mem()
const Pi * thorin::World::pi_mem (const Def * domain, const Def * codomain, const Def * dbg = {}) inline
Definition at line 121 of file world.h.
pick()
const Def * thorin::World::pick (const Def * type, const Def * value, const Def * dbg = {})
Definition at line 591 of file world.cpp.
References dbg().
Referenced by thorin::Pick::rebuild().
proxy()
const Proxy * thorin::World::proxy (const Def * type, Defs ops, tag_t index, flags_t flags, const Def * dbg = {}) inline
Definition at line 81 of file world.h.
Referenced by thorin::Proxy::rebuild().
raw_app() [1/2]
const Def * thorin::World::raw_app (const Def * callee, const Def * arg, const Def * dbg = {})
Same as World::app but does not apply NormalizeFn.
Definition at line 306 of file world.cpp.
References thorin::RuntimeCast< Base >::as(), axiom(), thorin::Array< T >::back(), dbg(), thorin::Axiom::get(), pi(), thorin::Def::reduce(), and thorin::Def::type().
Referenced by thorin::normalize_Acc(), and thorin::normalize_remem().
raw_app() [2/2]
const Def * thorin::World::raw_app (const Def * callee, Defs args, const Def * dbg = {}) inline
Same as World::app but does not apply NormalizeFn.
Definition at line 150 of file world.h.
select()
const Def * thorin::World::select (const Def * t, const Def * f, const Def * cond, const Def * dbg = {}) inline
Builds (f, t)cond.
Note that select expects t as first argument and f as second one.
Definition at line 214 of file world.h.
set() [1/3]
void thorin::World::set (LogLevel min_level) inline
Definition at line 553 of file world.h.
References min_level().
set() [2/3]
void thorin::World::set (std::shared_ptr< Stream > stream) inline
Definition at line 554 of file world.h.
References stream().
set() [3/3]
void thorin::World::set (std::unique_ptr< ErrorHandler > && err)
Definition at line 770 of file world.cpp.
References err().
sigma() [1/2]
const Sigma * thorin::World::sigma () inline
The unit type within Kind.
Definition at line 159 of file world.h.
Referenced by arr(), cn(), ext(), extract_(), sigma(), tuple(), and World().
sigma() [2/2]
const Def * thorin::World::sigma (Defs ops, const Def * dbg = {})
Definition at line 313 of file world.cpp.
References arr(), thorin::ArrayRef< T >::begin(), dbg(), thorin::ArrayRef< T >::end(), infer_kind(), op(), sigma(), and thorin::ArrayRef< T >::size().
Referenced by thorin::flatten(), thorin::infer_sigma(), thorin::is_unit(), thorin::merge_sigma(), and thorin::Sigma::rebuild().
space()
const Space * thorin::World::space () const inline
Definition at line 78 of file world.h.
Referenced by thorin::Space::rebuild(), thorin::Rewriter::Rewriter(), and World().
stream() [1/3]
Stream & thorin::World::stream () inline
Definition at line 550 of file world.h.
Referenced by debug_stream(), log(), set(), and stream().
stream() [2/3]
Stream & thorin::World::stream (RecStreamer & rec, const DepNode * n) const
Definition at line 275 of file stream.cpp.
References thorin::DepNode::children(), thorin::Stream::dedent(), thorin::Stream::indent(), thorin::DepNode::nom(), thorin::RecStreamer::noms, thorin::RecStreamer::run(), thorin::RecStreamer::s, and stream().
stream() [3/3]
Stream & thorin::World::stream (Stream & s) const
Definition at line 251 of file stream.cpp.
References thorin::Stream::endl(), externals(), name(), thorin::RecStreamer::noms, thorin::DepTree::root(), thorin::RecStreamer::run(), and stream().
sym()
Sym thorin::World::sym (std::string_view s, const Def * dbg = {}) inline
Definition at line 181 of file world.h.
test()
const Def * thorin::World::test (const Def * value, const Def * probe, const Def * match, const Def * clash, const Def * dbg = {})
Definition at line 593 of file world.cpp.
References thorin::a, thorin::Pi::codom(), dbg(), thorin::Pi::dom(), err(), thorin::RuntimeCast< Base >::isa(), thorin::isa_lit(), join(), pi(), and thorin::Def::type().
Referenced by thorin::Test::rebuild().
top()
const Def * thorin::World::top (const Def * type, const Def * dbg = {}) inline
Definition at line 297 of file world.h.
top_nat()
const Def * thorin::World::top_nat () inline
Definition at line 299 of file world.h.
track_history()
bool thorin::World::track_history () const
Definition at line 670 of file world.cpp.
tuple() [1/3]
const Tuple * thorin::World::tuple () inline
the unit value of type []
Definition at line 182 of file world.h.
Referenced by arr(), dbg(), ext(), extract_(), fn_for(), global_immutable_string(), insert(), op_for(), pack(), tuple(), and tuple_str().
tuple() [2/3]
const Def * thorin::World::tuple (const Def * type, Defs ops, const Def * dbg = {})
Ascribes type to this tuple - needed for dependently typed and nominal Sigmas.
Definition at line 336 of file world.cpp.
References thorin::ArrayRef< T >::begin(), dbg(), thorin::ArrayRef< T >::end(), err(), extract(), thorin::isa_lit(), thorin::Def::isa_nom(), op(), pack(), thorin::ArrayRef< T >::size(), tuple(), and thorin::Def::type().
tuple() [3/3]
const Def * thorin::World::tuple (Defs ops, const Def * dbg = {})
Definition at line 328 of file world.cpp.
References dbg(), err(), thorin::infer_sigma(), sigma(), thorin::t, and tuple().
Referenced by thorin::RetWrap::enter(), thorin::flatten(), thorin::merge_tuple(), thorin::Tuple::rebuild(), and thorin::ClosureConv::run().
tuple_str()
const Def * thorin::World::tuple_str (std::string_view s, const Def * dbg = {})
Definition at line 374 of file world.cpp.
References dbg(), lit_nat(), and tuple().
Referenced by dbg().
type_bool()
const App * thorin::World::type_bool () inline
Definition at line 340 of file world.h.
Referenced by World().
type_int() [1/3]
const Axiom * thorin::World::type_int () inline
Definition at line 337 of file world.h.
Referenced by type_int_width(), and World().
type_int() [2/3]
const App * thorin::World::type_int (const Def * mod) inline
Definition at line 344 of file world.h.
References app(), thorin::RuntimeCast< Base >::as(), and type_int().
Referenced by type_int().
type_int() [3/3]
const App * thorin::World::type_int (nat_t mod) inline
Definition at line 342 of file world.h.
References lit_nat(), and type_int().
Referenced by type_int().
type_int_width()
const App * thorin::World::type_int_width (nat_t width) inline
Definition at line 341 of file world.h.
References lit_nat(), type_int(), and thorin::width2mod().
type_mem()
const Axiom * thorin::World::type_mem () inline
Definition at line 336 of file world.h.
type_nat()
const Nat * thorin::World::type_nat () inline
Definition at line 335 of file world.h.
Referenced by thorin::Nat::rebuild(), and World().
type_ptr() [1/3]
const Axiom * thorin::World::type_ptr () inline
Definition at line 339 of file world.h.
Referenced by global_immutable_string(), and World().
type_ptr() [2/3]
const App * thorin::World::type_ptr (const Def * pointee, const Def * addr_space, const Def * dbg = {}) inline
Definition at line 349 of file world.h.
type_ptr() [3/3]
const App * thorin::World::type_ptr (const Def * pointee, nat_t addr_space = AddrSpace::Generic, const Def * dbg = {}) inline
Definition at line 346 of file world.h.
type_real() [1/3]
const Axiom * thorin::World::type_real () inline
Definition at line 338 of file world.h.
Referenced by World().
type_real() [2/3]
const App * thorin::World::type_real (const Def * width) inline
Definition at line 345 of file world.h.
References app(), thorin::RuntimeCast< Base >::as(), and type_real().
Referenced by type_real().
type_real() [3/3]
const App * thorin::World::type_real (nat_t width) inline
Definition at line 343 of file world.h.
References lit_nat(), and type_real().
Referenced by type_real().
use_breakpoint()
void thorin::World::use_breakpoint (size_t number)
Definition at line 668 of file world.cpp.
var()
const Var * thorin::World::var (const Def * type, Def * nom, const Def * dbg = {}) inline
Definition at line 80 of file world.h.
Referenced by thorin::Var::rebuild(), and thorin::ClosureConv::run().
vel()
const Def * thorin::World::vel (const Def * type, const Def * value, const Def * dbg = {})
Definition at line 586 of file world.cpp.
References dbg(), and thorin::RuntimeCast< Base >::isa().
Referenced by thorin::Vel::rebuild().
visit()
template<bool elide_empty> template void thorin::World::visit< false > (VisitFn) const
Transitively visits all reachable Scopes in this World that do not have free variables.
We call these Scopes top-level Scopes. Select with elide_empty whether you want to visit trivial Scopes of noms without body.
Definition at line 708 of file world.cpp.
References defs(), thorin::unique_queue< Set >::empty(), externals(), thorin::f, thorin::Scope::free_noms(), name(), thorin::unique_queue< Set >::pop(), and thorin::unique_queue< Set >::push().
wdef()
template<class... Args> void thorin::World::wdef (const Def * def, const char * fmt, Args &&... args) inline
Definition at line 573 of file world.h.
References thorin::Def::debug(), thorin::Debug::loc, log(), and thorin::Warn.
Friends And Related Function Documentation
Def::reduce
DefArray Def::reduce (const Def *) friend
swap
void swap (World & w1, World & w2) friend
Definition at line 595 of file world.h.
The documentation for this class was generated from the following files:
thorin/world.h
thorin/stream.cpp
thorin/world.cpp