MimIR: mim::ast::PiExpr::Dom Class Reference
mim::ast::PiExpr::Dom Class Reference
#include <mim/ast/ast.h>
Public Member Functions
Dom (Loc loc, Ptr< Ptrn > &&ptrn)
bool is_implicit () const
const Ptrn * ptrn () const
const IdPtrn * ret () const
void add_ret (AST &ast, Ptr< Expr > &&type) const
virtual void bind (Scopes &scopes, bool quiet=false) const
virtual void emit_type (Emitter &) const
std::ostream & stream (Tab &, std::ostream &) const override
Public Member Functions inherited from mim::ast::Node
Loc loc () const
void dump () const
Protected Member Functions
const Pi * set_codom (const Def *codom) const
Protected Member Functions inherited from mim::ast::Node
Node (Loc loc)
virtual ~Node ()
Protected Attributes
Pi * decl_ = nullptr
Pi * pi_ = nullptr
const Pi * const_pi_ = nullptr
Friends
class PiExpr
Detailed Description
Definition at line 481 of file ast.h.
Constructor & Destructor Documentation
Dom()
mim::ast::PiExpr::Dom::Dom (Loc loc, Ptr< Ptrn > && ptrn) inline
Definition at line 483 of file ast.h.
Member Function Documentation
add_ret()
void mim::ast::PiExpr::Dom::add_ret (AST & ast, Ptr< Expr > && type) const inline
Definition at line 491 of file ast.h.
References mim::ast::Node::loc(), mim::ast::AST::ptr(), and mim::ast::AST::sym_return().
bind()
void mim::ast::PiExpr::Dom::bind (Scopes & scopes, bool quiet = false) const virtual
Reimplemented in mim::ast::LamDecl::Dom.
Definition at line 146 of file bind.cpp.
References mim::ast::IdPtrn::bind(), mim::ast::Ptrn::bind(), ptrn(), and ret().
Referenced by mim::ast::CDecl::bind(), mim::ast::LamDecl::Dom::bind(), mim::ast::PiExpr::bind(), mim::ast::LamDecl::bind_body(), and mim::ast::LamDecl::bind_decl().
emit_type()
void mim::ast::PiExpr::Dom::emit_type (Emitter & e) const virtual
Definition at line 207 of file emit.cpp.
References decl_, emit_type(), mim::ast::Ptrn::emit_type(), mim::ast::Ptrn::emit_value(), is_implicit(), mim::ast::Node::loc(), pi_, ptrn(), ret(), mim::Pi::set_dom(), and mim::Def::var().
Referenced by mim::ast::CDecl::emit(), mim::ast::PiExpr::emit_(), mim::ast::LamDecl::emit_decl(), and emit_type().
is_implicit()
bool mim::ast::PiExpr::Dom::is_implicit () const inline
Definition at line 487 of file ast.h.
Referenced by emit_type(), and stream().
ptrn()
const Ptrn * mim::ast::PiExpr::Dom::ptrn () const inline
Definition at line 488 of file ast.h.
Referenced by bind(), emit_type(), mim::ast::LamDecl::Dom::is_implicit(), and stream().
ret()
const IdPtrn * mim::ast::PiExpr::Dom::ret () const inline
Definition at line 489 of file ast.h.
Referenced by bind(), emit_type(), and stream().
set_codom()
const Pi * mim::ast::PiExpr::Dom::set_codom (const Def * codom) const inline protected
Definition at line 501 of file ast.h.
References const_pi_, mim::Pi::immutabilize(), pi_, and mim::Pi::set_codom().
Referenced by mim::ast::PiExpr::emit_(), and mim::ast::LamDecl::emit_decl().
stream()
std::ostream & mim::ast::PiExpr::Dom::stream (Tab & tab, std::ostream & os) const override virtual
Implements mim::ast::Node.
Definition at line 112 of file stream.cpp.
References is_implicit(), mim::print(), ptrn(), and ret().
Friends And Related Symbol Documentation
PiExpr
friend class PiExpr friend
Definition at line 514 of file ast.h.
Member Data Documentation
const_pi_
const Pi* mim::ast::PiExpr::Dom::const_pi_ = nullptr mutable protected
Definition at line 508 of file ast.h.
Referenced by set_codom().
decl_
Pi* mim::ast::PiExpr::Dom::decl_ = nullptr mutable protected
Definition at line 506 of file ast.h.
Referenced by mim::ast::PiExpr::emit_decl(), and emit_type().
pi_
Pi* mim::ast::PiExpr::Dom::pi_ = nullptr mutable protected
Definition at line 507 of file ast.h.
Referenced by emit_type(), and set_codom().
The documentation for this class was generated from the following files:
include/mim/ast/ast.h
src/mim/ast/bind.cpp
src/mim/ast/emit.cpp
src/mim/ast/stream.cpp