MimIR: mim::PassManPhase Class Reference
mim::PassManPhase Class Reference
Wraps a PassMan pipeline as a Phase.
#include <mim/phase.h>
Public Member Functions
const PassMan & man () const
Construction
PassManPhase (World &world, std::unique_ptr< PassMan > &&man)
PassManPhase (World &world, flags_t annex)
void apply (const App *) final
Invoked if your Stage has additional args.
void apply (Stage &) final
Dito, but invoked by Stage::recreate.
Public Member Functions inherited from mim::Phase
Phase (World &world, std::string name)
Phase (World &world, flags_t annex)
bool todo () const
virtual void run ()
Entry point and generates some debug output; invokes Phase::start.
Public Member Functions inherited from mim::Stage
World & world ()
Driver & driver ()
Log & log () const
std::string_view name () const
flags_t annex () const
Stage (World &world, std::string name)
Stage (World &world, flags_t annex)
virtual ~Stage ()=default
virtual std::unique_ptr< Stage > recreate ()
Creates a new instance; needed by a fixed-point PhaseMan.
Private Member Functions
void start () final
Actual entry.
Additional Inherited Members
template<class P, class... Args>
static void run (Args &&... args)
Runs a single Phase.
static auto create (const Flags2Stages &stages, const Def *def)
template<class A, class P>
static void hook (Flags2Stages &stages)
Protected Attributes inherited from mim::Phase
bool todo_ = false
Set to true to indicate that you want to rerun all Phasees in current your fixed-point PhaseMan.
Protected Attributes inherited from mim::Stage
std::string name_
Detailed Description
Wraps a PassMan pipeline as a Phase.
Definition at line 187 of file phase.h.
Constructor & Destructor Documentation
PassManPhase() [1/2]
mim::PassManPhase::PassManPhase (World & world, std::unique_ptr< PassMan > && man) inline
Definition at line 191 of file phase.h.
References man(), mim::Phase::Phase(), and mim::Stage::world().
Referenced by apply().
PassManPhase() [2/2]
mim::PassManPhase::PassManPhase (World & world, flags_t annex) inline
Definition at line 194 of file phase.h.
References mim::Stage::annex(), mim::Phase::Phase(), and mim::Stage::world().
Member Function Documentation
apply() [1/2]
void mim::PassManPhase::apply (const App *) final virtual
Invoked if your Stage has additional args.
Reimplemented from mim::Stage.
Definition at line 164 of file phase.cpp.
References mim::Stage::annex(), mim::Stage::create(), mim::Stage::driver(), and mim::Stage::world().
apply() [2/2]
void mim::PassManPhase::apply (Stage &) final virtual
Dito, but invoked by Stage::recreate.
Reimplemented from mim::Stage.
Definition at line 174 of file phase.cpp.
References PassManPhase().
man()
const PassMan & mim::PassManPhase::man () const inline
Definition at line 201 of file phase.h.
Referenced by PassManPhase().
start()
void mim::PassManPhase::start () inline final private virtual
Actual entry.
Implements mim::Phase.
Definition at line 204 of file phase.h.
The documentation for this class was generated from the following files:
include/mim/phase.h
src/mim/phase.cpp