Thorin: thorin::ast::Ptrn Class Reference
thorin::ast::Ptrn Class Reference abstract
#include <thorin/ast/ast.h>
Public Member Functions
Ptrn (Loc loc, bool rebind, Dbg dbg)
bool rebind () const
Dbg dbg () const
virtual void bind (Scopes &, bool quiet=false) const =0
Ref emit_value (Emitter &, Ref) const
virtual Ref emit_type (Emitter &) const =0
Public Member Functions inherited from thorin::ast::Decl
Ref def () const
Public Member Functions inherited from thorin::ast::Node
Loc loc () const
virtual std::ostream & stream (Tab &, std::ostream &) const =0
void dump () const
Static Public Member Functions
static Ptr< Expr > to_expr (AST &, Ptr< Ptrn > &&)
static Ptr< Ptrn > to_ptrn (Ptr< Expr > &&)
Private Member Functions
virtual void emit_value_ (Emitter &, Ref) const
Additional Inherited Members
Protected Member Functions inherited from thorin::ast::Decl
Decl (Loc loc)
Protected Member Functions inherited from thorin::ast::Node
Node (Loc loc)
virtual ~Node ()
Protected Attributes inherited from thorin::ast::Decl
Ref def_ = nullptr
Detailed Description
Definition at line 171 of file ast.h.
Constructor & Destructor Documentation
Ptrn()
thorin::ast::Ptrn::Ptrn (Loc loc, bool rebind, Dbg dbg) inline
Definition at line 173 of file ast.h.
Member Function Documentation
bind()
virtual void thorin::ast::Ptrn::bind (Scopes & , bool quiet = false) const pure virtual
Implemented in thorin::ast::IdPtrn, thorin::ast::GrpPtrn, and thorin::ast::TuplePtrn.
Referenced by thorin::ast::TuplePtrn::bind(), and thorin::ast::PiExpr::Dom::bind().
dbg()
Dbg thorin::ast::Ptrn::dbg () const inline
Definition at line 179 of file ast.h.
Referenced by thorin::ast::IdPtrn::bind(), thorin::ast::GrpPtrn::bind(), thorin::ast::TuplePtrn::bind(), thorin::ast::TuplePtrn::emit_body(), thorin::ast::TuplePtrn::emit_decl(), emit_value(), thorin::ast::IdPtrn::mk_id(), thorin::ast::IdPtrn::stream(), thorin::ast::GrpPtrn::stream(), and thorin::ast::TuplePtrn::stream().
emit_type()
virtual Ref thorin::ast::Ptrn::emit_type (Emitter &) const pure virtual
Implemented in thorin::ast::IdPtrn, thorin::ast::GrpPtrn, and thorin::ast::TuplePtrn.
Referenced by thorin::ast::TuplePtrn::emit_body(), thorin::ast::PiExpr::Dom::emit_type(), and emit_value().
emit_value()
Ref thorin::ast::Ptrn::emit_value (Emitter & e, Ref def) const
Definition at line 53 of file emit.cpp.
References dbg(), thorin::ast::Decl::def(), thorin::ast::Decl::def_, emit_type(), emit_value_(), thorin::ast::Node::loc(), and thorin::Def::set().
Referenced by thorin::ast::TuplePtrn::emit_body(), thorin::ast::PiExpr::Dom::emit_type(), and thorin::ast::TuplePtrn::emit_value_().
emit_value_()
virtual void thorin::ast::Ptrn::emit_value_ (Emitter & , Ref) const inline private virtual
Reimplemented in thorin::ast::TuplePtrn.
Definition at line 189 of file ast.h.
Referenced by emit_value().
rebind()
bool thorin::ast::Ptrn::rebind () const inline
Definition at line 178 of file ast.h.
Referenced by thorin::ast::IdPtrn::bind(), thorin::ast::GrpPtrn::bind(), and thorin::ast::TuplePtrn::bind().
to_expr()
Ptr< Expr > thorin::ast::Ptrn::to_expr (AST & ast, Ptr< Ptrn > && ptrn) static
Definition at line 161 of file ast.cpp.
References thorin::ast::TuplePtrn::is_brckt(), and thorin::ast::AST::ptr().
to_ptrn()
Ptr< Ptrn > thorin::ast::Ptrn::to_ptrn (Ptr< Expr > && expr) static
Definition at line 171 of file ast.cpp.
The documentation for this class was generated from the following files:
include/thorin/ast/ast.h
src/thorin/ast/ast.cpp
src/thorin/ast/emit.cpp