Thorin: thorin::PooledSet< T > Class Template Reference
thorin::PooledSet< T > Class Template Reference
Ordered set maintained in a consecutive buffer and unified in Pool.
#include <thorin/util/pool.h>
Classes
struct Data
Public Member Functions
Getters
constexpr operator bool () const noexcept
Is not empty?
constexpr bool empty () const noexcept
constexpr size_t size () const noexcept
constexpr const T & operator[] (size_t i) const
constexpr const T & front () const
constexpr const T * elems () const
constexpr bool contains (const T &elem) const
Comparisons
constexpr bool operator== (PooledSet< T > other) const noexcept
constexpr bool operator!= (PooledSet< T > other) const noexcept
Iterators
constexpr auto begin () const noexcept
constexpr auto end () const noexcept
constexpr auto cbegin () const noexcept
constexpr auto cend () const noexcept
constexpr auto rbegin () const noexcept
constexpr auto rend () const noexcept
constexpr auto crbegin () const noexcept
constexpr auto crend () const noexcept
Friends
class Pool< T >
template<class H >
H AbslHashValue (H h, PooledSet< T > set)
Construction & Destruction
constexpr PooledSet () noexcept=default
constexpr PooledSet (const PooledSet &) noexcept=default
constexpr PooledSet & operator= (const PooledSet &) noexcept=default
constexpr void clear () noexcept
Detailed Description
template<class T>
class thorin::PooledSet< T >
Ordered set maintained in a consecutive buffer and unified in Pool.
Definition at line 19 of file pool.h.
Constructor & Destructor Documentation
PooledSet() [1/2]
template<class T > constexpr thorin::PooledSet< T >::PooledSet () constexpr default noexcept
PooledSet() [2/2]
template<class T > constexpr thorin::PooledSet< T >::PooledSet (const PooledSet< T > &) constexpr default noexcept
Member Function Documentation
begin()
template<class T > constexpr auto thorin::PooledSet< T >::begin () const inline constexpr noexcept
Definition at line 77 of file pool.h.
References thorin::PooledSet< T >::elems().
Referenced by thorin::PooledSet< T >::contains(), thorin::Pool< T >::erase(), thorin::Pool< T >::has_intersection(), thorin::Pool< T >::merge(), and thorin::PooledSet< T >::rend().
cbegin()
template<class T > constexpr auto thorin::PooledSet< T >::cbegin () const inline constexpr noexcept
Definition at line 79 of file pool.h.
References thorin::PooledSet< T >::elems().
cend()
template<class T > constexpr auto thorin::PooledSet< T >::cend () const inline constexpr noexcept
Definition at line 80 of file pool.h.
References thorin::PooledSet< T >::end().
clear()
template<class T > constexpr void thorin::PooledSet< T >::clear () inline constexpr noexcept
Definition at line 55 of file pool.h.
contains()
template<class T > constexpr bool thorin::PooledSet< T >::contains (const T & elem) const inline constexpr
Definition at line 66 of file pool.h.
References thorin::PooledSet< T >::begin(), thorin::binary_find(), and thorin::PooledSet< T >::end().
Referenced by thorin::Pi::immutabilize(), thorin::Arr::immutabilize(), and thorin::Pack::immutabilize().
crbegin()
template<class T > constexpr auto thorin::PooledSet< T >::crbegin () const inline constexpr noexcept
Definition at line 83 of file pool.h.
References thorin::PooledSet< T >::rbegin().
crend()
template<class T > constexpr auto thorin::PooledSet< T >::crend () const inline constexpr noexcept
Definition at line 84 of file pool.h.
References thorin::PooledSet< T >::rend().
elems()
template<class T > constexpr const T * thorin::PooledSet< T >::elems () const inline constexpr
Definition at line 65 of file pool.h.
References thorin::PooledSet< T >::Data::elems.
Referenced by thorin::PooledSet< T >::begin(), thorin::PooledSet< T >::cbegin(), and thorin::PooledSet< T >::end().
empty()
template<class T > constexpr bool thorin::PooledSet< T >::empty () const inline constexpr noexcept
Definition at line 61 of file pool.h.
Referenced by thorin::Def::is_closed(), thorin::Def::is_open(), thorin::VarRewriter::rewrite_imm(), and thorin::PooledSet< T >::size().
end()
template<class T > constexpr auto thorin::PooledSet< T >::end () const inline constexpr noexcept
Definition at line 78 of file pool.h.
References thorin::PooledSet< T >::elems(), and thorin::PooledSet< T >::size().
Referenced by thorin::PooledSet< T >::cend(), thorin::PooledSet< T >::contains(), thorin::Pool< T >::erase(), thorin::Pool< T >::has_intersection(), thorin::Pool< T >::merge(), and thorin::PooledSet< T >::rbegin().
front()
template<class T > constexpr const T & thorin::PooledSet< T >::front () const inline constexpr
Definition at line 64 of file pool.h.
operator bool()
template<class T > constexpr thorin::PooledSet< T >::operator bool () const inline explicit constexpr noexcept
Is not empty?
Definition at line 60 of file pool.h.
operator!=()
template<class T > constexpr bool thorin::PooledSet< T >::operator!= (PooledSet< T > other) const inline constexpr noexcept
Definition at line 72 of file pool.h.
operator=()
template<class T > constexpr PooledSet & thorin::PooledSet< T >::operator= (const PooledSet< T > &) constexpr default noexcept
operator==()
template<class T > constexpr bool thorin::PooledSet< T >::operator== (PooledSet< T > other) const inline constexpr noexcept
Definition at line 71 of file pool.h.
operator[]()
template<class T > constexpr const T & thorin::PooledSet< T >::operator[] (size_t i) const inline constexpr
Definition at line 63 of file pool.h.
References thorin::PooledSet< T >::Data::elems.
rbegin()
template<class T > constexpr auto thorin::PooledSet< T >::rbegin () const inline constexpr noexcept
Definition at line 81 of file pool.h.
References thorin::PooledSet< T >::end().
Referenced by thorin::PooledSet< T >::crbegin().
rend()
template<class T > constexpr auto thorin::PooledSet< T >::rend () const inline constexpr noexcept
Definition at line 82 of file pool.h.
References thorin::PooledSet< T >::begin().
Referenced by thorin::PooledSet< T >::crend().
size()
template<class T > constexpr size_t thorin::PooledSet< T >::size () const inline constexpr noexcept
Definition at line 62 of file pool.h.
References thorin::PooledSet< T >::empty(), and thorin::PooledSet< T >::Data::size.
Referenced by thorin::PooledSet< T >::end(), thorin::Pool< T >::erase(), and thorin::Pool< T >::merge().
Friends And Related Symbol Documentation
AbslHashValue
template<class T > template<class H > H AbslHashValue (H h, PooledSet< T > set) friend
Definition at line 90 of file pool.h.
Pool< T >
template<class T > friend class Pool< T > friend
Definition at line 90 of file pool.h.
The documentation for this class was generated from the following file:
include/thorin/util/pool.h