Thorin: thorin::Phase Class Reference
thorin::Phase Class Reference abstract
As opposed to a Pass, a Phase does one thing at a time and does not mix with other Phases.
#include <thorin/phase/phase.h>
Public Member Functions
Phase (World &world, std::string_view name, bool dirty)
virtual ~Phase ()=default
getters
World & world ()
std::string_view name () const
bool is_dirty () const
Protected Member Functions
virtual void start ()=0
Actual entry.
Protected Attributes
World & world_
std::string name_
bool dirty_
run
virtual void run ()
Entry point and generates some debug output; invokes Phase::start.
template<class P , class... Args>
static void run (Args &&... args)
Runs a single Phase.
Detailed Description
As opposed to a Pass, a Phase does one thing at a time and does not mix with other Phases.
They are supposed to classically run one after another. Phase::dirty indicates whether we may need a Cleanup afterwards.
Definition at line 15 of file phase.h.
Constructor & Destructor Documentation
Phase()
thorin::Phase::Phase (World & world, std::string_view name, bool dirty) inline
Definition at line 17 of file phase.h.
~Phase()
virtual thorin::Phase::~Phase () virtual default
Member Function Documentation
is_dirty()
bool thorin::Phase::is_dirty () const inline
Definition at line 27 of file phase.h.
References dirty_.
name()
std::string_view thorin::Phase::name () const inline
Definition at line 26 of file phase.h.
References name_.
Referenced by thorin::ll::Emitter::emit_bb(), thorin::ll::Emitter::emit_epilogue(), thorin::ll::Emitter::prepare(), run(), and thorin::ScopePhase::start().
run() [1/2]
void thorin::Phase::run () virtual
Entry point and generates some debug output; invokes Phase::start.
Definition at line 5 of file phase.cpp.
References name(), start(), and world().
Referenced by thorin::ll::emit(), thorin::optimize(), thorin::clos::ClosConvWrapper::prepare(), and thorin::clos::LowerTypedClosWrapper::prepare().
run() [2/2]
template<class P , class... Args> static void thorin::Phase::run (Args &&... args) inline static
Runs a single Phase.
Definition at line 36 of file phase.h.
start()
virtual void thorin::Phase::start () protected pure virtual
Actual entry.
Implemented in thorin::clos::ClosConv, thorin::clos::LowerTypedClos, thorin::ll::Emitter, thorin::RWPhase, thorin::FPPhase, thorin::PassPhase< P >, thorin::PassManPhase, thorin::Pipeline, and thorin::ScopePhase.
Referenced by run(), and thorin::ll::Emitter::start().
world()
World & thorin::Phase::world () inline
Definition at line 25 of file phase.h.
References world_.
Referenced by thorin::Pipeline::add(), thorin::ll::Emitter::emit_epilogue(), run(), thorin::clos::ClosConv::start(), thorin::clos::LowerTypedClos::start(), and thorin::ScopePhase::start().
Member Data Documentation
dirty_
bool thorin::Phase::dirty_ protected
Definition at line 47 of file phase.h.
Referenced by is_dirty().
name_
std::string thorin::Phase::name_ protected
Definition at line 46 of file phase.h.
Referenced by name().
world_
World& thorin::Phase::world_ protected
Definition at line 45 of file phase.h.
Referenced by thorin::RWPhase::old_world(), thorin::RWPhase::start(), and world().
The documentation for this class was generated from the following files:
thorin/phase/phase.h
thorin/phase/phase.cpp