Thorin: thorin::dot::Emitter Class Reference
thorin::dot::Emitter Class Reference
Public Types
using Super = thorin::Emitter< std::string, std::string, BB, Emitter >
Public Member Functions
Emitter (World &w, std::ostream &ostream, const std::function< void(std::ostream &, const Def *)> &stream_def)
~Emitter ()
bool is_valid (std::string_view s)
void emit_imported (Lam *)
void emit_epilogue (Lam *)
std::string emit_bb (BB &, const Def *)
std::string prepare (const Scope &)
void finalize (const Scope &)
Public Member Functions inherited from thorin::ScopePhase
ScopePhase (World &world, std::string_view name, bool elide_empty)
void start () override
Actual entry.
virtual void visit (const Scope &)=0
Public Member Functions inherited from thorin::Phase
Phase (World &world, std::string_view name, bool dirty)
virtual ~Phase ()=default
World & world ()
std::string_view name () const
bool is_dirty () const
virtual void run ()
Entry point and generates some debug output; invokes Phase::start.
Additional Inherited Members
Static Public Member Functions inherited from thorin::Phase
template<class P , class... Args>
static void run (Args &&... args)
Runs a single Phase.
Public Attributes inherited from thorin::Emitter< std::string, std::string, BB, Emitter >
Tab tab
Protected Member Functions inherited from thorin::Emitter< std::string, std::string, BB, Emitter >
Emitter (World &world, std::string_view name, std::ostream &ostream)
std::ostream & ostream () const
std::string emit (const Def *def)
Recursively emits code.
std::string emit_unsafe (const Def *def)
As above but returning !child().is_valid(value) is permitted.
void visit (const Scope &scope) override
Protected Member Functions inherited from thorin::ScopePhase
const Scope & scope () const
virtual void start ()=0
Actual entry.
Protected Attributes inherited from thorin::Emitter< std::string, std::string, BB, Emitter >
std::ostream & ostream_
Scheduler scheduler_
DefMap< std::string > locals_
DefMap< std::string > globals_
DefMap< std::string > types_
LamMap< BB > lam2bb_
Lam * entry_
Protected Attributes inherited from thorin::Phase
World & world_
std::string name_
bool dirty_
Detailed Description
Definition at line 13 of file dot.cpp.
Member Typedef Documentation
Super
using thorin::dot::Emitter::Super = thorin::Emitter<std::string, std::string, BB, Emitter>
Definition at line 15 of file dot.cpp.
Constructor & Destructor Documentation
Emitter()
thorin::dot::Emitter::Emitter (World & w, std::ostream & ostream, const std::function< void(std::ostream &, const Def *)> & stream_def) inline
Definition at line 17 of file dot.cpp.
References thorin::Emitter< std::string, std::string, BB, Emitter >::ostream().
~Emitter()
thorin::dot::Emitter::~Emitter () inline
Definition at line 23 of file dot.cpp.
References thorin::Emitter< std::string, std::string, BB, Emitter >::ostream_.
Member Function Documentation
emit_bb()
std::string thorin::dot::Emitter::emit_bb (BB & , const Def * def)
Definition at line 80 of file dot.cpp.
References thorin::dot::emit_node_attributes(), thorin::Emitter< std::string, std::string, BB, Emitter >::emit_unsafe(), thorin::RuntimeCast< B >::isa(), thorin::Def::node_name(), thorin::Def::ops(), thorin::Emitter< std::string, std::string, BB, Emitter >::ostream_, thorin::print(), and thorin::Def::unique_name().
emit_epilogue()
void thorin::dot::Emitter::emit_epilogue (Lam * lam)
Definition at line 67 of file dot.cpp.
References thorin::Lam::body(), thorin::Emitter< std::string, std::string, BB, Emitter >::emit(), thorin::dot::emit_cluster_start(), thorin::Emitter< std::string, std::string, BB, Emitter >::entry_, thorin::Emitter< std::string, std::string, BB, Emitter >::ostream_, and thorin::print().
emit_imported()
void thorin::dot::Emitter::emit_imported (Lam * lam)
Definition at line 63 of file dot.cpp.
References thorin::Def::node_name(), thorin::Emitter< std::string, std::string, BB, Emitter >::ostream_, thorin::print(), and thorin::Def::unique_name().
finalize()
void thorin::dot::Emitter::finalize (const Scope &)
Definition at line 106 of file dot.cpp.
References thorin::Emitter< std::string, std::string, BB, Emitter >::ostream_.
is_valid()
bool thorin::dot::Emitter::is_valid (std::string_view s) inline
Definition at line 28 of file dot.cpp.
prepare()
std::string thorin::dot::Emitter::prepare (const Scope & scope)
Definition at line 98 of file dot.cpp.
References thorin::Def::as_mut(), thorin::dot::emit_cluster_start(), thorin::Scope::entry(), thorin::Emitter< std::string, std::string, BB, Emitter >::ostream_, and thorin::ScopePhase::scope().
The documentation for this class was generated from the following file:
thorin/be/dot/dot.cpp