Thorin: thorin::ErrorHandler Class Reference
thorin::ErrorHandler Class Reference
#include <thorin/error.h>
Public Member Functions
virtual ~ErrorHandler ()=default
virtual void expected_shape (const Def *def, const Def *dbg)
virtual void expected_type (const Def *def, const Def *dbg)
virtual void index_out_of_range (const Def *arity, const Def *index, const Def *dbg)
virtual void ill_typed_app (const Def *callee, const Def *arg, const Def *dbg)
template<class T = std::logic_error, class... Args>
void err (Loc loc, const char *fmt, Args &&... args)
Place holder until we have better methods.
Detailed Description
Definition at line 29 of file error.h.
Constructor & Destructor Documentation
~ErrorHandler()
virtual thorin::ErrorHandler::~ErrorHandler () virtual default
Member Function Documentation
err()
template<class T = std::logic_error, class... Args> void thorin::ErrorHandler::err (Loc loc, const char * fmt, Args &&... args) inline
Place holder until we have better methods.
Definition at line 40 of file error.h.
References thorin::err(), and thorin::fmt().
Referenced by thorin::World::app(), expected_shape(), expected_type(), thorin::World::extract(), ill_typed_app(), and index_out_of_range().
expected_shape()
void thorin::ErrorHandler::expected_shape (const Def * def, const Def * dbg) virtual
Definition at line 9 of file error.cpp.
References thorin::Def::dbg(), err(), thorin::Debug::loc, and thorin::Def::type().
Referenced by thorin::World::arr(), and thorin::World::pack().
expected_type()
void thorin::ErrorHandler::expected_type (const Def * def, const Def * dbg) virtual
Definition at line 14 of file error.cpp.
References thorin::Def::dbg(), err(), and thorin::Debug::loc.
ill_typed_app()
void thorin::ErrorHandler::ill_typed_app (const Def * callee, const Def * arg, const Def * dbg) virtual
Definition at line 24 of file error.cpp.
References thorin::RuntimeCast< Base >::as(), thorin::Def::dbg(), thorin::Pi::dom(), err(), thorin::Debug::loc, and thorin::Def::type().
Referenced by thorin::World::app().
index_out_of_range()
void thorin::ErrorHandler::index_out_of_range (const Def * arity, const Def * index, const Def * dbg) virtual
Definition at line 19 of file error.cpp.
References thorin::Def::dbg(), err(), and thorin::Debug::loc.
Referenced by thorin::World::extract(), thorin::World::insert(), and thorin::World::lit_int().
The documentation for this class was generated from the following files:
thorin/error.h
thorin/error.cpp