Thorin: thorin::ast::AxiomDecl Class Reference
thorin::ast::AxiomDecl Class Reference
.ax ptrn: type = value;
#include <thorin/ast/ast.h>
Classes
class Alias
Public Member Functions
AxiomDecl (Loc loc, Dbg dbg, std::deque< Ptrs< Alias > > &&subs, Ptr< Expr > &&type, Dbg normalizer, Tok curry, Tok trip)
Dbg dbg () const
const auto & subs () const
size_t num_subs () const
const auto & sub (size_t i) const
const Expr * type () const
Dbg normalizer () const
Tok curry () const
Tok trip () const
void bind (Scopes &) const override
void emit (Emitter &) const override
std::ostream & stream (Tab &, std::ostream &) const override
Public Member Functions inherited from thorin::ast::Decl
Ref def () const
Public Member Functions inherited from thorin::ast::Node
Loc loc () const
void dump () const
Additional Inherited Members
Protected Member Functions inherited from thorin::ast::ValDecl
ValDecl (Loc loc)
Protected Member Functions inherited from thorin::ast::Decl
Decl (Loc loc)
Protected Member Functions inherited from thorin::ast::Node
Node (Loc loc)
virtual ~Node ()
Protected Attributes inherited from thorin::ast::Decl
Ref def_ = nullptr
Detailed Description
.ax ptrn: type = value;
Definition at line 723 of file ast.h.
Constructor & Destructor Documentation
AxiomDecl()
thorin::ast::AxiomDecl::AxiomDecl (Loc loc, Dbg dbg, std::deque< Ptrs< Alias > > && subs, Ptr< Expr > && type, Dbg normalizer, Tok curry, Tok trip) inline
Definition at line 743 of file ast.h.
Member Function Documentation
bind()
void thorin::ast::AxiomDecl::bind (Scopes & s) const override virtual
Implements thorin::ast::ValDecl.
Definition at line 225 of file bind.cpp.
References thorin::ast::Node::loc().
curry()
Tok thorin::ast::AxiomDecl::curry () const inline
Definition at line 758 of file ast.h.
dbg()
Dbg thorin::ast::AxiomDecl::dbg () const inline
Definition at line 752 of file ast.h.
Referenced by thorin::ast::AxiomDecl::Alias::bind().
emit()
void thorin::ast::AxiomDecl::emit (Emitter & e) const override virtual
Implements thorin::ast::ValDecl.
Definition at line 332 of file emit.cpp.
References thorin::error(), and thorin::Axiom::infer_curry_and_trip().
normalizer()
Dbg thorin::ast::AxiomDecl::normalizer () const inline
Definition at line 757 of file ast.h.
num_subs()
size_t thorin::ast::AxiomDecl::num_subs () const inline
Definition at line 754 of file ast.h.
stream()
std::ostream & thorin::ast::AxiomDecl::stream (Tab & tab, std::ostream & os) const override virtual
Implements thorin::ast::Node.
Definition at line 161 of file stream.cpp.
References thorin::print().
sub()
const auto & thorin::ast::AxiomDecl::sub (size_t i) const inline
Definition at line 755 of file ast.h.
subs()
const auto & thorin::ast::AxiomDecl::subs () const inline
Definition at line 753 of file ast.h.
trip()
Tok thorin::ast::AxiomDecl::trip () const inline
Definition at line 759 of file ast.h.
type()
const Expr * thorin::ast::AxiomDecl::type () const inline
Definition at line 756 of file ast.h.
The documentation for this class was generated from the following files:
include/thorin/ast/ast.h
src/thorin/ast/bind.cpp
src/thorin/ast/emit.cpp
src/thorin/ast/stream.cpp