Thorin: thorin::Pi Class Reference
thorin::Pi Class Reference
A dependent function type.
#include <thorin/lam.h>
Public Member Functions
Get/Set implicit
bool is_implicit () const
Pi * make_implicit ()
Pi * make_explicit ()
dom
See also
proj
Ref dom () const
nat_t num_doms () const
Ref dom (nat_t a, nat_t i) const
Ref dom (nat_t i) const
template<nat_t A = -1_s, class F >
auto doms (F f) const
template<nat_t A = -1_s>
auto doms () const
template<class F >
auto doms (nat_t a, F f) const
auto doms (nat_t a) const
codom
See also
proj
Ref codom () const
nat_t num_codoms () const
Ref codom (nat_t a, nat_t i) const
Ref codom (nat_t i) const
template<nat_t A = -1_s, class F >
auto codoms (F f) const
template<nat_t A = -1_s>
auto codoms () const
template<class F >
auto codoms (nat_t a, F f) const
auto codoms (nat_t a) const
Setters
See also
Setting Ops
Pi * set (Ref dom, Ref codom)
Pi * set_dom (Ref dom)
Pi * set_dom (Defs doms)
Pi * set_codom (Ref codom)
Pi * unset ()
Rebuild
const Pi * immutabilize () override
Tries to make an immutable from a mutable.
Pi * stub (World &, Ref) override
Ref rebuild (World &, Ref, Defs) const override
Def::rebuilds this Def while using new_op as substitute for its i'th Def::op.
Public Member Functions inherited from thorin::Def
World & world () const
flags_t flags () const
u32 gid () const
hash_t hash () const
node_t node () const
std::string_view node_name () const
const Def * type () const
Yields the raw type of this Def, i.e. maybe nullptr.
const Def * unfold_type () const
Yields the type of this Def and unfolds it if necessary.
bool is_term () const
Yields true if this:T and T:(.Type 0).
const Def * arity () const
std::optional< nat_t > isa_lit_arity () const
nat_t as_lit_arity () const
template<size_t N = -1_s>
auto ops () const
const Def * op (size_t i) const
size_t num_ops () const
Def * set (size_t i, const Def *def)
Successively set from left to right.
Def * reset (size_t i, const Def *def)
Successively reset from left to right.
Def * set (Defs ops)
Def::set ops all at once.
Def * reset (Defs ops)
Def::reset ops all at once.
Def * unset ()
Unsets all Def::ops; works even, if not set at all or partially.
Def * set_type (const Def *)
void unset_type ()
void update ()
Resolves Infers of this Def's type.
bool is_set () const
Yields true if empty or the last op is set.
Defs extended_ops () const
const Def * extended_op (size_t i) const
size_t num_extended_ops () const
Defs partial_ops () const
const Def * partial_op (size_t i) const
size_t num_partial_ops () const
const Uses & uses () const
size_t num_uses () const
unsigned dep () const
bool has_dep (Dep d) const
bool has_dep (unsigned u) const
bool dep_const () const
nat_t num_projs () const
Yields Def::as_lit_arity(), if it is in fact a Lit, or 1 otherwise.
const Def * proj (nat_t a, nat_t i) const
Similar to World::extract while assuming an arity of a, but also works on Sigmas and Arrays.
const Def * proj (nat_t i) const
Same as above but takes Def::num_projs as arity.
template<nat_t A = -1_s, class F >
auto projs (F f) const
Splits this Def via Def::projections into an Array (if A == -1_s) or std::array (otherwise).
template<class F >
auto projs (nat_t a, F f) const
template<nat_t A = -1_s>
auto projs () const
auto projs (nat_t a) const
Ref var ()
nat_t num_vars ()
Ref var (nat_t a, nat_t i)
Ref var (nat_t i)
template<nat_t A = -1_s, class F >
auto vars (F f)
template<nat_t A = -1_s>
auto vars ()
template<class F >
auto vars (nat_t a, F f)
auto vars (nat_t a)
bool is_external () const
void make_external ()
void make_internal ()
void transfer_external (Def *to)
template<class T = Def>
const T * isa_imm () const
template<class T = Def>
const T * as_imm () const
template<class T = Def, class R >
const T * isa_imm (R(T::*f)() const) const
template<class T = Def, bool invert = false>
T * isa_mut () const
If this is *mut*able, it will cast constness away and perform a dynamic_cast to T.
template<class T = Def, bool invert = false>
T * as_mut () const
Asserts that this is a mutable, casts constness away and performs a static_cast to T.
Dbg dbg () const
Loc loc () const
Sym sym () const
std::string unique_name () const
name + "_" + Def::gid
template<bool Ow = false>
const Def * set (Loc l) const
template<bool Ow = false>
Def * set (Loc l)
template<bool Ow = false>
const Def * set (Sym s) const
template<bool Ow = false>
Def * set (Sym s)
template<bool Ow = false>
const Def * set (std::string s) const
template<bool Ow = false>
Def * set (std::string s)
template<bool Ow = false>
const Def * set (Loc l, Sym s) const
template<bool Ow = false>
Def * set (Loc l, Sym s)
template<bool Ow = false>
const Def * set (Loc l, std::string s) const
template<bool Ow = false>
Def * set (Loc l, std::string s)
template<bool Ow = false>
const Def * set (Dbg d) const
template<bool Ow = false>
Def * set (Dbg d)
const Def * debug_prefix (std::string) const
const Def * debug_suffix (std::string) const
const Def * refine (size_t i, const Def *new_op) const
DefArray reduce (const Def *arg) const
Rewrites Def::ops by substituting this mutable's Var with arg.
DefArray reduce (const Def *arg)
const Def * reduce_rec () const
Transitively Def::reduce Lams, if this is an App.
void dump () const
void dump (int max) const
void write (int max) const
void write (int max, const char *file) const
std::ostream & stream (std::ostream &, int max) const
Public Member Functions inherited from thorin::RuntimeCast< Def >
T * as ()
static_cast with debug check.
const T * as () const
const version.
T * isa ()
dynamic_cast.
Def * isa ()
Yields B* if it is either T or U and `nullptr* otherwise.
const T * isa () const
const version.
const Def * isa () const
const version.
Static Public Member Functions
Continuations
Checks certain properties of this Pi regarding continuations.
static const Pi * isa_cn (Ref d)
Is this a continuation - i.e. is the Pi::codom thorin::Bottom?
static const Pi * isa_returning (Ref d)
Is this a continuation (Pi::isa_cn) which has a Pi::ret_pi?
static const Pi * isa_basicblock (Ref d)
Is this a continuation (Pi::isa_cn) that is not Pi::isa_returning?
Static Public Attributes
static constexpr auto Node = Node:: Pi
Protected Member Functions
Pi (const Def *type, const Def *dom, const Def *codom, bool implicit)
Constructor for an immutable Pi.
Pi (const Def *type, bool implicit)
Constructor for a *mut*able Pi.
Protected Member Functions inherited from thorin::Def
Def (World *, node_t, const Def *type, Defs ops, flags_t flags)
Constructor for an immutable Def.
Def (node_t n, const Def *type, Defs ops, flags_t flags)
Def (node_t, const Def *type, size_t num_ops, flags_t flags)
Constructor for a mutable Def.
virtual ~Def ()=default
Sym sym (const char *) const
Sym sym (std::string_view) const
Sym sym (std::string) const
Return Continuation
const Pi * ret_pi () const
Yields the last Pi::dom, if it Pi::isa_basicblock.
Ref ret_dom () const
Pi::domain of Pi::ret_pi.
static const Pi * ret_pi (Ref d)
Yields the Pi::ret_pi() of d, if it is in fact a Pi.
Type Checking
void check () override
static const Def * infer (const Def *dom, const Def *codom)
Additional Inherited Members
Protected Attributes inherited from thorin::Def
Dbg dbg_
union {
NormalizeFn normalizer_
Axioms use this member to store their normalizer.
const Axiom * axiom_
World * world_
Curried Apps of Axioms use this member to propagate the Axiom.
};
flags_t flags_
u8 curry_
u8 trip_
Detailed Description
A dependent function type.
See also
Lam
Definition at line 11 of file lam.h.
Constructor & Destructor Documentation
Pi() [1/2]
thorin::Pi::Pi (const Def * type, const Def * dom, const Def * codom, bool implicit) inline protected
Constructor for an immutable Pi.
Definition at line 14 of file lam.h.
References codom(), and dom().
Pi() [2/2]
thorin::Pi::Pi (const Def * type, bool implicit) inline protected
Constructor for a *mut*able Pi.
Definition at line 17 of file lam.h.
Member Function Documentation
check()
void thorin::Pi::check () override virtual
Reimplemented from thorin::Def.
Definition at line 197 of file check.cpp.
References codom(), dom(), thorin::error(), infer(), thorin::Def::type(), and thorin::Def::world().
codom() [1/3]
Ref thorin::Pi::codom () const inline
Definition at line 38 of file lam.h.
References thorin::Def::op().
Referenced by thorin::autodiff::autodiff_type_fun_pi(), check(), thorin::Lam::codom(), immutabilize(), infer(), isa_cn(), Pi(), set(), set_codom(), and thorin::World::test().
codom() [2/3]
Ref thorin::Pi::codom (nat_t a, nat_t i) const inline
Definition at line 39 of file lam.h.
codom() [3/3]
Ref thorin::Pi::codom (nat_t i) const inline
Definition at line 39 of file lam.h.
codoms() [1/4]
template<nat_t A = -1_s> auto thorin::Pi::codoms () const inline
Definition at line 39 of file lam.h.
codoms() [2/4]
template<nat_t A = -1_s, class F > auto thorin::Pi::codoms (F f) const inline
Definition at line 39 of file lam.h.
codoms() [3/4]
auto thorin::Pi::codoms (nat_t a) const inline
Definition at line 39 of file lam.h.
codoms() [4/4]
template<class F > auto thorin::Pi::codoms (nat_t a, F f) const inline
Definition at line 39 of file lam.h.
dom() [1/3]
Ref thorin::Pi::dom () const inline
Definition at line 31 of file lam.h.
References thorin::Def::op().
Referenced by thorin::World::app(), thorin::autodiff::AutoDiffEval::augment_lam(), thorin::autodiff::autodiff_type_fun_pi(), check(), thorin::compose_cn(), thorin::Lam::dom(), thorin::World::iapp(), immutabilize(), infer(), thorin::direct::op_cps2ds_dep(), Pi(), ret_dom(), thorin::Lam::ret_dom(), ret_pi(), set(), set_dom(), and thorin::World::test().
dom() [2/3]
Ref thorin::Pi::dom (nat_t a, nat_t i) const inline
Definition at line 32 of file lam.h.
dom() [3/3]
Ref thorin::Pi::dom (nat_t i) const inline
Definition at line 32 of file lam.h.
doms() [1/4]
template<nat_t A = -1_s> auto thorin::Pi::doms () const inline
Definition at line 32 of file lam.h.
Referenced by set_dom().
doms() [2/4]
template<nat_t A = -1_s, class F > auto thorin::Pi::doms (F f) const inline
Definition at line 32 of file lam.h.
Referenced by thorin::autodiff::autodiff_type_fun_pi(), thorin::clos::clos_type(), and thorin::affine::LowerFor::rewrite().
doms() [3/4]
auto thorin::Pi::doms (nat_t a) const inline
Definition at line 32 of file lam.h.
doms() [4/4]
template<class F > auto thorin::Pi::doms (nat_t a, F f) const inline
Definition at line 32 of file lam.h.
immutabilize()
const Pi * thorin::Pi::immutabilize () override virtual
Tries to make an immutable from a mutable.
This usually works if the mutable isn't recursive and its var isn't used.
Reimplemented from thorin::Def.
Definition at line 156 of file def.cpp.
References codom(), dom(), thorin::Scope::is_free(), thorin::World::pi(), and thorin::Def::world().
infer()
const Def * thorin::Pi::infer (const Def * dom, const Def * codom) static
Definition at line 165 of file check.cpp.
References codom(), dom(), thorin::Kind, thorin::World::umax(), thorin::Def::unfold_type(), and thorin::Def::world().
Referenced by check(), and thorin::World::pi().
is_implicit()
bool thorin::Pi::is_implicit () const inline
Definition at line 23 of file lam.h.
References thorin::Def::flags().
Referenced by thorin::World::iapp().
isa_basicblock()
static const Pi * thorin::Pi::isa_basicblock (Ref d) inline static
Is this a continuation (Pi::isa_cn) that is not Pi::isa_returning?
Definition at line 52 of file lam.h.
References thorin::RuntimeCast< B >::as(), isa_cn(), and ret_pi().
Referenced by thorin::autodiff::AutoDiffEval::augment_app(), thorin::ll::Emitter::emit_epilogue(), thorin::clos::ClosLit::is_basicblock(), thorin::Lam::isa_basicblock(), and ret_pi().
isa_cn()
static const Pi * thorin::Pi::isa_cn (Ref d) inline static
Is this a continuation - i.e. is the Pi::codom thorin::Bottom?
Definition at line 48 of file lam.h.
References thorin::RuntimeCast< B >::as(), thorin::Node::Bot, codom(), thorin::RuntimeCast< B >::isa(), and thorin::Def::node().
Referenced by thorin::autodiff::AutoDiffEval::augment_app(), thorin::autodiff::autodiff_type_fun_pi(), thorin::clos::ClosConvPrep::enter(), isa_basicblock(), thorin::clos::isa_clos_type(), thorin::Lam::isa_cn(), isa_returning(), thorin::clos::BranchClosElim::rewrite(), and thorin::clos::ClosConvPrep::rewrite_callee().
isa_returning()
static const Pi * thorin::Pi::isa_returning (Ref d) inline static
Is this a continuation (Pi::isa_cn) which has a Pi::ret_pi?
Definition at line 50 of file lam.h.
References thorin::RuntimeCast< B >::as(), isa_cn(), and ret_pi().
Referenced by thorin::compose_cn(), thorin::ll::Emitter::emit_epilogue(), thorin::clos::ClosConvPrep::enter(), thorin::clos::ClosLit::is_returning(), and thorin::Lam::isa_returning().
make_explicit()
Pi * thorin::Pi::make_explicit () inline
Definition at line 25 of file lam.h.
References thorin::Def::flags_.
make_implicit()
Pi * thorin::Pi::make_implicit () inline
Definition at line 24 of file lam.h.
References thorin::Def::flags_.
num_codoms()
nat_t thorin::Pi::num_codoms () const inline
Definition at line 39 of file lam.h.
num_doms()
nat_t thorin::Pi::num_doms () const inline
Definition at line 32 of file lam.h.
Referenced by ret_pi().
rebuild()
Ref thorin::Pi::rebuild (World & w, Ref type, Defs ops) const override virtual
Def::rebuilds this Def while using new_op as substitute for its i'th Def::op.
Implements thorin::Def.
Definition at line 97 of file def.cpp.
References thorin::World::pi(), and set().
ret_dom()
Ref thorin::Pi::ret_dom () const inline
Pi::domain of Pi::ret_pi.
Definition at line 65 of file lam.h.
References dom(), and ret_pi().
Referenced by thorin::compose_cn().
ret_pi() [1/2]
const Pi * thorin::Pi::ret_pi () const
Yields the last Pi::dom, if it Pi::isa_basicblock.
Definition at line 13 of file lam.cpp.
References dom(), isa_basicblock(), and num_doms().
Referenced by isa_basicblock(), isa_returning(), and ret_dom().
ret_pi() [2/2]
static const Pi * thorin::Pi::ret_pi (Ref d) inline static
Yields the Pi::ret_pi() of d, if it is in fact a Pi.
Definition at line 61 of file lam.h.
References thorin::RuntimeCast< B >::as(), thorin::RuntimeCast< B >::isa(), and ret_pi().
Referenced by thorin::ll::Emitter::emit_imported(), thorin::Lam::ret_pi(), ret_pi(), and thorin::Lam::ret_var().
set()
Pi * thorin::Pi::set (Ref dom, Ref codom) inline
Definition at line 71 of file lam.h.
References codom(), dom(), set_codom(), and set_dom().
Referenced by rebuild(), thorin::affine::LowerFor::rewrite(), and stub().
set_codom()
Pi * thorin::Pi::set_codom (Ref codom) inline
Definition at line 74 of file lam.h.
References thorin::RuntimeCast< B >::as(), codom(), and thorin::Def::set().
Referenced by set().
set_dom() [1/2]
Pi * thorin::Pi::set_dom (Defs doms)
Definition at line 22 of file lam.cpp.
References thorin::RuntimeCast< B >::as(), doms(), thorin::Def::set(), and thorin::Def::world().
set_dom() [2/2]
Pi * thorin::Pi::set_dom (Ref dom) inline
Definition at line 72 of file lam.h.
References thorin::RuntimeCast< B >::as(), dom(), and thorin::Def::set().
Referenced by set().
stub()
Pi * thorin::Pi::stub (World & w, Ref t) override virtual
Reimplemented from thorin::Def.
Definition at line 128 of file def.cpp.
References thorin::World::mut_pi(), and set().
unset()
Pi * thorin::Pi::unset () inline
Definition at line 75 of file lam.h.
References thorin::RuntimeCast< B >::as(), and thorin::Def::unset().
Member Data Documentation
Node
constexpr auto thorin::Pi::Node = Node:: Pi static constexpr
Definition at line 87 of file lam.h.
The documentation for this class was generated from the following files:
thorin/lam.h
thorin/check.cpp
thorin/def.cpp
thorin/lam.cpp