MimIR: mim::plug::clos::LowerTypedClos Class Reference
mim::plug::clos::LowerTypedClos Class Reference
This pass lowers typed closures to untyped closures.
#include <mim/plug/clos/phase/lower_typed_clos.h>
Public Member Functions
LowerTypedClos (World &world, flags_t annex)
void start () override
Actual entry.
Public Member Functions inherited from mim::Phase
Phase (World &world, std::string name)
Phase (World &world, flags_t annex)
bool todo () const
virtual void run ()
Entry point and generates some debug output; invokes Phase::start.
Public Member Functions inherited from mim::Stage
World & world ()
Driver & driver ()
Log & log () const
std::string_view name () const
flags_t annex () const
Stage (World &world, std::string name)
Stage (World &world, flags_t annex)
virtual ~Stage ()=default
virtual std::unique_ptr< Stage > recreate ()
Creates a new instance; needed by a fixed-point PhaseMan.
virtual void apply (const App *)
Invoked if your Stage has additional args.
virtual void apply (Stage &)
Dito, but invoked by Stage::recreate.
Additional Inherited Members
template<class P, class... Args>
static void run (Args &&... args)
Runs a single Phase.
static auto create (const Flags2Stages &stages, const Def *def)
template<class A, class P>
static void hook (Flags2Stages &stages)
Protected Attributes inherited from mim::Phase
bool todo_ = false
Set to true to indicate that you want to rerun all Phasees in current your fixed-point PhaseMan.
Protected Attributes inherited from mim::Stage
std::string name_
Detailed Description
This pass lowers typed closures to untyped closures.
For details on typed closures, see ClosConv. In general, untyped closure have the form (pointer-to-environment, code) with the following exceptions:
Lams in callee-position should be λ-lifted and thus don't receive an environment.
External and imported (not set) Lams also don't receive an environment. They are appropriately η-wrapped by ClosConv.
If the environment is of integer type, it's directly stored in the environment-pointer ("unboxed").
Note
In theory this should work for other primitive types as well, but the LL backend does not handle the required conversion correctly.
Further, first class continuations are rewritten to returning functions. They receive ⊥ as a dummy continuation. Therefore Clos2SJLJ should have taken place prior to this pass.
This pass will heap-allocate ClosKind::esc closures and stack-allocate everything else. These annotations are introduced by LowerTypedClosPrep.
Definition at line 28 of file lower_typed_clos.h.
Constructor & Destructor Documentation
LowerTypedClos()
mim::plug::clos::LowerTypedClos::LowerTypedClos (World & world, flags_t annex) inline
Definition at line 30 of file lower_typed_clos.h.
References mim::Stage::annex(), mim::Phase::Phase(), and mim::Stage::world().
Member Function Documentation
start()
void mim::plug::clos::LowerTypedClos::start () override virtual
Actual entry.
Implements mim::Phase.
Definition at line 17 of file lower_typed_clos.cpp.
References mim::Stage::annex(), mim::World::bot(), DLOG, and mim::Stage::world().
The documentation for this class was generated from the following files:
include/mim/plug/clos/phase/lower_typed_clos.h
src/mim/plug/clos/phase/lower_typed_clos.cpp