Thorin: thorin::Type Class Reference
thorin::Type Class Reference
#include <thorin/def.h>
Public Member Functions
ops
const Def * level () const
Rebuild
Ref rebuild (World &, Ref, Defs) const override
Def::rebuilds this Def while using new_op as substitute for its i'th Def::op.
Public Member Functions inherited from thorin::Def
World & world () const
flags_t flags () const
u32 gid () const
hash_t hash () const
node_t node () const
std::string_view node_name () const
const Def * type () const
Yields the raw type of this Def, i.e. maybe nullptr.
const Def * unfold_type () const
Yields the type of this Def and unfolds it if necessary.
bool is_term () const
Yields true if this:T and T:(.Type 0).
const Def * arity () const
std::optional< nat_t > isa_lit_arity () const
nat_t as_lit_arity () const
template<size_t N = -1_s>
auto ops () const
const Def * op (size_t i) const
size_t num_ops () const
Def * set (size_t i, const Def *def)
Successively set from left to right.
Def * reset (size_t i, const Def *def)
Successively reset from left to right.
Def * set (Defs ops)
Def::set ops all at once.
Def * reset (Defs ops)
Def::reset ops all at once.
Def * unset ()
Unsets all Def::ops; works even, if not set at all or partially.
Def * set_type (const Def *)
void unset_type ()
void update ()
Resolves Infers of this Def's type.
bool is_set () const
Yields true if empty or the last op is set.
Defs extended_ops () const
const Def * extended_op (size_t i) const
size_t num_extended_ops () const
Defs partial_ops () const
const Def * partial_op (size_t i) const
size_t num_partial_ops () const
const Uses & uses () const
size_t num_uses () const
unsigned dep () const
bool has_dep (Dep d) const
bool has_dep (unsigned u) const
bool dep_const () const
nat_t num_projs () const
Yields Def::as_lit_arity(), if it is in fact a Lit, or 1 otherwise.
const Def * proj (nat_t a, nat_t i) const
Similar to World::extract while assuming an arity of a, but also works on Sigmas and Arrays.
const Def * proj (nat_t i) const
Same as above but takes Def::num_projs as arity.
template<nat_t A = -1_s, class F >
auto projs (F f) const
Splits this Def via Def::projections into an Array (if A == -1_s) or std::array (otherwise).
template<class F >
auto projs (nat_t a, F f) const
template<nat_t A = -1_s>
auto projs () const
auto projs (nat_t a) const
const Var * var ()
nat_t num_vars ()
Ref var (nat_t a, nat_t i)
Ref var (nat_t i)
template<nat_t A = -1_s, class F >
auto vars (F f)
template<nat_t A = -1_s>
auto vars ()
template<class F >
auto vars (nat_t a, F f)
auto vars (nat_t a)
bool is_external () const
bool is_internal () const
Not Def::is_external.
void make_external ()
void make_internal ()
template<class T = Def>
const T * isa_imm () const
template<class T = Def>
const T * as_imm () const
template<class T = Def, class R >
const T * isa_imm (R(T::*f)() const) const
template<class T = Def, bool invert = false>
T * isa_mut () const
If this is *mut*able, it will cast constness away and perform a dynamic_cast to T.
template<class T = Def, bool invert = false>
T * as_mut () const
Asserts that this is a mutable, casts constness away and performs a static_cast to T.
Dbg dbg () const
Loc loc () const
Sym sym () const
std::string unique_name () const
name + "_" + Def::gid
template<bool Ow = false>
const Def * set (Loc l) const
template<bool Ow = false>
Def * set (Loc l)
template<bool Ow = false>
const Def * set (Sym s) const
template<bool Ow = false>
Def * set (Sym s)
template<bool Ow = false>
const Def * set (std::string s) const
template<bool Ow = false>
Def * set (std::string s)
template<bool Ow = false>
const Def * set (Loc l, Sym s) const
template<bool Ow = false>
Def * set (Loc l, Sym s)
template<bool Ow = false>
const Def * set (Loc l, std::string s) const
template<bool Ow = false>
Def * set (Loc l, std::string s)
template<bool Ow = false>
const Def * set (Dbg d) const
template<bool Ow = false>
Def * set (Dbg d)
const Def * debug_prefix (std::string) const
const Def * debug_suffix (std::string) const
virtual Def * stub (World &, Ref)
virtual const Def * immutabilize ()
Tries to make an immutable from a mutable.
const Def * refine (size_t i, const Def *new_op) const
DefArray reduce (const Def *arg) const
Rewrites Def::ops by substituting this mutable's Var with arg.
DefArray reduce (const Def *arg)
const Def * reduce_rec () const
Transitively Def::reduce Lams, if this is an App.
virtual void check ()
void dump () const
void dump (int max) const
void write (int max) const
void write (int max, const char *file) const
std::ostream & stream (std::ostream &, int max) const
Public Member Functions inherited from thorin::RuntimeCast< Def >
T * as ()
static_cast with debug check.
const T * as () const
const version.
T * isa ()
dynamic_cast.
Def * isa ()
Yields B* if it is either T or U and `nullptr* otherwise.
const T * isa () const
const version.
const Def * isa () const
const version.
Static Public Attributes
static constexpr auto Node = Node:: Type
Additional Inherited Members
Protected Member Functions inherited from thorin::Def
Def (World *, node_t, const Def *type, Defs ops, flags_t flags)
Constructor for an immutable Def.
Def (node_t n, const Def *type, Defs ops, flags_t flags)
Def (node_t, const Def *type, size_t num_ops, flags_t flags)
Constructor for a mutable Def.
virtual ~Def ()=default
Sym sym (const char *) const
Sym sym (std::string_view) const
Sym sym (std::string) const
Protected Attributes inherited from thorin::Def
Dbg dbg_
union {
NormalizeFn normalizer_
Axioms use this member to store their normalizer.
const Axiom * axiom_
World * world_
Curried Apps of Axioms use this member to propagate the Axiom.
};
flags_t flags_
u8 curry_
u8 trip_
Detailed Description
Definition at line 627 of file def.h.
Member Function Documentation
level()
const Def * thorin::Type::level () const inline
Definition at line 635 of file def.h.
References thorin::Def::op().
Referenced by thorin::World::umax().
rebuild()
Ref thorin::Type::rebuild (World & w, Ref type, Defs ops) const override virtual
Def::rebuilds this Def while using new_op as substitute for its i'th Def::op.
Implements thorin::Def.
Definition at line 102 of file def.cpp.
References thorin::Def::set(), and thorin::World::type().
Member Data Documentation
Node
constexpr auto thorin::Type::Node = Node:: Type static constexpr
Definition at line 638 of file def.h.
The documentation for this class was generated from the following files:
thorin/def.h
thorin/def.cpp