Thorin: thorin::Debug Class Reference
thorin::Debug Class Reference
#include <thorin/debug.h>
Public Member Functions
Debug (std::string_view name, Loc loc={}, const Def *meta=nullptr)
Debug (std::string name, Loc loc={}, const Def *meta=nullptr)
Debug (const char *name, Loc loc={}, const Def *meta=nullptr)
Debug (Sym sym, const Def *meta=nullptr)
Debug (Sym sym, Loc loc, const Def *meta=nullptr)
Debug (Loc loc)
Debug (const Def *)
const Def * def (World &) const
Public Attributes
std::string name
Loc loc
const Def * meta = nullptr
Detailed Description
Definition at line 76 of file debug.h.
Constructor & Destructor Documentation
Debug() [1/7]
thorin::Debug::Debug (std::string_view name, Loc loc = {}, const Def * meta = nullptr) inline
Definition at line 78 of file debug.h.
Debug() [2/7]
thorin::Debug::Debug (std::string name, Loc loc = {}, const Def * meta = nullptr) inline
Definition at line 82 of file debug.h.
Debug() [3/7]
thorin::Debug::Debug (const char * name, Loc loc = {}, const Def * meta = nullptr) inline
Definition at line 86 of file debug.h.
Debug() [4/7]
thorin::Debug::Debug (Sym sym, const Def * meta = nullptr) inline
Definition at line 88 of file debug.h.
Debug() [5/7]
thorin::Debug::Debug (Sym sym, Loc loc, const Def * meta = nullptr) inline
Definition at line 90 of file debug.h.
Debug() [6/7]
thorin::Debug::Debug (Loc loc) inline
Definition at line 92 of file debug.h.
Debug() [7/7]
thorin::Debug::Debug (const Def * def)
Definition at line 19 of file debug.cpp.
Member Function Documentation
def()
const Def * thorin::Debug::def (World & w) const
Definition at line 37 of file debug.cpp.
References thorin::World::bot(), thorin::Loc::def(), loc, meta, name, thorin::World::tuple(), thorin::World::tuple_str(), and thorin::World::type_bot().
Referenced by thorin::World::dbg().
Member Data Documentation
loc
Loc thorin::Debug::loc
Definition at line 99 of file debug.h.
Referenced by def(), thorin::ErrorHandler::expected_shape(), thorin::ErrorHandler::expected_type(), thorin::ErrorHandler::ill_typed_app(), thorin::ErrorHandler::index_out_of_range(), and thorin::Def::loc().
meta
const Def* thorin::Debug::meta = nullptr
Definition at line 100 of file debug.h.
Referenced by def(), and thorin::Def::meta().
name
std::string thorin::Debug::name
Definition at line 98 of file debug.h.
Referenced by def(), thorin::Scope::name(), and thorin::Def::name().
The documentation for this class was generated from the following files:
thorin/debug.h
thorin/debug.cpp