Thorin: thorin::plug::clos::ClosLit Class Reference
thorin::plug::clos::ClosLit Class Reference
Wrapper around a Def that can be used to match closures (see isa_clos_lit).
#include <thorin/plug/clos/clos.h>
Public Member Functions
operator bool () const
operator const Tuple * ()
const Tuple * operator-> ()
Getters
const Sigma * type ()
Ref env ()
Ref env_type ()
Ref fnc ()
const Pi * fnc_type ()
Lam * fnc_as_lam ()
Ref env_var ()
Ref ret_var ()
Properties
bool is_returning ()
bool is_basicblock ()
attr get ()
Clos annotation. These should appear in front of the code-part.
Detailed Description
Wrapper around a Def that can be used to match closures (see isa_clos_lit).
Definition at line 13 of file clos.h.
Member Function Documentation
env()
Ref thorin::plug::clos::ClosLit::env ()
Definition at line 46 of file clos.cpp.
References thorin::plug::clos::clos_unpack().
Referenced by env_type().
env_type()
Ref thorin::plug::clos::ClosLit::env_type () inline
Definition at line 23 of file clos.h.
References env(), and thorin::Def::type().
env_var()
Ref thorin::plug::clos::ClosLit::env_var ()
Definition at line 62 of file clos.cpp.
References thorin::plug::clos::Clos_Env_Param, fnc_as_lam(), and thorin::Def::var().
fnc()
Ref thorin::plug::clos::ClosLit::fnc ()
Definition at line 51 of file clos.cpp.
References thorin::plug::clos::clos_unpack().
Referenced by fnc_as_lam(), and fnc_type().
fnc_as_lam()
Lam * thorin::plug::clos::ClosLit::fnc_as_lam ()
Definition at line 56 of file clos.cpp.
References fnc().
Referenced by env_var(), and ret_var().
fnc_type()
const Pi * thorin::plug::clos::ClosLit::fnc_type () inline
Definition at line 26 of file clos.h.
References fnc(), and thorin::Def::type().
Referenced by is_basicblock(), and is_returning().
get()
attr thorin::plug::clos::ClosLit::get () inline
Clos annotation. These should appear in front of the code-part.
Definition at line 45 of file clos.h.
is_basicblock()
bool thorin::plug::clos::ClosLit::is_basicblock () inline
Definition at line 44 of file clos.h.
References fnc_type(), and thorin::Pi::isa_basicblock().
is_returning()
bool thorin::plug::clos::ClosLit::is_returning () inline
Definition at line 43 of file clos.h.
References fnc_type(), and thorin::Pi::isa_returning().
operator bool()
thorin::plug::clos::ClosLit::operator bool () const inline explicit
Definition at line 33 of file clos.h.
operator const Tuple *()
thorin::plug::clos::ClosLit::operator const Tuple * () inline
Definition at line 34 of file clos.h.
operator->()
const Tuple * thorin::plug::clos::ClosLit::operator-> () inline
Definition at line 36 of file clos.h.
ret_var()
Ref thorin::plug::clos::ClosLit::ret_var () inline
Definition at line 30 of file clos.h.
References fnc_as_lam(), and thorin::Lam::ret_var().
type()
const Sigma * thorin::plug::clos::ClosLit::type () inline
Definition at line 17 of file clos.h.
References thorin::Def::type().
The documentation for this class was generated from the following files:
include/thorin/plug/clos/clos.h
src/thorin/plug/clos/clos.cpp