Thorin: thorin::Scheduler Class Reference
thorin::Scheduler Class Reference
#include <thorin/analyses/schedule.h>
Public Member Functions
Construction
Scheduler ()=default
Scheduler (const Scope &)
Scheduler (const Scheduler &)=delete
Scheduler (Scheduler &&other) noexcept
Scheduler & operator= (Scheduler other) noexcept
Getters
const Scope & scope () const
const F_CFG & cfg () const
const CFNode * cfg (Def *mut) const
const DomTree & domtree () const
const Uses & uses (const Def *def) const
Compute Schedules
Def * early (const Def *)
Def * late (const Def *)
Def * smart (const Def *)
Schedule Mutabales
Order of Mutables within a Scope.
using Schedule = std::vector< Def * >
static Schedule schedule (const Scope &)
Detailed Description
Definition at line 10 of file schedule.h.
Member Typedef Documentation
Schedule
using thorin::Scheduler::Schedule = std::vector<Def*>
Definition at line 47 of file schedule.h.
Constructor & Destructor Documentation
Scheduler() [1/4]
thorin::Scheduler::Scheduler () default
Scheduler() [2/4]
thorin::Scheduler::Scheduler (const Scope & s) explicit
Definition at line 14 of file schedule.cpp.
References thorin::assert_emplace(), thorin::Scope::bound(), cfg(), thorin::Def::is_set(), thorin::Def::isa_mut(), thorin::Def::num_ops(), thorin::Def::op(), thorin::CFG< forward >::reverse_post_order(), scope(), and thorin::Def::type().
Scheduler() [3/4]
thorin::Scheduler::Scheduler (const Scheduler &) delete
Scheduler() [4/4]
thorin::Scheduler::Scheduler (Scheduler && other) inline noexcept
Definition at line 17 of file schedule.h.
References swap.
Member Function Documentation
cfg() [1/2]
const F_CFG & thorin::Scheduler::cfg () const inline
Definition at line 27 of file schedule.h.
Referenced by early(), late(), Scheduler(), and smart().
cfg() [2/2]
const CFNode * thorin::Scheduler::cfg (Def * mut) const inline
Definition at line 28 of file schedule.h.
References cfg().
Referenced by cfg().
domtree()
const DomTree & thorin::Scheduler::domtree () const inline
Definition at line 29 of file schedule.h.
Referenced by early(), late(), and smart().
early()
Def * thorin::Scheduler::early (const Def * def)
Definition at line 49 of file schedule.cpp.
References cfg(), thorin::Def::dep_const(), domtree(), early(), thorin::Scope::entry(), thorin::Def::extended_ops(), thorin::Def::isa_mut(), and scope().
Referenced by early(), and smart().
late()
Def * thorin::Scheduler::late (const Def * def)
Definition at line 65 of file schedule.cpp.
References cfg(), thorin::Def::dep_const(), domtree(), thorin::Scope::entry(), thorin::Def::isa_mut(), late(), thorin::DomTreeBase< forward >::least_common_ancestor(), thorin::CFNode::mut(), scope(), and uses().
Referenced by late(), and smart().
operator=()
Scheduler & thorin::Scheduler::operator= (Scheduler other) inline noexcept
Definition at line 21 of file schedule.h.
References swap.
schedule()
Scheduler::Schedule thorin::Scheduler::schedule (const Scope & scope) static
Definition at line 112 of file schedule.cpp.
References thorin::Scope::f_cfg(), thorin::CFG< forward >::reverse_post_order(), and scope().
Referenced by thorin::ll::Emitter::finalize(), and thorin::Emitter< Value, Type, BB, Child >::visit().
scope()
const Scope & thorin::Scheduler::scope () const inline
Definition at line 26 of file schedule.h.
Referenced by early(), late(), schedule(), and Scheduler().
smart()
Def * thorin::Scheduler::smart (const Def * def)
Definition at line 84 of file schedule.cpp.
References cfg(), domtree(), early(), thorin::DomTreeBase< forward >::idom(), late(), thorin::CFG< forward >::looptree(), and thorin::Scope::world().
uses()
const Uses & thorin::Scheduler::uses (const Def * def) const inline
Definition at line 30 of file schedule.h.
Referenced by late().
The documentation for this class was generated from the following files:
include/thorin/analyses/schedule.h
src/thorin/analyses/schedule.cpp