Thorin: thorin::Array< T > Class Template Reference
thorin::Array< T > Class Template Reference
A container for an array, either heap-allocated or stack allocated.
#include <thorin/util/array.h>
Public Types
using value_type = T
using iterator = T *
using const_iterator = const T *
using reverse_iterator = std::reverse_iterator< iterator >
using const_reverse_iterator = std::reverse_iterator< const_iterator >
Public Member Functions
constructor, destructor & assignment
Array ()
Array (size_t size)
Array (size_t size, const T &val)
Array (Span< T > ref)
Array (Array &&other)
Array (const Array &other)
Array (const std::vector< T > &other)
template<class I >
Array (const I begin, const I end)
Array (std::initializer_list< T > list)
Array (size_t size, std::function< T(size_t)> f)
Array (Span< T > ref, std::function< T(T)> f)
Array & operator= (Array other)
size
size_t size () const
bool empty () const
void shrink (size_t new_size)
begin/end iterators
iterator begin ()
iterator end ()
reverse_iterator rbegin ()
reverse_iterator rend ()
const_iterator begin () const
const_iterator end () const
const_reverse_iterator rbegin () const
const_reverse_iterator rend () const
access
T & front ()
T & back ()
const T & front () const
const T & back () const
T * data ()
const T * data () const
T & operator[] (size_t i)
T const & operator[] (size_t i) const
slice
Span< T > skip_front (size_t num=1) const
Span< T > skip_back (size_t num=1) const
Span< T > first (size_t num=1) const
Span< T > last (size_t num=1) const
convert
Span< T > ref () const
template<size_t N>
std::array< T, N > to_array () const
relational operators
bool operator== (const Array other) const
bool operator!= (const Array other) const
Detailed Description
template<class T>
class thorin::Array< T >
A container for an array, either heap-allocated or stack allocated.
This class is similar to std::vector with the following differences:
If the size is small enough, the array resides on the stack.
In contrast to std::vector, Array cannot grow dynamically. An Array may Array::shrink, however. But once shrunk, there is no way back.
Definition at line 240 of file array.h.
Member Typedef Documentation
const_iterator
template<class T > using thorin::Array< T >::const_iterator = const T*
Definition at line 244 of file array.h.
const_reverse_iterator
template<class T > using thorin::Array< T >::const_reverse_iterator = std::reverse_iterator<const_iterator>
Definition at line 246 of file array.h.
iterator
template<class T > using thorin::Array< T >::iterator = T*
Definition at line 243 of file array.h.
reverse_iterator
template<class T > using thorin::Array< T >::reverse_iterator = std::reverse_iterator<iterator>
Definition at line 245 of file array.h.
value_type
template<class T > using thorin::Array< T >::value_type = T
Definition at line 242 of file array.h.
Constructor & Destructor Documentation
Array() [1/11]
template<class T > thorin::Array< T >::Array () inline
Definition at line 250 of file array.h.
Array() [2/11]
template<class T > thorin::Array< T >::Array (size_t size) inline explicit
Definition at line 252 of file array.h.
Array() [3/11]
template<class T > thorin::Array< T >::Array (size_t size, const T & val) inline
Definition at line 256 of file array.h.
Array() [4/11]
template<class T > thorin::Array< T >::Array (Span< T > ref) inline
Definition at line 260 of file array.h.
References thorin::Array< T >::begin(), and thorin::Array< T >::ref().
Array() [5/11]
template<class T > thorin::Array< T >::Array (Array< T > && other) inline
Definition at line 264 of file array.h.
Array() [6/11]
template<class T > thorin::Array< T >::Array (const Array< T > & other) inline
Definition at line 266 of file array.h.
References thorin::Array< T >::begin().
Array() [7/11]
template<class T > thorin::Array< T >::Array (const std::vector< T > & other) inline
Definition at line 270 of file array.h.
References thorin::Array< T >::begin().
Array() [8/11]
template<class T > template<class I > thorin::Array< T >::Array (const I begin, const I end) inline
Definition at line 275 of file array.h.
References thorin::Array< T >::begin(), thorin::Array< T >::data(), and thorin::Array< T >::end().
Array() [9/11]
template<class T > thorin::Array< T >::Array (std::initializer_list< T > list) inline
Definition at line 279 of file array.h.
References thorin::Array< T >::data().
Array() [10/11]
template<class T > thorin::Array< T >::Array (size_t size, std::function< T(size_t)> f) inline
Definition at line 283 of file array.h.
References thorin::Array< T >::size().
Array() [11/11]
template<class T > thorin::Array< T >::Array (Span< T > ref, std::function< T(T)> f) inline
Definition at line 287 of file array.h.
References thorin::Array< T >::ref().
Member Function Documentation
back() [1/2]
template<class T > T & thorin::Array< T >::back () inline
Definition at line 326 of file array.h.
References thorin::Array< T >::data(), thorin::Array< T >::empty(), and thorin::Array< T >::size().
Referenced by thorin::World::app(), thorin::concat(), and thorin::Def::reduce_rec().
back() [2/2]
template<class T > const T & thorin::Array< T >::back () const inline
Definition at line 334 of file array.h.
References thorin::Array< T >::data(), thorin::Array< T >::empty(), and thorin::Array< T >::size().
begin() [1/2]
template<class T > iterator thorin::Array< T >::begin () inline
Definition at line 310 of file array.h.
References thorin::Array< T >::data().
Referenced by thorin::Array< T >::Array(), thorin::World::bound(), thorin::concat(), thorin::regex::make_binary_tree(), thorin::merge(), and thorin::Array< T >::rend().
begin() [2/2]
template<class T > const_iterator thorin::Array< T >::begin () const inline
Definition at line 314 of file array.h.
References thorin::Array< T >::data().
data() [1/2]
template<class T > T * thorin::Array< T >::data () inline
Definition at line 338 of file array.h.
References thorin::ArrayStorage< T, StackSize >::data().
Referenced by thorin::Array< T >::Array(), thorin::Array< T >::back(), thorin::Array< T >::begin(), thorin::Array< T >::end(), thorin::Array< T >::first(), thorin::Array< T >::front(), thorin::Array< T >::last(), thorin::Array< T >::operator[](), thorin::Array< T >::ref(), thorin::Array< T >::skip_back(), and thorin::Array< T >::skip_front().
data() [2/2]
template<class T > const T * thorin::Array< T >::data () const inline
Definition at line 339 of file array.h.
References thorin::ArrayStorage< T, StackSize >::data().
empty()
template<class T > bool thorin::Array< T >::empty () const inline
Definition at line 301 of file array.h.
References thorin::Array< T >::size().
Referenced by thorin::Array< T >::back(), thorin::Array< T >::front(), and thorin::regex::make_binary_tree().
end() [1/2]
template<class T > iterator thorin::Array< T >::end () inline
Definition at line 311 of file array.h.
References thorin::Array< T >::data(), and thorin::Array< T >::size().
Referenced by thorin::Array< T >::Array(), thorin::regex::make_binary_tree(), and thorin::Array< T >::rbegin().
end() [2/2]
template<class T > const_iterator thorin::Array< T >::end () const inline
Definition at line 315 of file array.h.
References thorin::Array< T >::data(), and thorin::Array< T >::size().
first()
template<class T > Span< T > thorin::Array< T >::first (size_t num = 1) const inline
Definition at line 354 of file array.h.
References thorin::Array< T >::data(), and thorin::Array< T >::size().
front() [1/2]
template<class T > T & thorin::Array< T >::front () inline
Definition at line 322 of file array.h.
References thorin::Array< T >::data(), and thorin::Array< T >::empty().
Referenced by thorin::concat(), and thorin::regex::make_binary_tree().
front() [2/2]
template<class T > const T & thorin::Array< T >::front () const inline
Definition at line 330 of file array.h.
References thorin::Array< T >::data(), and thorin::Array< T >::empty().
last()
template<class T > Span< T > thorin::Array< T >::last (size_t num = 1) const inline
Definition at line 358 of file array.h.
References thorin::Array< T >::data(), and thorin::Array< T >::size().
operator!=()
template<class T > bool thorin::Array< T >::operator!= (const Array< T > other) const inline
Definition at line 376 of file array.h.
operator=()
template<class T > Array & thorin::Array< T >::operator= (Array< T > other) inline
Definition at line 292 of file array.h.
References thorin::Array< T >::swap.
operator==()
template<class T > bool thorin::Array< T >::operator== (const Array< T > other) const inline
Definition at line 375 of file array.h.
operator[]() [1/2]
template<class T > T & thorin::Array< T >::operator[] (size_t i) inline
Definition at line 340 of file array.h.
References thorin::Array< T >::data(), and thorin::Array< T >::size().
operator[]() [2/2]
template<class T > T const & thorin::Array< T >::operator[] (size_t i) const inline
Definition at line 344 of file array.h.
References thorin::Array< T >::data(), and thorin::Array< T >::size().
rbegin() [1/2]
template<class T > reverse_iterator thorin::Array< T >::rbegin () inline
Definition at line 312 of file array.h.
References thorin::Array< T >::end().
rbegin() [2/2]
template<class T > const_reverse_iterator thorin::Array< T >::rbegin () const inline
Definition at line 316 of file array.h.
References thorin::Array< T >::end().
ref()
template<class T > Span< T > thorin::Array< T >::ref () const inline
Definition at line 366 of file array.h.
References thorin::Array< T >::data(), and thorin::Array< T >::size().
Referenced by thorin::Array< T >::Array(), and thorin::Array< T >::to_array().
rend() [1/2]
template<class T > reverse_iterator thorin::Array< T >::rend () inline
Definition at line 313 of file array.h.
References thorin::Array< T >::begin().
rend() [2/2]
template<class T > const_reverse_iterator thorin::Array< T >::rend () const inline
Definition at line 317 of file array.h.
References thorin::Array< T >::begin().
shrink()
template<class T > void thorin::Array< T >::shrink (size_t new_size) inline
Definition at line 302 of file array.h.
References thorin::ArrayStorage< T, StackSize >::shrink(), and thorin::Array< T >::size().
Referenced by thorin::World::bound().
size()
template<class T > size_t thorin::Array< T >::size () const inline
Definition at line 300 of file array.h.
References thorin::ArrayStorage< T, StackSize >::size().
Referenced by thorin::Array< T >::Array(), thorin::Array< T >::back(), thorin::World::bound(), thorin::IndexMap< Indexer, Key, Value >::capacity(), thorin::Array< T >::empty(), thorin::Array< T >::end(), thorin::Array< T >::first(), thorin::Array< T >::last(), thorin::Array< T >::operator[](), thorin::Array< T >::ref(), thorin::Array< T >::shrink(), thorin::Array< T >::skip_back(), and thorin::Array< T >::skip_front().
skip_back()
template<class T > Span< T > thorin::Array< T >::skip_back (size_t num = 1) const inline
Definition at line 353 of file array.h.
References thorin::Array< T >::data(), and thorin::Array< T >::size().
skip_front()
template<class T > Span< T > thorin::Array< T >::skip_front (size_t num = 1) const inline
Definition at line 352 of file array.h.
References thorin::Array< T >::data(), and thorin::Array< T >::size().
to_array()
template<class T > template<size_t N> std::array< T, N > thorin::Array< T >::to_array () const inline
Definition at line 368 of file array.h.
References thorin::Array< T >::ref().
The documentation for this class was generated from the following file:
thorin/util/array.h