Thorin: thorin::Stream Class Reference
thorin::Stream Class Reference
#include <thorin/util/stream.h>
Public Member Functions
Stream (std::ostream &ostream=std::cout, std::string_view tab={" "}, size_t level=0)
void friend swap (Stream &a, Stream &b)
getters
std::ostream & ostream ()
std::string_view tab () const
size_t level () const
modify Stream
Stream & indent (size_t i=1)
Stream & dedent (size_t i=1)
Stream & endl ()
Stream & flush ()
stream
Stream & fmt (const char *s)
Base case.
template<class T , class... Args>
Stream & fmt (const char *s, T &&t, Args &&... args)
fprintf-like function.
template<class R , class F , bool rangei = false>
Stream & range (const R &r, const char *sep, F f)
template<class R , class F , bool rangei = false>
Stream & range (const R &r, F f)
template<class R , class F >
Stream & rangei (const R &r, const char *sep, F f)
template<class R , class F >
Stream & rangei (const R &r, F f)
template<class R >
Stream & range (const R &r, const char *sep=", ")
Protected Member Functions
bool match2nd (const char *next, const char *&s, const char c)
Protected Attributes
std::ostream * ostream_
std::string tab_
size_t level_
Detailed Description
Definition at line 15 of file stream.h.
Constructor & Destructor Documentation
Stream()
thorin::Stream::Stream (std::ostream & ostream = std::cout, std::string_view tab = {" "}, size_t level = 0) inline
Definition at line 17 of file stream.h.
Member Function Documentation
dedent()
Stream & thorin::Stream::dedent (size_t i = 1) inline
Definition at line 32 of file stream.h.
References level_.
Referenced by thorin::ll::CodeGen::finalize(), fmt(), and thorin::World::stream().
endl()
Stream & thorin::Stream::endl ()
Definition at line 5 of file stream.cpp.
References level_, ostream(), and tab_.
Referenced by thorin::Def::dump(), thorin::ll::CodeGen::emit_imported(), thorin::ll::CodeGen::finalize(), fmt(), thorin::World::log(), range(), thorin::RecStreamer::run(), and thorin::World::stream().
flush()
Stream & thorin::Stream::flush () inline
Definition at line 34 of file stream.h.
References ostream().
Referenced by thorin::World::log().
fmt() [1/2]
Stream & thorin::Stream::fmt (const char * s)
Base case.
Definition at line 11 of file stream.cpp.
References dedent(), endl(), indent(), and match2nd().
Referenced by thorin::detail::HashTable< Key, T, H, StackCapacity >::dump(), thorin::ll::CodeGen::emit_bb(), thorin::ll::CodeGen::emit_imported(), thorin::err(), thorin::errf(), thorin::ll::CodeGen::finalize(), fmt(), thorin::Def::let(), thorin::World::log(), thorin::operator<<(), thorin::outf(), thorin::ll::CodeGen::prepare(), thorin::RecStreamer::run(), thorin::Pos::stream(), thorin::Loc::stream(), thorin::LoopTree< forward >::Head::stream(), thorin::LoopTree< forward >::Leaf::stream(), and thorin::Def::unwrap().
fmt() [2/2]
template<class T , class... Args> Stream & thorin::Stream::fmt (const char * s, T && t, Args &&... args)
fprintf-like function.
Each "{}" in s corresponds to one of the variadic arguments in args. The type of the corresponding argument must support operator<< on std::ostream& or preferably Stream. Furthermore, an argument may also be a range-based container where its elements fulfill the condition above. You can specify the separator within the braces:
s.fmt("({, })", list) // yields "(a, b, c)"
If you use "\n" as separator, it will invoke Stream::endl - keeping indentation:
s.fmt("({\n})", list)
Finally, you can use "\n", "\t", and "\b" to endl, indent, or dedent, respectively.
Definition at line 129 of file stream.h.
References dedent(), endl(), fmt(), indent(), match2nd(), range(), and thorin::t.
indent()
Stream & thorin::Stream::indent (size_t i = 1) inline
Definition at line 31 of file stream.h.
References level_.
Referenced by fmt(), and thorin::World::stream().
level()
size_t thorin::Stream::level () const inline
Definition at line 26 of file stream.h.
References level_.
match2nd()
bool thorin::Stream::match2nd (const char * next, const char *& s, const char c) protected
Definition at line 37 of file stream.cpp.
Referenced by fmt().
ostream()
std::ostream & thorin::Stream::ostream () inline
Definition at line 24 of file stream.h.
References ostream_.
Referenced by endl(), flush(), and thorin::operator<<().
range() [1/3]
template<class R , class F , bool use_rangei> Stream & thorin::Stream::range (const R & r, const char * sep, F f)
Definition at line 166 of file stream.h.
References endl(), and thorin::f.
Referenced by fmt(), and thorin::RecStreamer::run().
range() [2/3]
template<class R > Stream & thorin::Stream::range (const R & r, const char * sep = ", ") inline
Definition at line 58 of file stream.h.
References range().
Referenced by range().
range() [3/3]
template<class R , class F , bool rangei = false> Stream & thorin::Stream::range (const R & r, F f) inline
Definition at line 55 of file stream.h.
References thorin::f, and range().
Referenced by range().
rangei() [1/2]
template<class R , class F > Stream & thorin::Stream::rangei (const R & r, const char * sep, F f) inline
Definition at line 56 of file stream.h.
References thorin::f.
rangei() [2/2]
template<class R , class F > Stream & thorin::Stream::rangei (const R & r, F f) inline
Definition at line 57 of file stream.h.
References thorin::f.
swap()
void friend thorin::Stream::swap (Stream & a, Stream & b) inline
Definition at line 61 of file stream.h.
References thorin::a, thorin::b, and swap().
Referenced by swap().
tab()
std::string_view thorin::Stream::tab () const inline
Definition at line 25 of file stream.h.
References tab_.
Member Data Documentation
level_
size_t thorin::Stream::level_ protected
Definition at line 73 of file stream.h.
Referenced by dedent(), endl(), indent(), and level().
ostream_
std::ostream* thorin::Stream::ostream_ protected
Definition at line 71 of file stream.h.
Referenced by ostream().
tab_
std::string thorin::Stream::tab_ protected
Definition at line 72 of file stream.h.
Referenced by endl(), and tab().
The documentation for this class was generated from the following files:
thorin/util/stream.h
thorin/util/stream.cpp