Thorin: thorin::Rewriter Class Reference
thorin::Rewriter Class Reference
Recurseivly rewrites part of a program into the provided World.
#include <thorin/rewrite.h>
Public Member Functions
Rewriter (World &world)
World & world ()
recursively rewrite old Defs
Ref map (Ref old_def, Ref new_def)
virtual Ref rewrite (Ref)
virtual Ref rewrite_imm (Ref)
virtual Ref rewrite_mut (Def *)
Detailed Description
Recurseivly rewrites part of a program into the provided World.
This World may be different than the World we started with.
Definition at line 11 of file rewrite.h.
Constructor & Destructor Documentation
Rewriter()
thorin::Rewriter::Rewriter (World & world) inline
Definition at line 13 of file rewrite.h.
Member Function Documentation
map()
Ref thorin::Rewriter::map (Ref old_def, Ref new_def) inline
Definition at line 20 of file rewrite.h.
Referenced by thorin::World::app(), thorin::rewrite(), rewrite(), and rewrite_mut().
rewrite()
Ref thorin::Rewriter::rewrite (Ref old_def) virtual
Reimplemented in thorin::ScopeRewriter.
Definition at line 9 of file rewrite.cpp.
References thorin::Def::isa_mut(), map(), rewrite_imm(), rewrite_mut(), thorin::World::univ(), and world().
Referenced by thorin::ScopeRewriter::rewrite(), rewrite_imm(), thorin::matrix::LowerMatrixLowLevel::rewrite_imm(), rewrite_mut(), thorin::RWPhase::start(), and thorin::Cleanup::start().
rewrite_imm()
Ref thorin::Rewriter::rewrite_imm (Ref old_def) virtual
Reimplemented in thorin::matrix::LowerMatrixLowLevel.
Definition at line 18 of file rewrite.cpp.
References thorin::Def::dep_const(), thorin::Lit::isa(), thorin::Def::num_ops(), thorin::Def::rebuild(), rewrite(), thorin::Pack::shape(), thorin::Def::type(), and world().
Referenced by rewrite(), and thorin::matrix::LowerMatrixLowLevel::rewrite_imm().
rewrite_mut()
Ref thorin::Rewriter::rewrite_mut (Def * old_mut) virtual
Definition at line 33 of file rewrite.cpp.
References thorin::Def::is_set(), map(), thorin::Def::num_ops(), thorin::Def::op(), rewrite(), thorin::Def::stub(), thorin::Def::type(), and world().
Referenced by rewrite().
world()
World & thorin::Rewriter::world () inline
Definition at line 16 of file rewrite.h.
Referenced by rewrite(), rewrite_imm(), and rewrite_mut().
The documentation for this class was generated from the following files:
thorin/rewrite.h
thorin/rewrite.cpp