Thorin: thorin::fe::Scopes Class Reference
thorin::fe::Scopes Class Reference
#include <thorin/fe/scopes.h>
Public Types
using Scope = SymMap< std::pair< Loc, const Def * > >
Public Member Functions
Scopes ()
void push ()
void pop ()
Scope * curr ()
const Def * query (Dbg) const
const Def * find (Dbg) const
Same as Scopes::query but potentially raises an error.
void bind (Scope *, Dbg, const Def *, bool rebind=false)
void bind (Dbg dbg, const Def *def, bool rebind=false)
void swap (Scope &other)
Detailed Description
Definition at line 15 of file scopes.h.
Member Typedef Documentation
Scope
using thorin::fe::Scopes::Scope = SymMap<std::pair<Loc, const Def*> >
Definition at line 17 of file scopes.h.
Constructor & Destructor Documentation
Scopes()
thorin::fe::Scopes::Scopes () inline
Definition at line 19 of file scopes.h.
References push().
Member Function Documentation
bind() [1/2]
void thorin::fe::Scopes::bind (Dbg dbg, const Def * def, bool rebind = false) inline
Definition at line 27 of file scopes.h.
References bind().
Referenced by bind().
bind() [2/2]
void thorin::fe::Scopes::bind (Scope * scope, Dbg dbg, const Def * def, bool rebind = false)
Definition at line 27 of file scopes.cpp.
References thorin::error().
Referenced by thorin::fe::IdPtrn::bind(), and thorin::fe::TuplePtrn::bind().
curr()
Scope * thorin::fe::Scopes::curr () inline
Definition at line 23 of file scopes.h.
find()
const Def * thorin::fe::Scopes::find (Dbg dbg) const
Same as Scopes::query but potentially raises an error.
Definition at line 21 of file scopes.cpp.
References thorin::error(), and query().
pop()
void thorin::fe::Scopes::pop ()
Definition at line 7 of file scopes.cpp.
push()
void thorin::fe::Scopes::push () inline
Definition at line 21 of file scopes.h.
Referenced by Scopes().
query()
const Def * thorin::fe::Scopes::query (Dbg dbg) const
Definition at line 12 of file scopes.cpp.
Referenced by find().
swap()
void thorin::fe::Scopes::swap (Scope & other) inline
Definition at line 28 of file scopes.h.
The documentation for this class was generated from the following files:
thorin/fe/scopes.h
thorin/fe/scopes.cpp