MimIR: mim::Sets< D, N > Class Template Reference
mim::Sets< D, N > Class Template Reference
#include <mim/util/sets.h>
Classes
class Set
Public Member Functions
Construction
Sets & operator= (const Sets &)=delete
constexpr Sets () noexcept
constexpr Sets (const Sets &) noexcept=delete
constexpr Sets (Sets &&other) noexcept
Set Operations
Note
These operations do not modify the input set(s); they create a new Set.
Set create (Vector< D * > v)
Create a Set wih all elements in v.
Set insert (Set s, D *d)
Yields .
Set merge (Set s1, Set s2)
Yields .
Set erase (Set s, D *d)
Yields .
DOT output
void dot ()
void dot (std::ostream &os) const
void swap (Sets &s1, Sets &s2) noexcept
Detailed Description
template<class D, size_t N = 16>
class mim::Sets< D, N >
Definition at line 13 of file sets.h.
Constructor & Destructor Documentation
Sets() [1/3]
template<class D, size_t N = 16> mim::Sets< D, N >::Sets () inline constexpr noexcept
Definition at line 377 of file sets.h.
Sets() [2/3]
template<class D, size_t N = 16> mim::Sets< D, N >::Sets (const Sets< D, N > &) constexpr delete noexcept
Sets() [3/3]
template<class D, size_t N = 16> mim::Sets< D, N >::Sets (Sets< D, N > && other) inline constexpr noexcept
Definition at line 380 of file sets.h.
Member Function Documentation
create()
template<class D, size_t N = 16> Set mim::Sets< D, N >::create (Vector< D * > v) inline nodiscard
Create a Set wih all elements in v.
Definition at line 391 of file sets.h.
Referenced by mim::Sets< Def >::Set< Def >::erase(), and mim::Sets< Def >::Set< Def >::merge().
dot() [1/2]
template<class D, size_t N = 16> template void mim::Sets< D, N >::dot () inline
Definition at line 552 of file sets.h.
Referenced by mim::Sets< Def >::Set< Def >::dot().
dot() [2/2]
template<class D, size_t N = 16> void mim::Sets< D, N >::dot (std::ostream & os) const inline
Definition at line 557 of file sets.h.
erase()
template<class D, size_t N = 16> Set mim::Sets< D, N >::erase (Set s, D * d) inline nodiscard
Yields .
Definition at line 514 of file sets.h.
Referenced by mim::Sets< Def >::Set< Def >::erase().
insert()
template<class D, size_t N = 16> Set mim::Sets< D, N >::insert (Set s, D * d) inline nodiscard
Yields .
Definition at line 416 of file sets.h.
Referenced by mim::Sets< Def >::Set< Def >::create(), mim::Sets< Def >::Set< Def >::insert(), and mim::Sets< Def >::Set< Def >::merge().
merge()
template<class D, size_t N = 16> Set mim::Sets< D, N >::merge (Set s1, Set s2) inline nodiscard
Yields .
Definition at line 482 of file sets.h.
Referenced by mim::Sets< Def >::Set< Def >::merge(), and mim::Def::mut_local_muts().
operator=()
template<class D, size_t N = 16> Sets & mim::Sets< D, N >::operator= (const Sets< D, N > &) delete
Friends And Related Symbol Documentation
swap
template<class D, size_t N = 16> void swap (Sets< D, N > & s1, Sets< D, N > & s2) friend
Definition at line 565 of file sets.h.
Referenced by mim::Sets< Def >::Set< Def >::Sets(), and mim::Sets< Def >::Set< Def >::swap.
The documentation for this class was generated from the following files:
include/mim/util/sets.h
src/mim/def.cpp