Thorin: thorin::IdPtrn Class Reference
thorin::IdPtrn Class Reference
#include <thorin/fe/ast.h>
Public Member Functions
IdPtrn (Dbg dbg, bool rebind, const Def *type)
void bind (Scopes &, const Def *, bool rebind=false) const override
const Def * type (World &, Def2Fields &) const override
Public Member Functions inherited from thorin::Ptrn
Ptrn (Dbg dbg, bool rebind, const Def *type)
virtual ~Ptrn ()
Dbg dbg () const
Loc loc () const
Sym sym () const
bool rebind () const
bool is_anonymous () const
virtual void bind (Scopes &, const Def *, bool rebind=false) const =0
virtual const Def * type (World &, Def2Fields &) const =0
Additional Inherited Members
Protected Attributes inherited from thorin::Ptrn
Dbg dbg_
bool rebind_
const Def * type_
Detailed Description
Definition at line 47 of file ast.h.
Constructor & Destructor Documentation
IdPtrn()
thorin::IdPtrn::IdPtrn (Dbg dbg, bool rebind, const Def * type) inline
Definition at line 49 of file ast.h.
Member Function Documentation
bind()
void thorin::IdPtrn::bind (Scopes & scopes, const Def * def, bool rebind = false) const override virtual
Implements thorin::Ptrn.
Definition at line 16 of file ast.cpp.
References thorin::Scopes::bind(), thorin::Ptrn::dbg(), and thorin::Ptrn::rebind().
type()
const Def * thorin::IdPtrn::type (World & world, Def2Fields &) const override virtual
Implements thorin::Ptrn.
Definition at line 32 of file ast.cpp.
References thorin::Ptrn::loc(), thorin::World::mut_infer_type(), thorin::Infer::set(), and thorin::Ptrn::type_.
The documentation for this class was generated from the following files:
thorin/fe/ast.h
thorin/fe/ast.cpp