Thorin: thorin::plug::clos::LowerTypedClosPrep Class Reference
thorin::plug::clos::LowerTypedClosPrep Class Reference
#include <thorin/plug/clos/pass/lower_typed_clos_prep.h>
Public Member Functions
LowerTypedClosPrep (PassMan &man)
Public Member Functions inherited from thorin::FPPass< LowerTypedClosPrep, Lam >
FPPass (PassMan &man, std::string_view name)
bool fixed_point () const override
Public Member Functions inherited from thorin::RWPass< P, M >
RWPass (PassMan &man, std::string_view name)
bool inspect () const override
Should the PassMan even consider this pass?
M * curr_mut () const
Public Member Functions inherited from thorin::Pass
Pass (PassMan &, std::string_view name)
virtual ~Pass ()=default
World & world ()
PassMan & man ()
const PassMan & man () const
std::string_view name () const
size_t index () const
virtual Ref rewrite (const Var *var)
virtual Ref rewrite (const Proxy *proxy)
virtual undo_t analyze (const Var *)
virtual undo_t analyze (const Proxy *)
virtual void enter ()
Invoked just before Pass::rewriteing PassMan::curr_mut's body.
virtual void prepare ()
Invoked once before entering the main rewrite loop.
const Proxy * proxy (Ref type, Defs ops, u32 tag=0)
const Proxy * isa_proxy (Ref def, u32 tag=0)
Check whether given def is a Proxy whose Proxy::pass matches this Pass's IPass::index.
const Proxy * as_proxy (Ref def, u32 tag=0)
Private Member Functions
Ref rewrite (Ref) override
undo_t analyze (Ref) override
Additional Inherited Members
Public Types inherited from thorin::FPPass< LowerTypedClosPrep, Lam >
using Super = RWPass< LowerTypedClosPrep, Lam >
using Data = std::tuple<>
Default.
Protected Member Functions inherited from thorin::FPPass< LowerTypedClosPrep, Lam >
const auto & states () const
auto & states ()
auto & data ()
auto & data ()
auto & data (const K &key)
Use this for your convenience if P::Data is a map.
auto & data (const K &key)
Use this for your convenience if P::Data<I> is a map.
undo_t curr_undo () const
Current undo point.
undo_t undo_visit (Def *mut) const
Retrieves the point to backtrack to just before mut was seen the very first time.
undo_t undo_enter (Def *mut) const
Retrieves the point to backtrack to just before rewriting mut's body.
Detailed Description
Definition at line 10 of file lower_typed_clos_prep.h.
Constructor & Destructor Documentation
LowerTypedClosPrep()
thorin::plug::clos::LowerTypedClosPrep::LowerTypedClosPrep (PassMan & man) inline
Definition at line 12 of file lower_typed_clos_prep.h.
Member Function Documentation
analyze()
undo_t thorin::plug::clos::LowerTypedClosPrep::analyze (Ref def) override private virtual
Reimplemented from thorin::Pass.
Definition at line 77 of file lower_typed_clos_prep.cpp.
References thorin::plug::clos::isa_clos_lit(), thorin::Pi::isa_cn(), thorin::No_Undo, and thorin::Pass::world().
rewrite()
Ref thorin::plug::clos::LowerTypedClosPrep::rewrite (Ref def) override private virtual
Reimplemented from thorin::Pass.
Definition at line 66 of file lower_typed_clos_prep.cpp.
References thorin::plug::clos::bot, thorin::World::call(), thorin::plug::clos::clos_pack(), thorin::plug::clos::esc, thorin::plug::clos::isa_clos_lit(), and thorin::Pass::world().
The documentation for this class was generated from the following files:
include/thorin/plug/clos/pass/lower_typed_clos_prep.h
src/thorin/plug/clos/pass/lower_typed_clos_prep.cpp