MimIR: mim::plug::compile::InternalCleanup Class Reference
mim::plug::compile::InternalCleanup Class Reference
#include <mim/plug/compile/pass/internal_cleanup.h>
Public Member Functions
InternalCleanup (PassMan &man, const char *prefix="internal_")
void enter () override
Invoked just before Pass::rewriteing PassMan::curr_mut's body.
Public Member Functions inherited from mim::RWPass< InternalCleanup, Lam >
RWPass (PassMan &man, std::string_view name)
bool inspect () const override
Should the PassMan even consider this pass?
Lam * curr_mut () const
Public Member Functions inherited from mim::Pass
Pass (PassMan &, std::string_view name)
virtual ~Pass ()=default
World & world ()
PassMan & man ()
const PassMan & man () const
std::string_view name () const
size_t index () const
virtual const Def * rewrite (const Def *def)
virtual const Def * rewrite (const Var *var)
virtual const Def * rewrite (const Proxy *proxy)
virtual undo_t analyze (const Def *)
virtual undo_t analyze (const Var *)
virtual undo_t analyze (const Proxy *)
virtual bool fixed_point () const
virtual void prepare ()
Invoked once before entering the main rewrite loop.
const Proxy * proxy (const Def *type, Defs ops, u32 tag=0)
const Proxy * isa_proxy (const Def *def, u32 tag=0)
Check whether given def is a Proxy whose Proxy::pass matches this Pass's IPass::index.
const Proxy * as_proxy (const Def *def, u32 tag=0)
Detailed Description
Definition at line 8 of file internal_cleanup.h.
Constructor & Destructor Documentation
InternalCleanup()
mim::plug::compile::InternalCleanup::InternalCleanup (PassMan & man, const char * prefix = "internal_") inline
Definition at line 10 of file internal_cleanup.h.
References mim::Pass::man(), mim::Pass::PassMan, and mim::RWPass< InternalCleanup, Lam >::RWPass().
Member Function Documentation
enter()
void mim::plug::compile::InternalCleanup::enter () override virtual
Invoked just before Pass::rewriteing PassMan::curr_mut's body.
Note
This is invoked when seeing the inside of a mutable the first time. This is often too late, as you usually want to do something when you see a mutable the first time from the outside. This means that this PassMan::curr_mut has already been encountered elsewhere. Otherwise, we wouldn't have seen PassMan::curr_mut to begin with (unless it is Def::is_external).
Reimplemented from mim::Pass.
Definition at line 9 of file internal_cleanup.cpp.
References mim::RWPass< InternalCleanup, Lam >::curr_mut(), mim::Def::make_internal(), mim::Def::sym(), and mim::Pass::world().
The documentation for this class was generated from the following files:
include/mim/plug/compile/pass/internal_cleanup.h
src/mim/plug/compile/pass/internal_cleanup.cpp