Thorin: thorin::fe::Lexer Class Reference
thorin::fe::Lexer Class Reference
#include <thorin/fe/lexer.h>
Public Member Functions
Lexer (World &world, std::string_view file, std::istream &istream, std::ostream *md=nullptr)
Creates a lexer to read Thorin files (see Lexical Structure).
World & world ()
std::string_view file () const
Loc loc () const
Tok lex ()
Public Member Functions inherited from thorin::utf8::Lexer< 3 >
Lexer (std::string_view filename, std::istream &istream)
virtual ~Lexer ()
Additional Inherited Members
Protected Member Functions inherited from thorin::utf8::Lexer< 3 >
Ahead ahead (size_t i=0) const
virtual Ahead next ()
bool accept_if (Pred pred, bool append=true)
Yields true if pred holds.
bool accept (char32_t val, bool append=true)
Protected Attributes inherited from thorin::utf8::Lexer< 3 >
std::istream & istream_
Loc loc_
std::string str_
std::array< Ahead, Max_Ahead > ahead_
Detailed Description
Definition at line 17 of file lexer.h.
Constructor & Destructor Documentation
Lexer()
thorin::fe::Lexer::Lexer (World & world, std::string_view file, std::istream & istream, std::ostream * md = nullptr)
Creates a lexer to read Thorin files (see Lexical Structure).
If md is not nullptr, a Markdown output will be generated.
Definition at line 12 of file lexer.cpp.
References CODE, THORIN_KEY, and THORIN_SUBST.
Member Function Documentation
file()
std::string_view thorin::fe::Lexer::file () const inline
Definition at line 26 of file lexer.h.
References thorin::Loc::file, and thorin::utf8::Lexer< 3 >::loc_.
lex()
Tok thorin::fe::Lexer::lex ()
Definition at line 31 of file lexer.cpp.
References thorin::utf8::Lexer< 3 >::accept(), thorin::utf8::Lexer< 3 >::accept_if(), thorin::utf8::Lexer< 3 >::ahead(), thorin::Loc::begin, thorin::fe::Tok::D_angle_l, thorin::fe::Tok::D_angle_r, thorin::fe::Tok::D_brace_l, thorin::fe::Tok::D_brace_r, thorin::fe::Tok::D_brckt_l, thorin::fe::Tok::D_brckt_r, thorin::fe::Tok::D_paren_l, thorin::fe::Tok::D_paren_r, thorin::fe::Tok::D_quote_l, thorin::fe::Tok::D_quote_r, thorin::utf8::EoF, thorin::err(), thorin::utf8::Err, thorin::Loc::file, thorin::fe::issign(), loc(), thorin::utf8::Lexer< 3 >::loc_, thorin::fe::Tok::M_ax, thorin::fe::Tok::M_eof, thorin::fe::Tok::M_id, thorin::utf8::Lexer< 3 >::str_, thorin::World::sym(), thorin::fe::Tok::T_arrow, thorin::fe::Tok::T_assign, thorin::fe::Tok::T_at, thorin::fe::Tok::T_bang, thorin::fe::Tok::T_bot, thorin::fe::Tok::T_box, thorin::fe::Tok::T_colon, thorin::fe::Tok::T_colon_colon, thorin::fe::Tok::T_comma, thorin::fe::Tok::T_dot, thorin::fe::Tok::T_extract, thorin::fe::Tok::T_lm, thorin::fe::Tok::T_Pi, thorin::fe::Tok::T_semicolon, thorin::fe::Tok::T_star, and thorin::fe::Tok::T_top.
loc()
Loc thorin::fe::Lexer::loc () const inline
Definition at line 27 of file lexer.h.
References thorin::utf8::Lexer< 3 >::loc_.
Referenced by lex().
world()
World & thorin::fe::Lexer::world () inline
Definition at line 25 of file lexer.h.
Referenced by thorin::fe::Parser::world().
The documentation for this class was generated from the following files:
thorin/fe/lexer.h
thorin/fe/lexer.cpp