MimIR: mim::DomTree Class Reference
mim::DomTree Class Reference
A Dominance Tree.
#include <mim/analyses/domtree.h>
Public Member Functions
DomTree (const DomTree &)=delete
DomTree & operator= (DomTree)=delete
DomTree (const CFG &cfg)
const CFG & cfg () const
size_t index (const CFNode *n) const
const auto & children (const CFNode *n) const
const CFNode * root () const
const CFNode * idom (const CFNode *n) const
int depth (const CFNode *n) const
const CFNode * least_common_ancestor (const CFNode *i, const CFNode *j) const
Returns the least common ancestor of i and j.
Detailed Description
A Dominance Tree.
The template parameter forward determines whether a regular dominance tree (true) or a post-dominance tree (false) should be constructed. This template parameter is associated with CFG's forward parameter.
Definition at line 11 of file domtree.h.
Constructor & Destructor Documentation
DomTree() [1/2]
mim::DomTree::DomTree (const DomTree &) delete
DomTree() [2/2]
mim::DomTree::DomTree (const CFG & cfg) inline explicit
Definition at line 16 of file domtree.h.
References depth(), and root().
Member Function Documentation
cfg()
const CFG & mim::DomTree::cfg () const inline
Definition at line 25 of file domtree.h.
Referenced by index().
children()
const auto & mim::DomTree::children (const CFNode * n) const inline
Definition at line 27 of file domtree.h.
depth()
int mim::DomTree::depth (const CFNode * n) const inline
Definition at line 30 of file domtree.h.
Referenced by DomTree().
idom()
const CFNode * mim::DomTree::idom (const CFNode * n) const inline
Definition at line 29 of file domtree.h.
Referenced by least_common_ancestor().
index()
size_t mim::DomTree::index (const CFNode * n) const inline
Definition at line 26 of file domtree.h.
References cfg(), and mim::CFG::index().
Referenced by least_common_ancestor().
least_common_ancestor()
const CFNode * mim::DomTree::least_common_ancestor (const CFNode * i, const CFNode * j) const
Returns the least common ancestor of i and j.
Definition at line 44 of file domtree.cpp.
References idom(), and index().
operator=()
DomTree & mim::DomTree::operator= (DomTree) delete
root()
const CFNode * mim::DomTree::root () const inline
Definition at line 28 of file domtree.h.
Referenced by DomTree().
The documentation for this class was generated from the following files:
include/mim/analyses/domtree.h
src/mim/analyses/domtree.cpp