MimIR: mim::ast::AxmDecl Class Reference
mim::ast::AxmDecl Class Reference
axm ptrn: type = value;
#include <mim/ast/ast.h>
Classes
class Alias
Public Member Functions
AxmDecl (Loc loc, Dbg dbg, std::deque< Ptrs< Alias > > &&subs, Ptr< Expr > &&type, Dbg normalizer, Tok curry, Tok trip)
Dbg dbg () const
const auto & subs () const
size_t num_subs () const
const auto & sub (size_t i) const
const Expr * type () const
Dbg normalizer () const
Tok curry () const
Tok trip () const
void bind (Scopes &) const override
void emit (Emitter &) const override
std::ostream & stream (Tab &, std::ostream &) const override
Public Member Functions inherited from mim::ast::Decl
const Def * def () const
Public Member Functions inherited from mim::ast::Node
Loc loc () const
void dump () const
Additional Inherited Members
Protected Member Functions inherited from mim::ast::ValDecl
ValDecl (Loc loc)
Protected Member Functions inherited from mim::ast::Decl
Decl (Loc loc)
Protected Member Functions inherited from mim::ast::Node
Node (Loc loc)
virtual ~Node ()
Protected Attributes inherited from mim::ast::Decl
const Def * def_ = nullptr
Detailed Description
axm ptrn: type = value;
Definition at line 857 of file ast.h.
Constructor & Destructor Documentation
AxmDecl()
mim::ast::AxmDecl::AxmDecl (Loc loc, Dbg dbg, std::deque< Ptrs< Alias > > && subs, Ptr< Expr > && type, Dbg normalizer, Tok curry, Tok trip) inline
Definition at line 877 of file ast.h.
References curry(), dbg(), mim::ast::Node::loc(), normalizer(), subs(), trip(), type(), and mim::ast::ValDecl::ValDecl().
Referenced by bind().
Member Function Documentation
bind()
void mim::ast::AxmDecl::bind (Scopes & s) const override virtual
Implements mim::ast::ValDecl.
Definition at line 253 of file bind.cpp.
References AxmDecl(), dbg(), mim::error(), mim::ast::Node::loc(), normalizer(), num_subs(), sub(), subs(), and type().
curry()
Tok mim::ast::AxmDecl::curry () const inline
Definition at line 892 of file ast.h.
Referenced by AxmDecl(), emit(), and stream().
dbg()
Dbg mim::ast::AxmDecl::dbg () const inline
Definition at line 886 of file ast.h.
Referenced by AxmDecl(), mim::ast::AxmDecl::Alias::bind(), bind(), emit(), and stream().
emit()
void mim::ast::AxmDecl::emit (Emitter & e) const override virtual
Implements mim::ast::ValDecl.
Definition at line 382 of file emit.cpp.
References curry(), dbg(), mim::ast::Decl::def_, mim::error(), mim::Axm::infer_curry_and_trip(), num_subs(), sub(), trip(), and type().
normalizer()
Dbg mim::ast::AxmDecl::normalizer () const inline
Definition at line 891 of file ast.h.
Referenced by AxmDecl(), bind(), and stream().
num_subs()
size_t mim::ast::AxmDecl::num_subs () const inline
Definition at line 888 of file ast.h.
Referenced by bind(), emit(), and stream().
stream()
std::ostream & mim::ast::AxmDecl::stream (Tab & tab, std::ostream & os) const override virtual
Implements mim::ast::Node.
Definition at line 184 of file stream.cpp.
References curry(), dbg(), normalizer(), num_subs(), mim::print(), subs(), trip(), and type().
sub()
const auto & mim::ast::AxmDecl::sub (size_t i) const inline
Definition at line 889 of file ast.h.
Referenced by bind(), and emit().
subs()
const auto & mim::ast::AxmDecl::subs () const inline
Definition at line 887 of file ast.h.
Referenced by AxmDecl(), bind(), and stream().
trip()
Tok mim::ast::AxmDecl::trip () const inline
Definition at line 893 of file ast.h.
Referenced by AxmDecl(), emit(), and stream().
type()
const Expr * mim::ast::AxmDecl::type () const inline
Definition at line 890 of file ast.h.
Referenced by AxmDecl(), bind(), emit(), and stream().
The documentation for this class was generated from the following files:
include/mim/ast/ast.h
src/mim/ast/bind.cpp
src/mim/ast/emit.cpp
src/mim/ast/stream.cpp