Thorin: thorin::fe::Parser Class Reference
thorin::fe::Parser Class Reference
Parses Thorin code into the provided World.
#include <thorin/fe/parser.h>
Public Member Functions
Parser (World &world)
World & world ()
Driver & driver ()
void import (fs::path, std::ostream *md=nullptr)
void import (std::istream &, const fs::path *=nullptr, std::ostream *md=nullptr)
void plugin (fs::path)
const Scopes & scopes () const
Detailed Description
Parses Thorin code into the provided World.
The logic behind the various parse methods is as follows:
The parse_* method does not have a std::string_view ctxt parameter:
It's the caller's responsibility to first make appropriate FIRST/FOLLOW checks. Otherwise, an assertion will be triggered in the case of a syntax error.
The parse_* method does have a std::string_view ctxt parameter:
The called method checks this and spits out an appropriate error message using ctxt in the case of a syntax error.
The parse_* method does have a std::string_view ctxt = {} parameter with default argument:
If default argument is elided we have the same behavior as in 1.
If default argument is provided we have the same behavior as in 2.
Definition at line 29 of file parser.h.
Constructor & Destructor Documentation
Parser()
thorin::fe::Parser::Parser (World & world) inline
Definition at line 31 of file parser.h.
Member Function Documentation
driver()
Driver & thorin::fe::Parser::driver () inline
Definition at line 36 of file parser.h.
References thorin::World::driver(), and world().
Referenced by import(), and plugin().
import() [1/2]
void thorin::fe::Parser::import (fs::path name, std::ostream * md = nullptr)
Definition at line 81 of file parser.cpp.
References driver(), and world().
import() [2/2]
void thorin::fe::Parser::import (std::istream & is, const fs::path * path = nullptr, std::ostream * md = nullptr)
Definition at line 100 of file parser.cpp.
References thorin::err(), thorin::fe::Lexer::lex(), and world().
plugin()
void thorin::fe::Parser::plugin (fs::path name)
Definition at line 115 of file parser.cpp.
References thorin::bootstrap(), driver(), and thorin::Driver::load().
scopes()
const Scopes & thorin::fe::Parser::scopes () const inline
Definition at line 40 of file parser.h.
world()
World & thorin::fe::Parser::world () inline
Definition at line 35 of file parser.h.
Referenced by driver(), and import().
The documentation for this class was generated from the following files:
thorin/fe/parser.h
thorin/fe/parser.cpp