MimIR: mim::ClosedMutPhase< M > Class Template Reference
mim::ClosedMutPhase< M > Class Template Reference abstract
Transitively visits all reachable, closed mutables in the World.
#include <mim/phase/phase.h>
Public Member Functions
ClosedMutPhase (World &world, std::string name, bool elide_empty)
bool elide_empty () const
void start () override
Actual entry.
Public Member Functions inherited from mim::Phase
Phase (World &world, std::string name)
virtual ~Phase ()=default
virtual void reset ()
World & world ()
std::string_view name () const
bool todo () const
virtual void run ()
Entry point and generates some debug output; invokes Phase::start.
Protected Member Functions
virtual void visit (M *)=0
M * root () const
Additional Inherited Members
template<class P, class... Args>
static void run (Args &&... args)
Runs a single Phase.
Protected Attributes inherited from mim::Phase
bool todo_ = false
Set to true to indicate that you want to rerun all Phasees in current your fixed-point PhaseMan.
Detailed Description
template<class M = Def>
class mim::ClosedMutPhase< M >
Transitively visits all reachable, closed mutables in the World.
Select with elide_empty whether you want to visit trivial mutables without body.
If you a are only interested in specific mutables, you can pass this to M.
Definition at line 200 of file phase.h.
Constructor & Destructor Documentation
ClosedMutPhase()
template<class M = Def> mim::ClosedMutPhase< M >::ClosedMutPhase (World & world, std::string name, bool elide_empty) inline
Definition at line 202 of file phase.h.
References elide_empty(), mim::Phase::name(), mim::Phase::Phase(), and mim::Phase::world().
Member Function Documentation
elide_empty()
template<class M = Def> bool mim::ClosedMutPhase< M >::elide_empty () const inline
Definition at line 206 of file phase.h.
Referenced by ClosedMutPhase().
root()
template<class M = Def> M * mim::ClosedMutPhase< M >::root () const inline protected
Definition at line 225 of file phase.h.
References M.
start()
template<class M = Def> void mim::ClosedMutPhase< M >::start () inline override virtual
Actual entry.
Implements mim::Phase.
Reimplemented in mim::ll::Emitter.
Definition at line 208 of file phase.h.
References mim::Def::deps(), mim::unique_queue< Set >::empty(), mim::Def::local_muts(), M, mim::unique_queue< Set >::pop(), mim::unique_queue< Set >::push(), visit(), and mim::Phase::world().
visit()
template<class M = Def> virtual void mim::ClosedMutPhase< M >::visit (M *) protected pure virtual
Implemented in mim::NestPhase< Lam >.
References M.
Referenced by start().
The documentation for this class was generated from the following file:
include/mim/phase/phase.h