Thorin: thorin::ArrayStorage< T, StackSize > Class Template Reference
thorin::ArrayStorage< T, StackSize > Class Template Reference
#include <thorin/util/array.h>
Public Member Functions
ArrayStorage ()
ArrayStorage (size_t size)
ArrayStorage (ArrayStorage &&other)
~ArrayStorage ()
size_t size () const
void shrink (size_t new_size)
T * data ()
const T * data () const
Friends
void swap (ArrayStorage &a, ArrayStorage &b)
Detailed Description
template<typename T, size_t StackSize>
class thorin::ArrayStorage< T, StackSize >
Definition at line 153 of file array.h.
Constructor & Destructor Documentation
ArrayStorage() [1/3]
template<typename T , size_t StackSize> thorin::ArrayStorage< T, StackSize >::ArrayStorage () inline
Definition at line 158 of file array.h.
ArrayStorage() [2/3]
template<typename T , size_t StackSize> thorin::ArrayStorage< T, StackSize >::ArrayStorage (size_t size) inline
Definition at line 161 of file array.h.
References thorin::ArrayStorage< T, StackSize >::size().
ArrayStorage() [3/3]
template<typename T , size_t StackSize> thorin::ArrayStorage< T, StackSize >::ArrayStorage (ArrayStorage< T, StackSize > && other) inline
Definition at line 166 of file array.h.
~ArrayStorage()
template<typename T , size_t StackSize> thorin::ArrayStorage< T, StackSize >::~ArrayStorage () inline
Definition at line 174 of file array.h.
Member Function Documentation
data() [1/2]
template<typename T , size_t StackSize> T * thorin::ArrayStorage< T, StackSize >::data () inline
Definition at line 180 of file array.h.
Referenced by thorin::Array< T >::data().
data() [2/2]
template<typename T , size_t StackSize> const T * thorin::ArrayStorage< T, StackSize >::data () const inline
Definition at line 181 of file array.h.
shrink()
template<typename T , size_t StackSize> void thorin::ArrayStorage< T, StackSize >::shrink (size_t new_size) inline
Definition at line 179 of file array.h.
Referenced by thorin::Array< T >::shrink().
size()
template<typename T , size_t StackSize> size_t thorin::ArrayStorage< T, StackSize >::size () const inline
Definition at line 178 of file array.h.
Referenced by thorin::ArrayStorage< T, StackSize >::ArrayStorage(), and thorin::Array< T >::size().
Friends And Related Function Documentation
swap
template<typename T , size_t StackSize> void swap (ArrayStorage< T, StackSize > & a, ArrayStorage< T, StackSize > & b) friend
Definition at line 183 of file array.h.
The documentation for this class was generated from the following file:
/home/runner/work/thorin2/thorin2/thorin/util/array.h