MimIR: mim::ast::Ptrn Class Reference
mim::ast::Ptrn Class Reference abstract
#include <mim/ast/ast.h>
Public Member Functions
Ptrn (Loc loc)
virtual bool is_implicit () const
virtual void bind (Scopes &, bool rebind, bool quiet) const =0
virtual const Def * emit_value (Emitter &, const Def *) const =0
virtual const Def * emit_type (Emitter &) const =0
Public Member Functions inherited from mim::ast::Decl
const Def * def () const
Public Member Functions inherited from mim::ast::Node
Loc loc () const
virtual std::ostream & stream (Tab &, std::ostream &) const =0
void dump () const
Static Public Member Functions
static Ptr< Expr > to_expr (AST &, Ptr< Ptrn > &&)
static Ptr< Ptrn > to_ptrn (Ptr< Expr > &&)
Additional Inherited Members
Protected Member Functions inherited from mim::ast::Decl
Decl (Loc loc)
Protected Member Functions inherited from mim::ast::Node
Node (Loc loc)
virtual ~Node ()
Protected Attributes inherited from mim::ast::Decl
const Def * def_ = nullptr
Detailed Description
Definition at line 190 of file ast.h.
Constructor & Destructor Documentation
Ptrn()
mim::ast::Ptrn::Ptrn (Loc loc) inline
Definition at line 192 of file ast.h.
References mim::ast::Decl::Decl(), and mim::ast::Node::loc().
Referenced by mim::ast::AliasPtrn::AliasPtrn(), mim::ast::ErrorPtrn::ErrorPtrn(), mim::ast::GrpPtrn::GrpPtrn(), mim::ast::IdPtrn::IdPtrn(), mim::ast::AliasPtrn::ptrn(), mim::ast::TuplePtrn::ptrn(), and mim::ast::TuplePtrn::TuplePtrn().
Member Function Documentation
bind()
virtual void mim::ast::Ptrn::bind (Scopes & , bool rebind, bool quiet) const pure virtual
Implemented in mim::ast::AliasPtrn, mim::ast::ErrorPtrn, mim::ast::GrpPtrn, mim::ast::IdPtrn, and mim::ast::TuplePtrn.
Referenced by mim::ast::AliasPtrn::bind(), and mim::ast::MatchExpr::Arm::bind().
emit_type()
virtual const Def * mim::ast::Ptrn::emit_type (Emitter &) const pure virtual
Implemented in mim::ast::AliasPtrn, mim::ast::ErrorPtrn, mim::ast::GrpPtrn, mim::ast::IdPtrn, and mim::ast::TuplePtrn.
Referenced by mim::ast::MatchExpr::Arm::emit(), and mim::ast::AliasPtrn::emit_type().
emit_value()
virtual const Def * mim::ast::Ptrn::emit_value (Emitter & , const Def *) const pure virtual
Implemented in mim::ast::AliasPtrn, mim::ast::ErrorPtrn, mim::ast::GrpPtrn, mim::ast::IdPtrn, and mim::ast::TuplePtrn.
Referenced by mim::ast::MatchExpr::Arm::emit(), mim::ast::TuplePtrn::emit_body(), mim::ast::AliasPtrn::emit_value(), and mim::ast::TuplePtrn::emit_value().
is_implicit()
virtual bool mim::ast::Ptrn::is_implicit () const inline virtual
Reimplemented in mim::ast::AliasPtrn, and mim::ast::TuplePtrn.
Definition at line 195 of file ast.h.
Referenced by mim::ast::AliasPtrn::is_implicit(), and mim::ast::LamDecl::Dom::is_implicit().
to_expr()
Ptr< Expr > mim::ast::Ptrn::to_expr (AST & ast, Ptr< Ptrn > && ptrn) static nodiscard
Definition at line 169 of file ast.cpp.
References mim::ast::IdPtrn::dbg(), and mim::ast::TuplePtrn::is_brckt().
to_ptrn()
Ptr< Ptrn > mim::ast::Ptrn::to_ptrn (Ptr< Expr > && expr) static nodiscard
Definition at line 179 of file ast.cpp.
The documentation for this class was generated from the following files:
include/mim/ast/ast.h
src/mim/ast/ast.cpp