MimIR: mim::ast::CDecl Class Reference
mim::ast::CDecl Class Reference
cfun dbg dom -> codom
#include <mim/ast/ast.h>
Public Member Functions
CDecl (Loc loc, Tok::Tag tag, Dbg dbg, Ptr< Ptrn > &&dom, Ptr< Expr > &&codom)
Dbg dbg () const
Tok::Tag tag () const
const Ptrn * dom () const
const Expr * codom () const
void bind (Scopes &) const override
void emit (Emitter &) const override
std::ostream & stream (Tab &, std::ostream &) const override
Public Member Functions inherited from mim::ast::Decl
const Def * def () const
Public Member Functions inherited from mim::ast::Node
Loc loc () const
void dump () const
Additional Inherited Members
Protected Member Functions inherited from mim::ast::ValDecl
ValDecl (Loc loc)
Protected Member Functions inherited from mim::ast::Decl
Decl (Loc loc)
Protected Member Functions inherited from mim::ast::Node
Node (Loc loc)
virtual ~Node ()
Protected Attributes inherited from mim::ast::Decl
const Def * def_ = nullptr
Detailed Description
cfun dbg dom -> codom
Definition at line 1016 of file ast.h.
Constructor & Destructor Documentation
CDecl()
mim::ast::CDecl::CDecl (Loc loc, Tok::Tag tag, Dbg dbg, Ptr< Ptrn > && dom, Ptr< Expr > && codom) inline
Definition at line 1018 of file ast.h.
References codom(), dbg(), dom(), mim::ast::Node::loc(), tag(), and mim::ast::ValDecl::ValDecl().
Member Function Documentation
bind()
void mim::ast::CDecl::bind (Scopes & s) const override virtual
Implements mim::ast::ValDecl.
Definition at line 348 of file bind.cpp.
References codom(), dbg(), and dom().
codom()
const Expr * mim::ast::CDecl::codom () const inline
Definition at line 1028 of file ast.h.
Referenced by bind(), CDecl(), emit(), and stream().
dbg()
Dbg mim::ast::CDecl::dbg () const inline
Definition at line 1025 of file ast.h.
Referenced by bind(), CDecl(), emit(), and stream().
dom()
const Ptrn * mim::ast::CDecl::dom () const inline
Definition at line 1027 of file ast.h.
Referenced by bind(), CDecl(), emit(), and stream().
emit()
void mim::ast::CDecl::emit (Emitter & e) const override virtual
Implements mim::ast::ValDecl.
Definition at line 495 of file emit.cpp.
References codom(), dbg(), mim::ast::Decl::def_, dom(), and tag().
stream()
std::ostream & mim::ast::CDecl::stream (Tab & tab, std::ostream & os) const override virtual
Implements mim::ast::Node.
Definition at line 231 of file stream.cpp.
References codom(), dbg(), dom(), mim::print(), and tag().
tag()
Tok::Tag mim::ast::CDecl::tag () const inline
Definition at line 1026 of file ast.h.
Referenced by CDecl(), emit(), and stream().
The documentation for this class was generated from the following files:
include/mim/ast/ast.h
src/mim/ast/bind.cpp
src/mim/ast/emit.cpp
src/mim/ast/stream.cpp