MimIR: mim::NestPhase< M > Class Template Reference
mim::NestPhase< M > Class Template Reference abstract
Like ClosedMutPhase but computes a Nest for each NestPhase::visit.
#include <mim/phase.h>
Public Member Functions
NestPhase (World &world, std::string name, bool elide_empty)
NestPhase (World &world, flags_t annex, bool elide_empty)
const Nest & nest () const
virtual void visit (const Nest &)=0
Public Member Functions inherited from mim::ClosedMutPhase< Def >
ClosedMutPhase (World &world, std::string name, bool elide_empty)
ClosedMutPhase (World &world, flags_t annex, bool elide_empty)
bool elide_empty () const
void start () override
Actual entry.
Public Member Functions inherited from mim::Phase
Phase (World &world, std::string name)
Phase (World &world, flags_t annex)
bool todo () const
virtual void run ()
Entry point and generates some debug output; invokes Phase::start.
Public Member Functions inherited from mim::Stage
World & world ()
Driver & driver ()
Log & log () const
std::string_view name () const
flags_t annex () const
Stage (World &world, std::string name)
Stage (World &world, flags_t annex)
virtual ~Stage ()=default
virtual std::unique_ptr< Stage > recreate ()
Creates a new instance; needed by a fixed-point PhaseMan.
virtual void apply (const App *)
Invoked if your Stage has additional args.
virtual void apply (Stage &)
Dito, but invoked by Stage::recreate.
Private Member Functions
void visit (M *mut) final
Additional Inherited Members
template<class P, class... Args>
static void run (Args &&... args)
Runs a single Phase.
static auto create (const Flags2Stages &stages, const Def *def)
template<class A, class P>
static void hook (Flags2Stages &stages)
Protected Member Functions inherited from mim::ClosedMutPhase< Def >
virtual void visit (Def *)=0
Def * root () const
Protected Attributes inherited from mim::Phase
bool todo_ = false
Set to true to indicate that you want to rerun all Phasees in current your fixed-point PhaseMan.
Protected Attributes inherited from mim::Stage
std::string name_
Detailed Description
template<class M = Def>
class mim::NestPhase< M >
Like ClosedMutPhase but computes a Nest for each NestPhase::visit.
Definition at line 190 of file phase.h.
Constructor & Destructor Documentation
NestPhase() [1/2]
template<class M = Def> mim::NestPhase< M >::NestPhase (World & world, std::string name, bool elide_empty) inline
Definition at line 192 of file phase.h.
References mim::ClosedMutPhase< Def >::ClosedMutPhase(), mim::ClosedMutPhase< Def >::elide_empty(), M, mim::Stage::name(), and mim::Stage::world().
NestPhase() [2/2]
template<class M = Def> mim::NestPhase< M >::NestPhase (World & world, flags_t annex, bool elide_empty) inline
Definition at line 194 of file phase.h.
References mim::Stage::annex(), mim::ClosedMutPhase< Def >::ClosedMutPhase(), mim::ClosedMutPhase< Def >::elide_empty(), M, and mim::Stage::world().
Member Function Documentation
nest()
template<class M = Def> const Nest & mim::NestPhase< M >::nest () const inline
Definition at line 197 of file phase.h.
Referenced by visit().
visit() [1/2]
template<class M = Def> virtual void mim::NestPhase< M >::visit (const Nest &) pure virtual
Implemented in mim::Emitter< Value, Type, BB, Child >, mim::Emitter< std::string, std::string, BB, Emitter >, mim::Emitter< std::string, std::string, BB, Emitter >, and mim::plug::mem::AddMem.
Referenced by visit().
visit() [2/2]
template<class M = Def> void mim::NestPhase< M >::visit (M * mut) inline final private
Definition at line 201 of file phase.h.
References M, nest(), and visit().
The documentation for this class was generated from the following file:
include/mim/phase.h