MimIR: mim::Select Class Reference
mim::Select Class Reference
Matches (ff, tt)#cond - where cond is not a Literal.
#include <mim/tuple.h>
Public Member Functions
Select (const Def *)
operator bool () const noexcept
const Extract * extract () const
const Def * pair () const
const Def * cond () const
const Def * tt () const
const Def * ff () const
Detailed Description
Matches (ff, tt)#cond - where cond is not a Literal.
Note
If cond is a Literal, either
(x, y)#lit would have been folded to x/y anyway, or
we have something like this: pair#0_2
Definition at line 261 of file tuple.h.
Constructor & Destructor Documentation
Select()
mim::Select::Select (const Def * def)
Definition at line 51 of file tuple.cpp.
References extract(), and mim::Lit::isa().
Referenced by mim::Branch::Branch().
Member Function Documentation
cond()
const Def * mim::Select::cond () const inline
Definition at line 269 of file tuple.h.
References extract().
extract()
const Extract * mim::Select::extract () const inline
Definition at line 267 of file tuple.h.
Referenced by mim::Branch::Branch(), cond(), pair(), and Select().
ff()
const Def * mim::Select::ff () const inline
Definition at line 271 of file tuple.h.
References pair().
operator bool()
mim::Select::operator bool () const inline explicit noexcept
Definition at line 265 of file tuple.h.
pair()
const Def * mim::Select::pair () const inline
Definition at line 268 of file tuple.h.
References extract().
Referenced by ff(), and tt().
tt()
const Def * mim::Select::tt () const inline
Definition at line 270 of file tuple.h.
References pair().
The documentation for this class was generated from the following files:
include/mim/tuple.h
src/mim/tuple.cpp