MimIR: mim::ast::Import Class Reference
mim::ast::Import Class Reference
#include <mim/ast/ast.h>
Public Member Functions
Import (Loc loc, Tok::Tag tag, Dbg dbg, Ptr< Module > &&module)
Dbg dbg () const
Tok::Tag tag () const
const Module * module () const
void bind (Scopes &) const
void emit (Emitter &) const
std::ostream & stream (Tab &, std::ostream &) const
Public Member Functions inherited from mim::ast::Node
Loc loc () const
void dump () const
Friends
void swap (Import &i1, Import &i2) noexcept
Additional Inherited Members
Protected Member Functions inherited from mim::ast::Node
Node (Loc loc)
virtual ~Node ()
Detailed Description
Definition at line 956 of file ast.h.
Constructor & Destructor Documentation
Import()
mim::ast::Import::Import (Loc loc, Tok::Tag tag, Dbg dbg, Ptr< Module > && module) inline
Definition at line 958 of file ast.h.
Member Function Documentation
bind()
void mim::ast::Import::bind (Scopes & s) const
Definition at line 88 of file bind.cpp.
References mim::ast::Module::bind(), and module().
dbg()
Dbg mim::ast::Import::dbg () const inline
Definition at line 964 of file ast.h.
emit()
void mim::ast::Import::emit (Emitter & e) const
Definition at line 47 of file emit.cpp.
References mim::ast::Module::emit(), and module().
module()
const Module * mim::ast::Import::module () const inline
Definition at line 966 of file ast.h.
Referenced by bind(), and emit().
stream()
std::ostream & mim::ast::Import::stream (Tab & tab, std::ostream & os) const virtual
Implements mim::ast::Node.
Definition at line 41 of file stream.cpp.
References mim::Tab::println(), and tag().
tag()
Tok::Tag mim::ast::Import::tag () const inline
Definition at line 965 of file ast.h.
Referenced by stream().
Friends And Related Symbol Documentation
swap
void swap (Import & i1, Import & i2) friend
Definition at line 972 of file ast.h.
The documentation for this class was generated from the following files:
include/mim/ast/ast.h
src/mim/ast/bind.cpp
src/mim/ast/emit.cpp
src/mim/ast/stream.cpp