Thorin: thorin::ArrayRef< T > Class Template Reference
thorin::ArrayRef< T > Class Template Reference
A container-like wrapper for an array.
#include <thorin/util/array.h>
Public Types
using value_type = T
using const_iterator = const T *
using const_reverse_iterator = std::reverse_iterator< const_iterator >
Public Member Functions
constructor, destructor & assignment
ArrayRef ()
ArrayRef (size_t size, const T *ptr)
template<size_t N>
ArrayRef (const T(&ptr)[N])
ArrayRef (const ArrayRef< T > &ref)
ArrayRef (const Array< T > &array)
template<size_t N>
ArrayRef (const std::array< T, N > &array)
ArrayRef (std::initializer_list< T > list)
ArrayRef (const std::vector< T > &vector)
ArrayRef (ArrayRef &&array)
ArrayRef & operator= (ArrayRef other)
template<size_t N>
std::array< T, N > to_array () const
size
size_t size () const
bool empty () const
begin/end iterators
const_iterator begin () const
const_iterator end () const
const_reverse_iterator rbegin () const
const_reverse_iterator rend () const
access
const T & operator[] (size_t i) const
T const & front () const
T const & back () const
slice
ArrayRef< T > skip_front (size_t num=1) const
ArrayRef< T > skip_back (size_t num=1) const
ArrayRef< T > get_front (size_t num=1) const
ArrayRef< T > get_back (size_t num=1) const
Array< T > cut (ArrayRef< size_t > indices, size_t reserve=0) const
relational operators
template<class Other >
bool operator== (const Other &other) const
template<class Other >
bool operator!= (const Other &other) const
Friends
void swap (ArrayRef< T > &a1, ArrayRef< T > &a2)
Detailed Description
template<class T>
class thorin::ArrayRef< T >
A container-like wrapper for an array.
The array may either stem from a C array, a std::vector, a std::initializer_list, an Array or another ArrayRef. ArrayRef does not own the data and, thus, does not destroy any data. Likewise, you must be carefull to not destroy data an ArrayRef is pointing to. Thorin makes use of ArrayRefs in many places. Note that you can often construct an ArrayRef inline with an initializer_list: foo(arg1, {elem1, elem2, elem3}, arg3). Useful operations are ArrayRef::skip_front and ArrayRef::skip_back to create other ArrayRefs.
Definition at line 30 of file array.h.
Member Typedef Documentation
const_iterator
template<class T > using thorin::ArrayRef< T >::const_iterator = const T*
Definition at line 33 of file array.h.
const_reverse_iterator
template<class T > using thorin::ArrayRef< T >::const_reverse_iterator = std::reverse_iterator<const_iterator>
Definition at line 34 of file array.h.
value_type
template<class T > using thorin::ArrayRef< T >::value_type = T
Definition at line 32 of file array.h.
Constructor & Destructor Documentation
ArrayRef() [1/9]
template<class T > thorin::ArrayRef< T >::ArrayRef () inline
Definition at line 38 of file array.h.
ArrayRef() [2/9]
template<class T > thorin::ArrayRef< T >::ArrayRef (size_t size, const T * ptr) inline
Definition at line 41 of file array.h.
ArrayRef() [3/9]
template<class T > template<size_t N> thorin::ArrayRef< T >::ArrayRef (const T(&) ptr[N]) inline
Definition at line 45 of file array.h.
ArrayRef() [4/9]
template<class T > thorin::ArrayRef< T >::ArrayRef (const ArrayRef< T > & ref) inline
Definition at line 48 of file array.h.
ArrayRef() [5/9]
template<class T > thorin::ArrayRef< T >::ArrayRef (const Array< T > & array) inline
Definition at line 51 of file array.h.
ArrayRef() [6/9]
template<class T > template<size_t N> thorin::ArrayRef< T >::ArrayRef (const std::array< T, N > & array) inline
Definition at line 55 of file array.h.
ArrayRef() [7/9]
template<class T > thorin::ArrayRef< T >::ArrayRef (std::initializer_list< T > list) inline
Definition at line 58 of file array.h.
ArrayRef() [8/9]
template<class T > thorin::ArrayRef< T >::ArrayRef (const std::vector< T > & vector) inline
Definition at line 61 of file array.h.
ArrayRef() [9/9]
template<class T > thorin::ArrayRef< T >::ArrayRef (ArrayRef< T > && array) inline
Definition at line 64 of file array.h.
References thorin::ArrayRef< T >::swap.
Member Function Documentation
back()
template<class T > T const & thorin::ArrayRef< T >::back () const inline
Definition at line 106 of file array.h.
References thorin::ArrayRef< T >::empty().
Referenced by thorin::World::arr(), and thorin::World::pack().
begin()
template<class T > const_iterator thorin::ArrayRef< T >::begin () const inline
Definition at line 90 of file array.h.
Referenced by thorin::get_plugin_search_paths(), thorin::ArrayRef< T >::operator!=(), thorin::ArrayRef< T >::operator==(), and thorin::ArrayRef< T >::rend().
cut()
template<class T > Array< T > thorin::ArrayRef< T >::cut (ArrayRef< size_t > indices, size_t reserve = 0) const
Definition at line 392 of file array.h.
References thorin::ArrayRef< T >::size().
Referenced by thorin::Array< T >::cut().
empty()
template<class T > bool thorin::ArrayRef< T >::empty () const inline
Definition at line 85 of file array.h.
Referenced by thorin::World::arr(), thorin::ArrayRef< T >::back(), thorin::ArrayRef< T >::front(), thorin::Checker::is_uniform(), thorin::World::pack(), and thorin::unflatten().
end()
template<class T > const_iterator thorin::ArrayRef< T >::end () const inline
Definition at line 91 of file array.h.
Referenced by thorin::get_plugin_search_paths(), thorin::ArrayRef< T >::operator!=(), thorin::ArrayRef< T >::operator==(), and thorin::ArrayRef< T >::rbegin().
front()
template<class T > T const & thorin::ArrayRef< T >::front () const inline
Definition at line 102 of file array.h.
References thorin::ArrayRef< T >::empty().
Referenced by thorin::Checker::is_uniform().
get_back()
template<class T > ArrayRef< T > thorin::ArrayRef< T >::get_back (size_t num = 1) const inline
Definition at line 120 of file array.h.
References thorin::ArrayRef< T >::size().
get_front()
template<class T > ArrayRef< T > thorin::ArrayRef< T >::get_front (size_t num = 1) const inline
Definition at line 116 of file array.h.
References thorin::ArrayRef< T >::size().
operator!=()
template<class T > template<class Other > bool thorin::ArrayRef< T >::operator!= (const Other & other) const inline
Definition at line 134 of file array.h.
References thorin::ArrayRef< T >::begin(), thorin::ArrayRef< T >::end(), and thorin::ArrayRef< T >::size().
operator=()
template<class T > ArrayRef & thorin::ArrayRef< T >::operator= (ArrayRef< T > other) inline
Definition at line 69 of file array.h.
References thorin::ArrayRef< T >::swap.
operator==()
template<class T > template<class Other > bool thorin::ArrayRef< T >::operator== (const Other & other) const inline
Definition at line 130 of file array.h.
References thorin::ArrayRef< T >::begin(), thorin::ArrayRef< T >::end(), and thorin::ArrayRef< T >::size().
operator[]()
template<class T > const T & thorin::ArrayRef< T >::operator[] (size_t i) const inline
Definition at line 98 of file array.h.
References thorin::ArrayRef< T >::size().
rbegin()
template<class T > const_reverse_iterator thorin::ArrayRef< T >::rbegin () const inline
Definition at line 92 of file array.h.
References thorin::ArrayRef< T >::end().
rend()
template<class T > const_reverse_iterator thorin::ArrayRef< T >::rend () const inline
Definition at line 93 of file array.h.
References thorin::ArrayRef< T >::begin().
size()
template<class T > size_t thorin::ArrayRef< T >::size () const inline
Definition at line 84 of file array.h.
Referenced by thorin::World::ac(), thorin::clos::ctype(), thorin::ArrayRef< T >::cut(), thorin::ArrayRef< T >::get_back(), thorin::ArrayRef< T >::get_front(), thorin::infer_sigma(), thorin::merge(), thorin::Def::num_extended_ops(), thorin::Def::num_partial_ops(), thorin::affine::op_for(), thorin::ArrayRef< T >::operator!=(), thorin::ArrayRef< T >::operator==(), thorin::ArrayRef< T >::operator[](), thorin::clos::rebuild(), thorin::World::sigma(), thorin::ArrayRef< T >::skip_back(), thorin::ArrayRef< T >::skip_front(), thorin::ArrayRef< T >::to_array(), thorin::World::tuple(), and thorin::unflatten().
skip_back()
template<class T > ArrayRef< T > thorin::ArrayRef< T >::skip_back (size_t num = 1) const inline
Definition at line 115 of file array.h.
References thorin::ArrayRef< T >::size().
Referenced by thorin::World::arr(), and thorin::World::pack().
skip_front()
template<class T > ArrayRef< T > thorin::ArrayRef< T >::skip_front (size_t num = 1) const inline
Definition at line 114 of file array.h.
References thorin::ArrayRef< T >::size().
Referenced by thorin::Checker::is_uniform(), and thorin::Dumper::recurse().
to_array()
template<class T > template<size_t N> std::array< T, N > thorin::ArrayRef< T >::to_array () const inline
Definition at line 74 of file array.h.
References thorin::ArrayRef< T >::size().
Friends And Related Function Documentation
swap
template<class T > void swap (ArrayRef< T > & a1, ArrayRef< T > & a2) friend
Definition at line 139 of file array.h.
Referenced by thorin::ArrayRef< T >::ArrayRef(), and thorin::ArrayRef< T >::operator=().
The documentation for this class was generated from the following file:
thorin/util/array.h