Thorin: thorin::clos::ClosConvPrep Class Reference
thorin::clos::ClosConvPrep Class Reference
#include <dialects/clos/pass/rw/clos_conv_prep.h>
Public Member Functions
ClosConvPrep (PassMan &man, EtaExp *eta_exp)
void enter () override
Invoked just before Pass::rewriteing PassMan::curr_mut's body.
Ref rewrite (Ref) override
const App * rewrite_arg (const App *app)
const App * rewrite_callee (const App *app)
Lam * scope (Lam *lam)
bool from_outer_scope (Lam *lam)
bool from_outer_scope (Ref lam)
Ref eta_wrap (Ref def, attr a)
Public Member Functions inherited from thorin::RWPass< ClosConvPrep, Lam >
RWPass (PassMan &man, std::string_view name)
bool inspect () const override
Should the PassMan even consider this pass?
Lam * curr_mut () const
Public Member Functions inherited from thorin::Pass
Pass (PassMan &, std::string_view name)
virtual ~Pass ()=default
World & world ()
PassMan & man ()
const PassMan & man () const
std::string_view name () const
size_t index () const
virtual Ref rewrite (const Var *var)
virtual Ref rewrite (const Proxy *proxy)
virtual undo_t analyze (Ref)
virtual undo_t analyze (const Var *)
virtual undo_t analyze (const Proxy *)
virtual bool fixed_point () const
virtual void prepare ()
Invoked once before entering the main rewrite loop.
const Proxy * proxy (Ref type, Defs ops, u32 tag=0)
const Proxy * isa_proxy (Ref def, u32 tag=0)
Check whether given def is a Proxy whose Proxy::pass matches this Pass's IPass::index.
const Proxy * as_proxy (Ref def, u32 tag=0)
Detailed Description
Definition at line 14 of file clos_conv_prep.h.
Constructor & Destructor Documentation
ClosConvPrep()
thorin::clos::ClosConvPrep::ClosConvPrep (PassMan & man, EtaExp * eta_exp) inline
Definition at line 16 of file clos_conv_prep.h.
Member Function Documentation
enter()
void thorin::clos::ClosConvPrep::enter () override virtual
Invoked just before Pass::rewriteing PassMan::curr_mut's body.
Note
This is invoked when seeing the inside of a mutable the first time. This is often too late, as you usually want to do something when you see a mutable the first time from the outside. This means that this PassMan::curr_mut has already been encountered elsewhere. Otherwise, we wouldn't have seen PassMan::curr_mut to begin with (unless it is Def::is_external).
Reimplemented from thorin::Pass.
Definition at line 38 of file clos_conv_prep.cpp.
References thorin::Lam::body(), thorin::RWPass< ClosConvPrep, Lam >::curr_mut(), thorin::Pi::isa_cn(), thorin::Lam::isa_mut_basicblock(), thorin::Pi::isa_returning(), and thorin::Pass::world().
eta_wrap()
Ref thorin::clos::ClosConvPrep::eta_wrap (Ref def, attr a) inline
Definition at line 36 of file clos_conv_prep.h.
References thorin::World::call(), thorin::RWPass< ClosConvPrep, Lam >::curr_mut(), scope(), thorin::Def::type(), thorin::Def::var(), and thorin::Pass::world().
Referenced by rewrite_arg(), and rewrite_callee().
from_outer_scope() [1/2]
bool thorin::clos::ClosConvPrep::from_outer_scope (Lam * lam) inline
Definition at line 29 of file clos_conv_prep.h.
References thorin::RWPass< ClosConvPrep, Lam >::curr_mut(), and scope().
Referenced by rewrite_arg().
from_outer_scope() [2/2]
bool thorin::clos::ClosConvPrep::from_outer_scope (Ref lam) inline
Definition at line 34 of file clos_conv_prep.h.
rewrite()
Ref thorin::clos::ClosConvPrep::rewrite (Ref def) override virtual
Reimplemented from thorin::Pass.
Definition at line 133 of file clos_conv_prep.cpp.
References rewrite_arg(), and rewrite_callee().
rewrite_arg()
const App * thorin::clos::ClosConvPrep::rewrite_arg (const App * app)
Definition at line 57 of file clos_conv_prep.cpp.
References thorin::App::arg(), eta_wrap(), thorin::clos::freeBB, from_outer_scope(), thorin::clos::fstclassBB, thorin::Def::isa_mut(), thorin::Lam::isa_mut_basicblock(), thorin::Def::proj(), thorin::Def::refine(), thorin::clos::ret, thorin::Def::set(), and thorin::Pass::world().
Referenced by rewrite().
rewrite_callee()
const App * thorin::clos::ClosConvPrep::rewrite_callee (const App * app)
Definition at line 111 of file clos_conv_prep.cpp.
References thorin::clos::bot, thorin::App::callee(), thorin::App::callee_type(), eta_wrap(), thorin::Pi::isa_cn(), thorin::Def::refine(), thorin::Def::set(), thorin::Def::type(), and thorin::Pass::world().
Referenced by rewrite().
scope()
Lam * thorin::clos::ClosConvPrep::scope (Lam * lam)
Definition at line 33 of file clos_conv_prep.cpp.
References thorin::EtaExp::new2old().
Referenced by eta_wrap(), and from_outer_scope().
The documentation for this class was generated from the following files:
dialects/clos/pass/rw/clos_conv_prep.h
dialects/clos/pass/rw/clos_conv_prep.cpp