Thorin: thorin::Lit Class Reference
thorin::Lit Class Reference
#include <thorin/def.h>
Public Member Functions
template<class T = flags_t>
T get () const
template<bool Ow = false>
const Lit * set (Loc l) const
template<bool Ow = false>
Lit * set (Loc l)
template<bool Ow = false>
const Lit * set (Sym s) const
template<bool Ow = false>
Lit * set (Sym s)
template<bool Ow = false>
const Lit * set (std::string s) const
template<bool Ow = false>
Lit * set (std::string s)
template<bool Ow = false>
const Lit * set (Loc l, Sym s) const
template<bool Ow = false>
Lit * set (Loc l, Sym s)
template<bool Ow = false>
const Lit * set (Loc l, std::string s) const
template<bool Ow = false>
Lit * set (Loc l, std::string s)
template<bool Ow = false>
const Lit * set (Dbg d) const
template<bool Ow = false>
Lit * set (Dbg d)
Lit * stub (World &w, const Def *type)
Public Member Functions inherited from thorin::Def
World & world () const
flags_t flags () const
u32 gid () const
hash_t hash () const
node_t node () const
std::string_view node_name () const
const Def * type () const
Yields the raw type of this Def; maybe nullptr.
const Def * unfold_type () const
Yields the type of this Def and unfolds it if necessary. See Def::type, Def::reduce_rec.
const Def * arity () const
std::optional< nat_t > isa_lit_arity () const
nat_t as_lit_arity () const
bool is_term () const
template<size_t N = -1_s>
auto ops () const
const Def * op (size_t i) const
size_t num_ops () const
Def * set (size_t i, const Def *def)
Def * set (Defs ops)
void unset (size_t i)
void unset ()
Def * set_type (const Def *)
void unset_type ()
void update ()
Resolves Infers of this Def's type.
bool is_set () const
Yields true if empty or the last op is set.
Defs extended_ops () const
const Def * extended_op (size_t i) const
size_t num_extended_ops () const
Defs partial_ops () const
const Def * partial_op (size_t i) const
size_t num_partial_ops () const
const Uses & uses () const
size_t num_uses () const
unsigned dep () const
bool has_dep (Dep d) const
bool has_dep (unsigned u) const
bool dep_const () const
nat_t num_projs () const
Yields Def::arity as_lit, if it is in fact a Lit, or 1 otherwise.
const Def * proj (nat_t a, nat_t i) const
Similar to World::extract while assuming an arity of a but also works on Sigmas, and Arrays.
const Def * proj (nat_t i) const
Same as above but takes Def::num_projs as arity.
template<nat_t A = -1_s, class F >
auto projs (F f) const
Splits this Def via Def::projections into an Array (if A == -1_s) or std::array (otherwise).
template<class F >
auto projs (nat_t a, F f) const
template<nat_t A = -1_s>
auto projs () const
auto projs (nat_t a) const
bool is_external () const
bool is_internal () const
Not Def::is_external.
void make_external ()
void make_internal ()
std::string unique_name () const
name + "_" + Def::gid
template<bool Ow = false>
const Def * set (Loc l) const
template<bool Ow = false>
Def * set (Loc l)
template<bool Ow = false>
const Def * set (Sym s) const
template<bool Ow = false>
Def * set (Sym s)
template<bool Ow = false>
const Def * set (std::string s) const
template<bool Ow = false>
Def * set (std::string s)
template<bool Ow = false>
const Def * set (Loc l, Sym s) const
template<bool Ow = false>
Def * set (Loc l, Sym s)
template<bool Ow = false>
const Def * set (Loc l, std::string s) const
template<bool Ow = false>
Def * set (Loc l, std::string s)
template<bool Ow = false>
const Def * set (Dbg d) const
template<bool Ow = false>
Def * set (Dbg d)
Dbg dbg () const
Loc loc () const
Sym sym () const
const Def * debug_prefix (std::string) const
const Def * debug_suffix (std::string) const
template<class T = Def>
const T * isa_imm () const
template<class T = Def>
const T * as_imm () const
template<class T = Def, bool invert = false>
T * isa_mut () const
If this is *mut*able, it will cast constness away and perform a dynamic cast to T.
template<class T = Def, bool invert = false>
T * as_mut () const
Asserts that this is a *mut*able, casts constness away and performs a static cast to T (checked in Debug build).
const Var * var ()
nat_t num_vars ()
Ref var (nat_t a, nat_t i)
Ref var (nat_t i)
template<nat_t A = -1_s, class F >
auto vars (F f)
template<nat_t A = -1_s>
auto vars ()
template<class F >
auto vars (nat_t a, F f)
auto vars (nat_t a)
DefArray reduce (const Def *arg) const
DefArray reduce (const Def *arg)
const Def * reduce_rec () const
Transitively Def::reduce Lams, if this is an App.
Def * stub (World &w, Ref type)
Ref rebuild (World &w, Ref type, Defs ops) const
Def::rebuilds this Def while using new_op as substitute for its i'th Def::op.
virtual void check ()
virtual size_t first_dependend_op ()
const Def * refine (size_t i, const Def *new_op) const
virtual const Def * restructure ()
void dump () const
void dump (int max) const
void write (int max) const
void write (int max, const char *file) const
std::ostream & stream (std::ostream &, int max) const
Public Member Functions inherited from thorin::RuntimeCast< Def >
T * as ()
static_cast with debug check.
const T * as () const
const version.
T * isa ()
dynamic_cast.
Def * isa ()
Yields B* if it is either T or U and `nullptr* otherwise.
const T * isa () const
const version.
const Def * isa () const
const version.
Static Public Attributes
static constexpr auto Node = Node:: Lit
Friends
class World
Additional Inherited Members
Protected Member Functions inherited from thorin::Def
Def (World *, node_t, const Def *type, Defs ops, flags_t flags)
Constructor for an *imm*utable Def.
Def (node_t n, const Def *type, Defs ops, flags_t flags)
Def (node_t, const Def *type, size_t num_ops, flags_t flags)
Constructor for a *mut*able Def.
virtual ~Def ()=default
virtual Ref rebuild_ (World &, Ref, Defs) const =0
virtual Def * stub_ (World &, Ref)
const Def ** ops_ptr () const
void finalize ()
bool equal (const Def *other) const
Sym get_sym (const char *) const
Sym get_sym (std::string_view) const
Sym get_sym (std::string) const
Protected Attributes inherited from thorin::Def
union {
NormalizeFn normalizer_
Axioms use this member to store their normalizer.
const Axiom * axiom_
World * world_
Curried Apps of Axioms use this member to propagate the Axiom.
};
flags_t flags_
uint8_t node_
bool mut_: 1
bool external_: 1
unsigned dep_: 5
bool padding_: 1
u8 curry_
u8 trip_
hash_t hash_
u32 gid_
u32 num_ops_
Uses uses_
Dbg dbg_
const Def * type_
Detailed Description
Definition at line 616 of file def.h.
Member Function Documentation
get()
template<class T = flags_t> T thorin::Lit::get () const inline
Definition at line 623 of file def.h.
References thorin::Def::flags_.
Referenced by thorin::matrix::LowerMatrixMediumLevel::rewrite_(), thorin::mem::should_flatten(), and thorin_get_plugin().
set() [1/12]
template<bool Ow = false> Lit * thorin::Lit::set (Dbg d) inline
Definition at line 628 of file def.h.
set() [2/12]
template<bool Ow = false> const Lit * thorin::Lit::set (Dbg d) const inline
Definition at line 628 of file def.h.
set() [3/12]
template<bool Ow = false> Lit * thorin::Lit::set (Loc l) inline
Definition at line 628 of file def.h.
set() [4/12]
template<bool Ow = false> const Lit * thorin::Lit::set (Loc l) const inline
Definition at line 628 of file def.h.
set() [5/12]
template<bool Ow = false> Lit * thorin::Lit::set (Loc l, std::string s) inline
Definition at line 628 of file def.h.
set() [6/12]
template<bool Ow = false> const Lit * thorin::Lit::set (Loc l, std::string s) const inline
Definition at line 628 of file def.h.
set() [7/12]
template<bool Ow = false> Lit * thorin::Lit::set (Loc l, Sym s) inline
Definition at line 628 of file def.h.
set() [8/12]
template<bool Ow = false> const Lit * thorin::Lit::set (Loc l, Sym s) const inline
Definition at line 628 of file def.h.
set() [9/12]
template<bool Ow = false> Lit * thorin::Lit::set (std::string s) inline
Definition at line 628 of file def.h.
set() [10/12]
template<bool Ow = false> const Lit * thorin::Lit::set (std::string s) const inline
Definition at line 628 of file def.h.
set() [11/12]
template<bool Ow = false> Lit * thorin::Lit::set (Sym s) inline
Definition at line 628 of file def.h.
set() [12/12]
template<bool Ow = false> const Lit * thorin::Lit::set (Sym s) const inline
Definition at line 628 of file def.h.
stub()
Lit * thorin::Lit::stub (World & w, const Def * type) inline
Definition at line 628 of file def.h.
Friends And Related Function Documentation
World
friend class World friend
Definition at line 628 of file def.h.
Member Data Documentation
Node
constexpr auto thorin::Lit::Node = Node:: Lit static constexpr
Definition at line 628 of file def.h.
The documentation for this class was generated from the following files:
thorin/def.h
thorin/def.cpp