Thorin: thorin::mem::CopyProp Class Reference
thorin::mem::CopyProp Class Reference
This FPPass is similar to sparse conditional constant propagation (SCCP).
#include <dialects/mem/pass/fp/copy_prop.h>
Public Types
using Data = LamMap< DefVec >
Public Types inherited from thorin::FPPass< CopyProp, Lam >
using Super = RWPass< CopyProp, Lam >
using Data = std::tuple<>
Default.
Public Member Functions
CopyProp (PassMan &man, BetaRed *beta_red, EtaExp *eta_exp, bool bb_only=false)
Public Member Functions inherited from thorin::FPPass< CopyProp, Lam >
FPPass (PassMan &man, std::string_view name)
bool fixed_point () const override
Public Member Functions inherited from thorin::RWPass< P, N >
RWPass (PassMan &man, std::string_view name)
bool inspect () const override
Should the PassMan even consider this pass?
N * curr_mut () const
Public Member Functions inherited from thorin::Pass
Pass (PassMan &, std::string_view name)
virtual ~Pass ()=default
World & world ()
PassMan & man ()
const PassMan & man () const
std::string_view name () const
size_t index () const
virtual Ref rewrite (const Var *var)
virtual Ref rewrite (const Proxy *proxy)
virtual undo_t analyze (Ref)
virtual undo_t analyze (const Var *)
virtual void enter ()
Invoked just before Pass::rewriteing PassMan::curr_mut's body.
virtual void prepare ()
Invoked once before entering the main rewrite loop.
const Proxy * proxy (Ref type, Defs ops, u32 tag=0)
const Proxy * isa_proxy (Ref def, u32 tag=0)
Check whether given def is a Proxy whose Proxy::pass matches this Pass's IPass::index.
const Proxy * as_proxy (Ref def, u32 tag=0)
Private Member Functions
PassMan hooks
Ref rewrite (Ref) override
undo_t analyze (const Proxy *) override
Additional Inherited Members
Protected Member Functions inherited from thorin::FPPass< CopyProp, Lam >
const auto & states () const
auto & states ()
auto & data ()
auto & data ()
auto & data (const K &key)
Use this for your convenience if P::Data is a map.
auto & data (const K &key)
Use this for your convenience if P::Data<I> is a map.
undo_t curr_undo () const
Current undo point.
undo_t undo_visit (Def *mut) const
Retrieves the point to backtrack to just before mut was seen the very first time.
undo_t undo_enter (Def *mut) const
Retrieves the point to backtrack to just before rewriting mut's body.
Detailed Description
This FPPass is similar to sparse conditional constant propagation (SCCP).
However, this optmization also works on all Lams alike and does not only consider basic blocks as opposed to traditional SCCP. What is more, this optimization will also propagate arbitrary Defs and not only constants. Finally, it will also remove dead Vars.
Definition at line 16 of file copy_prop.h.
Member Typedef Documentation
Data
using thorin::mem::CopyProp::Data = LamMap<DefVec>
Definition at line 24 of file copy_prop.h.
Constructor & Destructor Documentation
CopyProp()
thorin::mem::CopyProp::CopyProp (PassMan & man, BetaRed * beta_red, EtaExp * eta_exp, bool bb_only = false) inline
Definition at line 18 of file copy_prop.h.
Member Function Documentation
analyze()
undo_t thorin::mem::CopyProp::analyze (const Proxy * proxy) override private virtual
Reimplemented from thorin::Pass.
Definition at line 93 of file copy_prop.cpp.
References thorin::Lit::as(), thorin::Def::as_mut(), thorin::No_Undo, thorin::Def::op(), thorin::Def::ops(), thorin::Pass::proxy(), thorin::Proxy::tag(), thorin::FPPass< CopyProp, Lam >::undo_visit(), and thorin::Pass::world().
rewrite()
Ref thorin::mem::CopyProp::rewrite (Ref def) override private virtual
Reimplemented from thorin::Pass.
Definition at line 10 of file copy_prop.cpp.
References thorin::World::app(), thorin::FPPass< CopyProp, Lam >::data(), thorin::equal(), thorin::isa_apped_mut_lam(), thorin::Lam::isa_returning(), thorin::isa_workable(), thorin::BetaRed::keep(), thorin::mem::mem_var(), thorin::EtaExp::new2old(), thorin::World::pi(), thorin::Proxy, thorin::Pass::proxy(), thorin::World::sigma(), thorin::Pi::stub(), and thorin::Pass::world().
The documentation for this class was generated from the following files:
dialects/mem/pass/fp/copy_prop.h
dialects/mem/pass/fp/copy_prop.cpp