Thorin: thorin::RecDumper Class Reference
thorin::RecDumper Class Reference
Public Member Functions
RecDumper (std::ostream &os, size_t max)
void run (const DepNode *node=nullptr)
void rec (const Def *)
void rec (Defs defs)
void dump (const DepNode *n)
void dump_ptrn (const Def *, const Def *)
void dump (const DepNode *, Lam *)
Static Public Member Functions
static std::string id (const Def *def)
static std::string_view external (const Def *def)
Public Attributes
std::ostream & os
Tab tab
size_t max
unique_queue< NomSet > noms
DefSet defs
Detailed Description
Definition at line 153 of file stream.cpp.
Constructor & Destructor Documentation
RecDumper()
thorin::RecDumper::RecDumper (std::ostream & os, size_t max) inline
Definition at line 155 of file stream.cpp.
Member Function Documentation
dump() [1/2]
void thorin::RecDumper::dump (const DepNode * node, Lam * lam)
Definition at line 299 of file stream.cpp.
References thorin::Lam::body(), thorin::DepNode::children(), thorin::Pi::codom(), thorin::Pi::dom(), dump_ptrn(), external(), thorin::Pi::is_cn(), thorin::Def::is_set(), thorin::Tab::lnprint(), noms, thorin::Def::ops(), os, thorin::Tab::print(), thorin::unique_queue< Set >::push(), rec(), run(), tab, thorin::Lam::type(), and thorin::Def::var().
dump() [2/2]
void thorin::RecDumper::dump (const DepNode * n)
Definition at line 257 of file stream.cpp.
References thorin::DepNode::nom(), noms, thorin::unique_queue< Set >::push(), and run().
Referenced by thorin::World::dump(), and run().
dump_ptrn()
void thorin::RecDumper::dump_ptrn (const Def * def, const Def * type)
Definition at line 284 of file stream.cpp.
References dump_ptrn(), os, thorin::print(), thorin::Def::proj(), thorin::Def::projs(), and thorin::Def::unique_name().
Referenced by dump(), and dump_ptrn().
external()
static std::string_view thorin::RecDumper::external (const Def * def) inline static
Definition at line 173 of file stream.cpp.
References thorin::Def::is_external().
Referenced by dump(), and run().
id()
static std::string thorin::RecDumper::id (const Def * def) inline static
Definition at line 168 of file stream.cpp.
References thorin::Def::is_external(), thorin::Def::is_set(), thorin::RuntimeCast< Base >::isa(), thorin::Def::name(), and thorin::Def::unique_name().
rec() [1/2]
void thorin::RecDumper::rec (const Def * def)
Definition at line 264 of file stream.cpp.
References defs, thorin::Def::isa_nom(), thorin::let(), thorin::Tab::lnprint(), max, noms, thorin::clos::op(), thorin::Def::ops(), os, thorin::unique_queue< Set >::push(), rec(), and tab.
Referenced by dump(), rec(), run(), and thorin::Def::stream().
rec() [2/2]
void thorin::RecDumper::rec (Defs defs) inline
Definition at line 161 of file stream.cpp.
References defs, and rec().
run()
void thorin::RecDumper::run (const DepNode * node = nullptr)
Definition at line 185 of file stream.cpp.
References thorin::DepNode::children(), dump(), thorin::e, thorin::unique_queue< Set >::empty(), external(), thorin::Tab::lnprint(), noms, os, thorin::unique_queue< Set >::pop(), thorin::print(), thorin::Tab::print(), thorin::unique_queue< Set >::push(), rec(), run(), tab, and thorin::unreachable().
Referenced by dump(), run(), and thorin::Def::stream().
Member Data Documentation
defs
DefSet thorin::RecDumper::defs
Definition at line 182 of file stream.cpp.
Referenced by rec().
max
size_t thorin::RecDumper::max
Definition at line 180 of file stream.cpp.
Referenced by rec().
noms
unique_queue<NomSet> thorin::RecDumper::noms
Definition at line 181 of file stream.cpp.
Referenced by dump(), rec(), run(), and thorin::Def::stream().
os
std::ostream& thorin::RecDumper::os
Definition at line 178 of file stream.cpp.
Referenced by dump(), dump_ptrn(), rec(), and run().
tab
Tab thorin::RecDumper::tab
Definition at line 179 of file stream.cpp.
Referenced by dump(), rec(), and run().
The documentation for this class was generated from the following file:
/home/runner/work/thorin2/thorin2/thorin/stream.cpp