Thorin: thorin::RetWrap Class Reference
thorin::RetWrap Class Reference
#include <thorin/pass/ret_wrap.h>
Public Member Functions
RetWrap (PassMan &man)
void enter () override
Invoked just before Pass::rewriteing PassMan::curr_mut's body.
Public Member Functions inherited from thorin::RWPass< RetWrap, Lam >
RWPass (PassMan &man, std::string_view name)
bool inspect () const override
Should the PassMan even consider this pass?
Lam * curr_mut () const
Public Member Functions inherited from thorin::Pass
Pass (PassMan &, std::string_view name)
virtual ~Pass ()=default
World & world ()
PassMan & man ()
const PassMan & man () const
std::string_view name () const
size_t index () const
virtual Ref rewrite (Ref def)
virtual Ref rewrite (const Var *var)
virtual Ref rewrite (const Proxy *proxy)
virtual undo_t analyze (Ref)
virtual undo_t analyze (const Var *)
virtual undo_t analyze (const Proxy *)
virtual bool fixed_point () const
virtual void prepare ()
Invoked once before entering the main rewrite loop.
const Proxy * proxy (Ref type, Defs ops, u32 tag=0)
const Proxy * isa_proxy (Ref def, u32 tag=0)
Check whether given def is a Proxy whose Proxy::pass matches this Pass's IPass::index.
const Proxy * as_proxy (Ref def, u32 tag=0)
Detailed Description
Definition at line 7 of file ret_wrap.h.
Constructor & Destructor Documentation
RetWrap()
thorin::RetWrap::RetWrap (PassMan & man) inline
Definition at line 9 of file ret_wrap.h.
Member Function Documentation
enter()
void thorin::RetWrap::enter () override virtual
Invoked just before Pass::rewriteing PassMan::curr_mut's body.
Note
This is invoked when seeing the inside of a mutable the first time. This is often too late, as you usually want to do something when you see a mutable the first time from the outside. This means that this PassMan::curr_mut has already been encountered elsewhere. Otherwise, we wouldn't have seen PassMan::curr_mut to begin with (unless it is Def::is_external).
Reimplemented from thorin::Pass.
Definition at line 5 of file ret_wrap.cpp.
References thorin::Lam::app(), thorin::RWPass< RetWrap, Lam >::curr_mut(), thorin::World::mut_lam(), thorin::Def::reset(), thorin::Lam::ret_var(), thorin::Lam::set(), thorin::World::tuple(), thorin::Def::vars(), and thorin::Pass::world().
The documentation for this class was generated from the following files:
include/thorin/pass/ret_wrap.h
src/thorin/pass/ret_wrap.cpp