MimIR: mim::RWPhase Class Reference
mim::RWPhase Class Reference
Rewrites the RWPhase::old_world into the RWPhase::new_world and swaps them afterwards.
#include <mim/phase.h>
Public Member Functions
bool is_bootstrapping () const
virtual bool analyze ()
You can do an optional fixed-point loop on the RWPhase::old_world before rewriting.
Construction
RWPhase (World &world, std::string name)
RWPhase (World &world, flags_t annex)
Rewrite
virtual void rewrite_annex (flags_t, const Def *)
virtual void rewrite_external (Def *)
World
Phase::world is the old one.
Rewriter::world is the new one.
RWPhase::world is deleted to not confuse this.
World & world ()=delete
Hides both and forbids direct access.
World & old_world ()
Get old Defs from here.
World & new_world ()
Create new Defs into this.
Public Member Functions inherited from mim::Phase
Phase (World &world, std::string name)
Phase (World &world, flags_t annex)
bool todo () const
virtual void run ()
Entry point and generates some debug output; invokes Phase::start.
Public Member Functions inherited from mim::Stage
World & world ()
Driver & driver ()
Log & log () const
std::string_view name () const
flags_t annex () const
Stage (World &world, std::string name)
Stage (World &world, flags_t annex)
virtual ~Stage ()=default
virtual std::unique_ptr< Stage > recreate ()
Creates a new instance; needed by a fixed-point PhaseMan.
virtual void apply (const App *)
Invoked if your Stage has additional args.
virtual void apply (Stage &)
Dito, but invoked by Stage::recreate.
Public Member Functions inherited from mim::Rewriter
Rewriter (std::unique_ptr< World > &&ptr)
Rewriter (World &world)
void reset (std::unique_ptr< World > &&ptr)
void reset ()
World & world ()
virtual void push ()
virtual void pop ()
const Def * map (const Def *old_def, const Def *new_def)
Map old_def to new_def and returns new_def.
const Def * map (const Def *old_def, Defs new_defs)
const Def * map (Defs old_defs, const Def *new_def)
const Def * map (Defs old_defs, Defs new_defs)
const Def * lookup (const Def *old_def)
Lookup old_def by searching in reverse through the stack of maps.
virtual const Def * rewrite (const Def *)
virtual const Def * rewrite_imm (const Def *)
virtual const Def * rewrite_mut (Def *)
virtual const Def * rewrite_stub (Def *, Def *)
virtual DefVec rewrite (Defs)
virtual const Def * rewrite_imm_Seq (const Seq *seq)
virtual const Def * rewrite_mut_Seq (Seq *seq)
Protected Member Functions
void start () override
Actual entry.
Additional Inherited Members
template<class P, class... Args>
static void run (Args &&... args)
Runs a single Phase.
static auto create (const Flags2Stages &stages, const Def *def)
template<class A, class P>
static void hook (Flags2Stages &stages)
Protected Attributes inherited from mim::Phase
bool todo_ = false
Set to true to indicate that you want to rerun all Phasees in current your fixed-point PhaseMan.
Protected Attributes inherited from mim::Stage
std::string name_
Detailed Description
Rewrites the RWPhase::old_world into the RWPhase::new_world and swaps them afterwards.
This will destroy RWPhase::old_world leaving RWPhase::new_world which will be created here as the current World to work with. This Phase will recursively Rewriter::rewrite
all (old) World::annexes() (during which RWPhase::is_bootstrapping is true), and then
all (old) World::externals() (during which RWPhase::is_bootstrapping is false).
Note
You can override Rewriter::rewrite, Rewriter::rewrite_imm, Rewriter::rewrite_mut, etc.
Definition at line 67 of file phase.h.
Constructor & Destructor Documentation
RWPhase() [1/2]
mim::RWPhase::RWPhase (World & world, std::string name) inline
Definition at line 71 of file phase.h.
References mim::Stage::name(), mim::Phase::Phase(), mim::Rewriter::Rewriter(), and world().
Referenced by mim::BetaRedPhase::BetaRedPhase(), mim::BranchNormalizePhase::BranchNormalizePhase(), mim::Cleanup::Cleanup(), mim::Cleanup::Cleanup(), mim::EtaExpPhase::EtaExpPhase(), mim::EtaRedPhase::EtaRedPhase(), mim::plug::affine::phase::LowerFor::LowerFor(), mim::plug::matrix::LowerMatrixLowLevel::LowerMatrixLowLevel(), mim::PrefixCleanup::PrefixCleanup(), mim::ReplManPhase::ReplManPhase(), mim::ReplManPhase::ReplManPhase(), and mim::RetWrap::RetWrap().
RWPhase() [2/2]
mim::RWPhase::RWPhase (World & world, flags_t annex) inline
Definition at line 74 of file phase.h.
References mim::Stage::annex(), mim::Phase::Phase(), mim::Rewriter::Rewriter(), and world().
Member Function Documentation
analyze()
virtual bool mim::RWPhase::analyze () inline virtual
You can do an optional fixed-point loop on the RWPhase::old_world before rewriting.
Note
If you don't need a fixed-point, just return false after the first run of analyze.
Reimplemented in mim::BetaRedPhase, mim::EtaExpPhase, and mim::RetWrap.
Definition at line 83 of file phase.h.
Referenced by start().
is_bootstrapping()
bool mim::RWPhase::is_bootstrapping () const inline
Definition at line 79 of file phase.h.
Referenced by mim::plug::matrix::LowerMatrixLowLevel::rewrite_imm_App().
new_world()
World & mim::RWPhase::new_world () inline
Create new Defs into this.
Definition at line 100 of file phase.h.
References mim::Rewriter::world().
Referenced by rewrite_annex(), mim::EtaExpPhase::rewrite_imm_App(), mim::plug::affine::phase::LowerFor::rewrite_imm_App(), mim::plug::matrix::LowerMatrixLowLevel::rewrite_imm_App(), mim::EtaExpPhase::rewrite_imm_Var(), mim::EtaRedPhase::rewrite_imm_Var(), mim::RetWrap::rewrite_mut_Lam(), and start().
old_world()
World & mim::RWPhase::old_world () inline
Get old Defs from here.
Definition at line 99 of file phase.h.
References mim::Stage::world().
Referenced by mim::BetaRedPhase::analyze(), mim::EtaExpPhase::analyze(), mim::RetWrap::analyze(), mim::ReplManPhase::apply(), mim::RetWrap::rewrite_mut_Lam(), mim::ReplManPhase::start(), and start().
rewrite_annex()
void mim::RWPhase::rewrite_annex (flags_t f, const Def * def) virtual
Definition at line 40 of file phase.cpp.
References new_world(), mim::World::register_annex(), and mim::Rewriter::rewrite().
Referenced by start().
rewrite_external()
void mim::RWPhase::rewrite_external (Def * old_mut) virtual
Reimplemented in mim::EtaExpPhase, mim::EtaRedPhase, and mim::PrefixCleanup.
Definition at line 42 of file phase.cpp.
References mim::Def::as_mut(), mim::Def::is_external(), and mim::Rewriter::rewrite().
Referenced by start().
start()
void mim::RWPhase::start () override protected virtual
Actual entry.
Implements mim::Phase.
Definition at line 23 of file phase.cpp.
References analyze(), new_world(), old_world(), rewrite_annex(), rewrite_external(), and mim::Phase::todo().
Referenced by mim::ReplManPhase::start().
world()
World & mim::RWPhase::world () delete
Hides both and forbids direct access.
Referenced by mim::BetaRedPhase::BetaRedPhase(), mim::BranchNormalizePhase::BranchNormalizePhase(), mim::Cleanup::Cleanup(), mim::Cleanup::Cleanup(), mim::EtaExpPhase::EtaExpPhase(), mim::EtaRedPhase::EtaRedPhase(), mim::plug::affine::phase::LowerFor::LowerFor(), mim::plug::matrix::LowerMatrixLowLevel::LowerMatrixLowLevel(), mim::PrefixCleanup::PrefixCleanup(), mim::ReplManPhase::ReplManPhase(), mim::ReplManPhase::ReplManPhase(), mim::RetWrap::RetWrap(), RWPhase(), and RWPhase().
The documentation for this class was generated from the following files:
include/mim/phase.h
src/mim/phase.cpp