MimIR: mim::Analysis Class Reference
mim::Analysis Class Reference
This Phase will recursively Rewriter::rewrite.
#include <mim/phase.h>
Public Member Functions
bool is_bootstrapping () const
Construction & Destruction
Analysis (World &world, std::string name)
Analysis (World &world, flags_t annex)
virtual void reset ()
Clears all members and sets todo() to false for next round in a fixed-point iteration.
Rewrite
virtual void rewrite_annex (flags_t, const Def *)
virtual void rewrite_external (Def *)
Getters
World & world ()
Public Member Functions inherited from mim::Phase
Phase (World &world, std::string name)
Phase (World &world, flags_t annex)
bool todo () const
virtual void run ()
Entry point and generates some debug output; invokes Phase::start.
Public Member Functions inherited from mim::Stage
World & world ()
Driver & driver ()
Log & log () const
std::string_view name () const
flags_t annex () const
Stage (World &world, std::string name)
Stage (World &world, flags_t annex)
virtual ~Stage ()=default
virtual std::unique_ptr< Stage > recreate ()
Creates a new instance; needed by a fixed-point PhaseMan.
virtual void apply (const App *)
Invoked if your Stage has additional args.
virtual void apply (Stage &)
Dito, but invoked by Stage::recreate.
Public Member Functions inherited from mim::Rewriter
Rewriter (std::unique_ptr< World > &&ptr)
Rewriter (World &world)
virtual ~Rewriter ()=default
void reset (std::unique_ptr< World > &&ptr)
void reset ()
World & world ()
virtual void push ()
virtual void pop ()
virtual const Def * map (const Def *old_def, const Def *new_def)
const Def * map (const Def *old_def, Defs new_defs)
const Def * map (Defs old_defs, const Def *new_def)
const Def * map (Defs old_defs, Defs new_defs)
virtual const Def * lookup (const Def *old_def)
Lookup old_def by searching in reverse through the stack of maps.
virtual const Def * rewrite (const Def *)
virtual const Def * rewrite_imm (const Def *)
virtual const Def * rewrite_mut (Def *)
virtual const Def * rewrite_stub (Def *, Def *)
virtual DefVec rewrite (Defs)
virtual const Def * rewrite_imm_Seq (const Seq *seq)
virtual const Def * rewrite_mut_Seq (Seq *seq)
Protected Member Functions
void start () override
Actual entry.
Additional Inherited Members
template<class P, class... Args>
static void run (Args &&... args)
Runs a single Phase.
static auto create (const Flags2Stages &stages, const Def *def)
template<class A, class P>
static void hook (Flags2Stages &stages)
Protected Attributes inherited from mim::Phase
bool todo_ = false
Set to true to indicate that you want to rerun all Phasees in your current fixed-point PhaseMan.
Protected Attributes inherited from mim::Stage
std::string name_
Protected Attributes inherited from mim::Rewriter
std::deque< Def2Def > old2news_
Detailed Description
This Phase will recursively Rewriter::rewrite.
all World::annexes() (during which Analysis::is_bootstrapping is true), and then
all World::externals() (during which Analysis::is_bootstrapping is false).
Note
You can override Rewriter::rewrite, Rewriter::rewrite_imm, Rewriter::rewrite_mut, etc.
Definition at line 64 of file phase.h.
Constructor & Destructor Documentation
Analysis() [1/2]
mim::Analysis::Analysis (World & world, std::string name) inline
Definition at line 68 of file phase.h.
References mim::Stage::name(), mim::Phase::Phase(), mim::Rewriter::Rewriter(), and world().
Analysis() [2/2]
mim::Analysis::Analysis (World & world, flags_t annex) inline
Definition at line 71 of file phase.h.
References mim::Stage::annex(), mim::Phase::Phase(), mim::Rewriter::Rewriter(), and world().
Member Function Documentation
is_bootstrapping()
bool mim::Analysis::is_bootstrapping () const inline
Definition at line 80 of file phase.h.
reset()
void mim::Analysis::reset () virtual
Clears all members and sets todo() to false for next round in a fixed-point iteration.
See also
RWPhase::analyze
Definition at line 23 of file phase.cpp.
References mim::Rewriter::old2news_, mim::Rewriter::push(), and mim::Phase::todo_.
rewrite_annex()
void mim::Analysis::rewrite_annex (flags_t , const Def * def) virtual
Definition at line 39 of file phase.cpp.
References mim::Rewriter::rewrite().
Referenced by start().
rewrite_external()
void mim::Analysis::rewrite_external (Def * mut) virtual
Definition at line 40 of file phase.cpp.
References mim::Rewriter::rewrite().
Referenced by start().
start()
void mim::Analysis::start () override protected virtual
Actual entry.
Implements mim::Phase.
Definition at line 29 of file phase.cpp.
References rewrite_annex(), rewrite_external(), and world().
world()
World & mim::Analysis::world () inline
Definition at line 90 of file phase.h.
References mim::Stage::world().
Referenced by Analysis(), Analysis(), and start().
The documentation for this class was generated from the following files:
include/mim/phase.h
src/mim/phase.cpp