Thorin: dialects/compile/compile.cpp File Reference
compile.cpp File Reference
#include "dialects/compile/compile.h"
#include <thorin/config.h>
#include <thorin/pass/pass.h>
#include "thorin/pass/fp/beta_red.h"
#include "thorin/pass/fp/eta_exp.h"
#include "thorin/pass/fp/eta_red.h"
#include "thorin/pass/fp/tail_rec_elim.h"
#include "thorin/pass/pipelinebuilder.h"
#include "thorin/pass/rw/lam_spec.h"
#include "thorin/pass/rw/ret_wrap.h"
#include "thorin/pass/rw/scalarize.h"
#include "dialects/compile/autogen.h"
#include "dialects/compile/passes/debug_print.h"
#include "dialects/compile/passes/internal_cleanup.h"
Functions
void add_phases (DefVec &phases, World &world, Passes &passes, PipelineBuilder &builder)
void add_passes (World &world, PipelineBuilder &builder, Passes &passes, DefVec &pass_list)
THORIN_EXPORT thorin::Plugin thorin_get_plugin ()
Function Documentation
add_passes()
void add_passes (World & world, PipelineBuilder & builder, Passes & passes, DefVec & pass_list)
Definition at line 25 of file compile.cpp.
References thorin::PipelineBuilder::begin_pass_phase(), thorin::PipelineBuilder::end_pass_phase(), and thorin::compile::handle_optimization_part().
Referenced by thorin_get_plugin().
add_phases()
void add_phases (DefVec & phases, World & world, Passes & passes, PipelineBuilder & builder)
Definition at line 21 of file compile.cpp.
References thorin::compile::handle_optimization_part().
Referenced by thorin_get_plugin().
thorin_get_plugin()
THORIN_EXPORT thorin::Plugin thorin_get_plugin ()
Definition at line 36 of file compile.cpp.
References add_passes(), thorin::PipelineBuilder::add_phase(), add_phases(), thorin::App::arg(), thorin::RuntimeCast< B >::as(), thorin::assert_emplace(), thorin::collect_args(), thorin::PipelineBuilder::def2pass(), thorin::Lit::get(), thorin::Def::projs(), and thorin::compile::register_normalizers().