Thorin: cli/main.cpp File Reference
main.cpp File Reference
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <iostream>
#include <lyra/lyra.hpp>
#include "thorin/config.h"
#include "thorin/driver.h"
#include "thorin/be/dot/dot.h"
#include "thorin/be/h/bootstrap.h"
#include "thorin/fe/parser.h"
#include "thorin/pass/optimize.h"
#include "thorin/pass/pass.h"
#include "thorin/pass/pipelinebuilder.h"
#include "thorin/phase/phase.h"
#include "thorin/util/sys.h"
Enumerations
enum Backends {
Dot , H , LL , Md ,
Thorin , Num_Backends
}
Functions
int main (int argc, char **argv)
Enumeration Type Documentation
Backends
enum Backends
Enumerator
Dot
H
LL
Md
Thorin
Num_Backends
Definition at line 23 of file main.cpp.
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 25 of file main.cpp.
References thorin::bootstrap(), thorin::World::breakpoint(), Dot, thorin::World::dump(), thorin::dot::emit(), thorin::err(), thorin::errln(), thorin::sys::find_cmd(), thorin::Driver::flags(), H, LL, Md, Num_Backends, thorin::optimize(), thorin::World::set(), thorin::World::sym(), Thorin, THORIN_ENABLE_CHECKS, THORIN_VER, and THORIN_WHICH.