Thorin: thorin::plug::matrix Namespace Reference
thorin::plug::matrix Namespace Reference
The matrix Plugin
Classes
class LowerMatrixHighLevelMapRed
Resolves lowering of high level operations into medium/other high-level operations.
class LowerMatrixLowLevel
In this phase, we lower all matrix operations and types to the low-level representation using pointers.
class LowerMatrixMediumLevel
In this step, we lower map_reduce operations into affine for loops making the iteration scheme explicit.
Enumerations
%matrix.Mat
enum Mat : flags_t
%matrix.constMat
enum constMat : flags_t
%matrix.init
enum init : flags_t
%matrix.sum
enum sum : flags_t
%matrix.lower_matrix_high_level_map_reduce
enum lower_matrix_high_level_map_reduce : flags_t
%matrix.lower_matrix_medium_level
enum lower_matrix_medium_level : flags_t
%matrix.internal_map_reduce_cleanup
enum internal_map_reduce_cleanup : flags_t
%matrix.lower_matrix_low_level
enum lower_matrix_low_level : flags_t
Functions
const Def * zero_int (World &w, Ref n, Ref S, Ref mem, nat_t m)
mat.zero: Π [n: .Nat, S: «n; .Nat», m: .Nat] -> mat.Mat (n,S,(.Idx m));
const Def * op_read (Ref mem, Ref matrix, Ref idx)
u64 get_max_index (u64 init, Defs inputs)
Matrix normalizer for product on two-dimensional matrices.
std::pair< Lam *, Ref > counting_for (Ref bound, DefVec acc, Ref exit, const char *name="for_body")
void register_normalizers (Normalizers &normalizers)
Variables
static constexpr plugin_t Plugin_Id = 0x3825532990000000
%matrix.shape
enum shape : flags_t
Ref normalize_shape (Ref type, Ref callee, Ref arg)
Normalizer for transpose operations.
%matrix.read
enum read : flags_t
Ref normalize_read (Ref type, Ref callee, Ref arg)
Normalizer for read opertions.
%matrix.insert
enum insert : flags_t
Ref normalize_insert (Ref type, Ref callee, Ref arg)
Normalizer for write operations TODO: implement.
%matrix.prod
enum prod : flags_t
Ref normalize_prod (Ref type, Ref callee, Ref arg)
%matrix.transpose
enum transpose : flags_t
Ref normalize_transpose (Ref type, Ref callee, Ref arg)
%matrix.map_reduce
enum map_reduce : flags_t
Ref normalize_map_reduce (Ref type, Ref callee, Ref arg)
map_reduce normalizers
Detailed Description
The matrix Plugin
Enumeration Type Documentation
constMat
enum thorin::plug::matrix::constMat : flags_t
Definition at line 38 of file autogen.h.
init
enum thorin::plug::matrix::init : flags_t
Definition at line 73 of file autogen.h.
insert
enum thorin::plug::matrix::insert : flags_t
Definition at line 61 of file autogen.h.
internal_map_reduce_cleanup
enum thorin::plug::matrix::internal_map_reduce_cleanup : flags_t
Definition at line 153 of file autogen.h.
lower_matrix_high_level_map_reduce
enum thorin::plug::matrix::lower_matrix_high_level_map_reduce : flags_t
Definition at line 131 of file autogen.h.
lower_matrix_low_level
enum thorin::plug::matrix::lower_matrix_low_level : flags_t
Definition at line 164 of file autogen.h.
lower_matrix_medium_level
enum thorin::plug::matrix::lower_matrix_medium_level : flags_t
Definition at line 142 of file autogen.h.
map_reduce
enum thorin::plug::matrix::map_reduce : flags_t
Definition at line 119 of file autogen.h.
Mat
enum thorin::plug::matrix::Mat : flags_t
Definition at line 15 of file autogen.h.
prod
enum thorin::plug::matrix::prod : flags_t
Definition at line 84 of file autogen.h.
read
enum thorin::plug::matrix::read : flags_t
Definition at line 49 of file autogen.h.
shape
enum thorin::plug::matrix::shape : flags_t
Definition at line 26 of file autogen.h.
sum
enum thorin::plug::matrix::sum : flags_t
Definition at line 108 of file autogen.h.
transpose
enum thorin::plug::matrix::transpose : flags_t
Definition at line 96 of file autogen.h.
Function Documentation
counting_for()
std::pair< Lam *, Ref > thorin::plug::matrix::counting_for (Ref bound, DefVec acc, Ref exit, const char * name = "for_body")
Definition at line 24 of file lower_matrix_mediumlevel.cpp.
References thorin::plug::affine::op_for(), thorin::Def::set(), thorin::World::tuple(), thorin::Def::type(), and thorin::Def::world().
Referenced by thorin::plug::matrix::LowerMatrixMediumLevel::rewrite_().
get_max_index()
u64 thorin::plug::matrix::get_max_index (u64 init, Defs inputs)
Matrix normalizer for product on two-dimensional matrices.
product (constMat v1, constMat v2) -> constMat v1 * v2 * dim (TODO: implement)
product (constMat v, m) -> ... (TODO: implement)
product (m, constMat v) -> ... (TODO: implement)
product (id, m) -> m (TODO: check)
product (m, id) -> m
map(constMat v, f) -> constMat f(v) (TODO: implement)
map f (map g m) -> map (f . g) m (TODO: implement)
map f (zipWith g m1 m2) -> zipWith (f . g) m1 m2 (TODO: implement)
Definition at line 76 of file normalizers.cpp.
References thorin::Lit::isa(), and thorin::Def::projs().
normalize_insert()
Ref thorin::plug::matrix::normalize_insert (Ref type, Ref callee, Ref arg)
Normalizer for write operations TODO: implement.
Definition at line 41 of file normalizers.cpp.
References thorin::World::raw_app(), and thorin::Def::world().
normalize_map_reduce()
Ref thorin::plug::matrix::normalize_map_reduce (Ref type, Ref callee, Ref arg)
map_reduce normalizers
TODO: map_reduce (..., ((idx,map_reduce([out, ]...), ...))) -> unify idx, out (out is implicit), name vars apart requires: same reduction, distributive reduction we assume distributivity of the reduction function
Definition at line 97 of file normalizers.cpp.
References thorin::World::raw_app(), and thorin::Def::world().
normalize_prod()
Ref thorin::plug::matrix::normalize_prod (Ref type, Ref callee, Ref arg)
Definition at line 104 of file normalizers.cpp.
References thorin::World::raw_app(), and thorin::Def::world().
normalize_read()
Ref thorin::plug::matrix::normalize_read (Ref type, Ref callee, Ref arg)
Normalizer for read opertions.
read(constMat v) -> v
read(insert m v i, i) -> v (TODO: check with map_reduce)
read(insert m v i, j) -> read(m, i) if i <> j (TODO: wanted? useful?)
read(transpose m, (i,j)) -> read(m, (j,i)) (TODO: check for map_reduce)
read(product m1 m2, (i,j)) -> ... (TODO: check with map_reduce)
read (map_reduce f) idx = loop f idx (TODO: implement => use inner loop from lowering phase)
Definition at line 19 of file normalizers.cpp.
References thorin::Def::projs(), and thorin::Def::world().
normalize_shape()
Ref thorin::plug::matrix::normalize_shape (Ref type, Ref callee, Ref arg)
Normalizer for transpose operations.
transpose (constMat v) -> cosntMat v (TODO: implement)
transpose (insert m v (i,j)) -> insert (transpose m) v (j,i) (TODO: implement, maybe other way around?)
transpose (tranpose m) -> m (TODO: implement)
shape (@mat n (k1,k2,...,kn) i) -> (k1,k2,...,kn)#i (TODO: implement)
Definition at line 57 of file normalizers.cpp.
References thorin::Def::projs(), and thorin::Def::world().
normalize_transpose()
Ref thorin::plug::matrix::normalize_transpose (Ref type, Ref callee, Ref arg)
Definition at line 109 of file normalizers.cpp.
References thorin::World::raw_app(), and thorin::Def::world().
op_read()
const Def * thorin::plug::matrix::op_read (Ref mem, Ref matrix, Ref idx) inline
Definition at line 19 of file matrix.h.
References thorin::Def::type(), and thorin::Def::world().
Referenced by thorin::plug::matrix::LowerMatrixMediumLevel::rewrite_().
register_normalizers()
void thorin::plug::matrix::register_normalizers (Normalizers & normalizers)
Referenced by thorin_get_plugin().
zero_int()
const Def * thorin::plug::matrix::zero_int (World & w, Ref n, Ref S, Ref mem, nat_t m) inline
mat.zero: Π [n: .Nat, S: «n; .Nat», m: .Nat] -> mat.Mat (n,S,(.Idx m));
Definition at line 14 of file matrix.h.
Variable Documentation
Plugin_Id
constexpr plugin_t thorin::plug::matrix::Plugin_Id = 0x3825532990000000 static constexpr
Definition at line 10 of file autogen.h.