Thorin: thorin::plug::refly Namespace Reference
thorin::plug::refly Namespace Reference
The refly Plugin
Classes
class RemoveDbgPerm
Removes all refly.debug.perm markers for code gen.
Enumerations
%refly.Code
enum Code : flags_t
%refly.error
enum error : flags_t
%refly.warn
enum warn : flags_t
%refly.info
enum info : flags_t
%refly.verbose
enum verbose : flags_t
%refly.debug
enum debug : flags_t
%refly.remove_dbg_perm_pass
enum remove_dbg_perm_pass : flags_t
Functions
void register_normalizers (Normalizers &normalizers)
Variables
static constexpr plugin_t Plugin_Id = 0x4c61cd6800000000
%refly.reify
enum reify : flags_t
Ref normalize_reify (Ref, Ref, Ref arg)
%refly.reflect
enum reflect : flags_t
Ref normalize_reflect (Ref, Ref, Ref arg)
%refly.gid
enum gid : flags_t
Ref normalize_gid (Ref, Ref, Ref arg)
%refly.dbg
enum dbg : flags_t {
tmp = 0x4c61cd6800000900 ,
perm = 0x4c61cd6800000901
}
template<dbg id>
Ref normalize_dbg (Ref type, Ref callee, Ref arg)
%refly.refine
enum refine : flags_t
Ref normalize_refine (Ref type, Ref callee, Ref arg)
Detailed Description
The refly Plugin
Enumeration Type Documentation
Code
enum thorin::plug::refly::Code : flags_t
Definition at line 15 of file autogen.h.
dbg
enum thorin::plug::refly::dbg : flags_t
Enumerator
tmp
perm
Definition at line 117 of file autogen.h.
debug
enum thorin::plug::refly::debug : flags_t
Definition at line 106 of file autogen.h.
error
enum thorin::plug::refly::error : flags_t
Definition at line 62 of file autogen.h.
gid
enum thorin::plug::refly::gid : flags_t
Definition at line 50 of file autogen.h.
info
enum thorin::plug::refly::info : flags_t
Definition at line 84 of file autogen.h.
refine
enum thorin::plug::refly::refine : flags_t
Definition at line 134 of file autogen.h.
reflect
enum thorin::plug::refly::reflect : flags_t
Definition at line 38 of file autogen.h.
reify
enum thorin::plug::refly::reify : flags_t
Definition at line 26 of file autogen.h.
remove_dbg_perm_pass
enum thorin::plug::refly::remove_dbg_perm_pass : flags_t
Definition at line 146 of file autogen.h.
verbose
enum thorin::plug::refly::verbose : flags_t
Definition at line 95 of file autogen.h.
warn
enum thorin::plug::refly::warn : flags_t
Definition at line 73 of file autogen.h.
Function Documentation
normalize_dbg()
template<dbg id> Ref thorin::plug::refly::normalize_dbg (Ref type, Ref callee, Ref arg)
Definition at line 39 of file normalizers.cpp.
References perm, thorin::Def::projs(), and thorin::Def::world().
normalize_gid()
Ref thorin::plug::refly::normalize_gid (Ref , Ref , Ref arg)
Definition at line 61 of file normalizers.cpp.
References thorin::Def::gid(), thorin::World::lit_nat(), and thorin::Def::world().
normalize_refine()
Ref thorin::plug::refly::normalize_refine (Ref type, Ref callee, Ref arg)
Definition at line 50 of file normalizers.cpp.
References thorin::Lit::isa(), thorin::Def::projs(), and thorin::Def::world().
normalize_reflect()
Ref thorin::plug::refly::normalize_reflect (Ref , Ref , Ref arg)
Definition at line 48 of file normalizers.cpp.
normalize_reify()
Ref thorin::plug::refly::normalize_reify (Ref , Ref , Ref arg)
Definition at line 46 of file normalizers.cpp.
register_normalizers()
void thorin::plug::refly::register_normalizers (Normalizers & normalizers)
Referenced by thorin_get_plugin().
Variable Documentation
Plugin_Id
constexpr plugin_t thorin::plug::refly::Plugin_Id = 0x4c61cd6800000000 static constexpr
Definition at line 10 of file autogen.h.