Thorin: thorin::ll Namespace Reference
thorin::ll Namespace Reference
Classes
struct BB
class Emitter
Functions
static bool is_const (const Def *def)
static const char * math_suffix (const Def *type)
static const char * llvm_suffix (const Def *type)
void emit (World &world, std::ostream &ostream)
int compile (World &world, std::string name)
int compile (World &world, std::string ll, std::string out)
int compile_and_run (World &world, std::string name, std::string args)
Function Documentation
compile() [1/2]
int thorin::ll::compile (World & world, std::string ll, std::string out)
Definition at line 970 of file ll.cpp.
References emit(), thorin::fmt(), and thorin::sys::system().
compile() [2/2]
int thorin::ll::compile (World & world, std::string name)
Definition at line 961 of file ll.cpp.
References compile().
Referenced by compile(), and compile_and_run().
compile_and_run()
int thorin::ll::compile_and_run (World & world, std::string name, std::string args)
Definition at line 978 of file ll.cpp.
References compile(), and thorin::sys::run().
emit()
void thorin::ll::emit (World & world, std::ostream & ostream)
Definition at line 956 of file ll.cpp.
References thorin::Phase::run().
Referenced by compile(), and thorin_get_dialect_info().
is_const()
static bool thorin::ll::is_const (const Def * def) static
Definition at line 34 of file ll.cpp.
References is_const(), thorin::RuntimeCast< B >::isa(), and thorin::Def::isa_structural().
Referenced by thorin::ll::Emitter::emit_bb(), and is_const().
llvm_suffix()
static const char * thorin::ll::llvm_suffix (const Def * type) static
Definition at line 417 of file ll.cpp.
References thorin::err(), and thorin::math::isa_f().
Referenced by thorin::ll::Emitter::emit_bb().
math_suffix()
static const char * thorin::ll::math_suffix (const Def * type) static
Definition at line 408 of file ll.cpp.
References thorin::err(), and thorin::math::isa_f().
Referenced by thorin::ll::Emitter::emit_bb().