Thorin: thorin::plug::demo Namespace Reference
thorin::plug::demo Namespace Reference
The demo Plugin
Functions
void register_normalizers (Normalizers &normalizers)
Variables
static constexpr plugin_t Plugin_Id = 0x1463900000000000
%demo.const_idx
enum const_idx : flags_t
Ref normalize_const (Ref type, Ref, Ref arg)
Detailed Description
The demo Plugin
Enumeration Type Documentation
const_idx
enum thorin::plug::demo::const_idx : flags_t
Definition at line 15 of file autogen.h.
Function Documentation
normalize_const()
Ref thorin::plug::demo::normalize_const (Ref type, Ref , Ref arg)
Definition at line 7 of file normalizers.cpp.
References thorin::World::lit(), and thorin::Def::world().
register_normalizers()
void thorin::plug::demo::register_normalizers (Normalizers & normalizers)
Referenced by thorin_get_plugin().
Variable Documentation
Plugin_Id
constexpr plugin_t thorin::plug::demo::Plugin_Id = 0x1463900000000000 static constexpr
Definition at line 10 of file autogen.h.