Thorin: thorin::affine Namespace Reference
thorin::affine Namespace Reference
Classes
struct Tag2Def_
struct Tag2Enum_
Typedefs
template<fields_t tag>
using Tag2Def = typename Tag2Def_< tag >::type
template<fields_t tag>
using Tag2Enum = typename Tag2Enum_< tag >::type
Enumerations
enum Tag : u64
Functions
template<fields_t tag>
Query< Tag2Enum< tag >, Tag2Def< tag > > isa (const Def *def)
template<fields_t tag>
Query< Tag2Enum< tag >, Tag2Def< tag > > isa (Tag2Enum< tag > flags, const Def *def)
template<fields_t t>
Query< Tag2Enum< t >, Tag2Def< t > > as (const Def *d)
template<fields_t t>
Query< Tag2Enum< t >, Tag2Def< t > > as (Tag2Enum< t > f, const Def *d)
Class Documentation
thorin::affine::Tag2Def_
struct thorin::affine::Tag2Def_
template<fields_t tag>
struct thorin::affine::Tag2Def_< tag >
Definition at line 13 of file affine.h.
Class Members
typedef App type
thorin::affine::Tag2Enum_
struct thorin::affine::Tag2Enum_
template<fields_t tag>
struct thorin::affine::Tag2Enum_< tag >
Definition at line 21 of file affine.h.
Class Members
typedef fields_t type
Typedef Documentation
Tag2Def
template<fields_t tag> using thorin::affine::Tag2Def = typedef typename Tag2Def_<tag>::type
Definition at line 18 of file affine.h.
Tag2Enum
template<fields_t tag> using thorin::affine::Tag2Enum = typedef typename Tag2Enum_<tag>::type
Definition at line 23 of file affine.h.
Enumeration Type Documentation
Tag
enum thorin::affine::Tag : u64
Definition at line 9 of file affine.h.
Function Documentation
as() [1/2]
template<fields_t t> Query< Tag2Enum< t >, Tag2Def< t > > thorin::affine::as (const Def * d)
Definition at line 41 of file affine.h.
References thorin::RuntimeCast< Base >::as(), and thorin::Axiom::get().
as() [2/2]
template<fields_t t> Query< Tag2Enum< t >, Tag2Def< t > > thorin::affine::as (Tag2Enum< t > f, const Def * d)
Definition at line 47 of file affine.h.
References thorin::RuntimeCast< Base >::as(), thorin::f, and thorin::Axiom::get().
isa() [1/2]
template<fields_t tag> Query< Tag2Enum< tag >, Tag2Def< tag > > thorin::affine::isa (const Def * def)
Definition at line 26 of file affine.h.
References thorin::RuntimeCast< Base >::as(), and thorin::Axiom::get().
isa() [2/2]
template<fields_t tag> Query< Tag2Enum< tag >, Tag2Def< tag > > thorin::affine::isa (Tag2Enum< tag > flags, const Def * def)
Definition at line 33 of file affine.h.
References thorin::RuntimeCast< Base >::as(), and thorin::Axiom::get().