MimIR: mim::plug::matrix Namespace Reference
mim::plug::matrix Namespace Reference
The matrix Plugin
Classes
class LowerMatrixHighLevelMapRed
Resolves lowering of high level operations into medium/other high-level operations.
class LowerMatrixLowLevel
In this phase, we lower all matrix operations and types to the low-level representation using pointers.
class LowerMatrixMediumLevel
In this step, we lower map_reduce operations into affine for loops making the iteration scheme explicit.
Enumerations
%matrix.Mat
enum class Mat : flags_t
%matrix.constMat
enum class constMat : flags_t
%matrix.init
enum class init : flags_t
%matrix.sum
enum class sum : flags_t
%matrix.lower_matrix_high_level_map_reduce
enum class lower_matrix_high_level_map_reduce : flags_t
%matrix.lower_matrix_medium_level
enum class lower_matrix_medium_level : flags_t
%matrix.internal_map_reduce_cleanup
enum class internal_map_reduce_cleanup : flags_t
%matrix.lower_matrix_low_level
enum class lower_matrix_low_level : flags_t
Functions
const Def * zero_int (World &w, const Def *n, const Def *S, const Def *mem, nat_t m)
mat.zero: [n: Nat, S: «n; Nat», m: Nat] -> mat.Mat (n,S,(Idx m));
const Def * op_read (const Def *mem, const Def *matrix, const Def *idx)
u64 get_max_index (u64 init, Defs inputs)
Matrix normalizer for product on two-dimensional matrices.
std::pair< Lam *, const Def * > counting_for (const Def *bound, DefVec acc, const Def *exit, const char *name="for_body")
void register_normalizers (Normalizers &normalizers)
Variables
static constexpr plugin_t Plugin_Id = 0x3825532990000000
%matrix.shape
enum class shape : flags_t
const Def * normalize_shape (const Def *type, const Def *callee, const Def *arg)
Normalizer for transpose operations.
%matrix.read
enum class read : flags_t
const Def * normalize_read (const Def *type, const Def *, const Def *arg)
Normalizer for read opertions.
%matrix.insert
enum class insert : flags_t
const Def * normalize_insert (const Def *, const Def *, const Def *)
Normalizer for write operations TODO: implement.
%matrix.prod
enum class prod : flags_t
const Def * normalize_prod (const Def *, const Def *, const Def *)
%matrix.transpose
enum class transpose : flags_t
const Def * normalize_transpose (const Def *, const Def *, const Def *)
%matrix.map_reduce
enum class map_reduce : flags_t
const Def * normalize_map_reduce (const Def *, const Def *, const Def *)
map_reduce normalizers
Detailed Description
The matrix Plugin
Enumeration Type Documentation
constMat
enum class mim::plug::matrix::constMat : flags_t strong
Definition at line 29 of file autogen.h.
init
enum class mim::plug::matrix::init : flags_t strong
Definition at line 52 of file autogen.h.
insert
enum class mim::plug::matrix::insert : flags_t strong
Definition at line 44 of file autogen.h.
internal_map_reduce_cleanup
enum class mim::plug::matrix::internal_map_reduce_cleanup : flags_t strong
Definition at line 104 of file autogen.h.
lower_matrix_high_level_map_reduce
enum class mim::plug::matrix::lower_matrix_high_level_map_reduce : flags_t strong
Definition at line 90 of file autogen.h.
lower_matrix_low_level
enum class mim::plug::matrix::lower_matrix_low_level : flags_t strong
Definition at line 111 of file autogen.h.
lower_matrix_medium_level
enum class mim::plug::matrix::lower_matrix_medium_level : flags_t strong
Definition at line 97 of file autogen.h.
map_reduce
enum class mim::plug::matrix::map_reduce : flags_t strong
Definition at line 82 of file autogen.h.
Mat
enum class mim::plug::matrix::Mat : flags_t strong
Definition at line 14 of file autogen.h.
prod
enum class mim::plug::matrix::prod : flags_t strong
Definition at line 59 of file autogen.h.
read
enum class mim::plug::matrix::read : flags_t strong
Definition at line 36 of file autogen.h.
shape
enum class mim::plug::matrix::shape : flags_t strong
Definition at line 21 of file autogen.h.
sum
enum class mim::plug::matrix::sum : flags_t strong
Definition at line 75 of file autogen.h.
transpose
enum class mim::plug::matrix::transpose : flags_t strong
Definition at line 67 of file autogen.h.
Function Documentation
counting_for()
std::pair< Lam *, const Def * > mim::plug::matrix::counting_for (const Def * bound, DefVec acc, const Def * exit, const char * name = "for_body")
Definition at line 26 of file lower_matrix_mediumlevel.cpp.
References mim::plug::affine::op_for(), mim::World::tuple(), mim::Def::type(), and mim::Def::world().
Referenced by mim::plug::matrix::LowerMatrixMediumLevel::rewrite_().
get_max_index()
u64 mim::plug::matrix::get_max_index (u64 init, Defs inputs)
Matrix normalizer for product on two-dimensional matrices.
product (constMat v1, constMat v2) -> constMat v1 * v2 * dim (TODO: implement)
product (constMat v, m) -> ... (TODO: implement)
product (m, constMat v) -> ... (TODO: implement)
product (id, m) -> m (TODO: check)
product (m, id) -> m
map(constMat v, f) -> constMat f(v) (TODO: implement)
map f (map g m) -> map (f . g) m (TODO: implement)
map f (zipWith g m1 m2) -> zipWith (f . g) m1 m2 (TODO: implement)
Definition at line 68 of file normalizers.cpp.
References mim::Lit::isa().
normalize_insert()
const Def * mim::plug::matrix::normalize_insert (const Def * , const Def * , const Def *)
Normalizer for write operations TODO: implement.
Definition at line 41 of file normalizers.cpp.
normalize_map_reduce()
const Def * mim::plug::matrix::normalize_map_reduce (const Def * , const Def * , const Def *)
map_reduce normalizers
TODO: map_reduce (..., ((idx,map_reduce([out, ]...), ...))) -> unify idx, out (out is implicit), name vars apart requires: same reduction, distributive reduction we assume distributivity of the reduction function
Definition at line 89 of file normalizers.cpp.
normalize_prod()
const Def * mim::plug::matrix::normalize_prod (const Def * , const Def * , const Def *)
Definition at line 90 of file normalizers.cpp.
normalize_read()
const Def * mim::plug::matrix::normalize_read (const Def * type, const Def * , const Def * arg)
Normalizer for read opertions.
read(constMat v) -> v
read(insert m v i, i) -> v (TODO: check with map_reduce)
read(insert m v i, j) -> read(m, i) if i <> j (TODO: wanted? useful?)
read(transpose m, (i,j)) -> read(m, (j,i)) (TODO: check for map_reduce)
read(product m1 m2, (i,j)) -> ... (TODO: check with map_reduce)
read (map_reduce f) idx = loop f idx (TODO: implement => use inner loop from lowering phase)
Definition at line 19 of file normalizers.cpp.
References mim::match(), mim::Def::projs(), and mim::Def::world().
normalize_shape()
const Def * mim::plug::matrix::normalize_shape (const Def * type, const Def * callee, const Def * arg)
Normalizer for transpose operations.
transpose (constMat v) -> cosntMat v (TODO: implement)
transpose (insert m v (i,j)) -> insert (transpose m) v (j,i) (TODO: implement, maybe other way around?)
transpose (tranpose m) -> m (TODO: implement)
shape (@mat n (k1,k2,...,kn) i) -> (k1,k2,...,kn)#i (TODO: implement)
Definition at line 49 of file normalizers.cpp.
References mim::match(), mim::Def::projs(), and mim::Def::world().
normalize_transpose()
const Def * mim::plug::matrix::normalize_transpose (const Def * , const Def * , const Def *)
Definition at line 91 of file normalizers.cpp.
op_read()
const Def * mim::plug::matrix::op_read (const Def * mem, const Def * matrix, const Def * idx) inline
Definition at line 19 of file matrix.h.
References mim::match(), mim::Def::type(), and mim::Def::world().
Referenced by mim::plug::matrix::LowerMatrixMediumLevel::rewrite_().
register_normalizers()
void mim::plug::matrix::register_normalizers (Normalizers & normalizers)
Referenced by mim_get_plugin().
zero_int()
const Def * mim::plug::matrix::zero_int (World & w, const Def * n, const Def * S, const Def * mem, nat_t m) inline
mat.zero: [n: Nat, S: «n; Nat», m: Nat] -> mat.Mat (n,S,(Idx m));
Definition at line 14 of file matrix.h.
Variable Documentation
Plugin_Id
plugin_t mim::plug::matrix::Plugin_Id = 0x3825532990000000 static constexpr
Definition at line 10 of file autogen.h.