Thorin: thorin::std Namespace Reference
thorin::std Namespace Reference
Classes
struct Tag2Def_
struct Tag2Enum_
struct Tag2Enum_< Tag::std_icmp >
Typedefs
template<fields_t tag>
using Tag2Def = typename Tag2Def_< tag >::type
template<fields_t tag>
using Tag2Enum = typename Tag2Enum_< tag >::type
Enumerations
enum Tag : u64 { std_icmp = 0x5151400000000000 }
enum class icmp : u8 {
xygle , f = xygle , xyglE , xygLe ,
xygLE , xyGle , xyGlE , xyGLe ,
xyGLE , xYgle , xYglE , xYgLe ,
sl = xYgLe , xYgLE , sle = xYgLE , xYGle ,
ug = xYGle , xYGlE , uge = xYGlE , xYGLe ,
xYGLE , Xygle , XyglE , XygLe ,
ul = XygLe , XygLE , ule = XygLE , XyGle ,
sg = XyGle , XyGlE , sge = XyGlE , XyGLe ,
XyGLE , XYgle , XYglE , XYgLe ,
XYgLE , XYGle , XYGlE , XYGLe ,
ne = XYGLe , XYGLE , t = XYGLE
}
Functions
template<fields_t tag>
Query< Tag2Enum< tag >, Tag2Def< tag > > isa (const Def *def)
template<fields_t tag>
Query< Tag2Enum< tag >, Tag2Def< tag > > isa (Tag2Enum< tag > flags, const Def *def)
template<fields_t t>
Query< Tag2Enum< t >, Tag2Def< t > > as (const Def *d)
template<fields_t t>
Query< Tag2Enum< t >, Tag2Def< t > > as (Tag2Enum< t > f, const Def *d)
Class Documentation
thorin::std::Tag2Def_
struct thorin::std::Tag2Def_
template<fields_t tag>
struct thorin::std::Tag2Def_< tag >
Definition at line 14 of file std.h.
Class Members
typedef App type
thorin::std::Tag2Enum_
struct thorin::std::Tag2Enum_
template<fields_t tag>
struct thorin::std::Tag2Enum_< tag >
Definition at line 22 of file std.h.
Class Members
typedef fields_t type
thorin::std::Tag2Enum_< Tag::std_icmp >
struct thorin::std::Tag2Enum_< Tag::std_icmp >
Definition at line 71 of file std.h.
Class Members
typedef icmp type
Typedef Documentation
Tag2Def
template<fields_t tag> using thorin::std::Tag2Def = typedef typename Tag2Def_<tag>::type
Definition at line 19 of file std.h.
Tag2Enum
template<fields_t tag> using thorin::std::Tag2Enum = typedef typename Tag2Enum_<tag>::type
Definition at line 72 of file std.h.
Enumeration Type Documentation
icmp
enum class thorin::std::icmp : u8 strong
Enumerator
xygle
f
xyglE
xygLe
xygLE
xyGle
xyGlE
xyGLe
xyGLE
xYgle
xYglE
xYgLe
sl
xYgLE
sle
xYGle
ug
xYGlE
uge
xYGLe
xYGLE
Xygle
XyglE
XygLe
ul
XygLE
ule
XyGle
sg
XyGlE
sge
XyGLe
XyGLE
XYgle
XYglE
XYgLe
XYgLE
XYGle
XYGlE
XYGLe
ne
XYGLE
t
Definition at line 24 of file std.h.
Tag
enum thorin::std::Tag : u64
Enumerator
std_icmp
Definition at line 9 of file std.h.
Function Documentation
as() [1/2]
template<fields_t t> Query< Tag2Enum< t >, Tag2Def< t > > thorin::std::as (const Def * d)
Definition at line 90 of file std.h.
References thorin::RuntimeCast< Base >::as(), and thorin::Axiom::get().
as() [2/2]
template<fields_t t> Query< Tag2Enum< t >, Tag2Def< t > > thorin::std::as (Tag2Enum< t > f, const Def * d)
Definition at line 96 of file std.h.
References thorin::RuntimeCast< Base >::as(), thorin::f, and thorin::Axiom::get().
isa() [1/2]
template<fields_t tag> Query< Tag2Enum< tag >, Tag2Def< tag > > thorin::std::isa (const Def * def)
Definition at line 75 of file std.h.
References thorin::RuntimeCast< Base >::as(), and thorin::Axiom::get().
isa() [2/2]
template<fields_t tag> Query< Tag2Enum< tag >, Tag2Def< tag > > thorin::std::isa (Tag2Enum< tag > flags, const Def * def)
Definition at line 82 of file std.h.
References thorin::RuntimeCast< Base >::as(), and thorin::Axiom::get().