Thorin: thorin::dl Namespace Reference
thorin::dl Namespace Reference
Classes
class Error
Functions
std::string_view prefix ()
"lib" or ""
std::string_view extension ()
".dll" or ".so"
template<class... Args>
void err (const char *fmt, Args &&... args)
void * open (const std::string &file)
void * get (void *handle, const std::string &symbol)
void close (void *handle)
Function Documentation
close()
void thorin::dl::close (void * handle)
Definition at line 80 of file dl.cpp.
References err().
Referenced by thorin::Dialect::load().
err()
template<class... Args> void thorin::dl::err (const char * fmt, Args &&... args)
Definition at line 32 of file dl.cpp.
References thorin::fmt(), and thorin::print().
Referenced by close(), get(), and open().
extension()
std::string_view thorin::dl::extension ()
".dll" or ".so"
Definition at line 23 of file dl.cpp.
Referenced by thorin::PipelineBuilder::extend_codegen_prep_phase(), thorin::PipelineBuilder::extend_opt_phase(), and get_plugin_name_variants().
get()
void * thorin::dl::get (void * handle, const std::string & symbol)
Definition at line 60 of file dl.cpp.
References err().
open()
void * thorin::dl::open (const std::string & file)
Definition at line 39 of file dl.cpp.
References err().
Referenced by thorin::Dialect::load().
prefix()
std::string_view thorin::dl::prefix ()
"lib" or ""
Definition at line 15 of file dl.cpp.
Referenced by get_plugin_name_variants().