Thorin: thorin::direct Namespace Reference
thorin::direct Namespace Reference
Classes
class CPS2DS
This is the second part of ds2cps.
class DS2CPS
Converts direct style function to cps functions.
Enumerations
ds2cps_pass
enum ds2cps_pass : flags_t
cps2ds_pass
enum cps2ds_pass : flags_t
cps2ds_dep
enum cps2ds_dep : flags_t
Functions
const Def * op_cps2ds_dep (const Def *f)
void register_normalizers (Normalizers &normalizers)
Variables
static constexpr plugin_t Plugin_Id = 0x14a4c61150000000
cps2ds
enum cps2ds : flags_t
Ref normalize_cps2ds (Ref, Ref, Ref fun)
cps2ds is directly converted to op_cps2ds_dep f in its normalizer.
Enumeration Type Documentation
cps2ds
enum thorin::direct::cps2ds : flags_t
Definition at line 24 of file autogen.h.
cps2ds_dep
enum thorin::direct::cps2ds_dep : flags_t
Definition at line 46 of file autogen.h.
cps2ds_pass
enum thorin::direct::cps2ds_pass : flags_t
Definition at line 36 of file autogen.h.
ds2cps_pass
enum thorin::direct::ds2cps_pass : flags_t
Definition at line 14 of file autogen.h.
Function Documentation
normalize_cps2ds()
Ref thorin::direct::normalize_cps2ds (Ref , Ref , Ref fun)
cps2ds is directly converted to op_cps2ds_dep f in its normalizer.
Definition at line 8 of file normalizers.cpp.
References op_cps2ds_dep().
op_cps2ds_dep()
const Def * thorin::direct::op_cps2ds_dep (const Def * f) inline
Definition at line 10 of file direct.h.
References thorin::RuntimeCast< B >::as(), thorin::Pi::dom(), thorin::rewrite(), thorin::Def::type(), and thorin::Def::var().
Referenced by thorin::autodiff::AutoDiffEval::augment_app(), thorin::autodiff::AutoDiffEval::augment_pack(), thorin::matrix::internal_function_of_axiom(), normalize_cps2ds(), thorin::matrix::LowerMatrixHighLevelMapRed::rewrite_(), and thorin::matrix::LowerMatrixMediumLevel::rewrite_().
register_normalizers()
void thorin::direct::register_normalizers (Normalizers & normalizers)
Referenced by thorin_get_plugin().
Variable Documentation
Plugin_Id
constexpr plugin_t thorin::direct::Plugin_Id = 0x14a4c61150000000 static constexpr
Definition at line 9 of file autogen.h.