Thorin: thorin Namespace Reference
thorin Namespace Reference
Helper functions of general interest.
Namespaces
namespace affine
namespace autodiff
Helper function related to automatic differentiation.
namespace clos
namespace core
namespace demo
namespace detail
namespace direct
namespace dl
namespace dot
namespace fe
namespace h
namespace ll
namespace mem
namespace Node
namespace normalize
namespace refly
add c++ bindings to call the axioms here preferably using inlined functions
namespace sys
namespace utf8
Classes
class Ac
Constructs a Meet value.
class App
class Arr
class Array
A container for an array, either heap-allocated or stack allocated.
class ArrayStorage
struct ArrayStorage< T, 0 >
class Axiom
class BetaRed
Optimistically performs β-reduction (aka inlining).
class BitSet
class Bound
Common base for TBound.
class CFA
Control Flow Analysis.
class CFG
A Control-Flow Graph.
class CFNode
A Control-Flow Node.
class Checker
class Cleanup
Removes unreachable and dead code by rebuilding the whole World into a new one and swapping afterwards.
class Debug
class Def
Base class for all Defs.
struct DefDefEq
struct DefDefHash
struct Dep
class DepNode
class DepTree
class Dialect
A thorin dialect.
struct DialectInfo
Basic info and registration function pointer to be returned from a dialect plugin.
class DomFrontierBase
A Dominance Frontier Graph.
class DomTreeBase
A Dominance Tree.
class Dumper
This thing operates in two modes:
struct Elem
Use with print to output complicated std::ranges::ranges.
class Emitter
class ErrorHandler
class EtaExp
Performs η-expansion: f -> λx.f x, if f is a Lam with more than one user and does not appear in callee position.
class EtaRed
Performs η-reduction.
class Ext
Common base for TExtremum.
class Extract
Extracts from a Sigma or Arr-typed Extract::tuple the element at position Extract::index.
struct Flags
struct FNV1
Magic numbers for FNV-1 hash.
class FPPass
Inherit from this class using CRTP, if you do need a Pass with a state and a fixed-point.
class FPPhase
Like a RWPhase but starts with a fixed-point loop of FPPhase::analyze beforehand.
struct GIDEq
struct GIDHash
struct GIDLt
class Global
class Idx
A built-in constant of type .Nat -> *.
class IndexMap
class IndexSet
class Infer
This node is a hole in the IR that is inferred by its context later on.
struct Inline
This is a wrapper to dump a Def "inline" and print it with all of its operands.
class Insert
Creates a new Tuple / Pack by inserting Insert::value at position Insert::index into Insert::tuple.
class Lam
class LamSpec
class Lit
struct Loc
struct Log
class LoopTree
Calculates a loop nesting forest rooted at LoopTree::root_.
class LoopTreeBuilder
struct LRPrec
class Match
class Nat
class Pack
class PartialEval
class Pass
All Passes that want to be registered in the PassMan must implement this interface.
struct passCmp
class PassMan
An optimizer that combines several optimizations in an optimal way.
class PassManPhase
Wraps a PassMan pipeline as a Phase.
class PassPhase
Wraps a Pass as a Phase.
struct PassTag
class Phase
As opposed to a Pass, a Phase does one thing at a time and does not mix with other Phases.
class PhaseRewriter
class Pi
A function type AKA Pi type.
class Pick
Picks the aspect of a Meet [value](Pick::value) by its [type](Def::type).
class Pipeline
Organizes several Phases as a pipeline.
class PipelineBuilder
struct Pos
class Proxy
class RetWrap
class Rewriter
Rewrites part of a program.
class RuntimeCast
Provides a dynamic_cast -like feature without resorting to RTTI.
class RWPass
Inherit from this class if your Pass does not need state and a fixed-point iteration.
class RWPhase
Visits the current Phase::world and constructs a new World Phase::new_world along the way.
class Scalerize
Perform Scalarization (= Argument simplification), i.e.
class Scheduler
class Scope
A Scope represents a region of Defs that are live from the view of an entry's Var.
class ScopePhase
Transitively visits all reachable Scopes in World that do not have free variables.
class ScopeRewriter
class Sigma
class Singleton
A singleton wraps a type into a higher order type.
class Span
A container-like wrapper for an array.
class Sym
struct SymHash
class Tab
Keeps track of indentation level.
class TailRecElim
class TBound
Specific Bound depending on up.
class Test
test value, probe, match, clash tests whether value currently holds type [probe](Test::probe).
class TExt
Extremum. Either Top (up) or Bottom.
class Tuple
Data constructor for a Sigma.
class Type
class unique_queue
class unique_stack
class Univ
class Use
References a user.
struct UseEq
struct UseHash
class Var
class Vel
Constructs a Join value.
struct w2r_
struct w2s_
struct w2s_< 1 >
struct w2s_< 16 >
struct w2s_< 32 >
struct w2s_< 64 >
struct w2s_< 8 >
struct w2u_
struct w2u_< 1 >
struct w2u_< 16 >
struct w2u_< 32 >
struct w2u_< 64 >
struct w2u_< 8 >
class World
The World represents the whole program and manages creation of Thorin nodes (Defs).
Concepts
concept axiom_with_subs
concept axiom_without_subs
Typedefs
using CFNodes = GIDSet< const CFNode * >
using DomFrontiers = DomFrontierBase< true >
using ControlDeps = DomFrontierBase< false >
using DomTree = DomTreeBase< true >
using PostDomTree = DomTreeBase< false >
using Schedule = std::vector< Def * >
using F_CFG = CFG< true >
using B_CFG = CFG< false >
template<class Val >
using SymMap = absl::flat_hash_map< Sym, Val, SymHash >
using SymSet = absl::flat_hash_set< Sym, SymHash >
using Defs = Span< const Def * >
using DefArray = Array< const Def * >
using Uses = absl::flat_hash_set< Use, UseHash, UseEq >
template<class To >
using DefMap = GIDMap< const Def *, To >
using DefSet = GIDSet< const Def * >
using Def2Def = DefMap< const Def * >
using DefDef = std::tuple< const Def *, const Def * >
using DefVec = std::vector< const Def * >
template<class To >
using DefDefMap = absl::flat_hash_map< DefDef, To, DefDefHash, DefDefEq >
using DefDefSet = absl::flat_hash_set< DefDef, DefDefHash, DefDefEq >
template<class To >
using NomMap = GIDMap< Def *, To >
using NomSet = GIDSet< Def * >
using Nom2Nom = NomMap< Def * >
template<class To >
using VarMap = GIDMap< const Var *, To >
using VarSet = GIDSet< const Var * >
using Var2Var = VarMap< const Var * >
using level_t = u64
using Backends = std::map< std::string, std::function< void(World &, std::ostream &)> >
using Normalizers = absl::flat_hash_map< flags_t, Def::NormalizeFn >
using LPrec = LRPrec< true >
using RPrec = LRPrec< false >
template<class To >
using LamMap = GIDMap< Lam *, To >
using LamSet = GIDSet< Lam * >
using Lam2Lam = LamMap< Lam * >
using Bot = TExt< false >
using Top = TExt< true >
using Meet = TBound< false >
using Join = TBound< true >
using undo_t = size_t
typedef std::function< void(PassMan &)> PassBuilder
typedef std::pair< int, PassBuilder > PrioPassBuilder
typedef std::vector< PrioPassBuilder > PassList
using hash_t = uint32_t
using s8 = int8_t
using u8 = uint8_t
using s16 = int16_t
using u16 = uint16_t
using s32 = int32_t
using u32 = uint32_t
using s64 = int64_t
using u64 = uint64_t
using u1 = bool
using r16 = half
using r32 = float
using r64 = double
template<int w>
using w2u = typename w2u_< w >::type
template<int w>
using w2s = typename w2s_< w >::type
template<int w>
using w2r = typename w2r_< w >::type
using nat_t = u64
using node_t = u8
using flags_t = u64
using dialect_t = u64
using tag_t = u8
using sub_t = u8
maps/sets based upon gid
template<class K , class V >
using GIDMap = absl::flat_hash_map< K, V, GIDHash< K >, GIDEq< K > >
template<class K >
using GIDSet = absl::flat_hash_set< K, GIDHash< K >, GIDEq< K > >
template<class K , class V >
using GIDNodeMap = absl::node_hash_map< K, V, GIDHash< K >, GIDEq< K > >
template<class K >
using GIDNodeSet = absl::node_hash_set< K, GIDHash< K >, GIDEq< K > >
Enumerations
enum { InSCC = 1 , OnStack = 2 , IsHead = 4 }
enum class Sort {
Term , Type , Kind , Space ,
Univ
}
Functions
std::ostream & operator<< (std::ostream &os, const CFNode *n)
static void merge (VarSet &vars, VarSet &&other)
template<bool forward>
std::ostream & operator<< (std::ostream &os, const typename LoopTree< forward >::Base *n)
template std::ostream & operator<<< true > (std::ostream &, const typename LoopTree< true >::Base *)
template std::ostream & operator<<< false > (std::ostream &, const typename LoopTree< false >::Base *)
Schedule schedule (const Scope &scope)
bool is_free (Def *nom, const Def *def)
Does nom's Var occurr free in def?
template<class This , class T >
T & lazy_init (const This *self, std::unique_ptr< T > &ptr)
static std::string_view sub_view (std::string_view s, size_t i, size_t n=std::string_view::npos)
constexpr uint64_t bitwidth2size (uint64_t n)
constexpr std::optional< uint64_t > size2bitwidth (uint64_t n)
template<class Id , bool DynCast = true>
auto match (const Def *def)
template<class Id , bool DynCast = true>
auto match (Id id, const Def *def)
template<class Id >
auto force (const Def *def)
template<class Id >
auto force (Id id, const Def *def)
const Def * infer_type_level (World &world, Defs defs)
std::ostream & operator<< (std::ostream &os, const Pos pos)
std::ostream & operator<< (std::ostream &os, const Loc loc)
std::ostream & operator<< (std::ostream &os, const Sym sym)
bool operator== (Sym s1, Sym s2)
bool operator== (Pos p1, Pos p2)
bool operator== (Loc l1, Loc l2)
template<class T = u64>
std::optional< T > isa_lit (const Def *)
template<class T = u64>
T as_lit (const Def *def)
template<class T >
const T * isa (flags_t f, const Def *def)
template<class T >
const T * as (flags_t f, const Def *def)
std::vector< std::filesystem::path > get_plugin_search_paths (Span< std::string > user_paths)
THORIN_EXPORT thorin::DialectInfo thorin_get_dialect_info ()
To be implemented and exported by the dialect plugins.
static Def * isa_decl (const Def *def)
static std::string id (const Def *def)
static std::string_view external (const Def *def)
std::ostream & operator<< (std::ostream &os, Inline u)
std::ostream & operator<< (std::ostream &os, const Def *def)
This will stream def as an operand.
template<class T = std::logic_error, class... Args>
void err (const char *fmt, Args &&... args)
template<class T = std::logic_error, class... Args>
void err (Loc loc, const char *fmt, Args &&... args)
Lam * get_var_lam (const Def *def)
Lam * isa_workable (Lam *lam)
These are Lams that are neither nullptr, nor Lam::is_external, nor Lam::is_unset.
const App * isa_callee (const Def *def, size_t i)
std::pair< const App *, Lam * > isa_apped_nom_lam (const Def *def)
const Ext * isa_ext (const Def *def)
const Bound * isa_bound (const Def *def)
template<Bit op>
const Def * normalize_Bit (const Def *type, const Def *c, const Def *arg, const Def *dbg)
template<Shr op>
const Def * normalize_Shr (const Def *type, const Def *c, const Def *arg, const Def *dbg)
template<Wrap op>
const Def * normalize_Wrap (const Def *type, const Def *c, const Def *arg, const Def *dbg)
template<ROp op>
const Def * normalize_ROp (const Def *type, const Def *c, const Def *arg, const Def *dbg)
template<ICmp op>
const Def * normalize_ICmp (const Def *type, const Def *c, const Def *arg, const Def *dbg)
template<RCmp op>
const Def * normalize_RCmp (const Def *type, const Def *c, const Def *arg, const Def *dbg)
u64 pad (u64 offset, u64 align)
template<Trait op>
const Def * normalize_Trait (const Def *, const Def *callee, const Def *type, const Def *dbg)
template<nat_t min_sw, nat_t min_dw, Conv op>
static const Def * fold_Conv (const Def *dst_type, const App *callee, const Def *src, const Def *dbg)
template<Conv op>
const Def * normalize_Conv (const Def *dst_type, const Def *c, const Def *src, const Def *dbg)
template<PE op>
const Def * normalize_PE (const Def *type, const Def *callee, const Def *arg, const Def *dbg)
template<Acc op>
const Def * normalize_Acc (const Def *type, const Def *callee, const Def *arg, const Def *dbg)
const Def * normalize_bitcast (const Def *dst_type, const Def *callee, const Def *src, const Def *dbg)
const Def * normalize_zip (const Def *type, const Def *c, const Def *arg, const Def *dbg)
static bool is_var (const Def *def)
static const App * eta_rule (Lam *lam)
For now, only η-reduce lam x.e x if e is a Var or a Lam.
void optimize (World &world, PipelineBuilder &builder)
The optimizations proceed in a pipeline ordered by priorities.
static bool is_top_level (LamMap< bool > &top, Lam *lam)
static bool is_top_level (Lam *lam)
const Def * rewrite (const Def *def, const Def *old_def, const Def *new_def, const Scope &scope)
Rewrites def by mapping old_def to new_def while obeying scope.
const Def * rewrite (Def *nom, const Def *arg, size_t i, const Scope &scope)
Same as above but uses scope as an optimization instead of computing a new Scope.
const Def * rewrite (Def *nom, const Def *arg, size_t i)
Rewrites nom's i^th op by substituting nom's Var with arg while obeying nom's scope.
DefArray rewrite (Def *nom, const Def *arg, const Scope &scope)
Same as above but uses scope as an optimization instead of computing a new Scope.
DefArray rewrite (Def *nom, const Def *arg)
Rewrites nom's ops by substituting nom's Var with arg while obeying nom's scope.
static bool should_flatten (const Def *def)
static bool nom_val_or_typ (const Def *def)
size_t flatten (DefVec &ops, const Def *def, bool flatten_noms)
const Def * flatten (const Def *def)
Flattens a sigma/array/pack/tuple.
static const Def * unflatten (Defs defs, const Def *type, size_t &j, bool flatten_noms)
const Def * unflatten (Defs ops, const Def *type, bool flatten_noms=true)
Same as unflatten, but uses the operands of a flattened pack/tuple directly.
const Def * unflatten (const Def *def, const Def *type)
Applies the reverse transformation on a pack/tuple, given the original type.
bool is_unit (const Def *def)
DefArray merge (const Def *def, Defs defs)
DefArray merge (Defs a, Defs b)
const Def * merge_sigma (const Def *def, Defs defs)
const Def * merge_tuple (const Def *def, Defs defs)
std::string tuple2str (const Def *def)
bool is_sigma_or_arr (const Def *def)
bool is_tuple_or_pack (const Def *def)
template<class T , class U >
auto concat (const T &a, const U &b) -> Array< typename T::value_type >
template<class T >
auto concat (const T &val, Span< T > a) -> Array< T >
template<class T >
auto concat (Span< T > a, const T &val) -> Array< T >
template<class T >
Array< typename T::value_type > make_array (const T &container)
void unreachable ()
void breakpoint ()
static uint64_t begin_mask (uint64_t i)
static uint64_t end_mask (uint64_t i)
template<class D , class S >
D bitcast (const S &src)
A bitcast.
template<class S >
auto pop (S &s) -> decltype(s.top(), typename S::value_type())
template<class Q >
auto pop (Q &q) -> decltype(q.front(), typename Q::value_type())
template<class I , class T , class Cmp >
I binary_find (I begin, I end, T val, Cmp cmp)
template<class Indexer , class Key , class Value >
Value * find (IndexMap< Indexer, Key, Value * > &map, Key key)
template<class Indexer , class Key , class Value >
const Value * find (const IndexMap< Indexer, Key, Value * > &map, Key key)
template<class Indexer , class Key >
bool visit (IndexSet< Indexer, Key > &set, const Key &key)
template<class Indexer , class Key >
void visit_first (IndexSet< Indexer, Key > &set, const Key &key)
std::ostream & print (std::ostream &os, const char *s)
Base case.
template<class T , class... Args>
std::ostream & print (std::ostream &os, const char *s, T &&t, Args &&... args)
Provides a printf-like interface to format s with args and puts it into os.
template<class... Args>
std::string fmt (const char *s, Args &&... args)
Wraps print to output a formatted std:string.
template<class... Args>
std::ostream & outf (const char *fmt, Args &&... args)
template<class... Args>
std::ostream & errf (const char *fmt, Args &&... args)
template<class... Args>
std::ostream & outln (const char *fmt, Args &&... args)
template<class... Args>
std::ostream & errln (const char *fmt, Args &&... args)
template<class T >
bool get_sign (T val)
constexpr s8 operator""_s8 (unsigned long long int s)
constexpr u8 operator""_u8 (unsigned long long int u)
constexpr s16 operator""_s16 (unsigned long long int s)
constexpr u16 operator""_u16 (unsigned long long int u)
constexpr s32 operator""_s32 (unsigned long long int s)
constexpr u32 operator""_u32 (unsigned long long int u)
constexpr s64 operator""_s64 (unsigned long long int s)
constexpr u64 operator""_u64 (unsigned long long int u)
half rem (half a, half b)
float rem (float a, float b)
double rem (double a, double b)
long double rem (long double a, long double b)
constexpr size_t operator""_s (unsigned long long int i)
A size_t literal. Use 0_s to disambiguate 0 from nullptr.
r16 operator""_r16 (long double d)
constexpr r32 operator""_r32 (long double d)
constexpr r64 operator""_r64 (long double d)
static const Def * infer_sigma (World &world, Defs ops)
bool is_shape (const Def *s)
bool is_continuation_type (const Def *E)
bool is_continuation (const Def *e)
bool is_returning_continuation (const Def *e)
bool is_open_continuation (const Def *e)
bool is_direct_style_function (const Def *e)
const Def * continuation_dom (const Def *E)
A wrapper to access parts of a cps function type.
const Def * continuation_codom (const Def *E)
const Def * compose_continuation (const Def *f, const Def *g)
The high level view is:
string hashing
hash_t hash (const char *s)
hash_t hash (std::string_view s)
murmur3 hash
See Wikipedia.
hash_t murmur_32_scramble (hash_t k)
hash_t murmur3 (hash_t h, uint32_t key)
hash_t murmur3 (hash_t h, uint64_t key)
hash_t murmur3_rest (hash_t h, uint8_t key)
hash_t murmur3_rest (hash_t h, uint16_t key)
hash_t murmur3_finalize (hash_t h, hash_t len)
hash_t murmur3 (hash_t h)
Use for a single value to hash.
FNV-1 hash
See Wikipedia.
template<class T >
hash_t hash_combine (hash_t seed, T v)
Returns a new hash by combining the hash seed with val.
template<class T >
hash_t hash_combine (hash_t seed, T *val)
template<class T , class... Args>
hash_t hash_combine (hash_t seed, T val, Args &&... args)
template<class T >
hash_t hash_begin (T val)
hash_t hash_begin ()
Variables
static constexpr int Search_In_Uses_Threshold = 8
static constexpr int Pass_Internal_Priority = 50
static constexpr int Pass_Default_Priority = 100
static constexpr int Opt_Phase = 100
static constexpr int Codegen_Prep_Phase = 300
static constexpr undo_t No_Undo = std::numeric_limits<undo_t>::max()
Detailed Description
Helper functions of general interest.
Class Documentation
thorin::Flags
struct thorin::Flags
Definition at line 6 of file flags.h.
Class Members
int dump_gid
bool dump_recursive
bool reeval_breakpoints
bool trace_gids
thorin::PassTag
struct thorin::PassTag
Definition at line 14 of file pass.h.
thorin::w2r_
struct thorin::w2r_
template<int>
struct thorin::w2r_< int >
Definition at line 42 of file types.h.
thorin::w2s_
struct thorin::w2s_
template<int>
struct thorin::w2s_< int >
Definition at line 41 of file types.h.
thorin::w2s_< 1 >
struct thorin::w2s_< 1 >
Definition at line 57 of file types.h.
Class Members
typedef bool type
thorin::w2s_< 16 >
struct thorin::w2s_< 16 >
Definition at line 51 of file types.h.
Class Members
typedef s16 type
typedef s16 type
thorin::w2s_< 32 >
struct thorin::w2s_< 32 >
Definition at line 51 of file types.h.
Class Members
typedef s32 type
typedef s32 type
thorin::w2s_< 64 >
struct thorin::w2s_< 64 >
Definition at line 51 of file types.h.
Class Members
typedef s64 type
typedef s64 type
thorin::w2s_< 8 >
struct thorin::w2s_< 8 >
Definition at line 51 of file types.h.
Class Members
typedef s8 type
thorin::w2u_
struct thorin::w2u_
template<int>
struct thorin::w2u_< int >
Definition at line 40 of file types.h.
thorin::w2u_< 1 >
struct thorin::w2u_< 1 >
Definition at line 56 of file types.h.
Class Members
typedef bool type
thorin::w2u_< 16 >
struct thorin::w2u_< 16 >
Definition at line 51 of file types.h.
Class Members
typedef u16 type
typedef u16 type
thorin::w2u_< 32 >
struct thorin::w2u_< 32 >
Definition at line 51 of file types.h.
Class Members
typedef u32 type
typedef u32 type
thorin::w2u_< 64 >
struct thorin::w2u_< 64 >
Definition at line 51 of file types.h.
Class Members
typedef u64 type
typedef u64 type
thorin::w2u_< 8 >
struct thorin::w2u_< 8 >
Definition at line 51 of file types.h.
Class Members
typedef u8 type
Typedef Documentation
B_CFG
using thorin::B_CFG = typedef CFG<false>
Definition at line 18 of file scope.h.
Backends
using thorin::Backends = typedef std::map<std::string, std::function<void(World&, std::ostream&)> >
Definition at line 16 of file dialects.h.
Bot
using thorin::Bot = typedef TExt<false>
Definition at line 167 of file lattice.h.
CFNodes
using thorin::CFNodes = typedef GIDSet<const CFNode*>
Definition at line 20 of file cfg.h.
ControlDeps
using thorin::ControlDeps = typedef DomFrontierBase<false>
Definition at line 42 of file domfrontier.h.
Def2Def
using thorin::Def2Def = typedef DefMap<const Def*>
Definition at line 443 of file def.h.
DefArray
using thorin::DefArray = typedef Array<const Def*>
Definition at line 47 of file def.h.
DefDef
using thorin::DefDef = typedef std::tuple<const Def*, const Def*>
Definition at line 444 of file def.h.
DefDefMap
template<class To > using thorin::DefDefMap = typedef absl::flat_hash_map<DefDef, To, DefDefHash, DefDefEq>
Definition at line 461 of file def.h.
DefDefSet
using thorin::DefDefSet = typedef absl::flat_hash_set<DefDef, DefDefHash, DefDefEq>
Definition at line 462 of file def.h.
DefMap
template<class To > using thorin::DefMap = typedef GIDMap<const Def*, To>
Definition at line 441 of file def.h.
Defs
using thorin::Defs = typedef Span<const Def*>
Definition at line 46 of file def.h.
DefSet
using thorin::DefSet = typedef GIDSet<const Def*>
Definition at line 442 of file def.h.
DefVec
using thorin::DefVec = typedef std::vector<const Def*>
Definition at line 445 of file def.h.
dialect_t
using thorin::dialect_t = typedef u64
Definition at line 86 of file types.h.
DomFrontiers
using thorin::DomFrontiers = typedef DomFrontierBase<true>
Definition at line 41 of file domfrontier.h.
DomTree
typedef DomTreeBase< true > thorin::DomTree
Definition at line 45 of file domtree.h.
F_CFG
using thorin::F_CFG = typedef CFG<true>
Definition at line 17 of file scope.h.
flags_t
using thorin::flags_t = typedef u64
Definition at line 85 of file types.h.
GIDMap
template<class K , class V > using thorin::GIDMap = typedef absl::flat_hash_map<K, V, GIDHash<K>, GIDEq<K> >
Definition at line 110 of file container.h.
GIDNodeMap
template<class K , class V > using thorin::GIDNodeMap = typedef absl::node_hash_map<K, V, GIDHash<K>, GIDEq<K> >
Definition at line 112 of file container.h.
GIDNodeSet
template<class K > using thorin::GIDNodeSet = typedef absl::node_hash_set<K, GIDHash<K>, GIDEq<K> >
Definition at line 113 of file container.h.
GIDSet
template<class K > using thorin::GIDSet = typedef absl::flat_hash_set<K, GIDHash<K>, GIDEq<K> >
Definition at line 111 of file container.h.
hash_t
using thorin::hash_t = typedef uint32_t
Definition at line 7 of file hash.h.
Join
using thorin::Join = typedef TBound<true>
Definition at line 170 of file lattice.h.
Lam2Lam
using thorin::Lam2Lam = typedef LamMap<Lam*>
Definition at line 138 of file lam.h.
LamMap
template<class To > using thorin::LamMap = typedef GIDMap<Lam*, To>
Definition at line 136 of file lam.h.
LamSet
using thorin::LamSet = typedef GIDSet<Lam*>
Definition at line 137 of file lam.h.
level_t
using thorin::level_t = typedef u64
Definition at line 510 of file def.h.
LPrec
using thorin::LPrec = typedef LRPrec<true>
Definition at line 104 of file dump.cpp.
Meet
using thorin::Meet = typedef TBound<false>
Definition at line 169 of file lattice.h.
nat_t
using thorin::nat_t = typedef u64
Definition at line 83 of file types.h.
node_t
using thorin::node_t = typedef u8
Definition at line 84 of file types.h.
Nom2Nom
using thorin::Nom2Nom = typedef NomMap<Def*>
Definition at line 467 of file def.h.
NomMap
template<class To > using thorin::NomMap = typedef GIDMap<Def*, To>
Definition at line 465 of file def.h.
NomSet
using thorin::NomSet = typedef GIDSet<Def*>
Definition at line 466 of file def.h.
Normalizers
using thorin::Normalizers = typedef absl::flat_hash_map<flags_t, Def::NormalizeFn>
Definition at line 17 of file dialects.h.
PassBuilder
typedef std::function<void(PassMan&)> thorin::PassBuilder
Definition at line 11 of file pipelinebuilder.h.
PassList
typedef std::vector<PrioPassBuilder> thorin::PassList
Definition at line 13 of file pipelinebuilder.h.
PostDomTree
using thorin::PostDomTree = typedef DomTreeBase<false>
Definition at line 46 of file domtree.h.
PrioPassBuilder
typedef std::pair<int, PassBuilder> thorin::PrioPassBuilder
Definition at line 12 of file pipelinebuilder.h.
r16
using thorin::r16 = typedef half
Definition at line 59 of file types.h.
r32
using thorin::r32 = typedef float
Definition at line 60 of file types.h.
r64
using thorin::r64 = typedef double
Definition at line 61 of file types.h.
RPrec
using thorin::RPrec = typedef LRPrec<false>
Definition at line 105 of file dump.cpp.
s16
typedef int16_t thorin::s16
Definition at line 51 of file types.h.
s32
typedef int32_t thorin::s32
Definition at line 51 of file types.h.
s64
typedef int64_t thorin::s64
Definition at line 51 of file types.h.
s8
using thorin::s8 = typedef int8_t
Definition at line 51 of file types.h.
Schedule
using thorin::Schedule = typedef std::vector<Def*>
Definition at line 57 of file schedule.h.
sub_t
using thorin::sub_t = typedef u8
Definition at line 88 of file types.h.
SymMap
template<class Val > using thorin::SymMap = typedef absl::flat_hash_map<Sym, Val, SymHash>
Definition at line 114 of file debug.h.
SymSet
using thorin::SymSet = typedef absl::flat_hash_set<Sym, SymHash>
Definition at line 115 of file debug.h.
tag_t
using thorin::tag_t = typedef u8
Definition at line 87 of file types.h.
Top
using thorin::Top = typedef TExt<true>
Definition at line 168 of file lattice.h.
u1
using thorin::u1 = typedef bool
Definition at line 53 of file types.h.
u16
typedef uint16_t thorin::u16
Definition at line 51 of file types.h.
u32
typedef uint32_t thorin::u32
Definition at line 51 of file types.h.
u64
typedef uint64_t thorin::u64
Definition at line 51 of file types.h.
u8
using thorin::u8 = typedef uint8_t
Definition at line 51 of file types.h.
undo_t
using thorin::undo_t = typedef size_t
Definition at line 11 of file pass.h.
Uses
using thorin::Uses = typedef absl::flat_hash_set<Use, UseHash, UseEq>
Definition at line 88 of file def.h.
Var2Var
using thorin::Var2Var = typedef VarMap<const Var*>
Definition at line 493 of file def.h.
VarMap
template<class To > using thorin::VarMap = typedef GIDMap<const Var*, To>
Definition at line 491 of file def.h.
VarSet
using thorin::VarSet = typedef GIDSet<const Var*>
Definition at line 492 of file def.h.
w2r
template<int w> using thorin::w2r = typedef typename w2r_<w>::type
Definition at line 74 of file types.h.
w2s
template<int w> using thorin::w2s = typedef typename w2s_<w>::type
Definition at line 73 of file types.h.
w2u
template<int w> using thorin::w2u = typedef typename w2u_<w>::type
Definition at line 72 of file types.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
InSCC
OnStack
IsHead
Definition at line 23 of file looptree.cpp.
Sort
enum class thorin::Sort strong
Enumerator
Term
Type
Kind
Space
Univ
Definition at line 91 of file def.h.
Function Documentation
as()
template<class T > const T * thorin::as (flags_t f, const Def * def)
Definition at line 433 of file def.h.
as_lit()
template<class T = u64> T thorin::as_lit (const Def * def)
Definition at line 558 of file def.h.
References thorin::RuntimeCast< Base >::as().
Referenced by thorin::ll::Emitter::emit_bb(), thorin::World::extract(), thorin::core::fold(), thorin::core::fold_conv(), fold_Conv(), infer_type_level(), thorin::World::insert(), thorin::autodiff::normalize_add(), thorin::Def::proj(), thorin::Def::sort(), tuple2str(), unflatten(), and thorin::Def::unfold_type().
begin_mask()
static uint64_t thorin::begin_mask (uint64_t i) inline static
Definition at line 20 of file bitset.cpp.
Referenced by thorin::BitSet::any_range().
binary_find()
template<class I , class T , class Cmp > I thorin::binary_find (I begin, I end, T val, Cmp cmp)
Definition at line 30 of file container.h.
Referenced by thorin::Bound::find().
bitcast()
template<class D , class S > D thorin::bitcast (const S & src) inline
A bitcast.
Definition at line 10 of file cast.h.
Referenced by thorin::ll::Emitter::emit_bb().
bitwidth2size()
constexpr uint64_t thorin::bitwidth2size (uint64_t n) constexpr
Definition at line 146 of file axiom.h.
Referenced by thorin::World::type_int().
breakpoint()
void thorin::breakpoint () inline
Definition at line 25 of file assert.h.
compose_continuation()
const Def * thorin::compose_continuation (const Def * f, const Def * g)
The high level view is:
Computes the composition λ x.
f: B -> C
g: A -> B
f o g := λ x. f(g(x)) : A -> C
In cps the types look like:
f: cn[B, cn C]
g: cn[A, cn B]
h = f o g
h : cn[A, cn C]
h = λ a ret_h. g(a,h')
h' : cn B
h' = λ b. f(b,ret_h)
f(g(x)). The given functions f and g are expected to be in cps.
Definition at line 212 of file autodiff_aux.cpp.
References continuation_codom(), continuation_dom(), is_continuation(), and is_returning_continuation().
Referenced by thorin::autodiff::AutoDiffEval::augment_app().
concat() [1/3]
template<class T , class U > auto thorin::concat (const T & a, const U & b) -> Array<typename T::value_type>
Definition at line 386 of file array.h.
References thorin::Array< T >::begin().
concat() [2/3]
template<class T > auto thorin::concat (const T & val, Span< T > a) -> Array<T>
Definition at line 393 of file array.h.
References thorin::Array< T >::begin(), and thorin::Array< T >::front().
concat() [3/3]
template<class T > auto thorin::concat (Span< T > a, const T & val) -> Array<T>
Definition at line 401 of file array.h.
References thorin::Array< T >::back(), and thorin::Array< T >::begin().
continuation_codom()
const Def * thorin::continuation_codom (const Def * E)
Definition at line 190 of file autodiff_aux.cpp.
References thorin::RuntimeCast< Base >::as().
Referenced by compose_continuation().
continuation_dom()
const Def * thorin::continuation_dom (const Def * E)
A wrapper to access parts of a cps function type.
Definition at line 183 of file autodiff_aux.cpp.
References thorin::RuntimeCast< Base >::as().
Referenced by compose_continuation().
end_mask()
static uint64_t thorin::end_mask (uint64_t i) inline static
Definition at line 21 of file bitset.cpp.
Referenced by thorin::BitSet::any_range().
err() [1/2]
template<class T = std::logic_error, class... Args> void thorin::err (const char * fmt, Args &&... args)
Definition at line 16 of file error.h.
References fmt(), and print().
Referenced by thorin::World::ax(), thorin::fe::Scopes::bind(), thorin::ErrorHandler::err(), thorin::fe::Scopes::find(), infer_type_level(), and thorin::fe::Lexer::lex().
err() [2/2]
template<class T = std::logic_error, class... Args> void thorin::err (Loc loc, const char * fmt, Args &&... args)
Definition at line 23 of file error.h.
References fmt(), and print().
errf()
template<class... Args> std::ostream & thorin::errf (const char * fmt, Args &&... args)
Definition at line 140 of file print.h.
References fmt(), and print().
Referenced by errln().
errln()
template<class... Args> std::ostream & thorin::errln (const char * fmt, Args &&... args)
Definition at line 142 of file print.h.
References errf(), and fmt().
eta_rule()
static const App * thorin::eta_rule (Lam * lam) static
For now, only η-reduce lam x.e x if e is a Var or a Lam.
Definition at line 12 of file eta_red.cpp.
References thorin::Lam::body(), is_var(), thorin::RuntimeCast< Base >::isa(), and thorin::Def::var().
external()
static std::string_view thorin::external (const Def * def) static
Definition at line 38 of file dump.cpp.
References thorin::Def::is_external().
Referenced by thorin::Dumper::dump().
find() [1/2]
template<class Indexer , class Key , class Value > const Value * thorin::find (const IndexMap< Indexer, Key, Value * > & map, Key key) inline
Definition at line 74 of file indexmap.h.
References find().
find() [2/2]
template<class Indexer , class Key , class Value > Value * thorin::find (IndexMap< Indexer, Key, Value * > & map, Key key) inline
Definition at line 68 of file indexmap.h.
References thorin::IndexMap< Indexer, Key, Value >::array(), and thorin::IndexMap< Indexer, Key, Value >::indexer().
Referenced by thorin::Bound::find(), find(), and thorin::LoopTree< forward >::operator[]().
flatten() [1/2]
const Def * thorin::flatten (const Def * def)
Flattens a sigma/array/pack/tuple.
Definition at line 29 of file tuple.cpp.
References thorin::Def::dbg(), flatten(), should_flatten(), thorin::World::sigma(), thorin::Def::sort(), Term, thorin::World::tuple(), thorin::Def::type(), and thorin::Def::world().
flatten() [2/2]
size_t thorin::flatten (DefVec & ops, const Def * def, bool flatten_noms)
Definition at line 17 of file tuple.cpp.
References thorin::Def::arity(), flatten(), nom_val_or_typ(), thorin::Def::proj(), and should_flatten().
Referenced by flatten(), and thorin::Scalerize::rewrite().
fmt()
template<class... Args> std::string thorin::fmt (const char * s, Args &&... args)
Wraps print to output a formatted std:string.
Definition at line 132 of file print.h.
References print().
Referenced by thorin::ll::compile(), err(), thorin::dl::err(), thorin::ErrorHandler::err(), errf(), errln(), get_plugin_name_variants(), thorin::Log::log(), outf(), and outln().
fold_Conv()
template<nat_t min_sw, nat_t min_dw, Conv op> static const Def * thorin::fold_Conv (const Def * dst_type, const App * callee, const Def * src, const Def * dbg) static
Definition at line 704 of file normalize.cpp.
References as_lit(), thorin::World::bot(), CODE, thorin::RuntimeCast< Base >::isa(), thorin::clos::op(), TABLE, thorin::Def::type(), and thorin::Def::world().
force() [1/2]
template<class Id > auto thorin::force (const Def * def)
Definition at line 180 of file axiom.h.
force() [2/2]
template<class Id > auto thorin::force (Id id, const Def * def)
Definition at line 181 of file axiom.h.
get_plugin_search_paths()
std::vector< std::filesystem::path > thorin::get_plugin_search_paths (Span< std::string > user_paths)
Definition at line 39 of file dialects.cpp.
References add_paths_from_env(), thorin::Span< T >::begin(), thorin::Span< T >::end(), and thorin::sys::path_to_curr_exe().
Referenced by thorin::fe::Parser::import_module(), and thorin::Dialect::load().
get_sign()
template<class T > bool thorin::get_sign (T val)
Definition at line 32 of file types.h.
Referenced by thorin::core::Fold< wrap, wrap::shl, w >::run(), and thorin::normalize::Fold< Wrap, Wrap::shl, w >::run().
get_var_lam()
Lam * thorin::get_var_lam (const Def * def)
Definition at line 67 of file lam.cpp.
References thorin::RuntimeCast< Base >::as(), and thorin::RuntimeCast< Base >::isa().
hash() [1/2]
hash_t thorin::hash (const char * s)
Definition at line 5 of file hash.cpp.
References hash_begin(), and hash_combine().
Referenced by thorin::DefDefHash::operator()().
hash() [2/2]
hash_t thorin::hash (std::string_view s)
Definition at line 11 of file hash.cpp.
References hash_begin(), and hash_combine().
hash_begin() [1/2]
hash_t thorin::hash_begin () inline
Definition at line 108 of file hash.h.
References thorin::FNV1::offset.
hash_begin() [2/2]
template<class T > hash_t thorin::hash_begin (T val)
Definition at line 105 of file hash.h.
References hash_combine(), and thorin::FNV1::offset.
Referenced by hash(), and thorin::UseHash::operator()().
hash_combine() [1/3]
template<class T > hash_t thorin::hash_combine (hash_t seed, T * val)
Definition at line 95 of file hash.h.
References hash_combine().
hash_combine() [2/3]
template<class T > hash_t thorin::hash_combine (hash_t seed, T v)
Returns a new hash by combining the hash seed with val.
Definition at line 81 of file hash.h.
References thorin::FNV1::prime.
Referenced by hash(), hash_begin(), hash_combine(), and thorin::UseHash::operator()().
hash_combine() [3/3]
template<class T , class... Args> hash_t thorin::hash_combine (hash_t seed, T val, Args &&... args)
Definition at line 100 of file hash.h.
References hash_combine().
id()
static std::string thorin::id (const Def * def) static
Definition at line 33 of file dump.cpp.
References thorin::Def::is_external(), thorin::Def::is_set(), thorin::RuntimeCast< Base >::isa(), thorin::Def::name(), and thorin::Def::unique_name().
Referenced by thorin::World::ax(), and thorin::Def::write().
infer_sigma()
static const Def * thorin::infer_sigma (World & world, Defs ops) static
Definition at line 113 of file world.cpp.
References thorin::World::sigma(), and thorin::Span< T >::size().
Referenced by thorin::World::tuple().
infer_type_level()
const Def * thorin::infer_type_level (World & world, Defs defs)
Definition at line 8 of file check.cpp.
References as_lit(), err(), thorin::World::lit_univ(), and thorin::World::type().
Referenced by thorin::World::ac(), thorin::World::bound(), thorin::World::sigma(), and thorin::fe::TuplePtrn::type().
is_continuation()
bool thorin::is_continuation (const Def * e)
Definition at line 161 of file autodiff_aux.cpp.
References is_continuation_type().
Referenced by thorin::autodiff::AutoDiffEval::augment_app(), compose_continuation(), is_direct_style_function(), and is_open_continuation().
is_continuation_type()
bool thorin::is_continuation_type (const Def * E)
Definition at line 156 of file autodiff_aux.cpp.
References thorin::RuntimeCast< Base >::isa().
Referenced by thorin::autodiff::autodiff_type_fun_pi(), is_continuation(), and is_returning_continuation().
is_direct_style_function()
bool thorin::is_direct_style_function (const Def * e)
Definition at line 178 of file autodiff_aux.cpp.
References is_continuation().
is_free()
bool thorin::is_free (Def * nom, const Def * def)
Does nom's Var occurr free in def?
Definition at line 93 of file scope.cpp.
References thorin::Scope::bound(), and thorin::Def::var().
Referenced by thorin::Pi::restructure(), and thorin::Sigma::restructure().
is_open_continuation()
bool thorin::is_open_continuation (const Def * e)
Definition at line 176 of file autodiff_aux.cpp.
References is_continuation(), and is_returning_continuation().
Referenced by thorin::autodiff::AutoDiffEval::augment_app(), and thorin::autodiff::AutoDiffEval::augment_lam().
is_returning_continuation()
bool thorin::is_returning_continuation (const Def * e)
Definition at line 163 of file autodiff_aux.cpp.
References is_continuation_type().
Referenced by compose_continuation(), and is_open_continuation().
is_shape()
bool thorin::is_shape (const Def * s)
Definition at line 257 of file world.cpp.
References thorin::RuntimeCast< Base >::isa(), thorin::Def::isa_structural(), and thorin::clos::op().
Referenced by thorin::World::arr(), and thorin::World::pack().
is_sigma_or_arr()
bool thorin::is_sigma_or_arr (const Def * def) inline
Definition at line 115 of file tuple.h.
References thorin::RuntimeCast< Base >::isa().
Referenced by should_flatten().
is_top_level() [1/2]
static bool thorin::is_top_level (Lam * lam) static
Definition at line 28 of file lam_spec.cpp.
References is_top_level(), and thorin::core::RMode::top.
is_top_level() [2/2]
static bool thorin::is_top_level (LamMap< bool > & top, Lam * lam) static
Definition at line 12 of file lam_spec.cpp.
References thorin::Scope::free_noms(), thorin::Scope::free_vars(), thorin::Def::is_external(), is_top_level(), and thorin::core::RMode::top.
Referenced by is_top_level().
is_tuple_or_pack()
bool thorin::is_tuple_or_pack (const Def * def) inline
Definition at line 116 of file tuple.h.
References thorin::RuntimeCast< Base >::isa().
Referenced by thorin::core::normalize_zip(), and normalize_zip().
is_unit()
bool thorin::is_unit (const Def * def)
Definition at line 57 of file tuple.cpp.
References thorin::World::sigma(), thorin::Def::type(), and thorin::Def::world().
is_var()
static bool thorin::is_var (const Def * def) static
Definition at line 5 of file eta_red.cpp.
References thorin::RuntimeCast< Base >::isa().
Referenced by eta_rule().
isa()
template<class T > const T * thorin::isa (flags_t f, const Def * def)
Definition at line 427 of file def.h.
References thorin::Def::flags().
isa_apped_nom_lam()
std::pair< const App *, Lam * > thorin::isa_apped_nom_lam (const Def * def) inline
Definition at line 180 of file lam.h.
References thorin::RuntimeCast< Base >::isa().
Referenced by thorin::PartialEval::rewrite().
isa_bound()
const Bound * thorin::isa_bound (const Def * def) inline
Definition at line 176 of file lattice.h.
References thorin::RuntimeCast< Base >::isa().
Referenced by thorin::Def::var().
isa_callee()
const App * thorin::isa_callee (const Def * def, size_t i) inline
Definition at line 179 of file lam.h.
References thorin::RuntimeCast< Base >::isa().
Referenced by thorin::clos::isa_callee_br().
isa_decl()
static Def * thorin::isa_decl (const Def * def) static
Definition at line 26 of file dump.cpp.
References thorin::Def::isa_nom().
Referenced by thorin::Inline::operator bool(), thorin::Dumper::recurse(), and thorin::Def::stream().
isa_ext()
const Ext * thorin::isa_ext (const Def * def) inline
Definition at line 172 of file lattice.h.
References thorin::RuntimeCast< Base >::isa().
isa_lit()
template<class T = u64> std::optional< T > thorin::isa_lit (const Def * def)
Definition at line 551 of file def.h.
References thorin::RuntimeCast< Base >::isa().
Referenced by thorin::World::arr(), thorin::Checker::assignable(), thorin::core::convert(), thorin::ll::Emitter::emit_bb(), thorin::World::extract(), thorin::World::insert(), thorin::Sym::is_anonymous(), thorin::World::lit(), normalize_Bit(), thorin::core::normalize_bit1(), thorin::core::normalize_bit2(), thorin::mem::normalize_lea(), thorin::core::normalize_ncmp(), thorin::core::normalize_nop(), thorin::refly::normalize_refine(), thorin::core::normalize_shr(), normalize_Shr(), thorin::core::normalize_trait(), normalize_Trait(), thorin::core::normalize_zip(), normalize_zip(), thorin::Def::num_projs(), thorin::World::pack(), thorin::Def::proj(), thorin::core::reassociate(), thorin::normalize::reassociate(), thorin::Arr::restructure(), thorin::Pack::restructure(), thorin::World::test(), and thorin::World::tuple().
isa_workable()
Lam * thorin::isa_workable (Lam * lam) inline
These are Lams that are neither nullptr, nor Lam::is_external, nor Lam::is_unset.
Definition at line 174 of file lam.h.
References thorin::Def::is_external(), and thorin::Def::is_unset().
lazy_init()
template<class This , class T > T & thorin::lazy_init (const This * self, std::unique_ptr< T > & ptr) inline
Definition at line 10 of file scope.h.
Referenced by thorin::CFA::b_cfg(), thorin::Scope::cfa(), thorin::CFG< forward >::domfrontier(), thorin::CFG< forward >::domtree(), thorin::CFA::f_cfg(), and thorin::CFG< forward >::looptree().
make_array()
template<class T > Array< typename T::value_type > thorin::make_array (const T & container)
Definition at line 409 of file array.h.
match() [1/2]
template<class Id , bool DynCast = true> auto thorin::match (const Def * def)
Definition at line 158 of file axiom.h.
References thorin::RuntimeCast< Base >::as(), and thorin::Axiom::get().
Referenced by thorin::core::normalize_pe(), thorin::refly::RemoveDbgPerm::rewrite(), thorin::World::test(), and thorin::Lam::test().
match() [2/2]
template<class Id , bool DynCast = true> auto thorin::match (Id id, const Def * def)
Definition at line 169 of file axiom.h.
References thorin::RuntimeCast< Base >::as(), and thorin::Axiom::get().
merge() [1/3]
DefArray thorin::merge (const Def * def, Defs defs)
Definition at line 59 of file tuple.cpp.
References thorin::Span< T >::size().
merge() [2/3]
DefArray thorin::merge (Defs a, Defs b)
Definition at line 63 of file tuple.cpp.
References thorin::Array< T >::begin().
merge() [3/3]
static void thorin::merge (VarSet & vars, VarSet && other) static
Definition at line 7 of file deptree.cpp.
Referenced by merge_sigma(), and merge_tuple().
merge_sigma()
const Def * thorin::merge_sigma (const Def * def, Defs defs)
Definition at line 70 of file tuple.cpp.
References thorin::RuntimeCast< Base >::isa(), thorin::Def::isa_nom(), merge(), thorin::World::sigma(), and thorin::Def::world().
merge_tuple()
const Def * thorin::merge_tuple (const Def * def, Defs defs)
Definition at line 76 of file tuple.cpp.
References thorin::RuntimeCast< Base >::isa(), thorin::Def::isa_nom(), merge(), thorin::World::tuple(), thorin::Def::type(), and thorin::Def::world().
murmur3() [1/3]
hash_t thorin::murmur3 (hash_t h) inline
Use for a single value to hash.
Definition at line 59 of file hash.h.
murmur3() [2/3]
hash_t thorin::murmur3 (hash_t h, uint32_t key) inline
Definition at line 19 of file hash.h.
References murmur_32_scramble().
Referenced by thorin::Def::Def(), thorin::DefDefHash::operator()(), thorin::SymHash::operator()(), and thorin::GIDHash< T >::operator()().
murmur3() [3/3]
hash_t thorin::murmur3 (hash_t h, uint64_t key) inline
Definition at line 26 of file hash.h.
References murmur_32_scramble().
murmur3_finalize()
hash_t thorin::murmur3_finalize (hash_t h, hash_t len) inline
Definition at line 48 of file hash.h.
Referenced by thorin::Def::Def(), and thorin::DefDefHash::operator()().
murmur3_rest() [1/2]
hash_t thorin::murmur3_rest (hash_t h, uint16_t key) inline
Definition at line 43 of file hash.h.
References murmur_32_scramble().
murmur3_rest() [2/2]
hash_t thorin::murmur3_rest (hash_t h, uint8_t key) inline
Definition at line 38 of file hash.h.
References murmur_32_scramble().
Referenced by thorin::Def::Def().
murmur_32_scramble()
hash_t thorin::murmur_32_scramble (hash_t k) inline
Definition at line 12 of file hash.h.
Referenced by murmur3(), and murmur3_rest().
nom_val_or_typ()
static bool thorin::nom_val_or_typ (const Def * def) static
Definition at line 12 of file tuple.cpp.
References thorin::Def::isa_nom(), thorin::Def::sort(), Term, and thorin::Def::type().
Referenced by flatten(), and unflatten().
normalize_Acc()
template<Acc op> const Def * thorin::normalize_Acc (const Def * type, const Def * callee, const Def * arg, const Def * dbg)
Definition at line 766 of file normalize.cpp.
References thorin::World::raw_app(), and thorin::Def::world().
normalize_Bit()
template<Bit op> const Def * thorin::normalize_Bit (const Def * type, const Def * c, const Def * arg, const Def * dbg)
Definition at line 282 of file normalize.cpp.
References thorin::RuntimeCast< Base >::as(), thorin::core::commute(), thorin::normalize::is_commutative(), isa_lit(), thorin::normalize::make_truth_table(), thorin::clos::op(), thorin::Def::op(), thorin::Def::projs(), unreachable(), and thorin::Def::world().
normalize_bitcast()
const Def * thorin::normalize_bitcast (const Def * dst_type, const Def * callee, const Def * src, const Def * dbg)
Definition at line 770 of file normalize.cpp.
References thorin::World::bot(), thorin::RuntimeCast< Base >::isa(), thorin::Def::type(), and thorin::Def::world().
normalize_Conv()
template<Conv op> const Def * thorin::normalize_Conv (const Def * dst_type, const Def * c, const Def * src, const Def * dbg)
Definition at line 735 of file normalize.cpp.
References thorin::RuntimeCast< Base >::as(), thorin::clos::op(), thorin::Def::op(), thorin::Def::type(), and thorin::Def::world().
normalize_ICmp()
template<ICmp op> const Def * thorin::normalize_ICmp (const Def * type, const Def * c, const Def * arg, const Def * dbg)
Definition at line 591 of file normalize.cpp.
References thorin::RuntimeCast< Base >::as(), thorin::clos::op(), thorin::Def::projs(), and thorin::Def::world().
normalize_PE()
template<PE op> const Def * thorin::normalize_PE (const Def * type, const Def * callee, const Def * arg, const Def * dbg)
Definition at line 754 of file normalize.cpp.
References thorin::Def::dep_const(), thorin::World::lit_ff(), thorin::clos::op(), and thorin::Def::world().
normalize_RCmp()
template<RCmp op> const Def * thorin::normalize_RCmp (const Def * type, const Def * c, const Def * arg, const Def * dbg)
Definition at line 608 of file normalize.cpp.
References thorin::RuntimeCast< Base >::as(), thorin::clos::op(), thorin::Def::projs(), and thorin::Def::world().
normalize_ROp()
template<ROp op> const Def * thorin::normalize_ROp (const Def * type, const Def * c, const Def * arg, const Def * dbg)
Definition at line 525 of file normalize.cpp.
References thorin::RuntimeCast< Base >::as(), thorin::core::RMode::fast, thorin::clos::op(), thorin::Def::projs(), rem(), unreachable(), and thorin::Def::world().
normalize_Shr()
template<Shr op> const Def * thorin::normalize_Shr (const Def * type, const Def * c, const Def * arg, const Def * dbg)
Definition at line 427 of file normalize.cpp.
References thorin::RuntimeCast< Base >::as(), isa_lit(), thorin::clos::op(), thorin::Def::projs(), unreachable(), and thorin::Def::world().
normalize_Trait()
template<Trait op> const Def * thorin::normalize_Trait (const Def * , const Def * callee, const Def * type, const Def * dbg)
Definition at line 632 of file normalize.cpp.
References thorin::RuntimeCast< Base >::isa(), isa_lit(), thorin::Def::isa_structural(), thorin::World::lit_nat(), thorin::core::WMode::nsw, thorin::core::WMode::nuw, thorin::clos::op(), thorin::Def::ops(), pad(), unreachable(), and thorin::Def::world().
normalize_Wrap()
template<Wrap op> const Def * thorin::normalize_Wrap (const Def * type, const Def * c, const Def * arg, const Def * dbg)
Definition at line 461 of file normalize.cpp.
References thorin::RuntimeCast< Base >::as(), thorin::clos::op(), thorin::Def::projs(), unreachable(), and thorin::Def::world().
normalize_zip()
const Def * thorin::normalize_zip (const Def * type, const Def * c, const Def * arg, const Def * dbg)
Definition at line 787 of file normalize.cpp.
References thorin::App::arg(), thorin::RuntimeCast< Base >::as(), is_tuple_or_pack(), isa_lit(), thorin::Def::projs(), and thorin::Def::world().
operator""_r16()
r16 thorin::operator""_r16 (long double d) inline
Definition at line 78 of file types.h.
operator""_r32()
constexpr r32 thorin::operator""_r32 (long double d) constexpr
Definition at line 79 of file types.h.
operator""_r64()
constexpr r64 thorin::operator""_r64 (long double d) constexpr
Definition at line 80 of file types.h.
operator""_s()
constexpr size_t thorin::operator""_s (unsigned long long int i) constexpr
A size_t literal. Use 0_s to disambiguate 0 from nullptr.
Definition at line 77 of file types.h.
operator""_s16()
constexpr s16 thorin::operator""_s16 (unsigned long long int s) constexpr
Definition at line 51 of file types.h.
operator""_s32()
constexpr s32 thorin::operator""_s32 (unsigned long long int s) constexpr
Definition at line 51 of file types.h.
operator""_s64()
constexpr s64 thorin::operator""_s64 (unsigned long long int s) constexpr
Definition at line 51 of file types.h.
operator""_s8()
constexpr s8 thorin::operator""_s8 (unsigned long long int s) constexpr
Definition at line 51 of file types.h.
operator""_u16()
constexpr u16 thorin::operator""_u16 (unsigned long long int u) constexpr
Definition at line 51 of file types.h.
operator""_u32()
constexpr u32 thorin::operator""_u32 (unsigned long long int u) constexpr
Definition at line 51 of file types.h.
operator""_u64()
constexpr u64 thorin::operator""_u64 (unsigned long long int u) constexpr
Definition at line 51 of file types.h.
operator""_u8()
constexpr u8 thorin::operator""_u8 (unsigned long long int u) constexpr
Definition at line 51 of file types.h.
operator<<() [1/7]
std::ostream & thorin::operator<< (std::ostream & os, const CFNode * n)
Definition at line 25 of file cfg.cpp.
References thorin::CFNode::nom().
operator<<() [2/7]
std::ostream & thorin::operator<< (std::ostream & os, const Def * def)
This will stream def as an operand.
This is usually id(def) unless it can be displayed Inline.
Definition at line 328 of file dump.cpp.
operator<<() [3/7]
std::ostream & thorin::operator<< (std::ostream & os, const Loc loc)
Definition at line 66 of file debug.cpp.
References thorin::Loc::begin, thorin::Loc::file, and thorin::Loc::finis.
operator<<() [4/7]
std::ostream & thorin::operator<< (std::ostream & os, const Pos pos)
Definition at line 61 of file debug.cpp.
References thorin::Pos::col, and thorin::Pos::row.
operator<<() [5/7]
std::ostream & thorin::operator<< (std::ostream & os, const Sym sym)
Definition at line 72 of file debug.cpp.
References thorin::Sym::to_string().
operator<<() [6/7]
template<bool forward> std::ostream & thorin::operator<< (std::ostream & os, const typename LoopTree< forward >::Base * n)
Definition at line 204 of file looptree.cpp.
References print(), and unreachable().
operator<<() [7/7]
std::ostream & thorin::operator<< (std::ostream & os, Inline u)
Definition at line 107 of file dump.cpp.
operator<<< false >()
template std::ostream & thorin::operator<<< false > (std::ostream & , const typename LoopTree< false >::Base *)
operator<<< true >()
template std::ostream & thorin::operator<<< true > (std::ostream & , const typename LoopTree< true >::Base *)
operator==() [1/3]
bool thorin::operator== (Loc l1, Loc l2) inline
Definition at line 107 of file debug.h.
References thorin::Loc::begin, thorin::Loc::file, and thorin::Loc::finis.
operator==() [2/3]
bool thorin::operator== (Pos p1, Pos p2) inline
Definition at line 106 of file debug.h.
References thorin::Pos::col, and thorin::Pos::row.
operator==() [3/3]
bool thorin::operator== (Sym s1, Sym s2) inline
Definition at line 105 of file debug.h.
References thorin::Sym::str().
optimize()
void thorin::optimize (World & world, PipelineBuilder & builder)
The optimizations proceed in a pipeline ordered by priorities.
Each phase is a sequence of passes that are run interleaved. The passes are added to the phase ordered by their priority. Order:
1-10: initial passes
100: Main optimization phase (default for extend_opt_phase)
200: Pre-CodeGen Optimization
300: CodeGen Preparation (default for extend_codegen_prep_phase)
concrete phases:
0 : Scalarize
1 : EtaRed
2 : TailRecElim
100: Optimize (Priority 50)
PartialEval
BetaRed
EtaRed
EtaExp
Scalarize
TailRecElim
+ Custom (default priority 100)
200: LamSpec
300: RetWrap (Priority 50)
+ Custom (default priority 100) See optimize.h for magic numbers
Definition at line 43 of file optimize.cpp.
References thorin::PassMan::add(), thorin::Pipeline::add(), thorin::PipelineBuilder::add_opt(), Codegen_Prep_Phase, thorin::PipelineBuilder::extend_opt_phase(), Opt_Phase, thorin::PipelineBuilder::opt_phase(), Pass_Internal_Priority, thorin::PipelineBuilder::passes(), and thorin::Phase::run().
outf()
template<class... Args> std::ostream & thorin::outf (const char * fmt, Args &&... args)
Definition at line 139 of file print.h.
References fmt(), and print().
Referenced by outln().
outln()
template<class... Args> std::ostream & thorin::outln (const char * fmt, Args &&... args)
Definition at line 141 of file print.h.
References fmt(), and outf().
pad()
u64 thorin::pad (u64 offset, u64 align) inline
Definition at line 621 of file normalize.cpp.
Referenced by normalize_Trait().
pop() [1/2]
template<class Q > auto thorin::pop (Q & q) -> decltype(q.front(), typename Q::value_type())
Definition at line 23 of file container.h.
pop() [2/2]
template<class S > auto thorin::pop (S & s) -> decltype(s.top(), typename S::value_type())
Definition at line 16 of file container.h.
Referenced by thorin::CFA::CFA(), thorin::unique_stack< Set >::pop(), thorin::unique_queue< Set >::pop(), and thorin::PassMan::run().
print() [1/2]
std::ostream & thorin::print (std::ostream & os, const char * s)
Base case.
Definition at line 5 of file print.cpp.
References thorin::detail::match2nd(), and unreachable().
Referenced by thorin::ll::BB::assign(), thorin::Dumper::dump(), thorin::World::dump(), thorin::Dumper::dump_ptrn(), thorin::h::Bootstrapper::emit(), thorin::ll::Emitter::emit_bb(), thorin::dot::Emitter::emit_bb(), thorin::dot::emit_cluster_start(), thorin::ll::Emitter::emit_epilogue(), thorin::dot::Emitter::emit_epilogue(), thorin::ll::Emitter::emit_imported(), thorin::dot::Emitter::emit_imported(), err(), thorin::dl::err(), errf(), thorin::ll::Emitter::finalize(), fmt(), thorin::Log::log(), operator<<(), outf(), thorin::ll::Emitter::prepare(), thorin::Tab::print(), print(), and thorin::ll::BB::tail().
print() [2/2]
template<class T , class... Args> std::ostream & thorin::print (std::ostream & os, const char * s, T && t, Args &&... args)
Provides a printf-like interface to format s with args and puts it into os.
Use {} as a placeholder within your format string s.
By default, os << t` will be used to stream the appropriate argument:
print(os, "int: {}, float: {}", 23, 42.f);
You can also place a function as argument to inject arbitrary code:
print(os, "int: {}, fun: {}, float: {}", 23, [&]() { os << "hey :)"}, 42.f);
There is also a variant to pass os to the function, if you don't have easy access to it:
print(os, "int: {}, fun: {}, float: {}", 23, [&](auto& os) { os << "hey :)"}, 42.f);
You can put a std::ranges::range as argument. This will output a list - using the given specifier as seperator. Each element elem of the range will be output via os << elem:
std::vector<int> v = {0, 1, 2, 3};
print(os, "v: {, }", v);
If you have a std::ranges::range that needs to be formatted in a more complicated way, bundle it with an Elem:
std::vector<int> v = {3, 2, 1, 0};
size_t i = 0;
print(os, "v: {, }", Elem(v, [&](auto elem) { print(os, "{}: {}", i++, elem); }));
You again have the option to pass os to the bundled function:
std::vector<int> v = {3, 2, 1, 0};
size_t i = 0;
print(os, "v: {, }", Elem(v, [&](auto& os, auto elem) { print(os, "{}: {}", i++, elem); }));
Definition at line 88 of file print.h.
References thorin::detail::match2nd(), print(), thorin::detail::range(), and unreachable().
rem() [1/4]
double thorin::rem (double a, double b) inline
Definition at line 65 of file types.h.
rem() [2/4]
float thorin::rem (float a, float b) inline
Definition at line 64 of file types.h.
rem() [3/4]
half thorin::rem (half a, half b) inline
Definition at line 63 of file types.h.
Referenced by normalize_ROp(), thorin::BitSet::operator>>=(), thorin::core::Fold< rop, rop::rem, w >::run(), and thorin::normalize::Fold< ROp, ROp::rem, w >::run().
rem() [4/4]
long double thorin::rem (long double a, long double b) inline
Definition at line 66 of file types.h.
rewrite() [1/5]
const Def * thorin::rewrite (const Def * def, const Def * old_def, const Def * new_def, const Scope & scope)
Rewrites def by mapping old_def to new_def while obeying scope.
Definition at line 48 of file rewrite.cpp.
References thorin::Rewriter::old2new, thorin::ScopeRewriter::rewrite(), and thorin::Def::world().
Referenced by thorin::World::extract(), thorin::direct::op_cps2ds_dep(), thorin::Def::reduce(), thorin::Arr::reduce(), thorin::Pack::reduce(), rewrite(), and thorin::clos::ClosConv::start().
rewrite() [2/5]
DefArray thorin::rewrite (Def * nom, const Def * arg)
Rewrites nom's ops by substituting nom's Var with arg while obeying nom's scope.
Definition at line 69 of file rewrite.cpp.
References rewrite().
rewrite() [3/5]
DefArray thorin::rewrite (Def * nom, const Def * arg, const Scope & scope)
Same as above but uses scope as an optimization instead of computing a new Scope.
Definition at line 63 of file rewrite.cpp.
References thorin::Def::num_ops(), thorin::Rewriter::old2new, thorin::Def::var(), and thorin::Def::world().
rewrite() [4/5]
const Def * thorin::rewrite (Def * nom, const Def * arg, size_t i)
Rewrites nom's i^th op by substituting nom's Var with arg while obeying nom's scope.
Definition at line 58 of file rewrite.cpp.
References rewrite().
rewrite() [5/5]
const Def * thorin::rewrite (Def * nom, const Def * arg, size_t i, const Scope & scope)
Same as above but uses scope as an optimization instead of computing a new Scope.
Definition at line 54 of file rewrite.cpp.
References thorin::Def::op(), rewrite(), and thorin::Def::var().
schedule()
Schedule thorin::schedule (const Scope & scope)
Definition at line 114 of file schedule.cpp.
References thorin::Scope::f_cfg(), and thorin::CFG< forward >::reverse_post_order().
Referenced by thorin::ll::Emitter::finalize(), and thorin::Emitter< Value, Type, BB, Child >::visit().
should_flatten()
static bool thorin::should_flatten (const Def * def) static
Definition at line 10 of file tuple.cpp.
References is_sigma_or_arr(), thorin::Def::sort(), Term, and thorin::Def::type().
Referenced by flatten().
size2bitwidth()
constexpr std::optional< uint64_t > thorin::size2bitwidth (uint64_t n) constexpr
Definition at line 151 of file axiom.h.
Referenced by thorin::ll::Emitter::emit_bb(), thorin::core::fold(), and thorin::core::fold_conv().
sub_view()
static std::string_view thorin::sub_view (std::string_view s, size_t i, size_t n = std::string_view::npos) static
Definition at line 70 of file axiom.cpp.
Referenced by thorin::Axiom::split().
thorin_get_dialect_info()
THORIN_EXPORT thorin::DialectInfo thorin::thorin_get_dialect_info ()
To be implemented and exported by the dialect plugins.
Shall return a filled DialectInfo.
tuple2str()
std::string thorin::tuple2str (const Def * def)
Definition at line 87 of file tuple.cpp.
References thorin::Def::arity(), as_lit(), and thorin::Def::projs().
Referenced by thorin::Sym::to_string().
unflatten() [1/3]
const Def * thorin::unflatten (const Def * def, const Def * type)
Applies the reverse transformation on a pack/tuple, given the original type.
Definition at line 55 of file tuple.cpp.
References thorin::Def::arity(), as_lit(), thorin::Def::projs(), and unflatten().
unflatten() [2/3]
static const Def * thorin::unflatten (Defs defs, const Def * type, size_t & j, bool flatten_noms) static
Definition at line 37 of file tuple.cpp.
References thorin::Def::arity(), thorin::Span< T >::empty(), nom_val_or_typ(), thorin::Def::proj(), unflatten(), and thorin::Def::world().
Referenced by unflatten().
unflatten() [3/3]
const Def * thorin::unflatten (Defs defs, const Def * type, bool flatten_noms)
Same as unflatten, but uses the operands of a flattened pack/tuple directly.
Definition at line 48 of file tuple.cpp.
References thorin::Span< T >::size(), and unflatten().
unreachable()
void thorin::unreachable () inline
Definition at line 19 of file assert.h.
Referenced by thorin::Dumper::dump(), thorin::ll::Emitter::emit_bb(), thorin::Checker::equiv(), thorin::core::fold(), thorin::core::get_size(), thorin::Log::level2acro(), thorin::Log::level2color(), thorin::Def::node_name(), normalize_Bit(), thorin::core::normalize_bit2(), thorin::core::normalize_ncmp(), thorin::core::normalize_rop(), normalize_ROp(), normalize_Shr(), thorin::core::normalize_trait(), normalize_Trait(), thorin::core::normalize_wrap(), normalize_Wrap(), operator<<(), thorin::fe::Tok::prec(), print(), thorin::Def::rebuild(), thorin::Def::stub(), thorin::fe::Tok::tag2str(), and thorin::Def::var().
visit()
template<class Indexer , class Key > bool thorin::visit (IndexSet< Indexer, Key > & set, const Key & key)
Definition at line 102 of file indexset.h.
References thorin::IndexSet< Indexer, Key >::insert().
Referenced by visit_first().
visit_first()
template<class Indexer , class Key > void thorin::visit_first (IndexSet< Indexer, Key > & set, const Key & key)
Definition at line 107 of file indexset.h.
References thorin::IndexSet< Indexer, Key >::contains(), and visit().
Variable Documentation
Codegen_Prep_Phase
constexpr int thorin::Codegen_Prep_Phase = 300 static constexpr
Definition at line 8 of file optimize.h.
Referenced by thorin::PipelineBuilder::extend_codegen_prep_phase(), and optimize().
No_Undo
constexpr undo_t thorin::No_Undo = std::numeric_limits<undo_t>::max() static constexpr
Definition at line 12 of file pass.h.
Referenced by thorin::Pass::analyze(), thorin::PassMan::run(), thorin::FPPass< P, N >::undo_enter(), and thorin::FPPass< P, N >::undo_visit().
Opt_Phase
constexpr int thorin::Opt_Phase = 100 static constexpr
Definition at line 7 of file optimize.h.
Referenced by thorin::PipelineBuilder::extend_opt_phase(), and optimize().
Pass_Default_Priority
constexpr int thorin::Pass_Default_Priority = 100 static constexpr
Definition at line 6 of file optimize.h.
Pass_Internal_Priority
constexpr int thorin::Pass_Internal_Priority = 50 static constexpr
Definition at line 5 of file optimize.h.
Referenced by thorin::PipelineBuilder::add_opt(), and optimize().
Search_In_Uses_Threshold
constexpr int thorin::Search_In_Uses_Threshold = 8 static constexpr
Definition at line 15 of file def.cpp.
Referenced by thorin::Def::proj(), and thorin::Def::var().