Thorin: thorin::automaton Namespace Reference
thorin::automaton Namespace Reference
Classes
class AutomatonBase
class DFA
class DFANode
class NFA
class NFANode
Functions
template<class NodeType , class PrintCharF >
std::ostream & print_node (std::ostream &os, const NodeType &node, PrintCharF &&print_char)
std::ostream & operator<< (std::ostream &os, const DFANode &node)
std::unique_ptr< DFA > minimize_dfa (const DFA &dfa)
std::ostream & operator<< (std::ostream &os, const NFANode &node)
std::set< const NFANode * > epsilonClosure (const std::set< const NFANode * > &states)
std::set< const NFANode * > epsilonClosure (const NFANode *state)
std::unique_ptr< DFA > nfa2dfa (const NFA &nfa)
Function Documentation
epsilonClosure() [1/2]
std::set< const NFANode * > thorin::automaton::epsilonClosure (const NFANode * state)
Definition at line 28 of file nfa2dfa.cpp.
References epsilonClosure().
epsilonClosure() [2/2]
std::set< const NFANode * > thorin::automaton::epsilonClosure (const std::set< const NFANode * > & states)
Definition at line 11 of file nfa2dfa.cpp.
References thorin::automaton::NFA::EPSILON.
Referenced by epsilonClosure(), and nfa2dfa().
minimize_dfa()
std::unique_ptr< DFA > thorin::automaton::minimize_dfa (const DFA & dfa)
Definition at line 114 of file dfamin.cpp.
References thorin::automaton::AutomatonBase< NodeType >::get_reachable_states(), and thorin::automaton::AutomatonBase< NodeType >::get_start().
Referenced by thorin::regex::LowerRegex::rewrite().
nfa2dfa()
std::unique_ptr< DFA > thorin::automaton::nfa2dfa (const NFA & nfa)
Definition at line 33 of file nfa2dfa.cpp.
References thorin::automaton::NFA::EPSILON, epsilonClosure(), and thorin::automaton::AutomatonBase< NodeType >::get_start().
Referenced by thorin::regex::LowerRegex::rewrite().
operator<<() [1/2]
std::ostream & thorin::automaton::operator<< (std::ostream & os, const DFANode & node)
Definition at line 25 of file dfa.cpp.
operator<<() [2/2]
std::ostream & thorin::automaton::operator<< (std::ostream & os, const NFANode & node)
Definition at line 31 of file nfa.cpp.
print_node()
template<class NodeType , class PrintCharF > std::ostream & thorin::automaton::print_node (std::ostream & os, const NodeType & node, PrintCharF && print_char)
Definition at line 72 of file automaton.h.