Thorin: thorin::regex Namespace Reference
thorin::regex Namespace Reference
The regex Plugin
Classes
struct app_range
class LowerRegex
Enumerations
%regex.lit
enum lit : flags_t
%regex.any
enum any : flags_t
%regex.lower_regex
enum lower_regex : flags_t
Functions
template<class ConjOrDisj >
void flatten_in_arg (Ref arg, std::vector< const Def * > &new_args)
template<class ConjOrDisj >
std::vector< const Def * > flatten_in_arg (Ref arg)
template<class ConjOrDisj >
Ref make_binary_tree (Ref type, DefArray args)
bool compare_re (const Def *lhs, const Def *rhs)
void make_vector_unique (std::vector< const Def * > &args)
bool is_in_range (std::pair< nat_t, nat_t > range, nat_t needle)
auto get_range (const Def *rng) -> std::pair< nat_t, nat_t >
void merge_ranges (std::vector< const Def * > &args)
template<cls A, cls B>
bool equals_any (const Def *cls0, const Def *cls1)
bool equals_any (const Def *lhs, const Def *rhs)
bool equals_any (const std::vector< const Def * > &lhs, const std::vector< const Def * > &rhs)
Ref dfa2matcher (World &w, const automaton::DFA &dfa, Ref n)
std::unique_ptr< automaton::NFA > regex2nfa (Ref regex)
std::optional< std::pair< nat_t, nat_t > > merge_ranges (std::pair< nat_t, nat_t > a, std::pair< nat_t, nat_t > b)
std::vector< std::pair< nat_t, nat_t > > merge_ranges (World &w, const std::vector< std::pair< nat_t, nat_t > > &old_ranges)
void register_normalizers (Normalizers &normalizers)
Variables
static constexpr plugin_t Plugin_Id = 0x4c62066400000000
%regex.conj
enum conj : flags_t
Ref normalize_conj (Ref type, Ref callee, Ref arg)
%regex.disj
enum disj : flags_t
Ref normalize_disj (Ref type, Ref, Ref arg)
%regex.range
enum range : flags_t
Ref normalize_range (Ref type, Ref callee, Ref arg)
%regex.not_
enum not_ : flags_t
Ref normalize_not (Ref type, Ref callee, Ref arg)
%regex.cls
enum cls : flags_t {
d = 0x4c62066400000500 ,
D = 0x4c62066400000501 ,
w = 0x4c62066400000502 ,
W = 0x4c62066400000503 ,
s = 0x4c62066400000504 ,
S = 0x4c62066400000505
}
constexpr auto operator& (cls x, cls y)
constexpr auto operator& (std::underlying_type_t< cls > x, cls y)
constexpr auto operator& (cls x, std::underlying_type_t< cls > y)
constexpr auto operator| (cls x, cls y)
constexpr auto operator| (std::underlying_type_t< cls > x, cls y)
constexpr auto operator| (cls x, std::underlying_type_t< cls > y)
constexpr auto operator^ (cls x, cls y)
constexpr auto operator^ (std::underlying_type_t< cls > x, cls y)
constexpr auto operator^ (cls x, std::underlying_type_t< cls > y)
constexpr std::strong_ordering operator<=> (std::underlying_type_t< cls > x, cls y)
constexpr std::strong_ordering operator<=> (cls x, std::underlying_type_t< cls > y)
constexpr bool operator== (std::underlying_type_t< cls > x, cls y)
constexpr bool operator== (cls x, std::underlying_type_t< cls > y)
%regex.quant
enum quant : flags_t {
optional = 0x4c62066400000700 ,
star = 0x4c62066400000701 ,
plus = 0x4c62066400000702
}
template<quant id>
Ref normalize_quant (Ref type, Ref callee, Ref arg)
constexpr auto operator& (quant x, quant y)
constexpr auto operator& (std::underlying_type_t< quant > x, quant y)
constexpr auto operator& (quant x, std::underlying_type_t< quant > y)
constexpr auto operator| (quant x, quant y)
constexpr auto operator| (std::underlying_type_t< quant > x, quant y)
constexpr auto operator| (quant x, std::underlying_type_t< quant > y)
constexpr auto operator^ (quant x, quant y)
constexpr auto operator^ (std::underlying_type_t< quant > x, quant y)
constexpr auto operator^ (quant x, std::underlying_type_t< quant > y)
constexpr std::strong_ordering operator<=> (std::underlying_type_t< quant > x, quant y)
constexpr std::strong_ordering operator<=> (quant x, std::underlying_type_t< quant > y)
constexpr bool operator== (std::underlying_type_t< quant > x, quant y)
constexpr bool operator== (quant x, std::underlying_type_t< quant > y)
Detailed Description
The regex Plugin
Enumeration Type Documentation
any
enum thorin::regex::any : flags_t
Definition at line 92 of file autogen.h.
cls
enum thorin::regex::cls : flags_t
Enumerator
d
D
w
W
s
S
Definition at line 74 of file autogen.h.
conj
enum thorin::regex::conj : flags_t
Definition at line 15 of file autogen.h.
disj
enum thorin::regex::disj : flags_t
Definition at line 27 of file autogen.h.
lit
enum thorin::regex::lit : flags_t
Definition at line 51 of file autogen.h.
lower_regex
enum thorin::regex::lower_regex : flags_t
Definition at line 121 of file autogen.h.
not_
enum thorin::regex::not_ : flags_t
Definition at line 62 of file autogen.h.
quant
enum thorin::regex::quant : flags_t
Enumerator
optional
star
plus
Definition at line 103 of file autogen.h.
range
enum thorin::regex::range : flags_t
Definition at line 39 of file autogen.h.
Function Documentation
compare_re()
bool thorin::regex::compare_re (const Def * lhs, const Def * rhs)
Definition at line 82 of file normalizers_regex.cpp.
References compare_re().
Referenced by compare_re(), and make_vector_unique().
dfa2matcher()
Ref thorin::regex::dfa2matcher (World & w, const automaton::DFA & dfa, Ref n)
Definition at line 93 of file dfa2matcher.cpp.
References thorin::error(), thorin::automaton::AutomatonBase< NodeType >::get_reachable_states(), and w.
Referenced by thorin::regex::LowerRegex::rewrite().
equals_any() [1/3]
template<cls A, cls B> bool thorin::regex::equals_any (const Def * cls0, const Def * cls1)
Definition at line 142 of file normalizers_regex.cpp.
References equals_any(), and thorin::match().
Referenced by equals_any(), and normalize_disj().
equals_any() [2/3]
bool thorin::regex::equals_any (const Def * lhs, const Def * rhs)
Definition at line 146 of file normalizers_regex.cpp.
References equals_any().
equals_any() [3/3]
bool thorin::regex::equals_any (const std::vector< const Def * > & lhs, const std::vector< const Def * > & rhs)
Definition at line 158 of file normalizers_regex.cpp.
References d, equals_any(), and get_range().
flatten_in_arg() [1/2]
template<class ConjOrDisj > std::vector< const Def * > thorin::regex::flatten_in_arg (Ref arg)
Definition at line 57 of file normalizers_regex.cpp.
flatten_in_arg() [2/2]
template<class ConjOrDisj > void thorin::regex::flatten_in_arg (Ref arg, std::vector< const Def * > & new_args)
Definition at line 47 of file normalizers_regex.cpp.
References thorin::Def::projs().
get_range()
auto thorin::regex::get_range (const Def * rng) -> std::pair<nat_t, nat_t>
Definition at line 110 of file normalizers_regex.cpp.
References get_range().
Referenced by equals_any(), get_range(), and merge_ranges().
is_in_range()
bool thorin::regex::is_in_range (std::pair< nat_t, nat_t > range, nat_t needle)
Definition at line 106 of file normalizers_regex.cpp.
References is_in_range().
Referenced by is_in_range().
make_binary_tree()
template<class ConjOrDisj > Ref thorin::regex::make_binary_tree (Ref type, DefArray args)
Definition at line 63 of file normalizers_regex.cpp.
References thorin::Array< T >::begin(), thorin::Array< T >::empty(), thorin::Array< T >::end(), thorin::Array< T >::front(), and thorin::Def::world().
make_vector_unique()
void thorin::regex::make_vector_unique (std::vector< const Def * > & args)
Definition at line 98 of file normalizers_regex.cpp.
References compare_re(), and make_vector_unique().
Referenced by make_vector_unique(), merge_ranges(), and normalize_disj().
merge_ranges() [1/3]
std::optional< std::pair< nat_t, nat_t > > thorin::regex::merge_ranges (std::pair< nat_t, nat_t > a, std::pair< nat_t, nat_t > b)
Definition at line 4 of file range_helper.cpp.
merge_ranges() [2/3]
void thorin::regex::merge_ranges (std::vector< const Def * > & args)
Definition at line 122 of file normalizers_regex.cpp.
References get_range(), make_vector_unique(), and merge_ranges().
Referenced by merge_ranges(), and normalize_disj().
merge_ranges() [3/3]
std::vector< std::pair< nat_t, nat_t > > thorin::regex::merge_ranges (World & w, const std::vector< std::pair< nat_t, nat_t > > & old_ranges)
Definition at line 13 of file range_helper.cpp.
References merge_ranges(), and w.
normalize_conj()
Ref thorin::regex::normalize_conj (Ref type, Ref callee, Ref arg)
Definition at line 71 of file normalizers_regex.cpp.
References thorin::Def::as_lit_arity(), normalize_conj(), and thorin::Def::world().
Referenced by normalize_conj().
normalize_disj()
Ref thorin::regex::normalize_disj (Ref type, Ref , Ref arg)
Definition at line 166 of file normalizers_regex.cpp.
References thorin::Def::as_lit_arity(), equals_any(), make_vector_unique(), merge_ranges(), normalize_disj(), and thorin::Def::world().
Referenced by normalize_disj().
normalize_not()
Ref thorin::regex::normalize_not (Ref type, Ref callee, Ref arg)
Definition at line 217 of file normalizers_regex.cpp.
References normalize_not(), thorin::World::raw_app(), and thorin::Def::world().
Referenced by normalize_not().
normalize_quant()
template<quant id> Ref thorin::regex::normalize_quant (Ref type, Ref callee, Ref arg)
Definition at line 21 of file normalizers_regex.cpp.
References thorin::match(), optional, plus, star, and thorin::Def::world().
normalize_range()
Ref thorin::regex::normalize_range (Ref type, Ref callee, Ref arg)
Definition at line 207 of file normalizers_regex.cpp.
References thorin::Lit::get(), normalize_range(), thorin::Def::projs(), and thorin::Def::world().
Referenced by normalize_range().
operator&() [1/6]
constexpr auto thorin::regex::operator& (cls x, cls y) constexpr
Definition at line 86 of file autogen.h.
operator&() [2/6]
constexpr auto thorin::regex::operator& (cls x, std::underlying_type_t< cls > y) constexpr
Definition at line 86 of file autogen.h.
operator&() [3/6]
constexpr auto thorin::regex::operator& (quant x, quant y) constexpr
Definition at line 112 of file autogen.h.
operator&() [4/6]
constexpr auto thorin::regex::operator& (quant x, std::underlying_type_t< quant > y) constexpr
Definition at line 112 of file autogen.h.
operator&() [5/6]
constexpr auto thorin::regex::operator& (std::underlying_type_t< cls > x, cls y) constexpr
Definition at line 86 of file autogen.h.
operator&() [6/6]
constexpr auto thorin::regex::operator& (std::underlying_type_t< quant > x, quant y) constexpr
Definition at line 112 of file autogen.h.
operator<=>() [1/4]
constexpr std::strong_ordering thorin::regex::operator<=> (cls x, std::underlying_type_t< cls > y) constexpr
Definition at line 86 of file autogen.h.
operator<=>() [2/4]
constexpr std::strong_ordering thorin::regex::operator<=> (quant x, std::underlying_type_t< quant > y) constexpr
Definition at line 112 of file autogen.h.
operator<=>() [3/4]
constexpr std::strong_ordering thorin::regex::operator<=> (std::underlying_type_t< cls > x, cls y) constexpr
Definition at line 86 of file autogen.h.
operator<=>() [4/4]
constexpr std::strong_ordering thorin::regex::operator<=> (std::underlying_type_t< quant > x, quant y) constexpr
Definition at line 112 of file autogen.h.
operator==() [1/4]
constexpr bool thorin::regex::operator== (cls x, std::underlying_type_t< cls > y) constexpr
Definition at line 86 of file autogen.h.
operator==() [2/4]
constexpr bool thorin::regex::operator== (quant x, std::underlying_type_t< quant > y) constexpr
Definition at line 112 of file autogen.h.
operator==() [3/4]
constexpr bool thorin::regex::operator== (std::underlying_type_t< cls > x, cls y) constexpr
Definition at line 86 of file autogen.h.
operator==() [4/4]
constexpr bool thorin::regex::operator== (std::underlying_type_t< quant > x, quant y) constexpr
Definition at line 112 of file autogen.h.
operator^() [1/6]
constexpr auto thorin::regex::operator^ (cls x, cls y) constexpr
Definition at line 86 of file autogen.h.
operator^() [2/6]
constexpr auto thorin::regex::operator^ (cls x, std::underlying_type_t< cls > y) constexpr
Definition at line 86 of file autogen.h.
operator^() [3/6]
constexpr auto thorin::regex::operator^ (quant x, quant y) constexpr
Definition at line 112 of file autogen.h.
operator^() [4/6]
constexpr auto thorin::regex::operator^ (quant x, std::underlying_type_t< quant > y) constexpr
Definition at line 112 of file autogen.h.
operator^() [5/6]
constexpr auto thorin::regex::operator^ (std::underlying_type_t< cls > x, cls y) constexpr
Definition at line 86 of file autogen.h.
operator^() [6/6]
constexpr auto thorin::regex::operator^ (std::underlying_type_t< quant > x, quant y) constexpr
Definition at line 112 of file autogen.h.
operator|() [1/6]
constexpr auto thorin::regex::operator| (cls x, cls y) constexpr
Definition at line 86 of file autogen.h.
operator|() [2/6]
constexpr auto thorin::regex::operator| (cls x, std::underlying_type_t< cls > y) constexpr
Definition at line 86 of file autogen.h.
operator|() [3/6]
constexpr auto thorin::regex::operator| (quant x, quant y) constexpr
Definition at line 112 of file autogen.h.
operator|() [4/6]
constexpr auto thorin::regex::operator| (quant x, std::underlying_type_t< quant > y) constexpr
Definition at line 112 of file autogen.h.
operator|() [5/6]
constexpr auto thorin::regex::operator| (std::underlying_type_t< cls > x, cls y) constexpr
Definition at line 86 of file autogen.h.
operator|() [6/6]
constexpr auto thorin::regex::operator| (std::underlying_type_t< quant > x, quant y) constexpr
Definition at line 112 of file autogen.h.
regex2nfa()
std::unique_ptr< automaton::NFA > thorin::regex::regex2nfa (Ref regex)
Definition at line 78 of file regex2nfa.cpp.
Referenced by thorin::regex::LowerRegex::rewrite().
register_normalizers()
void thorin::regex::register_normalizers (Normalizers & normalizers)
Referenced by thorin_get_plugin().
Variable Documentation
Plugin_Id
constexpr plugin_t thorin::regex::Plugin_Id = 0x4c62066400000000 static constexpr
Definition at line 10 of file autogen.h.