MimIR: mim Namespace Reference
mim Namespace Reference
Namespaces
namespace ast
namespace dl
namespace lct
namespace ll
namespace plug
namespace sys
Classes
struct Annex
Holds info about an entity defined within a Plugin (called Annex).
class App
class Arr
A (possibly paramterized) Array.
class Axm
class BetaRed
Optimistically performs β-reduction (aka inlining).
class BitSet
class Bound
Common base for TBound.
class Checker
class Cleanup
Removes unreachable and dead code by rebuilding the whole World into a new one and swapping afterwards.
class ClosedCollector
Transitively collects all closed mutables (Def::is_closed) in a World.
class ClosedMutPhase
Transitively visits all reachable closed mutables (Def::is_closed()) in World.
struct Dbg
class Def
Base class for all Defs.
class Driver
Some "global" variables needed all over the place.
struct Elem
Use with print to output complicated std::ranges::ranges.
class Emitter
class Error
class EtaExp
Performs η-expansion: f -> λx.f x, if f is a Lam with more than one user and does not appear in callee position.
class EtaRed
Performs η-reduction.
class Ext
Common base for TExtremum.
class Extract
Extracts from a Sigma or Array-typed Extract::tuple the element at position Extract::index.
struct Flags
Compiler switches that must be saved and looked up in later phases of compilation.
struct FNV1
struct FNV1< 4 >
struct FNV1< 8 >
class FPPass
Inherit from this class using CRTP, if you do need a Pass with a state and a fixed-point.
class FPPhase
Like a RWPhase but starts with a fixed-point loop of FPPhase::analyze beforehand.
struct GIDHash
struct GIDLt
class Global
class Hole
This node is a hole in the IR that is inferred by its context later on.
class Idx
A built-in constant of type Nat -> *.
class IndexMap
class IndexSet
class Inj
Constructs a Join value.
class Insert
Creates a new Tuple / Pack by inserting Insert::value at position Insert::index into Insert::tuple.
class Lam
A function.
class LamSpec
class Lit
class Log
Facility to log what you are doing.
class Match
Scrutinize Match::scrutinee() and dispatch to Match::arms.
class Merge
Constructs a Meet value.
class Nat
class Nest
Builds a nesting tree of all immutables‍/binders.
class NestPhase
Like ClosedMutPhase but computes a Nest for each NestPhase::visit.
class Pack
A (possibly paramterized) Tuple.
class Pass
All Passes that want to be registered in the PassMan must implement this interface.
class PassMan
An optimizer that combines several optimizations in an optimal way.
class PassManPhase
Wraps a PassMan pipeline as a Phase.
class PassPhase
Wraps a Pass as a Phase.
class Phase
As opposed to a Pass, a Phase does one thing at a time and does not mix with other Phases.
class Pi
A dependent function type.
class Pipeline
Organizes several Phases as a pipeline.
class PipelineBuilder
struct Plugin
Basic info and registration function pointer to be returned from a specific plugin.
class Prod
Base class for Sigma and Tuple.
class Proxy
class Res
Utility class when folding constants in normalizers.
class RetWrap
class Rewriter
Recurseivly rebuilds part of a program into the provided World w.r.t. Rewriter::map.
class RWPass
Inherit from this class using CRTP, if your Pass does not need state and a fixed-point iteration.
class RWPhase
Visits the current Phase::world and constructs a new RWPhase::world along the way.
class Scalarize
Perform Scalarization (= Argument simplification).
class Scheduler
class Seq
Base class for Arr and Pack.
class Sets
class Setters
CRTP-based Mixin to declare setters for Def::loc & Def::name using a covariant return type.
class Sigma
A dependent tuple type.
class Span
This is a thin wrapper for std::span<T, N> with the following additional features:
class Split
Picks the aspect of a Meet [value](Pick::value) by its [type](Def::type).
class Tab
Keeps track of indentation level.
class TailRecElim
class TBound
Specific Bound depending on Up.
class TExt
Extremum. Either Top (Up) or Bottom.
class Tuple
Data constructor for a Sigma.
class Type
class UInc
class UMax
class Uniq
A singleton wraps a type into a higher order type.
class unique_queue
class unique_stack
class Univ
class Use
const Def*erences a user.
struct UseEq
struct UseHash
class Var
class VarRewriter
class Vector
This is a thin wrapper for absl::InlinedVector<T, N, A> which is a drop-in replacement for std::vector<T, A>.
class World
The World represents the whole program and manages creation of MimIR nodes (Defs).
Concepts
concept annex_with_subs
concept annex_without_subs
concept Vectorlike
Something which behaves like std::vector or std::array.
Typedefs
using NormalizeFn = const Def* (*)(const Def*, const Def*, const Def*)
using Uses = absl::flat_hash_set<Use, UseHash, UseEq>
template<class T, size_t N = std::dynamic_extent>
using View = Span<const T, N>
Def
GIDSet / GIDMap keyed by Def::gid of conset Def*.
template<class To>
using DefMap = GIDMap<const Def*, To>
using DefSet = GIDSet<const Def*>
using Def2Def = DefMap<const Def*>
using Defs = View<const Def*>
using DefVec = Vector<const Def*>
Def (Mutable)
GIDSet / GIDMap keyed by Def::gid of Def*.
template<class To>
using MutMap = GIDMap<Def*, To>
using MutSet = GIDSet<Def*>
using Mut2Mut = MutMap<Def*>
using Muts = Sets<Def>::Set
Var
GIDSet / GIDMap keyed by Var::gid of const Var*.
template<class To>
using VarMap = GIDMap<const Var*, To>
using VarSet = GIDSet<const Var*>
using Var2Var = VarMap<const Var*>
using Vars = Sets<const Var>::Set
Lam
GIDSet / GIDMap keyed by Lam::gid of Lam*.
template<class To>
using LamMap = GIDMap<Lam*, To>
using LamSet = GIDSet<Lam*>
using Lam2Lam = LamMap<Lam*>
Lattice
using Bot = TExt<false>
using Top = TExt<true>
using Meet = TBound<false>
AKA intersection.
using Join = TBound<true>
AKA union.
Aliases for some Base Types
using s8 = int8_t
using u8 = uint8_t
using s16 = int16_t
using u16 = uint16_t
using s32 = int32_t
using u32 = uint32_t
using s64 = int64_t
using u64 = uint64_t
using u1 = bool
using f16 = half
using f32 = float
using f64 = double
using level_t = u64
using nat_t = u64
using node_t = u8
using flags_t = u64
using plugin_t = u64
using tag_t = u8
using sub_t = u8
Width to Signed/Unsigned/Float
template<int w>
using w2u = typename detail::w2u_<w>::type
template<int w>
using w2s = typename detail::w2s_<w>::type
template<int w>
using w2f = typename detail::w2f_<w>::type
GID
template<class K, class V>
using GIDMap = absl::flat_hash_map<K, V, GIDHash<K>>
template<class K>
using GIDSet = absl::flat_hash_set<K, GIDHash<K>>
template<class K, class V>
using GIDNodeMap = absl::node_hash_map<K, V, GIDHash<K>>
template<class K>
using GIDNodeSet = absl::node_hash_set<K, GIDHash<K>>
Functions
int commute_ (const Def *a, const Def *b)
bool commute (const Def *a, const Def *b)
Swap Lit to left - or smaller Def::gid, if no lit present.
void optimize (World &)
template<size_t I, class T, size_t N>
requires (N != std::dynamic_extent)
constexpr decltype(auto) get (Span< T, N > span) noexcept
std::ostream & operator<< (std::ostream &os, const Def *def)
This will stream def as an operand.
static void post_order (const Nest &nest, const Nest::Node *node, Scheduler::Schedule &res, MutSet &done)
is_commutative/is_associative
template<class Id>
constexpr bool is_commutative (Id)
template<class Id>
constexpr bool is_associative (Id id)
constexpr bool is_commutative (plug::core::nat id)
constexpr bool is_commutative (plug::core::ncmp id)
constexpr bool is_commutative (plug::core::wrap id)
constexpr bool is_commutative (plug::core::icmp id)
constexpr bool is_commutative (plug::core::bit2 id)
constexpr bool is_associative (plug::core::bit2 id)
constexpr bool is_associative (plug::core::nat id)
constexpr bool is_associative (plug::core::ncmp id)
constexpr bool is_associative (plug::core::icmp id)
constexpr bool is_associative (plug::core::wrap id)
constexpr bool is_commutative (plug::math::extrema)
constexpr bool is_commutative (plug::math::arith id)
constexpr bool is_commutative (plug::math::cmp id)
constexpr bool is_associative (plug::math::arith id)
Helpers to work with Functions
const App * isa_callee (const Def *def, size_t i)
Lam * isa_workable (Lam *lam)
These are Lams that are neither nullptr, nor Lam::is_external, nor Lam::is_unset.
std::pair< const App *, Lam * > isa_apped_mut_lam (const Def *def)
std::deque< const App * > decurry (const Def *)
Yields curried Apps in a flat std::deque<const App*>.
const Def * compose_cn (const Def *f, const Def *g)
The high level view is:
std::pair< const Def *, DefVec > collect_args (const Def *def)
Helper function to cope with the fact that normalizers take all arguments and not only its axm arguments.
Register Pass/Phase
template<class A, class P, class... CArgs>
void register_pass (Passes &passes, CArgs &&... args)
template<class A, class P, class... CArgs>
void register_phase (Passes &passes, CArgs &&... args)
template<class A, class P, class Q>
void register_pass_with_arg (Passes &passes)
Helpers to work with Tulpes/Sigmas/Arrays/Packs
bool is_unit (const Def *)
std::string tuple2str (const Def *)
const Def * flatten (const Def *def)
Flattens a sigma/array/pack/tuple.
size_t flatten (DefVec &ops, const Def *def, bool flatten_sigmas=true)
Same as unflatten, but uses the operands of a flattened Pack / Tuple directly.
const Def * unflatten (const Def *def, const Def *type)
Applies the reverse transformation on a Pack / Tuple, given the original type.
const Def * unflatten (Defs ops, const Def *type, bool flatten_muts=true)
Same as unflatten, but uses the operands of a flattened Pack / Tuple directly.
DefVec merge (Defs, Defs)
DefVec merge (const Def *def, Defs defs)
const Def * merge_sigma (const Def *def, Defs defs)
const Def * merge_tuple (const Def *def, Defs defs)
const Def * tuple_of_types (const Def *t)
Formatted Output
Provides a printf-like interface to format s with args and puts it into os.
Use {} as a placeholder within your format string s.
By default, os << t will be used to stream the appropriate argument:
print(os, "int: {}, float: {}", 23, 42.f);
You can also place a function as argument to inject arbitrary code:
print(os, "int: {}, fun: {}, float: {}", 23, [&]() { os << "hey :)"}, 42.f);
There is also a variant to pass os to the function, if you don't have easy access to it:
print(os, "int: {}, fun: {}, float: {}", 23, [&](auto& os) { os << "hey :)"}, 42.f);
You can put a std::ranges::range as argument. This will output a list - using the given specifier as separator. Each element elem of the range will be output via os << elem:
std::vector<int> v = {0, 1, 2, 3};
print(os, "v: {, }", v);
If you have a std::ranges::range that needs to be formatted in a more complicated way, bundle it with an Elem:
std::vector<int> v = {3, 2, 1, 0};
size_t i = 0;
print(os, "v: {, }", Elem(v, [&](auto elem) { print(os, "{}: {}", i++, elem); }));
You again have the option to pass os to the bundled function:
std::vector<int> v = {3, 2, 1, 0};
size_t i = 0;
print(os, "v: {, }", Elem(v, [&](auto& os, auto elem) { print(os, "{}: {}", i++, elem); }));
* Use `{{` or `}}` to literally output `{` or `{`:
print(os, "{{{}}}", 23); // "{23}"
See also
Tab
template<class... Args>
void error (Loc loc, const char *f, Args &&... args)
std::ostream & print (std::ostream &os, const char *s)
Base case.
template<class T, class... Args>
std::ostream & print (std::ostream &os, const char *s, T &&t, Args &&... args)
template<class... Args>
std::ostream & println (std::ostream &os, const char *fmt, Args &&... args)
As above but end with std::endl.
template<class... Args>
std::string fmt (const char *s, Args &&... args)
Wraps mim::print to output a formatted std:string.
template<class T = std::logic_error, class... Args>
void error (const char *fmt, Args &&... args)
Wraps mim::print to throw T with a formatted message.
Simple Hash
See Wikipedia.
constexpr uint32_t murmur3 (uint32_t h) noexcept
constexpr uint64_t splitmix64 (uint64_t h) noexcept
constexpr size_t hash (size_t h) noexcept
FNV-1 Hash
See Wikipedia.
template<class T>
constexpr size_t hash_combine (size_t seed, T v) noexcept
consteval size_t hash_begin () noexcept
template<class T>
constexpr size_t hash_begin (T val) noexcept
IndexMap find
template<class Indexer, class Key, class Value>
Value * find (IndexMap< Indexer, Key, Value * > &map, Key key)
template<class Indexer, class Key, class Value>
const Value * find (const IndexMap< Indexer, Key, Value * > &map, Key key)
IndexSet visit
template<class Indexer, class Key>
bool visit (IndexSet< Indexer, Key > &set, const Key &key)
template<class Indexer, class Key>
void visit_first (IndexSet< Indexer, Key > &set, const Key &key)
out/err
mim::prints to std::cout/std::cerr; the *ln variants emit an additional std::endl.
template<class... Args>
std::ostream & outf (const char *fmt, Args &&... args)
template<class... Args>
std::ostream & errf (const char *fmt, Args &&... args)
template<class... Args>
std::ostream & outln (const char *fmt, Args &&... args)
template<class... Args>
std::ostream & errln (const char *fmt, Args &&... args)
Deduction Guides
template<class I, class E>
Span (I, E) -> Span< std::remove_reference_t< std::iter_reference_t< I > > >
template<class T, size_t N>
Span (T(&)[N]) -> Span< T, N >
template<class T, size_t N>
Span (std::array< T, N > &) -> Span< T, N >
template<class T, size_t N>
Span (const std::array< T, N > &) -> Span< const T, N >
template<class R>
Span (R &&) -> Span< std::remove_reference_t< std::ranges::range_reference_t< R > > >
template<Vectorlike Vec>
Span (Vec &) -> Span< typename Vec::value_type, std::dynamic_extent >
template<Vectorlike Vec>
Span (const Vec &) -> Span< const typename Vec::value_type, std::dynamic_extent >
template<class I, class A = std::allocator<typename std::iterator_traits<I>::value_type>>
Vector (I, I, A=A()) -> Vector< typename std::iterator_traits< I >::value_type, Default_Inlined_Size< typename std::iterator_traits< I >::value_type >, A >
User-Defined Literals
constexpr s8 operator""_s8 (unsigned long long int s)
constexpr u8 operator""_u8 (unsigned long long int u)
constexpr s16 operator""_s16 (unsigned long long int s)
constexpr u16 operator""_u16 (unsigned long long int u)
constexpr s32 operator""_s32 (unsigned long long int s)
constexpr u32 operator""_u32 (unsigned long long int u)
constexpr s64 operator""_s64 (unsigned long long int s)
constexpr u64 operator""_u64 (unsigned long long int u)
constexpr size_t operator""_s (unsigned long long int i)
A size_t literal. Use 0_s to disambiguate 0 from nullptr.
constexpr nat_t operator""_n (unsigned long long int i)
f16 operator""_f16 (long double d)
constexpr f32 operator""_f32 (long double d)
constexpr f64 operator""_f64 (long double d)
rem
half rem (half a, half b)
float rem (float a, float b)
double rem (double a, double b)
long double rem (long double a, long double b)
Utility Functions
template<class D, class S>
D bitcast (const S &src)
A bitcast from src of type S to D.
template<class T>
bool get_sign (T val)
u64 pad (u64 offset, u64 align)
Algorithms
template<class I, class T, class L>
I binary_find (I begin, I end, T val, L lt)
std::string_view subview (std::string_view s, size_t i, size_t n=std::string_view::npos)
Like std::string::substr, but works on std::string_view instead.
void find_and_replace (std::string &str, std::string_view what, std::string_view repl)
Replaces all occurrences of what with repl.
Helpers for Containers
template<class S>
auto pop (S &s) -> decltype(s.top(), typename S::value_type())
template<class Q>
auto pop (Q &q) -> decltype(q.front(), typename Q::value_type())
template<class C, class K>
auto lookup (const C &container, const K &key)
Yields pointer to element (or the element itself if it is already a pointer), if found and nullptr otherwise.
template<class C, class... Args>
auto assert_emplace (C &container, Args &&... args)
Invokes emplace on container, asserts that insertion actually happened, and returns the iterator.
erase
template<class T, size_t N, class A, class U>
Vector< T, N, A >::size_type erase (Vector< T, N, A > &c, const U &value) noexcept
template<class T, size_t N, class A, class Pred>
Vector< T, N, A >::size_type erase_if (Vector< T, N, A > &c, Pred pred) noexcept
Variables
template<class T>
static constexpr size_t Default_Inlined_Size = std::max((size_t)1, 4 * sizeof(size_t) / sizeof(T))
Use up to 4 words (i.e., 4 * sizeof(size_t)) of inlined storage, rounded up.
Enums that classify certain aspects of Defs.
enum class Node : node_t {
CODE ,
Lit ,
Axm ,
Var ,
Global ,
Proxy ,
Hole ,
Type ,
Univ ,
UMax ,
UInc ,
Pi ,
Lam ,
App ,
Sigma ,
Tuple ,
Extract ,
Insert ,
Arr ,
Pack ,
Join ,
Inj ,
Match ,
Top ,
Meet ,
Merge ,
Split ,
Bot ,
Uniq ,
Nat ,
Idx
}
enum class Sort {
Term ,
Type ,
Kind ,
Space ,
Univ ,
Level
}
TODO remove or fix this.
enum class Dep : unsigned {
None = 0 ,
Mut = 1 << 0 ,
Var = 1 << 1 ,
Hole = 1 << 2 ,
Proxy = 1 << 3
}
Tracks a dependency to certain Defs transitively through the Def::deps() up to but excliding mutables.
enum class Judge : u32 {
Form = 1 << 0 ,
Intro = 1 << 1 ,
Elim = 1 << 2 ,
Meta = 1 << 3 ,
Hole = 1 << 4
}
Judgement.
static constexpr size_t Num_Nodes = size_t(0) +size_t(1) +size_t(1) +size_t(1) +size_t(1) +size_t(1) +size_t(1) +size_t(1) +size_t(1) +size_t(1) +size_t(1) +size_t(1) +size_t(1) +size_t(1) +size_t(1) +size_t(1) +size_t(1) +size_t(1) +size_t(1) +size_t(1) +size_t(1) +size_t(1) +size_t(1) +size_t(1) +size_t(1) +size_t(1) +size_t(1) +size_t(1) +size_t(1) +size_t(1) +size_t(1)
Undo
Used by FPPass::analyze to indicate where to backtrack to.
using undo_t = size_t
static constexpr undo_t No_Undo = std::numeric_limits<undo_t>::max()
Plugin Interface
See also
Plugin
using Normalizers = absl::flat_hash_map<flags_t, NormalizeFn>
using Passes = absl::flat_hash_map<flags_t, std::function<void(World&, PipelineBuilder&, const Def*)>>
axm ↦ (pipeline part) × (axm application) → ()
The function should inspect Application to construct the Pass/Phase and add it to the pipeline.
using Backends = absl::btree_map<std::string, void (*)(World&, std::ostream&)>
mim::Plugin mim_get_plugin ()
Class Documentation
mim::Flags
struct mim::Flags
Compiler switches that must be saved and looked up in later phases of compilation.
See also
Command-Line Reference
Definition at line 11 of file flags.h.
Class Members
bool aggressive_lam_spec = false
bool ascii = false
bool bootstrap = false
bool break_on_alpha = false
bool break_on_error = false
bool break_on_warn = false
bool disable_type_checking = false
uint32_t dump_gid = 0
bool dump_recursive = false
bool reeval_breakpoints = false
uint64_t scalarize_threshold = 32
bool trace_gids = false
mim::FNV1
struct mim::FNV1
template<size_t>
struct mim::FNV1< size_t >
Magic numbers for FNV-1 hash.
Definition at line 46 of file hash.h.
Typedef Documentation
Backends
using mim::Backends = absl::btree_map<std::string, void (*)(World&, std::ostream&)>
Definition at line 23 of file plugin.h.
Bot
using mim::Bot = TExt<false>
Definition at line 158 of file lattice.h.
Def2Def
using mim::Def2Def = DefMap<const Def*>
Definition at line 48 of file def.h.
DefMap
template<class To> using mim::DefMap = GIDMap<const Def*, To>
Definition at line 46 of file def.h.
Defs
using mim::Defs = View<const Def*>
Definition at line 49 of file def.h.
DefSet
using mim::DefSet = GIDSet<const Def*>
Definition at line 47 of file def.h.
DefVec
using mim::DefVec = Vector<const Def*>
Definition at line 50 of file def.h.
f16
using mim::f16 = half
Definition at line 39 of file types.h.
f32
using mim::f32 = float
Definition at line 40 of file types.h.
f64
using mim::f64 = double
Definition at line 41 of file types.h.
flags_t
using mim::flags_t = u64
Definition at line 45 of file types.h.
GIDMap
template<class K, class V> using mim::GIDMap = absl::flat_hash_map<K, V, GIDHash<K>>
Definition at line 176 of file util.h.
GIDNodeMap
template<class K, class V> using mim::GIDNodeMap = absl::node_hash_map<K, V, GIDHash<K>>
Definition at line 178 of file util.h.
GIDNodeSet
template<class K> using mim::GIDNodeSet = absl::node_hash_set<K, GIDHash<K>>
Definition at line 179 of file util.h.
GIDSet
template<class K> using mim::GIDSet = absl::flat_hash_set<K, GIDHash<K>>
Definition at line 177 of file util.h.
Join
using mim::Join = TBound<true>
AKA union.
Definition at line 161 of file lattice.h.
Lam2Lam
using mim::Lam2Lam = LamMap<Lam*>
Definition at line 204 of file lam.h.
LamMap
template<class To> using mim::LamMap = GIDMap<Lam*, To>
Definition at line 202 of file lam.h.
LamSet
using mim::LamSet = GIDSet<Lam*>
Definition at line 203 of file lam.h.
level_t
using mim::level_t = u64
Definition at line 42 of file types.h.
Meet
using mim::Meet = TBound<false>
AKA intersection.
Definition at line 160 of file lattice.h.
Mut2Mut
using mim::Mut2Mut = MutMap<Def*>
Definition at line 58 of file def.h.
MutMap
template<class To> using mim::MutMap = GIDMap<Def*, To>
Definition at line 56 of file def.h.
Muts
using mim::Muts = Sets<Def>::Set
Definition at line 59 of file def.h.
MutSet
using mim::MutSet = GIDSet<Def*>
Definition at line 57 of file def.h.
nat_t
using mim::nat_t = u64
Definition at line 43 of file types.h.
node_t
using mim::node_t = u8
Definition at line 44 of file types.h.
NormalizeFn
using mim::NormalizeFn = const Def* (*)(const Def*, const Def*, const Def*)
Definition at line 71 of file def.h.
Normalizers
using mim::Normalizers = absl::flat_hash_map<flags_t, NormalizeFn>
Definition at line 19 of file plugin.h.
Passes
using mim::Passes = absl::flat_hash_map<flags_t, std::function<void(World&, PipelineBuilder&, const Def*)>>
axm ↦ (pipeline part) × (axm application) → ()
The function should inspect Application to construct the Pass/Phase and add it to the pipeline.
Definition at line 22 of file plugin.h.
plugin_t
using mim::plugin_t = u64
Definition at line 46 of file types.h.
s16
using mim::s16 = int16_t
Definition at line 34 of file types.h.
s32
using mim::s32 = int32_t
Definition at line 34 of file types.h.
s64
using mim::s64 = int64_t
Definition at line 34 of file types.h.
s8
using mim::s8 = int8_t
Definition at line 34 of file types.h.
sub_t
using mim::sub_t = u8
Definition at line 48 of file types.h.
tag_t
using mim::tag_t = u8
Definition at line 47 of file types.h.
Top
using mim::Top = TExt<true>
Definition at line 159 of file lattice.h.
u1
using mim::u1 = bool
Definition at line 38 of file types.h.
u16
using mim::u16 = uint16_t
Definition at line 34 of file types.h.
u32
using mim::u32 = uint32_t
Definition at line 34 of file types.h.
u64
using mim::u64 = uint64_t
Definition at line 34 of file types.h.
u8
using mim::u8 = uint8_t
Definition at line 34 of file types.h.
undo_t
using mim::undo_t = size_t
Definition at line 14 of file pass.h.
Uses
using mim::Uses = absl::flat_hash_set<Use, UseHash, UseEq>
Definition at line 42 of file schedule.h.
Var2Var
using mim::Var2Var = VarMap<const Var*>
Definition at line 67 of file def.h.
VarMap
template<class To> using mim::VarMap = GIDMap<const Var*, To>
Definition at line 65 of file def.h.
Vars
using mim::Vars = Sets<const Var>::Set
Definition at line 68 of file def.h.
VarSet
using mim::VarSet = GIDSet<const Var*>
Definition at line 66 of file def.h.
View
template<class T, size_t N = std::dynamic_extent> using mim::View = Span<const T, N>
Definition at line 93 of file span.h.
w2f
template<int w> using mim::w2f = typename detail::w2f_<w>::type
Definition at line 74 of file types.h.
w2s
template<int w> using mim::w2s = typename detail::w2s_<w>::type
Definition at line 73 of file types.h.
w2u
template<int w> using mim::w2u = typename detail::w2u_<w>::type
Definition at line 72 of file types.h.
Enumeration Type Documentation
Dep
enum class mim::Dep : unsigned strong
Tracks a dependency to certain Defs transitively through the Def::deps() up to but excliding mutables.
Enumerator
None
Mut
Var
Hole
Proxy
Definition at line 97 of file def.h.
Judge
enum class mim::Judge : u32 strong
Judgement.
Enumerator
Form
Type Formation like T -> T.
Intro
Term Introduction like λ(x: Nat): Nat = x.
Elim
Term Elimination like f a.
Meta
Meta rules for Universe and Type levels.
Hole
Special rule for Hole.
Definition at line 106 of file def.h.
Node
enum class mim::Node : node_t strong
Enumerator
CODE
Lit
Axm
Var
Global
Proxy
Hole
Type
Univ
UMax
UInc
Pi
Lam
App
Sigma
Tuple
Extract
Insert
Arr
Pack
Join
Inj
Match
Top
Meet
Merge
Split
Bot
Uniq
Nat
Idx
Definition at line 83 of file def.h.
Sort
enum class mim::Sort strong
TODO remove or fix this.
Enumerator
Term
Type
Kind
Space
Univ
Level
Definition at line 94 of file def.h.
Function Documentation
assert_emplace()
template<class C, class... Args> auto mim::assert_emplace (C & container, Args &&... args)
Invokes emplace on container, asserts that insertion actually happened, and returns the iterator.
Definition at line 103 of file util.h.
Referenced by mim::World::app(), mim::Driver::load(), mim::World::make_external(), mim_get_plugin(), mim::World::reduce(), mim::World::register_annex(), register_pass(), register_pass_with_arg(), register_phase(), and mim::Scheduler::Scheduler().
binary_find()
template<class I, class T, class L> I mim::binary_find (I begin, I end, T val, L lt)
Definition at line 54 of file util.h.
Referenced by mim::Bound::find().
bitcast()
template<class D, class S> D mim::bitcast (const S & src) inline
A bitcast from src of type S to D.
Definition at line 22 of file util.h.
Referenced by mim::ll::Emitter::emit_bb(), mim::Lit::get(), mim::plug::math::lit_f(), and mim::Res::Res().
collect_args()
std::pair< const Def *, DefVec > mim::collect_args (const Def * def)
Helper function to cope with the fact that normalizers take all arguments and not only its axm arguments.
Definition at line 82 of file lam.cpp.
References collect_args().
Referenced by collect_args(), mim::plug::compile::handle_optimization_part(), mim_get_plugin(), mim::plug::compile::normalize_combine_pass_list(), mim::plug::compile::normalize_combined_phase(), mim::plug::compile::normalize_pass_phase(), and optimize().
commute()
bool mim::commute (const Def * a, const Def * b) inline nodiscard
Swap Lit to left - or smaller Def::gid, if no lit present.
Definition at line 27 of file normalize.h.
References commute_().
Referenced by mim::plug::core::normalize_bit2(), mim::plug::core::normalize_nat(), and mim::plug::core::normalize_ncmp().
commute_()
int mim::commute_ (const Def * a, const Def * b) nodiscard
Definition at line 9 of file normalize.cpp.
References commute_(), mim::Def::flags(), mim::Def::gid(), mim::Def::isa_imm(), mim::Def::isa_mut(), mim::Def::node(), mim::Def::num_ops(), and mim::Def::op().
Referenced by commute(), and commute_().
compose_cn()
const Def * mim::compose_cn (const Def * f, const Def * g)
The high level view is:
f: B -> C
g: A -> B
f o g := λ x. f(g(x)) : A -> C
In CPS the types look like:
f:  Cn[B, Cn C]
g:  Cn[A, Cn B]
h = f o g
h:  Cn[A, cn C]
h = λ (a ret_h) = g (a, h')
h': Cn B
h'= λ b = f (b, ret_h)
Definition at line 49 of file lam.cpp.
References mim::Pi::dom(), mim::Pi::isa_returning(), and mim::Pi::ret_dom().
Referenced by mim::plug::autodiff::AutoDiffEval::augment_app().
decurry()
std::deque< const App * > mim::decurry (const Def * def)
Yields curried Apps in a flat std::deque<const App*>.
Definition at line 40 of file lam.cpp.
Referenced by mim::plug::tuple::normalize_cat().
erase()
template<class T, size_t N, class A, class U> Vector< T, N, A >::size_type mim::erase (Vector< T, N, A > & c, const U & value) noexcept
Definition at line 67 of file vector.h.
Referenced by mim::plug::regex::normalize_disj().
erase_if()
template<class T, size_t N, class A, class Pred> Vector< T, N, A >::size_type mim::erase_if (Vector< T, N, A > & c, Pred pred) noexcept
Definition at line 75 of file vector.h.
errf()
template<class... Args> std::ostream & mim::errf (const char * fmt, Args &&... args)
Definition at line 189 of file print.h.
References fmt(), and print().
Referenced by errln().
errln()
template<class... Args> std::ostream & mim::errln (const char * fmt, Args &&... args)
Definition at line 191 of file print.h.
References errf(), and fmt().
Referenced by main().
error() [1/2]
template<class T = std::logic_error, class... Args> void mim::error (const char * fmt, Args &&... args)
Wraps mim::print to throw T with a formatted message.
Definition at line 163 of file print.h.
References fmt(), and print().
error() [2/2]
template<class... Args> void mim::error (Loc loc, const char * f, Args &&... args)
Single Error that throws immediately.
Definition at line 122 of file dbg.h.
References error(), and fmt().
Referenced by mim::World::annex(), mim::World::arr(), mim::Arr::check(), mim::Pi::check(), mim::dl::close(), mim::ll::compile_and_run(), dfa2matcher(), mim::ast::AxmDecl::emit(), mim::ast::ExtractExpr::emit_(), mim::ast::RetExpr::emit_(), mim::ll::Emitter::emit_bb(), error(), mim::sys::exec(), mim::World::extract(), mim::dl::get(), mim::World::insert(), mim::World::lit(), mim::Driver::load(), main(), mim::World::match(), mim::plug::refly::normalize_equiv(), mim::dl::open(), optimize(), mim::World::pack(), mim::World::tuple(), mim::World::type(), mim::World::uinc(), and mim::World::umax().
find() [1/2]
template<class Indexer, class Key, class Value> const Value * mim::find (const IndexMap< Indexer, Key, Value * > & map, Key key) inline
Definition at line 73 of file indexmap.h.
References find().
find() [2/2]
template<class Indexer, class Key, class Value> Value * mim::find (IndexMap< Indexer, Key, Value * > & map, Key key) inline
Definition at line 67 of file indexmap.h.
Referenced by find().
find_and_replace()
void mim::find_and_replace (std::string & str, std::string_view what, std::string_view repl) inline
Replaces all occurrences of what with repl.
Definition at line 71 of file util.h.
Referenced by mim::plug::autodiff::AutoDiffEval::augment_().
flatten() [1/2]
const Def * mim::flatten (const Def * def)
Flattens a sigma/array/pack/tuple.
Definition at line 87 of file tuple.cpp.
References flatten(), mim::Def::is_intro(), mim::World::sigma(), mim::World::tuple(), mim::Def::type(), and mim::Def::world().
Referenced by flatten(), flatten(), and mim::Scalarize::rewrite().
flatten() [2/2]
size_t mim::flatten (DefVec & ops, const Def * def, bool flatten_sigmas = true)
Same as unflatten, but uses the operands of a flattened Pack / Tuple directly.
Definition at line 76 of file tuple.cpp.
References flatten(), mim::Def::isa_lit_arity(), and mim::Def::proj().
fmt()
template<class... Args> std::string mim::fmt (const char * s, Args &&... args)
Wraps mim::print to output a formatted std:string.
Definition at line 156 of file print.h.
References print().
Referenced by mim::ll::compile(), errf(), errln(), mim::ast::AST::error(), error(), error(), mim::Log::log(), mim::Log::log(), mim::Error::msg(), mim::ast::AST::note(), outf(), outln(), println(), and mim::ast::AST::warn().
get()
template<size_t I, class T, size_t N> requires (N != std::dynamic_extent) decltype(auto) mim::get (Span< T, N > span) constexpr noexcept
Definition at line 107 of file span.h.
Referenced by mim::ast::ExtractExpr::emit_(), mim_get_plugin(), mim::Lit::rebuild_(), mim::plug::matrix::LowerMatrixMediumLevel::rewrite_(), and mim::plug::matrix::LowerMatrixLowLevel::rewrite_imm().
get_sign()
template<class T> bool mim::get_sign (T val)
Definition at line 36 of file util.h.
hash()
size_t mim::hash (size_t h) inline constexpr noexcept
Definition at line 32 of file hash.h.
References murmur3(), and splitmix64().
Referenced by mim::Def::Def(), mim::GIDHash< T >::operator()(), and mim::UseHash::operator()().
hash_begin() [1/2]
size_t mim::hash_begin () inline consteval noexcept
Definition at line 71 of file hash.h.
Referenced by mim::Def::Def(), hash_begin(), and mim::UseHash::operator()().
hash_begin() [2/2]
template<class T> size_t mim::hash_begin (T val) constexpr noexcept
Definition at line 73 of file hash.h.
References hash_begin(), and hash_combine().
hash_combine()
template<class T> size_t mim::hash_combine (size_t seed, T v) constexpr noexcept
Definition at line 58 of file hash.h.
Referenced by hash_begin(), and mim::UseHash::operator()().
is_associative() [1/7]
template<class Id> bool mim::is_associative (Id id) constexpr
Warning
By default we assume that any commutative operation is also associative. Please provide a proper specialization if this is not the case.
Definition at line 149 of file axm.h.
References is_commutative().
is_associative() [2/7]
bool mim::is_associative (plug::core::bit2 id) constexpr
Definition at line 107 of file core.h.
References mim::plug::core::and_, mim::plug::core::f, mim::plug::core::fst, mim::plug::core::nxor, mim::plug::core::or_, mim::plug::core::snd, mim::plug::core::t, and mim::plug::core::xor_.
is_associative() [3/7]
bool mim::is_associative (plug::core::icmp id) constexpr
Definition at line 124 of file core.h.
References is_commutative().
is_associative() [4/7]
bool mim::is_associative (plug::core::nat id) constexpr
Definition at line 122 of file core.h.
References is_commutative().
is_associative() [5/7]
bool mim::is_associative (plug::core::ncmp id) constexpr
Definition at line 123 of file core.h.
References is_commutative().
is_associative() [6/7]
bool mim::is_associative (plug::core::wrap id) constexpr
Definition at line 125 of file core.h.
References is_commutative().
is_associative() [7/7]
bool mim::is_associative (plug::math::arith id) constexpr
Definition at line 128 of file math.h.
References is_commutative().
is_commutative() [1/9]
template<class Id> bool mim::is_commutative (Id) constexpr
Definition at line 146 of file axm.h.
Referenced by is_associative(), is_associative(), is_associative(), is_associative(), is_associative(), is_associative(), mim::plug::core::normalize_bit2(), mim::plug::core::normalize_nat(), and mim::plug::core::normalize_ncmp().
is_commutative() [2/9]
bool mim::is_commutative (plug::core::bit2 id) constexpr
Definition at line 102 of file core.h.
is_commutative() [3/9]
bool mim::is_commutative (plug::core::icmp id) constexpr
Definition at line 99 of file core.h.
References mim::plug::core::ne.
is_commutative() [4/9]
bool mim::is_commutative (plug::core::nat id) constexpr
Definition at line 96 of file core.h.
is_commutative() [5/9]
bool mim::is_commutative (plug::core::ncmp id) constexpr
Definition at line 97 of file core.h.
References mim::plug::core::ne.
is_commutative() [6/9]
bool mim::is_commutative (plug::core::wrap id) constexpr
Definition at line 98 of file core.h.
References mim::plug::core::add, and mim::plug::core::mul.
is_commutative() [7/9]
bool mim::is_commutative (plug::math::arith id) constexpr
Definition at line 126 of file math.h.
References mim::plug::math::add, and mim::plug::math::mul.
is_commutative() [8/9]
bool mim::is_commutative (plug::math::cmp id) constexpr
Definition at line 127 of file math.h.
is_commutative() [9/9]
bool mim::is_commutative (plug::math::extrema) constexpr
Definition at line 125 of file math.h.
is_unit()
bool mim::is_unit (const Def * def)
Definition at line 54 of file tuple.cpp.
References mim::World::sigma(), mim::Def::type(), and mim::Def::world().
isa_apped_mut_lam()
std::pair< const App *, Lam * > mim::isa_apped_mut_lam (const Def * def) inline
Definition at line 259 of file lam.h.
Referenced by mim::TailRecElim::analyze(), mim::BetaRed::rewrite(), mim::LamSpec::rewrite(), mim::plug::mem::CopyProp::rewrite(), mim::plug::mem::SSAConstr::rewrite(), and mim::TailRecElim::rewrite().
isa_callee()
const App * mim::isa_callee (const Def * def, size_t i) inline
Definition at line 251 of file lam.h.
Referenced by mim::EtaExp::analyze(), mim::plug::mem::SSAConstr::analyze(), mim::EtaExp::rewrite(), and mim::EtaRed::rewrite().
isa_workable()
Lam * mim::isa_workable (Lam * lam) inline
These are Lams that are neither nullptr, nor Lam::is_external, nor Lam::is_unset.
Definition at line 254 of file lam.h.
References mim::Def::is_external(), and mim::Def::is_set().
Referenced by mim::BetaRed::analyze(), mim::plug::mem::SSAConstr::analyze(), mim::BetaRed::rewrite(), mim::LamSpec::rewrite(), mim::plug::mem::CopyProp::rewrite(), and mim::plug::mem::SSAConstr::rewrite().
lookup()
template<class C, class K> auto mim::lookup (const C & container, const K & key)
Yields pointer to element (or the element itself if it is already a pointer), if found and nullptr otherwise.
Warning
If the element is not already a pointer, this lookup will simply take the address of this element. This means that, e.g., a rehash of an absl::flat_hash_map will invalidate this pointer.
Definition at line 94 of file util.h.
Referenced by mim::Driver::backend(), mim::World::external(), mim::Driver::get_fun_ptr(), mim::Driver::is_loaded(), mim::EtaExp::new2old(), mim::Driver::normalizer(), mim::Driver::pass(), and mim::EtaExp::rewrite().
merge() [1/2]
DefVec mim::merge (const Def * def, Defs defs)
Definition at line 103 of file tuple.cpp.
merge() [2/2]
DefVec mim::merge (Defs a, Defs b)
Definition at line 107 of file tuple.cpp.
Referenced by merge_sigma(), and merge_tuple().
merge_sigma()
const Def * mim::merge_sigma (const Def * def, Defs defs)
Definition at line 114 of file tuple.cpp.
References mim::Def::isa_imm(), merge(), mim::World::sigma(), and mim::Def::world().
merge_tuple()
const Def * mim::merge_tuple (const Def * def, Defs defs)
Definition at line 119 of file tuple.cpp.
References mim::Def::isa_imm(), merge(), mim::World::tuple(), mim::Def::type(), and mim::Def::world().
mim_get_plugin()
mim::Plugin mim::mim_get_plugin ()
To be implemented and exported by a plugin.
Returns
a filled Plugin.
References MIM_EXPORT.
Referenced by mim::Driver::load().
murmur3()
uint32_t mim::murmur3 (uint32_t h) inline constexpr noexcept
Use for a single value to hash.
Definition at line 14 of file hash.h.
Referenced by hash().
operator""_f16()
f16 mim::operator""_f16 (long double d) inline
Definition at line 88 of file types.h.
operator""_f32()
f32 mim::operator""_f32 (long double d) constexpr
Definition at line 89 of file types.h.
operator""_f64()
f64 mim::operator""_f64 (long double d) constexpr
Definition at line 90 of file types.h.
operator""_n()
nat_t mim::operator""_n (unsigned long long int i) constexpr
Definition at line 87 of file types.h.
operator""_s()
size_t mim::operator""_s (unsigned long long int i) constexpr
A size_t literal. Use 0_s to disambiguate 0 from nullptr.
Definition at line 86 of file types.h.
operator""_s16()
s16 mim::operator""_s16 (unsigned long long int s) constexpr
Definition at line 82 of file types.h.
References CODE4.
operator""_s32()
s32 mim::operator""_s32 (unsigned long long int s) constexpr
Definition at line 82 of file types.h.
operator""_s64()
s64 mim::operator""_s64 (unsigned long long int s) constexpr
Definition at line 82 of file types.h.
operator""_s8()
s8 mim::operator""_s8 (unsigned long long int s) constexpr
Definition at line 82 of file types.h.
operator""_u16()
u16 mim::operator""_u16 (unsigned long long int u) constexpr
Definition at line 82 of file types.h.
operator""_u32()
u32 mim::operator""_u32 (unsigned long long int u) constexpr
Definition at line 82 of file types.h.
operator""_u64()
u64 mim::operator""_u64 (unsigned long long int u) constexpr
Definition at line 82 of file types.h.
operator""_u8()
u8 mim::operator""_u8 (unsigned long long int u) constexpr
Definition at line 82 of file types.h.
operator<<()
std::ostream & mim::operator<< (std::ostream & os, const Def * def)
This will stream def as an operand.
This is usually id(def) unless it can be displayed Inline.
Definition at line 419 of file dump.cpp.
optimize()
void mim::optimize (World & world)
Definition at line 10 of file optimize.cpp.
References collect_args(), mim::World::copy_externals(), mim::World::driver(), error(), mim::World::external(), mim::Def::flags(), mim::Def::make_internal(), mim::Driver::pass(), mim::PipelineBuilder::run_pipeline(), mim::World::sym(), and mim::Def::type().
Referenced by main().
outf()
template<class... Args> std::ostream & mim::outf (const char * fmt, Args &&... args)
Definition at line 188 of file print.h.
References fmt(), and print().
Referenced by outln().
outln()
template<class... Args> std::ostream & mim::outln (const char * fmt, Args &&... args)
Definition at line 190 of file print.h.
References fmt(), and outf().
pad()
u64 mim::pad (u64 offset, u64 align) inline
Definition at line 45 of file util.h.
Referenced by mim::plug::core::normalize_trait().
pop() [1/2]
template<class Q> auto mim::pop (Q & q) -> decltype(q.front(), typename Q::value_type())
Definition at line 85 of file util.h.
pop() [2/2]
template<class S> auto mim::pop (S & s) -> decltype(s.top(), typename S::value_type())
Definition at line 79 of file util.h.
Referenced by mim::plug::clos::free_defs(), mim::unique_queue< Set >::pop(), mim::unique_stack< Set >::pop(), and mim::PassMan::run().
post_order()
static void mim::post_order (const Nest & nest, const Nest::Node * node, Scheduler::Schedule & res, MutSet & done) static
Definition at line 105 of file schedule.cpp.
References mim::Def::deps(), mim::Def::local_muts(), mim::Nest::Node::mut(), mim::Nest::mut2node(), and post_order().
Referenced by post_order(), and mim::Scheduler::schedule().
print() [1/2]
std::ostream & mim::print (std::ostream & os, const char * s)
Base case.
Definition at line 5 of file print.cpp.
Referenced by mim::Error::ack(), mim::ll::BB::assign(), mim::ast::AST::bootstrap(), mim::ll::Emitter::declare(), mim::World::dump(), mim::ll::Emitter::emit_bb(), mim::ll::Emitter::emit_epilogue(), mim::ll::Emitter::emit_imported(), errf(), error(), mim::ll::Emitter::finalize(), fmt(), mim::Log::log(), mim::Error::Msg::operator<<, outf(), mim::ll::Emitter::prepare(), print(), mim::Tab::print(), println(), mim::ast::AliasPtrn::stream(), mim::ast::AppExpr::stream(), mim::ast::ArrowExpr::stream(), mim::ast::AxmDecl::stream(), mim::ast::CDecl::stream(), mim::ast::DeclExpr::stream(), mim::ast::ExtractExpr::stream(), mim::ast::IdExpr::stream(), mim::ast::IdPtrn::stream(), mim::ast::InjExpr::stream(), mim::ast::InsertExpr::stream(), mim::ast::LamDecl::Dom::stream(), mim::ast::LamDecl::stream(), mim::ast::LamExpr::stream(), mim::ast::LetDecl::stream(), mim::ast::LitExpr::stream(), mim::ast::MatchExpr::Arm::stream(), mim::ast::PiExpr::Dom::stream(), mim::ast::PiExpr::stream(), mim::ast::PrimaryExpr::stream(), mim::ast::RecDecl::stream(), mim::ast::SeqExpr::stream(), mim::ast::TupleExpr::stream(), mim::ast::TuplePtrn::stream(), mim::ast::TypeExpr::stream(), mim::ast::UnionExpr::stream(), mim::ast::UniqExpr::stream(), and mim::ll::BB::tail().
print() [2/2]
template<class T, class... Args> std::ostream & mim::print (std::ostream & os, const char * s, T && t, Args &&... args)
Definition at line 93 of file print.h.
References print().
println()
template<class... Args> std::ostream & mim::println (std::ostream & os, const char * fmt, Args &&... args)
As above but end with std::endl.
Definition at line 151 of file print.h.
References fmt(), and print().
Referenced by mim::Nest::dot(), and mim::ast::RetExpr::stream().
register_pass()
template<class A, class P, class... CArgs> void mim::register_pass (Passes & passes, CArgs &&... args)
Definition at line 47 of file pipelinebuilder.h.
References mim::PipelineBuilder::add_pass(), assert_emplace(), and mim::Annex::Base.
Referenced by mim_get_plugin().
register_pass_with_arg()
template<class A, class P, class Q> void mim::register_pass_with_arg (Passes & passes)
Definition at line 61 of file pipelinebuilder.h.
References mim::PipelineBuilder::add_pass(), mim::App::arg(), assert_emplace(), mim::Annex::Base, mim::Def::gid(), and mim::PipelineBuilder::pass().
Referenced by mim_get_plugin().
register_phase()
template<class A, class P, class... CArgs> void mim::register_phase (Passes & passes, CArgs &&... args)
Definition at line 54 of file pipelinebuilder.h.
References mim::PipelineBuilder::add_phase(), assert_emplace(), and mim::Annex::Base.
Referenced by mim_get_plugin().
rem() [1/4]
double mim::rem (double a, double b) inline
Definition at line 97 of file types.h.
rem() [2/4]
float mim::rem (float a, float b) inline
Definition at line 96 of file types.h.
rem() [3/4]
half mim::rem (half a, half b) inline
Definition at line 95 of file types.h.
Referenced by mim::BitSet::operator>>=().
rem() [4/4]
long double mim::rem (long double a, long double b) inline
Definition at line 98 of file types.h.
Span() [1/7]
template<class T, size_t N> mim::Span (const std::array< T, N > &) -> Span< const T, N >
Span() [2/7]
template<Vectorlike Vec> mim::Span (const Vec &) -> Span< const typename Vec::value_type, std::dynamic_extent >
Span() [3/7]
template<class I, class E> mim::Span (I , E) -> Span< std::remove_reference_t< std::iter_reference_t< I > > >
Span() [4/7]
template<class R> mim::Span (R &&) -> Span< std::remove_reference_t< std::ranges::range_reference_t< R > > >
Span() [5/7]
template<class T, size_t N> mim::Span (std::array< T, N > &) -> Span< T, N >
Span() [6/7]
template<class T, size_t N> mim::Span (T(&) [N]) -> Span< T, N >
Span() [7/7]
template<Vectorlike Vec> mim::Span (Vec &) -> Span< typename Vec::value_type, std::dynamic_extent >
splitmix64()
uint64_t mim::splitmix64 (uint64_t h) inline constexpr noexcept
Definition at line 23 of file hash.h.
Referenced by hash().
subview()
std::string_view mim::subview (std::string_view s, size_t i, size_t n = std::string_view::npos) inline
Like std::string::substr, but works on std::string_view instead.
Definition at line 65 of file util.h.
Referenced by mim::Annex::split().
tuple2str()
std::string mim::tuple2str (const Def * def)
Definition at line 56 of file tuple.cpp.
References mim::Def::arity(), mim::Lit::isa(), mim::Def::proj(), and mim::Def::world().
Referenced by mim::plug::refly::normalize_check().
tuple_of_types()
const Def * mim::tuple_of_types (const Def * t)
Definition at line 130 of file tuple.cpp.
Referenced by mim::plug::mem::op_lea().
unflatten() [1/2]
const Def * mim::unflatten (const Def * def, const Def * type)
Applies the reverse transformation on a Pack / Tuple, given the original type.
Definition at line 101 of file tuple.cpp.
References mim::Def::arity(), mim::Lit::as(), mim::Def::projs(), and unflatten().
Referenced by unflatten(), and unflatten().
unflatten() [2/2]
const Def * mim::unflatten (Defs ops, const Def * type, bool flatten_muts = true)
Same as unflatten, but uses the operands of a flattened Pack / Tuple directly.
Definition at line 94 of file tuple.cpp.
References unflatten().
Vector()
template<class I, class A = std::allocator<typename std::iterator_traits<I>::value_type>> mim::Vector (I , I , A = A()) -> Vector< typename std::iterator_traits< I >::value_type, Default_Inlined_Size< typename std::iterator_traits< I >::value_type >, A >
References Default_Inlined_Size.
Referenced by mim::Sets< Def >::Set< Def >::erase(), mim::Sets< Def >::Set< Def >::merge(), and mim::Def::projs().
visit()
template<class Indexer, class Key> bool mim::visit (IndexSet< Indexer, Key > & set, const Key & key)
Definition at line 95 of file indexset.h.
Referenced by visit_first().
visit_first()
template<class Indexer, class Key> void mim::visit_first (IndexSet< Indexer, Key > & set, const Key & key)
Definition at line 97 of file indexset.h.
References visit().
Variable Documentation
Default_Inlined_Size
template<class T> size_t mim::Default_Inlined_Size = std::max((size_t)1, 4 * sizeof(size_t) / sizeof(T)) static constexpr
Use up to 4 words (i.e., 4 * sizeof(size_t)) of inlined storage, rounded up.
Definition at line 10 of file vector.h.
Referenced by Vector().
No_Undo
undo_t mim::No_Undo = std::numeric_limits<undo_t>::max() static constexpr
Definition at line 15 of file pass.h.
Referenced by mim::BetaRed::analyze(), mim::BetaRed::analyze(), mim::EtaExp::analyze(), mim::EtaExp::analyze(), mim::EtaRed::analyze(), mim::Pass::analyze(), mim::Pass::analyze(), mim::Pass::analyze(), mim::plug::clos::LowerTypedClosPrep::analyze(), mim::plug::mem::CopyProp::analyze(), mim::plug::mem::SSAConstr::analyze(), mim::plug::mem::SSAConstr::analyze(), mim::TailRecElim::analyze(), mim::PassMan::run(), mim::FPPass< P, M >::undo_enter(), and mim::FPPass< P, M >::undo_visit().
Num_Nodes
size_t mim::Num_Nodes = size_t(0) +size_t(1) +size_t(1) +size_t(1) +size_t(1) +size_t(1) +size_t(1) +size_t(1) +size_t(1) +size_t(1) +size_t(1) +size_t(1) +size_t(1) +size_t(1) +size_t(1) +size_t(1) +size_t(1) +size_t(1) +size_t(1) +size_t(1) +size_t(1) +size_t(1) +size_t(1) +size_t(1) +size_t(1) +size_t(1) +size_t(1) +size_t(1) +size_t(1) +size_t(1) +size_t(1) static constexpr
Definition at line 90 of file def.h.