Thorin: thorin::math Namespace Reference
thorin::math Namespace Reference
The math Plugin
Functions
void register_normalizers (Normalizers &normalizers)
Variables
static constexpr plugin_t Plugin_Id = 0x3825490000000000
Mode
enum class Mode : nat_t {
top = 0 ,
none = top ,
nnan = 1 << 0 ,
ninf = 1 << 1 ,
nsz = 1 << 2 ,
arcp = 1 << 3 ,
contract = 1 << 4 ,
afn = 1 << 5 ,
reassoc = 1 << 6 ,
finite = nnan | ninf ,
unsafe = nsz | arcp | reassoc ,
fast ,
bot = fast
}
Allowed optimizations for a specific operation.
using VMode = std::variant< Mode, nat_t, Ref >
Give Mode as thorin::math::Mode, thorin::nat_t or Ref.
constexpr auto operator& (Mode x, Mode y)
constexpr auto operator& (std::underlying_type_t< Mode > x, Mode y)
constexpr auto operator& (Mode x, std::underlying_type_t< Mode > y)
constexpr auto operator| (Mode x, Mode y)
constexpr auto operator| (std::underlying_type_t< Mode > x, Mode y)
constexpr auto operator| (Mode x, std::underlying_type_t< Mode > y)
constexpr auto operator^ (Mode x, Mode y)
constexpr auto operator^ (std::underlying_type_t< Mode > x, Mode y)
constexpr auto operator^ (Mode x, std::underlying_type_t< Mode > y)
constexpr std::strong_ordering operator<=> (std::underlying_type_t< Mode > x, Mode y)
constexpr std::strong_ordering operator<=> (Mode x, std::underlying_type_t< Mode > y)
constexpr bool operator== (std::underlying_type_t< Mode > x, Mode y)
constexpr bool operator== (Mode x, std::underlying_type_t< Mode > y)
Ref mode (World &w, VMode m)
thorin::math::VMode -> Ref.
%math.F
enum F : flags_t
const Axiom * type_f (World &w)
Ref type_f (Ref pe)
Ref type_f (World &w, nat_t p, nat_t e)
Ref type_f16 (World &w)
Ref type_f32 (World &w)
Ref type_f64 (World &w)
template<nat_t P, nat_t E>
auto match_f (Ref def)
auto match_f16 (Ref def)
auto match_f32 (Ref def)
auto match_f64 (Ref def)
std::optional< nat_t > isa_f (Ref def)
template<class R >
const Lit * lit_f (World &w, R val)
const Lit * lit_f (World &w, nat_t width, f64 val)
%math.arith
enum arith : flags_t {
add = 0x3825490000000100 ,
sub = 0x3825490000000101 ,
mul = 0x3825490000000102 ,
div = 0x3825490000000103 ,
rem = 0x3825490000000104
}
Ref op_rminus (VMode m, Ref a)
template<arith id>
Ref normalize_arith (Ref type, Ref c, Ref arg)
constexpr auto operator& (arith x, arith y)
constexpr auto operator& (std::underlying_type_t< arith > x, arith y)
constexpr auto operator& (arith x, std::underlying_type_t< arith > y)
constexpr auto operator| (arith x, arith y)
constexpr auto operator| (std::underlying_type_t< arith > x, arith y)
constexpr auto operator| (arith x, std::underlying_type_t< arith > y)
constexpr auto operator^ (arith x, arith y)
constexpr auto operator^ (std::underlying_type_t< arith > x, arith y)
constexpr auto operator^ (arith x, std::underlying_type_t< arith > y)
constexpr std::strong_ordering operator<=> (std::underlying_type_t< arith > x, arith y)
constexpr std::strong_ordering operator<=> (arith x, std::underlying_type_t< arith > y)
constexpr bool operator== (std::underlying_type_t< arith > x, arith y)
constexpr bool operator== (arith x, std::underlying_type_t< arith > y)
%math.extrema
enum extrema : flags_t {
im = 0x3825490000000200 ,
fmin = im ,
iM = 0x3825490000000201 ,
fmax = iM ,
Im = 0x3825490000000202 ,
ieee754min = Im ,
IM = 0x3825490000000203 ,
ieee754max = IM
}
template<extrema id>
Ref normalize_extrema (Ref type, Ref c, Ref arg)
constexpr auto operator& (extrema x, extrema y)
constexpr auto operator& (std::underlying_type_t< extrema > x, extrema y)
constexpr auto operator& (extrema x, std::underlying_type_t< extrema > y)
constexpr auto operator| (extrema x, extrema y)
constexpr auto operator| (std::underlying_type_t< extrema > x, extrema y)
constexpr auto operator| (extrema x, std::underlying_type_t< extrema > y)
constexpr auto operator^ (extrema x, extrema y)
constexpr auto operator^ (std::underlying_type_t< extrema > x, extrema y)
constexpr auto operator^ (extrema x, std::underlying_type_t< extrema > y)
constexpr std::strong_ordering operator<=> (std::underlying_type_t< extrema > x, extrema y)
constexpr std::strong_ordering operator<=> (extrema x, std::underlying_type_t< extrema > y)
constexpr bool operator== (std::underlying_type_t< extrema > x, extrema y)
constexpr bool operator== (extrema x, std::underlying_type_t< extrema > y)
%math.tri
enum tri : flags_t {
ahff = 0x3825490000000300 ,
sin = ahff ,
ahfF = 0x3825490000000301 ,
cos = ahfF ,
ahFf = 0x3825490000000302 ,
tan = ahFf ,
ahFF = 0x3825490000000303 ,
aHff = 0x3825490000000304 ,
sinh = aHff ,
h = aHff ,
aHfF = 0x3825490000000305 ,
cosh = aHfF ,
aHFf = 0x3825490000000306 ,
tanh = aHFf ,
aHFF = 0x3825490000000307 ,
Ahff = 0x3825490000000308 ,
asin = Ahff ,
a = Ahff ,
AhfF = 0x3825490000000309 ,
acos = AhfF ,
AhFf = 0x382549000000030a ,
atan = AhFf ,
AhFF = 0x382549000000030b ,
AHff = 0x382549000000030c ,
asinh = AHff ,
AHfF = 0x382549000000030d ,
acosh = AHfF ,
AHFf = 0x382549000000030e ,
atanh = AHFf ,
AHFF = 0x382549000000030f
}
template<tri id>
Ref normalize_tri (Ref type, Ref c, Ref arg)
constexpr auto operator& (tri x, tri y)
constexpr auto operator& (std::underlying_type_t< tri > x, tri y)
constexpr auto operator& (tri x, std::underlying_type_t< tri > y)
constexpr auto operator| (tri x, tri y)
constexpr auto operator| (std::underlying_type_t< tri > x, tri y)
constexpr auto operator| (tri x, std::underlying_type_t< tri > y)
constexpr auto operator^ (tri x, tri y)
constexpr auto operator^ (std::underlying_type_t< tri > x, tri y)
constexpr auto operator^ (tri x, std::underlying_type_t< tri > y)
constexpr std::strong_ordering operator<=> (std::underlying_type_t< tri > x, tri y)
constexpr std::strong_ordering operator<=> (tri x, std::underlying_type_t< tri > y)
constexpr bool operator== (std::underlying_type_t< tri > x, tri y)
constexpr bool operator== (tri x, std::underlying_type_t< tri > y)
%math.pow
enum pow : flags_t
Ref normalize_pow (Ref type, Ref c, Ref arg)
%math.rt
enum rt : flags_t {
sq = 0x3825490000000500 ,
cb = 0x3825490000000501
}
template<rt id>
Ref normalize_rt (Ref type, Ref c, Ref arg)
constexpr auto operator& (rt x, rt y)
constexpr auto operator& (std::underlying_type_t< rt > x, rt y)
constexpr auto operator& (rt x, std::underlying_type_t< rt > y)
constexpr auto operator| (rt x, rt y)
constexpr auto operator| (std::underlying_type_t< rt > x, rt y)
constexpr auto operator| (rt x, std::underlying_type_t< rt > y)
constexpr auto operator^ (rt x, rt y)
constexpr auto operator^ (std::underlying_type_t< rt > x, rt y)
constexpr auto operator^ (rt x, std::underlying_type_t< rt > y)
constexpr std::strong_ordering operator<=> (std::underlying_type_t< rt > x, rt y)
constexpr std::strong_ordering operator<=> (rt x, std::underlying_type_t< rt > y)
constexpr bool operator== (std::underlying_type_t< rt > x, rt y)
constexpr bool operator== (rt x, std::underlying_type_t< rt > y)
%math.exp
enum exp : flags_t {
bl = 0x3825490000000600 ,
exp = bl ,
bL = 0x3825490000000601 ,
log = bL ,
Bl = 0x3825490000000602 ,
exp2 = Bl ,
b = Bl ,
BL = 0x3825490000000603 ,
log2 = BL
}
template<exp id>
Ref normalize_exp (Ref type, Ref c, Ref arg)
constexpr auto operator& (exp x, exp y)
constexpr auto operator& (std::underlying_type_t< exp > x, exp y)
constexpr auto operator& (exp x, std::underlying_type_t< exp > y)
constexpr auto operator| (exp x, exp y)
constexpr auto operator| (std::underlying_type_t< exp > x, exp y)
constexpr auto operator| (exp x, std::underlying_type_t< exp > y)
constexpr auto operator^ (exp x, exp y)
constexpr auto operator^ (std::underlying_type_t< exp > x, exp y)
constexpr auto operator^ (exp x, std::underlying_type_t< exp > y)
constexpr std::strong_ordering operator<=> (std::underlying_type_t< exp > x, exp y)
constexpr std::strong_ordering operator<=> (exp x, std::underlying_type_t< exp > y)
constexpr bool operator== (std::underlying_type_t< exp > x, exp y)
constexpr bool operator== (exp x, std::underlying_type_t< exp > y)
%math.er
enum er : flags_t {
f = 0x3825490000000700 ,
fc = 0x3825490000000701
}
template<er id>
Ref normalize_er (Ref type, Ref c, Ref arg)
constexpr auto operator& (er x, er y)
constexpr auto operator& (std::underlying_type_t< er > x, er y)
constexpr auto operator& (er x, std::underlying_type_t< er > y)
constexpr auto operator| (er x, er y)
constexpr auto operator| (std::underlying_type_t< er > x, er y)
constexpr auto operator| (er x, std::underlying_type_t< er > y)
constexpr auto operator^ (er x, er y)
constexpr auto operator^ (std::underlying_type_t< er > x, er y)
constexpr auto operator^ (er x, std::underlying_type_t< er > y)
constexpr std::strong_ordering operator<=> (std::underlying_type_t< er > x, er y)
constexpr std::strong_ordering operator<=> (er x, std::underlying_type_t< er > y)
constexpr bool operator== (std::underlying_type_t< er > x, er y)
constexpr bool operator== (er x, std::underlying_type_t< er > y)
%math.gamma
enum gamma : flags_t {
t = 0x3825490000000800 ,
l = 0x3825490000000801
}
template<gamma id>
Ref normalize_gamma (Ref type, Ref c, Ref arg)
constexpr auto operator& (gamma x, gamma y)
constexpr auto operator& (std::underlying_type_t< gamma > x, gamma y)
constexpr auto operator& (gamma x, std::underlying_type_t< gamma > y)
constexpr auto operator| (gamma x, gamma y)
constexpr auto operator| (std::underlying_type_t< gamma > x, gamma y)
constexpr auto operator| (gamma x, std::underlying_type_t< gamma > y)
constexpr auto operator^ (gamma x, gamma y)
constexpr auto operator^ (std::underlying_type_t< gamma > x, gamma y)
constexpr auto operator^ (gamma x, std::underlying_type_t< gamma > y)
constexpr std::strong_ordering operator<=> (std::underlying_type_t< gamma > x, gamma y)
constexpr std::strong_ordering operator<=> (gamma x, std::underlying_type_t< gamma > y)
constexpr bool operator== (std::underlying_type_t< gamma > x, gamma y)
constexpr bool operator== (gamma x, std::underlying_type_t< gamma > y)
%math.cmp
enum cmp : flags_t {
ugle = 0x3825490000000900 ,
f = 0x3825490000000700 ,
uglE = 0x3825490000000901 ,
e = uglE ,
ugLe = 0x3825490000000902 ,
l = 0x3825490000000801 ,
ugLE = 0x3825490000000903 ,
le = ugLE ,
uGle = 0x3825490000000904 ,
g = uGle ,
uGlE = 0x3825490000000905 ,
ge = uGlE ,
uGLe = 0x3825490000000906 ,
ne = uGLe ,
uGLE = 0x3825490000000907 ,
o = uGLE ,
Ugle = 0x3825490000000908 ,
u = Ugle ,
UglE = 0x3825490000000909 ,
ue = UglE ,
UgLe = 0x382549000000090a ,
ul = UgLe ,
UgLE = 0x382549000000090b ,
ule = UgLE ,
UGle = 0x382549000000090c ,
ug = UGle ,
UGlE = 0x382549000000090d ,
uge = UGlE ,
UGLe = 0x382549000000090e ,
une = UGLe ,
UGLE = 0x382549000000090f ,
t = 0x3825490000000800
}
template<cmp id>
Ref normalize_cmp (Ref type, Ref c, Ref arg)
constexpr auto operator& (cmp x, cmp y)
constexpr auto operator& (std::underlying_type_t< cmp > x, cmp y)
constexpr auto operator& (cmp x, std::underlying_type_t< cmp > y)
constexpr auto operator| (cmp x, cmp y)
constexpr auto operator| (std::underlying_type_t< cmp > x, cmp y)
constexpr auto operator| (cmp x, std::underlying_type_t< cmp > y)
constexpr auto operator^ (cmp x, cmp y)
constexpr auto operator^ (std::underlying_type_t< cmp > x, cmp y)
constexpr auto operator^ (cmp x, std::underlying_type_t< cmp > y)
constexpr std::strong_ordering operator<=> (std::underlying_type_t< cmp > x, cmp y)
constexpr std::strong_ordering operator<=> (cmp x, std::underlying_type_t< cmp > y)
constexpr bool operator== (std::underlying_type_t< cmp > x, cmp y)
constexpr bool operator== (cmp x, std::underlying_type_t< cmp > y)
%math.conv
enum conv : flags_t {
s2f = 0x3825490000000a00 ,
u2f = 0x3825490000000a01 ,
f2s = 0x3825490000000a02 ,
f2u = 0x3825490000000a03 ,
f2f = 0x3825490000000a04
}
template<conv id>
Ref normalize_conv (Ref dst_t, Ref c, Ref x)
constexpr auto operator& (conv x, conv y)
constexpr auto operator& (std::underlying_type_t< conv > x, conv y)
constexpr auto operator& (conv x, std::underlying_type_t< conv > y)
constexpr auto operator| (conv x, conv y)
constexpr auto operator| (std::underlying_type_t< conv > x, conv y)
constexpr auto operator| (conv x, std::underlying_type_t< conv > y)
constexpr auto operator^ (conv x, conv y)
constexpr auto operator^ (std::underlying_type_t< conv > x, conv y)
constexpr auto operator^ (conv x, std::underlying_type_t< conv > y)
constexpr std::strong_ordering operator<=> (std::underlying_type_t< conv > x, conv y)
constexpr std::strong_ordering operator<=> (conv x, std::underlying_type_t< conv > y)
constexpr bool operator== (std::underlying_type_t< conv > x, conv y)
constexpr bool operator== (conv x, std::underlying_type_t< conv > y)
Detailed Description
The math Plugin
Typedef Documentation
VMode
using thorin::math::VMode = typedef std::variant<Mode, nat_t, Ref>
Give Mode as thorin::math::Mode, thorin::nat_t or Ref.
Definition at line 45 of file math.h.
Enumeration Type Documentation
arith
enum thorin::math::arith : flags_t
Enumerator
add
sub
mul
div
rem
Definition at line 26 of file autogen.h.
cmp
enum thorin::math::cmp : flags_t
Enumerator
ugle
f
uglE
e
ugLe
l
ugLE
le
uGle
g
uGlE
ge
uGLe
ne
uGLE
o
Ugle
u
UglE
ue
UgLe
ul
UgLE
ule
UGle
ug
UGlE
uge
UGLe
une
UGLE
t
Definition at line 201 of file autogen.h.
conv
enum thorin::math::conv : flags_t
Enumerator
s2f
u2f
f2s
f2u
f2f
Definition at line 248 of file autogen.h.
er
enum thorin::math::er : flags_t
Enumerator
f
fc
Definition at line 167 of file autogen.h.
exp
enum thorin::math::exp : flags_t
Enumerator
bl
exp
bL
log
Bl
exp2
b
BL
log2
Definition at line 143 of file autogen.h.
extrema
enum thorin::math::extrema : flags_t
Enumerator
im
fmin
iM
fmax
Im
ieee754min
IM
ieee754max
Definition at line 46 of file autogen.h.
F
enum thorin::math::F : flags_t
Definition at line 15 of file autogen.h.
gamma
enum thorin::math::gamma : flags_t
Enumerator
t
l
Definition at line 184 of file autogen.h.
Mode
enum class thorin::math::Mode : nat_t strong
Allowed optimizations for a specific operation.
Enumerator
top
none
Alias for Mode::none.
nnan
No NaNs.
Allow optimizations to assume the arguments and result are not NaN. Such optimizations are required to retain defined behavior over NaNs, but the value of the result is undefined.
ninf
No Infs.
Allow optimizations to assume the arguments and result are not +/-Inf. Such optimizations are required to retain defined behavior over +/-Inf, but the value of the result is undefined.
nsz
No Signed Zeros.
Allow optimizations to treat the sign of a zero argument or result as insignificant.
arcp
Allow Reciprocal.
Allow optimizations to use the reciprocal of an argument rather than perform division.
contract
Allow floating-point contraction (e.g.
fusing a multiply followed by an addition into a fused multiply-and-add).
afn
Approximate functions.
Allow substitution of approximate calculations for functions (sin, log, sqrt, etc).
reassoc
Allow reassociation transformations for floating-point operations.
This may dramatically change results in floating point.
finite
Mode::nnan | Mode::ninf.
unsafe
Mode::nsz | Mode::arcp | Mode::reassoc.
fast
All flags.
bot
Alias for Mode::fast.
Definition at line 14 of file math.h.
pow
enum thorin::math::pow : flags_t
Definition at line 114 of file autogen.h.
rt
enum thorin::math::rt : flags_t
Enumerator
sq
cb
Definition at line 126 of file autogen.h.
tri
enum thorin::math::tri : flags_t
Enumerator
ahff
sin
ahfF
cos
ahFf
tan
ahFF
aHff
sinh
h
aHfF
cosh
aHFf
tanh
aHFF
Ahff
asin
a
AhfF
acos
AhFf
atan
AhFF
AHff
asinh
AHfF
acosh
AHFf
atanh
AHFF
Definition at line 69 of file autogen.h.
Function Documentation
isa_f()
std::optional< nat_t > thorin::math::isa_f (Ref def) inline
Definition at line 83 of file math.h.
References e.
Referenced by thorin::ll::Emitter::emit_bb(), normalize_arith(), normalize_conv(), thorin::core::normalize_trait(), and op_rminus().
lit_f() [1/2]
const Lit * thorin::math::lit_f (World & w, nat_t width, f64 val) inline
Definition at line 105 of file math.h.
References lit_f(), and thorin::unreachable().
lit_f() [2/2]
template<class R > const Lit * thorin::math::lit_f (World & w, R val)
Definition at line 96 of file math.h.
References thorin::World::lit(), type_f16(), type_f32(), type_f64(), and thorin::unreachable().
Referenced by lit_f(), normalize_arith(), and op_rminus().
match_f()
template<nat_t P, nat_t E> auto thorin::math::match_f (Ref def) inline
Definition at line 71 of file math.h.
References e, and thorin::RuntimeCast< Def >::isa().
match_f16()
auto thorin::math::match_f16 (Ref def) inline
Definition at line 79 of file math.h.
match_f32()
auto thorin::math::match_f32 (Ref def) inline
Definition at line 80 of file math.h.
match_f64()
auto thorin::math::match_f64 (Ref def) inline
Definition at line 81 of file math.h.
mode()
Ref thorin::math::mode (World & w, VMode m) inline
thorin::math::VMode -> Ref.
Definition at line 48 of file math.h.
Referenced by normalize_arith(), and op_rminus().
normalize_arith()
template<arith id> Ref thorin::math::normalize_arith (Ref type, Ref c, Ref arg)
Definition at line 222 of file normalizers.cpp.
References a, add, thorin::RuntimeCast< B >::as(), b, div, fast, thorin::RuntimeCast< Def >::isa(), isa_f(), lit_f(), mode(), mul, thorin::Def::projs(), rem, sub, thorin::unreachable(), and thorin::Def::world().
normalize_cmp()
template<cmp id> Ref thorin::math::normalize_cmp (Ref type, Ref c, Ref arg)
Definition at line 350 of file normalizers.cpp.
References a, thorin::RuntimeCast< B >::as(), b, f, thorin::Def::projs(), t, and thorin::Def::world().
normalize_conv()
template<conv id> Ref thorin::math::normalize_conv (Ref dst_t, Ref c, Ref x)
Definition at line 363 of file normalizers.cpp.
References thorin::App::arg(), thorin::RuntimeCast< B >::as(), f2f, f2s, f2u, thorin::RuntimeCast< Def >::isa(), thorin::RuntimeCast< B >::isa(), isa_f(), l, M, s2f, thorin::Idx::size2bitwidth(), thorin::Def::type(), u2f, thorin::unreachable(), and thorin::Def::world().
normalize_er()
template<er id> Ref thorin::math::normalize_er (Ref type, Ref c, Ref arg)
Definition at line 336 of file normalizers.cpp.
References thorin::World::raw_app(), and thorin::Def::world().
normalize_exp()
template<exp id> Ref thorin::math::normalize_exp (Ref type, Ref c, Ref arg)
Definition at line 329 of file normalizers.cpp.
References thorin::World::raw_app(), and thorin::Def::world().
normalize_extrema()
template<extrema id> Ref thorin::math::normalize_extrema (Ref type, Ref c, Ref arg)
Definition at line 287 of file normalizers.cpp.
References a, thorin::RuntimeCast< B >::as(), b, fmax, fmin, ieee754max, ieee754min, thorin::RuntimeCast< Def >::isa(), nnan, nsz, thorin::Def::projs(), and thorin::Def::world().
normalize_gamma()
template<gamma id> Ref thorin::math::normalize_gamma (Ref type, Ref c, Ref arg)
Definition at line 343 of file normalizers.cpp.
References thorin::World::raw_app(), and thorin::Def::world().
normalize_pow()
Ref thorin::math::normalize_pow (Ref type, Ref c, Ref arg)
Definition at line 314 of file normalizers.cpp.
normalize_rt()
template<rt id> Ref thorin::math::normalize_rt (Ref type, Ref c, Ref arg)
Definition at line 322 of file normalizers.cpp.
References thorin::World::raw_app(), and thorin::Def::world().
normalize_tri()
template<tri id> Ref thorin::math::normalize_tri (Ref type, Ref c, Ref arg)
Definition at line 308 of file normalizers.cpp.
References thorin::World::raw_app(), and thorin::Def::world().
op_rminus()
Ref thorin::math::op_rminus (VMode m, Ref a) inline
Definition at line 118 of file math.h.
References a, thorin::World::call(), isa_f(), lit_f(), mode(), and sub.
operator&() [1/30]
constexpr auto thorin::math::operator& (arith x, arith y) constexpr
Definition at line 37 of file autogen.h.
operator&() [2/30]
constexpr auto thorin::math::operator& (arith x, std::underlying_type_t< arith > y) constexpr
Definition at line 37 of file autogen.h.
operator&() [3/30]
constexpr auto thorin::math::operator& (cmp x, cmp y) constexpr
Definition at line 239 of file autogen.h.
operator&() [4/30]
constexpr auto thorin::math::operator& (cmp x, std::underlying_type_t< cmp > y) constexpr
Definition at line 239 of file autogen.h.
operator&() [5/30]
constexpr auto thorin::math::operator& (conv x, conv y) constexpr
Definition at line 259 of file autogen.h.
operator&() [6/30]
constexpr auto thorin::math::operator& (conv x, std::underlying_type_t< conv > y) constexpr
Definition at line 259 of file autogen.h.
operator&() [7/30]
constexpr auto thorin::math::operator& (er x, er y) constexpr
Definition at line 175 of file autogen.h.
operator&() [8/30]
constexpr auto thorin::math::operator& (er x, std::underlying_type_t< er > y) constexpr
Definition at line 175 of file autogen.h.
operator&() [9/30]
constexpr auto thorin::math::operator& (exp x, exp y) constexpr
Definition at line 158 of file autogen.h.
operator&() [10/30]
constexpr auto thorin::math::operator& (exp x, std::underlying_type_t< exp > y) constexpr
Definition at line 158 of file autogen.h.
operator&() [11/30]
constexpr auto thorin::math::operator& (extrema x, extrema y) constexpr
Definition at line 60 of file autogen.h.
operator&() [12/30]
constexpr auto thorin::math::operator& (extrema x, std::underlying_type_t< extrema > y) constexpr
Definition at line 60 of file autogen.h.
operator&() [13/30]
constexpr auto thorin::math::operator& (gamma x, gamma y) constexpr
Definition at line 192 of file autogen.h.
operator&() [14/30]
constexpr auto thorin::math::operator& (gamma x, std::underlying_type_t< gamma > y) constexpr
Definition at line 192 of file autogen.h.
operator&() [15/30]
constexpr auto thorin::math::operator& (Mode x, Mode y) constexpr
Definition at line 42 of file math.h.
operator&() [16/30]
constexpr auto thorin::math::operator& (Mode x, std::underlying_type_t< Mode > y) constexpr
Definition at line 42 of file math.h.
operator&() [17/30]
constexpr auto thorin::math::operator& (rt x, rt y) constexpr
Definition at line 134 of file autogen.h.
operator&() [18/30]
constexpr auto thorin::math::operator& (rt x, std::underlying_type_t< rt > y) constexpr
Definition at line 134 of file autogen.h.
operator&() [19/30]
constexpr auto thorin::math::operator& (std::underlying_type_t< arith > x, arith y) constexpr
Definition at line 37 of file autogen.h.
operator&() [20/30]
constexpr auto thorin::math::operator& (std::underlying_type_t< cmp > x, cmp y) constexpr
Definition at line 239 of file autogen.h.
operator&() [21/30]
constexpr auto thorin::math::operator& (std::underlying_type_t< conv > x, conv y) constexpr
Definition at line 259 of file autogen.h.
operator&() [22/30]
constexpr auto thorin::math::operator& (std::underlying_type_t< er > x, er y) constexpr
Definition at line 175 of file autogen.h.
operator&() [23/30]
constexpr auto thorin::math::operator& (std::underlying_type_t< exp > x, exp y) constexpr
Definition at line 158 of file autogen.h.
operator&() [24/30]
constexpr auto thorin::math::operator& (std::underlying_type_t< extrema > x, extrema y) constexpr
Definition at line 60 of file autogen.h.
operator&() [25/30]
constexpr auto thorin::math::operator& (std::underlying_type_t< gamma > x, gamma y) constexpr
Definition at line 192 of file autogen.h.
operator&() [26/30]
constexpr auto thorin::math::operator& (std::underlying_type_t< Mode > x, Mode y) constexpr
Definition at line 42 of file math.h.
operator&() [27/30]
constexpr auto thorin::math::operator& (std::underlying_type_t< rt > x, rt y) constexpr
Definition at line 134 of file autogen.h.
operator&() [28/30]
constexpr auto thorin::math::operator& (std::underlying_type_t< tri > x, tri y) constexpr
Definition at line 105 of file autogen.h.
operator&() [29/30]
constexpr auto thorin::math::operator& (tri x, std::underlying_type_t< tri > y) constexpr
Definition at line 105 of file autogen.h.
operator&() [30/30]
constexpr auto thorin::math::operator& (tri x, tri y) constexpr
Definition at line 105 of file autogen.h.
operator<=>() [1/20]
constexpr std::strong_ordering thorin::math::operator<=> (arith x, std::underlying_type_t< arith > y) constexpr
Definition at line 37 of file autogen.h.
operator<=>() [2/20]
constexpr std::strong_ordering thorin::math::operator<=> (cmp x, std::underlying_type_t< cmp > y) constexpr
Definition at line 239 of file autogen.h.
operator<=>() [3/20]
constexpr std::strong_ordering thorin::math::operator<=> (conv x, std::underlying_type_t< conv > y) constexpr
Definition at line 259 of file autogen.h.
operator<=>() [4/20]
constexpr std::strong_ordering thorin::math::operator<=> (er x, std::underlying_type_t< er > y) constexpr
Definition at line 175 of file autogen.h.
operator<=>() [5/20]
constexpr std::strong_ordering thorin::math::operator<=> (exp x, std::underlying_type_t< exp > y) constexpr
Definition at line 158 of file autogen.h.
operator<=>() [6/20]
constexpr std::strong_ordering thorin::math::operator<=> (extrema x, std::underlying_type_t< extrema > y) constexpr
Definition at line 60 of file autogen.h.
operator<=>() [7/20]
constexpr std::strong_ordering thorin::math::operator<=> (gamma x, std::underlying_type_t< gamma > y) constexpr
Definition at line 192 of file autogen.h.
operator<=>() [8/20]
constexpr std::strong_ordering thorin::math::operator<=> (Mode x, std::underlying_type_t< Mode > y) constexpr
Definition at line 42 of file math.h.
operator<=>() [9/20]
constexpr std::strong_ordering thorin::math::operator<=> (rt x, std::underlying_type_t< rt > y) constexpr
Definition at line 134 of file autogen.h.
operator<=>() [10/20]
constexpr std::strong_ordering thorin::math::operator<=> (std::underlying_type_t< arith > x, arith y) constexpr
Definition at line 37 of file autogen.h.
operator<=>() [11/20]
constexpr std::strong_ordering thorin::math::operator<=> (std::underlying_type_t< cmp > x, cmp y) constexpr
Definition at line 239 of file autogen.h.
operator<=>() [12/20]
constexpr std::strong_ordering thorin::math::operator<=> (std::underlying_type_t< conv > x, conv y) constexpr
Definition at line 259 of file autogen.h.
operator<=>() [13/20]
constexpr std::strong_ordering thorin::math::operator<=> (std::underlying_type_t< er > x, er y) constexpr
Definition at line 175 of file autogen.h.
operator<=>() [14/20]
constexpr std::strong_ordering thorin::math::operator<=> (std::underlying_type_t< exp > x, exp y) constexpr
Definition at line 158 of file autogen.h.
operator<=>() [15/20]
constexpr std::strong_ordering thorin::math::operator<=> (std::underlying_type_t< extrema > x, extrema y) constexpr
Definition at line 60 of file autogen.h.
operator<=>() [16/20]
constexpr std::strong_ordering thorin::math::operator<=> (std::underlying_type_t< gamma > x, gamma y) constexpr
Definition at line 192 of file autogen.h.
operator<=>() [17/20]
constexpr std::strong_ordering thorin::math::operator<=> (std::underlying_type_t< Mode > x, Mode y) constexpr
Definition at line 42 of file math.h.
operator<=>() [18/20]
constexpr std::strong_ordering thorin::math::operator<=> (std::underlying_type_t< rt > x, rt y) constexpr
Definition at line 134 of file autogen.h.
operator<=>() [19/20]
constexpr std::strong_ordering thorin::math::operator<=> (std::underlying_type_t< tri > x, tri y) constexpr
Definition at line 105 of file autogen.h.
operator<=>() [20/20]
constexpr std::strong_ordering thorin::math::operator<=> (tri x, std::underlying_type_t< tri > y) constexpr
Definition at line 105 of file autogen.h.
operator==() [1/20]
constexpr bool thorin::math::operator== (arith x, std::underlying_type_t< arith > y) constexpr
Definition at line 37 of file autogen.h.
operator==() [2/20]
constexpr bool thorin::math::operator== (cmp x, std::underlying_type_t< cmp > y) constexpr
Definition at line 239 of file autogen.h.
operator==() [3/20]
constexpr bool thorin::math::operator== (conv x, std::underlying_type_t< conv > y) constexpr
Definition at line 259 of file autogen.h.
operator==() [4/20]
constexpr bool thorin::math::operator== (er x, std::underlying_type_t< er > y) constexpr
Definition at line 175 of file autogen.h.
operator==() [5/20]
constexpr bool thorin::math::operator== (exp x, std::underlying_type_t< exp > y) constexpr
Definition at line 158 of file autogen.h.
operator==() [6/20]
constexpr bool thorin::math::operator== (extrema x, std::underlying_type_t< extrema > y) constexpr
Definition at line 60 of file autogen.h.
operator==() [7/20]
constexpr bool thorin::math::operator== (gamma x, std::underlying_type_t< gamma > y) constexpr
Definition at line 192 of file autogen.h.
operator==() [8/20]
constexpr bool thorin::math::operator== (Mode x, std::underlying_type_t< Mode > y) constexpr
Definition at line 42 of file math.h.
operator==() [9/20]
constexpr bool thorin::math::operator== (rt x, std::underlying_type_t< rt > y) constexpr
Definition at line 134 of file autogen.h.
operator==() [10/20]
constexpr bool thorin::math::operator== (std::underlying_type_t< arith > x, arith y) constexpr
Definition at line 37 of file autogen.h.
operator==() [11/20]
constexpr bool thorin::math::operator== (std::underlying_type_t< cmp > x, cmp y) constexpr
Definition at line 239 of file autogen.h.
operator==() [12/20]
constexpr bool thorin::math::operator== (std::underlying_type_t< conv > x, conv y) constexpr
Definition at line 259 of file autogen.h.
operator==() [13/20]
constexpr bool thorin::math::operator== (std::underlying_type_t< er > x, er y) constexpr
Definition at line 175 of file autogen.h.
operator==() [14/20]
constexpr bool thorin::math::operator== (std::underlying_type_t< exp > x, exp y) constexpr
Definition at line 158 of file autogen.h.
operator==() [15/20]
constexpr bool thorin::math::operator== (std::underlying_type_t< extrema > x, extrema y) constexpr
Definition at line 60 of file autogen.h.
operator==() [16/20]
constexpr bool thorin::math::operator== (std::underlying_type_t< gamma > x, gamma y) constexpr
Definition at line 192 of file autogen.h.
operator==() [17/20]
constexpr bool thorin::math::operator== (std::underlying_type_t< Mode > x, Mode y) constexpr
Definition at line 42 of file math.h.
operator==() [18/20]
constexpr bool thorin::math::operator== (std::underlying_type_t< rt > x, rt y) constexpr
Definition at line 134 of file autogen.h.
operator==() [19/20]
constexpr bool thorin::math::operator== (std::underlying_type_t< tri > x, tri y) constexpr
Definition at line 105 of file autogen.h.
operator==() [20/20]
constexpr bool thorin::math::operator== (tri x, std::underlying_type_t< tri > y) constexpr
Definition at line 105 of file autogen.h.
operator^() [1/30]
constexpr auto thorin::math::operator^ (arith x, arith y) constexpr
Definition at line 37 of file autogen.h.
operator^() [2/30]
constexpr auto thorin::math::operator^ (arith x, std::underlying_type_t< arith > y) constexpr
Definition at line 37 of file autogen.h.
operator^() [3/30]
constexpr auto thorin::math::operator^ (cmp x, cmp y) constexpr
Definition at line 239 of file autogen.h.
operator^() [4/30]
constexpr auto thorin::math::operator^ (cmp x, std::underlying_type_t< cmp > y) constexpr
Definition at line 239 of file autogen.h.
operator^() [5/30]
constexpr auto thorin::math::operator^ (conv x, conv y) constexpr
Definition at line 259 of file autogen.h.
operator^() [6/30]
constexpr auto thorin::math::operator^ (conv x, std::underlying_type_t< conv > y) constexpr
Definition at line 259 of file autogen.h.
operator^() [7/30]
constexpr auto thorin::math::operator^ (er x, er y) constexpr
Definition at line 175 of file autogen.h.
operator^() [8/30]
constexpr auto thorin::math::operator^ (er x, std::underlying_type_t< er > y) constexpr
Definition at line 175 of file autogen.h.
operator^() [9/30]
constexpr auto thorin::math::operator^ (exp x, exp y) constexpr
Definition at line 158 of file autogen.h.
operator^() [10/30]
constexpr auto thorin::math::operator^ (exp x, std::underlying_type_t< exp > y) constexpr
Definition at line 158 of file autogen.h.
operator^() [11/30]
constexpr auto thorin::math::operator^ (extrema x, extrema y) constexpr
Definition at line 60 of file autogen.h.
operator^() [12/30]
constexpr auto thorin::math::operator^ (extrema x, std::underlying_type_t< extrema > y) constexpr
Definition at line 60 of file autogen.h.
operator^() [13/30]
constexpr auto thorin::math::operator^ (gamma x, gamma y) constexpr
Definition at line 192 of file autogen.h.
operator^() [14/30]
constexpr auto thorin::math::operator^ (gamma x, std::underlying_type_t< gamma > y) constexpr
Definition at line 192 of file autogen.h.
operator^() [15/30]
constexpr auto thorin::math::operator^ (Mode x, Mode y) constexpr
Definition at line 42 of file math.h.
operator^() [16/30]
constexpr auto thorin::math::operator^ (Mode x, std::underlying_type_t< Mode > y) constexpr
Definition at line 42 of file math.h.
operator^() [17/30]
constexpr auto thorin::math::operator^ (rt x, rt y) constexpr
Definition at line 134 of file autogen.h.
operator^() [18/30]
constexpr auto thorin::math::operator^ (rt x, std::underlying_type_t< rt > y) constexpr
Definition at line 134 of file autogen.h.
operator^() [19/30]
constexpr auto thorin::math::operator^ (std::underlying_type_t< arith > x, arith y) constexpr
Definition at line 37 of file autogen.h.
operator^() [20/30]
constexpr auto thorin::math::operator^ (std::underlying_type_t< cmp > x, cmp y) constexpr
Definition at line 239 of file autogen.h.
operator^() [21/30]
constexpr auto thorin::math::operator^ (std::underlying_type_t< conv > x, conv y) constexpr
Definition at line 259 of file autogen.h.
operator^() [22/30]
constexpr auto thorin::math::operator^ (std::underlying_type_t< er > x, er y) constexpr
Definition at line 175 of file autogen.h.
operator^() [23/30]
constexpr auto thorin::math::operator^ (std::underlying_type_t< exp > x, exp y) constexpr
Definition at line 158 of file autogen.h.
operator^() [24/30]
constexpr auto thorin::math::operator^ (std::underlying_type_t< extrema > x, extrema y) constexpr
Definition at line 60 of file autogen.h.
operator^() [25/30]
constexpr auto thorin::math::operator^ (std::underlying_type_t< gamma > x, gamma y) constexpr
Definition at line 192 of file autogen.h.
operator^() [26/30]
constexpr auto thorin::math::operator^ (std::underlying_type_t< Mode > x, Mode y) constexpr
Definition at line 42 of file math.h.
operator^() [27/30]
constexpr auto thorin::math::operator^ (std::underlying_type_t< rt > x, rt y) constexpr
Definition at line 134 of file autogen.h.
operator^() [28/30]
constexpr auto thorin::math::operator^ (std::underlying_type_t< tri > x, tri y) constexpr
Definition at line 105 of file autogen.h.
operator^() [29/30]
constexpr auto thorin::math::operator^ (tri x, std::underlying_type_t< tri > y) constexpr
Definition at line 105 of file autogen.h.
operator^() [30/30]
constexpr auto thorin::math::operator^ (tri x, tri y) constexpr
Definition at line 105 of file autogen.h.
operator|() [1/30]
constexpr auto thorin::math::operator| (arith x, arith y) constexpr
Definition at line 37 of file autogen.h.
operator|() [2/30]
constexpr auto thorin::math::operator| (arith x, std::underlying_type_t< arith > y) constexpr
Definition at line 37 of file autogen.h.
operator|() [3/30]
constexpr auto thorin::math::operator| (cmp x, cmp y) constexpr
Definition at line 239 of file autogen.h.
operator|() [4/30]
constexpr auto thorin::math::operator| (cmp x, std::underlying_type_t< cmp > y) constexpr
Definition at line 239 of file autogen.h.
operator|() [5/30]
constexpr auto thorin::math::operator| (conv x, conv y) constexpr
Definition at line 259 of file autogen.h.
operator|() [6/30]
constexpr auto thorin::math::operator| (conv x, std::underlying_type_t< conv > y) constexpr
Definition at line 259 of file autogen.h.
operator|() [7/30]
constexpr auto thorin::math::operator| (er x, er y) constexpr
Definition at line 175 of file autogen.h.
operator|() [8/30]
constexpr auto thorin::math::operator| (er x, std::underlying_type_t< er > y) constexpr
Definition at line 175 of file autogen.h.
operator|() [9/30]
constexpr auto thorin::math::operator| (exp x, exp y) constexpr
Definition at line 158 of file autogen.h.
operator|() [10/30]
constexpr auto thorin::math::operator| (exp x, std::underlying_type_t< exp > y) constexpr
Definition at line 158 of file autogen.h.
operator|() [11/30]
constexpr auto thorin::math::operator| (extrema x, extrema y) constexpr
Definition at line 60 of file autogen.h.
operator|() [12/30]
constexpr auto thorin::math::operator| (extrema x, std::underlying_type_t< extrema > y) constexpr
Definition at line 60 of file autogen.h.
operator|() [13/30]
constexpr auto thorin::math::operator| (gamma x, gamma y) constexpr
Definition at line 192 of file autogen.h.
operator|() [14/30]
constexpr auto thorin::math::operator| (gamma x, std::underlying_type_t< gamma > y) constexpr
Definition at line 192 of file autogen.h.
operator|() [15/30]
constexpr auto thorin::math::operator| (Mode x, Mode y) constexpr
Definition at line 42 of file math.h.
operator|() [16/30]
constexpr auto thorin::math::operator| (Mode x, std::underlying_type_t< Mode > y) constexpr
Definition at line 42 of file math.h.
operator|() [17/30]
constexpr auto thorin::math::operator| (rt x, rt y) constexpr
Definition at line 134 of file autogen.h.
operator|() [18/30]
constexpr auto thorin::math::operator| (rt x, std::underlying_type_t< rt > y) constexpr
Definition at line 134 of file autogen.h.
operator|() [19/30]
constexpr auto thorin::math::operator| (std::underlying_type_t< arith > x, arith y) constexpr
Definition at line 37 of file autogen.h.
operator|() [20/30]
constexpr auto thorin::math::operator| (std::underlying_type_t< cmp > x, cmp y) constexpr
Definition at line 239 of file autogen.h.
operator|() [21/30]
constexpr auto thorin::math::operator| (std::underlying_type_t< conv > x, conv y) constexpr
Definition at line 259 of file autogen.h.
operator|() [22/30]
constexpr auto thorin::math::operator| (std::underlying_type_t< er > x, er y) constexpr
Definition at line 175 of file autogen.h.
operator|() [23/30]
constexpr auto thorin::math::operator| (std::underlying_type_t< exp > x, exp y) constexpr
Definition at line 158 of file autogen.h.
operator|() [24/30]
constexpr auto thorin::math::operator| (std::underlying_type_t< extrema > x, extrema y) constexpr
Definition at line 60 of file autogen.h.
operator|() [25/30]
constexpr auto thorin::math::operator| (std::underlying_type_t< gamma > x, gamma y) constexpr
Definition at line 192 of file autogen.h.
operator|() [26/30]
constexpr auto thorin::math::operator| (std::underlying_type_t< Mode > x, Mode y) constexpr
Definition at line 42 of file math.h.
operator|() [27/30]
constexpr auto thorin::math::operator| (std::underlying_type_t< rt > x, rt y) constexpr
Definition at line 134 of file autogen.h.
operator|() [28/30]
constexpr auto thorin::math::operator| (std::underlying_type_t< tri > x, tri y) constexpr
Definition at line 105 of file autogen.h.
operator|() [29/30]
constexpr auto thorin::math::operator| (tri x, std::underlying_type_t< tri > y) constexpr
Definition at line 105 of file autogen.h.
operator|() [30/30]
constexpr auto thorin::math::operator| (tri x, tri y) constexpr
Definition at line 105 of file autogen.h.
register_normalizers()
void thorin::math::register_normalizers (Normalizers & normalizers)
Referenced by thorin_get_plugin().
type_f() [1/3]
Ref thorin::math::type_f (Ref pe) inline
Definition at line 58 of file math.h.
References thorin::World::app(), and type_f().
type_f() [2/3]
const Axiom * thorin::math::type_f (World & w) inline
Definition at line 57 of file math.h.
References thorin::World::ax().
Referenced by type_f(), type_f16(), type_f32(), and type_f64().
type_f() [3/3]
Ref thorin::math::type_f (World & w, nat_t p, nat_t e) inline
Definition at line 62 of file math.h.
References e, le, thorin::World::lit_nat(), thorin::World::tuple(), and type_f().
type_f16()
Ref thorin::math::type_f16 (World & w) inline
Definition at line 67 of file math.h.
References type_f().
Referenced by lit_f().
type_f32()
Ref thorin::math::type_f32 (World & w) inline
Definition at line 68 of file math.h.
References type_f().
Referenced by lit_f().
type_f64()
Ref thorin::math::type_f64 (World & w) inline
Definition at line 69 of file math.h.
References type_f().
Referenced by lit_f().
Variable Documentation
Plugin_Id
constexpr plugin_t thorin::math::Plugin_Id = 0x3825490000000000 static constexpr
Definition at line 10 of file autogen.h.