Thorin: thorin::core Namespace Reference
thorin::core Namespace Reference
The core Plugin
Enumerations
%core.i1
enum i1 : flags_t
enum I1 : flags_t
%core.i8
enum i8 : flags_t
enum I8 : flags_t
%core.i16
enum i16 : flags_t
enum I16 : flags_t
%core.i32
enum i32 : flags_t
enum I32 : flags_t
%core.i64
enum i64 : flags_t
enum I64 : flags_t
%core.minus
enum minus : flags_t
Functions
void register_normalizers (Normalizers &normalizers)
Convert TBound to Sigma
This is WIP.
template<bool up>
const Sigma * convert (const TBound< up > *b)
const Sigma * convert (const Bound *b)
extract_unsafe
Ref extract_unsafe (Ref d, Ref i)
Ref extract_unsafe (Ref d, u64 i)
insert_unsafe
Ref insert_unsafe (Ref d, Ref i, Ref val)
Ref insert_unsafe (Ref d, u64 i, Ref val)
Variables
static constexpr plugin_t Plugin_Id = 0x1104c60000000000
Mode
What should happen if Idx arithmetic overflows?
enum class Mode : nat_t {
none = 0 ,
nsw = 1 << 0 ,
nuw = 1 << 1 ,
nusw = nuw | nsw
}
using VMode = std::variant< Mode, nat_t, Ref >
Give Mode as thorin::math::Mode, thorin::nat_t or Ref.
constexpr auto operator& (Mode x, Mode y)
constexpr auto operator& (std::underlying_type_t< Mode > x, Mode y)
constexpr auto operator& (Mode x, std::underlying_type_t< Mode > y)
constexpr auto operator| (Mode x, Mode y)
constexpr auto operator| (std::underlying_type_t< Mode > x, Mode y)
constexpr auto operator| (Mode x, std::underlying_type_t< Mode > y)
constexpr auto operator^ (Mode x, Mode y)
constexpr auto operator^ (std::underlying_type_t< Mode > x, Mode y)
constexpr auto operator^ (Mode x, std::underlying_type_t< Mode > y)
constexpr std::strong_ordering operator<=> (std::underlying_type_t< Mode > x, Mode y)
constexpr std::strong_ordering operator<=> (Mode x, std::underlying_type_t< Mode > y)
constexpr bool operator== (std::underlying_type_t< Mode > x, Mode y)
constexpr bool operator== (Mode x, std::underlying_type_t< Mode > y)
Ref mode (World &w, VMode m)
thorin::core::VMode -> Ref.
%core.nat
enum nat : flags_t {
add = 0x1104c60000000a00 ,
sub = 0x1104c60000000a01 ,
mul = 0x1104c60000000a02
}
template<nat id>
Ref normalize_nat (Ref type, Ref callee, Ref arg)
constexpr auto operator& (nat x, nat y)
constexpr auto operator& (std::underlying_type_t< nat > x, nat y)
constexpr auto operator& (nat x, std::underlying_type_t< nat > y)
constexpr auto operator| (nat x, nat y)
constexpr auto operator| (std::underlying_type_t< nat > x, nat y)
constexpr auto operator| (nat x, std::underlying_type_t< nat > y)
constexpr auto operator^ (nat x, nat y)
constexpr auto operator^ (std::underlying_type_t< nat > x, nat y)
constexpr auto operator^ (nat x, std::underlying_type_t< nat > y)
constexpr std::strong_ordering operator<=> (std::underlying_type_t< nat > x, nat y)
constexpr std::strong_ordering operator<=> (nat x, std::underlying_type_t< nat > y)
constexpr bool operator== (std::underlying_type_t< nat > x, nat y)
constexpr bool operator== (nat x, std::underlying_type_t< nat > y)
%core.ncmp
enum ncmp : flags_t {
gle = 0x1104c60000000b00 ,
f = gle ,
glE = 0x1104c60000000b01 ,
e = glE ,
gLe = 0x1104c60000000b02 ,
l = gLe ,
gLE = 0x1104c60000000b03 ,
le = gLE ,
Gle = 0x1104c60000000b04 ,
g = Gle ,
GlE = 0x1104c60000000b05 ,
ge = GlE ,
GLe = 0x1104c60000000b06 ,
ne = GLe ,
GLE = 0x1104c60000000b07 ,
t = GLE
}
template<ncmp id>
Ref normalize_ncmp (Ref type, Ref callee, Ref arg)
constexpr auto operator& (ncmp x, ncmp y)
constexpr auto operator& (std::underlying_type_t< ncmp > x, ncmp y)
constexpr auto operator& (ncmp x, std::underlying_type_t< ncmp > y)
constexpr auto operator| (ncmp x, ncmp y)
constexpr auto operator| (std::underlying_type_t< ncmp > x, ncmp y)
constexpr auto operator| (ncmp x, std::underlying_type_t< ncmp > y)
constexpr auto operator^ (ncmp x, ncmp y)
constexpr auto operator^ (std::underlying_type_t< ncmp > x, ncmp y)
constexpr auto operator^ (ncmp x, std::underlying_type_t< ncmp > y)
constexpr std::strong_ordering operator<=> (std::underlying_type_t< ncmp > x, ncmp y)
constexpr std::strong_ordering operator<=> (ncmp x, std::underlying_type_t< ncmp > y)
constexpr bool operator== (std::underlying_type_t< ncmp > x, ncmp y)
constexpr bool operator== (ncmp x, std::underlying_type_t< ncmp > y)
%core.mode
enum mode : flags_t {
us = 0x1104c60000000c00 ,
uS = 0x1104c60000000c01 ,
Us = 0x1104c60000000c02 ,
US = 0x1104c60000000c03 ,
nuw = 0x1104c60000000c04 ,
nsw = 0x1104c60000000c05 ,
nusw = 0x1104c60000000c06
}
constexpr auto operator& (mode x, mode y)
constexpr auto operator& (std::underlying_type_t< mode > x, mode y)
constexpr auto operator& (mode x, std::underlying_type_t< mode > y)
constexpr auto operator| (mode x, mode y)
constexpr auto operator| (std::underlying_type_t< mode > x, mode y)
constexpr auto operator| (mode x, std::underlying_type_t< mode > y)
constexpr auto operator^ (mode x, mode y)
constexpr auto operator^ (std::underlying_type_t< mode > x, mode y)
constexpr auto operator^ (mode x, std::underlying_type_t< mode > y)
constexpr std::strong_ordering operator<=> (std::underlying_type_t< mode > x, mode y)
constexpr std::strong_ordering operator<=> (mode x, std::underlying_type_t< mode > y)
constexpr bool operator== (std::underlying_type_t< mode > x, mode y)
constexpr bool operator== (mode x, std::underlying_type_t< mode > y)
%core.idx
enum idx : flags_t
Ref normalize_idx (Ref type, Ref c, Ref arg)
%core.bit1
enum bit1 : flags_t {
f = gle ,
neg = 0x1104c60000000e01 ,
id = 0x1104c60000000e02 ,
t = GLE
}
template<bit1 id>
Ref normalize_bit1 (Ref type, Ref c, Ref a)
constexpr auto operator& (bit1 x, bit1 y)
constexpr auto operator& (std::underlying_type_t< bit1 > x, bit1 y)
constexpr auto operator& (bit1 x, std::underlying_type_t< bit1 > y)
constexpr auto operator| (bit1 x, bit1 y)
constexpr auto operator| (std::underlying_type_t< bit1 > x, bit1 y)
constexpr auto operator| (bit1 x, std::underlying_type_t< bit1 > y)
constexpr auto operator^ (bit1 x, bit1 y)
constexpr auto operator^ (std::underlying_type_t< bit1 > x, bit1 y)
constexpr auto operator^ (bit1 x, std::underlying_type_t< bit1 > y)
constexpr std::strong_ordering operator<=> (std::underlying_type_t< bit1 > x, bit1 y)
constexpr std::strong_ordering operator<=> (bit1 x, std::underlying_type_t< bit1 > y)
constexpr bool operator== (std::underlying_type_t< bit1 > x, bit1 y)
constexpr bool operator== (bit1 x, std::underlying_type_t< bit1 > y)
%core.bit2
enum bit2 : flags_t {
f = gle ,
nor = 0x1104c60000000f01 ,
nciff = 0x1104c60000000f02 ,
nfst = 0x1104c60000000f03 ,
niff = 0x1104c60000000f04 ,
nsnd = 0x1104c60000000f05 ,
xor_ = 0x1104c60000000f06 ,
nand = 0x1104c60000000f07 ,
and_ = 0x1104c60000000f08 ,
nxor = 0x1104c60000000f09 ,
snd = 0x1104c60000000f0a ,
iff = 0x1104c60000000f0b ,
fst = 0x1104c60000000f0c ,
ciff = 0x1104c60000000f0d ,
or_ = 0x1104c60000000f0e ,
t = GLE
}
constexpr std::array< std::array< u64, 2 >, 2 > make_truth_table (bit2 id)
Use like this: a op b = tab[a][b]
template<bit2 id>
Ref normalize_bit2 (Ref type, Ref c, Ref arg)
constexpr auto operator& (bit2 x, bit2 y)
constexpr auto operator& (std::underlying_type_t< bit2 > x, bit2 y)
constexpr auto operator& (bit2 x, std::underlying_type_t< bit2 > y)
constexpr auto operator| (bit2 x, bit2 y)
constexpr auto operator| (std::underlying_type_t< bit2 > x, bit2 y)
constexpr auto operator| (bit2 x, std::underlying_type_t< bit2 > y)
constexpr auto operator^ (bit2 x, bit2 y)
constexpr auto operator^ (std::underlying_type_t< bit2 > x, bit2 y)
constexpr auto operator^ (bit2 x, std::underlying_type_t< bit2 > y)
constexpr std::strong_ordering operator<=> (std::underlying_type_t< bit2 > x, bit2 y)
constexpr std::strong_ordering operator<=> (bit2 x, std::underlying_type_t< bit2 > y)
constexpr bool operator== (std::underlying_type_t< bit2 > x, bit2 y)
constexpr bool operator== (bit2 x, std::underlying_type_t< bit2 > y)
%core.shr
enum shr : flags_t {
a = 0x1104c60000001000 ,
l = gLe
}
template<shr id>
Ref normalize_shr (Ref type, Ref c, Ref arg)
constexpr auto operator& (shr x, shr y)
constexpr auto operator& (std::underlying_type_t< shr > x, shr y)
constexpr auto operator& (shr x, std::underlying_type_t< shr > y)
constexpr auto operator| (shr x, shr y)
constexpr auto operator| (std::underlying_type_t< shr > x, shr y)
constexpr auto operator| (shr x, std::underlying_type_t< shr > y)
constexpr auto operator^ (shr x, shr y)
constexpr auto operator^ (std::underlying_type_t< shr > x, shr y)
constexpr auto operator^ (shr x, std::underlying_type_t< shr > y)
constexpr std::strong_ordering operator<=> (std::underlying_type_t< shr > x, shr y)
constexpr std::strong_ordering operator<=> (shr x, std::underlying_type_t< shr > y)
constexpr bool operator== (std::underlying_type_t< shr > x, shr y)
constexpr bool operator== (shr x, std::underlying_type_t< shr > y)
%core.wrap
enum wrap : flags_t {
add = 0x1104c60000000a00 ,
sub = 0x1104c60000000a01 ,
mul = 0x1104c60000000a02 ,
shl = 0x1104c60000001103
}
template<wrap id>
Ref normalize_wrap (Ref type, Ref c, Ref arg)
constexpr auto operator& (wrap x, wrap y)
constexpr auto operator& (std::underlying_type_t< wrap > x, wrap y)
constexpr auto operator& (wrap x, std::underlying_type_t< wrap > y)
constexpr auto operator| (wrap x, wrap y)
constexpr auto operator| (std::underlying_type_t< wrap > x, wrap y)
constexpr auto operator| (wrap x, std::underlying_type_t< wrap > y)
constexpr auto operator^ (wrap x, wrap y)
constexpr auto operator^ (std::underlying_type_t< wrap > x, wrap y)
constexpr auto operator^ (wrap x, std::underlying_type_t< wrap > y)
constexpr std::strong_ordering operator<=> (std::underlying_type_t< wrap > x, wrap y)
constexpr std::strong_ordering operator<=> (wrap x, std::underlying_type_t< wrap > y)
constexpr bool operator== (std::underlying_type_t< wrap > x, wrap y)
constexpr bool operator== (wrap x, std::underlying_type_t< wrap > y)
%core.div
enum div : flags_t {
sdiv = 0x1104c60000001300 ,
udiv = 0x1104c60000001301 ,
srem = 0x1104c60000001302 ,
urem = 0x1104c60000001303
}
template<div id>
Ref normalize_div (Ref full_type, Ref c, Ref arg)
constexpr auto operator& (div x, div y)
constexpr auto operator& (std::underlying_type_t< div > x, div y)
constexpr auto operator& (div x, std::underlying_type_t< div > y)
constexpr auto operator| (div x, div y)
constexpr auto operator| (std::underlying_type_t< div > x, div y)
constexpr auto operator| (div x, std::underlying_type_t< div > y)
constexpr auto operator^ (div x, div y)
constexpr auto operator^ (std::underlying_type_t< div > x, div y)
constexpr auto operator^ (div x, std::underlying_type_t< div > y)
constexpr std::strong_ordering operator<=> (std::underlying_type_t< div > x, div y)
constexpr std::strong_ordering operator<=> (div x, std::underlying_type_t< div > y)
constexpr bool operator== (std::underlying_type_t< div > x, div y)
constexpr bool operator== (div x, std::underlying_type_t< div > y)
%core.icmp
enum icmp : flags_t {
xygle = 0x1104c60000001400 ,
f = gle ,
xyglE = 0x1104c60000001401 ,
e = glE ,
xygLe = 0x1104c60000001402 ,
xygLE = 0x1104c60000001403 ,
xyGle = 0x1104c60000001404 ,
xyGlE = 0x1104c60000001405 ,
xyGLe = 0x1104c60000001406 ,
xyGLE = 0x1104c60000001407 ,
xYgle = 0x1104c60000001408 ,
xYglE = 0x1104c60000001409 ,
xYgLe = 0x1104c6000000140a ,
sl = xYgLe ,
xYgLE = 0x1104c6000000140b ,
sle = xYgLE ,
xYGle = 0x1104c6000000140c ,
ug = xYGle ,
xYGlE = 0x1104c6000000140d ,
uge = xYGlE ,
xYGLe = 0x1104c6000000140e ,
xYGLE = 0x1104c6000000140f ,
Xygle = 0x1104c60000001410 ,
XyglE = 0x1104c60000001411 ,
XygLe = 0x1104c60000001412 ,
ul = XygLe ,
XygLE = 0x1104c60000001413 ,
ule = XygLE ,
XyGle = 0x1104c60000001414 ,
sg = XyGle ,
XyGlE = 0x1104c60000001415 ,
sge = XyGlE ,
XyGLe = 0x1104c60000001416 ,
XyGLE = 0x1104c60000001417 ,
XYgle = 0x1104c60000001418 ,
XYglE = 0x1104c60000001419 ,
XYgLe = 0x1104c6000000141a ,
XYgLE = 0x1104c6000000141b ,
XYGle = 0x1104c6000000141c ,
XYGlE = 0x1104c6000000141d ,
XYGLe = 0x1104c6000000141e ,
ne = GLe ,
XYGLE = 0x1104c6000000141f ,
t = GLE
}
template<icmp id>
Ref normalize_icmp (Ref type, Ref c, Ref arg)
constexpr auto operator& (icmp x, icmp y)
constexpr auto operator& (std::underlying_type_t< icmp > x, icmp y)
constexpr auto operator& (icmp x, std::underlying_type_t< icmp > y)
constexpr auto operator| (icmp x, icmp y)
constexpr auto operator| (std::underlying_type_t< icmp > x, icmp y)
constexpr auto operator| (icmp x, std::underlying_type_t< icmp > y)
constexpr auto operator^ (icmp x, icmp y)
constexpr auto operator^ (std::underlying_type_t< icmp > x, icmp y)
constexpr auto operator^ (icmp x, std::underlying_type_t< icmp > y)
constexpr std::strong_ordering operator<=> (std::underlying_type_t< icmp > x, icmp y)
constexpr std::strong_ordering operator<=> (icmp x, std::underlying_type_t< icmp > y)
constexpr bool operator== (std::underlying_type_t< icmp > x, icmp y)
constexpr bool operator== (icmp x, std::underlying_type_t< icmp > y)
%core.extrema
enum extrema : flags_t {
sm = 0x1104c60000001500 ,
umin = sm ,
sM = 0x1104c60000001501 ,
umax = sM ,
Sm = 0x1104c60000001502 ,
smin = Sm ,
SM = 0x1104c60000001503 ,
smax = SM
}
template<extrema id>
Ref normalize_extrema (Ref type, Ref c, Ref arg)
constexpr auto operator& (extrema x, extrema y)
constexpr auto operator& (std::underlying_type_t< extrema > x, extrema y)
constexpr auto operator& (extrema x, std::underlying_type_t< extrema > y)
constexpr auto operator| (extrema x, extrema y)
constexpr auto operator| (std::underlying_type_t< extrema > x, extrema y)
constexpr auto operator| (extrema x, std::underlying_type_t< extrema > y)
constexpr auto operator^ (extrema x, extrema y)
constexpr auto operator^ (std::underlying_type_t< extrema > x, extrema y)
constexpr auto operator^ (extrema x, std::underlying_type_t< extrema > y)
constexpr std::strong_ordering operator<=> (std::underlying_type_t< extrema > x, extrema y)
constexpr std::strong_ordering operator<=> (extrema x, std::underlying_type_t< extrema > y)
constexpr bool operator== (std::underlying_type_t< extrema > x, extrema y)
constexpr bool operator== (extrema x, std::underlying_type_t< extrema > y)
%core.abs
enum abs : flags_t
Ref normalize_abs (Ref type, Ref c, Ref arg)
%core.conv
enum conv : flags_t {
s = 0x1104c60000001700 ,
u = 0x1104c60000001701
}
template<conv id>
Ref normalize_conv (Ref dst_t, Ref c, Ref x)
constexpr auto operator& (conv x, conv y)
constexpr auto operator& (std::underlying_type_t< conv > x, conv y)
constexpr auto operator& (conv x, std::underlying_type_t< conv > y)
constexpr auto operator| (conv x, conv y)
constexpr auto operator| (std::underlying_type_t< conv > x, conv y)
constexpr auto operator| (conv x, std::underlying_type_t< conv > y)
constexpr auto operator^ (conv x, conv y)
constexpr auto operator^ (std::underlying_type_t< conv > x, conv y)
constexpr auto operator^ (conv x, std::underlying_type_t< conv > y)
constexpr std::strong_ordering operator<=> (std::underlying_type_t< conv > x, conv y)
constexpr std::strong_ordering operator<=> (conv x, std::underlying_type_t< conv > y)
constexpr bool operator== (std::underlying_type_t< conv > x, conv y)
constexpr bool operator== (conv x, std::underlying_type_t< conv > y)
%core.bitcast
enum bitcast : flags_t
Ref normalize_bitcast (Ref dst_t, Ref callee, Ref src)
%core.trait
enum trait : flags_t {
size = 0x1104c60000001900 ,
align = 0x1104c60000001901
}
Ref op (trait o, Ref type)
template<trait id>
Ref normalize_trait (Ref nat, Ref callee, Ref type)
constexpr auto operator& (trait x, trait y)
constexpr auto operator& (std::underlying_type_t< trait > x, trait y)
constexpr auto operator& (trait x, std::underlying_type_t< trait > y)
constexpr auto operator| (trait x, trait y)
constexpr auto operator| (std::underlying_type_t< trait > x, trait y)
constexpr auto operator| (trait x, std::underlying_type_t< trait > y)
constexpr auto operator^ (trait x, trait y)
constexpr auto operator^ (std::underlying_type_t< trait > x, trait y)
constexpr auto operator^ (trait x, std::underlying_type_t< trait > y)
constexpr std::strong_ordering operator<=> (std::underlying_type_t< trait > x, trait y)
constexpr std::strong_ordering operator<=> (trait x, std::underlying_type_t< trait > y)
constexpr bool operator== (std::underlying_type_t< trait > x, trait y)
constexpr bool operator== (trait x, std::underlying_type_t< trait > y)
%core.pe
enum pe : flags_t {
hlt = 0x1104c60000001a00 ,
run = 0x1104c60000001a01 ,
known = 0x1104c60000001a02
}
Ref op (pe o, Ref def)
template<pe id>
Ref normalize_pe (Ref type, Ref callee, Ref arg)
constexpr auto operator& (pe x, pe y)
constexpr auto operator& (std::underlying_type_t< pe > x, pe y)
constexpr auto operator& (pe x, std::underlying_type_t< pe > y)
constexpr auto operator| (pe x, pe y)
constexpr auto operator| (std::underlying_type_t< pe > x, pe y)
constexpr auto operator| (pe x, std::underlying_type_t< pe > y)
constexpr auto operator^ (pe x, pe y)
constexpr auto operator^ (std::underlying_type_t< pe > x, pe y)
constexpr auto operator^ (pe x, std::underlying_type_t< pe > y)
constexpr std::strong_ordering operator<=> (std::underlying_type_t< pe > x, pe y)
constexpr std::strong_ordering operator<=> (pe x, std::underlying_type_t< pe > y)
constexpr bool operator== (std::underlying_type_t< pe > x, pe y)
constexpr bool operator== (pe x, std::underlying_type_t< pe > y)
%core.zip
enum zip : flags_t
Ref normalize_zip (Ref type, Ref c, Ref arg)
Detailed Description
The core Plugin
Typedef Documentation
VMode
using thorin::core::VMode = typedef std::variant<Mode, nat_t, Ref>
Give Mode as thorin::math::Mode, thorin::nat_t or Ref.
Definition at line 23 of file core.h.
Enumeration Type Documentation
abs
enum thorin::core::abs : flags_t
Definition at line 403 of file autogen.h.
bit1
enum thorin::core::bit1 : flags_t
Enumerator
f
neg
id
t
Definition at line 205 of file autogen.h.
bit2
enum thorin::core::bit2 : flags_t
Enumerator
f
nor
nciff
nfst
niff
nsnd
xor_
nand
and_
nxor
snd
iff
fst
ciff
or_
t
Definition at line 224 of file autogen.h.
bitcast
enum thorin::core::bitcast : flags_t
Definition at line 432 of file autogen.h.
conv
enum thorin::core::conv : flags_t
Enumerator
s
u
Definition at line 415 of file autogen.h.
div
enum thorin::core::div : flags_t
Enumerator
sdiv
udiv
srem
urem
Definition at line 302 of file autogen.h.
extrema
enum thorin::core::extrema : flags_t
Enumerator
sm
umin
sM
umax
Sm
smin
SM
smax
Definition at line 380 of file autogen.h.
i1
enum thorin::core::i1 : flags_t
Definition at line 15 of file autogen.h.
I1
enum thorin::core::I1 : flags_t
Definition at line 70 of file autogen.h.
i16
enum thorin::core::i16 : flags_t
Definition at line 37 of file autogen.h.
I16
enum thorin::core::I16 : flags_t
Definition at line 92 of file autogen.h.
i32
enum thorin::core::i32 : flags_t
Definition at line 48 of file autogen.h.
I32
enum thorin::core::I32 : flags_t
Definition at line 103 of file autogen.h.
i64
enum thorin::core::i64 : flags_t
Definition at line 59 of file autogen.h.
I64
enum thorin::core::I64 : flags_t
Definition at line 114 of file autogen.h.
i8
enum thorin::core::i8 : flags_t
Definition at line 26 of file autogen.h.
I8
enum thorin::core::I8 : flags_t
Definition at line 81 of file autogen.h.
icmp
enum thorin::core::icmp : flags_t
Enumerator
xygle
f
xyglE
e
xygLe
xygLE
xyGle
xyGlE
xyGLe
xyGLE
xYgle
xYglE
xYgLe
sl
xYgLE
sle
xYGle
ug
xYGlE
uge
xYGLe
xYGLE
Xygle
XyglE
XygLe
ul
XygLE
ule
XyGle
sg
XyGlE
sge
XyGLe
XyGLE
XYgle
XYglE
XYgLe
XYgLE
XYGle
XYGlE
XYGLe
ne
XYGLE
t
Definition at line 321 of file autogen.h.
idx
enum thorin::core::idx : flags_t
Definition at line 193 of file autogen.h.
minus
enum thorin::core::minus : flags_t
Definition at line 291 of file autogen.h.
mode
enum thorin::core::mode : flags_t
Enumerator
us
uS
Us
US
nuw
nsw
nusw
Definition at line 174 of file autogen.h.
Mode
enum class thorin::core::Mode : nat_t strong
Enumerator
none
Wrap around.
nsw
No Signed Wrap around.
nuw
No Unsigned Wrap around.
nusw
Definition at line 13 of file core.h.
nat
enum thorin::core::nat : flags_t
Enumerator
add
sub
mul
Definition at line 125 of file autogen.h.
ncmp
enum thorin::core::ncmp : flags_t
Enumerator
gle
f
glE
e
gLe
l
gLE
le
Gle
g
GlE
ge
GLe
ne
GLE
t
Definition at line 143 of file autogen.h.
pe
enum thorin::core::pe : flags_t
Enumerator
hlt
run
known
Definition at line 461 of file autogen.h.
shr
enum thorin::core::shr : flags_t
Enumerator
a
l
Definition at line 255 of file autogen.h.
trait
enum thorin::core::trait : flags_t
Enumerator
size
align
Definition at line 444 of file autogen.h.
wrap
enum thorin::core::wrap : flags_t
Enumerator
add
sub
mul
shl
Definition at line 272 of file autogen.h.
zip
enum thorin::core::zip : flags_t
Definition at line 479 of file autogen.h.
Function Documentation
convert() [1/2]
const Sigma * thorin::core::convert (const Bound * b) inline
Definition at line 90 of file core.h.
References thorin::RuntimeCast< B >::as(), convert(), and thorin::RuntimeCast< B >::isa().
convert() [2/2]
template<bool up> const Sigma * thorin::core::convert (const TBound< up > * b)
Definition at line 18 of file core.cpp.
References a, align, thorin::RuntimeCast< Def >::isa(), thorin::Def::num_ops(), op(), thorin::Def::ops(), s, size, and thorin::Def::world().
Referenced by convert(), and normalize_trait().
extract_unsafe() [1/2]
Ref thorin::core::extract_unsafe (Ref d, Ref i) inline
Definition at line 63 of file core.h.
References u.
Referenced by extract_unsafe().
extract_unsafe() [2/2]
Ref thorin::core::extract_unsafe (Ref d, u64 i) inline
Definition at line 67 of file core.h.
References extract_unsafe().
insert_unsafe() [1/2]
Ref thorin::core::insert_unsafe (Ref d, Ref i, Ref val) inline
Definition at line 75 of file core.h.
References u.
Referenced by insert_unsafe().
insert_unsafe() [2/2]
Ref thorin::core::insert_unsafe (Ref d, u64 i, Ref val) inline
Definition at line 79 of file core.h.
References insert_unsafe().
make_truth_table()
constexpr std::array< std::array< u64, 2 >, 2 > thorin::core::make_truth_table (bit2 id) constexpr
Use like this: a op b = tab[a][b]
Definition at line 53 of file core.h.
mode()
Ref thorin::core::mode (World & w, VMode m) inline
thorin::core::VMode -> Ref.
Definition at line 26 of file core.h.
normalize_abs()
Ref thorin::core::normalize_abs (Ref type, Ref c, Ref arg)
Definition at line 327 of file normalizers.cpp.
normalize_bit1()
template<bit1 id> Ref thorin::core::normalize_bit1 (Ref type, Ref c, Ref a)
Definition at line 338 of file normalizers.cpp.
normalize_bit2()
template<bit2 id> Ref thorin::core::normalize_bit2 (Ref type, Ref c, Ref arg)
Definition at line 361 of file normalizers.cpp.
normalize_bitcast()
Ref thorin::core::normalize_bitcast (Ref dst_t, Ref callee, Ref src)
Definition at line 622 of file normalizers.cpp.
References thorin::RuntimeCast< Def >::isa(), l, thorin::Idx::size(), thorin::Def::type(), thorin::World::type(), and thorin::Def::world().
normalize_conv()
template<conv id> Ref thorin::core::normalize_conv (Ref dst_t, Ref c, Ref x)
Definition at line 582 of file normalizers.cpp.
normalize_div()
template<div id> Ref thorin::core::normalize_div (Ref full_type, Ref c, Ref arg)
Definition at line 543 of file normalizers.cpp.
normalize_extrema()
template<extrema id> Ref thorin::core::normalize_extrema (Ref type, Ref c, Ref arg)
Definition at line 319 of file normalizers.cpp.
normalize_icmp()
template<icmp id> Ref thorin::core::normalize_icmp (Ref type, Ref c, Ref arg)
Definition at line 303 of file normalizers.cpp.
normalize_idx()
Ref thorin::core::normalize_idx (Ref type, Ref c, Ref arg)
Definition at line 440 of file normalizers.cpp.
normalize_nat()
template<nat id> Ref thorin::core::normalize_nat (Ref type, Ref callee, Ref arg)
Definition at line 243 of file normalizers.cpp.
normalize_ncmp()
template<ncmp id> Ref thorin::core::normalize_ncmp (Ref type, Ref callee, Ref arg)
Definition at line 275 of file normalizers.cpp.
normalize_pe()
template<pe id> Ref thorin::core::normalize_pe (Ref type, Ref callee, Ref arg)
Definition at line 732 of file normalizers.cpp.
normalize_shr()
template<shr id> Ref thorin::core::normalize_shr (Ref type, Ref c, Ref arg)
Definition at line 453 of file normalizers.cpp.
normalize_trait()
template<trait id> Ref thorin::core::normalize_trait (Ref nat, Ref callee, Ref type)
Definition at line 644 of file normalizers.cpp.
References a, align, convert(), thorin::RuntimeCast< Def >::isa(), thorin::RuntimeCast< B >::isa(), thorin::math::isa_f(), thorin::Def::isa_imm(), thorin::World::lit_nat(), op(), thorin::Def::ops(), thorin::pad(), s, size, thorin::Idx::size(), thorin::Idx::size2bitwidth(), t, thorin::unreachable(), and thorin::Def::world().
normalize_wrap()
template<wrap id> Ref thorin::core::normalize_wrap (Ref type, Ref c, Ref arg)
Definition at line 483 of file normalizers.cpp.
normalize_zip()
Ref thorin::core::normalize_zip (Ref type, Ref c, Ref arg)
Definition at line 691 of file normalizers.cpp.
op() [1/2]
Ref thorin::core::op (pe o, Ref def) inline
Definition at line 43 of file core.h.
References thorin::Def::type(), and thorin::Def::world().
op() [2/2]
Ref thorin::core::op (trait o, Ref type) inline
Definition at line 35 of file core.h.
References thorin::Def::world().
Referenced by convert(), and normalize_trait().
operator&() [1/42]
constexpr auto thorin::core::operator& (bit1 x, bit1 y) constexpr
Definition at line 215 of file autogen.h.
operator&() [2/42]
constexpr auto thorin::core::operator& (bit1 x, std::underlying_type_t< bit1 > y) constexpr
Definition at line 215 of file autogen.h.
operator&() [3/42]
constexpr auto thorin::core::operator& (bit2 x, bit2 y) constexpr
Definition at line 246 of file autogen.h.
operator&() [4/42]
constexpr auto thorin::core::operator& (bit2 x, std::underlying_type_t< bit2 > y) constexpr
Definition at line 246 of file autogen.h.
operator&() [5/42]
constexpr auto thorin::core::operator& (conv x, conv y) constexpr
Definition at line 423 of file autogen.h.
operator&() [6/42]
constexpr auto thorin::core::operator& (conv x, std::underlying_type_t< conv > y) constexpr
Definition at line 423 of file autogen.h.
operator&() [7/42]
constexpr auto thorin::core::operator& (div x, div y) constexpr
Definition at line 312 of file autogen.h.
operator&() [8/42]
constexpr auto thorin::core::operator& (div x, std::underlying_type_t< div > y) constexpr
Definition at line 312 of file autogen.h.
operator&() [9/42]
constexpr auto thorin::core::operator& (extrema x, extrema y) constexpr
Definition at line 394 of file autogen.h.
operator&() [10/42]
constexpr auto thorin::core::operator& (extrema x, std::underlying_type_t< extrema > y) constexpr
Definition at line 394 of file autogen.h.
operator&() [11/42]
constexpr auto thorin::core::operator& (icmp x, icmp y) constexpr
Definition at line 371 of file autogen.h.
operator&() [12/42]
constexpr auto thorin::core::operator& (icmp x, std::underlying_type_t< icmp > y) constexpr
Definition at line 371 of file autogen.h.
operator&() [13/42]
constexpr auto thorin::core::operator& (mode x, mode y) constexpr
Definition at line 187 of file autogen.h.
operator&() [14/42]
constexpr auto thorin::core::operator& (Mode x, Mode y) constexpr
Definition at line 20 of file core.h.
operator&() [15/42]
constexpr auto thorin::core::operator& (mode x, std::underlying_type_t< mode > y) constexpr
Definition at line 187 of file autogen.h.
operator&() [16/42]
constexpr auto thorin::core::operator& (Mode x, std::underlying_type_t< Mode > y) constexpr
Definition at line 20 of file core.h.
operator&() [17/42]
constexpr auto thorin::core::operator& (nat x, nat y) constexpr
Definition at line 134 of file autogen.h.
operator&() [18/42]
constexpr auto thorin::core::operator& (nat x, std::underlying_type_t< nat > y) constexpr
Definition at line 134 of file autogen.h.
operator&() [19/42]
constexpr auto thorin::core::operator& (ncmp x, ncmp y) constexpr
Definition at line 165 of file autogen.h.
operator&() [20/42]
constexpr auto thorin::core::operator& (ncmp x, std::underlying_type_t< ncmp > y) constexpr
Definition at line 165 of file autogen.h.
operator&() [21/42]
constexpr auto thorin::core::operator& (pe x, pe y) constexpr
Definition at line 470 of file autogen.h.
operator&() [22/42]
constexpr auto thorin::core::operator& (pe x, std::underlying_type_t< pe > y) constexpr
Definition at line 470 of file autogen.h.
operator&() [23/42]
constexpr auto thorin::core::operator& (shr x, shr y) constexpr
Definition at line 263 of file autogen.h.
operator&() [24/42]
constexpr auto thorin::core::operator& (shr x, std::underlying_type_t< shr > y) constexpr
Definition at line 263 of file autogen.h.
operator&() [25/42]
constexpr auto thorin::core::operator& (std::underlying_type_t< bit1 > x, bit1 y) constexpr
Definition at line 215 of file autogen.h.
operator&() [26/42]
constexpr auto thorin::core::operator& (std::underlying_type_t< bit2 > x, bit2 y) constexpr
Definition at line 246 of file autogen.h.
operator&() [27/42]
constexpr auto thorin::core::operator& (std::underlying_type_t< conv > x, conv y) constexpr
Definition at line 423 of file autogen.h.
operator&() [28/42]
constexpr auto thorin::core::operator& (std::underlying_type_t< div > x, div y) constexpr
Definition at line 312 of file autogen.h.
operator&() [29/42]
constexpr auto thorin::core::operator& (std::underlying_type_t< extrema > x, extrema y) constexpr
Definition at line 394 of file autogen.h.
operator&() [30/42]
constexpr auto thorin::core::operator& (std::underlying_type_t< icmp > x, icmp y) constexpr
Definition at line 371 of file autogen.h.
operator&() [31/42]
constexpr auto thorin::core::operator& (std::underlying_type_t< mode > x, mode y) constexpr
Definition at line 187 of file autogen.h.
operator&() [32/42]
constexpr auto thorin::core::operator& (std::underlying_type_t< Mode > x, Mode y) constexpr
Definition at line 20 of file core.h.
operator&() [33/42]
constexpr auto thorin::core::operator& (std::underlying_type_t< nat > x, nat y) constexpr
Definition at line 134 of file autogen.h.
operator&() [34/42]
constexpr auto thorin::core::operator& (std::underlying_type_t< ncmp > x, ncmp y) constexpr
Definition at line 165 of file autogen.h.
operator&() [35/42]
constexpr auto thorin::core::operator& (std::underlying_type_t< pe > x, pe y) constexpr
Definition at line 470 of file autogen.h.
operator&() [36/42]
constexpr auto thorin::core::operator& (std::underlying_type_t< shr > x, shr y) constexpr
Definition at line 263 of file autogen.h.
operator&() [37/42]
constexpr auto thorin::core::operator& (std::underlying_type_t< trait > x, trait y) constexpr
Definition at line 452 of file autogen.h.
operator&() [38/42]
constexpr auto thorin::core::operator& (std::underlying_type_t< wrap > x, wrap y) constexpr
Definition at line 282 of file autogen.h.
operator&() [39/42]
constexpr auto thorin::core::operator& (trait x, std::underlying_type_t< trait > y) constexpr
Definition at line 452 of file autogen.h.
operator&() [40/42]
constexpr auto thorin::core::operator& (trait x, trait y) constexpr
Definition at line 452 of file autogen.h.
operator&() [41/42]
constexpr auto thorin::core::operator& (wrap x, std::underlying_type_t< wrap > y) constexpr
Definition at line 282 of file autogen.h.
operator&() [42/42]
constexpr auto thorin::core::operator& (wrap x, wrap y) constexpr
Definition at line 282 of file autogen.h.
operator<=>() [1/28]
constexpr std::strong_ordering thorin::core::operator<=> (bit1 x, std::underlying_type_t< bit1 > y) constexpr
Definition at line 215 of file autogen.h.
operator<=>() [2/28]
constexpr std::strong_ordering thorin::core::operator<=> (bit2 x, std::underlying_type_t< bit2 > y) constexpr
Definition at line 246 of file autogen.h.
operator<=>() [3/28]
constexpr std::strong_ordering thorin::core::operator<=> (conv x, std::underlying_type_t< conv > y) constexpr
Definition at line 423 of file autogen.h.
operator<=>() [4/28]
constexpr std::strong_ordering thorin::core::operator<=> (div x, std::underlying_type_t< div > y) constexpr
Definition at line 312 of file autogen.h.
operator<=>() [5/28]
constexpr std::strong_ordering thorin::core::operator<=> (extrema x, std::underlying_type_t< extrema > y) constexpr
Definition at line 394 of file autogen.h.
operator<=>() [6/28]
constexpr std::strong_ordering thorin::core::operator<=> (icmp x, std::underlying_type_t< icmp > y) constexpr
Definition at line 371 of file autogen.h.
operator<=>() [7/28]
constexpr std::strong_ordering thorin::core::operator<=> (mode x, std::underlying_type_t< mode > y) constexpr
Definition at line 187 of file autogen.h.
operator<=>() [8/28]
constexpr std::strong_ordering thorin::core::operator<=> (Mode x, std::underlying_type_t< Mode > y) constexpr
Definition at line 20 of file core.h.
operator<=>() [9/28]
constexpr std::strong_ordering thorin::core::operator<=> (nat x, std::underlying_type_t< nat > y) constexpr
Definition at line 134 of file autogen.h.
operator<=>() [10/28]
constexpr std::strong_ordering thorin::core::operator<=> (ncmp x, std::underlying_type_t< ncmp > y) constexpr
Definition at line 165 of file autogen.h.
operator<=>() [11/28]
constexpr std::strong_ordering thorin::core::operator<=> (pe x, std::underlying_type_t< pe > y) constexpr
Definition at line 470 of file autogen.h.
operator<=>() [12/28]
constexpr std::strong_ordering thorin::core::operator<=> (shr x, std::underlying_type_t< shr > y) constexpr
Definition at line 263 of file autogen.h.
operator<=>() [13/28]
constexpr std::strong_ordering thorin::core::operator<=> (std::underlying_type_t< bit1 > x, bit1 y) constexpr
Definition at line 215 of file autogen.h.
operator<=>() [14/28]
constexpr std::strong_ordering thorin::core::operator<=> (std::underlying_type_t< bit2 > x, bit2 y) constexpr
Definition at line 246 of file autogen.h.
operator<=>() [15/28]
constexpr std::strong_ordering thorin::core::operator<=> (std::underlying_type_t< conv > x, conv y) constexpr
Definition at line 423 of file autogen.h.
operator<=>() [16/28]
constexpr std::strong_ordering thorin::core::operator<=> (std::underlying_type_t< div > x, div y) constexpr
Definition at line 312 of file autogen.h.
operator<=>() [17/28]
constexpr std::strong_ordering thorin::core::operator<=> (std::underlying_type_t< extrema > x, extrema y) constexpr
Definition at line 394 of file autogen.h.
operator<=>() [18/28]
constexpr std::strong_ordering thorin::core::operator<=> (std::underlying_type_t< icmp > x, icmp y) constexpr
Definition at line 371 of file autogen.h.
operator<=>() [19/28]
constexpr std::strong_ordering thorin::core::operator<=> (std::underlying_type_t< mode > x, mode y) constexpr
Definition at line 187 of file autogen.h.
operator<=>() [20/28]
constexpr std::strong_ordering thorin::core::operator<=> (std::underlying_type_t< Mode > x, Mode y) constexpr
Definition at line 20 of file core.h.
operator<=>() [21/28]
constexpr std::strong_ordering thorin::core::operator<=> (std::underlying_type_t< nat > x, nat y) constexpr
Definition at line 134 of file autogen.h.
operator<=>() [22/28]
constexpr std::strong_ordering thorin::core::operator<=> (std::underlying_type_t< ncmp > x, ncmp y) constexpr
Definition at line 165 of file autogen.h.
operator<=>() [23/28]
constexpr std::strong_ordering thorin::core::operator<=> (std::underlying_type_t< pe > x, pe y) constexpr
Definition at line 470 of file autogen.h.
operator<=>() [24/28]
constexpr std::strong_ordering thorin::core::operator<=> (std::underlying_type_t< shr > x, shr y) constexpr
Definition at line 263 of file autogen.h.
operator<=>() [25/28]
constexpr std::strong_ordering thorin::core::operator<=> (std::underlying_type_t< trait > x, trait y) constexpr
Definition at line 452 of file autogen.h.
operator<=>() [26/28]
constexpr std::strong_ordering thorin::core::operator<=> (std::underlying_type_t< wrap > x, wrap y) constexpr
Definition at line 282 of file autogen.h.
operator<=>() [27/28]
constexpr std::strong_ordering thorin::core::operator<=> (trait x, std::underlying_type_t< trait > y) constexpr
Definition at line 452 of file autogen.h.
operator<=>() [28/28]
constexpr std::strong_ordering thorin::core::operator<=> (wrap x, std::underlying_type_t< wrap > y) constexpr
Definition at line 282 of file autogen.h.
operator==() [1/28]
constexpr bool thorin::core::operator== (bit1 x, std::underlying_type_t< bit1 > y) constexpr
Definition at line 215 of file autogen.h.
operator==() [2/28]
constexpr bool thorin::core::operator== (bit2 x, std::underlying_type_t< bit2 > y) constexpr
Definition at line 246 of file autogen.h.
operator==() [3/28]
constexpr bool thorin::core::operator== (conv x, std::underlying_type_t< conv > y) constexpr
Definition at line 423 of file autogen.h.
operator==() [4/28]
constexpr bool thorin::core::operator== (div x, std::underlying_type_t< div > y) constexpr
Definition at line 312 of file autogen.h.
operator==() [5/28]
constexpr bool thorin::core::operator== (extrema x, std::underlying_type_t< extrema > y) constexpr
Definition at line 394 of file autogen.h.
operator==() [6/28]
constexpr bool thorin::core::operator== (icmp x, std::underlying_type_t< icmp > y) constexpr
Definition at line 371 of file autogen.h.
operator==() [7/28]
constexpr bool thorin::core::operator== (mode x, std::underlying_type_t< mode > y) constexpr
Definition at line 187 of file autogen.h.
operator==() [8/28]
constexpr bool thorin::core::operator== (Mode x, std::underlying_type_t< Mode > y) constexpr
Definition at line 20 of file core.h.
operator==() [9/28]
constexpr bool thorin::core::operator== (nat x, std::underlying_type_t< nat > y) constexpr
Definition at line 134 of file autogen.h.
operator==() [10/28]
constexpr bool thorin::core::operator== (ncmp x, std::underlying_type_t< ncmp > y) constexpr
Definition at line 165 of file autogen.h.
operator==() [11/28]
constexpr bool thorin::core::operator== (pe x, std::underlying_type_t< pe > y) constexpr
Definition at line 470 of file autogen.h.
operator==() [12/28]
constexpr bool thorin::core::operator== (shr x, std::underlying_type_t< shr > y) constexpr
Definition at line 263 of file autogen.h.
operator==() [13/28]
constexpr bool thorin::core::operator== (std::underlying_type_t< bit1 > x, bit1 y) constexpr
Definition at line 215 of file autogen.h.
operator==() [14/28]
constexpr bool thorin::core::operator== (std::underlying_type_t< bit2 > x, bit2 y) constexpr
Definition at line 246 of file autogen.h.
operator==() [15/28]
constexpr bool thorin::core::operator== (std::underlying_type_t< conv > x, conv y) constexpr
Definition at line 423 of file autogen.h.
operator==() [16/28]
constexpr bool thorin::core::operator== (std::underlying_type_t< div > x, div y) constexpr
Definition at line 312 of file autogen.h.
operator==() [17/28]
constexpr bool thorin::core::operator== (std::underlying_type_t< extrema > x, extrema y) constexpr
Definition at line 394 of file autogen.h.
operator==() [18/28]
constexpr bool thorin::core::operator== (std::underlying_type_t< icmp > x, icmp y) constexpr
Definition at line 371 of file autogen.h.
operator==() [19/28]
constexpr bool thorin::core::operator== (std::underlying_type_t< mode > x, mode y) constexpr
Definition at line 187 of file autogen.h.
operator==() [20/28]
constexpr bool thorin::core::operator== (std::underlying_type_t< Mode > x, Mode y) constexpr
Definition at line 20 of file core.h.
operator==() [21/28]
constexpr bool thorin::core::operator== (std::underlying_type_t< nat > x, nat y) constexpr
Definition at line 134 of file autogen.h.
operator==() [22/28]
constexpr bool thorin::core::operator== (std::underlying_type_t< ncmp > x, ncmp y) constexpr
Definition at line 165 of file autogen.h.
operator==() [23/28]
constexpr bool thorin::core::operator== (std::underlying_type_t< pe > x, pe y) constexpr
Definition at line 470 of file autogen.h.
operator==() [24/28]
constexpr bool thorin::core::operator== (std::underlying_type_t< shr > x, shr y) constexpr
Definition at line 263 of file autogen.h.
operator==() [25/28]
constexpr bool thorin::core::operator== (std::underlying_type_t< trait > x, trait y) constexpr
Definition at line 452 of file autogen.h.
operator==() [26/28]
constexpr bool thorin::core::operator== (std::underlying_type_t< wrap > x, wrap y) constexpr
Definition at line 282 of file autogen.h.
operator==() [27/28]
constexpr bool thorin::core::operator== (trait x, std::underlying_type_t< trait > y) constexpr
Definition at line 452 of file autogen.h.
operator==() [28/28]
constexpr bool thorin::core::operator== (wrap x, std::underlying_type_t< wrap > y) constexpr
Definition at line 282 of file autogen.h.
operator^() [1/42]
constexpr auto thorin::core::operator^ (bit1 x, bit1 y) constexpr
Definition at line 215 of file autogen.h.
operator^() [2/42]
constexpr auto thorin::core::operator^ (bit1 x, std::underlying_type_t< bit1 > y) constexpr
Definition at line 215 of file autogen.h.
operator^() [3/42]
constexpr auto thorin::core::operator^ (bit2 x, bit2 y) constexpr
Definition at line 246 of file autogen.h.
operator^() [4/42]
constexpr auto thorin::core::operator^ (bit2 x, std::underlying_type_t< bit2 > y) constexpr
Definition at line 246 of file autogen.h.
operator^() [5/42]
constexpr auto thorin::core::operator^ (conv x, conv y) constexpr
Definition at line 423 of file autogen.h.
operator^() [6/42]
constexpr auto thorin::core::operator^ (conv x, std::underlying_type_t< conv > y) constexpr
Definition at line 423 of file autogen.h.
operator^() [7/42]
constexpr auto thorin::core::operator^ (div x, div y) constexpr
Definition at line 312 of file autogen.h.
operator^() [8/42]
constexpr auto thorin::core::operator^ (div x, std::underlying_type_t< div > y) constexpr
Definition at line 312 of file autogen.h.
operator^() [9/42]
constexpr auto thorin::core::operator^ (extrema x, extrema y) constexpr
Definition at line 394 of file autogen.h.
operator^() [10/42]
constexpr auto thorin::core::operator^ (extrema x, std::underlying_type_t< extrema > y) constexpr
Definition at line 394 of file autogen.h.
operator^() [11/42]
constexpr auto thorin::core::operator^ (icmp x, icmp y) constexpr
Definition at line 371 of file autogen.h.
operator^() [12/42]
constexpr auto thorin::core::operator^ (icmp x, std::underlying_type_t< icmp > y) constexpr
Definition at line 371 of file autogen.h.
operator^() [13/42]
constexpr auto thorin::core::operator^ (mode x, mode y) constexpr
Definition at line 187 of file autogen.h.
operator^() [14/42]
constexpr auto thorin::core::operator^ (Mode x, Mode y) constexpr
Definition at line 20 of file core.h.
operator^() [15/42]
constexpr auto thorin::core::operator^ (mode x, std::underlying_type_t< mode > y) constexpr
Definition at line 187 of file autogen.h.
operator^() [16/42]
constexpr auto thorin::core::operator^ (Mode x, std::underlying_type_t< Mode > y) constexpr
Definition at line 20 of file core.h.
operator^() [17/42]
constexpr auto thorin::core::operator^ (nat x, nat y) constexpr
Definition at line 134 of file autogen.h.
operator^() [18/42]
constexpr auto thorin::core::operator^ (nat x, std::underlying_type_t< nat > y) constexpr
Definition at line 134 of file autogen.h.
operator^() [19/42]
constexpr auto thorin::core::operator^ (ncmp x, ncmp y) constexpr
Definition at line 165 of file autogen.h.
operator^() [20/42]
constexpr auto thorin::core::operator^ (ncmp x, std::underlying_type_t< ncmp > y) constexpr
Definition at line 165 of file autogen.h.
operator^() [21/42]
constexpr auto thorin::core::operator^ (pe x, pe y) constexpr
Definition at line 470 of file autogen.h.
operator^() [22/42]
constexpr auto thorin::core::operator^ (pe x, std::underlying_type_t< pe > y) constexpr
Definition at line 470 of file autogen.h.
operator^() [23/42]
constexpr auto thorin::core::operator^ (shr x, shr y) constexpr
Definition at line 263 of file autogen.h.
operator^() [24/42]
constexpr auto thorin::core::operator^ (shr x, std::underlying_type_t< shr > y) constexpr
Definition at line 263 of file autogen.h.
operator^() [25/42]
constexpr auto thorin::core::operator^ (std::underlying_type_t< bit1 > x, bit1 y) constexpr
Definition at line 215 of file autogen.h.
operator^() [26/42]
constexpr auto thorin::core::operator^ (std::underlying_type_t< bit2 > x, bit2 y) constexpr
Definition at line 246 of file autogen.h.
operator^() [27/42]
constexpr auto thorin::core::operator^ (std::underlying_type_t< conv > x, conv y) constexpr
Definition at line 423 of file autogen.h.
operator^() [28/42]
constexpr auto thorin::core::operator^ (std::underlying_type_t< div > x, div y) constexpr
Definition at line 312 of file autogen.h.
operator^() [29/42]
constexpr auto thorin::core::operator^ (std::underlying_type_t< extrema > x, extrema y) constexpr
Definition at line 394 of file autogen.h.
operator^() [30/42]
constexpr auto thorin::core::operator^ (std::underlying_type_t< icmp > x, icmp y) constexpr
Definition at line 371 of file autogen.h.
operator^() [31/42]
constexpr auto thorin::core::operator^ (std::underlying_type_t< mode > x, mode y) constexpr
Definition at line 187 of file autogen.h.
operator^() [32/42]
constexpr auto thorin::core::operator^ (std::underlying_type_t< Mode > x, Mode y) constexpr
Definition at line 20 of file core.h.
operator^() [33/42]
constexpr auto thorin::core::operator^ (std::underlying_type_t< nat > x, nat y) constexpr
Definition at line 134 of file autogen.h.
operator^() [34/42]
constexpr auto thorin::core::operator^ (std::underlying_type_t< ncmp > x, ncmp y) constexpr
Definition at line 165 of file autogen.h.
operator^() [35/42]
constexpr auto thorin::core::operator^ (std::underlying_type_t< pe > x, pe y) constexpr
Definition at line 470 of file autogen.h.
operator^() [36/42]
constexpr auto thorin::core::operator^ (std::underlying_type_t< shr > x, shr y) constexpr
Definition at line 263 of file autogen.h.
operator^() [37/42]
constexpr auto thorin::core::operator^ (std::underlying_type_t< trait > x, trait y) constexpr
Definition at line 452 of file autogen.h.
operator^() [38/42]
constexpr auto thorin::core::operator^ (std::underlying_type_t< wrap > x, wrap y) constexpr
Definition at line 282 of file autogen.h.
operator^() [39/42]
constexpr auto thorin::core::operator^ (trait x, std::underlying_type_t< trait > y) constexpr
Definition at line 452 of file autogen.h.
operator^() [40/42]
constexpr auto thorin::core::operator^ (trait x, trait y) constexpr
Definition at line 452 of file autogen.h.
operator^() [41/42]
constexpr auto thorin::core::operator^ (wrap x, std::underlying_type_t< wrap > y) constexpr
Definition at line 282 of file autogen.h.
operator^() [42/42]
constexpr auto thorin::core::operator^ (wrap x, wrap y) constexpr
Definition at line 282 of file autogen.h.
operator|() [1/42]
constexpr auto thorin::core::operator| (bit1 x, bit1 y) constexpr
Definition at line 215 of file autogen.h.
operator|() [2/42]
constexpr auto thorin::core::operator| (bit1 x, std::underlying_type_t< bit1 > y) constexpr
Definition at line 215 of file autogen.h.
operator|() [3/42]
constexpr auto thorin::core::operator| (bit2 x, bit2 y) constexpr
Definition at line 246 of file autogen.h.
operator|() [4/42]
constexpr auto thorin::core::operator| (bit2 x, std::underlying_type_t< bit2 > y) constexpr
Definition at line 246 of file autogen.h.
operator|() [5/42]
constexpr auto thorin::core::operator| (conv x, conv y) constexpr
Definition at line 423 of file autogen.h.
operator|() [6/42]
constexpr auto thorin::core::operator| (conv x, std::underlying_type_t< conv > y) constexpr
Definition at line 423 of file autogen.h.
operator|() [7/42]
constexpr auto thorin::core::operator| (div x, div y) constexpr
Definition at line 312 of file autogen.h.
operator|() [8/42]
constexpr auto thorin::core::operator| (div x, std::underlying_type_t< div > y) constexpr
Definition at line 312 of file autogen.h.
operator|() [9/42]
constexpr auto thorin::core::operator| (extrema x, extrema y) constexpr
Definition at line 394 of file autogen.h.
operator|() [10/42]
constexpr auto thorin::core::operator| (extrema x, std::underlying_type_t< extrema > y) constexpr
Definition at line 394 of file autogen.h.
operator|() [11/42]
constexpr auto thorin::core::operator| (icmp x, icmp y) constexpr
Definition at line 371 of file autogen.h.
operator|() [12/42]
constexpr auto thorin::core::operator| (icmp x, std::underlying_type_t< icmp > y) constexpr
Definition at line 371 of file autogen.h.
operator|() [13/42]
constexpr auto thorin::core::operator| (mode x, mode y) constexpr
Definition at line 187 of file autogen.h.
operator|() [14/42]
constexpr auto thorin::core::operator| (Mode x, Mode y) constexpr
Definition at line 20 of file core.h.
operator|() [15/42]
constexpr auto thorin::core::operator| (mode x, std::underlying_type_t< mode > y) constexpr
Definition at line 187 of file autogen.h.
operator|() [16/42]
constexpr auto thorin::core::operator| (Mode x, std::underlying_type_t< Mode > y) constexpr
Definition at line 20 of file core.h.
operator|() [17/42]
constexpr auto thorin::core::operator| (nat x, nat y) constexpr
Definition at line 134 of file autogen.h.
operator|() [18/42]
constexpr auto thorin::core::operator| (nat x, std::underlying_type_t< nat > y) constexpr
Definition at line 134 of file autogen.h.
operator|() [19/42]
constexpr auto thorin::core::operator| (ncmp x, ncmp y) constexpr
Definition at line 165 of file autogen.h.
operator|() [20/42]
constexpr auto thorin::core::operator| (ncmp x, std::underlying_type_t< ncmp > y) constexpr
Definition at line 165 of file autogen.h.
operator|() [21/42]
constexpr auto thorin::core::operator| (pe x, pe y) constexpr
Definition at line 470 of file autogen.h.
operator|() [22/42]
constexpr auto thorin::core::operator| (pe x, std::underlying_type_t< pe > y) constexpr
Definition at line 470 of file autogen.h.
operator|() [23/42]
constexpr auto thorin::core::operator| (shr x, shr y) constexpr
Definition at line 263 of file autogen.h.
operator|() [24/42]
constexpr auto thorin::core::operator| (shr x, std::underlying_type_t< shr > y) constexpr
Definition at line 263 of file autogen.h.
operator|() [25/42]
constexpr auto thorin::core::operator| (std::underlying_type_t< bit1 > x, bit1 y) constexpr
Definition at line 215 of file autogen.h.
operator|() [26/42]
constexpr auto thorin::core::operator| (std::underlying_type_t< bit2 > x, bit2 y) constexpr
Definition at line 246 of file autogen.h.
operator|() [27/42]
constexpr auto thorin::core::operator| (std::underlying_type_t< conv > x, conv y) constexpr
Definition at line 423 of file autogen.h.
operator|() [28/42]
constexpr auto thorin::core::operator| (std::underlying_type_t< div > x, div y) constexpr
Definition at line 312 of file autogen.h.
operator|() [29/42]
constexpr auto thorin::core::operator| (std::underlying_type_t< extrema > x, extrema y) constexpr
Definition at line 394 of file autogen.h.
operator|() [30/42]
constexpr auto thorin::core::operator| (std::underlying_type_t< icmp > x, icmp y) constexpr
Definition at line 371 of file autogen.h.
operator|() [31/42]
constexpr auto thorin::core::operator| (std::underlying_type_t< mode > x, mode y) constexpr
Definition at line 187 of file autogen.h.
operator|() [32/42]
constexpr auto thorin::core::operator| (std::underlying_type_t< Mode > x, Mode y) constexpr
Definition at line 20 of file core.h.
operator|() [33/42]
constexpr auto thorin::core::operator| (std::underlying_type_t< nat > x, nat y) constexpr
Definition at line 134 of file autogen.h.
operator|() [34/42]
constexpr auto thorin::core::operator| (std::underlying_type_t< ncmp > x, ncmp y) constexpr
Definition at line 165 of file autogen.h.
operator|() [35/42]
constexpr auto thorin::core::operator| (std::underlying_type_t< pe > x, pe y) constexpr
Definition at line 470 of file autogen.h.
operator|() [36/42]
constexpr auto thorin::core::operator| (std::underlying_type_t< shr > x, shr y) constexpr
Definition at line 263 of file autogen.h.
operator|() [37/42]
constexpr auto thorin::core::operator| (std::underlying_type_t< trait > x, trait y) constexpr
Definition at line 452 of file autogen.h.
operator|() [38/42]
constexpr auto thorin::core::operator| (std::underlying_type_t< wrap > x, wrap y) constexpr
Definition at line 282 of file autogen.h.
operator|() [39/42]
constexpr auto thorin::core::operator| (trait x, std::underlying_type_t< trait > y) constexpr
Definition at line 452 of file autogen.h.
operator|() [40/42]
constexpr auto thorin::core::operator| (trait x, trait y) constexpr
Definition at line 452 of file autogen.h.
operator|() [41/42]
constexpr auto thorin::core::operator| (wrap x, std::underlying_type_t< wrap > y) constexpr
Definition at line 282 of file autogen.h.
operator|() [42/42]
constexpr auto thorin::core::operator| (wrap x, wrap y) constexpr
Definition at line 282 of file autogen.h.
register_normalizers()
void thorin::core::register_normalizers (Normalizers & normalizers)
Referenced by thorin_get_plugin().
Variable Documentation
Plugin_Id
constexpr plugin_t thorin::core::Plugin_Id = 0x1104c60000000000 static constexpr
Definition at line 10 of file autogen.h.