MimIR: mim::plug::direct Namespace Reference
mim::plug::direct Namespace Reference
The direct style Plugin
Classes
class CPS2DS
This is the second part of ds2cps.
class DS2CPS
Converts direct style function to cps functions.
Enumerations
%direct.ds2cps_pass
enum class ds2cps_pass : flags_t
%direct.cps2ds_pass
enum class cps2ds_pass : flags_t
Functions
void register_normalizers (Normalizers &normalizers)
Variables
static constexpr plugin_t Plugin_Id = 0x14a4c61150000000
%direct.cps2ds
enum class cps2ds : flags_t
const Def * normalize_cps2ds (const Def *, const Def *, const Def *fun)
cps2ds is directly converted to op_cps2ds_dep f in its normalizer.
%direct.cps2ds_dep
enum class cps2ds_dep : flags_t
const Def * op_cps2ds_dep (const Def *k)
Detailed Description
The direct style Plugin
Enumeration Type Documentation
cps2ds
enum class mim::plug::direct::cps2ds : flags_t strong
Definition at line 14 of file autogen.h.
cps2ds_dep
enum class mim::plug::direct::cps2ds_dep : flags_t strong
Definition at line 22 of file autogen.h.
cps2ds_pass
enum class mim::plug::direct::cps2ds_pass : flags_t strong
Definition at line 36 of file autogen.h.
ds2cps_pass
enum class mim::plug::direct::ds2cps_pass : flags_t strong
Definition at line 29 of file autogen.h.
Function Documentation
normalize_cps2ds()
const Def * mim::plug::direct::normalize_cps2ds (const Def * , const Def * , const Def * fun)
cps2ds is directly converted to op_cps2ds_dep f in its normalizer.
Definition at line 8 of file normalizers.cpp.
References op_cps2ds_dep().
op_cps2ds_dep()
const Def * mim::plug::direct::op_cps2ds_dep (const Def * k) inline
Definition at line 15 of file direct.h.
References mim::Pi::dom(), mim::Pi::isa_cn(), mim::VarRewriter::rewrite(), mim::Def::type(), and mim::Def::world().
Referenced by mim::plug::autodiff::AutoDiffEval::augment_app(), mim::plug::autodiff::AutoDiffEval::augment_pack(), normalize_cps2ds(), mim::plug::matrix::LowerMatrixHighLevelMapRed::rewrite_(), and mim::plug::matrix::LowerMatrixMediumLevel::rewrite_().
register_normalizers()
void mim::plug::direct::register_normalizers (Normalizers & normalizers)
Referenced by mim_get_plugin().
Variable Documentation
Plugin_Id
plugin_t mim::plug::direct::Plugin_Id = 0x14a4c61150000000 static constexpr
Definition at line 10 of file autogen.h.