MimIR: mim::ll Namespace Reference
mim::ll Namespace Reference
Classes
struct BB
class Emitter
Functions
void emit (World &, std::ostream &)
int compile (World &, std::string name)
int compile (World &, std::string ll, std::string out)
int compile_and_run (World &, std::string name, std::string args={})
Function Documentation
compile() [1/2]
int mim::ll::compile (World & world, std::string ll, std::string out)
Definition at line 1073 of file ll.cpp.
References emit(), mim::fmt(), and mim::sys::system().
compile() [2/2]
int mim::ll::compile (World & world, std::string name)
Definition at line 1064 of file ll.cpp.
References compile().
Referenced by compile(), and compile_and_run().
compile_and_run()
int mim::ll::compile_and_run (World & world, std::string name, std::string args = {})
Definition at line 1081 of file ll.cpp.
References compile(), mim::error(), and mim::sys::run().
emit()
void mim::ll::emit (World & world, std::ostream & ostream)
Definition at line 1059 of file ll.cpp.
References mim::Phase::run().
Referenced by compile(), and mim_get_plugin().