MimIR: mim::plug::demo Namespace Reference
mim::plug::demo Namespace Reference
The demo Plugin
Functions
void register_normalizers (Normalizers &normalizers)
Variables
static constexpr plugin_t Plugin_Id = 0x1463900000000000
%demo.const_idx
enum class const_idx : flags_t
const Def * normalize_const (const Def *type, const Def *, const Def *arg)
Detailed Description
The demo Plugin
Enumeration Type Documentation
const_idx
enum class mim::plug::demo::const_idx : flags_t strong
Definition at line 14 of file autogen.h.
Function Documentation
normalize_const()
const Def * mim::plug::demo::normalize_const (const Def * type, const Def * , const Def * arg)
Definition at line 7 of file normalizers.cpp.
References mim::World::lit(), and mim::Def::world().
register_normalizers()
void mim::plug::demo::register_normalizers (Normalizers & normalizers)
Referenced by mim_get_plugin().
Variable Documentation
Plugin_Id
plugin_t mim::plug::demo::Plugin_Id = 0x1463900000000000 static constexpr
Definition at line 10 of file autogen.h.