MimIR: mim::plug::ord Namespace Reference
mim::plug::ord Namespace Reference
The ord Plugin
Enumerations
%ord.Key
enum class Key : flags_t
%ord.Set
enum class Set : flags_t
%ord.Map
enum class Map : flags_t
%ord.create_set
enum class create_set : flags_t
%ord.create_map
enum class create_map : flags_t
%ord.is_empty_set
enum class is_empty_set : flags_t
%ord.is_empty_map
enum class is_empty_map : flags_t
Functions
void register_normalizers (Normalizers &normalizers)
Variables
static constexpr plugin_t Plugin_Id = 0x4131400000000000
%ord.init
enum class init : flags_t {
set = 0x4131400000000300 ,
map = 0x4131400000000301
}
template<init id>
const Def * normalize_init (const Def *type, const Def *callee, const Def *arg)
%ord.size
enum class size : flags_t {
set = 0x4131400000000600 ,
map = 0x4131400000000601
}
template<size>
const Def * normalize_size (const Def *, const Def *, const Def *arg)
%ord.get
enum class get : flags_t
const Def * normalize_get (const Def *, const Def *, const Def *arg)
%ord.contains
enum class contains : flags_t {
set = 0x4131400000000a00 ,
map = 0x4131400000000a01
}
template<contains id>
const Def * normalize_contains (const Def *, const Def *, const Def *arg)
%ord.insert
enum class insert : flags_t {
set = 0x4131400000000b00 ,
map = 0x4131400000000b01
}
template<insert id>
const Def * normalize_insert (const Def *type, const Def *, const Def *arg)
Detailed Description
The ord Plugin
Enumeration Type Documentation
contains
enum class mim::plug::ord::contains : flags_t strong
Enumerator
set
map
Definition at line 95 of file autogen.h.
create_map
enum class mim::plug::ord::create_map : flags_t strong
Definition at line 54 of file autogen.h.
create_set
enum class mim::plug::ord::create_set : flags_t strong
Definition at line 47 of file autogen.h.
get
enum class mim::plug::ord::get : flags_t strong
Definition at line 87 of file autogen.h.
init
enum class mim::plug::ord::init : flags_t strong
Enumerator
set
map
Definition at line 35 of file autogen.h.
insert
enum class mim::plug::ord::insert : flags_t strong
Enumerator
set
map
Definition at line 107 of file autogen.h.
is_empty_map
enum class mim::plug::ord::is_empty_map : flags_t strong
Definition at line 80 of file autogen.h.
is_empty_set
enum class mim::plug::ord::is_empty_set : flags_t strong
Definition at line 73 of file autogen.h.
Key
enum class mim::plug::ord::Key : flags_t strong
Definition at line 14 of file autogen.h.
Map
enum class mim::plug::ord::Map : flags_t strong
Definition at line 28 of file autogen.h.
Set
enum class mim::plug::ord::Set : flags_t strong
Definition at line 21 of file autogen.h.
size
enum class mim::plug::ord::size : flags_t strong
Enumerator
set
map
Definition at line 61 of file autogen.h.
Function Documentation
normalize_contains()
template<contains id> const Def * mim::plug::ord::normalize_contains (const Def * , const Def * , const Def * arg)
Definition at line 32 of file normalizers.cpp.
References mim::Axm::isa(), map, mim::Def::projs(), and mim::Def::world().
normalize_get()
const Def * mim::plug::ord::normalize_get (const Def * , const Def * , const Def * arg)
Definition at line 19 of file normalizers.cpp.
References mim::Axm::isa(), map, and mim::Def::projs().
normalize_init()
template<init id> const Def * mim::plug::ord::normalize_init (const Def * type, const Def * callee, const Def * arg)
Definition at line 9 of file normalizers.cpp.
normalize_insert()
template<insert id> const Def * mim::plug::ord::normalize_insert (const Def * type, const Def * , const Def * arg)
Definition at line 51 of file normalizers.cpp.
References mim::Axm::isa(), mim::Lit::isa(), map, mim::Def::projs(), and set.
normalize_size()
template<size> const Def * mim::plug::ord::normalize_size (const Def * , const Def * , const Def * arg)
Definition at line 14 of file normalizers.cpp.
References mim::Axm::isa().
register_normalizers()
void mim::plug::ord::register_normalizers (Normalizers & normalizers)
Referenced by mim_get_plugin().
Variable Documentation
Plugin_Id
plugin_t mim::plug::ord::Plugin_Id = 0x4131400000000000 static constexpr
Definition at line 10 of file autogen.h.