Thorin: thorin::matrix Namespace Reference
thorin::matrix Namespace Reference
Classes
class LowerMatrixHighLevelMapRed
Resolves lowering of high level operations into medium/other high-level operations.
class LowerMatrixLowLevel
In this phase, we lower all matrix operations and types to the low-level representation using pointers.
class LowerMatrixMediumLevel
In this step, we lower map_reduce operations into affine for loops making the iteration scheme explicit.
Enumerations
lower_matrix_high_level_map_reduce
enum lower_matrix_high_level_map_reduce : flags_t
lower_matrix_medium_level
enum lower_matrix_medium_level : flags_t
Mat
enum Mat : flags_t
sum
enum sum : flags_t
constMat
enum constMat : flags_t
internal_map_reduce_cleanup
enum internal_map_reduce_cleanup : flags_t
lower_matrix_low_level
enum lower_matrix_low_level : flags_t
init
enum init : flags_t
Functions
const Def * zero_int (World &w, Ref n, Ref S, Ref mem, nat_t m)
mat.zero: Π [n: .Nat, S: «n; .Nat», m: .Nat] -> mat.Mat (n,S,(.Idx m));
const Def * op_read (Ref mem, Ref matrix, Ref idx)
u64 get_max_index (u64 init, Defs inputs)
Matrix normalizer for product on two-dimensional matrices.
void findAndReplaceAll (std::string &data, std::string toSearch, std::string replaceStr)
std::optional< Ref > internal_function_of_axiom (const Axiom *axiom, Ref meta_args, Ref args)
static Ref op_lea_tuple (Ref arr, Ref tuple)
static Ref op_pack_tuple (u64 n, Ref tuple, Ref val)
static Ref arrTyOfMatrixTy (Ref S, Ref T)
std::pair< Lam *, Ref > counting_for (Ref bound, DefArray acc, Ref exit, const char *name="for_body")
void register_normalizers (Normalizers &normalizers)
Variables
static constexpr plugin_t Plugin_Id = 0x3825532990000000
read
enum read : flags_t
Ref normalize_read (Ref type, Ref callee, Ref arg)
Normalizer for read opertions.
prod
enum prod : flags_t
Ref normalize_prod (Ref type, Ref callee, Ref arg)
shape
enum shape : flags_t
Ref normalize_shape (Ref type, Ref callee, Ref arg)
Normalizer for transpose operations.
map_reduce
enum map_reduce : flags_t
Ref normalize_map_reduce (Ref type, Ref callee, Ref arg)
map_reduce normalizers
insert
enum insert : flags_t
Ref normalize_insert (Ref type, Ref callee, Ref arg)
Normalizer for write operations TODO: implement.
transpose
enum transpose : flags_t
Ref normalize_transpose (Ref type, Ref callee, Ref arg)
Enumeration Type Documentation
constMat
enum thorin::matrix::constMat : flags_t
Definition at line 90 of file autogen.h.
init
enum thorin::matrix::init : flags_t
Definition at line 144 of file autogen.h.
insert
enum thorin::matrix::insert : flags_t
Definition at line 132 of file autogen.h.
internal_map_reduce_cleanup
enum thorin::matrix::internal_map_reduce_cleanup : flags_t
Definition at line 100 of file autogen.h.
lower_matrix_high_level_map_reduce
enum thorin::matrix::lower_matrix_high_level_map_reduce : flags_t
Definition at line 14 of file autogen.h.
lower_matrix_low_level
enum thorin::matrix::lower_matrix_low_level : flags_t
Definition at line 110 of file autogen.h.
lower_matrix_medium_level
enum thorin::matrix::lower_matrix_medium_level : flags_t
Definition at line 24 of file autogen.h.
map_reduce
enum thorin::matrix::map_reduce : flags_t
Definition at line 120 of file autogen.h.
Mat
enum thorin::matrix::Mat : flags_t
Definition at line 58 of file autogen.h.
prod
enum thorin::matrix::prod : flags_t
Definition at line 46 of file autogen.h.
read
enum thorin::matrix::read : flags_t
Definition at line 34 of file autogen.h.
shape
enum thorin::matrix::shape : flags_t
Definition at line 78 of file autogen.h.
sum
enum thorin::matrix::sum : flags_t
Definition at line 68 of file autogen.h.
transpose
enum thorin::matrix::transpose : flags_t
Definition at line 154 of file autogen.h.
Function Documentation
arrTyOfMatrixTy()
static Ref thorin::matrix::arrTyOfMatrixTy (Ref S, Ref T) static
Definition at line 44 of file lower_matrix_lowlevel.cpp.
References thorin::Def::num_projs(), thorin::Def::proj(), and thorin::Def::world().
Referenced by thorin::matrix::LowerMatrixLowLevel::rewrite_imm().
counting_for()
std::pair< Lam *, Ref > thorin::matrix::counting_for (Ref bound, DefArray acc, Ref exit, const char * name = "for_body")
Definition at line 24 of file lower_matrix_mediumlevel.cpp.
References thorin::affine::op_for(), thorin::Def::set(), thorin::World::tuple(), thorin::Def::type(), and thorin::Def::world().
Referenced by thorin::matrix::LowerMatrixMediumLevel::rewrite_().
findAndReplaceAll()
void thorin::matrix::findAndReplaceAll (std::string & data, std::string toSearch, std::string replaceStr)
Definition at line 15 of file lower_matrix_highlevel.cpp.
Referenced by internal_function_of_axiom().
get_max_index()
u64 thorin::matrix::get_max_index (u64 init, Defs inputs)
Matrix normalizer for product on two-dimensional matrices.
product (constMat v1, constMat v2) -> constMat v1 * v2 * dim (TODO: implement)
product (constMat v, m) -> ... (TODO: implement)
product (m, constMat v) -> ... (TODO: implement)
product (id, m) -> m (TODO: check)
product (m, id) -> m
map(constMat v, f) -> constMat f(v) (TODO: implement)
map f (map g m) -> map (f . g) m (TODO: implement)
map f (zipWith g m1 m2) -> zipWith (f . g) m1 m2 (TODO: implement)
Definition at line 76 of file normalizers.cpp.
References thorin::isa_lit().
internal_function_of_axiom()
std::optional< Ref > thorin::matrix::internal_function_of_axiom (const Axiom * axiom, Ref meta_args, Ref args)
Definition at line 30 of file lower_matrix_highlevel.cpp.
References findAndReplaceAll(), INTERNAL_PREFIX, thorin::direct::op_cps2ds_dep(), thorin::Def::sym(), and thorin::Def::world().
Referenced by thorin::matrix::LowerMatrixHighLevelMapRed::rewrite_().
normalize_insert()
Ref thorin::matrix::normalize_insert (Ref type, Ref callee, Ref arg)
Normalizer for write operations TODO: implement.
Definition at line 41 of file normalizers.cpp.
References thorin::World::raw_app(), and thorin::Def::world().
normalize_map_reduce()
Ref thorin::matrix::normalize_map_reduce (Ref type, Ref callee, Ref arg)
map_reduce normalizers
TODO: map_reduce (..., ((idx,map_reduce([out, ]...), ...))) -> unify idx, out (out is implicit), name vars apart requires: same reduction, distributive reduction we assume distributivity of the reduction function
Definition at line 97 of file normalizers.cpp.
References thorin::World::raw_app(), and thorin::Def::world().
normalize_prod()
Ref thorin::matrix::normalize_prod (Ref type, Ref callee, Ref arg)
Definition at line 104 of file normalizers.cpp.
References thorin::World::raw_app(), and thorin::Def::world().
normalize_read()
Ref thorin::matrix::normalize_read (Ref type, Ref callee, Ref arg)
Normalizer for read opertions.
read(constMat v) -> v
read(insert m v i, i) -> v (TODO: check with map_reduce)
read(insert m v i, j) -> read(m, i) if i <> j (TODO: wanted? useful?)
read(transpose m, (i,j)) -> read(m, (j,i)) (TODO: check for map_reduce)
read(product m1 m2, (i,j)) -> ... (TODO: check with map_reduce)
read (map_reduce f) idx = loop f idx (TODO: implement => use inner loop from lowering phase)
Definition at line 19 of file normalizers.cpp.
References thorin::Def::projs(), and thorin::Def::world().
normalize_shape()
Ref thorin::matrix::normalize_shape (Ref type, Ref callee, Ref arg)
Normalizer for transpose operations.
transpose (constMat v) -> cosntMat v (TODO: implement)
transpose (insert m v (i,j)) -> insert (transpose m) v (j,i) (TODO: implement, maybe other way around?)
transpose (tranpose m) -> m (TODO: implement)
shape (@mat n (k1,k2,...,kn) i) -> (k1,k2,...,kn)#i (TODO: implement)
Definition at line 57 of file normalizers.cpp.
References thorin::Def::projs(), and thorin::Def::world().
normalize_transpose()
Ref thorin::matrix::normalize_transpose (Ref type, Ref callee, Ref arg)
Definition at line 109 of file normalizers.cpp.
References thorin::World::raw_app(), and thorin::Def::world().
op_lea_tuple()
static Ref thorin::matrix::op_lea_tuple (Ref arr, Ref tuple) static
Definition at line 22 of file lower_matrix_lowlevel.cpp.
References thorin::Def::num_projs(), thorin::mem::op_lea(), thorin::Def::proj(), thorin::Def::type(), and thorin::Def::world().
Referenced by thorin::matrix::LowerMatrixLowLevel::rewrite_imm().
op_pack_tuple()
static Ref thorin::matrix::op_pack_tuple (u64 n, Ref tuple, Ref val) static
Definition at line 31 of file lower_matrix_lowlevel.cpp.
References thorin::Def::proj(), thorin::Def::type(), and thorin::Def::world().
Referenced by thorin::matrix::LowerMatrixLowLevel::rewrite_imm().
op_read()
const Def * thorin::matrix::op_read (Ref mem, Ref matrix, Ref idx) inline
Definition at line 19 of file matrix.h.
References thorin::Def::type(), and thorin::Def::world().
Referenced by thorin::matrix::LowerMatrixMediumLevel::rewrite_().
register_normalizers()
void thorin::matrix::register_normalizers (Normalizers & normalizers)
Referenced by thorin_get_plugin().
zero_int()
const Def * thorin::matrix::zero_int (World & w, Ref n, Ref S, Ref mem, nat_t m) inline
mat.zero: Π [n: .Nat, S: «n; .Nat», m: .Nat] -> mat.Mat (n,S,(.Idx m));
Definition at line 14 of file matrix.h.
References thorin::World::app(), and thorin::World::ax().
Variable Documentation
Plugin_Id
constexpr plugin_t thorin::matrix::Plugin_Id = 0x3825532990000000 static constexpr
Definition at line 9 of file autogen.h.