Thorin: thorin::utf8 Namespace Reference
thorin::utf8 Namespace Reference
Classes
class Lexer
Functions
size_t num_bytes (char8_t c)
Returns the expected number of bytes for an UTF-8 char sequence by inspecting the first byte.
char32_t encode (std::istream &is)
Encodes the next sequence of bytes from is as UTF-32.
bool decode (std::ostream &os, char32_t c)
Decodes the UTF-32 char c to UTF-8 and writes the sequence of bytes to os.
char32_t append (char32_t c, char32_t b)
Append b to c for converting UTF-8 to UTF-32.
char32_t first (char32_t c, char32_t num)
Get relevant bits of first UTF-8 byte c of a multi-byte sequence consisting of num bytes.
std::optional< char8_t > is_valid (char8_t c)
Is the 2nd, 3rd, or 4th byte of an UTF-8 byte sequence valid?
Variables
static constexpr size_t Max = 4
Maximal number of char8_ts of an UTF-8 byte sequence.
static constexpr char32_t BOM = 0xfeff_u32
Byte Order Mark.
static constexpr char32_t EoF = (char32_t)std::istream::traits_type::eof()
End of File.
static constexpr char32_t Err = (char32_t)-2
Erroneous UTF char.
Function Documentation
append()
char32_t thorin::utf8::append (char32_t c, char32_t b) inline
Append b to c for converting UTF-8 to UTF-32.
Definition at line 22 of file utf8.h.
Referenced by thorin::utf8::Lexer< Max_Ahead >::accept(), thorin::utf8::Lexer< Max_Ahead >::accept_if(), and encode().
decode()
bool thorin::utf8::decode (std::ostream & os, char32_t c)
Decodes the UTF-32 char c to UTF-8 and writes the sequence of bytes to os.
Returns
false on error.
Definition at line 42 of file utf8.cpp.
encode()
char32_t thorin::utf8::encode (std::istream & is)
Encodes the next sequence of bytes from is as UTF-32.
Returns
std::nullopt on error.
Definition at line 22 of file utf8.cpp.
References append(), EoF, Err, first(), is_valid(), and num_bytes().
Referenced by thorin::utf8::Lexer< Max_Ahead >::next().
first()
char32_t thorin::utf8::first (char32_t c, char32_t num) inline
Get relevant bits of first UTF-8 byte c of a multi-byte sequence consisting of num bytes.
Definition at line 25 of file utf8.h.
Referenced by encode().
is_valid()
std::optional< char8_t > thorin::utf8::is_valid (char8_t c) inline
Is the 2nd, 3rd, or 4th byte of an UTF-8 byte sequence valid?
Definition at line 28 of file utf8.h.
Referenced by encode().
num_bytes()
size_t thorin::utf8::num_bytes (char8_t c)
Returns the expected number of bytes for an UTF-8 char sequence by inspecting the first byte.
Retuns 0 if invalid.
Definition at line 14 of file utf8.cpp.
Referenced by encode().
Variable Documentation
BOM
constexpr char32_t thorin::utf8::BOM = 0xfeff_u32 static constexpr
Byte Order Mark.
Definition at line 13 of file utf8.h.
EoF
constexpr char32_t thorin::utf8::EoF = (char32_t)std::istream::traits_type::eof() static constexpr
End of File.
Definition at line 14 of file utf8.h.
Referenced by encode(), thorin::fe::Lexer::lex(), and thorin::utf8::Lexer< Max_Ahead >::next().
Err
constexpr char32_t thorin::utf8::Err = (char32_t)-2 static constexpr
Erroneous UTF char.
Definition at line 15 of file utf8.h.
Referenced by encode(), and thorin::fe::Lexer::lex().
Max
constexpr size_t thorin::utf8::Max = 4 static constexpr
Maximal number of char8_ts of an UTF-8 byte sequence.
Definition at line 12 of file utf8.h.