MimIR: mim::plug::refly Namespace Reference
mim::plug::refly Namespace Reference
The refly Plugin
Enumerations
%refly.Code
enum class Code : flags_t
%refly.error
enum class error : flags_t
%refly.warn
enum class warn : flags_t
%refly.info
enum class info : flags_t
%refly.verbose
enum class verbose : flags_t
%refly.debug
enum class debug : flags_t
%refly.remove_dbg_repl
enum class remove_dbg_repl : flags_t
Functions
void register_normalizers (Normalizers &normalizers)
Variables
static constexpr plugin_t Plugin_Id = 0x4c61cd6800000000
%refly.reify
enum class reify : flags_t
const Def * normalize_reify (const Def *, const Def *, const Def *arg)
%refly.reflect
enum class reflect : flags_t
const Def * normalize_reflect (const Def *, const Def *, const Def *arg)
%refly.type
enum class type : flags_t
const Def * normalize_type (const Def *, const Def *, const Def *arg)
%refly.gid
enum class gid : flags_t
const Def * normalize_gid (const Def *, const Def *, const Def *arg)
%refly.dbg
enum class dbg : flags_t {
tmp = 0x4c61cd6800000a00 ,
perm = 0x4c61cd6800000a01
}
template<dbg id>
const Def * normalize_dbg (const Def *, const Def *, const Def *arg)
%refly.equiv
enum class equiv : flags_t {
ae = 0x4c61cd6800000b00 ,
struc_ne = ae ,
aE = 0x4c61cd6800000b01 ,
struc_eq = aE ,
Ae = 0x4c61cd6800000b02 ,
alpha_ne = Ae ,
AE = 0x4c61cd6800000b03 ,
alpha_eq = AE
}
template<equiv id>
const Def * normalize_equiv (const Def *, const Def *, const Def *arg)
%refly.check
enum class check : flags_t
const Def * normalize_check (const Def *type, const Def *, const Def *arg)
%refly.refine
enum class refine : flags_t
const Def * normalize_refine (const Def *, const Def *, const Def *arg)
Detailed Description
The refly Plugin
Enumeration Type Documentation
check
enum class mim::plug::refly::check : flags_t strong
Definition at line 118 of file autogen.h.
Code
enum class mim::plug::refly::Code : flags_t strong
Definition at line 14 of file autogen.h.
dbg
enum class mim::plug::refly::dbg : flags_t strong
Enumerator
tmp
perm
Definition at line 88 of file autogen.h.
debug
enum class mim::plug::refly::debug : flags_t strong
Definition at line 81 of file autogen.h.
equiv
enum class mim::plug::refly::equiv : flags_t strong
Enumerator
ae
struc_ne
aE
struc_eq
Ae
alpha_ne
AE
alpha_eq
Definition at line 100 of file autogen.h.
error
enum class mim::plug::refly::error : flags_t strong
Definition at line 53 of file autogen.h.
gid
enum class mim::plug::refly::gid : flags_t strong
Definition at line 45 of file autogen.h.
info
enum class mim::plug::refly::info : flags_t strong
Definition at line 67 of file autogen.h.
refine
enum class mim::plug::refly::refine : flags_t strong
Definition at line 126 of file autogen.h.
reflect
enum class mim::plug::refly::reflect : flags_t strong
Definition at line 29 of file autogen.h.
reify
enum class mim::plug::refly::reify : flags_t strong
Definition at line 21 of file autogen.h.
remove_dbg_repl
enum class mim::plug::refly::remove_dbg_repl : flags_t strong
Definition at line 134 of file autogen.h.
type
enum class mim::plug::refly::type : flags_t strong
Definition at line 37 of file autogen.h.
verbose
enum class mim::plug::refly::verbose : flags_t strong
Definition at line 74 of file autogen.h.
warn
enum class mim::plug::refly::warn : flags_t strong
Definition at line 60 of file autogen.h.
Function Documentation
normalize_check()
const Def * mim::plug::refly::normalize_check (const Def * type, const Def * , const Def * arg)
Definition at line 81 of file normalizers.cpp.
References mim::Def::projs(), and mim::tuple2str().
normalize_dbg()
template<dbg id> const Def * mim::plug::refly::normalize_dbg (const Def * , const Def * , const Def * arg)
Definition at line 43 of file normalizers.cpp.
References perm, and mim::Def::projs().
normalize_equiv()
template<equiv id> const Def * mim::plug::refly::normalize_equiv (const Def * , const Def * , const Def * arg)
Definition at line 67 of file normalizers.cpp.
References Ae, aE, mim::Checker::alpha(), mim::error(), mim::Def::loc(), and mim::Def::projs().
normalize_gid()
const Def * mim::plug::refly::normalize_gid (const Def * , const Def * , const Def * arg)
Definition at line 64 of file normalizers.cpp.
References mim::Def::gid(), mim::World::lit_nat(), and mim::Def::world().
normalize_refine()
const Def * mim::plug::refly::normalize_refine (const Def * , const Def * , const Def * arg)
Definition at line 53 of file normalizers.cpp.
References mim::Lit::isa(), and mim::Def::projs().
normalize_reflect()
const Def * mim::plug::refly::normalize_reflect (const Def * , const Def * , const Def * arg)
Definition at line 51 of file normalizers.cpp.
normalize_reify()
const Def * mim::plug::refly::normalize_reify (const Def * , const Def * , const Def * arg)
Definition at line 49 of file normalizers.cpp.
normalize_type()
const Def * mim::plug::refly::normalize_type (const Def * , const Def * , const Def * arg)
Definition at line 63 of file normalizers.cpp.
References mim::Def::type().
register_normalizers()
void mim::plug::refly::register_normalizers (Normalizers & normalizers)
Referenced by mim_get_plugin().
Variable Documentation
Plugin_Id
plugin_t mim::plug::refly::Plugin_Id = 0x4c61cd6800000000 static constexpr
Definition at line 10 of file autogen.h.