Thorin: thorin::debug Namespace Reference
thorin::debug Namespace Reference
add c++ bindings to call the axioms here preferably using inlined functions
Classes
class DebugRemovePerm
removes all permanent debug markers for code gen
Enumerations
enum class dbg : flags_t
enum class dbg_perm : flags_t
Functions
void debug_print (const Def *def)
const Def * normalize_dbg (const Def *, const Def *, const Def *arg, const Def *)
const Def * normalize_dbg_perm (const Def *type, const Def *callee, const Def *arg, const Def *dbg)
bool operator== (dbg lhs, flags_t rhs)
flags_t operator& (dbg lhs, flags_t rhs)
flags_t operator& (dbg lhs, dbg rhs)
flags_t operator| (dbg lhs, flags_t rhs)
flags_t operator| (dbg lhs, dbg rhs)
bool operator== (dbg_perm lhs, flags_t rhs)
flags_t operator& (dbg_perm lhs, flags_t rhs)
flags_t operator& (dbg_perm lhs, dbg_perm rhs)
flags_t operator| (dbg_perm lhs, flags_t rhs)
flags_t operator| (dbg_perm lhs, dbg_perm rhs)
void register_normalizers (Normalizers &normalizers)
Variables
static constexpr dialect_t Dialect_Id = 0x1460d62000000000
Detailed Description
add c++ bindings to call the axioms here preferably using inlined functions
Enumeration Type Documentation
dbg
enum class thorin::debug::dbg : flags_t strong
Definition at line 11 of file autogen.h.
dbg_perm
enum class thorin::debug::dbg_perm : flags_t strong
Definition at line 22 of file autogen.h.
Function Documentation
debug_print()
void thorin::debug::debug_print (const Def * def)
Definition at line 27 of file debug.cpp.
References BLANK, thorin::Def::node_name(), thorin::Def::num_extended_ops(), thorin::Def::num_ops(), thorin::Def::num_projs(), thorin::Def::type(), thorin::Def::unique_name(), thorin::Def::world(), and YELLOW.
Referenced by normalize_dbg(), and normalize_dbg_perm().
normalize_dbg()
const Def * thorin::debug::normalize_dbg (const Def * , const Def * , const Def * arg, const Def *)
Definition at line 7 of file normalizers.cpp.
References debug_print().
normalize_dbg_perm()
const Def * thorin::debug::normalize_dbg_perm (const Def * type, const Def * callee, const Def * arg, const Def * dbg)
Definition at line 12 of file normalizers.cpp.
References debug_print(), and thorin::Def::world().
operator&() [1/4]
flags_t thorin::debug::operator& (dbg lhs, dbg rhs) inline
Definition at line 16 of file autogen.h.
operator&() [2/4]
flags_t thorin::debug::operator& (dbg lhs, flags_t rhs) inline
Definition at line 15 of file autogen.h.
operator&() [3/4]
flags_t thorin::debug::operator& (dbg_perm lhs, dbg_perm rhs) inline
Definition at line 27 of file autogen.h.
operator&() [4/4]
flags_t thorin::debug::operator& (dbg_perm lhs, flags_t rhs) inline
Definition at line 26 of file autogen.h.
operator==() [1/2]
bool thorin::debug::operator== (dbg lhs, flags_t rhs) inline
Definition at line 14 of file autogen.h.
operator==() [2/2]
bool thorin::debug::operator== (dbg_perm lhs, flags_t rhs) inline
Definition at line 25 of file autogen.h.
operator|() [1/4]
flags_t thorin::debug::operator| (dbg lhs, dbg rhs) inline
Definition at line 18 of file autogen.h.
operator|() [2/4]
flags_t thorin::debug::operator| (dbg lhs, flags_t rhs) inline
Definition at line 17 of file autogen.h.
operator|() [3/4]
flags_t thorin::debug::operator| (dbg_perm lhs, dbg_perm rhs) inline
Definition at line 29 of file autogen.h.
operator|() [4/4]
flags_t thorin::debug::operator| (dbg_perm lhs, flags_t rhs) inline
Definition at line 28 of file autogen.h.
register_normalizers()
void thorin::debug::register_normalizers (Normalizers & normalizers)
Variable Documentation
Dialect_Id
constexpr dialect_t thorin::debug::Dialect_Id = 0x1460d62000000000 static constexpr
Definition at line 9 of file autogen.h.