MimIR: mim::plug::affine Namespace Reference
mim::plug::affine Namespace Reference
The affine Plugin
Classes
class LowerFor
Lowers the for axiom to actual control flow in CPS.
Enumerations
%affine.lower_for_pass
enum class lower_for_pass : flags_t
Variables
static constexpr plugin_t Plugin_Id = 0x871ca3c60000000
%affine.For
enum class For : flags_t
const Def * fn_for (World &w, Defs params)
const Def * op_for (World &w, const Def *begin, const Def *end, const Def *step, Defs inits, const Def *body, const Def *brk)
Returns a fully applied affine_for axiom.
Detailed Description
The affine Plugin
Enumeration Type Documentation
For
enum class mim::plug::affine::For : flags_t strong
Definition at line 14 of file autogen.h.
lower_for_pass
enum class mim::plug::affine::lower_for_pass : flags_t strong
Definition at line 21 of file autogen.h.
Function Documentation
fn_for()
const Def * mim::plug::affine::fn_for (World & w, Defs params) inline
Definition at line 13 of file affine.h.
Referenced by op_for().
op_for()
const Def * mim::plug::affine::op_for (World & w, const Def * begin, const Def * end, const Def * step, Defs inits, const Def * body, const Def * brk) inline
Returns a fully applied affine_for axiom.
See documentation for affine.For axiom in The affine Plugin.
Definition at line 20 of file affine.h.
References fn_for().
Referenced by mim::plug::matrix::counting_for().
Variable Documentation
Plugin_Id
plugin_t mim::plug::affine::Plugin_Id = 0x871ca3c60000000 static constexpr
Definition at line 10 of file autogen.h.