Thorin: thorin::compile Namespace Reference
thorin::compile Namespace Reference
Classes
class DebugPrint
class InternalCleanup
Enumerations
mem_plugin
enum mem_plugin : flags_t
plugin_select
enum plugin_select : flags_t
lam_spec_pass
enum lam_spec_pass : flags_t
debug_phase
enum debug_phase : flags_t
core_plugin
enum core_plugin : flags_t
tail_rec_elim_pass
enum tail_rec_elim_pass : flags_t
affine_plugin
enum affine_plugin : flags_t
scalerize_pass
enum scalerize_pass : flags_t
pass_list
enum pass_list : flags_t
eta_red_pass
enum eta_red_pass : flags_t
internal_cleanup_pass
enum internal_cleanup_pass : flags_t
partial_eval_pass
enum partial_eval_pass : flags_t
phase_list
enum phase_list : flags_t
beta_red_pass
enum beta_red_pass : flags_t
eta_exp_pass
enum eta_exp_pass : flags_t
phases_to_phase
enum phases_to_phase : flags_t
pipe
enum pipe : flags_t
Pass
enum Pass : flags_t
passes_to_phase
enum passes_to_phase : flags_t
direct_plugin
enum direct_plugin : flags_t
Phase
enum Phase : flags_t
clos_plugin
enum clos_plugin : flags_t
matrix_plugin
enum matrix_plugin : flags_t
demo_plugin
enum demo_plugin : flags_t
refly_plugin
enum refly_plugin : flags_t
Plugin
enum Plugin : flags_t
nullptr_pass
enum nullptr_pass : flags_t
ret_wrap_pass
enum ret_wrap_pass : flags_t
autodiff_plugin
enum autodiff_plugin : flags_t
Functions
void handle_optimization_part (const Def *part, World &world, Passes &passes, PipelineBuilder &builder)
void register_normalizers (Normalizers &normalizers)
Variables
static constexpr plugin_t Plugin_Id = 0x11039128d1800000
combined_phase
enum combined_phase : flags_t
Ref normalize_combined_phase (Ref type, Ref, Ref arg)
combined_phase (phase_list phase1 ... phasen) -> phases_to_phase n (phase1, ..., phasen)
single_pass_phase
enum single_pass_phase : flags_t
Ref normalize_single_pass_phase (Ref type, Ref, Ref arg)
single_pass_phase pass -> passes_to_phase 1 pass
combine_pass_list
enum combine_pass_list : flags_t
Ref normalize_combine_pass_list (Ref type, Ref, Ref arg)
combine_pass_list K (pass_list pass11 ... pass1N) ... (pass_list passK1 ... passKM) = pass_list pass11 ... p1N ... passK1 ... passKM
pass_phase
enum pass_phase : flags_t
Ref normalize_pass_phase (Ref type, Ref, Ref arg)
Enumeration Type Documentation
affine_plugin
enum thorin::compile::affine_plugin : flags_t
Definition at line 98 of file autogen.h.
autodiff_plugin
enum thorin::compile::autodiff_plugin : flags_t
Definition at line 342 of file autogen.h.
beta_red_pass
enum thorin::compile::beta_red_pass : flags_t
Definition at line 168 of file autogen.h.
clos_plugin
enum thorin::compile::clos_plugin : flags_t
Definition at line 272 of file autogen.h.
combine_pass_list
enum thorin::compile::combine_pass_list : flags_t
Definition at line 198 of file autogen.h.
combined_phase
enum thorin::compile::combined_phase : flags_t
Definition at line 14 of file autogen.h.
core_plugin
enum thorin::compile::core_plugin : flags_t
Definition at line 66 of file autogen.h.
debug_phase
enum thorin::compile::debug_phase : flags_t
Definition at line 56 of file autogen.h.
demo_plugin
enum thorin::compile::demo_plugin : flags_t
Definition at line 292 of file autogen.h.
direct_plugin
enum thorin::compile::direct_plugin : flags_t
Definition at line 252 of file autogen.h.
eta_exp_pass
enum thorin::compile::eta_exp_pass : flags_t
Definition at line 178 of file autogen.h.
eta_red_pass
enum thorin::compile::eta_red_pass : flags_t
Definition at line 128 of file autogen.h.
internal_cleanup_pass
enum thorin::compile::internal_cleanup_pass : flags_t
Definition at line 138 of file autogen.h.
lam_spec_pass
enum thorin::compile::lam_spec_pass : flags_t
Definition at line 46 of file autogen.h.
matrix_plugin
enum thorin::compile::matrix_plugin : flags_t
Definition at line 282 of file autogen.h.
mem_plugin
enum thorin::compile::mem_plugin : flags_t
Definition at line 26 of file autogen.h.
nullptr_pass
enum thorin::compile::nullptr_pass : flags_t
Definition at line 322 of file autogen.h.
partial_eval_pass
enum thorin::compile::partial_eval_pass : flags_t
Definition at line 148 of file autogen.h.
Pass
enum thorin::compile::Pass : flags_t
Definition at line 220 of file autogen.h.
pass_list
enum thorin::compile::pass_list : flags_t
Definition at line 118 of file autogen.h.
pass_phase
enum thorin::compile::pass_phase : flags_t
Definition at line 230 of file autogen.h.
passes_to_phase
enum thorin::compile::passes_to_phase : flags_t
Definition at line 242 of file autogen.h.
Phase
enum thorin::compile::Phase : flags_t
Definition at line 262 of file autogen.h.
phase_list
enum thorin::compile::phase_list : flags_t
Definition at line 158 of file autogen.h.
phases_to_phase
enum thorin::compile::phases_to_phase : flags_t
Definition at line 188 of file autogen.h.
pipe
enum thorin::compile::pipe : flags_t
Definition at line 210 of file autogen.h.
Plugin
enum thorin::compile::Plugin : flags_t
Definition at line 312 of file autogen.h.
plugin_select
enum thorin::compile::plugin_select : flags_t
Definition at line 36 of file autogen.h.
refly_plugin
enum thorin::compile::refly_plugin : flags_t
Definition at line 302 of file autogen.h.
ret_wrap_pass
enum thorin::compile::ret_wrap_pass : flags_t
Definition at line 332 of file autogen.h.
scalerize_pass
enum thorin::compile::scalerize_pass : flags_t
Definition at line 108 of file autogen.h.
single_pass_phase
enum thorin::compile::single_pass_phase : flags_t
Definition at line 76 of file autogen.h.
tail_rec_elim_pass
enum thorin::compile::tail_rec_elim_pass : flags_t
Definition at line 88 of file autogen.h.
Function Documentation
handle_optimization_part()
void thorin::compile::handle_optimization_part (const Def * part, World & world, Passes & passes, PipelineBuilder & builder) inline
Definition at line 10 of file compile.h.
References thorin::collect_args(), thorin::World::flags(), thorin::RuntimeCast< B >::isa(), thorin::Def::reduce(), and thorin::Def::type().
Referenced by add_passes(), add_phases(), and thorin_get_plugin().
normalize_combine_pass_list()
Ref thorin::compile::normalize_combine_pass_list (Ref type, Ref , Ref arg)
combine_pass_list K (pass_list pass11 ... pass1N) ... (pass_list passK1 ... passKM) = pass_list pass11 ... p1N ... passK1 ... passKM
Definition at line 48 of file normalizers.cpp.
References thorin::collect_args(), thorin::Def::projs(), and thorin::Def::world().
Referenced by normalize_pass_phase().
normalize_combined_phase()
Ref thorin::compile::normalize_combined_phase (Ref type, Ref , Ref arg)
combined_phase (phase_list phase1 ... phasen) -> phases_to_phase n (phase1, ..., phasen)
Definition at line 30 of file normalizers.cpp.
References thorin::collect_args(), and thorin::Def::world().
normalize_pass_phase()
Ref thorin::compile::normalize_pass_phase (Ref type, Ref , Ref arg)
Definition at line 7 of file normalizers.cpp.
References thorin::RuntimeCast< B >::as(), thorin::collect_args(), normalize_combine_pass_list(), and thorin::Def::world().
normalize_single_pass_phase()
Ref thorin::compile::normalize_single_pass_phase (Ref type, Ref , Ref arg)
single_pass_phase pass -> passes_to_phase 1 pass
Definition at line 41 of file normalizers.cpp.
References thorin::World::app(), and thorin::Def::world().
register_normalizers()
void thorin::compile::register_normalizers (Normalizers & normalizers)
Referenced by thorin_get_plugin().
Variable Documentation
Plugin_Id
constexpr plugin_t thorin::compile::Plugin_Id = 0x11039128d1800000 static constexpr
Definition at line 9 of file autogen.h.