Thorin: thorin::mem Namespace Reference
thorin::mem Namespace Reference
Namespaces
namespace AddrSpace
Classes
class Alloc2Malloc
class CopyProp
This FPPass is similar to sparse conditional constant propagation (SCCP).
class RememElim
class SSAConstr
SSA construction algorithm that promotes slots, loads, and stores to SSA values.
Enumerations
enum class free : flags_t
enum class mslot : flags_t
enum class lea : flags_t
enum class load : flags_t
enum class M : flags_t
enum class slot : flags_t
enum class remem : flags_t
enum class malloc : flags_t
enum class alloc : flags_t
enum class store : flags_t
enum class Ptr : flags_t
Functions
const Axiom * type_mem (World &w)
const Axiom * type_ptr (World &w)
const App * type_ptr (const Def *pointee, const Def *addr_space, const Def *dbg={})
const App * type_ptr (const Def *pointee, nat_t addr_space=AddrSpace::Generic, const Def *dbg={})
const Pi * cn_mem (const Def *dom, const Def *dbg={})
Same as World::cn / World::pi but adds a World::type_mem-typed Var to each Pi.
const Pi * cn_mem_ret (const Def *dom, const Def *ret_dom, const Def *dbg={})
const Pi * pi_mem (const Def *domain, const Def *codomain, const Def *dbg={})
const Pi * fn_mem (const Def *domain, const Def *codomain, const Def *dbg={})
static const Def * tuple_of_types (const Def *t)
const Def * op_lea (const Def *ptr, const Def *index, const Def *dbg={})
const Def * op_lea_unsafe (const Def *ptr, const Def *i, const Def *dbg={})
const Def * op_lea_unsafe (const Def *ptr, u64 i, const Def *dbg={})
const Def * op_load (const Def *mem, const Def *ptr, const Def *dbg={})
const Def * op_store (const Def *mem, const Def *ptr, const Def *val, const Def *dbg={})
const Def * op_remem (const Def *mem, const Def *dbg={})
const Def * op_alloc (const Def *type, const Def *mem, const Def *dbg={})
const Def * op_slot (const Def *type, const Def *mem, const Def *dbg={})
const Def * op_malloc (const Def *type, const Def *mem, const Def *dbg)
const Def * op_mslot (const Def *type, const Def *mem, const Def *id, const Def *dbg)
const Def * op_free (const Def *mem, const Def *ptr, const Def *dbg={})
const Def * mem_var (Lam *lam, const Def *dbg=nullptr)
const Def * normalize_lea (const Def *type, const Def *callee, const Def *arg, const Def *dbg)
const Def * normalize_load (const Def *type, const Def *callee, const Def *arg, const Def *dbg)
const Def * normalize_remem (const Def *type, const Def *callee, const Def *mem, const Def *dbg)
const Def * normalize_store (const Def *type, const Def *callee, const Def *arg, const Def *dbg)
static const Def * get_sloxy_type (const Proxy *sloxy)
static std::tuple< const Proxy *, Lam * > split_phixy (const Proxy *phixy)
bool operator== (free lhs, flags_t rhs)
flags_t operator& (free lhs, flags_t rhs)
flags_t operator& (free lhs, free rhs)
flags_t operator| (free lhs, flags_t rhs)
flags_t operator| (free lhs, free rhs)
bool operator== (mslot lhs, flags_t rhs)
flags_t operator& (mslot lhs, flags_t rhs)
flags_t operator& (mslot lhs, mslot rhs)
flags_t operator| (mslot lhs, flags_t rhs)
flags_t operator| (mslot lhs, mslot rhs)
bool operator== (lea lhs, flags_t rhs)
flags_t operator& (lea lhs, flags_t rhs)
flags_t operator& (lea lhs, lea rhs)
flags_t operator| (lea lhs, flags_t rhs)
flags_t operator| (lea lhs, lea rhs)
bool operator== (load lhs, flags_t rhs)
flags_t operator& (load lhs, flags_t rhs)
flags_t operator& (load lhs, load rhs)
flags_t operator| (load lhs, flags_t rhs)
flags_t operator| (load lhs, load rhs)
bool operator== (M lhs, flags_t rhs)
flags_t operator& (M lhs, flags_t rhs)
flags_t operator& (M lhs, M rhs)
flags_t operator| (M lhs, flags_t rhs)
flags_t operator| (M lhs, M rhs)
bool operator== (slot lhs, flags_t rhs)
flags_t operator& (slot lhs, flags_t rhs)
flags_t operator& (slot lhs, slot rhs)
flags_t operator| (slot lhs, flags_t rhs)
flags_t operator| (slot lhs, slot rhs)
bool operator== (remem lhs, flags_t rhs)
flags_t operator& (remem lhs, flags_t rhs)
flags_t operator& (remem lhs, remem rhs)
flags_t operator| (remem lhs, flags_t rhs)
flags_t operator| (remem lhs, remem rhs)
bool operator== (malloc lhs, flags_t rhs)
flags_t operator& (malloc lhs, flags_t rhs)
flags_t operator& (malloc lhs, malloc rhs)
flags_t operator| (malloc lhs, flags_t rhs)
flags_t operator| (malloc lhs, malloc rhs)
bool operator== (alloc lhs, flags_t rhs)
flags_t operator& (alloc lhs, flags_t rhs)
flags_t operator& (alloc lhs, alloc rhs)
flags_t operator| (alloc lhs, flags_t rhs)
flags_t operator| (alloc lhs, alloc rhs)
bool operator== (store lhs, flags_t rhs)
flags_t operator& (store lhs, flags_t rhs)
flags_t operator& (store lhs, store rhs)
flags_t operator| (store lhs, flags_t rhs)
flags_t operator| (store lhs, store rhs)
bool operator== (Ptr lhs, flags_t rhs)
flags_t operator& (Ptr lhs, flags_t rhs)
flags_t operator& (Ptr lhs, Ptr rhs)
flags_t operator| (Ptr lhs, flags_t rhs)
flags_t operator| (Ptr lhs, Ptr rhs)
void register_normalizers (Normalizers &normalizers)
Variables
static constexpr dialect_t Dialect_Id = 0x3863800000000000
Enumeration Type Documentation
alloc
enum class thorin::mem::alloc : flags_t strong
Definition at line 89 of file autogen.h.
free
enum class thorin::mem::free : flags_t strong
Definition at line 11 of file autogen.h.
lea
enum class thorin::mem::lea : flags_t strong
Definition at line 29 of file autogen.h.
load
enum class thorin::mem::load : flags_t strong
Definition at line 40 of file autogen.h.
M
enum class thorin::mem::M : flags_t strong
Definition at line 51 of file autogen.h.
malloc
enum class thorin::mem::malloc : flags_t strong
Definition at line 80 of file autogen.h.
mslot
enum class thorin::mem::mslot : flags_t strong
Definition at line 20 of file autogen.h.
Ptr
enum class thorin::mem::Ptr : flags_t strong
Definition at line 109 of file autogen.h.
remem
enum class thorin::mem::remem : flags_t strong
Definition at line 69 of file autogen.h.
slot
enum class thorin::mem::slot : flags_t strong
Definition at line 60 of file autogen.h.
store
enum class thorin::mem::store : flags_t strong
Definition at line 98 of file autogen.h.
Function Documentation
cn_mem()
const Pi * thorin::mem::cn_mem (const Def * dom, const Def * dbg = {}) inline
Same as World::cn / World::pi but adds a World::type_mem-typed Var to each Pi.
Definition at line 36 of file mem.h.
cn_mem_ret()
const Pi * thorin::mem::cn_mem_ret (const Def * dom, const Def * ret_dom, const Def * dbg = {}) inline
Definition at line 40 of file mem.h.
fn_mem()
const Pi * thorin::mem::fn_mem (const Def * domain, const Def * codomain, const Def * dbg = {}) inline
Definition at line 49 of file mem.h.
get_sloxy_type()
static const Def * thorin::mem::get_sloxy_type (const Proxy * sloxy) static
Definition at line 9 of file ssa_constr.cpp.
References thorin::Def::type().
mem_var()
const Def * thorin::mem::mem_var (Lam * lam, const Def * dbg = nullptr) inline
Definition at line 128 of file mem.h.
References thorin::Def::type(), and thorin::Def::var().
Referenced by thorin::clos::Clos2SJLJ::enter().
normalize_lea()
const Def * thorin::mem::normalize_lea (const Def * type, const Def * callee, const Def * arg, const Def * dbg)
Definition at line 7 of file normalizers.cpp.
References thorin::isa_lit(), thorin::Def::projs(), and thorin::Def::world().
normalize_load()
const Def * thorin::mem::normalize_load (const Def * type, const Def * callee, const Def * arg, const Def * dbg)
Definition at line 18 of file normalizers.cpp.
References thorin::RuntimeCast< Base >::as(), thorin::Def::op(), thorin::Def::projs(), and thorin::Def::world().
normalize_remem()
const Def * thorin::mem::normalize_remem (const Def * type, const Def * callee, const Def * mem, const Def * dbg)
Definition at line 32 of file normalizers.cpp.
References thorin::World::raw_app(), and thorin::Def::world().
normalize_store()
const Def * thorin::mem::normalize_store (const Def * type, const Def * callee, const Def * arg, const Def * dbg)
Definition at line 39 of file normalizers.cpp.
References thorin::Pack::body(), thorin::RuntimeCast< Base >::isa(), thorin::clos::op(), thorin::Def::projs(), and thorin::Def::world().
op_alloc()
const Def * thorin::mem::op_alloc (const Def * type, const Def * mem, const Def * dbg = {}) inline
Definition at line 96 of file mem.h.
op_free()
const Def * thorin::mem::op_free (const Def * mem, const Def * ptr, const Def * dbg = {}) inline
Definition at line 121 of file mem.h.
op_lea()
const Def * thorin::mem::op_lea (const Def * ptr, const Def * index, const Def * dbg = {}) inline
Definition at line 61 of file mem.h.
op_lea_unsafe() [1/2]
const Def * thorin::mem::op_lea_unsafe (const Def * ptr, const Def * i, const Def * dbg = {}) inline
Definition at line 68 of file mem.h.
op_lea_unsafe() [2/2]
const Def * thorin::mem::op_lea_unsafe (const Def * ptr, u64 i, const Def * dbg = {}) inline
Definition at line 74 of file mem.h.
op_load()
const Def * thorin::mem::op_load (const Def * mem, const Def * ptr, const Def * dbg = {}) inline
Definition at line 79 of file mem.h.
op_malloc()
const Def * thorin::mem::op_malloc (const Def * type, const Def * mem, const Def * dbg) inline
Definition at line 106 of file mem.h.
References thorin::World::app(), thorin::World::ax(), thorin::core::op(), thorin::core::size, and thorin::Def::world().
Referenced by thorin::mem::Alloc2Malloc::rewrite().
op_mslot()
const Def * thorin::mem::op_mslot (const Def * type, const Def * mem, const Def * id, const Def * dbg) inline
Definition at line 112 of file mem.h.
References thorin::World::app(), thorin::World::ax(), thorin::core::op(), thorin::core::size, and thorin::Def::world().
Referenced by thorin::mem::Alloc2Malloc::rewrite().
op_remem()
const Def * thorin::mem::op_remem (const Def * mem, const Def * dbg = {}) inline
Definition at line 91 of file mem.h.
op_slot()
const Def * thorin::mem::op_slot (const Def * type, const Def * mem, const Def * dbg = {}) inline
Definition at line 101 of file mem.h.
Referenced by thorin::clos::Clos2SJLJ::enter().
op_store()
const Def * thorin::mem::op_store (const Def * mem, const Def * ptr, const Def * val, const Def * dbg = {}) inline
Definition at line 85 of file mem.h.
operator&() [1/22]
flags_t thorin::mem::operator& (alloc lhs, alloc rhs) inline
Definition at line 94 of file autogen.h.
operator&() [2/22]
flags_t thorin::mem::operator& (alloc lhs, flags_t rhs) inline
Definition at line 93 of file autogen.h.
operator&() [3/22]
flags_t thorin::mem::operator& (free lhs, flags_t rhs) inline
Definition at line 15 of file autogen.h.
operator&() [4/22]
flags_t thorin::mem::operator& (free lhs, free rhs) inline
Definition at line 16 of file autogen.h.
operator&() [5/22]
flags_t thorin::mem::operator& (lea lhs, flags_t rhs) inline
Definition at line 33 of file autogen.h.
operator&() [6/22]
flags_t thorin::mem::operator& (lea lhs, lea rhs) inline
Definition at line 34 of file autogen.h.
operator&() [7/22]
flags_t thorin::mem::operator& (load lhs, flags_t rhs) inline
Definition at line 44 of file autogen.h.
operator&() [8/22]
flags_t thorin::mem::operator& (load lhs, load rhs) inline
Definition at line 45 of file autogen.h.
operator&() [9/22]
flags_t thorin::mem::operator& (M lhs, flags_t rhs) inline
Definition at line 55 of file autogen.h.
operator&() [10/22]
flags_t thorin::mem::operator& (M lhs, M rhs) inline
Definition at line 56 of file autogen.h.
operator&() [11/22]
flags_t thorin::mem::operator& (malloc lhs, flags_t rhs) inline
Definition at line 84 of file autogen.h.
operator&() [12/22]
flags_t thorin::mem::operator& (malloc lhs, malloc rhs) inline
Definition at line 85 of file autogen.h.
operator&() [13/22]
flags_t thorin::mem::operator& (mslot lhs, flags_t rhs) inline
Definition at line 24 of file autogen.h.
operator&() [14/22]
flags_t thorin::mem::operator& (mslot lhs, mslot rhs) inline
Definition at line 25 of file autogen.h.
operator&() [15/22]
flags_t thorin::mem::operator& (Ptr lhs, flags_t rhs) inline
Definition at line 113 of file autogen.h.
operator&() [16/22]
flags_t thorin::mem::operator& (Ptr lhs, Ptr rhs) inline
Definition at line 114 of file autogen.h.
operator&() [17/22]
flags_t thorin::mem::operator& (remem lhs, flags_t rhs) inline
Definition at line 73 of file autogen.h.
operator&() [18/22]
flags_t thorin::mem::operator& (remem lhs, remem rhs) inline
Definition at line 74 of file autogen.h.
operator&() [19/22]
flags_t thorin::mem::operator& (slot lhs, flags_t rhs) inline
Definition at line 64 of file autogen.h.
operator&() [20/22]
flags_t thorin::mem::operator& (slot lhs, slot rhs) inline
Definition at line 65 of file autogen.h.
operator&() [21/22]
flags_t thorin::mem::operator& (store lhs, flags_t rhs) inline
Definition at line 102 of file autogen.h.
operator&() [22/22]
flags_t thorin::mem::operator& (store lhs, store rhs) inline
Definition at line 103 of file autogen.h.
operator==() [1/11]
bool thorin::mem::operator== (alloc lhs, flags_t rhs) inline
Definition at line 92 of file autogen.h.
operator==() [2/11]
bool thorin::mem::operator== (free lhs, flags_t rhs) inline
Definition at line 14 of file autogen.h.
operator==() [3/11]
bool thorin::mem::operator== (lea lhs, flags_t rhs) inline
Definition at line 32 of file autogen.h.
operator==() [4/11]
bool thorin::mem::operator== (load lhs, flags_t rhs) inline
Definition at line 43 of file autogen.h.
operator==() [5/11]
bool thorin::mem::operator== (M lhs, flags_t rhs) inline
Definition at line 54 of file autogen.h.
operator==() [6/11]
bool thorin::mem::operator== (malloc lhs, flags_t rhs) inline
Definition at line 83 of file autogen.h.
operator==() [7/11]
bool thorin::mem::operator== (mslot lhs, flags_t rhs) inline
Definition at line 23 of file autogen.h.
operator==() [8/11]
bool thorin::mem::operator== (Ptr lhs, flags_t rhs) inline
Definition at line 112 of file autogen.h.
operator==() [9/11]
bool thorin::mem::operator== (remem lhs, flags_t rhs) inline
Definition at line 72 of file autogen.h.
operator==() [10/11]
bool thorin::mem::operator== (slot lhs, flags_t rhs) inline
Definition at line 63 of file autogen.h.
operator==() [11/11]
bool thorin::mem::operator== (store lhs, flags_t rhs) inline
Definition at line 101 of file autogen.h.
operator|() [1/22]
flags_t thorin::mem::operator| (alloc lhs, alloc rhs) inline
Definition at line 96 of file autogen.h.
operator|() [2/22]
flags_t thorin::mem::operator| (alloc lhs, flags_t rhs) inline
Definition at line 95 of file autogen.h.
operator|() [3/22]
flags_t thorin::mem::operator| (free lhs, flags_t rhs) inline
Definition at line 17 of file autogen.h.
operator|() [4/22]
flags_t thorin::mem::operator| (free lhs, free rhs) inline
Definition at line 18 of file autogen.h.
operator|() [5/22]
flags_t thorin::mem::operator| (lea lhs, flags_t rhs) inline
Definition at line 35 of file autogen.h.
operator|() [6/22]
flags_t thorin::mem::operator| (lea lhs, lea rhs) inline
Definition at line 36 of file autogen.h.
operator|() [7/22]
flags_t thorin::mem::operator| (load lhs, flags_t rhs) inline
Definition at line 46 of file autogen.h.
operator|() [8/22]
flags_t thorin::mem::operator| (load lhs, load rhs) inline
Definition at line 47 of file autogen.h.
operator|() [9/22]
flags_t thorin::mem::operator| (M lhs, flags_t rhs) inline
Definition at line 57 of file autogen.h.
operator|() [10/22]
flags_t thorin::mem::operator| (M lhs, M rhs) inline
Definition at line 58 of file autogen.h.
operator|() [11/22]
flags_t thorin::mem::operator| (malloc lhs, flags_t rhs) inline
Definition at line 86 of file autogen.h.
operator|() [12/22]
flags_t thorin::mem::operator| (malloc lhs, malloc rhs) inline
Definition at line 87 of file autogen.h.
operator|() [13/22]
flags_t thorin::mem::operator| (mslot lhs, flags_t rhs) inline
Definition at line 26 of file autogen.h.
operator|() [14/22]
flags_t thorin::mem::operator| (mslot lhs, mslot rhs) inline
Definition at line 27 of file autogen.h.
operator|() [15/22]
flags_t thorin::mem::operator| (Ptr lhs, flags_t rhs) inline
Definition at line 115 of file autogen.h.
operator|() [16/22]
flags_t thorin::mem::operator| (Ptr lhs, Ptr rhs) inline
Definition at line 116 of file autogen.h.
operator|() [17/22]
flags_t thorin::mem::operator| (remem lhs, flags_t rhs) inline
Definition at line 75 of file autogen.h.
operator|() [18/22]
flags_t thorin::mem::operator| (remem lhs, remem rhs) inline
Definition at line 76 of file autogen.h.
operator|() [19/22]
flags_t thorin::mem::operator| (slot lhs, flags_t rhs) inline
Definition at line 66 of file autogen.h.
operator|() [20/22]
flags_t thorin::mem::operator| (slot lhs, slot rhs) inline
Definition at line 67 of file autogen.h.
operator|() [21/22]
flags_t thorin::mem::operator| (store lhs, flags_t rhs) inline
Definition at line 104 of file autogen.h.
operator|() [22/22]
flags_t thorin::mem::operator| (store lhs, store rhs) inline
Definition at line 105 of file autogen.h.
pi_mem()
const Pi * thorin::mem::pi_mem (const Def * domain, const Def * codomain, const Def * dbg = {}) inline
Definition at line 44 of file mem.h.
register_normalizers()
void thorin::mem::register_normalizers (Normalizers & normalizers)
split_phixy()
static std::tuple< const Proxy *, Lam * > thorin::mem::split_phixy (const Proxy * phixy) static
Definition at line 11 of file ssa_constr.cpp.
References thorin::RuntimeCast< Base >::as(), thorin::Def::as_nom(), and thorin::Def::op().
tuple_of_types()
static const Def * thorin::mem::tuple_of_types (const Def * t) inline static
Definition at line 54 of file mem.h.
type_mem()
const Axiom * thorin::mem::type_mem (World & w) inline
Definition at line 23 of file mem.h.
References thorin::World::ax().
Referenced by thorin::clos::Clos2SJLJ::enter(), and thorin::clos::split().
type_ptr() [1/3]
const App * thorin::mem::type_ptr (const Def * pointee, const Def * addr_space, const Def * dbg = {}) inline
Definition at line 26 of file mem.h.
type_ptr() [2/3]
const App * thorin::mem::type_ptr (const Def * pointee, nat_t addr_space = AddrSpace::Generic, const Def * dbg = {}) inline
Definition at line 30 of file mem.h.
type_ptr() [3/3]
const Axiom * thorin::mem::type_ptr (World & w) inline
Definition at line 25 of file mem.h.
References thorin::World::ax().
Variable Documentation
Dialect_Id
constexpr dialect_t thorin::mem::Dialect_Id = 0x3863800000000000 static constexpr
Definition at line 9 of file autogen.h.