Thorin: thorin::autodiff Namespace Reference
thorin::autodiff Namespace Reference
Helper function related to automatic differentiation.
Classes
class AutoDiffEval
This pass is the heart of AD.
class AutoDiffExternalCleanup
Removes all external autodiff axioms extensions from the program.
class AutoDiffZero
Replaces calls to the zero axioms with actual zeros.
class AutoDiffZeroCleanup
Replaces remaining zeros (not resolvable) with ⊥.
Enumerations
enum class add : flags_t
enum class Tangent : flags_t
enum class AD : flags_t
enum class ad : flags_t
enum class zero : flags_t
enum class sum : flags_t
Functions
const Def * op_autodiff (const Def *fun)
const Def * op_zero (const Def *A)
const Def * id_pullback (const Def *A)
const Def * zero_pullback (const Def *E, const Def *A)
const Def * tangent_type_fun (const Def *ty)
const Pi * pullback_type (const Def *E, const Def *A)
computes pb type E* -> A* E - type of the expression (return type for a function) A - type of the argument (point of orientation resp.
const Pi * autodiff_type_fun (const Def *arg, const Def *ret)
const Pi * autodiff_type_fun_pi (const Pi *pi)
const Def * autodiff_type_fun (const Def *ty)
const Def * zero_def (const Def *T)
const Def * op_sum (const Def *T, DefArray defs)
const Def * normalize_ad (const Def *type, const Def *callee, const Def *arg, const Def *dbg)
Currently this normalizer does nothin.
const Def * normalize_AD (const Def *type, const Def *callee, const Def *arg, const Def *dbg)
const Def * normalize_Tangent (const Def *, const Def *, const Def *arg, const Def *)
const Def * normalize_zero (const Def *type, const Def *callee, const Def *arg, const Def *dbg)
Currently this normalizer does nothing.
const Def * normalize_add (const Def *type, const Def *callee, const Def *arg, const Def *dbg)
Currently resolved the full addition.
const Def * normalize_sum (const Def *type, const Def *callee, const Def *arg, const Def *dbg)
bool operator== (add lhs, flags_t rhs)
flags_t operator& (add lhs, flags_t rhs)
flags_t operator& (add lhs, add rhs)
flags_t operator| (add lhs, flags_t rhs)
flags_t operator| (add lhs, add rhs)
bool operator== (Tangent lhs, flags_t rhs)
flags_t operator& (Tangent lhs, flags_t rhs)
flags_t operator& (Tangent lhs, Tangent rhs)
flags_t operator| (Tangent lhs, flags_t rhs)
flags_t operator| (Tangent lhs, Tangent rhs)
bool operator== (AD lhs, flags_t rhs)
flags_t operator& (AD lhs, flags_t rhs)
flags_t operator& (AD lhs, AD rhs)
flags_t operator| (AD lhs, flags_t rhs)
flags_t operator| (AD lhs, AD rhs)
bool operator== (ad lhs, flags_t rhs)
flags_t operator& (ad lhs, flags_t rhs)
flags_t operator& (ad lhs, ad rhs)
flags_t operator| (ad lhs, flags_t rhs)
flags_t operator| (ad lhs, ad rhs)
bool operator== (zero lhs, flags_t rhs)
flags_t operator& (zero lhs, flags_t rhs)
flags_t operator& (zero lhs, zero rhs)
flags_t operator| (zero lhs, flags_t rhs)
flags_t operator| (zero lhs, zero rhs)
bool operator== (sum lhs, flags_t rhs)
flags_t operator& (sum lhs, flags_t rhs)
flags_t operator& (sum lhs, sum rhs)
flags_t operator| (sum lhs, flags_t rhs)
flags_t operator| (sum lhs, sum rhs)
void register_normalizers (Normalizers &normalizers)
Variables
static constexpr dialect_t Dialect_Id = 0x9655014a1c70000
Detailed Description
Helper function related to automatic differentiation.
Enumeration Type Documentation
AD
enum class thorin::autodiff::AD : flags_t strong
Definition at line 33 of file autogen.h.
ad
enum class thorin::autodiff::ad : flags_t strong
Definition at line 44 of file autogen.h.
add
enum class thorin::autodiff::add : flags_t strong
Definition at line 11 of file autogen.h.
sum
enum class thorin::autodiff::sum : flags_t strong
Definition at line 66 of file autogen.h.
Tangent
enum class thorin::autodiff::Tangent : flags_t strong
Definition at line 22 of file autogen.h.
zero
enum class thorin::autodiff::zero : flags_t strong
Definition at line 55 of file autogen.h.
Function Documentation
autodiff_type_fun() [1/2]
const Pi * thorin::autodiff::autodiff_type_fun (const Def * arg, const Def * ret)
Definition at line 50 of file autodiff_aux.cpp.
References autodiff_type_fun(), pullback_type(), and thorin::Def::world().
Referenced by thorin::autodiff::AutoDiffEval::augment_(), thorin::autodiff::AutoDiffEval::augment_lam(), autodiff_type_fun(), autodiff_type_fun_pi(), and normalize_AD().
autodiff_type_fun() [2/2]
const Def * thorin::autodiff::autodiff_type_fun (const Def * ty)
Definition at line 90 of file autodiff_aux.cpp.
References autodiff_type_fun(), autodiff_type_fun_pi(), thorin::RuntimeCast< Base >::isa(), thorin::Def::node_name(), thorin::clos::op(), thorin::Idx::size(), and thorin::Def::world().
autodiff_type_fun_pi()
const Pi * thorin::autodiff::autodiff_type_fun_pi (const Pi * pi)
Definition at line 67 of file autodiff_aux.cpp.
References autodiff_type_fun(), thorin::Pi::codom(), thorin::Pi::dom(), thorin::is_continuation_type(), and thorin::Def::world().
Referenced by autodiff_type_fun(), and thorin::autodiff::AutoDiffEval::derive_().
id_pullback()
const Def * thorin::autodiff::id_pullback (const Def * A)
Definition at line 11 of file autodiff_aux.cpp.
References pullback_type(), and thorin::Def::world().
Referenced by thorin::autodiff::AutoDiffEval::derive_().
normalize_ad()
const Def * thorin::autodiff::normalize_ad (const Def * type, const Def * callee, const Def * arg, const Def * dbg)
Currently this normalizer does nothin.
TODO: Maybe we want to handle trivial lookup replacements here.
Definition at line 14 of file normalizers.cpp.
References thorin::World::raw_app(), and thorin::Def::world().
normalize_AD()
const Def * thorin::autodiff::normalize_AD (const Def * type, const Def * callee, const Def * arg, const Def * dbg)
Definition at line 19 of file normalizers.cpp.
References autodiff_type_fun(), and thorin::Def::world().
normalize_add()
const Def * thorin::autodiff::normalize_add (const Def * type, const Def * callee, const Def * arg, const Def * dbg)
Currently resolved the full addition.
There is no benefit in keeping additions around longer than necessary.
Definition at line 38 of file normalizers.cpp.
References thorin::core::add, thorin::RuntimeCast< Base >::as(), thorin::as_lit(), thorin::Def::projs(), thorin::Idx::size(), and thorin::Def::world().
normalize_sum()
const Def * thorin::autodiff::normalize_sum (const Def * type, const Def * callee, const Def * arg, const Def * dbg)
Definition at line 92 of file normalizers.cpp.
References thorin::RuntimeCast< Base >::as(), thorin::Def::projs(), and thorin::Def::world().
normalize_Tangent()
const Def * thorin::autodiff::normalize_Tangent (const Def * , const Def * , const Def * arg, const Def *)
Definition at line 26 of file normalizers.cpp.
References tangent_type_fun().
normalize_zero()
const Def * thorin::autodiff::normalize_zero (const Def * type, const Def * callee, const Def * arg, const Def * dbg)
Currently this normalizer does nothing.
We usually want to keep zeros as long as possible to avoid unnecessary allocations. A high-level addition with zero can be shortened directly.
Definition at line 31 of file normalizers.cpp.
References thorin::World::raw_app(), and thorin::Def::world().
op_autodiff()
const Def * thorin::autodiff::op_autodiff (const Def * fun) inline
Definition at line 9 of file autodiff.h.
References thorin::World::app(), thorin::World::ax(), thorin::Def::type(), and thorin::Def::world().
Referenced by thorin::autodiff::AutoDiffEval::augment_lam().
op_sum()
const Def * thorin::autodiff::op_sum (const Def * T, DefArray defs)
Definition at line 146 of file autodiff_aux.cpp.
References thorin::World::raw_app(), and thorin::Def::world().
Referenced by thorin::autodiff::AutoDiffEval::augment_tuple().
op_zero()
const Def * thorin::autodiff::op_zero (const Def * A) inline
Definition at line 16 of file autodiff.h.
References thorin::World::app(), thorin::World::ax(), and thorin::Def::world().
Referenced by thorin::autodiff::AutoDiffEval::augment_extract(), and zero_pullback().
operator&() [1/12]
flags_t thorin::autodiff::operator& (AD lhs, AD rhs) inline
Definition at line 38 of file autogen.h.
operator&() [2/12]
flags_t thorin::autodiff::operator& (ad lhs, ad rhs) inline
Definition at line 49 of file autogen.h.
operator&() [3/12]
flags_t thorin::autodiff::operator& (AD lhs, flags_t rhs) inline
Definition at line 37 of file autogen.h.
operator&() [4/12]
flags_t thorin::autodiff::operator& (ad lhs, flags_t rhs) inline
Definition at line 48 of file autogen.h.
operator&() [5/12]
flags_t thorin::autodiff::operator& (add lhs, add rhs) inline
Definition at line 16 of file autogen.h.
operator&() [6/12]
flags_t thorin::autodiff::operator& (add lhs, flags_t rhs) inline
Definition at line 15 of file autogen.h.
operator&() [7/12]
flags_t thorin::autodiff::operator& (sum lhs, flags_t rhs) inline
Definition at line 70 of file autogen.h.
operator&() [8/12]
flags_t thorin::autodiff::operator& (sum lhs, sum rhs) inline
Definition at line 71 of file autogen.h.
operator&() [9/12]
flags_t thorin::autodiff::operator& (Tangent lhs, flags_t rhs) inline
Definition at line 26 of file autogen.h.
operator&() [10/12]
flags_t thorin::autodiff::operator& (Tangent lhs, Tangent rhs) inline
Definition at line 27 of file autogen.h.
operator&() [11/12]
flags_t thorin::autodiff::operator& (zero lhs, flags_t rhs) inline
Definition at line 59 of file autogen.h.
operator&() [12/12]
flags_t thorin::autodiff::operator& (zero lhs, zero rhs) inline
Definition at line 60 of file autogen.h.
operator==() [1/6]
bool thorin::autodiff::operator== (AD lhs, flags_t rhs) inline
Definition at line 36 of file autogen.h.
operator==() [2/6]
bool thorin::autodiff::operator== (ad lhs, flags_t rhs) inline
Definition at line 47 of file autogen.h.
operator==() [3/6]
bool thorin::autodiff::operator== (add lhs, flags_t rhs) inline
Definition at line 14 of file autogen.h.
operator==() [4/6]
bool thorin::autodiff::operator== (sum lhs, flags_t rhs) inline
Definition at line 69 of file autogen.h.
operator==() [5/6]
bool thorin::autodiff::operator== (Tangent lhs, flags_t rhs) inline
Definition at line 25 of file autogen.h.
operator==() [6/6]
bool thorin::autodiff::operator== (zero lhs, flags_t rhs) inline
Definition at line 58 of file autogen.h.
operator|() [1/12]
flags_t thorin::autodiff::operator| (AD lhs, AD rhs) inline
Definition at line 40 of file autogen.h.
operator|() [2/12]
flags_t thorin::autodiff::operator| (ad lhs, ad rhs) inline
Definition at line 51 of file autogen.h.
operator|() [3/12]
flags_t thorin::autodiff::operator| (AD lhs, flags_t rhs) inline
Definition at line 39 of file autogen.h.
operator|() [4/12]
flags_t thorin::autodiff::operator| (ad lhs, flags_t rhs) inline
Definition at line 50 of file autogen.h.
operator|() [5/12]
flags_t thorin::autodiff::operator| (add lhs, add rhs) inline
Definition at line 18 of file autogen.h.
operator|() [6/12]
flags_t thorin::autodiff::operator| (add lhs, flags_t rhs) inline
Definition at line 17 of file autogen.h.
operator|() [7/12]
flags_t thorin::autodiff::operator| (sum lhs, flags_t rhs) inline
Definition at line 72 of file autogen.h.
operator|() [8/12]
flags_t thorin::autodiff::operator| (sum lhs, sum rhs) inline
Definition at line 73 of file autogen.h.
operator|() [9/12]
flags_t thorin::autodiff::operator| (Tangent lhs, flags_t rhs) inline
Definition at line 28 of file autogen.h.
operator|() [10/12]
flags_t thorin::autodiff::operator| (Tangent lhs, Tangent rhs) inline
Definition at line 29 of file autogen.h.
operator|() [11/12]
flags_t thorin::autodiff::operator| (zero lhs, flags_t rhs) inline
Definition at line 61 of file autogen.h.
operator|() [12/12]
flags_t thorin::autodiff::operator| (zero lhs, zero rhs) inline
Definition at line 62 of file autogen.h.
pullback_type()
const Pi * thorin::autodiff::pullback_type (const Def * E, const Def * A)
computes pb type E* -> A* E - type of the expression (return type for a function) A - type of the argument (point of orientation resp.
derivative - argument type for partial pullbacks)
Definition at line 41 of file autodiff_aux.cpp.
References tangent_type_fun(), and thorin::Def::world().
Referenced by thorin::autodiff::AutoDiffEval::augment_extract(), thorin::autodiff::AutoDiffEval::augment_lam(), thorin::autodiff::AutoDiffEval::augment_pack(), thorin::autodiff::AutoDiffEval::augment_tuple(), autodiff_type_fun(), id_pullback(), and zero_pullback().
register_normalizers()
void thorin::autodiff::register_normalizers (Normalizers & normalizers)
Referenced by thorin_get_dialect_info().
tangent_type_fun()
const Def * thorin::autodiff::tangent_type_fun (const Def * ty)
Definition at line 36 of file autodiff_aux.cpp.
Referenced by thorin::autodiff::AutoDiffEval::augment_pack(), thorin::autodiff::AutoDiffEval::augment_tuple(), normalize_Tangent(), pullback_type(), and zero_pullback().
zero_def()
const Def * thorin::autodiff::zero_def (const Def * T)
Definition at line 117 of file autodiff_aux.cpp.
References thorin::World::app(), thorin::Def::dbg(), thorin::RuntimeCast< Base >::isa(), thorin::Def::node_name(), thorin::clos::op(), thorin::Idx::size(), and thorin::Def::world().
Referenced by thorin::autodiff::AutoDiffZero::rewrite().
zero_pullback()
const Def * thorin::autodiff::zero_pullback (const Def * E, const Def * A)
Definition at line 23 of file autodiff_aux.cpp.
References op_zero(), pullback_type(), tangent_type_fun(), and thorin::Def::world().
Referenced by thorin::autodiff::AutoDiffEval::augment_lam(), thorin::autodiff::AutoDiffEval::augment_lit(), and thorin::autodiff::AutoDiffEval::derive_().
Variable Documentation
Dialect_Id
constexpr dialect_t thorin::autodiff::Dialect_Id = 0x9655014a1c70000 static constexpr
Definition at line 9 of file autogen.h.