MimIR: mim::plug::tuple Namespace Reference
mim::plug::tuple Namespace Reference
The tuple Plugin
Enumerations
%tuple.append
enum class append : flags_t
%tuple.prepend
enum class prepend : flags_t
Functions
void register_normalizers (Normalizers &normalizers)
Variables
static constexpr plugin_t Plugin_Id = 0x55644d1800000000
%tuple.cat
enum class cat : flags_t
const Def * normalize_cat (const Def *type, const Def *callee, const Def *arg)
%tuple.contains
enum class contains : flags_t
const Def * normalize_contains (const Def *type, const Def *, const Def *arg)
%tuple.zip
enum class zip : flags_t
const Def * normalize_zip (const Def *type, const Def *c, const Def *arg)
Detailed Description
The tuple Plugin
Enumeration Type Documentation
append
enum class mim::plug::tuple::append : flags_t strong
Definition at line 22 of file autogen.h.
cat
enum class mim::plug::tuple::cat : flags_t strong
Definition at line 14 of file autogen.h.
contains
enum class mim::plug::tuple::contains : flags_t strong
Definition at line 36 of file autogen.h.
prepend
enum class mim::plug::tuple::prepend : flags_t strong
Definition at line 29 of file autogen.h.
zip
enum class mim::plug::tuple::zip : flags_t strong
Definition at line 44 of file autogen.h.
Function Documentation
normalize_cat()
const Def * mim::plug::tuple::normalize_cat (const Def * type, const Def * callee, const Def * arg)
Definition at line 8 of file normalizers.cpp.
References mim::decurry(), mim::Lit::isa(), and mim::Def::projs().
normalize_contains()
const Def * mim::plug::tuple::normalize_contains (const Def * type, const Def * , const Def * arg)
Definition at line 23 of file normalizers.cpp.
References mim::Def::projs().
normalize_zip()
const Def * mim::plug::tuple::normalize_zip (const Def * type, const Def * c, const Def * arg)
Definition at line 49 of file normalizers.cpp.
References mim::App::arg(), mim::Lit::isa(), and mim::Def::projs().
register_normalizers()
void mim::plug::tuple::register_normalizers (Normalizers & normalizers)
Referenced by mim_get_plugin().
Variable Documentation
Plugin_Id
plugin_t mim::plug::tuple::Plugin_Id = 0x55644d1800000000 static constexpr
Definition at line 10 of file autogen.h.