Thorin: thorin::clos Namespace Reference
thorin::clos Namespace Reference
Classes
class BranchClosElim
class Clos2SJLJ
class ClosConv
Performs typed closure conversion.
class ClosConvPrep
class ClosLit
Wrapper around a Def that can be used to match closures (see isa_clos_lit).
class FreeDefAna
Transitively compute free Def's on demand.
class LowerTypedClos
This pass lowers typed closures to untyped closures.
class LowerTypedClosPrep
Enumerations
enum class setjmp : flags_t
enum class clos : flags_t {
ret = 0x10d4140000000300 , freeBB = 0x10d4140000000301 , fstclassBB = 0x10d4140000000302 , esc = 0x10d4140000000303 ,
bot = 0x10d4140000000304
}
enum class longjmp : flags_t
enum class alloc_jmpbuf : flags_t
Functions
const Def * op_alloc_jumpbuf (const Def *mem, const Def *dbg={})
const Def * op_setjmp (const Def *mem, const Def *buf, const Def *dbg={})
const Def * op_longjmp (const Def *mem, const Def *buf, const Def *id, const Def *dbg={})
const Def * op (clos o, const Def *def, const Def *dbg={})
template<class N >
std::tuple< const Extract *, N * > ca_isa_var (const Def *def)
Checks is def is the variable of a nom of type N.
std::tuple< Lam *, const Def *, const Def * > clos_lam_stub (const Def *env_type, const Def *dom, const Def *dbg={})
template<clos o>
const Def * normalize_clos (const Def *type, const Def *callee, const Def *arg, const Def *dbg)
static bool interesting_type (const Def *type, DefSet &visited)
static bool interesting_type (const Def *def)
static void split (DefSet &out, const Def *def, bool as_callee)
static DefSet split (const Def *def, bool keep_others)
static std::tuple< std::vector< ClosLit >, const Def * > isa_branch (const Def *callee)
static std::array< const Def *, 3 > split (const Def *def)
static const Def * rebuild (const Def *mem, const Def *env, Defs remaining)
static bool isa_cont (const App *body, const Def *def, size_t i)
static const Def * isa_br (const App *body, const Def *def)
static bool isa_callee_br (const App *body, const Def *def, size_t i)
static Lam * isa_retvar (const Def *def)
static size_t shift_env (size_t i)
static size_t skip_env (size_t i)
static const Def * ctype (World &w, Defs doms, const Def *env_type=nullptr)
static bool is_toplevel (const Def *fd)
static bool is_memop_res (const Def *fd)
static const Def * insert_ret (const Def *def, const Def *ret)
bool operator== (setjmp lhs, flags_t rhs)
flags_t operator& (setjmp lhs, flags_t rhs)
flags_t operator& (setjmp lhs, setjmp rhs)
flags_t operator| (setjmp lhs, flags_t rhs)
flags_t operator| (setjmp lhs, setjmp rhs)
bool operator== (clos lhs, flags_t rhs)
flags_t operator& (clos lhs, flags_t rhs)
flags_t operator& (clos lhs, clos rhs)
flags_t operator| (clos lhs, flags_t rhs)
flags_t operator| (clos lhs, clos rhs)
bool operator== (longjmp lhs, flags_t rhs)
flags_t operator& (longjmp lhs, flags_t rhs)
flags_t operator& (longjmp lhs, longjmp rhs)
flags_t operator| (longjmp lhs, flags_t rhs)
flags_t operator| (longjmp lhs, longjmp rhs)
bool operator== (alloc_jmpbuf lhs, flags_t rhs)
flags_t operator& (alloc_jmpbuf lhs, flags_t rhs)
flags_t operator& (alloc_jmpbuf lhs, alloc_jmpbuf rhs)
flags_t operator| (alloc_jmpbuf lhs, flags_t rhs)
flags_t operator| (alloc_jmpbuf lhs, alloc_jmpbuf rhs)
void register_normalizers (Normalizers &normalizers)
closures
ClosLit isa_clos_lit (const Def *def, bool fn_isa_lam=true)
Tries to match a closure literal.
const Def * clos_pack_dbg (const Def *env, const Def *fn, const Def *dbg, const Def *ct=nullptr)
Pack a typed closure. This assumes that fn expects the environment as its Clos_Env_Paramth argument.
const Def * clos_pack (const Def *env, const Def *fn, const Def *ct=nullptr)
std::tuple< const Def *, const Def *, const Def * > clos_unpack (const Def *c)
Deconstruct a closure into (env_type, function, env).
const Def * clos_apply (const Def *closure, const Def *args)
Apply a closure to arguments.
const Def * apply_closure (const Def *closure, Defs args)
closure types
const Sigma * isa_clos_type (const Def *def)
Returns def if def is a closure and nullptr otherwise.
Sigma * clos_type (const Pi *pi)
Creates a typed closure type from pi.
const Pi * clos_type_to_pi (const Def *ct, const Def *new_env_type=nullptr)
Convert a closure type to a Pi, where the environment type has been removed or replaced by new_env_type (if new_env_type != nullptr)
Variables
static constexpr dialect_t Dialect_Id = 0x10d4140000000000
closure environments
tup_or_sig should generally be a Tuple, Sigma or Var.
const size_t Clos_Env_Param = 1_u64
Describes where the environment is placed in the argument list.
const Def * clos_insert_env (size_t i, const Def *env, std::function< const Def *(size_t)> f)
const Def * clos_insert_env (size_t i, const Def *env, const Def *a)
const Def * clos_insert_env (const Def *env, const Def *tup_or_sig)
const Def * clos_remove_env (size_t i, std::function< const Def *(size_t)> f)
const Def * clos_remove_env (size_t i, const Def *def)
const Def * clos_remove_env (const Def *tup_or_sig)
const Def * clos_sub_env (const Def *tup_or_sig, const Def *new_env)
Enumeration Type Documentation
alloc_jmpbuf
enum class thorin::clos::alloc_jmpbuf : flags_t strong
Definition at line 46 of file autogen.h.
clos
enum class thorin::clos::clos : flags_t strong
Enumerator
ret
freeBB
fstclassBB
esc
bot
Definition at line 20 of file autogen.h.
longjmp
enum class thorin::clos::longjmp : flags_t strong
Definition at line 37 of file autogen.h.
setjmp
enum class thorin::clos::setjmp : flags_t strong
Definition at line 11 of file autogen.h.
Function Documentation
apply_closure()
const Def * thorin::clos::apply_closure (const Def * closure, Defs args) inline
Definition at line 96 of file clos.h.
References clos_apply(), thorin::World::tuple(), and thorin::Def::world().
ca_isa_var()
template<class N > std::tuple< const Extract *, N * > thorin::clos::ca_isa_var (const Def * def)
Checks is def is the variable of a nom of type N.
Definition at line 106 of file clos.h.
References thorin::RuntimeCast< Base >::isa(), and thorin::Var::nom().
clos_apply()
const Def * thorin::clos::clos_apply (const Def * closure, const Def * args)
Apply a closure to arguments.
Definition at line 80 of file clos_conv.cpp.
References thorin::RuntimeCast< Base >::as(), clos_unpack(), thorin::core::fn(), thorin::Def::type(), and thorin::Def::world().
Referenced by apply_closure(), and thorin::clos::Clos2SJLJ::enter().
clos_insert_env() [1/3]
const Def * thorin::clos::clos_insert_env (const Def * env, const Def * tup_or_sig) inline
Definition at line 143 of file clos.h.
References thorin::RuntimeCast< Base >::isa(), thorin::Def::num_projs(), thorin::World::sigma(), thorin::World::tuple(), and thorin::Def::world().
clos_insert_env() [2/3]
const Def * thorin::clos::clos_insert_env (size_t i, const Def * env, const Def * a) inline
Definition at line 139 of file clos.h.
References clos_insert_env().
clos_insert_env() [3/3]
const Def * thorin::clos::clos_insert_env (size_t i, const Def * env, std::function< const Def *(size_t)> f)
Definition at line 19 of file clos_conv.cpp.
References Clos_Env_Param, and shift_env().
Referenced by clos_insert_env().
clos_lam_stub()
std::tuple< Lam *, const Def *, const Def * > thorin::clos::clos_lam_stub (const Def * env_type, const Def * dom, const Def * dbg = {})
clos_pack()
const Def * thorin::clos::clos_pack (const Def * env, const Def * fn, const Def * ct = nullptr) inline
Definition at line 85 of file clos.h.
References clos_pack_dbg(), and thorin::core::fn().
Referenced by thorin::clos::Clos2SJLJ::enter(), and thorin::clos::Clos2SJLJ::rewrite().
clos_pack_dbg()
const Def * thorin::clos::clos_pack_dbg (const Def * env, const Def * fn, const Def * dbg, const Def * ct = nullptr)
Pack a typed closure. This assumes that fn expects the environment as its Clos_Env_Paramth argument.
Definition at line 58 of file clos_conv.cpp.
References Clos_Env_Param, clos_remove_env(), clos_type(), thorin::RuntimeCast< Base >::isa(), isa_clos_type(), thorin::Def::type(), and thorin::Def::world().
Referenced by clos_pack().
clos_remove_env() [1/3]
const Def * thorin::clos::clos_remove_env (const Def * tup_or_sig) inline
Definition at line 153 of file clos.h.
References thorin::RuntimeCast< Base >::isa(), thorin::Def::num_projs(), thorin::World::sigma(), thorin::World::tuple(), and thorin::Def::world().
clos_remove_env() [2/3]
const Def * thorin::clos::clos_remove_env (size_t i, const Def * def) inline
Definition at line 150 of file clos.h.
References clos_remove_env(), and thorin::Def::proj().
clos_remove_env() [3/3]
const Def * thorin::clos::clos_remove_env (size_t i, std::function< const Def *(size_t)> f)
Definition at line 23 of file clos_conv.cpp.
References skip_env().
Referenced by clos_pack_dbg(), clos_remove_env(), clos_type_to_pi(), and thorin::clos::BranchClosElim::rewrite().
clos_sub_env()
const Def * thorin::clos::clos_sub_env (const Def * tup_or_sig, const Def * new_env) inline
Definition at line 159 of file clos.h.
References Clos_Env_Param, and thorin::Def::refine().
Referenced by clos_type_to_pi().
clos_type()
Sigma * thorin::clos::clos_type (const Pi * pi)
Creates a typed closure type from pi.
Definition at line 37 of file clos_conv.cpp.
References thorin::Def::as_nom(), ctype(), and thorin::Def::world().
Referenced by clos_pack_dbg(), and thorin::clos::Clos2SJLJ::enter().
clos_type_to_pi()
const Pi * thorin::clos::clos_type_to_pi (const Def * ct, const Def * new_env_type = nullptr)
Convert a closure type to a Pi, where the environment type has been removed or replaced by new_env_type (if new_env_type != nullptr)
Definition at line 39 of file clos_conv.cpp.
References clos_remove_env(), clos_sub_env(), thorin::RuntimeCast< Base >::isa(), isa_clos_type(), thorin::Def::op(), and thorin::Def::world().
clos_unpack()
std::tuple< const Def *, const Def *, const Def * > thorin::clos::clos_unpack (const Def * c)
Deconstruct a closure into (env_type, function, env).
Important: use this or ClosLit to destruct closures, since typechecking dependent pairs is currently broken.
Definition at line 68 of file clos_conv.cpp.
References isa_clos_type(), thorin::Def::projs(), and thorin::Def::type().
Referenced by clos_apply(), thorin::clos::ClosLit::env(), and thorin::clos::ClosLit::fnc().
ctype()
static const Def * thorin::clos::ctype (World & w, Defs doms, const Def * env_type = nullptr) static
Definition at line 25 of file clos_conv.cpp.
References thorin::World::cn(), ctype(), thorin::World::dbg(), thorin::World::nom_sigma(), thorin::Sigma::set(), thorin::ArrayRef< T >::size(), and thorin::World::type().
Referenced by clos_type(), and ctype().
insert_ret()
static const Def * thorin::clos::insert_ret (const Def * def, const Def * ret) static
Definition at line 25 of file lower_typed_clos.cpp.
References thorin::Def::num_projs(), thorin::Def::sort(), thorin::Term, thorin::World::tuple(), and thorin::Def::world().
interesting_type() [1/2]
static bool thorin::clos::interesting_type (const Def * def) static
Definition at line 19 of file lower_typed_clos_prep.cpp.
References interesting_type(), and thorin::Def::type().
interesting_type() [2/2]
static bool thorin::clos::interesting_type (const Def * type, DefSet & visited) static
Definition at line 9 of file lower_typed_clos_prep.cpp.
References interesting_type(), thorin::RuntimeCast< Base >::isa(), isa_clos_type(), and thorin::Def::isa_nom().
Referenced by interesting_type(), and split().
is_memop_res()
static bool thorin::clos::is_memop_res (const Def * fd) static
Definition at line 328 of file clos_conv.cpp.
References thorin::RuntimeCast< Base >::isa(), thorin::Def::ops(), thorin::Extract::tuple(), and thorin::Def::type().
is_toplevel()
static bool thorin::clos::is_toplevel (const Def * fd) static
Definition at line 324 of file clos_conv.cpp.
References thorin::Def::dep_const(), thorin::RuntimeCast< Base >::isa(), thorin::Def::isa_nom(), and thorin::Def::sort().
isa_br()
static const Def * thorin::clos::isa_br (const App * body, const Def * def) static
Definition at line 14 of file clos_conv_prep.cpp.
References thorin::App::callee(), thorin::App::callee_type(), thorin::Pi::is_cn(), thorin::RuntimeCast< Base >::isa(), and thorin::Extract::tuple().
Referenced by isa_callee_br(), and thorin::clos::ClosConvPrep::rewrite().
isa_branch()
static std::tuple< std::vector< ClosLit >, const Def * > thorin::clos::isa_branch (const Def * callee) static
Definition at line 7 of file branch_clos_elim.cpp.
References thorin::RuntimeCast< Base >::isa(), isa_clos_lit(), isa_clos_type(), op(), and thorin::Def::ops().
Referenced by thorin::clos::BranchClosElim::rewrite().
isa_callee_br()
static bool thorin::clos::isa_callee_br (const App * body, const Def * def, size_t i) static
Definition at line 20 of file clos_conv_prep.cpp.
References thorin::App::callee_type(), thorin::Pi::is_cn(), isa_br(), and thorin::isa_callee().
Referenced by thorin::clos::ClosConvPrep::rewrite().
isa_clos_lit()
ClosLit thorin::clos::isa_clos_lit (const Def * def, bool fn_isa_lam = true)
Tries to match a closure literal.
Definition at line 87 of file clos_conv.cpp.
Referenced by isa_branch(), thorin::clos::Clos2SJLJ::rewrite(), and split().
isa_clos_type()
const Sigma * thorin::clos::isa_clos_type (const Def * def)
Returns def if def is a closure and nullptr otherwise.
Definition at line 48 of file clos_conv.cpp.
References Clos_Env_Param, thorin::RuntimeCast< Base >::isa(), thorin::Def::isa_nom(), thorin::Def::op(), thorin::Def::var(), and thorin::Def::world().
Referenced by clos_pack_dbg(), clos_type_to_pi(), clos_unpack(), interesting_type(), and isa_branch().
isa_cont()
static bool thorin::clos::isa_cont (const App * body, const Def * def, size_t i) static
Definition at line 10 of file clos_conv_prep.cpp.
References thorin::App::arg(), thorin::App::callee_type(), thorin::Pi::is_returning(), and thorin::Def::num_ops().
Referenced by thorin::clos::ClosConvPrep::rewrite().
isa_retvar()
static Lam * thorin::clos::isa_retvar (const Def * def) static
Definition at line 25 of file clos_conv_prep.cpp.
Referenced by thorin::clos::ClosConvPrep::rewrite().
normalize_clos()
template<clos o> const Def * thorin::clos::normalize_clos (const Def * type, const Def * callee, const Def * arg, const Def * dbg)
Definition at line 6 of file normalizers.cpp.
References bot, and thorin::Def::world().
op()
const Def * thorin::clos::op (clos o, const Def * def, const Def * dbg = {}) inline
Definition at line 21 of file clos.h.
Referenced by thorin::World::bound(), thorin::CFA::CFA(), thorin::Scheduler::early(), thorin::ll::Emitter::emit_bb(), thorin::dot::Emitter::emit_bb(), thorin::clos::Clos2SJLJ::enter(), thorin::clos::ClosConvPrep::eta_wrap(), thorin::is_shape(), thorin::Checker::is_uniform(), isa_branch(), thorin::mem::normalize_store(), thorin::Dumper::recurse(), thorin::clos::ClosConvPrep::rewrite(), thorin::Scalerize::rewrite(), thorin::Rewriter::rewrite(), thorin::PassMan::run(), thorin::Scheduler::Scheduler(), split(), and thorin::IndexSet< Indexer, Key >::transform().
op_alloc_jumpbuf()
const Def * thorin::clos::op_alloc_jumpbuf (const Def * mem, const Def * dbg = {}) inline
Definition at line 9 of file clos.h.
Referenced by thorin::clos::Clos2SJLJ::enter().
op_longjmp()
const Def * thorin::clos::op_longjmp (const Def * mem, const Def * buf, const Def * id, const Def * dbg = {}) inline
Definition at line 17 of file clos.h.
op_setjmp()
const Def * thorin::clos::op_setjmp (const Def * mem, const Def * buf, const Def * dbg = {}) inline
Definition at line 13 of file clos.h.
Referenced by thorin::clos::Clos2SJLJ::enter().
operator&() [1/8]
flags_t thorin::clos::operator& (alloc_jmpbuf lhs, alloc_jmpbuf rhs) inline
Definition at line 51 of file autogen.h.
operator&() [2/8]
flags_t thorin::clos::operator& (alloc_jmpbuf lhs, flags_t rhs) inline
Definition at line 50 of file autogen.h.
operator&() [3/8]
flags_t thorin::clos::operator& (clos lhs, clos rhs) inline
Definition at line 30 of file autogen.h.
operator&() [4/8]
flags_t thorin::clos::operator& (clos lhs, flags_t rhs) inline
Definition at line 29 of file autogen.h.
operator&() [5/8]
flags_t thorin::clos::operator& (longjmp lhs, flags_t rhs) inline
Definition at line 41 of file autogen.h.
operator&() [6/8]
flags_t thorin::clos::operator& (longjmp lhs, longjmp rhs) inline
Definition at line 42 of file autogen.h.
operator&() [7/8]
flags_t thorin::clos::operator& (setjmp lhs, flags_t rhs) inline
Definition at line 15 of file autogen.h.
operator&() [8/8]
flags_t thorin::clos::operator& (setjmp lhs, setjmp rhs) inline
Definition at line 16 of file autogen.h.
operator==() [1/4]
bool thorin::clos::operator== (alloc_jmpbuf lhs, flags_t rhs) inline
Definition at line 49 of file autogen.h.
operator==() [2/4]
bool thorin::clos::operator== (clos lhs, flags_t rhs) inline
Definition at line 28 of file autogen.h.
operator==() [3/4]
bool thorin::clos::operator== (longjmp lhs, flags_t rhs) inline
Definition at line 40 of file autogen.h.
operator==() [4/4]
bool thorin::clos::operator== (setjmp lhs, flags_t rhs) inline
Definition at line 14 of file autogen.h.
operator|() [1/8]
flags_t thorin::clos::operator| (alloc_jmpbuf lhs, alloc_jmpbuf rhs) inline
Definition at line 53 of file autogen.h.
operator|() [2/8]
flags_t thorin::clos::operator| (alloc_jmpbuf lhs, flags_t rhs) inline
Definition at line 52 of file autogen.h.
operator|() [3/8]
flags_t thorin::clos::operator| (clos lhs, clos rhs) inline
Definition at line 32 of file autogen.h.
operator|() [4/8]
flags_t thorin::clos::operator| (clos lhs, flags_t rhs) inline
Definition at line 31 of file autogen.h.
operator|() [5/8]
flags_t thorin::clos::operator| (longjmp lhs, flags_t rhs) inline
Definition at line 43 of file autogen.h.
operator|() [6/8]
flags_t thorin::clos::operator| (longjmp lhs, longjmp rhs) inline
Definition at line 44 of file autogen.h.
operator|() [7/8]
flags_t thorin::clos::operator| (setjmp lhs, flags_t rhs) inline
Definition at line 17 of file autogen.h.
operator|() [8/8]
flags_t thorin::clos::operator| (setjmp lhs, setjmp rhs) inline
Definition at line 18 of file autogen.h.
rebuild()
static const Def * thorin::clos::rebuild (const Def * mem, const Def * env, Defs remaining) static
Definition at line 69 of file clos2sjlj.cpp.
References thorin::ArrayRef< T >::size(), and thorin::Def::world().
register_normalizers()
void thorin::clos::register_normalizers (Normalizers & normalizers)
Referenced by thorin_get_dialect_info().
shift_env()
static size_t thorin::clos::shift_env (size_t i) static
Definition at line 14 of file clos_conv.cpp.
References Clos_Env_Param.
Referenced by clos_insert_env().
skip_env()
static size_t thorin::clos::skip_env (size_t i) static
Definition at line 17 of file clos_conv.cpp.
References Clos_Env_Param.
Referenced by clos_remove_env().
split() [1/3]
static std::array< const Def *, 3 > thorin::clos::split (const Def * def) static
Definition at line 46 of file clos2sjlj.cpp.
References Clos_Env_Param, thorin::Def::num_projs(), op(), thorin::Def::proj(), thorin::Def::sort(), thorin::Term, thorin::Def::type(), thorin::mem::type_mem(), and thorin::Def::world().
split() [2/3]
static DefSet thorin::clos::split (const Def * def, bool keep_others) static
Definition at line 44 of file lower_typed_clos_prep.cpp.
References split().
split() [3/3]
static void thorin::clos::split (DefSet & out, const Def * def, bool as_callee) static
Definition at line 24 of file lower_typed_clos_prep.cpp.
References interesting_type(), thorin::RuntimeCast< Base >::isa(), isa_clos_lit(), op(), thorin::Def::ops(), and split().
Referenced by thorin::clos::Clos2SJLJ::enter(), and split().
Variable Documentation
Clos_Env_Param
const size_t thorin::clos::Clos_Env_Param = 1_u64
Describes where the environment is placed in the argument list.
Definition at line 136 of file clos.h.
Referenced by clos_insert_env(), clos_pack_dbg(), clos_sub_env(), thorin::clos::ClosLit::env_var(), isa_clos_type(), shift_env(), skip_env(), and split().
Dialect_Id
constexpr dialect_t thorin::clos::Dialect_Id = 0x10d4140000000000 static constexpr
Definition at line 9 of file autogen.h.