MimIR: mim::dl Namespace Reference
mim::dl Namespace Reference
Functions
void * open (const char *filename)
void * get (void *handle, const char *symbol_name)
void close (void *handle)
Variables
static constexpr auto extension
Function Documentation
close()
void mim::dl::close (void * handle)
Definition at line 55 of file dl.cpp.
References mim::error().
Referenced by mim::Driver::load().
get()
void * mim::dl::get (void * handle, const char * symbol_name)
Definition at line 36 of file dl.cpp.
References mim::error().
Referenced by mim::Driver::get_fun_ptr(), and mim::Driver::load().
open()
void * mim::dl::open (const char * filename)
Definition at line 17 of file dl.cpp.
References mim::error().
Referenced by mim::Driver::load().
Variable Documentation
extension
auto mim::dl::extension static constexpr
Initial value:
=
    "so"
Definition at line 8 of file dl.h.
Referenced by mim::Driver::load().