Thorin: thorin::plug::core Namespace Reference
thorin::plug::core Namespace Reference
The core Plugin
Enumerations
%core.i1
enum i1 : flags_t
enum I1 : flags_t
%core.i8
enum i8 : flags_t
enum I8 : flags_t
%core.i16
enum i16 : flags_t
enum I16 : flags_t
%core.i32
enum i32 : flags_t
enum I32 : flags_t
%core.i64
enum i64 : flags_t
enum I64 : flags_t
%core.mode
enum mode : flags_t {
us = 0x1104c60000000c00 ,
uS = 0x1104c60000000c01 ,
Us = 0x1104c60000000c02 ,
US = 0x1104c60000000c03 ,
nuw = 0x1104c60000000c04 ,
nsw = 0x1104c60000000c05 ,
nusw = 0x1104c60000000c06
}
%core.minus
enum minus : flags_t
Functions
void register_normalizers (Normalizers &normalizers)
extract_unsafe
Ref extract_unsafe (Ref d, Ref i)
Ref extract_unsafe (Ref d, u64 i)
insert_unsafe
Ref insert_unsafe (Ref d, Ref i, Ref val)
Ref insert_unsafe (Ref d, u64 i, Ref val)
Convert TBound to Sigma
This is WIP.
template<bool up>
const Sigma * convert (const TBound< up > *b)
const Sigma * convert (const Bound *b)
Variables
static constexpr plugin_t Plugin_Id = 0x1104c60000000000
Mode
What should happen if Idx arithmetic overflows?
enum class Mode : nat_t {
none = 0 ,
nsw = 1 << 0 ,
nuw = 1 << 1 ,
nusw = nuw | nsw
}
using VMode = std::variant< Mode, nat_t, Ref >
Give Mode as thorin::plug::math::Mode, thorin::nat_t or Ref.
Ref mode (World &w, VMode m)
thorin::plug::core::VMode -> Ref.
%core.nat
enum nat : flags_t {
add = 0x1104c60000000a00 ,
sub = 0x1104c60000000a01 ,
mul = 0x1104c60000000a02
}
template<nat id>
Ref normalize_nat (Ref type, Ref callee, Ref arg)
%core.ncmp
enum ncmp : flags_t {
gle = 0x1104c60000000b00 ,
f = gle ,
glE = 0x1104c60000000b01 ,
e = glE ,
gLe = 0x1104c60000000b02 ,
l = gLe ,
gLE = 0x1104c60000000b03 ,
le = gLE ,
Gle = 0x1104c60000000b04 ,
g = Gle ,
GlE = 0x1104c60000000b05 ,
ge = GlE ,
GLe = 0x1104c60000000b06 ,
ne = GLe ,
GLE = 0x1104c60000000b07 ,
t = GLE
}
template<ncmp id>
Ref normalize_ncmp (Ref type, Ref callee, Ref arg)
%core.idx
enum idx : flags_t
Ref normalize_idx (Ref type, Ref c, Ref arg)
%core.bit1
enum bit1 : flags_t {
f = gle ,
neg = 0x1104c60000000e01 ,
id = 0x1104c60000000e02 ,
t = GLE
}
template<bit1 id>
Ref normalize_bit1 (Ref type, Ref c, Ref a)
%core.bit2
enum bit2 : flags_t {
f = gle ,
nor = 0x1104c60000000f01 ,
nciff = 0x1104c60000000f02 ,
nfst = 0x1104c60000000f03 ,
niff = 0x1104c60000000f04 ,
nsnd = 0x1104c60000000f05 ,
xor_ = 0x1104c60000000f06 ,
nand = 0x1104c60000000f07 ,
and_ = 0x1104c60000000f08 ,
nxor = 0x1104c60000000f09 ,
snd = 0x1104c60000000f0a ,
iff = 0x1104c60000000f0b ,
fst = 0x1104c60000000f0c ,
ciff = 0x1104c60000000f0d ,
or_ = 0x1104c60000000f0e ,
t = GLE
}
constexpr std::array< std::array< u64, 2 >, 2 > make_truth_table (bit2 id)
Use like this: a op b = tab[a][b]
template<bit2 id>
Ref normalize_bit2 (Ref type, Ref c, Ref arg)
%core.shr
enum shr : flags_t {
a = 0x1104c60000001000 ,
l = gLe
}
template<shr id>
Ref normalize_shr (Ref type, Ref c, Ref arg)
%core.wrap
enum wrap : flags_t {
add = 0x1104c60000000a00 ,
sub = 0x1104c60000000a01 ,
mul = 0x1104c60000000a02 ,
shl = 0x1104c60000001103
}
template<wrap id>
Ref normalize_wrap (Ref type, Ref c, Ref arg)
%core.div
enum div : flags_t {
sdiv = 0x1104c60000001300 ,
udiv = 0x1104c60000001301 ,
srem = 0x1104c60000001302 ,
urem = 0x1104c60000001303
}
template<div id>
Ref normalize_div (Ref full_type, Ref c, Ref arg)
%core.icmp
enum icmp : flags_t {
xygle = 0x1104c60000001400 ,
f = gle ,
xyglE = 0x1104c60000001401 ,
e = glE ,
xygLe = 0x1104c60000001402 ,
xygLE = 0x1104c60000001403 ,
xyGle = 0x1104c60000001404 ,
xyGlE = 0x1104c60000001405 ,
xyGLe = 0x1104c60000001406 ,
xyGLE = 0x1104c60000001407 ,
xYgle = 0x1104c60000001408 ,
xYglE = 0x1104c60000001409 ,
xYgLe = 0x1104c6000000140a ,
sl = xYgLe ,
xYgLE = 0x1104c6000000140b ,
sle = xYgLE ,
xYGle = 0x1104c6000000140c ,
ug = xYGle ,
xYGlE = 0x1104c6000000140d ,
uge = xYGlE ,
xYGLe = 0x1104c6000000140e ,
xYGLE = 0x1104c6000000140f ,
Xygle = 0x1104c60000001410 ,
XyglE = 0x1104c60000001411 ,
XygLe = 0x1104c60000001412 ,
ul = XygLe ,
XygLE = 0x1104c60000001413 ,
ule = XygLE ,
XyGle = 0x1104c60000001414 ,
sg = XyGle ,
XyGlE = 0x1104c60000001415 ,
sge = XyGlE ,
XyGLe = 0x1104c60000001416 ,
XyGLE = 0x1104c60000001417 ,
XYgle = 0x1104c60000001418 ,
XYglE = 0x1104c60000001419 ,
XYgLe = 0x1104c6000000141a ,
XYgLE = 0x1104c6000000141b ,
XYGle = 0x1104c6000000141c ,
XYGlE = 0x1104c6000000141d ,
XYGLe = 0x1104c6000000141e ,
ne = GLe ,
XYGLE = 0x1104c6000000141f ,
t = GLE
}
template<icmp id>
Ref normalize_icmp (Ref type, Ref c, Ref arg)
%core.extrema
enum extrema : flags_t {
sm = 0x1104c60000001500 ,
umin = sm ,
sM = 0x1104c60000001501 ,
umax = sM ,
Sm = 0x1104c60000001502 ,
smin = Sm ,
SM = 0x1104c60000001503 ,
smax = SM
}
template<extrema id>
Ref normalize_extrema (Ref type, Ref c, Ref arg)
%core.abs
enum abs : flags_t
Ref normalize_abs (Ref type, Ref c, Ref arg)
%core.conv
enum conv : flags_t {
s = 0x1104c60000001700 ,
u = 0x1104c60000001701
}
template<conv id>
Ref normalize_conv (Ref dst_t, Ref c, Ref x)
%core.bitcast
enum bitcast : flags_t
Ref normalize_bitcast (Ref dst_t, Ref callee, Ref src)
%core.trait
enum trait : flags_t {
size = 0x1104c60000001900 ,
align = 0x1104c60000001901
}
Ref op (trait o, Ref type)
template<trait id>
Ref normalize_trait (Ref nat, Ref callee, Ref type)
%core.pe
enum pe : flags_t {
hlt = 0x1104c60000001a00 ,
run = 0x1104c60000001a01 ,
known = 0x1104c60000001a02
}
Ref op (pe o, Ref def)
template<pe id>
Ref normalize_pe (Ref type, Ref callee, Ref arg)
%core.zip
enum zip : flags_t
Ref normalize_zip (Ref type, Ref c, Ref arg)
Detailed Description
The core Plugin
Typedef Documentation
VMode
using thorin::plug::core::VMode = typedef std::variant<Mode, nat_t, Ref>
Give Mode as thorin::plug::math::Mode, thorin::nat_t or Ref.
Definition at line 23 of file core.h.
Enumeration Type Documentation
abs
enum thorin::plug::core::abs : flags_t
Definition at line 403 of file autogen.h.
bit1
enum thorin::plug::core::bit1 : flags_t
Enumerator
f
neg
id
t
Definition at line 205 of file autogen.h.
bit2
enum thorin::plug::core::bit2 : flags_t
Enumerator
f
nor
nciff
nfst
niff
nsnd
xor_
nand
and_
nxor
snd
iff
fst
ciff
or_
t
Definition at line 224 of file autogen.h.
bitcast
enum thorin::plug::core::bitcast : flags_t
Definition at line 432 of file autogen.h.
conv
enum thorin::plug::core::conv : flags_t
Enumerator
s
u
Definition at line 415 of file autogen.h.
div
enum thorin::plug::core::div : flags_t
Enumerator
sdiv
udiv
srem
urem
Definition at line 302 of file autogen.h.
extrema
enum thorin::plug::core::extrema : flags_t
Enumerator
sm
umin
sM
umax
Sm
smin
SM
smax
Definition at line 380 of file autogen.h.
i1
enum thorin::plug::core::i1 : flags_t
Definition at line 15 of file autogen.h.
I1
enum thorin::plug::core::I1 : flags_t
Definition at line 70 of file autogen.h.
i16
enum thorin::plug::core::i16 : flags_t
Definition at line 37 of file autogen.h.
I16
enum thorin::plug::core::I16 : flags_t
Definition at line 92 of file autogen.h.
i32
enum thorin::plug::core::i32 : flags_t
Definition at line 48 of file autogen.h.
I32
enum thorin::plug::core::I32 : flags_t
Definition at line 103 of file autogen.h.
i64
enum thorin::plug::core::i64 : flags_t
Definition at line 59 of file autogen.h.
I64
enum thorin::plug::core::I64 : flags_t
Definition at line 114 of file autogen.h.
i8
enum thorin::plug::core::i8 : flags_t
Definition at line 26 of file autogen.h.
I8
enum thorin::plug::core::I8 : flags_t
Definition at line 81 of file autogen.h.
icmp
enum thorin::plug::core::icmp : flags_t
Enumerator
xygle
f
xyglE
e
xygLe
xygLE
xyGle
xyGlE
xyGLe
xyGLE
xYgle
xYglE
xYgLe
sl
xYgLE
sle
xYGle
ug
xYGlE
uge
xYGLe
xYGLE
Xygle
XyglE
XygLe
ul
XygLE
ule
XyGle
sg
XyGlE
sge
XyGLe
XyGLE
XYgle
XYglE
XYgLe
XYgLE
XYGle
XYGlE
XYGLe
ne
XYGLE
t
Definition at line 321 of file autogen.h.
idx
enum thorin::plug::core::idx : flags_t
Definition at line 193 of file autogen.h.
minus
enum thorin::plug::core::minus : flags_t
Definition at line 291 of file autogen.h.
mode
enum thorin::plug::core::mode : flags_t
Enumerator
us
uS
Us
US
nuw
nsw
nusw
Definition at line 174 of file autogen.h.
Mode
enum class thorin::plug::core::Mode : nat_t strong
Enumerator
none
Wrap around.
nsw
No Signed Wrap around.
nuw
No Unsigned Wrap around.
nusw
Definition at line 13 of file core.h.
nat
enum thorin::plug::core::nat : flags_t
Enumerator
add
sub
mul
Definition at line 125 of file autogen.h.
ncmp
enum thorin::plug::core::ncmp : flags_t
Enumerator
gle
f
glE
e
gLe
l
gLE
le
Gle
g
GlE
ge
GLe
ne
GLE
t
Definition at line 143 of file autogen.h.
pe
enum thorin::plug::core::pe : flags_t
Enumerator
hlt
run
known
Definition at line 461 of file autogen.h.
shr
enum thorin::plug::core::shr : flags_t
Enumerator
a
l
Definition at line 255 of file autogen.h.
trait
enum thorin::plug::core::trait : flags_t
Enumerator
size
align
Definition at line 444 of file autogen.h.
wrap
enum thorin::plug::core::wrap : flags_t
Enumerator
add
sub
mul
shl
Definition at line 272 of file autogen.h.
zip
enum thorin::plug::core::zip : flags_t
Definition at line 479 of file autogen.h.
Function Documentation
convert() [1/2]
const Sigma * thorin::plug::core::convert (const Bound * b) inline
Definition at line 90 of file core.h.
References convert().
convert() [2/2]
template<bool up> const Sigma * thorin::plug::core::convert (const TBound< up > * b)
Definition at line 19 of file core.cpp.
References a, align, thorin::Lit::isa(), thorin::Def::num_ops(), op(), thorin::Def::ops(), s, size, and thorin::Def::world().
Referenced by convert(), and normalize_trait().
extract_unsafe() [1/2]
Ref thorin::plug::core::extract_unsafe (Ref d, Ref i) inline
Definition at line 63 of file core.h.
References u.
Referenced by extract_unsafe().
extract_unsafe() [2/2]
Ref thorin::plug::core::extract_unsafe (Ref d, u64 i) inline
Definition at line 67 of file core.h.
References extract_unsafe().
insert_unsafe() [1/2]
Ref thorin::plug::core::insert_unsafe (Ref d, Ref i, Ref val) inline
Definition at line 75 of file core.h.
References u.
Referenced by insert_unsafe().
insert_unsafe() [2/2]
Ref thorin::plug::core::insert_unsafe (Ref d, u64 i, Ref val) inline
Definition at line 79 of file core.h.
References insert_unsafe().
make_truth_table()
constexpr std::array< std::array< u64, 2 >, 2 > thorin::plug::core::make_truth_table (bit2 id) constexpr
Use like this: a op b = tab[a][b]
Definition at line 53 of file core.h.
Referenced by normalize_bit2().
mode()
Ref thorin::plug::core::mode (World & w, VMode m) inline
thorin::plug::core::VMode -> Ref.
Definition at line 26 of file core.h.
normalize_abs()
Ref thorin::plug::core::normalize_abs (Ref type, Ref c, Ref arg)
Definition at line 302 of file normalizers.cpp.
References a, thorin::Def::projs(), and thorin::Def::world().
normalize_bit1()
template<bit1 id> Ref thorin::plug::core::normalize_bit1 (Ref type, Ref c, Ref a)
Definition at line 313 of file normalizers.cpp.
References a, thorin::App::arg(), thorin::App::decurry(), id, thorin::Lit::isa(), neg, s, and thorin::Def::world().
normalize_bit2()
template<bit2 id> Ref thorin::plug::core::normalize_bit2 (Ref type, Ref c, Ref arg)
Definition at line 336 of file normalizers.cpp.
References a, and_, ciff, thorin::commute(), fst, iff, thorin::is_commutative(), thorin::Lit::isa(), make_truth_table(), nand, nciff, neg, nfst, niff, nor, nsnd, nxor, or_, thorin::Def::projs(), s, snd, thorin::Def::world(), and xor_.
normalize_bitcast()
Ref thorin::plug::core::normalize_bitcast (Ref dst_t, Ref callee, Ref src)
Definition at line 597 of file normalizers.cpp.
References thorin::Lit::isa(), l, thorin::Idx::size(), thorin::Def::type(), and thorin::Def::world().
normalize_conv()
template<conv id> Ref thorin::plug::core::normalize_conv (Ref dst_t, Ref c, Ref x)
Definition at line 557 of file normalizers.cpp.
References thorin::App::arg(), thorin::Lit::isa(), l, M, s, thorin::Idx::size2bitwidth(), thorin::Def::type(), u, and thorin::Def::world().
normalize_div()
template<div id> Ref thorin::plug::core::normalize_div (Ref full_type, Ref c, Ref arg)
Definition at line 518 of file normalizers.cpp.
References a, thorin::Lit::isa(), thorin::Def::projs(), sdiv, srem, udiv, urem, and thorin::Def::world().
normalize_extrema()
template<extrema id> Ref thorin::plug::core::normalize_extrema (Ref type, Ref c, Ref arg)
Definition at line 294 of file normalizers.cpp.
References a, thorin::Def::projs(), and thorin::Def::world().
normalize_icmp()
template<icmp id> Ref thorin::plug::core::normalize_icmp (Ref type, Ref c, Ref arg)
Definition at line 278 of file normalizers.cpp.
References a, e, f, ne, thorin::Def::projs(), t, and thorin::Def::world().
normalize_idx()
Ref thorin::plug::core::normalize_idx (Ref type, Ref c, Ref arg)
Definition at line 415 of file normalizers.cpp.
References thorin::Lit::isa(), s, thorin::Idx::size(), and thorin::Def::world().
normalize_nat()
template<nat id> Ref thorin::plug::core::normalize_nat (Ref type, Ref callee, Ref arg)
Definition at line 218 of file normalizers.cpp.
References a, thorin::commute(), thorin::is_commutative(), thorin::Lit::isa(), thorin::Def::projs(), and thorin::Def::world().
normalize_ncmp()
template<ncmp id> Ref thorin::plug::core::normalize_ncmp (Ref type, Ref callee, Ref arg)
Definition at line 250 of file normalizers.cpp.
References a, thorin::commute(), g, ge, thorin::is_commutative(), thorin::Lit::isa(), le, thorin::World::lit_tt(), thorin::Def::projs(), and thorin::Def::world().
normalize_pe()
template<pe id> Ref thorin::plug::core::normalize_pe (Ref type, Ref callee, Ref arg)
Definition at line 707 of file normalizers.cpp.
References thorin::Def::dep_const(), hlt, known, thorin::World::lit_ff(), thorin::match(), and thorin::Def::world().
normalize_shr()
template<shr id> Ref thorin::plug::core::normalize_shr (Ref type, Ref c, Ref arg)
Definition at line 428 of file normalizers.cpp.
References a, thorin::Lit::isa(), l, thorin::Def::projs(), s, thorin::Idx::size(), thorin::Def::type(), and thorin::Def::world().
normalize_trait()
template<trait id> Ref thorin::plug::core::normalize_trait (Ref nat, Ref callee, Ref type)
Definition at line 619 of file normalizers.cpp.
References a, align, convert(), thorin::Lit::isa(), thorin::plug::math::isa_f(), thorin::Def::isa_imm(), thorin::World::lit_nat(), op(), thorin::Def::ops(), thorin::pad(), s, size, thorin::Idx::size(), thorin::Idx::size2bitwidth(), t, and thorin::Def::world().
normalize_wrap()
template<wrap id> Ref thorin::plug::core::normalize_wrap (Ref type, Ref c, Ref arg)
Definition at line 458 of file normalizers.cpp.
References a, add, thorin::Lit::isa(), mul, thorin::Def::projs(), s, shl, thorin::Idx::size(), sub, and thorin::Def::world().
normalize_zip()
Ref thorin::plug::core::normalize_zip (Ref type, Ref c, Ref arg)
Definition at line 666 of file normalizers.cpp.
References thorin::App::arg(), f, thorin::Lit::isa(), thorin::Def::projs(), s, and thorin::Def::world().
op() [1/2]
Ref thorin::plug::core::op (pe o, Ref def) inline
Definition at line 43 of file core.h.
References thorin::Def::type(), and thorin::Def::world().
op() [2/2]
Ref thorin::plug::core::op (trait o, Ref type) inline
Definition at line 35 of file core.h.
References thorin::Def::world().
Referenced by convert(), and normalize_trait().
register_normalizers()
void thorin::plug::core::register_normalizers (Normalizers & normalizers)
Referenced by thorin_get_plugin().
Variable Documentation
Plugin_Id
constexpr plugin_t thorin::plug::core::Plugin_Id = 0x1104c60000000000 static constexpr
Definition at line 10 of file autogen.h.