Thorin: thorin::normalize Namespace Reference
thorin::normalize Namespace Reference
Classes
struct Fold< ICmp, cmp, w >
struct Fold< RCmp, cmp, w >
struct Fold< ROp, ROp::add, w >
struct Fold< ROp, ROp::div, w >
struct Fold< ROp, ROp::mul, w >
struct Fold< ROp, ROp::rem, w >
struct Fold< ROp, ROp::sub, w >
struct Fold< Shr, Shr::ashr, w >
struct Fold< Shr, Shr::lshr, w >
struct Fold< Wrap, Wrap::add, w >
struct Fold< Wrap, Wrap::mul, w >
struct Fold< Wrap, Wrap::shl, w >
struct Fold< Wrap, Wrap::sub, w >
struct FoldConv
struct FoldConv< Conv::r2r, dw, sw >
struct FoldConv< Conv::r2s, dw, sw >
struct FoldConv< Conv::r2u, dw, sw >
struct FoldConv< Conv::s2r, dw, sw >
struct FoldConv< Conv::s2s, dw, sw >
struct FoldConv< Conv::u2r, dw, sw >
struct FoldConv< Conv::u2u, dw, sw >
Functions
constexpr std::array< std::array< u64, 2 >, 2 > make_truth_table (Bit op)
Use like this: a op b = tab[a][b]
template<>
constexpr bool is_commutative (Wrap op)
template<>
constexpr bool is_commutative (ROp op)
template<>
constexpr bool is_commutative (ICmp op)
template<>
constexpr bool is_commutative (RCmp op)
template<>
constexpr bool is_commutative (Bit op)
template<>
constexpr bool is_associative (Bit op)
template<sub_t sub>
static const Def * reassociate (Tag2Enum< sub > op, World &world, const App *ab, const Def *a, const Def *b, const Def *dbg)
Reassociates a und b according to following rules.
template<tag_t tag>
static const Def * merge_cmps (std::array< std::array< u64, 2 >, 2 > tab, const Def *a, const Def *b, const Def *dbg)
Class Documentation
thorin::normalize::FoldConv
struct thorin::normalize::FoldConv
template<Conv op, nat_t, nat_t>
struct thorin::normalize::FoldConv< op, nat_t, nat_t >
Definition at line 173 of file normalize.cpp.
Function Documentation
is_associative()
template<> constexpr bool thorin::normalize::is_associative (Bit op) constexpr
Definition at line 56 of file normalize.cpp.
References thorin::clos::op().
Referenced by reassociate().
is_commutative() [1/5]
template<> constexpr bool thorin::normalize::is_commutative (Bit op) constexpr
Definition at line 47 of file normalize.cpp.
References make_truth_table(), and thorin::clos::op().
Referenced by thorin::normalize_Bit().
is_commutative() [2/5]
template<> constexpr bool thorin::normalize::is_commutative (ICmp op) constexpr
Definition at line 43 of file normalize.cpp.
References thorin::clos::op().
is_commutative() [3/5]
template<> constexpr bool thorin::normalize::is_commutative (RCmp op) constexpr
Definition at line 45 of file normalize.cpp.
References thorin::clos::op().
is_commutative() [4/5]
template<> constexpr bool thorin::normalize::is_commutative (ROp op) constexpr
Definition at line 41 of file normalize.cpp.
References thorin::clos::op().
is_commutative() [5/5]
template<> constexpr bool thorin::normalize::is_commutative (Wrap op) constexpr
Definition at line 39 of file normalize.cpp.
References thorin::clos::op().
make_truth_table()
constexpr std::array< std::array< u64, 2 >, 2 > thorin::normalize::make_truth_table (Bit op) constexpr
Use like this: a op b = tab[a][b]
Definition at line 28 of file normalize.cpp.
References thorin::clos::op().
Referenced by is_commutative(), and thorin::normalize_Bit().
merge_cmps()
template<tag_t tag> static const Def * thorin::normalize::merge_cmps (std::array< std::array< u64, 2 >, 2 > tab, const Def * a, const Def * b, const Def * dbg) static
Definition at line 252 of file normalize.cpp.
reassociate()
template<sub_t sub> static const Def * thorin::normalize::reassociate (Tag2Enum< sub > op, World & world, const App * ab, const Def * a, const Def * b, const Def * dbg) static
Reassociates a und b according to following rules.
We use the following naming convention while literals are prefixed with an 'l':
    a    op     b
(x op y) op (z op w)
(1)     la    op (lz op w) -> (la op lz) op w
(2) (lx op y) op (lz op w) -> (lx op lz) op (y op w)
(3)      a    op (lz op w) ->  lz op (a op w)
(4) (lx op y) op      b    ->  lx op (y op b)
Definition at line 199 of file normalize.cpp.
References thorin::core::RMode::bot, is_associative(), thorin::isa_lit(), thorin::core::WMode::none, thorin::clos::op(), and thorin::core::RMode::reassoc.