Thorin: thorin::DialectInfo Struct Reference
thorin::DialectInfo Struct Reference
Basic info and registration function pointer to be returned from a dialect plugin.
#include <thorin/dialects.h>
Public Attributes
const char * plugin_name
Name of the plugin.
void(* add_passes)(PipelineBuilder &builder)
Callback for registering the dialects' callbacks for the pipeline extension points.
void(* register_passes)(Passes &passes)
void(* register_backends)(Backends &backends)
Callback for registering the mapping from backend names to emission functions in the given backends map.
void(* register_normalizers)(Normalizers &normalizers)
Callback for registering the mapping from axiom ids to normalizer functions in the given normalizers map.
Detailed Description
Basic info and registration function pointer to be returned from a dialect plugin.
Use Dialect to load such a plugin.
Definition at line 22 of file dialects.h.
Member Data Documentation
add_passes
void(* thorin::DialectInfo::add_passes) (PipelineBuilder &builder)
Callback for registering the dialects' callbacks for the pipeline extension points.
Definition at line 27 of file dialects.h.
Referenced by thorin::Dialect::add_passes().
plugin_name
const char* thorin::DialectInfo::plugin_name
Name of the plugin.
Definition at line 24 of file dialects.h.
Referenced by thorin::Dialect::name().
register_backends
void(* thorin::DialectInfo::register_backends) (Backends &backends)
Callback for registering the mapping from backend names to emission functions in the given backends map.
Definition at line 31 of file dialects.h.
Referenced by thorin::Dialect::register_backends().
register_normalizers
void(* thorin::DialectInfo::register_normalizers) (Normalizers &normalizers)
Callback for registering the mapping from axiom ids to normalizer functions in the given normalizers map.
Definition at line 34 of file dialects.h.
Referenced by thorin::Dialect::register_normalizers().
register_passes
void(* thorin::DialectInfo::register_passes) (Passes &passes)
Definition at line 28 of file dialects.h.
Referenced by thorin::Dialect::register_passes().
The documentation for this struct was generated from the following file:
thorin/dialects.h