Thorin: thorin::Loc Struct Reference
thorin::Loc Struct Reference
#include <thorin/debug.h>
Public Member Functions
Loc ()=default
Loc (std::string_view file, Pos begin, Pos finis)
Loc (std::string_view file, Pos pos)
Loc (const Def *dbg)
Loc anew_begin () const
Loc anew_finis () const
const Def * def (World &) const
Public Attributes
std::string file
Pos begin = {uint32_t(-1), uint32_t(-1)}
Pos finis = {uint32_t(-1), uint32_t(-1)}
It's called finis because it refers to the last character within this Location.
Detailed Description
Definition at line 30 of file debug.h.
Constructor & Destructor Documentation
Loc() [1/4]
thorin::Loc::Loc () default
Loc() [2/4]
thorin::Loc::Loc (std::string_view file, Pos begin, Pos finis) inline
Definition at line 32 of file debug.h.
Loc() [3/4]
thorin::Loc::Loc (std::string_view file, Pos pos) inline
Definition at line 36 of file debug.h.
Loc() [4/4]
thorin::Loc::Loc (const Def * dbg)
Definition at line 14 of file debug.cpp.
Member Function Documentation
anew_begin()
Loc thorin::Loc::anew_begin () const inline
Definition at line 40 of file debug.h.
References begin, and file.
anew_finis()
Loc thorin::Loc::anew_finis () const inline
Definition at line 41 of file debug.h.
References file, and finis.
def()
const Def * thorin::Loc::def (World & w) const
Definition at line 30 of file debug.cpp.
References begin, thorin::Pos::def(), file, finis, thorin::World::tuple(), and thorin::World::tuple_str().
Referenced by thorin::Debug::def(), and thorin::World::sym().
Member Data Documentation
begin
Pos thorin::Loc::begin = {uint32_t(-1), uint32_t(-1)}
Definition at line 45 of file debug.h.
Referenced by anew_begin(), def(), thorin::fe::Lexer::lex(), thorin::operator<<(), and thorin::operator==().
file
std::string thorin::Loc::file
Definition at line 44 of file debug.h.
Referenced by anew_begin(), anew_finis(), def(), thorin::fe::Lexer::file(), thorin::fe::Lexer::lex(), thorin::operator<<(), and thorin::operator==().
finis
Pos thorin::Loc::finis = {uint32_t(-1), uint32_t(-1)}
It's called finis because it refers to the last character within this Location.
In the STL the word end refers to the position of something that is one element past the end.
Definition at line 46 of file debug.h.
Referenced by anew_finis(), def(), thorin::utf8::Lexer< Max_Ahead >::next(), thorin::operator<<(), and thorin::operator==().
The documentation for this struct was generated from the following files:
thorin/debug.h
thorin/debug.cpp