MimIR: mim::ll::BB Struct Reference
mim::ll::BB Struct Reference
Public Member Functions
BB ()=default
BB (const BB &)=delete
BB (BB &&other) noexcept=default
BB & operator= (BB other) noexcept
std::deque< std::ostringstream > & head ()
std::deque< std::ostringstream > & body ()
std::deque< std::ostringstream > & tail ()
template<class... Args>
std::string assign (std::string_view name, const char *s, Args &&... args)
template<class... Args>
void tail (const char *s, Args &&... args)
Public Attributes
DefMap< std::deque< std::pair< std::string, std::string > > > phis
std::array< std::deque< std::ostringstream >, 3 > parts
Friends
void swap (BB &a, BB &b) noexcept
Detailed Description
Definition at line 84 of file ll.cpp.
Constructor & Destructor Documentation
BB() [1/3]
mim::ll::BB::BB () default
Referenced by BB(), BB(), operator=(), and swap.
BB() [2/3]
mim::ll::BB::BB (const BB &) delete
References BB().
BB() [3/3]
mim::ll::BB::BB (BB && other) default noexcept
References BB().
Member Function Documentation
assign()
template<class... Args> std::string mim::ll::BB::assign (std::string_view name, const char * s, Args &&... args) inline
Definition at line 95 of file ll.cpp.
References body(), and mim::print().
Referenced by mim::ll::Emitter::emit_bb().
body()
std::deque< std::ostringstream > & mim::ll::BB::body () inline
Definition at line 91 of file ll.cpp.
References parts.
Referenced by assign(), and mim::ll::Emitter::emit_bb().
head()
std::deque< std::ostringstream > & mim::ll::BB::head () inline
Definition at line 90 of file ll.cpp.
References parts.
operator=()
BB & mim::ll::BB::operator= (BB other) inline noexcept
Definition at line 88 of file ll.cpp.
References BB(), and swap.
tail() [1/2]
std::deque< std::ostringstream > & mim::ll::BB::tail () inline
Definition at line 92 of file ll.cpp.
References parts.
Referenced by mim::ll::Emitter::emit_bb(), and tail().
tail() [2/2]
template<class... Args> void mim::ll::BB::tail (const char * s, Args &&... args) inline
Definition at line 101 of file ll.cpp.
References mim::print(), and tail().
Friends And Related Symbol Documentation
swap
void swap (BB & a, BB & b) friend
Definition at line 105 of file ll.cpp.
References BB(), and swap.
Referenced by operator=(), and swap.
Member Data Documentation
parts
std::array<std::deque<std::ostringstream>, 3> mim::ll::BB::parts
Definition at line 112 of file ll.cpp.
Referenced by body(), head(), and tail().
phis
DefMap<std::deque<std::pair<std::string, std::string> > > mim::ll::BB::phis
Definition at line 111 of file ll.cpp.
The documentation for this struct was generated from the following file:
src/mim/plug/core/be/ll.cpp