Thorin: thorin::ll::BB Struct Reference
thorin::ll::BB Struct Reference
Public Member Functions
BB ()=default
BB (const BB &)=delete
BB (BB &&other)
std::deque< std::ostringstream > & head ()
std::deque< std::ostringstream > & body ()
std::deque< std::ostringstream > & tail ()
template<class... Args>
std::string assign (std::string_view name, const char *s, Args &&... args)
template<class... Args>
void tail (const char *s, Args &&... args)
Public Attributes
DefMap< std::vector< std::pair< std::string, std::string > > > phis
std::array< std::deque< std::ostringstream >, 3 > parts
Friends
void swap (BB &a, BB &b)
Detailed Description
Definition at line 47 of file ll.cpp.
Constructor & Destructor Documentation
BB() [1/3]
thorin::ll::BB::BB () default
BB() [2/3]
thorin::ll::BB::BB (const BB &) delete
BB() [3/3]
thorin::ll::BB::BB (BB && other) inline
Definition at line 50 of file ll.cpp.
References swap.
Member Function Documentation
assign()
template<class... Args> std::string thorin::ll::BB::assign (std::string_view name, const char * s, Args &&... args) inline
Definition at line 57 of file ll.cpp.
References body(), and thorin::print().
Referenced by thorin::ll::Emitter::emit_bb().
body()
std::deque< std::ostringstream > & thorin::ll::BB::body () inline
Definition at line 53 of file ll.cpp.
References parts.
Referenced by assign(), and thorin::ll::Emitter::emit_bb().
head()
std::deque< std::ostringstream > & thorin::ll::BB::head () inline
Definition at line 52 of file ll.cpp.
References parts.
tail() [1/2]
std::deque< std::ostringstream > & thorin::ll::BB::tail () inline
Definition at line 54 of file ll.cpp.
References parts.
Referenced by thorin::ll::Emitter::emit_bb(), and tail().
tail() [2/2]
template<class... Args> void thorin::ll::BB::tail (const char * s, Args &&... args) inline
Definition at line 63 of file ll.cpp.
References thorin::print(), and tail().
Friends And Related Function Documentation
swap
void swap (BB & a, BB & b) friend
Definition at line 67 of file ll.cpp.
Referenced by BB().
Member Data Documentation
parts
std::array<std::deque<std::ostringstream>, 3> thorin::ll::BB::parts
Definition at line 74 of file ll.cpp.
Referenced by body(), head(), and tail().
phis
DefMap<std::vector<std::pair<std::string, std::string> > > thorin::ll::BB::phis
Definition at line 73 of file ll.cpp.
The documentation for this struct was generated from the following file:
dialects/core/be/ll/ll.cpp