Thorin: thorin::Log Struct Reference
thorin::Log Struct Reference
#include <thorin/util/log.h>
Public Types
enum class Level {
Error , Warn , Info , Verbose ,
Debug
}
Public Member Functions
template<class... Args>
void log (Level level, Loc loc, const char *fmt, Args &&... args)
void log ()
Dummy for Debug build.
Static Public Member Functions
static std::string_view level2acro (Level)
static Level str2level (std::string_view)
static int level2color (Level level)
static std::string colorize (std::string_view str, int color)
Public Attributes
std::ostream * ostream = nullptr
Level level = Level::Error
Maximum log Level.
Detailed Description
Definition at line 9 of file log.h.
Member Enumeration Documentation
Level
enum class thorin::Log::Level strong
Enumerator
Error
Warn
Info
Verbose
Debug
Definition at line 10 of file log.h.
Member Function Documentation
colorize()
std::string thorin::Log::colorize (std::string_view str, int color) static
Definition at line 48 of file log.cpp.
Referenced by log().
level2acro()
std::string_view thorin::Log::level2acro (Level level) static
Definition at line 6 of file log.cpp.
References Debug, Error, Info, level, thorin::unreachable(), Verbose, and Warn.
Referenced by log().
level2color()
int thorin::Log::level2color (Level level) static
Definition at line 27 of file log.cpp.
References Debug, Error, Info, level, thorin::unreachable(), Verbose, and Warn.
Referenced by log().
log() [1/2]
void thorin::Log::log () inline
Dummy for Debug build.
Definition at line 21 of file log.h.
log() [2/2]
template<class... Args> void thorin::Log::log (Level level, Loc loc, const char * fmt, Args &&... args) inline
Definition at line 13 of file log.h.
References colorize(), thorin::fmt(), level, level2acro(), level2color(), ostream, and thorin::print().
str2level()
Log::Level thorin::Log::str2level (std::string_view s) static
Definition at line 17 of file log.cpp.
References Debug, Error, Info, Verbose, and Warn.
Member Data Documentation
level
Level thorin::Log::level = Level::Error
Maximum log Level.
Definition at line 29 of file log.h.
Referenced by level2acro(), level2color(), and log().
ostream
std::ostream* thorin::Log::ostream = nullptr
Definition at line 28 of file log.h.
Referenced by log().
The documentation for this struct was generated from the following files:
thorin/util/log.h
thorin/util/log.cpp