var searchData=
[
  ['range_0',['%regex.range',['../regex.html#autotoc_md297',1,'']]],
  ['re_1',['RE',['../regex.html#autotoc_md292',1,'']]],
  ['read_2',['%matrix.read',['../matrix.html#autotoc_md223',1,'']]],
  ['recommended_20design_20pattern_3',['Recommended design pattern',['../phases.html#autotoc_md76',1,'']]],
  ['reduce_4',['%tensor.reduce',['../tensor.html#autotoc_md319',1,'']]],
  ['reference_5',['Reference',['../cli.html',1,'Command-Line Reference'],['../langref.html',1,'Mim Language Reference']]],
  ['refine_6',['%refly.refine',['../refly.html#autotoc_md287',1,'']]],
  ['reflect_7',['Reify / Reflect',['../refly.html#autotoc_md276',1,'']]],
  ['reflect_8',['%refly.reflect',['../refly.html#autotoc_md278',1,'']]],
  ['refly_20check_9',['%refly.check',['../refly.html#autotoc_md285',1,'']]],
  ['refly_20dbg_10',['%refly.dbg',['../refly.html#autotoc_md282',1,'']]],
  ['refly_20equiv_11',['%refly.equiv',['../refly.html#autotoc_md284',1,'']]],
  ['refly_20gid_12',['%refly.gid',['../refly.html#autotoc_md281',1,'']]],
  ['refly_20plugin_13',['The refly Plugin',['../refly.html',1,'']]],
  ['refly_20refine_14',['%refly.refine',['../refly.html#autotoc_md287',1,'']]],
  ['refly_20reflect_15',['%refly.reflect',['../refly.html#autotoc_md278',1,'']]],
  ['refly_20reify_16',['%refly.reify',['../refly.html#autotoc_md277',1,'']]],
  ['refly_20type_17',['%refly.type',['../refly.html#autotoc_md280',1,'']]],
  ['regex_20any_18',['%regex.any',['../regex.html#autotoc_md302',1,'']]],
  ['regex_20cls_19',['%regex.cls.*',['../regex.html#autotoc_md301',1,'']]],
  ['regex_20conj_20',['%regex.conj',['../regex.html#autotoc_md294',1,'']]],
  ['regex_20disj_21',['%regex.disj',['../regex.html#autotoc_md295',1,'']]],
  ['regex_20empty_22',['%regex.empty',['../regex.html#autotoc_md303',1,'']]],
  ['regex_20lit_23',['%regex.lit',['../regex.html#autotoc_md298',1,'']]],
  ['regex_20neg_5flookahead_24',['%regex.neg_lookahead',['../regex.html#autotoc_md300',1,'']]],
  ['regex_20not_5f_25',['%regex.not_',['../regex.html#autotoc_md299',1,'']]],
  ['regex_20plugin_26',['The regex Plugin',['../regex.html',1,'']]],
  ['regex_20quant_27',['%regex.quant.*',['../regex.html#autotoc_md305',1,'']]],
  ['regex_20range_28',['%regex.range',['../regex.html#autotoc_md297',1,'']]],
  ['registered_20translations_29',['Registered translations',['../autodiff.html#autotoc_md118',1,'']]],
  ['reify_30',['%refly.reify',['../refly.html#autotoc_md277',1,'']]],
  ['reify_20reflect_31',['Reify / Reflect',['../refly.html#autotoc_md276',1,'']]],
  ['related_20to_20longjmp_32',['Operations related to longjmp',['../clos.html#autotoc_md123',1,'']]],
  ['relationship_20between_20both_33',['Relationship between both',['../rewriting.html#autotoc_md103',1,'']]],
  ['remem_34',['%mem.remem',['../mem.html#autotoc_md242',1,'']]],
  ['repls_35',['Repls',['../autodiff.html#autotoc_md116',1,'Repls'],['../compile.html#autotoc_md135',1,'Repls'],['../gpu.html#autotoc_md196',1,'Repls'],['../mem.html#autotoc_md252',1,'Repls'],['../refly.html#autotoc_md289',1,'Repls']]],
  ['reset_20between_20iterations_36',['Reset between Iterations',['../phases.html#autotoc_md61',1,'']]],
  ['reshape_37',['reshape',['../tensor.html#autotoc_md315',1,'%tensor.reshape'],['../mem.html#autotoc_md254',1,'mem.reshape']]],
  ['rewrite_20does_38',['What the rewrite does',['../phases.html#autotoc_md73',1,'']]],
  ['rewriter_39',['Rewriter',['../phases.html#autotoc_md60',1,'Powered by Rewriter'],['../rewriting.html#rewriter',1,'Rewriter']]],
  ['rewrites_20and_20scoped_20substitutions_40',['Mutable Rewrites and Scoped Substitutions',['../rewriting.html#autotoc_md98',1,'']]],
  ['rewriting_41',['Rewriting',['../rewriting.html',1,'']]],
  ['right_20base_20class_42',['Choosing the right base class',['../phases.html#autotoc_md75',1,'']]],
  ['round_43',['%math.round',['../math.html#autotoc_md209',1,'']]],
  ['rrt_44',['%math.rrt',['../math.html#autotoc_md215',1,'']]],
  ['rt_45',['%math.rt',['../math.html#autotoc_md204',1,'']]],
  ['rwphase_46',['RWPhase',['../phases.html#phases_rwphase',1,'']]]
];
