var searchData=
[
  ['icmp_0',['%core.icmp',['../core.html#autotoc_md144',1,'']]],
  ['icmp_20xygle_20eq_1',['%core.icmp.xYgLE (eq)',['../autodiff.html#autotoc_md113',1,'']]],
  ['idx_2',['%core.idx',['../core.html#autotoc_md138',1,'']]],
  ['immutables_3',['Downcast to Immutables',['../dev.html#autotoc_md20',1,'']]],
  ['immutables_20vs_20mutables_4',['Immutables vs. Mutables',['../dev.html#mut',1,'']]],
  ['in_20tree_20plugin_5',['In Tree Plugin',['../plugins.html#autotoc_md76',1,'Create a New In-Tree Plugin'],['../plugins.html#autotoc_md78',1,'Extract an Existing In-Tree Plugin']]],
  ['indices_6',['Working with Indices',['../dev.html#autotoc_md27',1,'']]],
  ['init_7',['init',['../matrix.html#autotoc_md221',1,'%matrix.init'],['../ord.html#autotoc_md258',1,'%ord.init']]],
  ['innovations_8',['🔥 Key Innovations',['../index.html#autotoc_md85',1,'']]],
  ['ins_9',['Downcasts for Built-ins',['../dev.html#cast_builtin',1,'']]],
  ['insert_10',['insert',['../matrix.html#autotoc_md219',1,'%matrix.insert'],['../ord.html#autotoc_md267',1,'%ord.insert']]],
  ['inspect_11',['Inspect',['../refly.html#autotoc_md273',1,'']]],
  ['install_20optional_12',['📦 Install (optional)',['../index.html#autotoc_md84',1,'']]],
  ['integer_20operations_13',['Integer Operations',['../core.html#autotoc_md136',1,'']]],
  ['ir_14',['Matching IR',['../dev.html#autotoc_md18',1,'']]],
  ['is_20useful_15',['Why this split is useful',['../phases.html#autotoc_md71',1,'']]],
  ['is_5fempty_16',['%ord.is_empty',['../ord.html#autotoc_md262',1,'']]],
  ['is_5floaded_17',['%compile.is_loaded',['../compile.html#autotoc_md125',1,'']]],
  ['is_5funique_18',['%vec.is_unique',['../vec.html#autotoc_md329',1,'']]],
  ['item_20synchronization_19',['Work-Item Synchronization',['../gpu.html#autotoc_md186',1,'']]],
  ['iterating_20over_20the_20program_20',['Iterating over the Program',['../dev.html#autotoc_md33',1,'']]],
  ['iterations_21',['Reset between Iterations',['../phases.html#autotoc_md58',1,'']]],
  ['iterators_22',['Iterators',['../vec.html#autotoc_md322',1,'']]]
];
