var searchData=
[
  ['tensor_20broadcast_5fin_5fdim_0',['%tensor.broadcast_in_dim',['../tensor.html#autotoc_md318',1,'']]],
  ['tensor_20dot_5fgeneral_1',['%tensor.dot_general',['../tensor.html#autotoc_md316',1,'']]],
  ['tensor_20element_5fwise_2',['%tensor.element_wise',['../tensor.html#autotoc_md312',1,'']]],
  ['tensor_20map_5freduce_3',['%tensor.map_reduce',['../tensor.html#autotoc_md320',1,'']]],
  ['tensor_20plugin_4',['The tensor Plugin',['../tensor.html',1,'']]],
  ['tensor_20prod_5f2d_5',['tensor prod_2d',['../tensor.html#autotoc_md311',1,'%tensor.prod_2d'],['../tensor.html#autotoc_md317',1,'%tensor.prod_2d']]],
  ['tensor_20reduce_6',['%tensor.reduce',['../tensor.html#autotoc_md319',1,'']]],
  ['tensor_20reshape_7',['%tensor.reshape',['../tensor.html#autotoc_md315',1,'']]],
  ['tensor_20slice_8',['%tensor.slice',['../tensor.html#autotoc_md314',1,'']]],
  ['tensor_20transpose_9',['%tensor.transpose',['../tensor.html#autotoc_md313',1,'']]],
  ['terminals_10',['Terminals',['../langref.html#terminals',1,'']]],
  ['terminals_11',['terminals',['../langref.html#autotoc_md41',1,'Pattern terminals'],['../langref.html#autotoc_md38',1,'Primary terminals'],['../langref.html#autotoc_md39',1,'Secondary terminals']]],
  ['testing_12',['Testing',['../refly.html#autotoc_md283',1,'']]],
  ['tests_13',['Tests',['../coding.html#autotoc_md14',1,'&lt;span class=&quot;tt&quot;&gt;lit&lt;/span&gt; Tests'],['../coding.html#tests',1,'Tests']]],
  ['the_20affine_20plugin_14',['The affine Plugin',['../affine.html',1,'']]],
  ['the_20analysis_20computes_15',['What the analysis computes',['../phases.html#autotoc_md72',1,'']]],
  ['the_20automatic_20differentiation_20plugin_16',['The automatic differentiation Plugin',['../autodiff.html',1,'']]],
  ['the_20clos_20plugin_17',['The clos Plugin',['../clos.html',1,'']]],
  ['the_20command_20line_18',['Triggering Breakpoints from the Command Line',['../coding.html#autotoc_md15',1,'']]],
  ['the_20compile_20plugin_19',['The compile Plugin',['../compile.html',1,'']]],
  ['the_20core_20plugin_20',['The core Plugin',['../core.html',1,'']]],
  ['the_20demo_20plugin_21',['The demo Plugin',['../demo.html',1,'']]],
  ['the_20direct_20style_20plugin_22',['The direct style Plugin',['../direct.html',1,'']]],
  ['the_20gpu_20plugin_23',['The gpu Plugin',['../gpu.html',1,'']]],
  ['the_20math_20plugin_24',['The math Plugin',['../math.html',1,'']]],
  ['the_20matrix_20plugin_25',['The matrix Plugin',['../matrix.html',1,'']]],
  ['the_20mem_20plugin_26',['The mem Plugin',['../mem.html',1,'']]],
  ['the_20opt_20plugin_27',['The opt Plugin',['../opt.html',1,'']]],
  ['the_20ord_20plugin_28',['The ord Plugin',['../ord.html',1,'']]],
  ['the_20program_29',['Iterating over the Program',['../dev.html#autotoc_md36',1,'']]],
  ['the_20refly_20plugin_30',['The refly Plugin',['../refly.html',1,'']]],
  ['the_20regex_20plugin_31',['The regex Plugin',['../regex.html',1,'']]],
  ['the_20rewrite_20does_32',['What the rewrite does',['../phases.html#autotoc_md73',1,'']]],
  ['the_20right_20base_20class_33',['Choosing the right base class',['../phases.html#autotoc_md75',1,'']]],
  ['the_20tensor_20plugin_34',['The tensor Plugin',['../tensor.html',1,'']]],
  ['the_20tuple_20plugin_35',['The tuple Plugin',['../tuple.html',1,'']]],
  ['the_20vec_20plugin_36',['The vec Plugin',['../vec.html',1,'']]],
  ['third_20party_20builds_37',['Standalone Third-Party Builds',['../plugins.html#autotoc_md83',1,'']]],
  ['third_20party_20plugin_38',['Create a Third-Party Plugin',['../plugins.html#autotoc_md80',1,'']]],
  ['third_20party_20plugin_20discovery_39',['Third-Party Plugin Discovery',['../plugins.html#autotoc_md81',1,'']]],
  ['this_20split_20is_20useful_40',['Why this split is useful',['../phases.html#autotoc_md74',1,'']]],
  ['thresholded_20variants_41',['Thresholded Variants',['../dev.html#autotoc_md33',1,'']]],
  ['to_20immutables_42',['Downcast to Immutables',['../dev.html#autotoc_md23',1,'']]],
  ['to_20longjmp_43',['Operations related to longjmp',['../clos.html#autotoc_md123',1,'']]],
  ['to_20mutables_44',['Downcast to Mutables',['../dev.html#autotoc_md24',1,'']]],
  ['todo_20list_45',['Todo List',['../todo.html',1,'']]],
  ['trait_46',['%core.trait',['../core.html#autotoc_md157',1,'']]],
  ['translations_47',['Registered translations',['../autodiff.html#autotoc_md118',1,'']]],
  ['transpose_48',['transpose',['../tensor.html#autotoc_md313',1,'%tensor.transpose'],['../matrix.html#autotoc_md231',1,'transpose']]],
  ['tree_20plugin_49',['Tree Plugin',['../plugins.html#autotoc_md79',1,'Create a New In-Tree Plugin'],['../plugins.html#autotoc_md82',1,'Extract an Existing In-Tree Plugin']]],
  ['tri_50',['%math.tri',['../math.html#autotoc_md202',1,'']]],
  ['triggering_20breakpoints_20from_20the_20command_20line_51',['Triggering Breakpoints from the Command Line',['../coding.html#autotoc_md15',1,'']]],
  ['tuple_20cat_52',['%tuple.cat',['../tuple.html#autotoc_md324',1,'']]],
  ['tuple_20contains_53',['%tuple.contains',['../tuple.html#autotoc_md325',1,'']]],
  ['tuple_20plugin_54',['The tuple Plugin',['../tuple.html',1,'']]],
  ['tuple_20typecat_55',['%tuple.typecat',['../tuple.html#autotoc_md323',1,'']]],
  ['tuple_20zip_56',['%tuple.zip',['../tuple.html#autotoc_md326',1,'']]],
  ['type_57',['%refly.type',['../refly.html#autotoc_md280',1,'']]],
  ['typecat_58',['%tuple.typecat',['../tuple.html#autotoc_md323',1,'']]],
  ['types_59',['Types',['../gpu.html#autotoc_md169',1,'Memory Types'],['../gpu.html#autotoc_md170',1,'Pointer Types'],['../autodiff.html#autotoc_md110',1,'Types'],['../compile.html#autotoc_md128',1,'Types'],['../gpu.html#autotoc_md167',1,'Types'],['../math.html#autotoc_md197',1,'Types'],['../matrix.html#autotoc_md217',1,'Types'],['../mem.html#autotoc_md237',1,'Types'],['../ord.html#autotoc_md260',1,'Types'],['../refly.html#autotoc_md275',1,'Types'],['../regex.html#autotoc_md291',1,'Types'],['../tensor.html#autotoc_md309',1,'Types']]],
  ['types_60',['types',['../langref.html#autotoc_md53',1,'Function types'],['../langref.html#autotoc_md43',1,'Kinds and builtin types'],['../langref.html#autotoc_md49',1,'Summary: Functions and types']]],
  ['typical_20shape_61',['Typical Shape',['../phases.html#autotoc_md59',1,'Typical Shape'],['../phases.html#autotoc_md66',1,'Typical Shape'],['../phases.html#autotoc_md68',1,'Typical Shape']]],
  ['typical_20usage_62',['Typical Usage',['../phases.html#autotoc_md67',1,'Typical Usage'],['../rewriting.html#autotoc_md100',1,'Typical Usage'],['../rewriting.html#autotoc_md102',1,'Typical Usage']]]
];
