var searchData=
[
  ['icmp_0',['%core.icmp',['../core.html#autotoc_md149',1,'']]],
  ['icmp_20xygle_20eq_1',['%core.icmp.xYgLE (eq)',['../autodiff.html#autotoc_md118',1,'']]],
  ['idx_2',['%core.idx',['../core.html#autotoc_md143',1,'']]],
  ['immutables_3',['Immutables',['../dev.html#autotoc_md24',1,'Downcast to Immutables'],['../dev.html#autotoc_md20',1,'Immutables']]],
  ['immutables_20vs_20mutables_4',['Immutables vs. Mutables',['../dev.html#mut',1,'']]],
  ['in_20tree_20plugin_5',['In Tree Plugin',['../plugins.html#autotoc_md78',1,'Create a New In-Tree Plugin'],['../plugins.html#autotoc_md81',1,'Extract an Existing In-Tree Plugin']]],
  ['indices_6',['Working with Indices',['../dev.html#autotoc_md31',1,'']]],
  ['init_7',['init',['../matrix.html#autotoc_md226',1,'%matrix.init'],['../ord.html#autotoc_md273',1,'%ord.init']]],
  ['innovations_8',['🔥 Key Innovations',['../index.html#autotoc_md88',1,'']]],
  ['ins_9',['Downcasts for Built-ins',['../dev.html#cast_builtin',1,'']]],
  ['insert_10',['insert',['../matrix.html#autotoc_md224',1,'%matrix.insert'],['../ord.html#autotoc_md282',1,'%ord.insert']]],
  ['inspect_11',['Inspect',['../refly.html#autotoc_md288',1,'']]],
  ['install_20optional_12',['📦 Install (Optional)',['../index.html#autotoc_md87',1,'']]],
  ['integer_20operations_13',['Integer Operations',['../core.html#autotoc_md141',1,'']]],
  ['ir_14',['Matching IR',['../dev.html#autotoc_md22',1,'']]],
  ['is_20useful_15',['Why This Split Is Useful',['../phases.html#autotoc_md73',1,'']]],
  ['is_5fempty_16',['%ord.is_empty',['../ord.html#autotoc_md277',1,'']]],
  ['is_5floaded_17',['%compile.is_loaded',['../compile.html#autotoc_md130',1,'']]],
  ['is_5fsome_18',['option.is_some',['../option.html#autotoc_md265',1,'']]],
  ['is_5funique_19',['%vec.is_unique',['../vec.html#autotoc_md344',1,'']]],
  ['item_20synchronization_20',['Work-Item Synchronization',['../gpu.html#autotoc_md191',1,'']]],
  ['iterating_20over_20the_20program_21',['Iterating over the Program',['../dev.html#autotoc_md37',1,'']]],
  ['iterations_22',['Reset Between Iterations',['../phases.html#autotoc_md62',1,'']]],
  ['iterators_23',['Iterators',['../vec.html#autotoc_md337',1,'']]]
];
