var searchData=
[
  ['dbg_0',['%refly.dbg',['../refly.html#autotoc_md281',1,'']]],
  ['debugging_1',['Debugging',['../coding.html',1,'Contributing &amp; Debugging'],['../coding.html#autotoc_md9',1,'Debugging']]],
  ['debugging_20features_2',['Debugging Features',['../cli.html#clidebug',1,'']]],
  ['declaration_20blocks_3',['Local Declaration Blocks',['../langref.html#autotoc_md48',1,'']]],
  ['declarations_4',['Declarations',['../langref.html#decl',1,'Declarations'],['../langref.html#autotoc_md51',1,'Declarations']]],
  ['demo_20const_5fidx_5',['%demo.const_idx',['../demo.html#autotoc_md160',1,'']]],
  ['demo_20plugin_6',['The demo Plugin',['../demo.html',1,'']]],
  ['dependencies_7',['Dependencies',['../coding.html#autotoc_md1',1,'Dependencies'],['../affine.html#autotoc_md103',1,'Dependencies'],['../autodiff.html#autotoc_md108',1,'Dependencies'],['../clos.html#autotoc_md121',1,'Dependencies'],['../core.html#autotoc_md137',1,'Dependencies'],['../direct.html#autotoc_md161',1,'Dependencies'],['../gpu.html#autotoc_md165',1,'Dependencies'],['../matrix.html#autotoc_md215',1,'Dependencies'],['../mem.html#autotoc_md235',1,'Dependencies'],['../opt.html#autotoc_md255',1,'Dependencies'],['../ord.html#autotoc_md258',1,'Dependencies'],['../refly.html#autotoc_md273',1,'Dependencies'],['../regex.html#autotoc_md289',1,'Dependencies'],['../tensor.html#autotoc_md307',1,'Dependencies'],['../tuple.html#autotoc_md320',1,'Dependencies'],['../vec.html#autotoc_md326',1,'Dependencies']]],
  ['deprecated_20list_8',['Deprecated List',['../deprecated.html',1,'']]],
  ['design_20pattern_9',['Recommended Design Pattern',['../phases.html#autotoc_md75',1,'']]],
  ['developer_20guide_10',['Developer Guide',['../dev.html',1,'']]],
  ['diff_11',['%vec.diff',['../vec.html#autotoc_md336',1,'']]],
  ['differentiation_20plugin_12',['The automatic differentiation Plugin',['../autodiff.html',1,'']]],
  ['direct_20cps2ds_13',['%direct.cps2ds',['../direct.html#autotoc_md163',1,'']]],
  ['direct_20style_20plugin_14',['The direct style Plugin',['../direct.html',1,'']]],
  ['discovery_15',['Third-Party Plugin Discovery',['../plugins.html#autotoc_md80',1,'']]],
  ['disj_16',['%regex.disj',['../regex.html#autotoc_md294',1,'']]],
  ['displaying_20dot_20graphs_17',['Displaying DOT Graphs',['../coding.html#autotoc_md11',1,'']]],
  ['div_18',['%core.div',['../core.html#autotoc_md148',1,'']]],
  ['does_19',['What the Rewrite Does',['../phases.html#autotoc_md72',1,'']]],
  ['dominance_20',['🪾 SSA without Dominance',['../index.html#autotoc_md91',1,'']]],
  ['dot_20graphs_21',['Displaying DOT Graphs',['../coding.html#autotoc_md11',1,'']]],
  ['dot_5fgeneral_22',['%tensor.dot_general',['../tensor.html#autotoc_md315',1,'']]],
  ['downcast_23',['General Downcast',['../dev.html#autotoc_md23',1,'']]],
  ['downcast_20to_20immutables_24',['Downcast to Immutables',['../dev.html#autotoc_md24',1,'']]],
  ['downcast_20to_20mutables_25',['Downcast to Mutables',['../dev.html#autotoc_md25',1,'']]],
  ['downcasts_20for_20built_20ins_26',['Downcasts for Built-ins',['../dev.html#cast_builtin',1,'']]],
  ['doxygen_20style_27',['Doxygen Style',['../coding.html#autotoc_md4',1,'']]],
  ['dumping_28',['Dumping',['../coding.html#autotoc_md10',1,'']]]
];
