var searchData=
[
  ['scan_0',['%vec.scan',['../vec.html#autotoc_md325',1,'']]],
  ['scanning_1',['Scanning',['../vec.html#autotoc_md324',1,'']]],
  ['sccp_2',['Example: SCCP',['../phases.html#autotoc_md70',1,'']]],
  ['sccp_20cpp_3',['&lt;span class=&quot;tt&quot;&gt;sccp.cpp&lt;/span&gt;',['../phases.html#autotoc_md72',1,'']]],
  ['sccp_20h_4',['&lt;span class=&quot;tt&quot;&gt;sccp.h&lt;/span&gt;',['../phases.html#autotoc_md71',1,'']]],
  ['scoped_20substitution_5',['Scoped Substitution',['../rewriting.html#autotoc_md94',1,'']]],
  ['scoping_6',['Scoping',['../langref.html#autotoc_md55',1,'Scoping'],['../rewriting.html#autotoc_md92',1,'Scoping']]],
  ['sea_20of_20nodes_7',['🌊 Sea of Nodes',['../index.html#autotoc_md86',1,'']]],
  ['secondary_20terminals_8',['Secondary terminals',['../langref.html#autotoc_md37',1,'']]],
  ['select_9',['%core.select',['../core.html#autotoc_md152',1,'']]],
  ['set_20ord_20map_10',['%ord.Set / %ord.Map',['../ord.html#autotoc_md255',1,'']]],
  ['sgn_11',['%math.sgn',['../math.html#autotoc_md207',1,'']]],
  ['shape_12',['Shape',['../dev.html#autotoc_md32',1,'Shape'],['../phases.html#autotoc_md60',1,'Typical Shape'],['../phases.html#autotoc_md67',1,'Typical Shape'],['../phases.html#autotoc_md69',1,'Typical Shape']]],
  ['shape_13',['%matrix.shape',['../matrix.html#autotoc_md213',1,'']]],
  ['shr_14',['%core.shr',['../core.html#autotoc_md140',1,'']]],
  ['side_20effects_15',['Side Effects',['../mem.html#autotoc_md232',1,'Operations w/ Side Effects'],['../mem.html#autotoc_md241',1,'Operations w/o Side Effects']]],
  ['sigmas_16',['Field names of sigmas',['../langref.html#autotoc_md58',1,'']]],
  ['size_17',['%ord.size',['../ord.html#autotoc_md260',1,'']]],
  ['slf_18',['%math.slf',['../math.html#autotoc_md206',1,'']]],
  ['slice_19',['%tensor.slice',['../tensor.html#autotoc_md307',1,'']]],
  ['slot_20',['%mem.slot',['../mem.html#autotoc_md237',1,'']]],
  ['spaces_21',['Address Spaces',['../gpu.html#autotoc_md161',1,'']]],
  ['split_20is_20useful_22',['Why this split is useful',['../phases.html#autotoc_md75',1,'']]],
  ['ssa_20without_20dominance_23',['🪾 SSA without Dominance',['../index.html#autotoc_md87',1,'']]],
  ['stages_24',['Stages',['../autodiff.html#autotoc_md108',1,'Stages'],['../gpu.html#autotoc_md188',1,'Stages'],['../mem.html#autotoc_md243',1,'Stages'],['../refly.html#autotoc_md281',1,'Stages']]],
  ['start_25',['🚀 Quick Start',['../index.html#autotoc_md82',1,'']]],
  ['store_26',['%mem.store',['../mem.html#autotoc_md234',1,'']]],
  ['stream_5fdeinit_27',['%gpu.stream_deinit',['../gpu.html#autotoc_md168',1,'']]],
  ['stream_5finit_28',['%gpu.stream_init',['../gpu.html#autotoc_md167',1,'']]],
  ['stream_5fsync_29',['%gpu.stream_sync',['../gpu.html#autotoc_md169',1,'']]],
  ['streams_30',['Streams',['../gpu.html#autotoc_md164',1,'Streams'],['../gpu.html#autotoc_md166',1,'Streams']]],
  ['structure_31',['Lexical Structure',['../langref.html#lex',1,'']]],
  ['style_32',['Style',['../coding.html#autotoc_md2',1,'Coding Style'],['../coding.html#autotoc_md3',1,'Doxygen Style']]],
  ['style_33',['()-style vs []-style',['../langref.html#autotoc_md41',1,'']]],
  ['style_20plugin_34',['The direct style Plugin',['../direct.html',1,'']]],
  ['style_20vs_20style_35',['()-style vs []-style',['../langref.html#autotoc_md41',1,'']]],
  ['substitution_36',['Scoped Substitution',['../rewriting.html#autotoc_md94',1,'']]],
  ['subtags_37',['Subtags',['../dev.html#autotoc_md26',1,'With Subtags'],['../dev.html#autotoc_md25',1,'Without Subtags']]],
  ['sum_38',['sum',['../matrix.html#autotoc_md225',1,'']]],
  ['summary_39',['Summary',['../dev.html#autotoc_md23',1,'Summary'],['../dev.html#autotoc_md27',1,'Summary'],['../dev.html#autotoc_md33',1,'Summary'],['../phases.html#autotoc_md79',1,'Summary']]],
  ['summary_3a_20functions_20and_20types_40',['Summary: Functions and types',['../langref.html#autotoc_md50',1,'']]],
  ['sync_5fwork_5fitems_41',['%gpu.sync_work_items',['../gpu.html#autotoc_md186',1,'']]],
  ['synced_5fscope_42',['%gpu.synced_scope',['../gpu.html#autotoc_md187',1,'']]],
  ['synchronization_43',['Work-Item Synchronization',['../gpu.html#autotoc_md185',1,'']]],
  ['syntax_20highlighting_44',['Syntax Highlighting',['../coding.html#autotoc_md14',1,'']]]
];
