var searchData=
[
  ['a_20new_20in_20tree_20plugin_0',['Create a New In-Tree Plugin',['../plugins.html#autotoc_md79',1,'']]],
  ['a_20third_20party_20plugin_1',['Create a Third-Party Plugin',['../plugins.html#autotoc_md80',1,'']]],
  ['abs_2',['abs',['../core.html#autotoc_md152',1,'%core.abs'],['../math.html#autotoc_md208',1,'%math.abs']]],
  ['ad_3',['%autodiff.ad',['../autodiff.html#autotoc_md112',1,'']]],
  ['add_4',['add',['../autodiff.html#autotoc_md114',1,'%autodiff.add'],['../autodiff.html#autotoc_md120',1,'%core.wrap.add']]],
  ['add_5fmim_5fplugin_5',['add_mim_plugin',['../add_mim_plugin_cmake.html',1,'']]],
  ['address_20spaces_6',['Address Spaces',['../gpu.html#autotoc_md168',1,'']]],
  ['affine_20for_7',['%affine.For',['../affine.html#autotoc_md106',1,'']]],
  ['affine_20lower_5ffor_5fpass_8',['%affine.lower_for_pass',['../affine.html#autotoc_md108',1,'']]],
  ['affine_20plugin_9',['The affine Plugin',['../affine.html',1,'']]],
  ['alloc_10',['alloc',['../gpu.html#autotoc_md178',1,'%gpu.alloc'],['../mem.html#autotoc_md243',1,'%mem.alloc']]],
  ['alloc_5fasync_11',['%gpu.alloc_async',['../gpu.html#autotoc_md184',1,'']]],
  ['alloc_5fcopy_12',['%gpu.alloc_copy',['../gpu.html#autotoc_md182',1,'']]],
  ['alloc_5fcopy_5fasync_13',['%gpu.alloc_copy_async',['../gpu.html#autotoc_md188',1,'']]],
  ['an_20existing_20in_20tree_20plugin_14',['Extract an Existing In-Tree Plugin',['../plugins.html#autotoc_md82',1,'']]],
  ['analysis_15',['Analysis',['../phases.html#phases_analysis',1,'Analysis'],['../phases.html#autotoc_md65',1,'Optional Pre-Analysis']]],
  ['analysis_20computes_16',['What the Analysis Computes',['../phases.html#autotoc_md72',1,'']]],
  ['and_20basic_20forms_17',['Literals and Basic Forms',['../langref.html#autotoc_md44',1,'']]],
  ['and_20builtin_20types_18',['Kinds and Builtin Types',['../langref.html#autotoc_md43',1,'']]],
  ['and_20continuations_19',['Functions and Continuations',['../langref.html#autotoc_md45',1,'']]],
  ['and_20matching_20',['Products, Sequences, Unions, and Matching',['../langref.html#autotoc_md46',1,'']]],
  ['and_20naming_20metadata_21',['Preserving Debug and Naming Metadata',['../rewriting.html#autotoc_md99',1,'']]],
  ['and_20phases_22',['and Phases',['../affine.html#autotoc_md107',1,'Passes and Phases'],['../clos.html#autotoc_md125',1,'Passes and Phases'],['../matrix.html#autotoc_md233',1,'Passes and Phases'],['../regex.html#autotoc_md306',1,'Passes and Phases']]],
  ['and_20pipelines_23',['Passes, Phases, and Pipelines',['../opt.html#autotoc_md257',1,'']]],
  ['and_20scoped_20substitutions_24',['Mutable Rewrites and Scoped Substitutions',['../rewriting.html#autotoc_md98',1,'']]],
  ['and_20types_25',['Summary: Functions and Types',['../langref.html#autotoc_md49',1,'']]],
  ['and_20varrewriter_26',['Relationship Between Rewriter and VarRewriter',['../rewriting.html#autotoc_md103',1,'']]],
  ['annex_27',['Annex',['../langref.html#autotoc_md56',1,'']]],
  ['any_28',['%regex.any',['../regex.html#autotoc_md302',1,'']]],
  ['applications_29',['Applications',['../langref.html#autotoc_md52',1,'']]],
  ['arith_30',['%math.arith',['../math.html#autotoc_md200',1,'']]],
  ['arity_31',['Arity',['../dev.html#autotoc_md31',1,'']]],
  ['asynchronous_20memory_20operations_32',['Asynchronous Memory Operations',['../gpu.html#autotoc_md183',1,'']]],
  ['attribute_33',['Closure Attribute',['../clos.html#autotoc_md124',1,'']]],
  ['autodiff_20ad_34',['%autodiff.ad',['../autodiff.html#autotoc_md112',1,'']]],
  ['autodiff_20add_35',['%autodiff.add',['../autodiff.html#autotoc_md114',1,'']]],
  ['autodiff_20zero_36',['%autodiff.zero',['../autodiff.html#autotoc_md113',1,'']]],
  ['automatic_20differentiation_20plugin_37',['The automatic differentiation Plugin',['../autodiff.html',1,'']]],
  ['axioms_38',['Matching Axioms',['../dev.html#cast_axm',1,'']]]
];
