var searchData=
[
  ['party_20builds_0',['Standalone Third-Party Builds',['../plugins.html#autotoc_md84',1,'']]],
  ['party_20plugin_1',['Create a Third-Party Plugin',['../plugins.html#autotoc_md81',1,'']]],
  ['party_20plugin_20discovery_2',['Third-Party Plugin Discovery',['../plugins.html#autotoc_md82',1,'']]],
  ['pass_20compile_20phase_3',['%compile.Pass / %compile.Phase',['../compile.html#autotoc_md130',1,'']]],
  ['passes_4',['Passes',['../autodiff.html#autotoc_md118',1,'Passes'],['../clos.html#autotoc_md127',1,'Passes'],['../compile.html#autotoc_md137',1,'Passes'],['../matrix.html#autotoc_md235',1,'Passes'],['../mem.html#autotoc_md254',1,'Passes'],['../regex.html#autotoc_md318',1,'Passes']]],
  ['passes_5',['%compile.phases / %compile.passes',['../compile.html#autotoc_md134',1,'']]],
  ['passes_20and_20phases_6',['Passes and Phases',['../affine.html#autotoc_md108',1,'Passes and Phases'],['../clos.html#autotoc_md126',1,'Passes and Phases'],['../matrix.html#autotoc_md234',1,'Passes and Phases'],['../regex.html#autotoc_md317',1,'Passes and Phases']]],
  ['passes_20phases_20and_20pipelines_7',['Passes, Phases, and Pipelines',['../opt.html#autotoc_md258',1,'']]],
  ['pattern_8',['Recommended Design Pattern',['../phases.html#autotoc_md76',1,'']]],
  ['pattern_20terminals_9',['Pattern Terminals',['../langref.html#autotoc_md42',1,'']]],
  ['patterns_10',['Patterns',['../langref.html#ptrn',1,'']]],
  ['pe_11',['%core.pe',['../core.html#autotoc_md159',1,'']]],
  ['phase_12',['Phase',['../compile.html#autotoc_md130',1,'%compile.Pass / %compile.Phase'],['../phases.html#phases_phase',1,'Phase']]],
  ['phaseman_13',['PhaseMan',['../phases.html#phases_phase_man',1,'']]],
  ['phases_14',['Phases',['../affine.html#autotoc_md108',1,'Passes and Phases'],['../clos.html#autotoc_md126',1,'Passes and Phases'],['../matrix.html#autotoc_md234',1,'Passes and Phases'],['../regex.html#autotoc_md317',1,'Passes and Phases'],['../phases.html',1,'Phases'],['../clos.html#autotoc_md128',1,'Phases'],['../compile.html#autotoc_md135',1,'Phases'],['../direct.html#autotoc_md166',1,'Phases'],['../matrix.html#autotoc_md236',1,'Phases'],['../mem.html#autotoc_md252',1,'Phases']]],
  ['phases_20and_20pipelines_15',['Passes, Phases, and Pipelines',['../opt.html#autotoc_md258',1,'']]],
  ['phases_20compile_20passes_16',['%compile.phases / %compile.passes',['../compile.html#autotoc_md134',1,'']]],
  ['pipelines_17',['Pipelines',['../opt.html#autotoc_md258',1,'Passes, Phases, and Pipelines'],['../compile.html#autotoc_md138',1,'Pipelines'],['../mem.html#autotoc_md256',1,'Pipelines'],['../opt.html#autotoc_md259',1,'Pipelines']]],
  ['pipelines_20in_20m⁠im_18',['Compilation Pipelines in M⁠im',['../phases.html#autotoc_md78',1,'']]],
  ['plugin_19',['Plugin',['../plugins.html#autotoc_md80',1,'Create a New In-Tree Plugin'],['../plugins.html#autotoc_md81',1,'Create a Third-Party Plugin'],['../plugins.html#autotoc_md83',1,'Extract an Existing In-Tree Plugin'],['../affine.html',1,'The affine Plugin'],['../autodiff.html',1,'The automatic differentiation Plugin'],['../clos.html',1,'The clos Plugin'],['../compile.html',1,'The compile Plugin'],['../core.html',1,'The core Plugin'],['../demo.html',1,'The demo Plugin'],['../direct.html',1,'The direct style Plugin'],['../gpu.html',1,'The gpu Plugin'],['../math.html',1,'The math Plugin'],['../matrix.html',1,'The matrix Plugin'],['../mem.html',1,'The mem Plugin'],['../opt.html',1,'The opt Plugin'],['../option.html',1,'The option Plugin'],['../ord.html',1,'The ord Plugin'],['../refly.html',1,'The refly Plugin'],['../regex.html',1,'The regex Plugin'],['../tensor.html',1,'The tensor Plugin'],['../tuple.html',1,'The tuple Plugin'],['../vec.html',1,'The vec Plugin']]],
  ['plugin_20discovery_20',['Third-Party Plugin Discovery',['../plugins.html#autotoc_md82',1,'']]],
  ['plugins_21',['Plugins',['../index.html#autotoc_md91',1,'🧩 Plugins'],['../plugins.html',1,'Plugins']]],
  ['pointer_20types_22',['Pointer Types',['../gpu.html#autotoc_md171',1,'']]],
  ['pow_23',['%math.pow',['../math.html#autotoc_md204',1,'']]],
  ['pre_20analysis_24',['Optional Pre-Analysis',['../phases.html#autotoc_md65',1,'']]],
  ['precedence_25',['Precedence',['../langref.html#autotoc_md49',1,'']]],
  ['preserving_20metadata_26',['Preserving Metadata',['../rewriting.html#autotoc_md100',1,'']]],
  ['primary_20terminals_27',['Primary Terminals',['../langref.html#autotoc_md39',1,'']]],
  ['prod_5f2d_28',['prod_2d',['../tensor.html#autotoc_md322',1,'%tensor.prod_2d'],['../tensor.html#autotoc_md328',1,'%tensor.prod_2d']]],
  ['product_29',['product',['../matrix.html#autotoc_md231',1,'']]],
  ['products_20sequences_20unions_20and_20matching_30',['Products, Sequences, Unions, and Matching',['../langref.html#autotoc_md47',1,'']]],
  ['program_31',['Iterating over the Program',['../dev.html#autotoc_md37',1,'']]],
  ['projs_32',['Projs',['../dev.html#autotoc_md33',1,'']]],
  ['ptr_33',['%mem.Ptr',['../mem.html#autotoc_md239',1,'']]],
  ['publications_34',['📖 Publications',['../index.html#autotoc_md97',1,'']]]
];
