var searchData=
[
  ['tensor_20broadcast_5fin_5fdim_0',['%tensor.broadcast_in_dim',['../tensor.html#autotoc_md327',1,'']]],
  ['tensor_20dot_5fgeneral_1',['%tensor.dot_general',['../tensor.html#autotoc_md325',1,'']]],
  ['tensor_20element_5fwise_2',['%tensor.element_wise',['../tensor.html#autotoc_md321',1,'']]],
  ['tensor_20map_5freduce_3',['%tensor.map_reduce',['../tensor.html#autotoc_md329',1,'']]],
  ['tensor_20plugin_4',['The tensor Plugin',['../tensor.html',1,'']]],
  ['tensor_20prod_5f2d_5',['tensor prod_2d',['../tensor.html#autotoc_md320',1,'%tensor.prod_2d'],['../tensor.html#autotoc_md326',1,'%tensor.prod_2d']]],
  ['tensor_20reduce_6',['%tensor.reduce',['../tensor.html#autotoc_md328',1,'']]],
  ['tensor_20reshape_7',['%tensor.reshape',['../tensor.html#autotoc_md324',1,'']]],
  ['tensor_20slice_8',['%tensor.slice',['../tensor.html#autotoc_md323',1,'']]],
  ['tensor_20transpose_9',['%tensor.transpose',['../tensor.html#autotoc_md322',1,'']]],
  ['terminals_10',['Terminals',['../langref.html#autotoc_md42',1,'Pattern Terminals'],['../langref.html#autotoc_md39',1,'Primary Terminals'],['../langref.html#autotoc_md40',1,'Secondary Terminals'],['../langref.html#terminals',1,'Terminals']]],
  ['testing_11',['Testing',['../refly.html#autotoc_md292',1,'']]],
  ['tests_12',['Tests',['../coding.html#autotoc_md15',1,'lit Tests'],['../coding.html#tests',1,'Tests']]],
  ['the_20affine_20plugin_13',['The affine Plugin',['../affine.html',1,'']]],
  ['the_20analysis_20computes_14',['What the Analysis Computes',['../phases.html#autotoc_md71',1,'']]],
  ['the_20automatic_20differentiation_20plugin_15',['The automatic differentiation Plugin',['../autodiff.html',1,'']]],
  ['the_20clos_20plugin_16',['The clos Plugin',['../clos.html',1,'']]],
  ['the_20compile_20plugin_17',['The compile Plugin',['../compile.html',1,'']]],
  ['the_20core_20plugin_18',['The core Plugin',['../core.html',1,'']]],
  ['the_20demo_20plugin_19',['The demo Plugin',['../demo.html',1,'']]],
  ['the_20direct_20style_20plugin_20',['The direct style Plugin',['../direct.html',1,'']]],
  ['the_20gpu_20plugin_21',['The gpu Plugin',['../gpu.html',1,'']]],
  ['the_20math_20plugin_22',['The math Plugin',['../math.html',1,'']]],
  ['the_20matrix_20plugin_23',['The matrix Plugin',['../matrix.html',1,'']]],
  ['the_20mem_20plugin_24',['The mem Plugin',['../mem.html',1,'']]],
  ['the_20opt_20plugin_25',['The opt Plugin',['../opt.html',1,'']]],
  ['the_20option_20plugin_26',['The option Plugin',['../option.html',1,'']]],
  ['the_20ord_20plugin_27',['The ord Plugin',['../ord.html',1,'']]],
  ['the_20program_28',['Iterating over the Program',['../dev.html#autotoc_md37',1,'']]],
  ['the_20refly_20plugin_29',['The refly Plugin',['../refly.html',1,'']]],
  ['the_20regex_20plugin_30',['The regex Plugin',['../regex.html',1,'']]],
  ['the_20rewrite_20does_31',['What the Rewrite Does',['../phases.html#autotoc_md72',1,'']]],
  ['the_20right_20base_20class_32',['Choosing the Right Base Class',['../phases.html#autotoc_md74',1,'']]],
  ['the_20tensor_20plugin_33',['The tensor Plugin',['../tensor.html',1,'']]],
  ['the_20tuple_20plugin_34',['The tuple Plugin',['../tuple.html',1,'']]],
  ['the_20vec_20plugin_35',['The vec Plugin',['../vec.html',1,'']]],
  ['third_20party_20builds_36',['Standalone Third-Party Builds',['../plugins.html#autotoc_md82',1,'']]],
  ['third_20party_20plugin_37',['Create a Third-Party Plugin',['../plugins.html#autotoc_md79',1,'']]],
  ['third_20party_20plugin_20discovery_38',['Third-Party Plugin Discovery',['../plugins.html#autotoc_md80',1,'']]],
  ['this_20split_20is_20useful_39',['Why This Split Is Useful',['../phases.html#autotoc_md73',1,'']]],
  ['thresholded_20variants_40',['Thresholded Variants',['../dev.html#autotoc_md34',1,'']]],
  ['to_20immutables_41',['Downcast to Immutables',['../dev.html#autotoc_md24',1,'']]],
  ['to_20longjmp_42',['Operations related to longjmp',['../clos.html#autotoc_md122',1,'']]],
  ['to_20mutables_43',['Downcast to Mutables',['../dev.html#autotoc_md25',1,'']]],
  ['trait_44',['%core.trait',['../core.html#autotoc_md156',1,'']]],
  ['translations_45',['Registered translations',['../autodiff.html#autotoc_md117',1,'']]],
  ['transpose_46',['transpose',['../tensor.html#autotoc_md322',1,'%tensor.transpose'],['../matrix.html#autotoc_md230',1,'transpose']]],
  ['tree_20plugin_47',['Tree Plugin',['../plugins.html#autotoc_md78',1,'Create a New In-Tree Plugin'],['../plugins.html#autotoc_md81',1,'Extract an Existing In-Tree Plugin']]],
  ['tri_48',['%math.tri',['../math.html#autotoc_md201',1,'']]],
  ['triggering_20breakpoints_49',['Triggering Breakpoints',['../coding.html#autotoc_md16',1,'']]],
  ['tuple_20cat_50',['%tuple.cat',['../tuple.html#autotoc_md333',1,'']]],
  ['tuple_20contains_51',['%tuple.contains',['../tuple.html#autotoc_md334',1,'']]],
  ['tuple_20plugin_52',['The tuple Plugin',['../tuple.html',1,'']]],
  ['tuple_20typecat_53',['%tuple.typecat',['../tuple.html#autotoc_md332',1,'']]],
  ['tuple_20zip_54',['%tuple.zip',['../tuple.html#autotoc_md335',1,'']]],
  ['type_55',['%refly.type',['../refly.html#autotoc_md289',1,'']]],
  ['typecat_56',['%tuple.typecat',['../tuple.html#autotoc_md332',1,'']]],
  ['types_57',['Types',['../langref.html#autotoc_md54',1,'Function Types'],['../langref.html#autotoc_md44',1,'Kinds and Builtin Types'],['../gpu.html#autotoc_md168',1,'Memory Types'],['../gpu.html#autotoc_md169',1,'Pointer Types'],['../langref.html#autotoc_md50',1,'Summary: Functions and Types'],['../autodiff.html#autotoc_md109',1,'Types'],['../compile.html#autotoc_md127',1,'Types'],['../gpu.html#autotoc_md166',1,'Types'],['../math.html#autotoc_md196',1,'Types'],['../matrix.html#autotoc_md216',1,'Types'],['../mem.html#autotoc_md236',1,'Types'],['../option.html#autotoc_md259',1,'Types'],['../ord.html#autotoc_md269',1,'Types'],['../refly.html#autotoc_md284',1,'Types'],['../regex.html#autotoc_md300',1,'Types'],['../tensor.html#autotoc_md318',1,'Types']]],
  ['typical_20shape_58',['Typical Shape',['../phases.html#autotoc_md60',1,'Typical Shape'],['../phases.html#autotoc_md67',1,'Typical Shape'],['../phases.html#autotoc_md69',1,'Typical Shape']]],
  ['typical_20usage_59',['Typical Usage',['../phases.html#autotoc_md68',1,'Typical Usage'],['../rewriting.html#autotoc_md99',1,'Typical Usage'],['../rewriting.html#autotoc_md101',1,'Typical Usage']]]
];
