var searchData=
[
  ['party_20builds_0',['Standalone Third-Party Builds',['../plugins.html#autotoc_md81',1,'']]],
  ['party_20plugin_1',['Create a Standalone Third-Party Plugin',['../plugins.html#autotoc_md78',1,'']]],
  ['party_20plugin_20discovery_2',['Third-Party Plugin Discovery',['../plugins.html#autotoc_md80',1,'']]],
  ['pass_20compile_20phase_3',['%compile.Pass / %compile.Phase',['../compile.html#autotoc_md124',1,'']]],
  ['passes_4',['Passes',['../autodiff.html#autotoc_md112',1,'Passes'],['../clos.html#autotoc_md121',1,'Passes'],['../compile.html#autotoc_md131',1,'Passes'],['../matrix.html#autotoc_md229',1,'Passes'],['../mem.html#autotoc_md248',1,'Passes'],['../regex.html#autotoc_md302',1,'Passes']]],
  ['passes_5',['%compile.phases / %compile.passes',['../compile.html#autotoc_md128',1,'']]],
  ['passes_20and_20phases_6',['Passes and Phases',['../affine.html#autotoc_md102',1,'Passes and Phases'],['../clos.html#autotoc_md120',1,'Passes and Phases'],['../matrix.html#autotoc_md228',1,'Passes and Phases'],['../regex.html#autotoc_md301',1,'Passes and Phases']]],
  ['passes_20phases_20and_20pipelines_7',['Passes, Phases, and Pipelines',['../opt.html#autotoc_md252',1,'']]],
  ['pattern_8',['Recommended design pattern',['../phases.html#autotoc_md74',1,'']]],
  ['pattern_20terminals_9',['Pattern terminals',['../langref.html#autotoc_md39',1,'']]],
  ['patterns_10',['Patterns',['../langref.html#ptrn',1,'']]],
  ['pe_11',['%core.pe',['../core.html#autotoc_md153',1,'']]],
  ['phase_12',['Phase',['../compile.html#autotoc_md124',1,'%compile.Pass / %compile.Phase'],['../phases.html#phases_phase',1,'Phase']]],
  ['phaseman_13',['PhaseMan',['../phases.html#phases_phase_man',1,'']]],
  ['phases_14',['Phases',['../affine.html#autotoc_md102',1,'Passes and Phases'],['../clos.html#autotoc_md120',1,'Passes and Phases'],['../matrix.html#autotoc_md228',1,'Passes and Phases'],['../regex.html#autotoc_md301',1,'Passes and Phases'],['../phases.html',1,'Phases'],['../clos.html#autotoc_md122',1,'Phases'],['../compile.html#autotoc_md129',1,'Phases'],['../direct.html#autotoc_md160',1,'Phases'],['../matrix.html#autotoc_md230',1,'Phases'],['../mem.html#autotoc_md246',1,'Phases']]],
  ['phases_20and_20pipelines_15',['Passes, Phases, and Pipelines',['../opt.html#autotoc_md252',1,'']]],
  ['phases_20compile_20passes_16',['%compile.phases / %compile.passes',['../compile.html#autotoc_md128',1,'']]],
  ['pipelines_17',['Pipelines',['../opt.html#autotoc_md252',1,'Passes, Phases, and Pipelines'],['../compile.html#autotoc_md132',1,'Pipelines'],['../mem.html#autotoc_md250',1,'Pipelines'],['../opt.html#autotoc_md253',1,'Pipelines']]],
  ['plugin_18',['Plugin',['../plugins.html#autotoc_md77',1,'Create a New In-Tree Plugin'],['../plugins.html#autotoc_md78',1,'Create a Standalone Third-Party Plugin'],['../plugins.html#autotoc_md79',1,'Extract an Existing In-Tree Plugin'],['../affine.html',1,'The affine Plugin'],['../autodiff.html',1,'The automatic differentiation Plugin'],['../clos.html',1,'The clos Plugin'],['../compile.html',1,'The compile Plugin'],['../core.html',1,'The core Plugin'],['../demo.html',1,'The demo Plugin'],['../direct.html',1,'The direct style Plugin'],['../gpu.html',1,'The gpu Plugin'],['../math.html',1,'The math Plugin'],['../matrix.html',1,'The matrix Plugin'],['../mem.html',1,'The mem Plugin'],['../opt.html',1,'The opt Plugin'],['../ord.html',1,'The ord Plugin'],['../refly.html',1,'The refly Plugin'],['../regex.html',1,'The regex Plugin'],['../tensor.html',1,'The tensor Plugin'],['../tuple.html',1,'The tuple Plugin'],['../vec.html',1,'The vec Plugin']]],
  ['plugin_20discovery_19',['Third-Party Plugin Discovery',['../plugins.html#autotoc_md80',1,'']]],
  ['plugins_20',['Plugins',['../index.html#autotoc_md87',1,'🧩 Plugins'],['../plugins.html',1,'Plugins']]],
  ['pointer_20types_21',['Pointer Types',['../gpu.html#autotoc_md165',1,'']]],
  ['pow_22',['%math.pow',['../math.html#autotoc_md198',1,'']]],
  ['powered_20by_20rewriter_23',['Powered by Rewriter',['../phases.html#autotoc_md58',1,'']]],
  ['pre_20analysis_24',['Optional Pre-Analysis',['../phases.html#autotoc_md63',1,'']]],
  ['precedence_25',['Precedence',['../langref.html#autotoc_md46',1,'']]],
  ['primary_20terminals_26',['Primary terminals',['../langref.html#autotoc_md36',1,'']]],
  ['prod_5f2d_27',['prod_2d',['../tensor.html#autotoc_md306',1,'%tensor.prod_2d'],['../tensor.html#autotoc_md312',1,'%tensor.prod_2d']]],
  ['product_28',['product',['../matrix.html#autotoc_md225',1,'']]],
  ['products_20sequences_20unions_20and_20matching_29',['Products, sequences, unions, and matching',['../langref.html#autotoc_md44',1,'']]],
  ['program_30',['Iterating over the Program',['../dev.html#autotoc_md34',1,'']]],
  ['projs_31',['Projs',['../dev.html#autotoc_md30',1,'']]],
  ['ptr_32',['%mem.Ptr',['../mem.html#autotoc_md233',1,'']]],
  ['publications_33',['📖 Publications',['../index.html#autotoc_md93',1,'']]]
];
