var searchData=
[
  ['o_20side_20effects_0',['Operations w/o Side Effects',['../mem.html#autotoc_md245',1,'']]],
  ['of_20nodes_1',['🌊 Sea of Nodes',['../index.html#autotoc_md90',1,'']]],
  ['of_20sigmas_2',['Field names of sigmas',['../langref.html#autotoc_md57',1,'']]],
  ['operations_3',['Operations',['../gpu.html#autotoc_md180',1,'Asynchronous Memory Operations'],['../gpu.html#autotoc_md174',1,'Blocking Memory Operations'],['../core.html#autotoc_md139',1,'Integer Operations'],['../core.html#autotoc_md136',1,'Nat Operations'],['../math.html#autotoc_md196',1,'Numerical Operations'],['../affine.html#autotoc_md102',1,'Operations'],['../autodiff.html#autotoc_md108',1,'Operations'],['../demo.html#autotoc_md157',1,'Operations'],['../direct.html#autotoc_md160',1,'Operations'],['../gpu.html#autotoc_md169',1,'Operations'],['../matrix.html#autotoc_md216',1,'Operations'],['../tensor.html#autotoc_md307',1,'Operations'],['../tuple.html#autotoc_md319',1,'Operations'],['../core.html#autotoc_md153',1,'Other Operations'],['../math.html#autotoc_md207',1,'Other Operations']]],
  ['operations_4',['High-level matrix operations',['../matrix.html#autotoc_md225',1,'']]],
  ['operations_20related_20to_20longjmp_5',['Operations related to longjmp',['../clos.html#autotoc_md120',1,'']]],
  ['operations_20w_20o_20side_20effects_6',['Operations w/o Side Effects',['../mem.html#autotoc_md245',1,'']]],
  ['operations_20w_20side_20effects_7',['Operations w/ Side Effects',['../mem.html#autotoc_md236',1,'']]],
  ['opt_20plugin_8',['The opt Plugin',['../opt.html',1,'']]],
  ['optional_9',['📦 Install (optional)',['../index.html#autotoc_md87',1,'']]],
  ['optional_20pre_20analysis_10',['Optional Pre-Analysis',['../phases.html#autotoc_md65',1,'']]],
  ['ord_20contains_11',['%ord.contains',['../ord.html#autotoc_md268',1,'']]],
  ['ord_20create_12',['%ord.create',['../ord.html#autotoc_md262',1,'']]],
  ['ord_20get_13',['ord get',['../ord.html#autotoc_md267',1,'%ord.get'],['../todo.html#_todo000001',1,'%ord.get']]],
  ['ord_20init_14',['%ord.init',['../ord.html#autotoc_md261',1,'']]],
  ['ord_20insert_15',['%ord.insert',['../ord.html#autotoc_md270',1,'']]],
  ['ord_20is_5fempty_16',['%ord.is_empty',['../ord.html#autotoc_md265',1,'']]],
  ['ord_20key_17',['%ord.Key',['../ord.html#autotoc_md258',1,'']]],
  ['ord_20map_18',['%ord.Set / %ord.Map',['../ord.html#autotoc_md259',1,'']]],
  ['ord_20plugin_19',['The ord Plugin',['../ord.html',1,'']]],
  ['ord_20set_20ord_20map_20',['%ord.Set / %ord.Map',['../ord.html#autotoc_md259',1,'']]],
  ['ord_20size_21',['%ord.size',['../ord.html#autotoc_md264',1,'']]],
  ['other_20operations_22',['Other Operations',['../core.html#autotoc_md153',1,'Other Operations'],['../math.html#autotoc_md207',1,'Other Operations']]],
  ['over_20the_20program_23',['Iterating over the Program',['../dev.html#autotoc_md33',1,'']]],
  ['overview_24',['Overview',['../phases.html#autotoc_md58',1,'']]]
];
