var searchData=
[
  ['m_0',['%mem.M',['../mem.html#memM',1,'']]],
  ['malloc_1',['%mem.malloc',['../mem.html#autotoc_md238',1,'']]],
  ['manipulate_2',['Manipulate',['../refly.html#autotoc_md279',1,'']]],
  ['map_3',['%ord.Set / %ord.Map',['../ord.html#autotoc_md255',1,'']]],
  ['map_5freduce_4',['%tensor.map_reduce',['../tensor.html#autotoc_md313',1,'']]],
  ['mat_5',['%matrix.Mat',['../matrix.html#autotoc_md211',1,'']]],
  ['matching_20axioms_6',['Matching Axioms',['../dev.html#cast_axm',1,'']]],
  ['matching_20ir_7',['Matching IR',['../dev.html#autotoc_md19',1,'']]],
  ['matching_20literals_8',['Matching Literals',['../dev.html#cast_lit',1,'']]],
  ['math_20abs_9',['%math.abs',['../math.html#autotoc_md201',1,'']]],
  ['math_20arith_10',['%math.arith',['../math.html#autotoc_md193',1,'']]],
  ['math_20cmp_11',['%math.cmp',['../math.html#autotoc_md204',1,'']]],
  ['math_20conv_12',['%math.conv',['../math.html#autotoc_md205',1,'']]],
  ['math_20er_13',['%math.er',['../math.html#autotoc_md199',1,'']]],
  ['math_20exp_14',['%math.exp',['../math.html#autotoc_md198',1,'']]],
  ['math_20extrema_15',['%math.extrema',['../math.html#autotoc_md194',1,'']]],
  ['math_20f_16',['%math.F',['../math.html#autotoc_md191',1,'']]],
  ['math_20gamma_17',['%math.gamma',['../math.html#autotoc_md200',1,'']]],
  ['math_20plugin_18',['The math Plugin',['../math.html',1,'']]],
  ['math_20pow_19',['%math.pow',['../math.html#autotoc_md196',1,'']]],
  ['math_20round_20',['%math.round',['../math.html#autotoc_md202',1,'']]],
  ['math_20rrt_21',['%math.rrt',['../math.html#autotoc_md208',1,'']]],
  ['math_20rt_22',['%math.rt',['../math.html#autotoc_md197',1,'']]],
  ['math_20sgn_23',['%math.sgn',['../math.html#autotoc_md207',1,'']]],
  ['math_20slf_24',['%math.slf',['../math.html#autotoc_md206',1,'']]],
  ['math_20tri_25',['%math.tri',['../math.html#autotoc_md195',1,'']]],
  ['matrix_20const_26',['%matrix.const',['../matrix.html#autotoc_md215',1,'']]],
  ['matrix_20init_27',['%matrix.init',['../matrix.html#autotoc_md220',1,'']]],
  ['matrix_20insert_28',['%matrix.insert',['../matrix.html#autotoc_md218',1,'']]],
  ['matrix_20mat_29',['%matrix.Mat',['../matrix.html#autotoc_md211',1,'']]],
  ['matrix_20operations_30',['High-level matrix operations',['../matrix.html#autotoc_md221',1,'']]],
  ['matrix_20plugin_31',['The matrix Plugin',['../matrix.html',1,'']]],
  ['matrix_20read_32',['%matrix.read',['../matrix.html#autotoc_md216',1,'']]],
  ['matrix_20shape_33',['%matrix.shape',['../matrix.html#autotoc_md213',1,'']]],
  ['mem_20alloc_34',['%mem.alloc',['../mem.html#autotoc_md236',1,'']]],
  ['mem_20free_35',['%mem.free',['../mem.html#autotoc_md239',1,'']]],
  ['mem_20lea_36',['%mem.lea',['../mem.html#autotoc_md242',1,'']]],
  ['mem_20load_37',['%mem.load',['../mem.html#autotoc_md233',1,'']]],
  ['mem_20m_38',['%mem.M',['../mem.html#memM',1,'']]],
  ['mem_20malloc_39',['%mem.malloc',['../mem.html#autotoc_md238',1,'']]],
  ['mem_20mslot_40',['%mem.mslot',['../mem.html#autotoc_md240',1,'']]],
  ['mem_20plugin_41',['The mem Plugin',['../mem.html',1,'']]],
  ['mem_20ptr_42',['%mem.Ptr',['../mem.html#autotoc_md231',1,'']]],
  ['mem_20remem_43',['%mem.remem',['../mem.html#autotoc_md235',1,'']]],
  ['mem_20reshape_44',['mem.reshape',['../mem.html#autotoc_md247',1,'']]],
  ['mem_20slot_45',['%mem.slot',['../mem.html#autotoc_md237',1,'']]],
  ['mem_20store_46',['%mem.store',['../mem.html#autotoc_md234',1,'']]],
  ['memory_20operations_47',['Memory Operations',['../gpu.html#autotoc_md176',1,'Asynchronous Memory Operations'],['../gpu.html#autotoc_md170',1,'Blocking Memory Operations']]],
  ['memory_20types_48',['Memory Types',['../gpu.html#autotoc_md162',1,'']]],
  ['meta_49',['Meta',['../regex.html#autotoc_md286',1,'']]],
  ['mim_50',['🐉 Naming: MimIR vs Mim',['../index.html#autotoc_md88',1,'']]],
  ['mim_20language_20reference_51',['Mim Language Reference',['../langref.html',1,'']]],
  ['mimir_52',['MimIR',['../index.html#autotoc_md81',1,'💡 Why MimIR?'],['../index.html',1,'MimIR']]],
  ['mimir_20vs_20mim_53',['🐉 Naming: MimIR vs Mim',['../index.html#autotoc_md88',1,'']]],
  ['minimal_20examples_54',['Minimal examples',['../phases.html#autotoc_md78',1,'']]],
  ['mode_55',['Mode',['../core.html#autotoc_md136',1,'']]],
  ['model_56',['Execution Model',['../phases.html#autotoc_md63',1,'']]],
  ['modifiers_57',['Modifiers',['../ord.html#autotoc_md265',1,'Modifiers'],['../vec.html#autotoc_md329',1,'Modifiers']]],
  ['module_58',['Module',['../langref.html#module',1,'']]],
  ['mslot_59',['%mem.mslot',['../mem.html#autotoc_md240',1,'']]],
  ['mul_60',['%core.wrap.mul',['../autodiff.html#autotoc_md114',1,'']]],
  ['mutables_61',['Mutables',['../dev.html#autotoc_md22',1,'Downcast to Mutables'],['../dev.html#mut',1,'Immutables vs. Mutables']]]
];
