var searchData=
[
  ['party_20builds_0',['Standalone Third-Party Builds',['../plugins.html#autotoc_md83',1,'']]],
  ['party_20plugin_1',['Create a Standalone Third-Party Plugin',['../plugins.html#autotoc_md80',1,'']]],
  ['party_20plugin_20discovery_2',['Third-Party Plugin Discovery',['../plugins.html#autotoc_md82',1,'']]],
  ['pass_20compile_20phase_3',['%compile.Pass / %compile.Phase',['../compile.html#autotoc_md126',1,'']]],
  ['passes_4',['Passes',['../autodiff.html#autotoc_md114',1,'Passes'],['../clos.html#autotoc_md123',1,'Passes'],['../compile.html#autotoc_md133',1,'Passes'],['../matrix.html#autotoc_md231',1,'Passes'],['../mem.html#autotoc_md250',1,'Passes'],['../regex.html#autotoc_md304',1,'Passes']]],
  ['passes_5',['%compile.phases / %compile.passes',['../compile.html#autotoc_md130',1,'']]],
  ['passes_20and_20phases_6',['Passes and Phases',['../affine.html#autotoc_md104',1,'Passes and Phases'],['../clos.html#autotoc_md122',1,'Passes and Phases'],['../matrix.html#autotoc_md230',1,'Passes and Phases'],['../regex.html#autotoc_md303',1,'Passes and Phases']]],
  ['passes_20phases_20and_20pipelines_7',['Passes, Phases, and Pipelines',['../opt.html#autotoc_md254',1,'']]],
  ['pattern_8',['Recommended design pattern',['../phases.html#autotoc_md76',1,'']]],
  ['pattern_20terminals_9',['Pattern terminals',['../langref.html#autotoc_md38',1,'']]],
  ['patterns_10',['Patterns',['../langref.html#ptrn',1,'']]],
  ['patterns_11',['Alias patterns',['../langref.html#autotoc_md42',1,'']]],
  ['pe_12',['%core.pe',['../core.html#autotoc_md155',1,'']]],
  ['phase_13',['Phase',['../compile.html#autotoc_md126',1,'%compile.Pass / %compile.Phase'],['../phases.html#phases_phase',1,'Phase']]],
  ['phaseman_14',['PhaseMan',['../phases.html#phases_phase_man',1,'']]],
  ['phases_15',['Phases',['../affine.html#autotoc_md104',1,'Passes and Phases'],['../clos.html#autotoc_md122',1,'Passes and Phases'],['../matrix.html#autotoc_md230',1,'Passes and Phases'],['../regex.html#autotoc_md303',1,'Passes and Phases'],['../phases.html',1,'Phases'],['../clos.html#autotoc_md124',1,'Phases'],['../compile.html#autotoc_md131',1,'Phases'],['../direct.html#autotoc_md162',1,'Phases'],['../matrix.html#autotoc_md232',1,'Phases'],['../mem.html#autotoc_md248',1,'Phases']]],
  ['phases_20and_20pipelines_16',['Passes, Phases, and Pipelines',['../opt.html#autotoc_md254',1,'']]],
  ['phases_20compile_20passes_17',['%compile.phases / %compile.passes',['../compile.html#autotoc_md130',1,'']]],
  ['pipelines_18',['Pipelines',['../opt.html#autotoc_md254',1,'Passes, Phases, and Pipelines'],['../compile.html#autotoc_md134',1,'Pipelines'],['../mem.html#autotoc_md252',1,'Pipelines'],['../opt.html#autotoc_md255',1,'Pipelines']]],
  ['plugin_19',['Plugin',['../plugins.html#autotoc_md79',1,'Create a New In-Tree Plugin'],['../plugins.html#autotoc_md80',1,'Create a Standalone Third-Party Plugin'],['../plugins.html#autotoc_md81',1,'Extract an Existing In-Tree Plugin'],['../affine.html',1,'The affine Plugin'],['../autodiff.html',1,'The automatic differentiation Plugin'],['../clos.html',1,'The clos Plugin'],['../compile.html',1,'The compile Plugin'],['../core.html',1,'The core Plugin'],['../demo.html',1,'The demo Plugin'],['../direct.html',1,'The direct style Plugin'],['../gpu.html',1,'The gpu Plugin'],['../math.html',1,'The math Plugin'],['../matrix.html',1,'The matrix Plugin'],['../mem.html',1,'The mem Plugin'],['../opt.html',1,'The opt Plugin'],['../ord.html',1,'The ord Plugin'],['../refly.html',1,'The refly Plugin'],['../regex.html',1,'The regex Plugin'],['../tensor.html',1,'The tensor Plugin'],['../tuple.html',1,'The tuple Plugin'],['../vec.html',1,'The vec Plugin']]],
  ['plugin_20discovery_20',['Third-Party Plugin Discovery',['../plugins.html#autotoc_md82',1,'']]],
  ['plugins_21',['Plugins',['../index.html#autotoc_md89',1,'🧩 Plugins'],['../plugins.html',1,'Plugins']]],
  ['pointer_20types_22',['Pointer Types',['../gpu.html#autotoc_md167',1,'']]],
  ['pow_23',['%math.pow',['../math.html#autotoc_md200',1,'']]],
  ['powered_20by_20rewriter_24',['Powered by Rewriter',['../phases.html#autotoc_md60',1,'']]],
  ['pre_20analysis_25',['Optional Pre-Analysis',['../phases.html#autotoc_md65',1,'']]],
  ['precedence_26',['Precedence',['../langref.html#autotoc_md48',1,'']]],
  ['primary_20terminals_27',['Primary terminals',['../langref.html#autotoc_md35',1,'']]],
  ['prod_5f2d_28',['prod_2d',['../tensor.html#autotoc_md308',1,'%tensor.prod_2d'],['../tensor.html#autotoc_md314',1,'%tensor.prod_2d']]],
  ['product_29',['product',['../matrix.html#autotoc_md227',1,'']]],
  ['products_30',['Tuples, arrays, and products',['../langref.html#autotoc_md47',1,'']]],
  ['program_31',['Iterating over the Program',['../dev.html#autotoc_md33',1,'']]],
  ['projs_32',['Projs',['../dev.html#autotoc_md29',1,'']]],
  ['ptr_33',['%mem.Ptr',['../mem.html#autotoc_md235',1,'']]],
  ['publications_34',['📖 Publications',['../index.html#autotoc_md95',1,'']]]
];
