var searchData=
[
  ['range_0',['%regex.range',['../regex.html#autotoc_md306',1,'']]],
  ['re_1',['RE',['../regex.html#autotoc_md301',1,'']]],
  ['read_2',['%matrix.read',['../matrix.html#autotoc_md222',1,'']]],
  ['recommended_20design_20pattern_3',['Recommended Design Pattern',['../phases.html#autotoc_md74',1,'']]],
  ['reduce_4',['%tensor.reduce',['../tensor.html#autotoc_md328',1,'']]],
  ['reference_5',['Reference',['../cli.html',1,'Command-Line Reference'],['../langref.html',1,'Mim Language Reference']]],
  ['refine_6',['%refly.refine',['../refly.html#autotoc_md296',1,'']]],
  ['reflect_7',['Reify / Reflect',['../refly.html#autotoc_md285',1,'']]],
  ['reflect_8',['%refly.reflect',['../refly.html#autotoc_md287',1,'']]],
  ['refly_20check_9',['%refly.check',['../refly.html#autotoc_md294',1,'']]],
  ['refly_20dbg_10',['%refly.dbg',['../refly.html#autotoc_md291',1,'']]],
  ['refly_20equiv_11',['%refly.equiv',['../refly.html#autotoc_md293',1,'']]],
  ['refly_20gid_12',['%refly.gid',['../refly.html#autotoc_md290',1,'']]],
  ['refly_20plugin_13',['The refly Plugin',['../refly.html',1,'']]],
  ['refly_20refine_14',['%refly.refine',['../refly.html#autotoc_md296',1,'']]],
  ['refly_20reflect_15',['%refly.reflect',['../refly.html#autotoc_md287',1,'']]],
  ['refly_20reify_16',['%refly.reify',['../refly.html#autotoc_md286',1,'']]],
  ['refly_20type_17',['%refly.type',['../refly.html#autotoc_md289',1,'']]],
  ['regex_20any_18',['%regex.any',['../regex.html#autotoc_md311',1,'']]],
  ['regex_20cls_19',['%regex.cls.*',['../regex.html#autotoc_md310',1,'']]],
  ['regex_20conj_20',['%regex.conj',['../regex.html#autotoc_md303',1,'']]],
  ['regex_20disj_21',['%regex.disj',['../regex.html#autotoc_md304',1,'']]],
  ['regex_20empty_22',['%regex.empty',['../regex.html#autotoc_md312',1,'']]],
  ['regex_20lit_23',['%regex.lit',['../regex.html#autotoc_md307',1,'']]],
  ['regex_20neg_5flookahead_24',['%regex.neg_lookahead',['../regex.html#autotoc_md309',1,'']]],
  ['regex_20not_5f_25',['%regex.not_',['../regex.html#autotoc_md308',1,'']]],
  ['regex_20plugin_26',['The regex Plugin',['../regex.html',1,'']]],
  ['regex_20quant_27',['%regex.quant.*',['../regex.html#autotoc_md314',1,'']]],
  ['regex_20range_28',['%regex.range',['../regex.html#autotoc_md306',1,'']]],
  ['registered_20translations_29',['Registered translations',['../autodiff.html#autotoc_md117',1,'']]],
  ['reify_30',['%refly.reify',['../refly.html#autotoc_md286',1,'']]],
  ['reify_20reflect_31',['Reify / Reflect',['../refly.html#autotoc_md285',1,'']]],
  ['related_20to_20longjmp_32',['Operations related to longjmp',['../clos.html#autotoc_md122',1,'']]],
  ['remem_33',['%mem.remem',['../mem.html#autotoc_md241',1,'']]],
  ['repls_34',['Repls',['../autodiff.html#autotoc_md115',1,'Repls'],['../compile.html#autotoc_md134',1,'Repls'],['../gpu.html#autotoc_md195',1,'Repls'],['../mem.html#autotoc_md251',1,'Repls'],['../refly.html#autotoc_md298',1,'Repls']]],
  ['reset_20between_20iterations_35',['Reset Between Iterations',['../phases.html#autotoc_md61',1,'']]],
  ['reshape_36',['reshape',['../tensor.html#autotoc_md324',1,'%tensor.reshape'],['../mem.html#autotoc_md253',1,'mem.reshape']]],
  ['rewriter_37',['Rewriter',['../rewriting.html#rewriter',1,'']]],
  ['rewriter_20vs_20varrewriter_38',['Rewriter vs. VarRewriter',['../rewriting.html#autotoc_md102',1,'']]],
  ['rewrites_39',['Mutable Rewrites',['../rewriting.html#autotoc_md97',1,'']]],
  ['rewriting_40',['Rewriting',['../rewriting.html',1,'']]],
  ['right_20base_20class_41',['Choosing the Right Base Class',['../phases.html#autotoc_md73',1,'']]],
  ['round_42',['%math.round',['../math.html#autotoc_md208',1,'']]],
  ['rrt_43',['%math.rrt',['../math.html#autotoc_md214',1,'']]],
  ['rt_44',['%math.rt',['../math.html#autotoc_md203',1,'']]],
  ['rwphase_45',['RWPhase',['../phases.html#phases_rwphase',1,'']]]
];
