var searchData=
[
  ['scan_0',['%vec.scan',['../vec.html#autotoc_md343',1,'']]],
  ['scanning_1',['Scanning',['../vec.html#autotoc_md342',1,'']]],
  ['sccp_2',['Example: SCCP',['../phases.html#autotoc_md71',1,'']]],
  ['scoped_20substitution_3',['Scoped Substitution',['../rewriting.html#autotoc_md102',1,'']]],
  ['scoping_4',['Scoping',['../langref.html#autotoc_md55',1,'Scoping'],['../rewriting.html#autotoc_md98',1,'Scoping']]],
  ['sea_20of_20nodes_5',['🌊 Sea of Nodes',['../index.html#autotoc_md92',1,'']]],
  ['secondary_20terminals_6',['Secondary Terminals',['../langref.html#autotoc_md40',1,'']]],
  ['select_7',['%core.select',['../core.html#autotoc_md160',1,'']]],
  ['sequences_20unions_20and_20matching_8',['Products, Sequences, Unions, and Matching',['../langref.html#autotoc_md47',1,'']]],
  ['set_20ord_20map_9',['%ord.Set / %ord.Map',['../ord.html#autotoc_md273',1,'']]],
  ['sgn_10',['%math.sgn',['../math.html#autotoc_md215',1,'']]],
  ['shape_11',['Shape',['../dev.html#autotoc_md35',1,'Shape'],['../phases.html#autotoc_md60',1,'Typical Shape'],['../phases.html#autotoc_md68',1,'Typical Shape'],['../phases.html#autotoc_md69',1,'Typical Shape'],['../phases.html#autotoc_md70',1,'Typical Shape']]],
  ['shape_12',['%matrix.shape',['../matrix.html#autotoc_md221',1,'']]],
  ['shr_13',['%core.shr',['../core.html#autotoc_md148',1,'']]],
  ['side_20effects_14',['Side Effects',['../mem.html#autotoc_md240',1,'Operations w/ Side Effects'],['../mem.html#autotoc_md249',1,'Operations w/o Side Effects']]],
  ['sigmas_15',['Field Names of Sigmas',['../langref.html#autotoc_md58',1,'']]],
  ['size_16',['%ord.size',['../ord.html#autotoc_md278',1,'']]],
  ['slf_17',['%math.slf',['../math.html#autotoc_md214',1,'']]],
  ['slice_18',['%tensor.slice',['../tensor.html#autotoc_md325',1,'']]],
  ['slot_19',['%mem.slot',['../mem.html#autotoc_md245',1,'']]],
  ['some_20',['%option.some',['../option.html#autotoc_md264',1,'']]],
  ['spaces_21',['Address Spaces',['../gpu.html#autotoc_md169',1,'']]],
  ['ssa_20without_20dominance_22',['🪾 SSA without Dominance',['../index.html#autotoc_md93',1,'']]],
  ['stages_23',['Stages',['../autodiff.html#autotoc_md116',1,'Stages'],['../gpu.html#autotoc_md196',1,'Stages'],['../mem.html#autotoc_md251',1,'Stages'],['../refly.html#autotoc_md299',1,'Stages']]],
  ['standalone_20third_20party_20builds_24',['Standalone Third-Party Builds',['../plugins.html#autotoc_md84',1,'']]],
  ['start_25',['Start',['../index.html#autotoc_md88',1,'🚀 Quick Start'],['../coding.html#building',1,'Contributor Quick Start']]],
  ['store_26',['%mem.store',['../mem.html#autotoc_md242',1,'']]],
  ['stream_5fdeinit_27',['%gpu.stream_deinit',['../gpu.html#autotoc_md176',1,'']]],
  ['stream_5finit_28',['%gpu.stream_init',['../gpu.html#autotoc_md175',1,'']]],
  ['stream_5fsync_29',['%gpu.stream_sync',['../gpu.html#autotoc_md177',1,'']]],
  ['streams_30',['Streams',['../gpu.html#autotoc_md172',1,'Streams'],['../gpu.html#autotoc_md174',1,'Streams']]],
  ['structure_31',['Lexical Structure',['../langref.html#lex',1,'']]],
  ['style_32',['Style',['../coding.html#autotoc_md5',1,'C++ Style'],['../coding.html#autotoc_md8',1,'CMake Style'],['../coding.html#autotoc_md4',1,'Coding Style'],['../coding.html#autotoc_md6',1,'Doxygen Style'],['../coding.html#autotoc_md10',1,'M⁠im Coding Style'],['../coding.html#autotoc_md9',1,'Markdown Style']]],
  ['style_20plugin_33',['The direct style Plugin',['../direct.html',1,'']]],
  ['substitution_34',['Scoped Substitution',['../rewriting.html#autotoc_md102',1,'']]],
  ['subtags_35',['Subtags',['../dev.html#autotoc_md29',1,'With Subtags'],['../dev.html#autotoc_md28',1,'Without Subtags']]],
  ['sum_36',['sum',['../matrix.html#autotoc_md233',1,'']]],
  ['summary_37',['Summary',['../dev.html#autotoc_md26',1,'Summary'],['../dev.html#autotoc_md30',1,'Summary'],['../dev.html#autotoc_md36',1,'Summary'],['../phases.html#autotoc_md79',1,'Summary']]],
  ['summary_3a_20functions_20and_20types_38',['Summary: Functions and Types',['../langref.html#autotoc_md50',1,'']]],
  ['sync_5fwork_5fitems_39',['%gpu.sync_work_items',['../gpu.html#autotoc_md194',1,'']]],
  ['synced_5fscope_40',['%gpu.synced_scope',['../gpu.html#autotoc_md195',1,'']]],
  ['synchronization_41',['Work-Item Synchronization',['../gpu.html#autotoc_md193',1,'']]],
  ['syntax_20highlighting_42',['Syntax Highlighting',['../coding.html#autotoc_md11',1,'']]]
];
