var searchData=
[
  ['abs_0',['abs',['../core.html#autotoc_md145',1,'%core.abs'],['../math.html#autotoc_md201',1,'%math.abs']]],
  ['ad_1',['%autodiff.ad',['../autodiff.html#autotoc_md105',1,'']]],
  ['add_2',['add',['../autodiff.html#autotoc_md107',1,'%autodiff.add'],['../autodiff.html#autotoc_md113',1,'%core.wrap.add']]],
  ['add_5fmim_5fplugin_3',['&lt;span class=&quot;tt&quot;&gt;add_mim_plugin&lt;/span&gt;',['../coding.html#autotoc_md17',1,'']]],
  ['address_20spaces_4',['Address Spaces',['../gpu.html#autotoc_md161',1,'']]],
  ['affine_20for_5',['%affine.For',['../affine.html#autotoc_md99',1,'']]],
  ['affine_20lower_5ffor_5fpass_6',['%affine.lower_for_pass',['../affine.html#autotoc_md101',1,'']]],
  ['affine_20plugin_7',['The affine Plugin',['../affine.html',1,'']]],
  ['alias_20patterns_8',['Alias patterns',['../langref.html#autotoc_md43',1,'']]],
  ['alloc_9',['alloc',['../gpu.html#autotoc_md171',1,'%gpu.alloc'],['../mem.html#autotoc_md236',1,'%mem.alloc']]],
  ['alloc_5fasync_10',['%gpu.alloc_async',['../gpu.html#autotoc_md177',1,'']]],
  ['alloc_5fcopy_11',['%gpu.alloc_copy',['../gpu.html#autotoc_md175',1,'']]],
  ['alloc_5fcopy_5fasync_12',['%gpu.alloc_copy_async',['../gpu.html#autotoc_md181',1,'']]],
  ['analysis_13',['Analysis',['../phases.html#phases_analysis',1,'Analysis'],['../phases.html#autotoc_md66',1,'Optional Pre-Analysis']]],
  ['analysis_20computes_14',['What the analysis computes',['../phases.html#autotoc_md73',1,'']]],
  ['and_20basic_20forms_15',['Literals and basic forms',['../langref.html#autotoc_md46',1,'']]],
  ['and_20builtin_20types_16',['Kinds and builtin types',['../langref.html#autotoc_md45',1,'']]],
  ['and_20phases_17',['and Phases',['../affine.html#autotoc_md100',1,'Passes and Phases'],['../clos.html#autotoc_md118',1,'Passes and Phases'],['../matrix.html#autotoc_md226',1,'Passes and Phases'],['../regex.html#autotoc_md299',1,'Passes and Phases']]],
  ['and_20pipelines_18',['Passes, Phases, and Pipelines',['../opt.html#autotoc_md250',1,'']]],
  ['and_20products_19',['Tuples, arrays, and products',['../langref.html#autotoc_md48',1,'']]],
  ['and_20types_20',['Summary: Functions and types',['../langref.html#autotoc_md50',1,'']]],
  ['annex_21',['Annex',['../langref.html#autotoc_md57',1,'']]],
  ['any_22',['%regex.any',['../regex.html#autotoc_md295',1,'']]],
  ['applications_23',['Applications',['../langref.html#autotoc_md53',1,'']]],
  ['arith_24',['%math.arith',['../math.html#autotoc_md193',1,'']]],
  ['arity_25',['Arity',['../dev.html#autotoc_md29',1,'']]],
  ['arrays_20and_20products_26',['Tuples, arrays, and products',['../langref.html#autotoc_md48',1,'']]],
  ['asynchronous_20memory_20operations_27',['Asynchronous Memory Operations',['../gpu.html#autotoc_md176',1,'']]],
  ['attribute_28',['Closure Attribute',['../clos.html#autotoc_md117',1,'']]],
  ['autodiff_20ad_29',['%autodiff.ad',['../autodiff.html#autotoc_md105',1,'']]],
  ['autodiff_20add_30',['%autodiff.add',['../autodiff.html#autotoc_md107',1,'']]],
  ['autodiff_20zero_31',['%autodiff.zero',['../autodiff.html#autotoc_md106',1,'']]],
  ['automatic_20differentiation_20plugin_32',['The automatic differentiation Plugin',['../autodiff.html',1,'']]],
  ['axioms_33',['Matching Axioms',['../dev.html#cast_axm',1,'']]]
];
