var searchData=
[
  ['tensor_20broadcast_5fin_5fdim_0',['%tensor.broadcast_in_dim',['../tensor.html#autotoc_md311',1,'']]],
  ['tensor_20dot_5fgeneral_1',['%tensor.dot_general',['../tensor.html#autotoc_md309',1,'']]],
  ['tensor_20element_5fwise_2',['%tensor.element_wise',['../tensor.html#autotoc_md305',1,'']]],
  ['tensor_20map_5freduce_3',['%tensor.map_reduce',['../tensor.html#autotoc_md313',1,'']]],
  ['tensor_20plugin_4',['The tensor Plugin',['../tensor.html',1,'']]],
  ['tensor_20prod_5f2d_5',['tensor prod_2d',['../tensor.html#autotoc_md304',1,'%tensor.prod_2d'],['../tensor.html#autotoc_md310',1,'%tensor.prod_2d']]],
  ['tensor_20reduce_6',['%tensor.reduce',['../tensor.html#autotoc_md312',1,'']]],
  ['tensor_20reshape_7',['%tensor.reshape',['../tensor.html#autotoc_md308',1,'']]],
  ['tensor_20slice_8',['%tensor.slice',['../tensor.html#autotoc_md307',1,'']]],
  ['tensor_20transpose_9',['%tensor.transpose',['../tensor.html#autotoc_md306',1,'']]],
  ['terminals_10',['Terminals',['../langref.html#terminals',1,'']]],
  ['terminals_11',['terminals',['../langref.html#autotoc_md39',1,'Pattern terminals'],['../langref.html#autotoc_md36',1,'Primary terminals'],['../langref.html#autotoc_md37',1,'Secondary terminals']]],
  ['testing_12',['Testing',['../refly.html#autotoc_md276',1,'']]],
  ['tests_13',['Tests',['../coding.html#autotoc_md11',1,'&lt;span class=&quot;tt&quot;&gt;lit&lt;/span&gt; Tests'],['../coding.html#tests',1,'Tests']]],
  ['the_20affine_20plugin_14',['The affine Plugin',['../affine.html',1,'']]],
  ['the_20analysis_20computes_15',['What the analysis computes',['../phases.html#autotoc_md73',1,'']]],
  ['the_20automatic_20differentiation_20plugin_16',['The automatic differentiation Plugin',['../autodiff.html',1,'']]],
  ['the_20clos_20plugin_17',['The clos Plugin',['../clos.html',1,'']]],
  ['the_20command_20line_18',['Triggering Breakpoints from the Command Line',['../coding.html#autotoc_md12',1,'']]],
  ['the_20compile_20plugin_19',['The compile Plugin',['../compile.html',1,'']]],
  ['the_20core_20plugin_20',['The core Plugin',['../core.html',1,'']]],
  ['the_20demo_20plugin_21',['The demo Plugin',['../demo.html',1,'']]],
  ['the_20direct_20style_20plugin_22',['The direct style Plugin',['../direct.html',1,'']]],
  ['the_20gpu_20plugin_23',['The gpu Plugin',['../gpu.html',1,'']]],
  ['the_20math_20plugin_24',['The math Plugin',['../math.html',1,'']]],
  ['the_20matrix_20plugin_25',['The matrix Plugin',['../matrix.html',1,'']]],
  ['the_20mem_20plugin_26',['The mem Plugin',['../mem.html',1,'']]],
  ['the_20opt_20plugin_27',['The opt Plugin',['../opt.html',1,'']]],
  ['the_20ord_20plugin_28',['The ord Plugin',['../ord.html',1,'']]],
  ['the_20program_29',['Iterating over the Program',['../dev.html#autotoc_md34',1,'']]],
  ['the_20refly_20plugin_30',['The refly Plugin',['../refly.html',1,'']]],
  ['the_20regex_20plugin_31',['The regex Plugin',['../regex.html',1,'']]],
  ['the_20rewrite_20does_32',['What the rewrite does',['../phases.html#autotoc_md74',1,'']]],
  ['the_20right_20base_20class_33',['Choosing the right base class',['../phases.html#autotoc_md76',1,'']]],
  ['the_20tensor_20plugin_34',['The tensor Plugin',['../tensor.html',1,'']]],
  ['the_20tuple_20plugin_35',['The tuple Plugin',['../tuple.html',1,'']]],
  ['the_20vec_20plugin_36',['The vec Plugin',['../vec.html',1,'']]],
  ['third_20party_20plugins_37',['Third-Party Plugins',['../coding.html#autotoc_md16',1,'']]],
  ['this_20split_20is_20useful_38',['Why this split is useful',['../phases.html#autotoc_md75',1,'']]],
  ['thresholded_20variants_39',['Thresholded Variants',['../dev.html#autotoc_md31',1,'']]],
  ['to_20immutables_40',['Downcast to Immutables',['../dev.html#autotoc_md21',1,'']]],
  ['to_20longjmp_41',['Operations related to longjmp',['../clos.html#autotoc_md116',1,'']]],
  ['to_20mutables_42',['Downcast to Mutables',['../dev.html#autotoc_md22',1,'']]],
  ['todo_20list_43',['Todo List',['../todo.html',1,'']]],
  ['trait_44',['%core.trait',['../core.html#autotoc_md150',1,'']]],
  ['translations_45',['Registered translations',['../autodiff.html#autotoc_md111',1,'']]],
  ['transpose_46',['transpose',['../tensor.html#autotoc_md306',1,'%tensor.transpose'],['../matrix.html#autotoc_md224',1,'transpose']]],
  ['tri_47',['%math.tri',['../math.html#autotoc_md195',1,'']]],
  ['triggering_20breakpoints_20from_20the_20command_20line_48',['Triggering Breakpoints from the Command Line',['../coding.html#autotoc_md12',1,'']]],
  ['tuple_20cat_49',['%tuple.cat',['../tuple.html#autotoc_md317',1,'']]],
  ['tuple_20contains_50',['%tuple.contains',['../tuple.html#autotoc_md318',1,'']]],
  ['tuple_20plugin_51',['The tuple Plugin',['../tuple.html',1,'']]],
  ['tuple_20typecat_52',['%tuple.typecat',['../tuple.html#autotoc_md316',1,'']]],
  ['tuple_20zip_53',['%tuple.zip',['../tuple.html#autotoc_md319',1,'']]],
  ['tuples_20arrays_20and_20products_54',['Tuples, arrays, and products',['../langref.html#autotoc_md48',1,'']]],
  ['type_55',['%refly.type',['../refly.html#autotoc_md273',1,'']]],
  ['typecat_56',['%tuple.typecat',['../tuple.html#autotoc_md316',1,'']]],
  ['types_57',['Types',['../gpu.html#autotoc_md162',1,'Memory Types'],['../gpu.html#autotoc_md163',1,'Pointer Types'],['../autodiff.html#autotoc_md103',1,'Types'],['../compile.html#autotoc_md121',1,'Types'],['../gpu.html#autotoc_md160',1,'Types'],['../math.html#autotoc_md190',1,'Types'],['../matrix.html#autotoc_md210',1,'Types'],['../mem.html#autotoc_md230',1,'Types'],['../ord.html#autotoc_md253',1,'Types'],['../refly.html#autotoc_md268',1,'Types'],['../regex.html#autotoc_md284',1,'Types'],['../tensor.html#autotoc_md302',1,'Types']]],
  ['types_58',['types',['../langref.html#autotoc_md54',1,'Function types'],['../langref.html#autotoc_md45',1,'Kinds and builtin types'],['../langref.html#autotoc_md50',1,'Summary: Functions and types']]],
  ['typical_20shape_59',['Typical Shape',['../phases.html#autotoc_md60',1,'Typical Shape'],['../phases.html#autotoc_md67',1,'Typical Shape'],['../phases.html#autotoc_md69',1,'Typical Shape']]],
  ['typical_20usage_60',['Typical Usage',['../phases.html#autotoc_md68',1,'Typical Usage'],['../rewriting.html#autotoc_md93',1,'Typical Usage'],['../rewriting.html#autotoc_md95',1,'Typical Usage']]]
];
