var searchData=
[
  ['dbg_0',['%refly.dbg',['../refly.html#autotoc_md279',1,'']]],
  ['debugging_1',['Debugging',['../coding.html',1,'Coding &amp; Debugging'],['../coding.html#autotoc_md7',1,'Debugging']]],
  ['debugging_20features_2',['Debugging Features',['../cli.html#clidebug',1,'']]],
  ['declarations_3',['Declarations',['../langref.html#decl',1,'Declarations'],['../langref.html#autotoc_md50',1,'Declarations']]],
  ['demo_20const_5fidx_4',['%demo.const_idx',['../demo.html#autotoc_md158',1,'']]],
  ['demo_20plugin_5',['The demo Plugin',['../demo.html',1,'']]],
  ['dependencies_6',['Dependencies',['../coding.html#autotoc_md1',1,'Dependencies'],['../affine.html#autotoc_md101',1,'Dependencies'],['../autodiff.html#autotoc_md106',1,'Dependencies'],['../clos.html#autotoc_md119',1,'Dependencies'],['../core.html#autotoc_md135',1,'Dependencies'],['../direct.html#autotoc_md159',1,'Dependencies'],['../gpu.html#autotoc_md163',1,'Dependencies'],['../matrix.html#autotoc_md213',1,'Dependencies'],['../mem.html#autotoc_md233',1,'Dependencies'],['../opt.html#autotoc_md253',1,'Dependencies'],['../ord.html#autotoc_md256',1,'Dependencies'],['../refly.html#autotoc_md271',1,'Dependencies'],['../regex.html#autotoc_md287',1,'Dependencies'],['../tensor.html#autotoc_md305',1,'Dependencies'],['../tuple.html#autotoc_md318',1,'Dependencies'],['../vec.html#autotoc_md324',1,'Dependencies']]],
  ['deprecated_20list_7',['Deprecated List',['../deprecated.html',1,'']]],
  ['design_20pattern_8',['Recommended design pattern',['../phases.html#autotoc_md76',1,'']]],
  ['developer_20guide_9',['Developer Guide',['../dev.html',1,'']]],
  ['diff_10',['%vec.diff',['../vec.html#autotoc_md334',1,'']]],
  ['differentiation_20plugin_11',['The automatic differentiation Plugin',['../autodiff.html',1,'']]],
  ['direct_20cps2ds_12',['%direct.cps2ds',['../direct.html#autotoc_md161',1,'']]],
  ['direct_20style_20plugin_13',['The direct style Plugin',['../direct.html',1,'']]],
  ['discovery_14',['Third-Party Plugin Discovery',['../plugins.html#autotoc_md82',1,'']]],
  ['disj_15',['%regex.disj',['../regex.html#autotoc_md292',1,'']]],
  ['displaying_20dot_20graphs_16',['Displaying DOT Graphs',['../coding.html#autotoc_md9',1,'']]],
  ['div_17',['%core.div',['../core.html#autotoc_md146',1,'']]],
  ['does_18',['What the rewrite does',['../phases.html#autotoc_md73',1,'']]],
  ['dominance_19',['🪾 SSA without Dominance',['../index.html#autotoc_md91',1,'']]],
  ['dot_20graphs_20',['Displaying DOT Graphs',['../coding.html#autotoc_md9',1,'']]],
  ['dot_5fgeneral_21',['%tensor.dot_general',['../tensor.html#autotoc_md313',1,'']]],
  ['downcast_22',['General Downcast',['../dev.html#autotoc_md19',1,'']]],
  ['downcast_20to_20immutables_23',['Downcast to Immutables',['../dev.html#autotoc_md20',1,'']]],
  ['downcast_20to_20mutables_24',['Downcast to Mutables',['../dev.html#autotoc_md21',1,'']]],
  ['downcasts_20for_20built_20ins_25',['Downcasts for Built-ins',['../dev.html#cast_builtin',1,'']]],
  ['doxygen_20style_26',['Doxygen Style',['../coding.html#autotoc_md5',1,'']]],
  ['dumping_27',['Dumping',['../coding.html#autotoc_md8',1,'']]]
];
