var searchData=
[
  ['capacity_0',['Capacity',['../ord.html#autotoc_md263',1,'']]],
  ['casts_1',['Further Casts',['../dev.html#autotoc_md23',1,'']]],
  ['cat_2',['%tuple.cat',['../tuple.html#autotoc_md321',1,'']]],
  ['catching_20exceptions_3',['Catching Exceptions',['../coding.html#autotoc_md11',1,'']]],
  ['check_4',['%refly.check',['../refly.html#autotoc_md282',1,'']]],
  ['choosing_20the_20right_20base_20class_5',['Choosing the right base class',['../phases.html#autotoc_md75',1,'']]],
  ['class_6',['Choosing the right base class',['../phases.html#autotoc_md75',1,'']]],
  ['cleanup_7',['Cleanup',['../phases.html#autotoc_md63',1,'']]],
  ['clos_20plugin_8',['The clos Plugin',['../clos.html',1,'']]],
  ['closedmutphase_9',['ClosedMutPhase',['../phases.html#phases_closed_mut_phase',1,'']]],
  ['closure_20attribute_10',['Closure Attribute',['../clos.html#autotoc_md121',1,'']]],
  ['cls_11',['%regex.cls.*',['../regex.html#autotoc_md298',1,'']]],
  ['cmake_20style_12',['CMake Style',['../coding.html#autotoc_md3',1,'']]],
  ['cmp_13',['%math.cmp',['../math.html#autotoc_md208',1,'']]],
  ['coding_20debugging_14',['Coding &amp;amp; Debugging',['../coding.html',1,'']]],
  ['coding_20style_15',['Coding Style',['../coding.html#autotoc_md2',1,'']]],
  ['command_20line_16',['Triggering Breakpoints from the Command Line',['../coding.html#autotoc_md14',1,'']]],
  ['command_20line_20reference_17',['Command-Line Reference',['../cli.html',1,'']]],
  ['comments_18',['Comments',['../langref.html#autotoc_md39',1,'']]],
  ['community_19',['💬 Community',['../index.html#autotoc_md93',1,'']]],
  ['compile_20is_5floaded_20',['%compile.is_loaded',['../compile.html#autotoc_md128',1,'']]],
  ['compile_20pass_20compile_20phase_21',['%compile.Pass / %compile.Phase',['../compile.html#autotoc_md126',1,'']]],
  ['compile_20passes_22',['%compile.phases / %compile.passes',['../compile.html#autotoc_md130',1,'']]],
  ['compile_20phase_23',['%compile.Pass / %compile.Phase',['../compile.html#autotoc_md126',1,'']]],
  ['compile_20phases_20compile_20passes_24',['%compile.phases / %compile.passes',['../compile.html#autotoc_md130',1,'']]],
  ['compile_20plugin_25',['The compile Plugin',['../compile.html',1,'']]],
  ['computes_26',['What the analysis computes',['../phases.html#autotoc_md72',1,'']]],
  ['conditional_20breakpoints_27',['Conditional Breakpoints',['../coding.html#autotoc_md10',1,'']]],
  ['conj_28',['%regex.conj',['../regex.html#autotoc_md291',1,'']]],
  ['const_29',['%matrix.const',['../matrix.html#autotoc_md219',1,'']]],
  ['const_5fidx_30',['%demo.const_idx',['../demo.html#autotoc_md158',1,'']]],
  ['constructors_31',['Constructors',['../compile.html#autotoc_md129',1,'Constructors'],['../ord.html#autotoc_md260',1,'Constructors']]],
  ['contains_32',['contains',['../ord.html#autotoc_md268',1,'%ord.contains'],['../tuple.html#autotoc_md322',1,'%tuple.contains']]],
  ['conv_33',['conv',['../core.html#autotoc_md151',1,'%core.conv'],['../math.html#autotoc_md209',1,'%math.conv']]],
  ['conversions_34',['Conversions',['../core.html#autotoc_md150',1,'']]],
  ['copy_5fto_5fdevice_35',['%gpu.copy_to_device',['../gpu.html#autotoc_md177',1,'']]],
  ['copy_5fto_5fdevice_5fasync_36',['%gpu.copy_to_device_async',['../gpu.html#autotoc_md183',1,'']]],
  ['copy_5fto_5fhost_37',['%gpu.copy_to_host',['../gpu.html#autotoc_md178',1,'']]],
  ['copy_5fto_5fhost_5fasync_38',['%gpu.copy_to_host_async',['../gpu.html#autotoc_md184',1,'']]],
  ['core_20abs_39',['%core.abs',['../core.html#autotoc_md149',1,'']]],
  ['core_20bit1_40',['%core.bit1',['../core.html#autotoc_md142',1,'']]],
  ['core_20bit2_41',['%core.bit2',['../core.html#autotoc_md143',1,'']]],
  ['core_20bitcast_42',['%core.bitcast',['../core.html#autotoc_md152',1,'']]],
  ['core_20conv_43',['%core.conv',['../core.html#autotoc_md151',1,'']]],
  ['core_20div_44',['%core.div',['../core.html#autotoc_md146',1,'']]],
  ['core_20extrema_45',['%core.extrema',['../core.html#autotoc_md148',1,'']]],
  ['core_20icmp_46',['%core.icmp',['../core.html#autotoc_md147',1,'']]],
  ['core_20icmp_20xygle_20eq_47',['%core.icmp.xYgLE (eq)',['../autodiff.html#autotoc_md116',1,'']]],
  ['core_20idx_48',['%core.idx',['../core.html#autotoc_md141',1,'']]],
  ['core_20nat_49',['%core.nat',['../core.html#autotoc_md137',1,'']]],
  ['core_20ncmp_50',['%core.ncmp',['../core.html#autotoc_md138',1,'']]],
  ['core_20pe_51',['%core.pe',['../core.html#autotoc_md155',1,'']]],
  ['core_20plugin_52',['The core Plugin',['../core.html',1,'']]],
  ['core_20select_53',['%core.select',['../core.html#autotoc_md156',1,'']]],
  ['core_20shr_54',['%core.shr',['../core.html#autotoc_md144',1,'']]],
  ['core_20trait_55',['%core.trait',['../core.html#autotoc_md154',1,'']]],
  ['core_20wrap_56',['%core.wrap',['../core.html#autotoc_md145',1,'']]],
  ['core_20wrap_20add_57',['%core.wrap.add',['../autodiff.html#autotoc_md117',1,'']]],
  ['core_20wrap_20mul_58',['%core.wrap.mul',['../autodiff.html#autotoc_md118',1,'']]],
  ['cpp_59',['&lt;span class=&quot;tt&quot;&gt;sccp.cpp&lt;/span&gt;',['../phases.html#autotoc_md71',1,'']]],
  ['cps2ds_60',['%direct.cps2ds',['../direct.html#autotoc_md161',1,'']]],
  ['create_61',['%ord.create',['../ord.html#autotoc_md262',1,'']]],
  ['create_20a_20new_20in_20tree_20plugin_62',['Create a New In-Tree Plugin',['../plugins.html#autotoc_md79',1,'']]],
  ['create_20a_20standalone_20third_20party_20plugin_63',['Create a Standalone Third-Party Plugin',['../plugins.html#autotoc_md80',1,'']]]
];
