var searchData=
[
  ['m_0',['%mem.M',['../mem.html#memM',1,'']]],
  ['malloc_1',['%mem.malloc',['../mem.html#autotoc_md242',1,'']]],
  ['manipulate_2',['Manipulate',['../refly.html#autotoc_md283',1,'']]],
  ['map_3',['%ord.Set / %ord.Map',['../ord.html#autotoc_md259',1,'']]],
  ['map_5freduce_4',['%tensor.map_reduce',['../tensor.html#autotoc_md317',1,'']]],
  ['markdown_20style_5',['Markdown Style',['../coding.html#autotoc_md4',1,'']]],
  ['mat_6',['%matrix.Mat',['../matrix.html#autotoc_md215',1,'']]],
  ['matching_20axioms_7',['Matching Axioms',['../dev.html#cast_axm',1,'']]],
  ['matching_20ir_8',['Matching IR',['../dev.html#autotoc_md18',1,'']]],
  ['matching_20literals_9',['Matching Literals',['../dev.html#cast_lit',1,'']]],
  ['math_20abs_10',['%math.abs',['../math.html#autotoc_md205',1,'']]],
  ['math_20arith_11',['%math.arith',['../math.html#autotoc_md197',1,'']]],
  ['math_20cmp_12',['%math.cmp',['../math.html#autotoc_md208',1,'']]],
  ['math_20conv_13',['%math.conv',['../math.html#autotoc_md209',1,'']]],
  ['math_20er_14',['%math.er',['../math.html#autotoc_md203',1,'']]],
  ['math_20exp_15',['%math.exp',['../math.html#autotoc_md202',1,'']]],
  ['math_20extrema_16',['%math.extrema',['../math.html#autotoc_md198',1,'']]],
  ['math_20f_17',['%math.F',['../math.html#autotoc_md195',1,'']]],
  ['math_20gamma_18',['%math.gamma',['../math.html#autotoc_md204',1,'']]],
  ['math_20plugin_19',['The math Plugin',['../math.html',1,'']]],
  ['math_20pow_20',['%math.pow',['../math.html#autotoc_md200',1,'']]],
  ['math_20round_21',['%math.round',['../math.html#autotoc_md206',1,'']]],
  ['math_20rrt_22',['%math.rrt',['../math.html#autotoc_md212',1,'']]],
  ['math_20rt_23',['%math.rt',['../math.html#autotoc_md201',1,'']]],
  ['math_20sgn_24',['%math.sgn',['../math.html#autotoc_md211',1,'']]],
  ['math_20slf_25',['%math.slf',['../math.html#autotoc_md210',1,'']]],
  ['math_20tri_26',['%math.tri',['../math.html#autotoc_md199',1,'']]],
  ['matrix_20const_27',['%matrix.const',['../matrix.html#autotoc_md219',1,'']]],
  ['matrix_20init_28',['%matrix.init',['../matrix.html#autotoc_md224',1,'']]],
  ['matrix_20insert_29',['%matrix.insert',['../matrix.html#autotoc_md222',1,'']]],
  ['matrix_20mat_30',['%matrix.Mat',['../matrix.html#autotoc_md215',1,'']]],
  ['matrix_20operations_31',['High-level matrix operations',['../matrix.html#autotoc_md225',1,'']]],
  ['matrix_20plugin_32',['The matrix Plugin',['../matrix.html',1,'']]],
  ['matrix_20read_33',['%matrix.read',['../matrix.html#autotoc_md220',1,'']]],
  ['matrix_20shape_34',['%matrix.shape',['../matrix.html#autotoc_md217',1,'']]],
  ['mem_20alloc_35',['%mem.alloc',['../mem.html#autotoc_md240',1,'']]],
  ['mem_20free_36',['%mem.free',['../mem.html#autotoc_md243',1,'']]],
  ['mem_20lea_37',['%mem.lea',['../mem.html#autotoc_md246',1,'']]],
  ['mem_20load_38',['%mem.load',['../mem.html#autotoc_md237',1,'']]],
  ['mem_20m_39',['%mem.M',['../mem.html#memM',1,'']]],
  ['mem_20malloc_40',['%mem.malloc',['../mem.html#autotoc_md242',1,'']]],
  ['mem_20mslot_41',['%mem.mslot',['../mem.html#autotoc_md244',1,'']]],
  ['mem_20plugin_42',['The mem Plugin',['../mem.html',1,'']]],
  ['mem_20ptr_43',['%mem.Ptr',['../mem.html#autotoc_md235',1,'']]],
  ['mem_20remem_44',['%mem.remem',['../mem.html#autotoc_md239',1,'']]],
  ['mem_20reshape_45',['mem.reshape',['../mem.html#autotoc_md251',1,'']]],
  ['mem_20slot_46',['%mem.slot',['../mem.html#autotoc_md241',1,'']]],
  ['mem_20store_47',['%mem.store',['../mem.html#autotoc_md238',1,'']]],
  ['memory_20operations_48',['Memory Operations',['../gpu.html#autotoc_md180',1,'Asynchronous Memory Operations'],['../gpu.html#autotoc_md174',1,'Blocking Memory Operations']]],
  ['memory_20types_49',['Memory Types',['../gpu.html#autotoc_md166',1,'']]],
  ['meta_50',['Meta',['../regex.html#autotoc_md290',1,'']]],
  ['mim_51',['🐉 Naming: MimIR vs Mim',['../index.html#autotoc_md92',1,'']]],
  ['mim_20language_20reference_52',['Mim Language Reference',['../langref.html',1,'']]],
  ['mimir_53',['MimIR',['../index.html#autotoc_md85',1,'💡 Why MimIR?'],['../index.html',1,'MimIR']]],
  ['mimir_20vs_20mim_54',['🐉 Naming: MimIR vs Mim',['../index.html#autotoc_md92',1,'']]],
  ['minimal_20examples_55',['Minimal examples',['../phases.html#autotoc_md77',1,'']]],
  ['mode_56',['Mode',['../core.html#autotoc_md140',1,'']]],
  ['model_57',['Execution Model',['../phases.html#autotoc_md62',1,'']]],
  ['modifiers_58',['Modifiers',['../ord.html#autotoc_md269',1,'Modifiers'],['../vec.html#autotoc_md333',1,'Modifiers']]],
  ['module_59',['Module',['../langref.html#module',1,'']]],
  ['mslot_60',['%mem.mslot',['../mem.html#autotoc_md244',1,'']]],
  ['mul_61',['%core.wrap.mul',['../autodiff.html#autotoc_md118',1,'']]],
  ['mutables_62',['Mutables',['../dev.html#autotoc_md21',1,'Downcast to Mutables'],['../dev.html#mut',1,'Immutables vs. Mutables']]]
];
