from __future__ import annotations
import os
import typing
__all__: list[str] = ['AST', 'Debug', 'Def', 'Driver', 'Error', 'Flags', 'Info', 'Lam', 'Level', 'Lit', 'Log', 'MIM_Error', 'Parser', 'Pi', 'PyParser', 'PyWorld', 'Sym', 'SymPool', 'Verbose', 'Warn', 'World']
class AST:
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: World) -> None:
        ...
class Def:
    def dump(self) -> None:
        ...
    def externalize(self) -> None:
        ...
    def num_projs(self) -> int:
        ...
    @typing.overload
    def proj(self, arg0: int, arg1: int) -> Def:
        ...
    @typing.overload
    def proj(self, arg0: int) -> Def:
        ...
    def projs(self, arg0: int) -> list[Def]:
        ...
    def set(self, arg0: str) -> Def:
        ...
    def var(self) -> Def:
        ...
class Driver(SymPool):
    def __init__(self) -> None:
        ...
    def add_import(self, arg0: str, arg1: str) -> os.PathLike:
        ...
    def add_search_path(self, arg0: os.PathLike) -> None:
        ...
    def backend(self, arg0: str, arg1: str, arg2: World) -> None:
        ...
    def load_pluins(self, arg0: list[str]) -> None:
        ...
    def log(self) -> ...:
        ...
    def world(self) -> World:
        ...
class Flags:
    dump_grid: int
    scalarize_threshhold: int
    def __init__(self) -> None:
        ...
class Lam(Def):
    def app(self, arg0: bool, arg1: Def, arg2: list[Def]) -> Lam:
        ...
    def externalize(self) -> None:
        ...
    def var(self) -> Def:
        ...
class Level:
    """
    Members:
    
      Error
    
      Warn
    
      Info
    
      Verbose
    
      Debug
    """
    Debug: typing.ClassVar[Level]  # value = <Level.Debug: 4>
    Error: typing.ClassVar[Level]  # value = <Level.Error: 0>
    Info: typing.ClassVar[Level]  # value = <Level.Info: 2>
    Verbose: typing.ClassVar[Level]  # value = <Level.Verbose: 3>
    Warn: typing.ClassVar[Level]  # value = <Level.Warn: 1>
    __members__: typing.ClassVar[dict[str, Level]]  # value = {'Error': <Level.Error: 0>, 'Warn': <Level.Warn: 1>, 'Info': <Level.Info: 2>, 'Verbose': <Level.Verbose: 3>, 'Debug': <Level.Debug: 4>}
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: int) -> None:
        ...
    def __int__(self) -> int:
        ...
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: int) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class Lit(Def):
    pass
class Log:
    def __init__(self, arg0: ...) -> None:
        ...
    def set(self, arg0: ...) -> Log:
        ...
    def set_stdout(self) -> Log:
        ...
class MIM_Error(Exception):
    pass
class Parser:
    def __init__(self, arg0: AST) -> None:
        ...
    def plugin(self, arg0: str) -> None:
        ...
class Pi(Def):
    pass
class PyParser:
    def __init__(self, arg0: Parser) -> None:
        ...
    def plugin(self, arg0: str) -> None:
        ...
class PyWorld:
    def __init__(self, arg0: World) -> None:
        ...
    def annex(self, arg0: Sym) -> Def:
        ...
    def implicit_app(self, arg0: Def, arg1: list[Def]) -> Def:
        ...
    def mut_fun(self, arg0: Def, arg1: list[Def]) -> ...:
        ...
    def sym(self, arg0: str) -> Sym:
        ...
    def type_i32(self) -> Def:
        ...
    def write(self) -> None:
        ...
class Sym:
    def __init__(self) -> None:
        ...
    def empty(self) -> bool:
        ...
    def size(self) -> int:
        ...
    def str(self) -> str:
        ...
    def view(self) -> str:
        ...
class SymPool:
    def __init__(self) -> None:
        ...
    @typing.overload
    def sym(self, arg0: str) -> Sym:
        ...
    @typing.overload
    def sym(self, arg0: str) -> Sym:
        ...
    @typing.overload
    def sym(self, arg0: str) -> Sym:
        ...
class World:
    def annex(self, arg0: ...) -> ...:
        ...
    def annex_by_id(self, arg0: int) -> ...:
        ...
    def arr(self, arg0: ..., arg1: ...) -> ...:
        ...
    def call_by_id(self, sym: int, args: list[...] = []) -> ...:
        ...
    def cn(self, arg0: list[...]) -> ...:
        ...
    def dot(self, arg0: str, arg1: bool, arg2: bool) -> None:
        ...
    def implicit_app(self, arg0: ..., arg1: list[...]) -> ...:
        ...
    def lit(self, arg0: ..., arg1: int) -> ...:
        ...
    def lit_i8(self, arg0: int) -> ...:
        ...
    def lit_nat_0(self) -> ...:
        ...
    def mut_con(self, arg0: list[...]) -> ...:
        ...
    def mut_fun(self, arg0: ..., arg1: list[...]) -> ...:
        ...
    def mut_fun2(self, arg0: list[...], arg1: list[...]) -> ...:
        ...
    def optimize(self) -> None:
        ...
    def sym(self, arg0: str) -> ...:
        ...
    def top_nat(self) -> ...:
        ...
    def type_bool(self) -> ...:
        ...
    def type_i32(self) -> ...:
        ...
    def type_i8(self) -> ...:
        ...
    @typing.overload
    def type_idx(self, arg0: ...) -> ...:
        ...
    @typing.overload
    def type_idx(self, arg0: int) -> ...:
        ...
    def write(self) -> None:
        ...
Debug: Level  # value = <Level.Debug: 4>
Error: Level  # value = <Level.Error: 0>
Info: Level  # value = <Level.Info: 2>
Verbose: Level  # value = <Level.Verbose: 3>
Warn: Level  # value = <Level.Warn: 1>
