name: build-and-test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build-and-test:
    name: Build and test on ${{matrix.os}} in ${{matrix.build-type}} mode
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        build-type: [Debug, Release]
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Set up Clang
      uses: egor-tensin/setup-clang@v1
      if: matrix.os == 'ubuntu-latest'
      with:
        version: latest
        platform: x64

    - name: Configure
      run: >
        cmake 
        -B ${{github.workspace}}/build 
        -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build/bin
      run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure
